### ISSUE TITLE
READ THIS: File engine issues on minetest

### ISSUE THREAD

**Issue by celeron55** [minetest/minetest_game#1]
Only file issues in here which *specifically* affect *only* minetest_game. If you are not sure, file them on minetest.

Issues related to the engine go here: https://github.com/minetest/minetest/issues

**Comment by asl97** [comment]
this should really be in a `CONTRIBUTING.md`
how many people actually see this?

**Comment by paramat** [comment]
This is in issues so is in the correct place, although of course rarely seen at the end of the list.
Perhaps we can remove?

**Comment by celeron55** [comment]
I agree that if there was a `CONTRIBUTING.md`, this should be there. There isn't one though so that's a bit of an issue? 8)

**Comment by asl97** [comment]
it's not that hard to create the file and there isn't really any reason against creating it
https://github.com/minetest/minetest_game/compare/master...asl97:patch-3

**Comment by paramat** [comment]
I vote we delete this issue as it's never seen at the end of the list.

**Comment by asl97** [comment]
@paramat there is no way to delete an issue, you can only close it (unless you count deleting the whole repo and recreating it).

**Comment by paramat** [comment]
Yes indded i mean close it.

**Comment by paramat** [comment]
sfan5 agreed to close this.
