### ISSUE TITLE
Fences don't connect two blocks

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest_game#1004]
Fences don't connect to blocks this is extremely frustrating if I'm trying to build

**Comment by RHRhino** [comment]
Fences aren't supposed to connect to every block. It's also impossible to find a solution for your problem, if you don't give any useful descripting e.g. to which blocks are fences not connecting although they should.

**Comment by Kinokoio** [comment]
@tobyplowy you should check how to write proper bugs, this is not really clear about what do you want to report as a bug. 

For what I have been testing, fences only connect to other fence blocks not, opaque blocks. I don't know if it would be good to implement, though.

**Comment by sofar** [comment]
The connected fence nodes I recently introduced connect to almost all wood blocks, making it reasonably connecting enough. If you want fences connect to other nodes as well, I suggest working on an extended fence mod that adds the connections that you want. With ```minetest.override``` it is really trivial to do this, as you only need to modify the ```connects_to``` property.

**Comment by tobyplowy** [comment]
I don't know how to write code I'm just here to report problems

**Comment by sofar** [comment]
>I don't know how to write code I'm just here to report problems

I'm writing it because the list of nodes that fences connect to was carefully chosen, and I don't see it getting changed.

So you're reporting something that isn't a bug, and therefore it's an enhancement or feature request. And it's highly unlikely that it will get implemented, as I don't think there is enough support for, not would I support it, either.

**Comment by tobyplowy** [comment]
# sofar I just don't understand why fences don't connect to All blocks

**Comment by tobyplowy** [comment]
This is a little side question and has nothing to do with this topic but I just want to know will stairs have corner pieces like this http://i.imgur.com/a65gO.png

**Comment by C1ffisme** [comment]
@tobyplowy Why don't you open that up as a different feature request?

Fences connect to wooden items. That's it. Why would fences connect to stone items? You can't hammer nails into stone.

**Comment by paramat** [comment]
The fence behaviour is intentional and accepted by the devs.
You can open a new issue requesting stair corners.
