### ISSUE TITLE
Liquids over snow nodes and nodeboxes

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1005]
I've noticed that lava over snow block/nodebox does not affect it in any way, liquids over nodeboxes look incorrect (it is designed that way, I know).
Example:
![fypznfi](https://cloud.githubusercontent.com/assets/16494741/14210938/ff3fafc6-f833-11e5-9b27-683ff89977f0.png)

Any workarounds/fixes viable?

**Comment by sofar** [comment]
since we already have a ```group:flammable``` we should probably add a ```group:meltable``` and add an ABM that makes snow melt. Question is, does melting snow give water or make it disappear?

**Comment by tobyplowy** [comment]
#sofar I think it should disappear. otherwise you will get tons of cobblestone and obsidian its gonna Be a mess

**Comment by C1ffisme** [comment]
I think this has to do with being `floodable`.

Or at least, it would implement this better.

**Comment by paramat** [comment]
Making snow nodeboxes floodable would be simple and good enough, maybe snowblocks too? Water and lava would melt/vapourise snow.

**Comment by sofar** [comment]
@paramat I don't see why not, all of those suggestions sound entirely reasonable.

**Comment by tenplus1** [comment]
Wait for the on_flood function to become active and then things like snow can be dealt with easily.

**Comment by paramat** [comment]
>  I think it should disappear. otherwise you will get tons of cobblestone and obsidian its gonna Be a mess

I agree, lava would vapourise low density snow, so fllodable works for that.
Water tends to melt snow, no need to change snow to water because allowing the water to flood into snow has the same effect and copes with different types of water.
So 'floodable' works fine and avoids another ABM.
Fire next to snow or ice is extinguished, so having fire melt those is pointless, the idea is that the snow/ice is melted by the fire and extinguishes it.

**Comment by sofar** [comment]
Do we want lava to flood snow *blocks* and/or *ice* blocks? I'm cautious to do so, as it would make lava and water fall straight through glaciers, and I think it should turn to cobble instead, but maybe people disagree.

**Comment by sofar** [comment]
#1008

**Comment by Fixer-007** [comment]
Ok, so what about lava flooding ice and snow blocks, this part was left out...

**Comment by sofar** [comment]
perhaps just open a new issue? It seems the whole discussion in this thread is about the snow nodebox nodes.

**Comment by paramat** [comment]
If you make ice and snowblocks 'floodable' then water as well as lava will destroy these. I wouldn't want water destroying ice or snowblocks, water is often spilled and this would cause ugly bare patches in snow biomes and holes in ice..

**Comment by paramat** [comment]
Ok i know. Lava would melt ice or snwblock, which would then become water which would cool the lava, we can add ice and snowblock to the lavacooling ABM, simple and effective.

**Comment by Fixer-007** [comment]
@paramat Yeah, I guess this will be the simplest way.
