### ISSUE TITLE
Feature Request - Darker Value for Default Gravel Texture

### ISSUE THREAD

**Issue by LazyJ** [minetest/minetest_game#1010]
The somewhat recent change to the default gravel texture's value does not harmonize well with the other, default, gray stones in the default texture pack. The gravel is too light in value compared to the darker values of the default stone, cobblestone, and stonebrick. I realize that in real life, gravel comes in many different hues and values; however, for the sake of keeping the default texture pack looking homogeneous, I believe that the gravel texture should be darker than it currently is.

Below are two images, one with the current gravel; the other with the gravel's value darkened, and a link to the darker gravel texture's png file.

In the first image the grey stones, together, show that they suit each other more aesthetically than the current gravel texture to the right in the screenshot:

![Current default gravel texture compared to the other gray stones.](http://i.imgur.com/KY8bH39.png)

The stonebrick, in the middle of the screenshot, blends almost seamlessly with the stone. The cobblestone, to the left, appears darker because of the darker grout yet still gives the sense that it came from the stone because the cobblestone's value is not too far off from that of stone's value. The current gravel texture, to the right, doesn't fit in well with the other grey stones.

The second image is the same display examples but with the darker value gravel:

![Proposed darker value gravel texture.](http://i.imgur.com/XbjtLA9.png)

Here, the value spread between the various grey stones is similar enough to provide aesthetic harmony yet different enough to provide visual distinction.

Link to the darker value gravel texture, "default_gravel.png":  [http://i.imgur.com/XbjtLA9.png](http://i.imgur.com/XbjtLA9.png)

**Comment by DonBatman** [comment]
I agree

**Comment by tenplus1** [comment]
+1

**Comment by RHRhino** [comment]
Changing textures is very difficult, some people preffer darker other people lighter textures. We should try to have one consistent texturepack and rules how future textures have to look like to fit into it, otherwise we will change textures again and again.

**Comment by PilzAdam** [comment]
Why do you think that the gravel color should be similar to stone? The other materials you compare it with, cobble and stone bricks, are made out of stone, so it's logical that their color is similar to stone. Gravel is not made out of stone, so why should it look like stone? Wouldn't it be (visually) boring, if all gray-ish nodes would have the same tone of gray?

**Comment by paramat** [comment]
:-1: Too dark. Gravel is good light coloured, that was requested so that gravel beaches were not gloomy. Gravel tends to be more reflective as it is dust and smaller particles.

**Comment by LazyJ** [comment]
Two non-approvals by two core developers. Closing this issue.

**Comment by C1ffisme** [comment]
@LazyJ Too bad... That contrast looks ugly in my eyes.

@paramat To be fair, not all gravel is grey. What about making desert gravel? It could be more orange and yellow.

![default_desert_gravel](https://cloud.githubusercontent.com/assets/9893266/14258390/ed73760c-fa67-11e5-9799-e790b609b128.png)
![default_desert_gravel_big](https://cloud.githubusercontent.com/assets/9893266/14258392/eed14d3a-fa67-11e5-9800-e7c7d51d1cc7.png)

(Example Textures. Made for fun by myself.)

**Comment by red-001** [comment]
@PilzAdam  IRL gravel ***is*** stone.

**Comment by PilzAdam** [comment]
@red-001 I was talking about crafting relations. IRL there are thousands of different types of stone with a large variety of colors, while we have only 2 in this game.

**Comment by C1ffisme** [comment]
@PilzAdam We could add geology... But that's offtopic.

Just an idea.
