### ISSUE TITLE
Death on login [needs investigation]

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1012]
I'm very worried about one _critical_ bug that could be in MTG 0.4.14.
I'm not sure what the cause, but I've experienced death on login on two heavily modded server that uses recent minetest and minetest_game (Extreme Survival Minetest and Xanadu). Many players already confirmed this on both servers. @TenPlus1 is looking into it.
You login, instant death - spawn, you loose your bones.
Why I think it can be a MTG problem, ESM server run fine on older version (before that fancy stuff with gates, doors and stuff), but after update people on survival server started to die on login randomly. And now this problem also appeared on Xanadu.
From what I know, there was no such issue in sep 2015 build 64a5eec .
Could be possible related to changes to bones or to bubbles bug?

I'm not sure what is the cause, could be mods, but could be default mtg, and this is very bad and annoying bug. This needs investigation. Players hate it because you loose all your stuff.

**Comment by Dragonop** [comment]
I can confirm this happens every time I start a fresh world in MT Game, I instantly die as I spawn

**Comment by Fixer-007** [comment]
This is confirmed as engine issue, so I close it here :)
