### ISSUE TITLE
Fire is boring

### ISSUE THREAD

**Issue by PilzAdam** [minetest/minetest_game#1015]
I just tried to burn down a single apple tree. It took over 10 Minutes to burn down. This is extremely boring. Before @paramat came with all his "optimizations" you could burn down a complete forest in this time.

This also makes it way too easy for the player to fight a fire. The player has way too much time to remove a fire node before even a single burnable node nearby is destroyed.

I'm not asking to completely return to the old behavior, but it definitely can't stay the way it is currently.

**Comment by paramat** [comment]
Not a bug.
Forest fires can be a problem considering how dense and large forests are in the new biome system. It's good to have a chance to stop the spread.
If you test with a collection of trees it soon starts to spread fast, one tree will seem slow though due to having fewer nodes.
It does take a long time to burn out but that's due to how slowly the ABM removes flame nodes.
As i often write, it will inevitably be slow at first because spread speed is exponential.


I don't mind though, let's try chance 8 and chance 4, faster spread and faster burnout.

**Comment by sofar** [comment]
The flame removal should be a nodetimer, which is way more efficient and will reduce ABM load drastically, allowing for us to tune fire to burn faster.

#1001

**Comment by PilzAdam** [comment]
Not a feature request, obviously. Marked as bug because it's a regression in gameplay.

**Comment by 0-afflatus** [comment]
> Marked as bug because it's a regression in gameplay.

That's deliberately ignoring the wide range of differing opinions on the usefulness of fire. Many players and server owners feel that fire should be nerfed in multiplayer due to lag and griefing potential. I don't particularly like it either, but I can see that it is necessary.

**Comment by kilbith** [comment]
For such concern, disabling the mod is the best option for admins.

**Comment by sofar** [comment]
I'm strongly opposed to tuning minetest_game for multiplayer. It's entirely unsuitable for multiplayer without any mods or heavy tuning. Now we're nerfing the default singleplayer experience for no good reason.

**Comment by paramat** [comment]
It's not a bug, everything works fine and this was approved by other devs. You're just being provocative and doing this because you strongly dislike how it is.
I'm okay with not calling it a feature request as it isn't.
Remember i actually agree with you this can be sped up, i'll even make the PR, so you don't have to be confrontational.

**Comment by Ferk** [comment]
Maybe the fire mod should use some factor value settable in minetest.conf, so that people hosting servers can configure fire to be slow and boring if they want, but keep a fast and fun default for singleplayer.

**Comment by est31** [comment]
This is reigniting an old argument I had too when it was "optimized" in 0.4.13. I agree with @PilzAdam, fire doesn't do what fire does anymore, it just exists and bores.

And admins of multiplayer servers where keeping buildings is a priority should simply remove the mod, rather than keeping an almost-fixed vulnerability in the system.

**Comment by paramat** [comment]
I made it far too slow for 0.4.13 stable, it has been sped up twice since then, last time 18 days ago.

**Comment by kilbith** [comment]
Please keep in mind we need a fire that lasts quite longer for using in fireplaces or for boiling water in certain mods.

The burnability in <0.4.13 was so aggressive that it mades me think flammable nodes were soaked of fuel... IMO it's realistic enough as it is.

**Comment by DonBatman** [comment]
I actually fought forest fires. They burn for a long time. I think the time should stay as is.

**Comment by sofar** [comment]
>I actually fought forest fires. They burn for a long time. I think the
>time should stay as is.

This.

Don doesn't live to far from where I am. The fire season starts in a few weeks, and parts of this state will be burning until mid September.

Last year we logged a two acre part of forest. The slash piles burned for a week.

In minetest time that would be well over two hours of playing time to burn a 80x80 plot.

**Comment by 0-afflatus** [comment]
@sofar 
> I'm strongly opposed to tuning minetest_game for multiplayer. It's entirely unsuitable for multiplayer without any mods or heavy tuning. 
@est31 
> admins of multiplayer servers where keeping buildings is a priority should simply remove the mod
@kilbith 
> Please keep in mind we need a fire that lasts quite longer for using in fireplaces or for boiling water in certain mods.

Sofar's comment has given me a deeper understanding of this issue. While it is true that vanilla MTG isn't that suitable for multiplayer, I don't think it is at all valid to deny that it used as the core of a majority of multiplayer games and as the base for many subgames, which are essentially mods for multiplayer use. Kilbith's comment above is the clincher, removing fire is not really an option if you use other mods which depend on it. The `disable_fire` setting doesn't do what I want it to in multiplayer and my cauldron and bonfire mods rely on it to a certain extent, so I use a modified (nerfed) version of fire in my game. This makes the process of updating it more complicated, which isn't a big deal. I don't particularly wish to create a multiplayer fork of this mod, although I might consider that. It would be much more pleasant to have a specific setting for multiplayer use, then PilzAdam and sofar can have their exciting singleplayer fire-fighting experiences and those of us running servers can continue to use the same mod without constantly being told we should disable it. I'm not the first person to be confused by this somewhat paradoxical state of affairs and I don't suppose I shall be the last.

**Comment by Fixer-007** [comment]
When I last checked it looked find, yes, it can be slow at times, but performance is much-much better now.

**Comment by paramat** [comment]
#1017 is merged in modified form, flammable material burns away slightly faster, fire spread speed is unchanged.

**Comment by PilzAdam** [comment]
> flammable material burns away slightly faster, fire spread speed is unchanged

This is indeed what was bothering me the most. Fire spread was ok, but it burnt forever until the flammable nodes actually disappeared. Good fix.

**Comment by sofar** [comment]
I'm not in agreement here. It's statistically still probably that these flames will exist forever, and never get removed. The nodetimer approach in #1001 is a better solution.
