### ISSUE TITLE
Flint and steel wears out if not used

### ISSUE THREAD

**Issue by PilzAdam** [minetest/minetest_game#1016]
Flint and steel wears out, even if it doesn't create a fire node (i.e. you are pointing at a non burnable node).

Also, the control scheme to place fire with a leftclick is inconsistent with normal node behavior, where you place stuff in the world with a rightclick.

**Comment by rubenwardy** [comment]
you're using the item as a tool, rather than placing the item like a node

**Comment by kilbith** [comment]
Sorry, I just applied @paramat's request : https://github.com/minetest/minetest_game/pull/962#discussion_r56846667

> I think all attempts at ignition (on flammable or non flammable nodes) should add wear to the flint and steel

**Comment by paramat** [comment]
Makes sense as it is, if a player repeatedly tries to light a non-flammable node the flint and steel is being used, therefore wear. This is obvious, it's not a bug.

**Comment by paramat** [comment]
Closing as current behaviour seems acceptable to most.
