### ISSUE TITLE
Paging and title issues in the book formspec

### ISSUE THREAD

**Issue by Ferk** [minetest/minetest_game#1023]
![screenshot](http://i.imgur.com/nmPxLM7.png)

there are two issues in here:

1. The title gets cropped. Why not use a text area as well and make it able to wrap?

2. The textarea with the content is not paging it properly. In the screenshot I actually typed up to 40 lines with numbers, only 18 show and there's no 2nd page splitting it. It looks like the code splits pages based in the number of characters, not number of lines, this can result in missing lines when there's a number of newlines in the text, or when the window is resized to have less available space (or android screens). 

For the point 2, I guess there are 4 solutions I can think of:

1. Don't use textarea for the content, but something like labels or tables. This is the simplest but then we go back to not having word wrapping and breaking compatibility with old books.
2. Do not do automatic paging, instead just have also a "next/prev page" button for the player that writes the book and let him decide when a new page is needed. But this might also break compatibility.
3. Add in the engine textareas with scrollbars.
4. Detect properly where is the page split required (or the line split, if we wanted to instead add wrapping to the tables).. which I don't think is possible unless we were able to somehow obtain the dimensions of the window and it's relationship with the fontsize. I doubt the engine offers that. But maybe it could be added.

**Comment by kilbith** [comment]
> Why not use a text area as well and make it able to wrap?

Because `textarea` doesn't support colored text. Book titles are usually much shorter than in your screenshot. It's not worth it.

> The textarea with the content is not paging it properly.

This is not something new. You could as well get cropped with the duo `textarea` (author) / `field` (reader) in the original implementation (e.g. typing lots of empty newlines before writing text).

It's hard to count accurately the number of lines as it depends of your window resolution, font size or GUI scaling.

**Comment by kilbith** [comment]
> Do not do automatic paging, instead just have also a "next/prev page" button for the player that writes the book and let him decide when a new page is needed.

Seems the best solution but would require a limited size for the `textarea`.

**Comment by Ferk** [comment]
> limited size for the textarea.

That'd be nice. It would also help if the title input had a limit as well. Specially since books might end up having the title in the tooltip after https://github.com/minetest/minetest/pull/3449

**Comment by paramat** [comment]
#1024 is merged.
