### ISSUE TITLE
new cobblestone/mossycobblestone texture (textures inside)

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest_game#1026]
i didn't like the current cobblestone texture so i made a new one
(NOTE)i hope it looks good i did my best to mimic the minetest style 
![default_mossycobble](https://cloud.githubusercontent.com/assets/16853304/14436350/894dbf92-001c-11e6-8843-576590f2b548.png)
![default_cobble](https://cloud.githubusercontent.com/assets/16853304/14436351/8dcb273a-001c-11e6-819b-e80019c2948f.png)
![default_desert_cobble](https://cloud.githubusercontent.com/assets/16853304/14438271/86a9a504-0025-11e6-9574-bcdf1ec09679.png)
![cobble](https://cloud.githubusercontent.com/assets/16853304/14436542/7c5d3b36-001d-11e6-8571-b4999f8fd1a8.png)

**Comment by PilzAdam** [comment]
https://forum.minetest.net/viewforum.php?f=4

**Comment by tobyplowy** [comment]
@PilzAdam I don't understand what you trying to say?!?!?

**Comment by sofar** [comment]
I'm not making any judgement at this point, but if the cobble texture is going to be changed, then I insist that the desert cobble texture is included in the change.

**Comment by tobyplowy** [comment]
@sofar so is the cobbel texture good?

**Comment by sofar** [comment]
I think I was really clear when I said:

> I'm not making any judgement at this point

**Comment by tobyplowy** [comment]
@sofar hire its just a recolor but yeah
![default_desert_cobble](https://cloud.githubusercontent.com/assets/16853304/14438271/86a9a504-0025-11e6-9574-bcdf1ec09679.png)

**Comment by tobyplowy** [comment]
The original doesn't really look like cobblestone more like Red brick https://www.google.be/search?q=red+brick+wall&client=tablet-android-google&prmd=ivmn&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjdzJyDnofMAhULWBQKHYW5ARMQ_AUIBygB&biw=960&bih=600

**Comment by sofar** [comment]
Why isn't this a PR with the textures as a patch?

**Comment by tobyplowy** [comment]
@sofar what?

**Comment by sofar** [comment]
You made an issue. If you want to suggest a change, it should be a pull request.

**Comment by tobyplowy** [comment]
@sofar thanks for the help

**Comment by tobyplowy** [comment]
@sofar why are there things posted there from the past? I probably did something wrong

**Comment by C1ffisme** [comment]
Those textures look pretty good, but you should probably make a [pull request](https://help.github.com/articles/creating-a-pull-request/).

**Comment by tobyplowy** [comment]
@C1ffisme i did #1028

**Comment by PilzAdam** [comment]
@tobyplowy if you don't like the default textures, then you should create a texture pack.

**Comment by C1ffisme** [comment]
@tobyplowy I know. I commented.

@PilzAdam There isn't a reason not to discuss texture tweaks every now and then.

**Comment by PilzAdam** [comment]
@C1ffisme maybe people like you, who like unproductive discussions about anything, like this, but don't expect any further attention from devs.

**Comment by tobyplowy** [comment]
@C1ffisme @DonBatman hey guys sorry that I was gone for the night sorry that you guys have some trouble each other and sorry dat im a noob i can't program but I can do pixel art! :\ The comments From @PilzAdam  kind of Hurt Me and if this is the minetest Community I don't think I wanna help!

**Comment by tobyplowy** [comment]
I can't seem to find a way to make the pull request work :\

**Comment by sofar** [comment]
I recommend learning the git command and using that. Using the website is going to result in more trouble and has proven to be problematic for almost everyone.

**Comment by tobyplowy** [comment]
@sofar I think I've had enough and i Don't think Wanna Be part of this community :\

**Comment by sofar** [comment]
TBH the texture you made isn't bad at all. But don't let that stop you. Next time talk to me on IRC and I can help you out, there's better ways to start contributing.

If you think it's you, don't. Look up the gravel texture patch I did a while back, and look at how long it took to get merged. Just .. pick a different thing you'd like to contribute and try again.

**Comment by tobyplowy** [comment]
@sofar do you have a link to IRC what is IRC? Is there any other way to connect to you like Skype or fb

**Comment by asl97** [comment]
@tobyplowy IRC stands for Internet Relay Chat, google it if you want to find out more.

if you don't have an irc client, you can just use the webclient:
https://webchat.freenode.net/?channels=#minetest-dev

^ link from http://www.minetest.net/irc/

**Comment by C1ffisme** [comment]
> C1ffisme said:
> And then what? Will we still be a project for anyone to help develop? Or will people just get mad and want to fork us?

> tobyplowy said:
> I think I've had enough and i Don't think Wanna Be part of this community :\

My point exactly, @PilzAdam .

**Comment by tobyplowy** [comment]
@C1ffisme do you Blame me. I think looks ar as important as the game It Self looks ar Not unproductive!

**Comment by C1ffisme** [comment]
@tobyplowy No, I was pointing out to PilzAdam what can happen if people just start 'ignoring' other people.

**Comment by tobyplowy** [comment]
@C1ffisme thanks for doing dat Bdw The Conversation has moved to #1030

**Comment by tobyplowy** [comment]
@paramat thanks ;) bdw sorry for my late reply Have to Sleep jaknow :)

**Comment by paramat** [comment]
Discussion moved to #1030
