### ISSUE TITLE
Vessel shelf texture is "composed" but doesn't have alpha

### ISSUE THREAD

**Issue by sofar** [minetest/minetest_game#1027]
The vessel shelf texture is overlaid on top of default_wood.png. If the player is using a texture pack that isn't 16x16px, it looks weird:

![](https://i.imgur.com/yw2944z.png)

The reason is here:

https://github.com/minetest/minetest_game/blob/master/mods/vessels/init.lua#L18

Now, there is absolutely no reason for the shelf texture to be combined here, since it has no transparency. Without the "^" combination, the texture will stretch to the full block face.

**Comment by sofar** [comment]
Thanks to fixer for spotting the issue.

**Comment by Fixer-007** [comment]
I've actually seen very-very long ago, but don't remember where and why.

**Comment by C1ffisme** [comment]
Wouldn't most texture packs change the texture of the shelf as well?

Although, I suppose we should really fix that.

**Comment by sofar** [comment]
>Wouldn't most texture packs change the texture of the shelf as well?
>
>Although, I suppose we should really fix that.

There is nothing wrong with texture packs that only change some of the textures, and not all. In this case the vessels mod is doing something unneeded that is making it needlessly hard for texture pack makers.

**Comment by Fixer-007** [comment]
It is not only vessels btw.

**Comment by paramat** [comment]
+1 for removing the '^'.

**Comment by sofar** [comment]
#1031

**Comment by paramat** [comment]
#1031 is merged.
