### ISSUE TITLE
Slightly faster boat

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1033]
This was mentioned by sofar on IRC. Checking this, the boat has a maximum speed of 4.5 n/s, only slightly faster than walking speed of 4 n/s. I suggest 5 or 6? I don't think we should copy Minecraft and have an insanely fast boat.

**Comment by DonBatman** [comment]
I like the idea. Just a thought, can this be made into an api so we can have boats of different speeds? I am not asking for minetest_game too supply the boats. Just an easy way for mods to do it.

**Comment by paramat** [comment]
With some research, 5 m/s is roughly the world record average speed for a single racing rowboat over 2000m. Obviously our boat is a crude raft but speed in Minetest is exaggerated..

**Comment by paramat** [comment]
I think it's best mods provide boats with different speeds, for the MTGame boat i can't see a use for variable speed, as faster would be ridiculous and slower would be boring. I feel we should keep it simple and choose a reasonable top speed.
Faster boats probably deserve new models (sailboats, motorboats etc.) so i think are best done by mods.

**Comment by C1ffisme** [comment]
@paramat
> Also, our nodes are a little less than 1m

When I look around in Minetest, the blocks seem much too small to be a meter.

To me, it's more like 2.5 feet, maybe a yard, although that's an approximation. I haven't found the time to measure that distance.

Of course, it could be the fact that Minetest is on a screen... Or that my FOV is too low.

**Comment by Fixer-007** [comment]
Will it lag even more?

**Comment by paramat** [comment]
It won't lag more at 5n/s.
If you use the world averge height for a human and equate it to the height of Minetest plyer model (1.8m?) you can work it out. Someone has done this and it was something like 0.9m i can't remember.

**Comment by paramat** [comment]
I'll make a simple PR for 5 n/s.

**Comment by paramat** [comment]
See #1036

**Comment by paramat** [comment]
1036 is merged.
