### ISSUE TITLE
Grass: growing underwater?

### ISSUE THREAD

**Issue by sofar** [minetest/minetest_game#1045]
Reported on the forums:

https://forum.minetest.net/viewtopic.php?p=214824#p214824

It appears grass is growing back under water. We should likely check that dirt are not underneath a liquid node before allowing them to turn into dirt_with_*.

The old code had some more checks, perhaps we need to bring those back to remain consistent.

**Comment by paramat** [comment]
But our new code does have a check for air. Tenlplus1 has apparently changed this code on the server so it may be his problem.

**Comment by sofar** [comment]
I can't spot an error in the code either. Also, in the forum images, it's clear that it's a custom grass that is behaving like this.
