### ISSUE TITLE
Placing waterlily with a stack of 1 results in two visible lilies.

### ISSUE THREAD

**Issue by everamzah** [minetest/minetest_game#1046]
![screenshot_20160420_225033](https://cloud.githubusercontent.com/assets/1761623/14696635/d19d9742-074a-11e6-95c9-d9dd9bc2450f.png)

This visual glitch doesn't appear when there's a remaining stack of lilies.

**Comment by paramat** [comment]
@kilbith 
When waterlily is placed normally it does very briefly appear underwater then disappear.

**Comment by sofar** [comment]
it's probably placement prediction. Disabling it may be a better effect.

**Comment by kilbith** [comment]
I placed like ~500 lilies and I never seen that. I suspect he uses a different code. Anyways you know pertinently that : 

- It's not a bug, but the placement prediction (visible also when you place a lily onto a non-water node).
- It's not solvable in Minetest Game, if you believe it's a bug.

**Comment by kilbith** [comment]
It's certainly an engine bug, I could find a workaround in Minetest Game but not solving the root cause.

**Comment by paramat** [comment]
Workaround is fine for now. maybe we'll fix the engine issue during freeze.

**Comment by PilzAdam** [comment]
Disabling placement prediction for waterlilies seems fine.

**Comment by kilbith** [comment]
Solved with : https://github.com/minetest/minetest_game/pull/1048

**Comment by paramat** [comment]
Please keep this issue open until we fix the engine issues.

**Comment by paramat** [comment]
#1048 is merged.
