### ISSUE TITLE
Flint and Steel should ignite gunpowder and TNT

### ISSUE THREAD

**Issue by sofar** [minetest/minetest_game#1047]
This could even replace the torch method, entirely, making it a bit harder to use TNT. But for now I'd be just happy to see that we can use flint&steel to set off gunpowder and TNT.

@kilbith - do you have time?

**Comment by kilbith** [comment]
Isn't that https://github.com/minetest/minetest_game/pull/976 is meant for ?

**Comment by paramat** [comment]
:+1: But keep lighting by torch.
#976 has messy commits, maybe a new PR can be opened including the lighting of TNT?

**Comment by kilbith** [comment]
> #976 has messy commits

You can squash that. The code looks good to me (and it includes the lighting of TNT).

**Comment by paramat** [comment]
I might work on this, maybe include it in #1076

**Comment by paramat** [comment]
#1076 is merged.
