### ISSUE TITLE
It should be possible to break containers with items in it (like a chest and furnaces)

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest_game#1052]
If you try to break a chest with items in it, it won't break. This is really annoying if I'm trying to move my storage. (Basically, the way it should work is you break the chest, and all the items fall out of it.) It shouldn't be too hard to program because TNT can do this with chests. See #1039 but I'm not a programmer so I wouldn't know. :wink: ( @rubenwardy mentiond a take all and deposit all button its a extremely good idea. All credit to him).

**Comment by C1ffisme** [comment]
Um... I would probably fix that grammar. That is a pain to read.

But since you probably won't find the time to do it, I'll go ahead and correct you this one time so you can copy-paste.

> If you try to break a chest with items in it, it won't break. This is really annoying if I'm trying to move my storage. (Basically, the way it should work is you break the chest, and all the items fall out of it.) It shouldn't be too hard to program because TNT can do this with chests. See #1039 but I'm not a programmer so I wouldn't know. :wink: 

(:wink: = `:wink:`)

On topic, though, if items fell out of chests, that could be annoying if you axidentally break one (Spelling mistake intended, if you know what I mean.). 

![default_tool_diamondaxe](https://cloud.githubusercontent.com/assets/9893266/14755991/f2ecde64-08ab-11e6-805f-ead8c64e0ba8.png)

**Comment by stujones11** [comment]
> It should be possible to break containers with items in it

No, that should not be possible.

**Comment by tobyplowy** [comment]
@C1ffisme  Thank You For correcting me I'm really doing my best. I'm not a native English speaker  so yeah. Also lol

**Comment by tobyplowy** [comment]
@stujones11 could you please Explain why?

**Comment by rubenwardy** [comment]
It's too easy to it accidentally. A much better solution would be "take all" and "deposit all" buttons. Or maybe a mod adding a tool to destroy a chest with items in it.

**Comment by tobyplowy** [comment]
@rubenwardy actually the deposit and take all idea is extremely good. Why didn't I think of this myself?

**Comment by sofar** [comment]
With shift-clicking being available, I see little reason to clutter the UI with more buttons.

**Comment by tobyplowy** [comment]
@sofar yeah maybe you're right :cry:

**Comment by everamzah** [comment]
For what it's worth, @tobyplowy, if you're using X-Decor then the storage chests and shelves there will drop their contents when you break them.

**Comment by paramat** [comment]
:-1: We have shift-click.

**Comment by sofar** [comment]
I'm actually fairly positive to the idea that containers can be broken, but I wonder if it should be optional and not enabled by default.

**Comment by C1ffisme** [comment]
Shift click is great and all, but if I'm sorting through a large storage room full of chests, I don't want to click 24 times for each chest. Not only that, but your inventory has to be completely clear to empty the chest.

**Comment by sofar** [comment]
@C1ffisme that's because you're a hoarder. In seriousness, though, I don't think that is a good reason to add more buttons (just make a mod that adds chests with these buttons).

the shift-click problem is also offtopic. This PR is about breaking chests. I blame @rubenwardy :)

**Comment by paramat** [comment]
I'm neutral now.

**Comment by rubenwardy** [comment]
Why blame me?

**Comment by numberZero** [comment]
It would be a very nice feature, and it is the way things should work. But as some people dislike it, there should be an option to disable it.

**Comment by tobyplowy** [comment]
@C1ffisme @sofar @rubenwardy @paramat @stujones11 @numberZero 
Any last opinions about this I Guess this can be closed because No One Wants It ;)

**Comment by numberZero** [comment]
@tobyplowy Well, I want) But I think a mod can easily do that, so this can be closed.
Moreover, a mod can alter items in other mods as well, including e.g. `technic` machines, to achieve consistent behavior, without their support.

**Comment by Ferk** [comment]
The thing is that it would be possible for someone to create an indestructible cage made out of protected chests with each 1 cobblestone inside.
Seems weird.

It would make more sense to simply make them harder to break.

**Comment by paramat** [comment]
Issue is a year old. If someone wants this they have to code it or find someone who can.
Will close in 1 month.

**Comment by tobyplowy** [comment]
@paramat waw is been a year (time go's so fast) Well you can close if you want

**Comment by numberZero** [comment]
https://github.com/numberZero/chests

**Comment by Fixer-007** [comment]
>It's too easy to do it accidentally.

Doubt this, unless you walk with axe all day long. Breaking containers with items in it expose other minetest problem - picking items up is very cumbersome, there is no autopick up like in minetest.

**Comment by AntumDeluge** [comment]
Doesn't technic mod provide a wrench that allows you to pick up chests with all their contents?

**Comment by Fixer-007** [comment]
>Doesn't technic mod provide a wrench that allows you to pick up chests with all their contents?

Yes, you can only pick up your chests though.

**Comment by numberZero** [comment]
1. The wrench is not craftable (as it effectively gives infinite
inventory).
2. It lets you to pick up the whole chest as a single item, instead of
breaking it and taking everything it contained as separate items.
3. Not only players break nodes. But currently nonempty chests are
*totally* unbreakable.

**Comment by paramat** [comment]
If you break a chest and items drop out you have to pick them up which is much more fiddly than shift-clicking items into your inventory, so i can't see an advantage. I can't see good reason to add it as an option either. Not much support, even from author, so closing.
