### ISSUE TITLE
TNT should not effect non-physical objects

### ISSUE THREAD

**Issue by stujones11** [minetest/minetest_game#1053]
I recently ran into a situation where the entity part of a 'composite' node gets blown away by TNT

https://github.com/stujones11/minetest-3d_armor/issues/55

I have solved this with some hacks but I think that along with checking the `physical` property, it would be no big deal to check for an `on_blast` callback in the entity's definition.

I would make a PR but I am aware that others are working on this mod and I do not wish to waste any more of my time for it to be re-done by someone else.

**Comment by sofar** [comment]
Checking for the ```physical``` property seems reasonable.

I'd like to verify that this is a good selection criteria, though.

**Comment by sofar** [comment]
Looked into this. The ```physical``` property isn't usable for this purpose, as it's randomly enabled and disabled for things that TNT should really punch and/or move around.

I'd disable the punch for non-physical objects, but I'd still enable the knockback - blowing armor off your armor stands.

Maybe you can have the armor entities made so that they can be picked up?

**Comment by stujones11** [comment]
Knocking back non-physical objects makes absolutely no sense to me but I could live with a callback so that entities can at least override the effects in the same way that is possible for nodes.

> Maybe you can have the armor entities made so that they can be picked up?

I thought about that but it would be much easier if there was a way of knowing when the entity has been effected. I could, for example, destroy the entity and drop the individual items.

**Comment by PilzAdam** [comment]
IIRC dropped items disable `physical` if they are not moving.

**Comment by sofar** [comment]
I can see value in calling an entity ```on_blast()```. we could even have it return drops in case you want to remove the entity and drop an item. ```nil``` would signal to not damage or knock back the entity?

**Comment by stujones11** [comment]
At the risk of going a little off-topic, it is my opinion that the `on_blast` function(s) should be able to return `true` or `false` where if true it can allow the removal/knockback or abort when nil or false.

**Comment by sofar** [comment]
I don't see why that would be off-topic.

The problem with returning ```true``` is that you may actually want to drop items and get knocked back (but not take damage)

We can make it cover all the aspects by making something like this:

```(knockback, damage, drops) = obj.on_blast(intensity)```

**Comment by stujones11** [comment]
That would fine for entities if perhaps maybe a bit more complex than necessary. A simple `on_blast` function with the same functionality as the node equivalent would resolve this issue as far as I am concerned and should be fairly trivial to implement.

btw, I don't think you can call the method directly from the object reference like that. I think you'd have to either do `obj:get_luanentity()` or better still call it from the entity definition table like you do for nodes but I really don't mind how it works.

**Comment by sofar** [comment]
Nodes are way simpler: they can't move, and they are immortal per definition. Omitting these aspects from entities seems a mistake, and I'd hate to implement a spec that is fundamentally an oversight from the start.

**Comment by stujones11** [comment]
Okay, fair comment, so long as it is implemented somehow I will be happy :-)

**Comment by sofar** [comment]
I've submitted a change to not damage (punch) immortal entities, this should at least help somewhat. If you mark your armor stand entities as immortal, at least they can be picked up for now.

**Comment by stujones11** [comment]
Does this mean they still suffer the knockback? That is the biggest problem for me because I think they look silly just floating in mid-air and I'd also need to update the inventory of the node.
I can think of plenty workarounds but a simple `on_blast` callback would make life much easier.

**Comment by sofar** [comment]
@stujones11 not until the on_blast() callback gets added.

**Comment by stujones11** [comment]
As far as I am concerned this issue was resolved with #1060
