### ISSUE TITLE
Bad-looking pixel in torch texture

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest_game#1058]
The torch texture has an horrible pixel changing color from yellow, white-ish and then a very inappropriate black color.

I remember this texture was (lazily ?) scaled down from an HD texture by VanessaE. Its color palette is rather crappy.

![screenshot_20160425_132923](https://cloud.githubusercontent.com/assets/7883281/14782596/9ea0e404-0aea-11e6-895d-a2c533707e23.png)

Someone motivated enough to fix that or make a better torch texture ?

Cc: @paramat @sofar

**Comment by paramat** [comment]
The pixel 1-right 1-down has a better cycle that could perhaps be partly sampled across to replace the black part of the bad pixel's cycle. Maybe something for after release.

**Comment by C1ffisme** [comment]
Animating a torch is hard. I still can't make that good of a fire texture.

![kiln_active](https://cloud.githubusercontent.com/assets/9893266/14823701/145dcf1e-0b99-11e6-8864-35639094fcfe.png)

That's my best fire texture, anyway. Thought I'd just show it.

**Comment by kilbith** [comment]
A maintainer for deleting the umpteenth C1ffisme's offtopic comment, please.

**Comment by paramat** [comment]
C1ffisme that's a random comment best left to forum chat.

**Comment by Fixer-007** [comment]
Why not to rework them or make 3d? Default one looks crappy for sure.

**Comment by sofar** [comment]
That's why I've been maintaining a torches mod. It could replace default torches at one point. I took out all the fluff.

**Comment by tobyplowy** [comment]
This is the perfect moment to add 3d torches. Finally

**Comment by paramat** [comment]
Meh this pixel is okay, does it offend anyone? kilbith has left too, so closing.

**Comment by Fixer-007** [comment]
I'm offended by general look of the torches, yes

**Comment by tobyplowy** [comment]
@paramat we should add 3D torches also what do you mean by kilbith is gone

**Comment by tobyplowy** [comment]
@Fixer-007 3D torches would be a lot better

**Comment by 0-afflatus** [comment]
So far, the 3d torches I've seen are mostly terrible. It would be easy and desirable to improve the 2d graphics. Either option relies on someone coming up with a good PR for it, any other discussion is pointless.
How many Minetest contributors does it take to change a torch?

**Comment by C1ffisme** [comment]
> How many Minetest contributors does it take to change a torch?

I don't know. :laughing: 

(Did you actually have a punchline prepared?)

**Comment by 0-afflatus** [comment]
> (Did you actually have a punchline prepared?)
ok, that was actually ironic / rhetorical for once.
I am tempted, but that's definitely forum material.
