### ISSUE TITLE
3D torches

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest_game#1063]
We really need 3D torch models why do we have flat torches in the First Place It Looks really bad (I know there's a mod for 3D torches so don't mention it) also The Idea Came Into My Head Because of @Fixer-007 and @sofar over at #1058

**Comment by StepDevelop** [comment]
Yes, I also expect the implementation of mod "torches" in vanilla;) I hope to put :)

**Comment by tobyplowy** [comment]
@StepDevelop I hope to put?

**Comment by sofar** [comment]
My intent has been to debug https://github.com/minetest-mods/torches for a bit, and then to submit that to minetest_game.

**Comment by ShadowNinja** [comment]
I'd certainly welcome making the default torches 3D (provided they're not too buggy of course).

**Comment by sofar** [comment]
@ShadowNinja that's why I've taken out all the options and gizmos from blockmen's torches and reduced them to the absolute minimum needed.

**Comment by tobyplowy** [comment]
@sofar Keep it Up Your the best :smile:

**Comment by rubenwardy** [comment]
Flat 2d torches look weird in a 3d world

**Comment by tobyplowy** [comment]
@rubenwardy yes it does

**Comment by tobyplowy** [comment]
@sofar are you still working on that 3D torch mod (i'm just curious)

**Comment by tobyplowy** [comment]
@paramat will 3D torches get added for the next stable update? it seems a lot of people really want it.

**Comment by ExeterDad** [comment]
I'm joining the campaign for 3d torches. We've been using @sofar's mod for awhile on our Pi server with no issues. No way we're going back to flat.

**Comment by DonBatman** [comment]
I would like 3d torches added as well.

**Comment by MarkuBu** [comment]
There is one issue with inventory tweak. If you place a wall mounted torch and it was the last torch of the stack, the next stack is not loaded automatically

**Comment by tobyplowy** [comment]
@ExeterDad (off topic) lol the way you said that sounds like you're choosing the next president or something XD

**Comment by sofar** [comment]
@tobyplowy yes, it's maintained and I regularly patch it for issues found.

There are issues with item frames, and quarries are also digging up the wieldlights, so it still needs work.

**Comment by FaraoneLele** [comment]
I think the 3D lights may be added before the 0.4.15, why not set as milestones that version? torches that are present in the game right now are horrible.

**Comment by tobyplowy** [comment]
@FaraoneLele the faster I get them the more happy I am (that means full support from me +1)

**Comment by octacian** [comment]
I was planning on working on this 2 weeks ago, will definitely take a look in a few days. It will use ideas from @BlockMen's torches mod, but completely rewritten from scratch.

**Comment by tobyplowy** [comment]
@octacian I Can't Wait :D

**Comment by octacian** [comment]
@tobyplowy done. #1322

**Comment by tobyplowy** [comment]
@octacian looks nice :D

**Comment by sofar** [comment]
@octacian why didn't you start with the github.com/minetest-mods/torches code? It's practically ready for merge!

**Comment by sofar** [comment]
#1325, sigh

**Comment by sofar** [comment]
Since this is an issue, it gets closed when the issue is resolved.

**Comment by est31** [comment]
:tada: 0bd2efcfc1fb23bdb078d5aaeea8cad8ec27d828

**Comment by tobyplowy** [comment]
@sofar thank you :) also to everyone Who worked on this
