### ISSUE TITLE
New Textures, first release!

### ISSUE THREAD

**Issue by StepDevelop** [minetest/minetest_game#1064]
Guys, I have finished the new textures:

- Glass & Glass plane (blue reflections)
- Tree, Acacia, Aspen ... work in progress (update Jungle tree)
- Apple, Bread drawn! inspired by Minecraft :)

Go to my profile and look at the screenshots github (I published the folder with the textures that I have described above).

Thanks, I hope to see the new textures in the next version of Minetest.

Work in progress...

**Comment by kilbith** [comment]
You mean the ones you [copied](https://github.com/StepDevelop/Minetest_0.4.14_Textures_Update/commit/a21ced50972476529f277884da6b19530c341f6e) from Minecraft ?

The joke stops now, get the fuck out and never come back here.

**Comment by tobyplowy** [comment]
@StepDevelop Why Did You Copy Minecraft textures and say you made them. Because you didn't @kilbith there's nicer ways to say that.

**Comment by StepDevelop** [comment]
is a mod for minetest (edit), I change the textures, this is what I wrote in the "readme" of the project! @kilbith your answer is not kind enough :( read and wait 5 minutes (the textures I've posted a few minutes ago), if "I" edit "with gimp, the textures are mine! I will publish screenshots of the changes if you want to ... greetings...

**Comment by rubenwardy** [comment]
Originally is good, blatently copying isn't

**Comment by tobyplowy** [comment]
@StepDevelop  well if they look almost the same like the original Minecraft textures you still have stolen them you need to begin from scratch but show me some screenshots

**Comment by tobyplowy** [comment]
@rubenwardy Amin :smile:

**Comment by StepDevelop** [comment]
Update all textures of my mod and then public again screenshots. I just wanted to describe my idea! make the texture "continuous" no dark edges! then the public a screenshot where you see a small structure built with new textures.

Ps. my fault and my English. I hope that I made clear now :) thanks ...

**Comment by C1ffisme** [comment]
@kilbith Please don't shoot people with language like that. We are an open source project, meaning we are open to contributions.

@StepDevelop Please do not use Github for making jokes. We have a [forum](forum.minetest.net). Please just leave us if all you have to say is just joking, and you have no intention of helping development.

**Comment by StepDevelop** [comment]
ok, I go on the forum ...

No tricks! you only have misunderstood my fault :) (my english). Tomorrow I update you on the forum, so you see the end result. thank you

**Comment by sofar** [comment]
There is no code here, please close this issue.

**Comment by paramat** [comment]
Please open a PR when you have textures to submit.
