### ISSUE TITLE
Mese texture should suggest an alien origin

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest_game#1066]
I've made in the past a recall that Mese is of [alien origin](http://irc.minetest.ru/minetest-dev/2012-12-13#i_2711799) and it's culturally known as such. This texture had some "mysterious" characters in it, and the change to latin characters was a mistake since it's inconsistent with its fictional origin. Aside the fact it's a bad texture.

What I propose is to change back to the [2nd official look](http://wiki.minetest.net/images/e/e7/Old_Mese.png) that Gambit respected and slightly improved : 

 ![default_mese_block](https://cloud.githubusercontent.com/assets/7883281/14953705/716a8cce-106c-11e6-94c6-81fbab26fd68.png) ![capture d ecran de 2016-05-02 13-49-22](https://cloud.githubusercontent.com/assets/7883281/14953751/c5ceaa20-106c-11e6-8dd9-6b549f0b89a6.png)

Derivation in yellow : 

![mese](https://cloud.githubusercontent.com/assets/7883281/14953715/7af0cc54-106c-11e6-8f1d-c712ac99f44b.png)

Although the yellow can be confused with the gold and the color may need to be changed back to a distinctive khaki green ?

Cc: @paramat, if you're interested.

**Comment by tobyplowy** [comment]
The Green One Looks better

**Comment by sofar** [comment]
This is an improvement, so, I'm fairly positive about it!

**Comment by C1ffisme** [comment]
Hmmm... What about making the block found underground have an alien texture, and the block made by the player would have latin letters? Maybe Mese has mind-control powers, that force you to engrave the name of it on it?

Just for fun, anyway, I made this:

![mese](https://cloud.githubusercontent.com/assets/9893266/14959513/5066abbe-1055-11e6-91dd-c0b375c3bd32.png)

**Comment by sofar** [comment]
I'd rather have the letters be unrecognizable, as in the original suggestion.

**Comment by C1ffisme** [comment]
I know... my letters need a lot less contrast...

**Comment by paramat** [comment]
> the change to latin characters was a mistake since it's inconsistent with its fictional origin. Aside the fact it's a bad texture.

Totally agree. The current texture is not good. For a long time i have thought that the origin of the word 'Mese' could be that strange alien font was found on it that resembled the letters MESE.
So i prefer the 2nd official texture to the current as it is more vague, however the letters could be more alien-looking, they are still obviously terran MESE.

I also miss the character of the original mese, being bright pure yellow with black letters, so i combined these 2 desired in my own mese texture:

![default_mese](https://cloud.githubusercontent.com/assets/3686677/14963570/2d470a24-109c-11e6-9ea8-9bf737f4f258.png)

Which is obviously too minimal to be acceptable, it would need editing to add a bevel around the edge, i'll see what i can do.

**Comment by paramat** [comment]
Reading the linked IRC i do think we should go with c55's inspiration that this is a mysterious/alien material.

**Comment by PilzAdam** [comment]
I think we shouldn't suggest an origin of mese at all.

**Comment by rubenwardy** [comment]
> I think we shouldn't suggest an origin of mese at all.

That basically makes it inconsistent / random. I like the idea of making mese alien, and adding other elements to match that.

**Comment by paramat** [comment]
First attempt based on classic mese yellow and our second texture, with more abstract symbols.

![default_mese_128](https://cloud.githubusercontent.com/assets/3686677/14971724/f6ef4bf4-10cc-11e6-89de-c226be6f3a1b.png)

**Comment by rubenwardy** [comment]
That's too over exposed, imo

**Comment by kilbith** [comment]
Can't you just be content with Gambit's texture, and tweaking it with moderation ?

**Comment by tobyplowy** [comment]
@paramat It's Oké But It's A Little Bit too bright (my eyes it burns) :smile:

**Comment by PilzAdam** [comment]
@rubenwardy what's the benefit of giving mese a background story?

**Comment by C1ffisme** [comment]
@PilzAdam Saying that mese is alien is very far from giving it a background story. A background story would have much, much more detail.

**Comment by paramat** [comment]
Yes it's too bright, will work on it.
My texture is very similar to Gambit's and our second official texture, but has more mysterious font and is classic mese-yellow. I have always missed the old pure yellow of mese, it's ridiculous pure yellowness helps to create a mysterious/alien look. I'm not keen on the dirty greenish-yellow of Gambit's texture, it might as well be classic pure yellow.

I feel we could just consider it unknown/mysterious/possibly alien with no extra detail.

**Comment by Napiophelios** [comment]
@PilzAdam: I think by calling it alien in origin makes it so we dont actually need a background story.

"Its alien....so its special...so...stop asking us questions about it...cuz thats all we know"

**Comment by paramat** [comment]
![default_mese128](https://cloud.githubusercontent.com/assets/3686677/15001790/6d0ae40e-1192-11e6-9d98-4dab870219aa.png)

I used shading sampled from the crystal texture.

![default_mese_crystal128](https://cloud.githubusercontent.com/assets/3686677/15001792/71b24380-1192-11e6-9acb-51d4a96b7947.png)

To abstract the letters the 'E's are now 3 horizontal lines, the 'M' is 3 vertical lines, the 'S' is the snakelike shape used in my texture pack version.

**Comment by Thomas--S** [comment]
How about adding a bit HSV noise to the yellow background?

**Comment by C1ffisme** [comment]
> To abstract the letters the 'E's are now 3 horizontal lines, the 'M' is 3 vertical lines, the 'S' is the snakelike shape used in my texture pack version.

Aren't those just a tad too much like latin letters? I mean, you really just removed a few pixels. Most letters are actually based off of the shape of the mouth. (The E is a bit like a mouth with a tounge. See? Or the O looks like the mouth you make when you make... The O sound. An H is two lips/teeth sets, with a small line of space between them.)

An example of a more alien letter would be my S. It's based off of teeth, since you close your teeth to make an S, or a T sound. (The symbol actually means an S sound or a T sound.)

Of course, I don't imagine that aliens have the same mouth shapes as the human player. Any thoughts on this?

**Comment by benrob0329** [comment]
Perhaps this would be a good time to make a video on my thoery of the origins of MESE....

**Comment by C1ffisme** [comment]
th**eo**ry

(Thought you might as well know...)

**Comment by benrob0329** [comment]
Oops :laughing:

**Comment by paramat** [comment]
After 2 unpopular PRs, here's a classic-mese-yellow version of Celeron55's 2nd official Minetest texture:

![mese5_128](https://cloud.githubusercontent.com/assets/3686677/15412136/21c8a4ee-1e1d-11e6-9201-12cfea3654ce.png)

![default_mese_2nd128](https://cloud.githubusercontent.com/assets/3686677/15412139/25b301e4-1e1d-11e6-8211-1b1ddd334e15.png)

^ Celeron55's texture

Any comments?

**Comment by Zeno-** [comment]
I think the "lettering" on in should actually be a code that is decipherable by anyone bored enough to do so.

**Comment by benrob0329** [comment]
I think that the highlighting is a bit too bright.

Other than that looks good.

**Comment by Thomas--S** [comment]
Do we really want to have an "unreadable" mese texture? New players will have problems to figure out how to call this node. (If they don't activate debug mode)

**Comment by Napiophelios** [comment]
Thomas--S, once its in the inventory it will have a tool tip description.

If MESE is a crystalline mass it should be similar in design
to a diamond's block form.

**Comment by Thomas--S** [comment]
@Napiophelios I really like your texture suggestion. :+1:

**Comment by Napiophelios** [comment]
I seriously doubt it will catch on Thomas--S;
It doesn't look special enough :) 

And its also devoid of the historical look of MESE.

**Comment by benrob0329** [comment]
I consider Mese to be a metallic crystalline (its a crystal, but can be melted into mesecon or formed into a sword)

**Comment by C1ffisme** [comment]
@Napiophelios Maybe you could write the words on it in small text?

**Comment by paramat** [comment]
> I think that the highlighting is a bit too bright.

That's sort of unavoidable as it needs to be brighter than the yellow to define the top of the letters.

> Do we really want to have an "unreadable" mese texture?

No, the last 2 PRs were rejected as 2 game devs want it to clearly read MESE, as my texture does.
It's a big pure crystal apparently so the letters are raised areas of the material, the only way to see them is by using edge-shine and shadow.

**Comment by paramat** [comment]
@Ekdohibs @PilzAdam @sfan5  any comments? i don't want to spend time making a PR unless this is acceptable.

**Comment by Ekdohibs** [comment]
@paramat Sorry, I don't like that one: too flat and too contrasted.

**Comment by paramat** [comment]
PR #1106
Ekdohibs i have improved the texture and opened a PR, i'm not confident you like it but we need a new texture and it may be acceptable to PilzAdam and sfan5. It seems that with the mese texture tastes differ so much we can't keep all MTGame devs happy, as much as i would like to.

**Comment by paramat** [comment]
Finally merged #1106
