### ISSUE TITLE
Inconsistency with digging of sandstone

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1071]
Long ago I noticed that I can dig sandstone with my bare hands (which is strange, since sandstone is pretty hard rock). Now PilzAdam asked the same, so wth I opened the issue.
I did testing to see what sandstone items are breakable by hand. So:
Breakable by hand:
* default:sandstone
* stairs:slab_sandstone
* stairs:slab_sandstonebrick
* stairs:stair_sandstone
* stairs:stair_sandstonebrick

Not breakable by hand:
* default:sandstonebrick

It seems odd, I guess all of these blocks should not be breakable by hand.

Screenshot of those blocks: https://i.imgur.com/5Cl7mVL.png
Example of sandstone: http://www.sandatlas.org/wp-content/uploads/00105-IMG_5703-sandstone.jpg

@paramat @sofar (geology department)

**Comment by PilzAdam** [comment]
Trivial to fix: remove `crumbly = 2` from [here](https://github.com/minetest/minetest_game/blob/master/mods/stairs/init.lua#L349)

**Comment by paramat** [comment]
I guess all ssandstone should be cracky = 3 to match stone.

**Comment by PilzAdam** [comment]
@paramat why match stone, and not stone bricks? Bricks seem to generally have a rating of 2 in the cracky group.

**Comment by paramat** [comment]
Agreed cracky = 2 for bricks.

**Comment by paramat** [comment]
PR #1075

**Comment by paramat** [comment]
#10 75 is merged.
