### ISSUE TITLE
Creative playername troubles

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest_game#1072]
Players signing into a creative server with a '-' character in their name have trouble moving passed page 2 in the creative inventory screen.

**Comment by tenplus1** [comment]
Fixed! https://github.com/minetest/minetest_game/pull/1049

**Comment by sofar** [comment]
FYI we leave the bugreports open until the fix actually gets merged - now someone could think that this issue is actually fixed, while it's not.

**Comment by tenplus1** [comment]
oops, sorry dude...

**Comment by paramat** [comment]
#1049 is merged.
