### ISSUE TITLE
Bucket violates conservation of mass

### ISSUE THREAD

**Issue by jhcole** [minetest/minetest_game#1080]
An empty bucket is returned when placing a liquid with a bucket even if the placement fails due to the protection check. Is this an intentional punishment for trying to place a liquid in a protected area or just a bug?

**Comment by tenplus1** [comment]
Fixed: https://github.com/minetest/minetest_game/pull/1081

**Comment by paramat** [comment]
I agree this needs changing.

**Comment by sofar** [comment]
Patch looks OK, not tested though.

**Comment by paramat** [comment]
#1081 is merged.
