### ISSUE TITLE
Page counter behaves weirdly after creative search

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#1087]
* Start Minetest Game in Creative Mode
* Open inventory menu
* Select tab “All”
* Go to page 8
* Enter “bed” into search and search → there should be only 1 page and the page counter should show “1 / 1”
* Click on the left “arrow” (smaller than sign)

The list of displayed items becomes empty and the page counter will now show “7 / 1” which doesn't make much sense.

e7a55734d3de051d6565ebe28a9dd53043f9b352

**Comment by tenplus1** [comment]
Works fine here ?

**Comment by Fixer-007** [comment]
Confirmed on 58b54cf

**Comment by Thomas--S** [comment]
Confirmed on latest Ubuntu daily builds.

**Comment by paramat** [comment]
Confirmed but not a big issue, after any search moving back through pages is weird but users would rarely do that. Not a blocker for release.

**Comment by red-001** [comment]
This also happens when switching between tabs.

**Comment by paramat** [comment]
#1098 is merged.
