### ISSUE TITLE
Drinking Glass Texture

### ISSUE THREAD

**Issue by cdqwertz** [minetest/minetest_game#1089]
If you place a drinking glass it looks really strange:

![screenshot_20160516_112659](https://cloud.githubusercontent.com/assets/12814327/15285719/55cb4af6-1b59-11e6-8a05-4bf56fd0894d.png)

I think we should fix that.

**Comment by C1ffisme** [comment]
Not to mention the fact that a bottle or glass seems to be a meter high when you place it down.

**Comment by Thomas--S** [comment]
How about this modification of the current texture?

![](http://i.imgur.com/1epsWGX.png)

![](http://i.imgur.com/WwF0bg5.png)

**Comment by PilzAdam** [comment]
@Thomas--S this doesn't really look like a drinking glass in the inventory.

**Comment by Thomas--S** [comment]
I don't suggest to modify the inventory image.

Atm, there are two different versions:

vessels_drinking_glass.png
vessels_drinking_glass_inv.png

I only suggest to modify the first one.

**Comment by Thomas--S** [comment]
PR: #1096

**Comment by paramat** [comment]
#1099 is merged.
