### ISSUE TITLE
Mushrooms do not spread

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#1091]
It seems that mushrooms do not spread in darkness (or *at all*), but I expect them to do.
I have placed a brown mushroom on Dirt with Grass in pitch darkness, made sure there is enough space around (surface: Dirt with Grass and Tree blocks), had run the game for about 60 minutes and my guess is that the intent of Minetest Game is for the mushroom to multiply. This did not happen.

However, mushrooms actually die off in direct sunlight (much quicker than in 60 minutes, of course), so at least this part of the ABM works.

So currently, Minetest Game has a situation where mushrooms can slowly die but not multiply. This is not good IMO as this means there will be fewer and fewer mushrooms over time, until only those in the shadow remain.

Please try to test this on your Minetest Game as well to try to confirm that the mushrooms do not indeed spread.

Tested in: e7a55734d3de051d6565ebe28a9dd53043f9b352

**Comment by paramat** [comment]
Needs to be light level 3 or below, that's cave-darkness, did you try underground? try increasing ABM rate when testing.

**Comment by Wuzzy2** [comment]
Huh, spread only happens at midday? I could not see it in the code.

I hid the mushrooms in a very dark place in an enclosed structure, no light came through.
Now I tested it waiting for midday and the mushrooms did indeed multiply!

This midday check thing is bad IMO because this means mushrooms never spread if `time_speed` is set to 0, which is useful if you do not want the sun to move at all. Yet mushrooms die off reliably.

**Comment by PilzAdam** [comment]
@Wuzzy2 it doesn't wait until midday to check the light value. It checks what light value the position would have, if it was midday. This is done to check that no sunlight reaches the mushroom.

As you said in your last comment, the mushrooms do spread, so this can be closed.
