### ISSUE TITLE
Furnaces show all items not cookable and any fuel item as 0%

### ISSUE THREAD

**Issue by myketronic** [minetest/minetest_game#1092]
Furnaces are completely non-functional, for me
- Minetest game in version 0.4.14, pulled down today
- Issue seen in 32-bit and 64-bit minetest official builds
- OS is WIndows 7 x64, 8 GB RAM
- No errors seen in console or debug

- Re-created issue in x64 build, attached debug.txt in verbose mode, game world was created from scratch and was not saved or reloaded between creation and when the problem was re-created.

- Furnace placed at line 6792
- Placed 4 logs in fuel slot, 4 in smelting slot<br />
    NOTE: The problem is seen regardless of the type of fuel or the item to be smelted
- Screenshot attached with furnace status message:
    Furnace inactive (Item: Not cookable; Fuel: 0%)

[debug.txt](https://github.com/minetest/minetest_game/files/266791/debug.txt)

![furnace_no_worky](https://cloud.githubusercontent.com/assets/13257122/15300890/38e9d47a-1b68-11e6-92b0-d25221e89931.png)

**Comment by PilzAdam** [comment]
You can't cook logs in the furnace.

**Comment by myketronic** [comment]
Ok, I can't cook logs - got it.  Should I be able to cook sand into glass?  That also doesn't work.

**Comment by myketronic** [comment]
Scratch that - cannot reproduce after restarting my Windows host.
