### ISSUE TITLE
Add API information for creative.formspec_add

### ISSUE THREAD

**Issue by davisonio** [minetest/minetest_game#1095]
https://github.com/minetest/minetest_game/commit/8ea031ef775d77b4837153f1c889916855b255c0 should have an entry in `game_api.txt` so that mod developers are able to discover it.

**Comment by sofar** [comment]
@tenplus1 want to take a stab at this?

**Comment by tenplus1** [comment]
Does this help: https://github.com/minetest/minetest_game/pull/1097

**Comment by sofar** [comment]
yes

**Comment by paramat** [comment]
#1097 is merged.
