### ISSUE TITLE
Bookshelf impossible openings

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1104]
I discovered to my surprise you can't build bookshelves onto themselves because right-clicking opens the formspec instead of building, multiplie layers need other temporary nodes to build onto. Not good for building large libraries.

The bookshelf texture is on all 4 sides of the node, having deep shelves on all 4 sides is impossible and looks wrong. However correcting this may be unpopular as many bookshelves will then need to be rotated to the desired direction. Any comments on whether changing this to 2 open sides is acceptable?

My proposal:
I would like to add a new node 'junglewood_bookshelf' which is not interactable and is meant for building with and decoration. It can therefore be open on 2 sides not 4, this along with the darker colour will distinguish it from the interactable bookshelf.

Related #1103

**Comment by Thomas--S** [comment]
You can build to a bookshelf with shift-rightclick.

**Comment by paramat** [comment]
I see.
An extra node might be useful for use in large numbers where we want to avoid adding metadata for every node.

**Comment by Thomas--S** [comment]
I can totally understand your point of view, but I think it's a bit illogical: Why can books be put in a wooden shelf, but not in a shelf made out of junglewood. I think it would confuse players pretty much.

**Comment by 0-afflatus** [comment]
Argh no. All nodes with a formspec have the same issues. Changing bookshelves like this would break so many builds without any appreciable benefit.

**Comment by C1ffisme** [comment]
What about formspecs requiring craftitems or the hand to open, otherwise you place the node?

**Comment by MT-Modder** [comment]
:+1: 2 open sides + facedir rotation

:-1: junglewood_bookshelf

**Comment by sofar** [comment]
Positive about 2-faced open shelves.

I would solve the placement problem otherwise - if you target the "face with books" side with a node, open formspec, otherwise, place node. this way, stacking and chaining shelves is trivial.

**Comment by sofar** [comment]
@0-afflatus that problem can be mitigated with a fallback nodedef. But yes, it will break stuff.

**Comment by MT-Modder** [comment]
@paramat
@sofar 

Placement isn't a problem because all nodes with formspecs behave this way. Unless you plan on changing how all node formspecs behave it would be inconsistent to make a single change.

I'd personally like to see a **global** change in this behavior because it's a little inconvenient, especially when flying and building.

**Comment by paramat** [comment]
Since building is apparently possible with shift-click, i'm only now concerned about the impossible openings, but changing the textures would break a lot of builds it seems. I'm not sure it's worth upsetting players.

**Comment by benrob0329** [comment]
There is a screwdriver for a reason, I'd rather fix a library than have impossible bookshelves that don't look right from the side.

**Comment by paramat** [comment]
> You can build to a bookshelf with shift-rightclick.

Doesn't work for me??

**Comment by DonBatman** [comment]
Please do the texture change. I never cared for the books showing on 4 sides

**Comment by NathanSalapat** [comment]
I personally could never figure out how the books from two adjoining sides could exist as they would both have to run through each other, a texture change is a good idea.

**Comment by Thomas--S** [comment]
:+1: for a texture change

**Comment by tenplus1** [comment]
Have books show on 2-sides only (front and back) with sides being wood.

**Comment by 0-afflatus** [comment]
As I've said many times, I trust you won't take my opinion on MTG as any kind of vote - and considering the weight of opinion I may yet reconsider. Interesting.

**Comment by sofar** [comment]
Texture change should be separate PR (not saying it wouldn't be worth it).

**Comment by C1ffisme** [comment]
@paramat If you set your sneak key to something else, you use your sneak key instead of Shift.

**Comment by paramat** [comment]
Aha that's why!

**Comment by paramat** [comment]
sofar i agree, the PR will be for a texture change only since these are buildable with sneak-rightclick.

**Comment by paramat** [comment]
PR #1110

**Comment by paramat** [comment]
#1110 is merged.

**Comment by WSDguy2014** [comment]
*Facepalm* I should keep that, no texture change, nor adding a junglewood bookshelf. But, you are worse.
