### ISSUE TITLE
Problems with sound code in fire mod

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1112]
From lua_api.txt:
'loop = true, -- only sounds connected to objects can be looped'
I don't see objects used.
Fire sounds are reported to be heard 1000s of nodes away.

Rejoining the game makes flames go silent.
The fire sound code is hacky and probably heavy, playing looped sounds every 6 nodes.
Certainly we need a new sound API and engine code for uses such as flames and running water.

**Comment by Fixer-007** [comment]
Please don't remove the sounds.

**Comment by 0-afflatus** [comment]
Surely it would be possible to reduce the audible radius and decrease the number of nodes triggering sound loops. 

A new api for ambient noise emitted by masses of nodes would be desirable. It could be extended to leaf masses emitting birdsong, grass emitting cricket chirrups and wolf-howls from pine trunks, even the whirring of machinery.

**Comment by tenplus1** [comment]
My Ambience lite has a faster way of checking for flame and playing sound: github.com/tenplus1/ambience

**Comment by paramat** [comment]
I think tenplus1's mod has potential and the method should be considered for fire sounds and maybe flowing water sounds too.

**Comment by Fixer-007** [comment]
Or just include the damn thing, we need ambience, I doubt someone will code it.

**Comment by paramat** [comment]
Nope it is excessive with all the wildlife sounds, so a mod thing.

**Comment by paramat** [comment]
I'm looking into using tenplus1's code for fire sounds.

**Comment by sofar** [comment]
I'd postpone this until we get an idea where client-side modding API goes. That is the right place for ambient sounds IMHO, and will make it much easier to do.

**Comment by paramat** [comment]
True, but until that arrives we need better working and more lightweight fire sounds, the current implementation is really bad, and heavy.

**Comment by paramat** [comment]
I'm simplifying tenplus1's ambience mod to just work with fire, the code so far:
https://gist.github.com/paramat/b9b664fdacfd3847db2051a919552f68

**Comment by paramat** [comment]
Greatly simplified tenplus1's ambience mod for use with fire sounds.
Code: https://gist.github.com/paramat/b9b664fdacfd3847db2051a919552f68
Only the 'large fire' sound is used, but it's volume now depends on number of flames found in the radius around the player, a single flame has a quiet gentle sound. Gain rises with the square root of flames found.
I feel this mat be more lightweight than the current fire sounds code, as it doesn't add a fire sound at all positions in a 6-node lattice, only one sound is played to each player at any time.
Re-joining the game now makes fire sounds return (after a few seconds).

**Comment by paramat** [comment]
Updated that code again. Now the flame count from the previous cycle is stored. If a player walks into range of flames an alternative version of the sound is played that smoothly fades in. If a player walks out of range of flames an alternative version of the sound is played that smoothly fades out. This avoids any instant start or stop of fire sounds.

**Comment by paramat** [comment]
https://github.com/paramat/parambience
Here it is as a mod for testing, easily tested by placing 'permanent flame' nodes around.
The time cycle is 4s to reduce the occurence of node searches, the cycle can be reduced in the parameters, the search radius can also be adjusted.
There are now 3 alternative fire samples used to avoid a repetitive ambience, all have been re-edited from the original freesound download.

**Comment by Fixer-007** [comment]
will check

**Comment by paramat** [comment]
Yeah, the cycle could be made shorter, it'a case of balancing it against weight of 'fnd nodes in area' searches, tenplus1's mod uses 2s. The radius could perhaps be 6.
The non-positional sounds are a little weird, but i don't yet know an acceptable way to have positional.

**Comment by paramat** [comment]
I'll try something with positional, it won't be perfect though.

**Comment by paramat** [comment]
https://github.com/paramat/parambience
Now positional, uses the first flame position in list, which is southern and western, so in a large collection of flames the sound will come from a corner.
Since the sounds are now positional, each player in range of flames adds a sound in the environment, a little weird but hopefully not a big problem. Worth it for positional sounds.
I changed the cycle to 3s, it may have to be 2s but that's short enough, 1s or shorter is too often to trigger these large node searches around every player all the time. We have to balance the feature against load.

I tried choosing a random flame position per cycle, that made the position shift every cycle which seemed to be worse, however that is an option. You can test that wiith this line at line 49:
`pos = fpos[math.random(#fpos)],`

**Comment by Fixer-007** [comment]
>Since the sounds are now positional, each player in range of flames adds a sound in the environment

o_0 o_0 o_0

**Comment by tenplus1** [comment]
@paramat - that's why I linked sound played to an actual player to stop multiple sounds playing...  to_player = player_name,

**Comment by paramat** [comment]
Well i just thought of having positional sounds played to only one player, if that's possible, i thought it wasn't from the documentation, i'll try it.

**Comment by paramat** [comment]
Updated mod, seems to work.

**Comment by Fixer-007** [comment]
* positional sound seems to work (did not check if other players will not hear it)
* searching middle point for sound gives some odd results, place some sounds underground, and few above your head, you will notice how rapidly its volume and probably position can change if you move just 1 block away or under it.
* when you go away from the flame - sound goes down but just before end volume bumps up again a lot and dies down
* reaction time is way too slow (1 sec is bare minimum, is it really that hard on CPU to justify this? even if you have 40 players, thats 40 checks in total, you can simulate this with 1/40 sec cycle and then do modprofile)

**Comment by paramat** [comment]
> searching middle point for sound often gives some odd results, place some sounds underground, and few above your head, you will notice how rapidly its volume and probably position can change if you move just 1 block away or under it. I think it is not the best method, another example when I have lots of scattered fire around - but it is very quite
when you go away from the flame - sound goes down but just before end volume bumps up again a lot and dies down

Good points. Non-positional may be better.

**Comment by paramat** [comment]
The problem with shortening the cycle is that the sound samples then get shorter, 1s samples are not going to sound as good. I feel 2-3s is about right.

**Comment by paramat** [comment]
Updated the mod again:
 Make sounds non-positional again. Add water sounds (CC BY-NC so temporary)

**Comment by paramat** [comment]
See #1385

**Comment by Fixer-007** [comment]
>The problem with shortening the cycle is that the sound samples then get shorter

hm, why can't it keep playing the sound out of cycle varying volume as needed?

**Comment by paramat** [comment]
#1436 merged.

**Comment by sorcerykid** [comment]
Just FYI: Don't trust the documentation, it is misleading. Sounds can be looped regardless of their association with an object. Moreover, sounds are not "attached" to an object internally.

When minetest.sound_play( ) is invoked with an object, it does not maintain any reference to the object. It is only used for positioning purposes at the time of invocatioin. Regardless of whether the object is moved or removed afterward, the looped sound will continue to play from that same position until stopped (hence the bug with fire sounds).

If you really want to attach a sound to an object, you'd need to create and maintain a state table.
