### ISSUE TITLE
Make stone bricks rotatable

### ISSUE THREAD

**Issue by lightonflux** [minetest/minetest_game#1113]
It often looks weird when a path with stone bricks has a pattern in one direction, and another in the same, although the path goes along in 90°.

Please make all stone bricks rotatable. 

It also looks weird when the rotation of stone brick stairs from the stairs mod don't match. 
![bildschirmfoto von 2016-05-28 17-37-58](https://cloud.githubusercontent.com/assets/1377943/15628167/f03d5750-24fa-11e6-8531-440fb10881f3.png)

**Comment by yyt16384** [comment]
I guess making it rotatable will cause more problems, as you will need to place every brick correctly.

**Comment by Fixer-007** [comment]
Not only stone bricks have this problem.

**Comment by lightonflux** [comment]
Semi fix: Always place in same direction, make it rotatable with screwdriver.

**Comment by C1ffisme** [comment]
@yyt16384 Not to mention that every brick block would now have to carry extra data.

**Comment by sofar** [comment]
Rotation data doesn't take any extra storage space.

**Comment by paramat** [comment]
> Semi fix: Always place in same direction, make it rotatable with screwdriver.

This happens currently.

**Comment by paramat** [comment]
The textures are directional so i guess they should be rotatable.

**Comment by 0-afflatus** [comment]
Adding paramtype2 = "facedir", if that's what this is about, doesn't mess up existing builds as already placed nodes should all be in default rotation. Removing it does of course.

If there is a way to make nodes rotatable with the screwdriver without affecting placement that would be ideal, but I haven't figured out how to do that if it even is possible.

**Comment by sofar** [comment]
Existing builds should be unaffected, because the screwdriver mod won't be able to rotate them, and thus param2 for all those nodes will remain `0` (unless some worldedit hack was used, but we don't care about this, really).

**Comment by sofar** [comment]
Pushed #1116 - which makes a ton of crafted blocks rotatable.

**Comment by C1ffisme** [comment]
@sofar Oh... I guess you'd be right, since params are always there...

**Comment by paramat** [comment]
#1116 is merged.
