### ISSUE TITLE
Mossycobble has no its slab and stair

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1118]
why not?

**Comment by C1ffisme** [comment]
You are right!

It seems that mossycobble is important enough to have a wall, but it doesn't get stairs and slabs.

A search for "slab" in the creative inventory seems to reveal a lot of colours, but no green coloured slabs. Seems like a good addition.

**Comment by paramat** [comment]
+1 want to make a PR?

**Comment by 0-afflatus** [comment]
Because of realism over gameplay. 
Realism says cobble stairs and slabs should have a moss-growing function, because the moss is a kind of patina which comes off if you handle it.
Gameplay says building blocks should consistently have shaped variations available, this is what most players expect.

**Comment by Fixer-007** [comment]
Think other way, moss growed on steps to produce mossy cobble stair, magically %)

**Comment by C1ffisme** [comment]
> Because of realism over gameplay.

Uh... I think you have that the wrong way around.

Gameplay is **always** put ahead of realism, only in a realism simulating game does Realism **ever** share the same priority level as Gameplay.

**Comment by sofar** [comment]
I'm totally for adding the mossy cobble stair and slab. I'm entirely neutral as to whether they should be craftable or not, it may be nice to only ever allow mossy cobble slabs to get made by water proximity.

**Comment by sofar** [comment]
#1120 implements the nodes, but omits a crafting recipe to make these directly. Instead, you need water to turn these nodes into mossy versions :)

**Comment by paramat** [comment]
Agreed they should only be created using the existing dampness / moss ABM.

**Comment by Fixer-007** [comment]
merged https://github.com/minetest/minetest_game/commit/2199be51087d0d9661d1b3f80c0bb2a55410458b
