### ISSUE TITLE
Add ability to handle alpha textures into /default/stairs mod

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1121]
If I understand it correctly right now, default stairs mod is not taking into account nodes with `use_texture_alpha = true`, so if you make stair/slab of some transparent block, it will lose its transparency.

**Comment by sofar** [comment]
`use_texture_alpha` is broken for mesh and nodebox nodes, so likely the best solution is to not allow this and have mods manually create slab and stair versions instead.

**Comment by paramat** [comment]
See https://github.com/minetest/minetest/issues/95
Transparency != translucency.
Translucency is buggy in Minetest anyway so you wouldn't want to use it for nodeboxes/meshes.

**Comment by paramat** [comment]
How do transparent nodeboxes appear? Like default glass stairs.

**Comment by Fixer-007** [comment]
I mean translucency :)

**Comment by paramat** [comment]
Ok.
