### ISSUE TITLE
3D renderd arm

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest_game#1123]
Why do we have a 2D image for the characters hands? Why not 3D here's an example of what it should look like https://www.google.be/search?q=minecraft+arm&client=tablet-android-google&biw=960&bih=600&prmd=ivn&source=lnms&tbm=isch&sa=X&ved=0ahUKEwizm9LA2JDNAhXMJsAKHc5zBF4Q_AUIBigB#imgrc=cCbe9pFkLHMSxM%3A a actual 3D renderd arm would look a lot better.
(it would be the same arm like in Minecraft)

**Comment by paramat** [comment]
This is more of an engine issue.

**Comment by tobyplowy** [comment]
@paramat yeah exactly that's what I want (det uses the player skin)

**Comment by tobyplowy** [comment]
@paramat i re-opened it in minetest itself #4190
