### ISSUE TITLE
beds: why is it that beds must be red?

### ISSUE THREAD

**Issue by pithydon** [minetest/minetest_game#1125]
I like blue.

**Comment by sofar** [comment]
Options available to you:

- make or use a texture pack
- make or use a mod that changes the color
- make or use a mod that provides alternative beds and bed colors

Please close this bug.

**Comment by paramat** [comment]
Duplicate of #475 please continue discussion there.
Not depending on red dye is a valid point but 'I like blue' is not a valid argument or request.

**Comment by fujita-nozomi** [comment]
i think if use red as bed color
then "somebody" will be get mad :-D
