### ISSUE TITLE
how to use "Nyan Cat" and "rainbow" block?

### ISSUE THREAD

**Issue by fujita-nozomi** [minetest/minetest_game#1128]
or them just a useless east-egg?

**Comment by 0-afflatus** [comment]
Hey @fujita-nozomi this issue tracker is the place to talk about bugs and development of Minetest game. You should use https://forum.minetest.net/ for this sort of question. In fact you will probably find there is already an answer there.

**Comment by paramat** [comment]
They are only decorative by default, there is no use. Some mods use them though.

**Comment by tenplus1** [comment]
I use both on server for special armor and potions, they are used and collected by players as a rare item :)
