### ISSUE TITLE
Some plant life in the water

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest_game#1129]
the oceans are kind of boring, there should be more stuff in the oceans corals and seaweed Maybe? Also maybe beaches culd generate between land and oceans.

**Comment by tenplus1** [comment]
This would be nice so long as air bubbles don't appear all around underwater plantlike nodes.

**Comment by paramat** [comment]
I would support some cubic corals. Plants need a solution for air bubbles (possibly engine side).

**Comment by pithydon** [comment]
Here are some textures for coral. you may use WTFPL for them.

![coral_bleeched](https://cloud.githubusercontent.com/assets/18400998/15987263/9c25f498-2fdf-11e6-9655-a190a36f107a.png)
![coral_blue](https://cloud.githubusercontent.com/assets/18400998/15987264/9c27220a-2fdf-11e6-9c24-f9542a888fc9.png)
![coral_pink](https://cloud.githubusercontent.com/assets/18400998/15987262/9c23952c-2fdf-11e6-93b5-06d4e7193758.png)
![coral_yellow](https://cloud.githubusercontent.com/assets/18400998/15987265/9c2a31de-2fdf-11e6-83f0-1dcdbce5689b.png)

Sorry tobyplowy there not plants.

**Comment by tobyplowy** [comment]
@pithydon nice textures I'm not a fan of the colors but a good anyways :) no problem that you don't have plant textures :)

**Comment by Rogier-5** [comment]
> I would support some cubic corals. Plants need a solution for air bubbles (possibly engine side).

Stairs and slabs need a solution too.

Would it be possible (i.e. feasible) to have a generic solution / generic support for fluid-like nodes, like water and lava, but also air ? Such a solution would allow the 'empty' part of nodes (of plantlike nodes, but also of stairs, slabs, etc.) to be filled with the fluid medium they are supposed to be in, whether that is air, water, lava, or something else. Additional types of air-like nodes would then become a possibility too. For instance vacuum, or colored air. Or real smoke. Poisonous gases in mines, Etc.

**Comment by tobyplowy** [comment]
@Rogier-5 yes this would be amazing ( this is always a future that i wannted in Minecraft so it would be amazing if minetest would do it)

**Comment by tenplus1** [comment]
Maybe a new flag in node definition would be handy, something like:  water_passthrough = true, so that water would draw instead of air ?

**Comment by Rogier-5** [comment]
> Maybe a new flag in node definition would be handy, something like: water_passthrough = true, so that water would draw instead of air ?

That would significantly improve the current situation indeed.

Maybe the name `liquid_passthrough` would be better ? As it would also apply to lava, and other liquids. Maybe even `adjacent_liquid_effect = "passthrough"`, so that other effects would be possible as well ?

When such a node is dug, the server could then also directly replace it with the liquid that is passing through, instead of replacing it with air, and waiting for the liquid loop to fill the gap.

**Comment by yyt16384** [comment]
It is tricky to get it right. You have to consider which faces are connected to outside liquid. A normal slab will let liquid pass through horizontally, but not vertically, for example.

**Comment by Rogier-5** [comment]
> It is tricky to get it right. You have to consider which faces are connected to outside liquid. A normal slab will let liquid pass through horizontally, but not vertically, for example.

And nodes could have a wall in their *middle*, so that on one side water could flow in, while lava could flow in on the other side. Without them affecting each other... Such behaviour probably even goes against the block-oriented nature of minetest...
Bottom line: slabs are very tricky indeed :-(. A flag would certainly not solve that problem.

So, I think a straightforward single setting that solves 80% of the problem, for plantlike nodes and some others, like torches, ladders, etc. is a worthwile and significant improvement.

**Comment by tobyplowy** [comment]
`And nodes could have a wall in their middle, so that on one side water could flow in, while lava could flow in on the other side. Without them affecting each other... Such behaviour probably even goes against the block-oriented nature of minetest...`

I think that is going to be a bit too complicated but it would be cool though

**Comment by tobyplowy** [comment]
> And nodes could have a wall in their middle, so that on one side water could flow in, while lava could flow in on the other side. Without them affecting each other... Such behaviour probably even goes against the block-oriented nature of minetest...

@Rogier-5 I think that is going to be a bit too complicated but it would be cool though (i have no idea how complicated it is I can't program :sweat_smile:) but minetest would definitely benefit from this `liquid_passthrough`

**Comment by paramat** [comment]
Certainly we need a way to avoid air bubbles, but who's going to code it? I have no idea how to do this.

**Comment by tobyplowy** [comment]
@paramat well I can't do it I can't program at all :(

**Comment by paramat** [comment]
I was being grumpy :]
Thanks for the texture submissions i will also look around for alternatives.

**Comment by tobyplowy** [comment]
@paramat maybe [this mod](https://forum.minetest.net/viewtopic.php?id=4627) could help.

**Comment by paramat** [comment]
Thanks had a look but all coral is in plant form, with a special trick to remove air bubbles, we need textures suitable for cubic coral, if anyone finds alternatives please post links here.

**Comment by tobyplowy** [comment]
@paramat why are the textures By @pithydon Not good?

**Comment by paramat** [comment]
They are good, i'm just asking for alternatives for consideration, if any exist.

**Comment by tobyplowy** [comment]
@paramat maybe there could also be some rocks spawning rocks made out of stone blocks And Coral blocks on them (also will you be making seaweed or only Coral blocks?)

**Comment by Xanthin** [comment]
I still love the sea modpack. 
But for alternatives I remember the [valleys_c mapgen mod](https://github.com/duane-r/valleys_c)  had some really good looking coral blocks, in my opinion.

**Comment by tobyplowy** [comment]
@Xanthin yeah they look good but they are not 16x16 pixels (therefore they don't really fit the style of Minetest)

**Comment by tenplus1** [comment]
Sea mod handles air bubbles well but the abm's they use to do it are laggy.  We need a new drawtype that allows liquids to passthrough plantlike nodes.

**Comment by tobyplowy** [comment]
@paramat https://forum.minetest.net/viewtopic.php?f=4&t=14132 pixelbox has sum underwater textures in it 
@kilbith is it allowed to use those Textures?

**Comment by tobyplowy** [comment]
@paramat i also made 2 textures for plants
![fdsvfvxx](https://cloud.githubusercontent.com/assets/16853304/16177316/3484a186-3629-11e6-8480-cc2741fbf30d.png)
coral plant
![coral plant](https://cloud.githubusercontent.com/assets/16853304/16177297/76a001a6-3628-11e6-9b98-c387c3437970.png)
and kelp

**Comment by sofar** [comment]
Alive coral is all sorts of colors in real world, but orange, and browns are prevalent, and since water is already blue, I wouldn't pick blue as a coral color.

Just making a texture is a fairly unfinished way to introduce a new game element. I'd argue that a decent PR adding coral should absolutely include the following elements:

* Full nodedef that's well thought out
* Has an actual use (can be cosmetic, of course, but e.g. can be crafted into at least one other node)
* Mapgen added placement in mgv7 (maybe schematics can work for underwater placement, or ore blobs)

Coral is relatively simple since it won't have the air bubble issues. The textures should definitely be crisp, but not neon.

Harvested coral should be all-white, since harvested coral is dead, and dead coral bleaches instantly. This may also teach young minetest players that the only way to enjoy colorful coral is when it's naturally growing, and even touching it kills it. There should also be an ABM for alive coral nodes that kills the coral if there's no water next to it.

Maybe coral can grow out over stone at proper water depths. Coral has a tendency to grow up and sideways at optimal depth, which is -2m, due to wave action energy being low enough at -2m to survive, but plenty light being available at those depths.

Of course, coral also should only grow in high-temperature biomes, so it should only appear in the right biomes.

**Comment by tobyplowy** [comment]
@sofar holy $#!7 you did your research. Maybe oceans could go a little bit deeper.  just an idea :smile:

**Comment by pithydon** [comment]
Coral skeletons are made of limestone so you could add limestone and make it craftable from coral.
The nodedef could be similar to stone and cobble.
Here is more textures
![coral_brown](https://cloud.githubusercontent.com/assets/18400998/16203309/e0b947ce-36d6-11e6-8835-116756b1c1ce.png)
![coral_orange](https://cloud.githubusercontent.com/assets/18400998/16203310/e0bc596e-36d6-11e6-8b9b-c1fc654b91b5.png)
![limestone](https://cloud.githubusercontent.com/assets/18400998/16203311/e0cf0b72-36d6-11e6-88a0-c69cf9957989.png)

**Comment by tobyplowy** [comment]
@pithydon nice textures. Can you Make Coral plant textures?

**Comment by pithydon** [comment]
You mean this [https://en.wikipedia.org/wiki/Russelia_equisetiformis](url)?
It's a little of topic but maybe I will make a texture for it.

**Comment by tobyplowy** [comment]
@pithydon no I'm referring to things like this [1](http://lazytoad.com/travel/turks/turks-Images/33.jpg) [2](http://impressive.net/people/gerald/2004/03/08/15-17-55-sm.jpg) [3](http://www.shorediving.com/images/453-04-Underwater-Omar_Paez.JPG)

**Comment by tobyplowy** [comment]
@pithydon no I'm referring to things like this [(1)](http://lazytoad.com/travel/turks/turks-Images/33.jpg) [(2)](http://impressive.net/people/gerald/2004/03/08/15-17-55-sm.jpg) [(3)](http://www.shorediving.com/images/453-04-Underwater-Omar_Paez.JPG) also thank you for offering your help it's really appreciated

**Comment by paramat** [comment]
sofar good input, good textures pithydon i'd like to use them

**Comment by tobyplowy** [comment]
@paramat will kelp be added?

**Comment by paramat** [comment]
Coral areas may have to be schematics due to containng several different colours, but i'll try placing by noise too, in concentrated clusters.

**Comment by sofar** [comment]
@pithydon those textures are not 16x16?

**Comment by sofar** [comment]
@tobyplowy we can't add kelp of anything plantlike until the engine provides a solution for the bubble problem.

**Comment by pithydon** [comment]
My computer says my textures are 16x16, so if they are not then my computer is lying to my face.

**Comment by sofar** [comment]
It could be just github displaying them cropped...

**Comment by tobyplowy** [comment]
@sofar just Coral blocks are good as well :\ (also when will the air bubbles be fixed?)

**Comment by sofar** [comment]
Possible coral implementation (WIP) #1160

**Comment by paramat** [comment]
Coral reefs will be added before 0.4.15.

**Comment by tobyplowy** [comment]
@paramat can this be closed?

**Comment by sofar** [comment]
I'd say corals are not enough, I'd like to keep this open to make sure we push the engine to a fix for underwater plantlike, at minimum.

**Comment by paramat** [comment]
^ Agreed.

**Comment by tobyplowy** [comment]
@sofar @paramat That's The Spirit +1

**Comment by C1ffisme** [comment]
@tobyplowy But is it the _Spirit of Minetest_? :wink: (Sorry, old joke.)

**Comment by paramat** [comment]
Request issue in the engine https://github.com/minetest/minetest/issues/4869

**Comment by paramat** [comment]
We still need a solution for underwater plants, but i can make a reed-like node with a new type of plantlike, see https://github.com/minetest/minetest/issues/4869#issuecomment-273189405 onwards.

**Comment by tobyplowy** [comment]
@paramat have any progress or news on this?

(Sorry if this comment is useless)

**Comment by paramat** [comment]
I have 2 ideas, one is the above, another is to combine the plant with the full cubic node below, both are new drawtypes (the above being a new plantlike meshoption) and are a little hacky so i need to discuss with other devs.

**Comment by tobyplowy** [comment]
@paramat I may not understand correctly so please correct me if I'm wrong,

 What I understand is you added a new drowtype that is a full cube that has two Planes sticking out on the top correct?

**Comment by paramat** [comment]
Correct, that takes 2 textures, one for the cube and one for the plantlike extension. The cube is the actual position of the node (seabed) and the planes are just textures that extend into the water nodes above by any amount. With some careful code it would be practical but would have to be "default:sand_with_waterplantname".

**Comment by tobyplowy** [comment]
@paramat I don't think that is the correct way to fix this also how will kelp work?

**Comment by paramat** [comment]
It's not ideal but no-one has thought up an alternative way.
Kelp would use 'visual_scale' to enlarge the planes to be several nodes high.

**Comment by tobyplowy** [comment]
> Kelp would use 'visual_scale' to enlarge the planes to be several nodes high.
> With these nodes you would dig them by digging the base cube, or maybe the selectionbox can be extended upwards to surround the plant also.

I'm Not really sure about that, If That's The Way It Is Gonna Be added I Rather Have This not be added

**Comment by paramat** [comment]
Code would replace the base cube when dug. The node in inventory would appear as just the plant. When the plant is placed it would replace the seabed node with it's own.
If the plant is decided to only grow on sand then the base cube having to be sand is no problem.
Seems ok to me and well worth a slightly hacky method.

**Comment by tobyplowy** [comment]
@paramat so let me get this straight if you would break kelp that would have the same effect as you breaking a tree that's one object correct? 

That sounds abit half assed doesn't it?

**Comment by paramat** [comment]
Do you have a better solution? it's very likely the choice is an unusual method or nothing at all.

**Comment by tobyplowy** [comment]
@paramat now that I think of it isn't your fix already possible by using a 3D model?

Also how will you fix stairs slabs and other blocks that are not full blocks?

https://forum.minetest.net/viewtopic.php?id=4627 seems to work maybe a modefied method of this can be used?

**Comment by paramat** [comment]
Sea mod uses nodeboxes that extend outside the primary node, my approach is faster to render because it will be only 2 flat planes extending out, as fast as plantlike to render and faster than a 3D model too.
Stairs and slabs can only be done if they are extensions of another full cube, so not useful.

**Comment by paramat** [comment]
See https://github.com/minetest/minetest/pull/5748

**Comment by paramat** [comment]
Plantlike rooted has been added, anyone want to make textures for some kind of underwater plant?

**Comment by tobyplowy** [comment]
@paramat I made some for farlands you can use those

**Comment by tobyplowy** [comment]
@paramat i hope these are good or atleast usefull
anemone
![mapgen_anemone](https://user-images.githubusercontent.com/16853304/28246992-f702b88c-6a27-11e7-96de-68c8c88ee0ec.png)
coral
![mapgen_big_coral](https://user-images.githubusercontent.com/16853304/28246993-f7052fa4-6a27-11e7-8c52-70175f789ddc.png)
![mapgen_blue_coral](https://user-images.githubusercontent.com/16853304/28246994-f7080152-6a27-11e7-91da-71596fc63d85.png)
![mapgen_orange_coral](https://user-images.githubusercontent.com/16853304/28246996-f71fd69c-6a27-11e7-8e36-5bcaeb68615a.png)
![mapgen_red_coral](https://user-images.githubusercontent.com/16853304/28246995-f71e9124-6a27-11e7-8979-20a0c99c347d.png)
kelp
![mapgen_kelp](https://user-images.githubusercontent.com/16853304/28247006-16f404d4-6a28-11e7-8047-1c0ab414a494.png)
![mapgen_kelp_2](https://user-images.githubusercontent.com/16853304/28247005-16f30598-6a28-11e7-9ce2-eeef1de8fefc.png)
sea grass 
![mapgen_seagrass_1](https://user-images.githubusercontent.com/16853304/28246999-f73e7214-6a27-11e7-9e7c-ef91760a99ee.png)
![mapgen_seagrass_2](https://user-images.githubusercontent.com/16853304/28247001-f74c5e92-6a27-11e7-8e37-a0474243c8b5.png)
![mapgen_seagrass_3](https://user-images.githubusercontent.com/16853304/28247000-f74c35f2-6a27-11e7-9648-e2f4e294e013.png)
sea grass block
![mapgen_sea_grass](https://user-images.githubusercontent.com/16853304/28246997-f7359a90-6a27-11e7-833a-790998356cd5.png)
![mapgen_sea_grass_side](https://user-images.githubusercontent.com/16853304/28246998-f737f740-6a27-11e7-98f9-2c9fde9922a4.png)

**Comment by paramat** [comment]
Thanks we will consider, kelp would be good for plantlike rooted as it is a stacked decoration.

**Comment by rubenwardy** [comment]
as said, I'm supportive of more variety in mapgen including sea plants

**Comment by tobyplowy** [comment]
If you need more or difrent textures just ask me :)

**Comment by paramat** [comment]
I intend to code kelp decorations using your texture.

**Comment by tobyplowy** [comment]
@paramat Thanks

**Comment by AntumDeluge** [comment]
I believe that the [sea modpack](https://forum.minetest.net/viewtopic.php?t=4627) is supposed to fill out water areas. Perhaps it could be helpful.

**Comment by paramat** [comment]
It doesn't use the new drawtype, it uses a buggy hack.

**Comment by tobyplowy** [comment]
Also it doesn't work anymore sadly enough

**Comment by paramat** [comment]
But i'll check the textures.

**Comment by tobyplowy** [comment]
@paramat Maybe you could also Add The Sea grass?
I think it would look good in the kelp forests

**Comment by paramat** [comment]
#1912 merged.
I think we now have 'some' underwater decorations, more to come of course, but this can be closed now.
We'll continue to consider your other textures and suggestions and feel free to continue discussion here.
