### ISSUE TITLE
New Savanna tree? (baobab)

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest_game#1131]
I would like to see [this tree](https://savannaenvironment.files.wordpress.com/2008/04/baobab.jpg) generate in Savannah biomes (the baobab tree)

**Comment by yyt16384** [comment]
It probably won't be added here... Try making an issue in moretrees mod.

**Comment by tobyplowy** [comment]
@yyt16384 could you give me a link to the github of moretrees mod I can't seem to find it

**Comment by yyt16384** [comment]
@tobyplowy https://github.com/minetest-mods/moretrees

**Comment by tobyplowy** [comment]
@yyt16384 thank you :)

**Comment by sofar** [comment]
Can this be closed then?

**Comment by tobyplowy** [comment]
@sofar if there's no interest for this to be added to the base game then yes it can be closed.

**Comment by paramat** [comment]
We could consider a second savanna tree. The issue would be whether to add another wood for it of just use standard generic 'wood'.

**Comment by tobyplowy** [comment]
@paramat the Idea is to use acacia wood

**Comment by tobyplowy** [comment]
@paramat ![savannah](https://cloud.githubusercontent.com/assets/16853304/16036793/c661abfe-321d-11e6-9f97-acd8dc9887ae.png)

**Comment by tenplus1** [comment]
+1 for new tree using acacia wood.

**Comment by everamzah** [comment]
What in the wild world of sports is going on here?

**Comment by paramat** [comment]
No it can't use acacia wood, obviously. We would have to add baobab wood.

**Comment by tobyplowy** [comment]
@paramat + for New wood :D

**Comment by sofar** [comment]
Off:

@everamzah flat world, different textures, non-smooth lighting.

**Comment by sofar** [comment]
I don't feel this adds much diversity or gameplay, even with a new wood type. Still think that it would fit better in `moretrees`.

A better focus would be to brush up on the bushes PR and see how we can enrich gameplay / landscape diversity that way I think - Now that most biomes have 3-4 elements to them (trees, logs, mushrooms, grasses, flowers, some multiple of those) this isn't that urgently needed.

Off: underwater biomes are still very empty - this should be a higher priority but probably requires engine changes to handle underwater plants.

**Comment by tobyplowy** [comment]
@sofar I personally think a new tree would be awesome. but what you are saying is actually kind of true. I think the bushes are a lot more awesome and corals are something which needs to be added. (but the corals really need to be added, because oceans are so boring)

**Comment by tobyplowy** [comment]
@everamzah @sofar the texture pack is actually called [summerfields](http://summerfields.info/?) in case you wanted to know :D

**Comment by paramat** [comment]
I agree with sofar, another savanna tree is low priority and bushes are needed more.

**Comment by paramat** [comment]
A second tree in savanna might be considered in future, but not soon.

**Comment by paramat** [comment]
Closing, we can consider extra trees in future, for savanna bushes are needed first.
Also, a new tree means a new wood type and we have quite a few.

**Comment by RHRhino** [comment]
> No it can't use acacia wood, obviously. We would have to add baobab wood.

@paramat I think minetest_game already have enough wood types, but it is in lack of tree deversity. Why can't we use the current wood types and just create more tree models with them?

**Comment by paramat** [comment]
Yeah we can have 2 types of pine etc.
