### ISSUE TITLE
sprinting?

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest_game#1132]
We have crouching why don't we have sprinting? It's quite boring to cover large distances of terrain without being able to Sprint. ( also please don't say thers mods for this)

**Comment by everamzah** [comment]
You can just use fast mode without turning on free move.  Then hold Use (default [E]) to go fast.  It doesn't deplete stamina, or anything like that, but you can cover areas faster.  It's also configurable how fast fast mode is.

**Comment by tenplus1** [comment]
github.com/tenplus1/hudbars github.com/tenplus1/hud_hunger github.com/minetest-mods/stamina - these will supply sprinting to your game

**Comment by tobyplowy** [comment]
@tenplus1 thank you, I will take a look at them later

**Comment by paramat** [comment]
This is an engine issue, there's an issue open about this (and i strongly disapprove).
