### ISSUE TITLE
Water/lava buckets in creative mode should not run out of water/lava

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest_game#1133]
The title says it all (if you use a bucket in creative it's empty this is really annoying if you're trying to build something, I know there's water source blocks but there's no point for them to be there if the buckets work correctly, also in the newest version of Minetest (stable  0.4.14) the water source blocks are invisible in the inventory

**Comment by paramat** [comment]
Just use the source nodes instead.

> in the newest version of Minetest (stable 0.4.14) the water source blocks are invisible in the inventory

Nope, have you updated both engine and game? inventory cube was removed recently.

**Comment by paramat** [comment]
#1135 was closed unmerged.

**Comment by paramat** [comment]
Closing since we decided against the PR.
