### ISSUE TITLE
lava does not seem to generate correctly

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest_game#1138]
Why does lava generate at Different Heights? in the same pool of lava?
![lava](https://cloud.githubusercontent.com/assets/16853304/16057602/1ca3b9aa-327b-11e6-96f8-eaa2c00c6e46.png)
![lava](https://cloud.githubusercontent.com/assets/16853304/16057553/ec7b99aa-327a-11e6-81cf-4ffc93c2ea5b.png)
![lava](https://cloud.githubusercontent.com/assets/16853304/16057691/7ee1d606-327b-11e6-854c-e7ea1b043dfc.png)
![lava](https://cloud.githubusercontent.com/assets/16853304/16057453/7cc14196-327a-11e6-8e94-e49dc265c436.png)

**Comment by paramat** [comment]
That's how cavegen works, caves are a combination of short sections, each of which may have a blob of lava placed within it, so inconsistent blobs at different levels are common.

**Comment by tobyplowy** [comment]
@paramat cant it be fixed?

**Comment by tobyplowy** [comment]
@paramat water Can do it so Why Not lava?I know this is probably a stupid question

**Comment by paramat** [comment]
Flooded caves often have blobs of water too just like this, lava caves don't happen at sea level and the water caves at sea level work differently, they use the maogen 'water_level' value to make water lavel consistent, this can't be done underground, so each section of cave has it's own liquid level and they often don't match up.

Its not a bug just a result of how it works, if you study the generation code and think about it you'll see it can't be fixed, it perhaps could be improved.

**Comment by Rogier-5** [comment]
Please don't change this. I think the lava flows and waterfalls are a nice *feature* in caves.

**Comment by paramat** [comment]
I agree, i don't think it should be changed.
