### ISSUE TITLE
Bones API for dumping items on death

### ISSUE THREAD

**Issue by raymoo** [minetest/minetest_game#1148]
I suggest the addition of two functions to the bones API:
- register_on_placebones(func(player, bones_inv)) - Registers a callback to be called when bones are placed for a player. The registered callback receives the player's ObjectRef and the inventory of the new bones node. This can be used to write callbacks to add items to the player's bones.
- register_dumpable_inv_list("listname") - Registers an inventory list to be dumped into a player's bones on death. If the bones node is full, the remaining items are dumped into the world. This is a convenience function that could be written in terms of register_on_placebones.

This would make it easy for mods that add different kinds of inventory to work nicely with bones.

**Comment by paramat** [comment]
Why would we need to add items on death?
Is this request affected by the latest bones commit which adds a drop on die option?

**Comment by raymoo** [comment]
Mods (for example armor mods) might want to dump their non-main inventory into the bones (or spit out if there is no room)

**Comment by everamzah** [comment]
Adding inventory can occur on_die or on_respawn in said external mod.  Using find_nodes_in_area and matching nodemeta owner with player would ensure said inventory is added to the correct bones node.

**Comment by raymoo** [comment]
What if the player dies multiple times in the same place? You would have to check all the bones and split the inventory between them, in case one is full. And why rely on a hack instead of having an API for a common use case?

**Comment by paramat** [comment]
For simplicity, and because we are insanely understaffed, if something can be done reasonably well in a mod it should be. There needs to be a need, and a need for an API instead of doing it in a mod.

**Comment by raymoo** [comment]
It can certainly be done, as everamzah mentioned, but the question is whether it's "reasonable". There is some need since at least 3D armor dumps armor into bones on death, and it currently uses everamzah's method.

> insanely understaffed

Does that mean it would be more likely to be accepted if there was already a pull request?

**Comment by paramat** [comment]
Nope, whether there is a pull or not doesn't affect our judgement of the feature.

**Comment by t4im** [comment]
You're getting pushback because 2 global callback registrations are overkill for a feature affecting only one type of node and might only be useful to one type of mod. :-)

A simple individual node-callback or a wrapable function would be more reasonable, if it were needed.

But you could probably just wrap the bone's `on_construct(pos)`:
(not tested, but it's just to get the idea)
```lua
local bones_on_construct = minetest.registered_nodes["bones:bones"].on_construct

minetest.override_item("bones:bones", {
	on_construct = function(pos)
		if bones_on_construct then -- Call any existing constructor first
			bones_on_construct(pos)
		end

		minetest.after(0, function()
			-- do your thing, you should have all the nodemeta in here
		end
	end
})
```

**Comment by raymoo** [comment]
With the changes to bones, modders who want their inventories to be compatible with bones now have to check the server's configuration options to see what do do on player death. This isn't very good separation-of-concerns-wise.

**Comment by everamzah** [comment]
The default is the traditional behavior.  The bones node very well should be there.  If one starts Minetest with bones_mode = drop, then they can also modify 3d_armor's ARMOR_DROP.  Wildly off-topic but, I'd love to see the new settingtypes.txt used in 3d_armor, which would make it trivial for one to adjust that setting.

**Comment by raymoo** [comment]
The point is that every modder shouldn't have to write the same code checking which bones mode is being used.

**Comment by t4im** [comment]
Will #1229 address your needs?
I didn't see much reason why we would hardcode the inventory-listnames we go through either.
And exposing it as API is just a globalisation away from that.

**Comment by raymoo** [comment]
Yes, I think so.

**Comment by paramat** [comment]
#1229 merged.
