### ISSUE TITLE
Unable to place preserved leaves while building near edge with shift

### ISSUE THREAD

**Issue by asl97** [minetest/minetest_game#1154]
I created this issue because it doesn't seem to be getting much attention and so that it doesn't get forgotten.

---

one can sneak at anytime but can't easily not sneak when placing leaves near a edge without falling when one want to preserved the leaves.

see additional comments on https://github.com/minetest/minetest_game/pull/868#issuecomment-227586005

ps: feel free to change the title.

**Comment by paramat** [comment]
We could perhaps consider a different key. But if that key is to be sneak then the most likely use (players building with non-decaying leaves) should be the one not requiring sneak.
The issue of needing sneak when placing leaves when near edges is i think not a big issue, i almost never use sneak and i think players over-use it. If there's danger of falling just place a temporary platform.

**Comment by pithydon** [comment]
Sounds like the apple approach "you're holding the phone the wrong way".

**Comment by yyt16384** [comment]
> If there's danger of falling just place a temporary platform. When building it's not often a player needs sneak.

But you need sneak to place the temporary platform, unless you build it from ground, which is tedious in many cases.

Another case of needing sneak is to build around containers or other nodes with `on_rightclick`.

**Comment by tobyplowy** [comment]
@pithydon lol :smile:

**Comment by paramat** [comment]
yyt16384 yes, but the majority of the time sneak is not needed, so:

> when players build with leaves they are much more likely to want non-decaying leaves. Using sneak when building is irritating so the most likely use should not require sneak.

**Comment by paramat** [comment]
@sofar @rubenwardy any thoughts?

**Comment by C1ffisme** [comment]
@paramat Another problem is that you can't place these preserved leaves or place things on blocks with `on_rightclick` while flying, since the sneak key is used for descending.

**Comment by rubenwardy** [comment]
I can see how this could be misleading to users - ie, there's no indication that the leaves placed will decay. I can't see how to fix this in a nice way though, and I consider this a minor issue

**Comment by paramat** [comment]
@sofar @sfan5 @Ekdohibs @ShadowNinja any opinions?
See my comments, i think this should be closed.

**Comment by sofar** [comment]
The issue here is that the code allows placement of decaying leaves with shift. IMHO we can remove that functionality altogether. Player-placed leaves should probably never decay for simplicity.

**Comment by asl97** [comment]
Personally, I don't really support @sofar suggestion but it's better than the current possible confusing mess.

Possibly with a new node without the decay group for optimization.

**Comment by sofar** [comment]
@asl97 nahh, let's not add 5 new nodes to solve this? This is such an insignificant problem, it doesn't deserve much more than the deletion of 3 lines of code if you ask me.

**Comment by paramat** [comment]
> Player-placed leaves should probably never decay for simplicity.

The idea was that placing decaying leaves is needed for creating trees, so i'm not sure we can do this.

This is an insignificant problem so closing.

**Comment by asl97** [comment]
A tree with non-decaying leaves doesn't look different from a tree with decaying leaves even though taking it down again would be troublesome.

If you can call an usability problem insignificant and call that the reason for closing, you can probably close up most of the issues.

**Comment by asl97** [comment]
In other words, a tree IS a tree.
