### ISSUE TITLE
New command, time day and time night

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest_game#1157]
I think there should be a new command called time day, and time night, if you type this command it would basically set the time to mid-day or midnight it's much easier than typing time and a number.

**Comment by Rogier-5** [comment]
I suppose your main problem is with the number, as it not very intuitive ? Because `/time night` is more typing than `/time 0`, and `/time day` is not much shorter than `/time 12000`...

To me `/time day` and `/time night` seem a bit too specific. I'd suggest something like `/time 11:00` (or `/time 11:00[ap]`) ? Optionally with a shorthand `/time 11:` or `/time 11h`, `/time 23h`, `/time 11a` and `/time 11p` ?

**Comment by tobyplowy** [comment]
@Rogier-5 your idea is a lot better ( my idea was just to get midnight and midday because that's the only time I really care about in Minetest for building but your idea is a lot better 👍

**Comment by godisgood4** [comment]
@Rogier-5 👍

**Comment by sofar** [comment]
This is clearly `mod` terrain. All the functionality needed is present, all you're looking for is a "simpler" way to interact with it for a *very specific use case*. Suggest closing this (too specific).

I'm pretty sure there are like 5 mods that do this in some way already.

**Comment by paramat** [comment]
Indeed this would be adding code to avoid typing /time 0 or /time 12000 which is not remotely problematic.

**Comment by Rogier-5** [comment]
You could very easily create a simple mod for day and night yourself: create a mod directory, in it create a text file `init.lua` with the following contents:
```
minetest.register_chatcommand("day", {
        func = function(player, param)
                minetest.set_timeofday(0.5)
        end
})
minetest.register_chatcommand("night", {
        func = function(player, param)
                minetest.set_timeofday(0)
        end
})
```
And there you go: `/day` sets noon, `/night` sets midnight.

**Comment by tobyplowy** [comment]
@Rogier-5 wow thank you

**Comment by benrob0329** [comment]
As of right now you can type in /time 12:00 or /time 0 (or 0:00)
