### ISSUE TITLE
New time command, /time stop

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest_game#1158]
/time stop, it should basically stop the day-night cycle from happening it just freezes day-night cycle Not time (you're probably wondering why this could be useful well let me tell you) this is really useful for building because it's really annoying having to worry about time in creative constantly having to type the command it's quite annoying. :)

**Comment by Rogier-5** [comment]
Does `/set time_speed 0` solve your problem ?

**Comment by tobyplowy** [comment]
@Rogier-5 yes it does, sorry. :P
