### ISSUE TITLE
Stair corners missing

### ISSUE THREAD

**Issue by godisgood4** [minetest/minetest_game#1159]
https://www.dropbox.com/s/tgn4cymz5ftvriy/Screenshot%202016-06-25%2011.07.34.png?dl=0

Stairs don't have corner pieces, as you can see in the screenshot above. Slabs can be used, but the center 1/4 of the node doesn't stick up anymore. Messing around with the screwdriver yields no results.

**Comment by Fixer-007** [comment]
I was thinking about that just half a day ago. It is not only stair corner needed, but also inverted stair corner (for opposite cases).
With those two blocks you can make nice corners in bottom and up positions and that will be solid foundation for building without moreblocks or xdecor installed.

Do I want that? Sure! Only downside is additional two pages of those items (I don't care about that personally :))

**Comment by tenplus1** [comment]
Would this help: https://github.com/tenplus1/stairs

**Comment by sofar** [comment]
These are missing on purpose - mods like `moreblocks` and others add them.

Arguably the *best* place to fix this would be in-engine (a new drawtype), not in `minetest_game`.

**Comment by paramat** [comment]
Corners are i feel not fundamental and needed enough to add to the basic game.

**Comment by everamzah** [comment]
Or, take the shapes out of the creative menu, add a workbench/saw, add inner and outer stairs, microslabs, and call it a day.

**Comment by tobyplowy** [comment]
Maybe they could work like Minecraft if you make a corner they automatically connect, so you don't have to add a new Page of blocks to the creatieve inventory.

**Comment by tobyplowy** [comment]
I also really like the corners it look's good, I have some building designs I made in Minecraft but I cannot make them Look good in minetest because of the cornerd stairs :/

**Comment by everamzah** [comment]
The thing is, with a new drawtype - and that's interesting - but, nodeboxes were marked experimented for a long time in lua_api.txt, and they really can slow down rendering a lot depending on the nodebox.  minetest_game should use them.  Stairs themselves are an .obj file.  Lighting doesn't seem to work properly with nodeboxes, particularly smooth lighting.  There's some multiple issues with all of this, I gather.

**Comment by sofar** [comment]
I wouldn't implement it as a nodebox - it would be a builtin type where the mesh is made in C++, and zero code in Lua needed to manipulate it (neither needed nor possible, actually).

**Comment by paramat** [comment]
A drawtype might be best in future, but for now the consistent way would be meshnodes and adding corners to the stairs API.

**Comment by C1ffisme** [comment]
How about a drawtype that uses an 8-bit value to show any formation of microblocks?

A block contains 8 microblocks, so an 8-bit value means you can show any combination of those microblocks at a time.

The only trouble is making a good API in lua for how they would be shown.

**Comment by sofar** [comment]
@C1ffisme while that is a valid solution, it would require a lot of Lua code to drive, and it would be subject to lag.

**Comment by pithydon** [comment]
My little subgame has this feature. Maybe posting a link here will help.
Hope my code is not too crazy.
[https://github.com/pithydon/middle_test](url)

**Comment by C1ffisme** [comment]
@sofar Not necessarily, I imagine it would work a bit like connected nodeboxes. Perhaps each node of this drawtype would come with a param holding the 8 bit number, and this param could be edited by code? (E.G., on_rightclick with a screwdriver changes the number between a few values that represent rotated versions of the same shape.)

**Comment by godisgood4** [comment]
I hope this doesn't sound too dumb, but what about just adding a stair corner node and a new crafting recipe, since corners are a different shape than stairs and would need to be crafted differently.

**Comment by tobyplowy** [comment]
@godisgood4 I think the idea By @C1ffisme allows for more customizability

**Comment by sofar** [comment]
@C1ffisme since stair nodes use `paramtype2 = facedir`, the param2 value isn't available to determine what parts should be drawn. So it would *have* to add a new drawtype and a lot of custom code to properly draw them, which would make it all Lua-based.

That's a stiff penalty for very little gain, I don't think anyone would want to maintain that engine code. I wouldn't.

Connected nodeboxes are nice and simple right now because there's very little to no Lua code needed right now, making it fast, not laggy, and easy to work with for builders. This is the opposite.

**Comment by sofar** [comment]
@godisgood4 that's why several mods offer this option.

**Comment by paramat** [comment]
I feel fairly neutral about this. If we add these 2 corner nodes i feel it should be done consistently by adding meshnodes to the stairs mod.

**Comment by tobyplowy** [comment]
@paramat yay :D

**Comment by rubenwardy** [comment]
Certain builds look weird without corner blocks. I'm not 100% on whether this should be in MTG though

**Comment by tobyplowy** [comment]
Maybe it could also be possible to click on it with a screwdriver to turn it into a normal stair so if you need a normal straight stair in a corner for some reason you could do it that way?

**Comment by pithydon** [comment]
@tobyplowy My unfinished subgame does it that way.

**Comment by tobyplowy** [comment]
@pithydon what is the name of the sub game do you have a link, I'll be sure to check it out thanks for letting me know :D

**Comment by sofar** [comment]
I'm in favor of leaving this in the mod realm for now.

**Comment by paramat** [comment]
Yeah i agree.

**Comment by paramat** [comment]
3rd disapproval from nore
http://irc.minetest.ru/minetest-dev/2016-07-10#i_4647245
Closing.
