### ISSUE TITLE
Water lilies shouldn't spawn on river water

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest_game#1166]
It looks odd when water lilies spawn in floating river water. They dig a hole in the water surface

![screenshot_20160626_223247](https://cloud.githubusercontent.com/assets/16163058/16364701/22a537ee-3bee-11e6-97b6-dc80ffeb0ba5.png)

**Comment by paramat** [comment]
I think they're being placed correctly at sea level, then after mapgen the river water starts to flow and flows around them, because they are nodes. This only happens at river mouths. Mgvalleys places river water vertically, in other (future) river mapgens those waterlillies would actually beplaced on sea water.

Not sure this can be fixed but i'll look into it.

**Comment by paramat** [comment]
![screenshot_20160627_083900](https://cloud.githubusercontent.com/assets/3686677/16372181/31cda56c-3c43-11e6-843c-79378f13ba80.png)

Yeah i don't know how to fix yet but will keep it in mind. I'm not sure it can be called a bug, more a request for better behaviour.

**Comment by MarkuBu** [comment]
Maybe remove them in floating water. There was a discussion to remove torches in floating water. I don't know what was the result of this discussion, but maybe it is a good idea to implement a generic system that removes specific nodes in floating water like torches, water lilies, mushrooms and so on

**Comment by paramat** [comment]
Yeah we might have 'on flood' callbacks in future, that would work.

**Comment by 0-afflatus** [comment]
Surely lilies should spawn on fresh water rather than salt. An on_flood callback would be useful.

**Comment by paramat** [comment]
Many Minetest lakes at y = 1 may actually be freshwater, default:water is not necessarily salt water, however river water certainly is. Spawing water lilies on rivers wound multiply this problem, and some parts of rivers are unsuitable due to steep slope and 'fast flow'.

**Comment by t4im** [comment]
> Yeah i don't know how to fix yet

Why not make those nodes [floodable](https://github.com/minetest/minetest/blob/fa0bbbf96df17f0d7911274ea85e5c049c20d07b/doc/lua_api.txt#L3549)?
I would love to see that for grass and flowers as well.

**Comment by paramat** [comment]
Of course, duh, will do this.

**Comment by paramat** [comment]
See #1170

**Comment by paramat** [comment]
#1170 is merged.
