### ISSUE TITLE
4 glitches in Minetest version 0.4.14

### ISSUE THREAD

**Issue by WSDguy2014** [minetest/minetest_game#1193]
I found 4 glitches.
1. Any falling sand entities will stuck forever or going to be despawning at any opened fence gate. Must be on NON-SOLID block for all any opening fence gates!
   [EDIT by paramat: Now fixed by #1231 ]
2. Removing a invisible block on all 4 mesh doors (I don't like new mesh doors) and any falling sand entities will stuck forever or going to be despawning.
3. You can break obsidian glass door with bare hand, but on obsidian glass block don't.
   [EDIT by paramat: Now fixed by #1194 ]
4. Any ghost slabs.
   [EDIT by paramat: Now fixed by new slab code]

How to reproduce: https://www.youtube.com/watch?v=WvlIkifyJy4

**Comment by tenplus1** [comment]
https://github.com/minetest/minetest/pull/4315

**Comment by paramat** [comment]
@sofar perhaps you can look at these doors bugs?

**Comment by sofar** [comment]
Interesting, I know I checked sand falling onto doors. I'll have to figure out why fence gates are different.

**Comment by WSDguy2014** [comment]
@sofar, can you create a issue for 1st bug from my issue on minetest engine?

**Comment by t4im** [comment]
The collision box of the open gate is less than 1m high, that's why the falling node is jerking around so much.

However, it is also lacking a placeholder node. You can already place a solid node into the open gate and the falling node will solidify.

We could either keep both collision boxes the same, or we add a placeholder node to the fence_gate. Either is independent of any engine improvements and one of them should be done.

**Comment by paramat** [comment]
3. Make gate collisionbox full height?

**Comment by t4im** [comment]
> Make gate collisionbox full height?

That stops the node indeed from moving. But without there being a walkable node below, or the falling node being able to fall down to one, it won't solidify.
Right now the open collision-box hangs into an air node, making it impossible for the falling node to "touch ground".

One could change that behavior in builtin based on monitoring velocity, but that might be error prone and lead occasionally to nodes solidifying mid-air when loading chunks or colliding with other entities.

**Comment by DonBatman** [comment]
Just a thought. Since irl putting sand on a fence or gate would result in the sand falling to the ground. Could you add a grou2to the gate like fall_through = 1. Then have the falling sand fall through the gate and stop at the ground? The sand would have to remain an entity.

**Comment by t4im** [comment]
For the sand there is no node below it, just air. So no group to check.
There is a collision-box of a node next to it, but its collision is enforced by the physics engine, not the falling node.

**Comment by DonBatman** [comment]
My mistake. I still would like my suggestion considered for fences, gates and others.
As for this issue I agree that reducing the collision box would be good.

**Comment by paramat** [comment]
> 1. Keep both collision boxes the same size. The node can fall to the ground.

I like this, the fence gate is on the border between 2 nodes anyway and it would be reasonable for loose material to fall either side of it, will make a PR.

**Comment by paramat** [comment]
See #1231

**Comment by jhcole** [comment]
#1231 only fixed the problem in the -z direction. The collision box for the open fence gate still extends too far in the -x direction.
![screenshot_20160917_223406_1](https://cloud.githubusercontent.com/assets/1099507/18612406/edc451b6-7d26-11e6-8c04-fb1207d236d7.png)

**Comment by paramat** [comment]
Oh yeah, will fix.

**Comment by WSDguy2014** [comment]
@jhcole, this screenshot, texture for fence gate looks like old texture from more tree type mod?

**Comment by paramat** [comment]
#1292 merged.

**Comment by WSDguy2014** [comment]
In 4th one. In survival mode, you need to hold only any slabs, amount of 2 and try to make a full block now, to produce a ghost slab, if you place another any slab or rejoin world, ghost slab disappear.

**Comment by paramat** [comment]
Yes we have merged changes to slabs so please recheck that bug.
Are you saying ghost slabs are fixed?

**Comment by WSDguy2014** [comment]
@paramat, I didn't see, for merged a bug that fixing the ghost slabs.

**Comment by paramat** [comment]
Bugs 1, 3 and 4 are fixed.

**Comment by paramat** [comment]
Tested the remaining bugs, all fixed.
