### ISSUE TITLE
Beds: if kicked while in bed, no wield item after restart

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1196]
Decided to play on Cash World server, it has "kick after inactivity" thing, while I was in bed, it kicked me, after restart I noted absence of my hand, I forgot to inspect player from third view. After resleeping it appeared back to normal.

Server: 0.4.14-dev, MTG of probably 0.4.14-dev version, with mods and some probable changes.
I have not tried to reproduce it on localhost yet.

**Comment by sofar** [comment]
Did you lose the item in the hand, or did the `wieldview` mod cause a visual bug?

**Comment by Fixer-007** [comment]
Server does not have this mod, iirc not only hand was invisible, cross was too.

**Comment by An0n3m0us** [comment]
I cannot recreate this bug; has it happened since?

**Comment by An0n3m0us** [comment]
Tried multiple times but I cannot recreate this issue.
