### ISSUE TITLE
2D Player texture on front view looks like mirrored. Instead of normal.

### ISSUE THREAD

**Issue by WSDguy2014** [minetest/minetest_game#1197]
![2d skin bug](https://cloud.githubusercontent.com/assets/13905392/16899801/70a7f720-4c19-11e6-8160-5cfe7823cdc6.png)
I'm on Minimal Development Test subgame, for testing 2D textures. It's a bug on 2D player front texture, because, 2D player front texture looks like a mirrored in-game. Must be normal look...

**Comment by paramat** [comment]
Note: look at hands to see the bug.

This is an engine issue please can you copy this across to there?

**Comment by WSDguy2014** [comment]
@paramat, Maybe...

**Comment by paramat** [comment]
Issue is opened in engine.
