### ISSUE TITLE
Nyancat textures incorrectly named

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1201]
@rubenwardy they should start with nyancat_ ...
Please could the texture names be improved as this is the ideal time to do this:
nyancat_back.png
nyancat_front.png
nyancat_rainbow.png
nyancat_side.png

**Comment by rubenwardy** [comment]
This is only a guideline. For texture pack compatibility reasons I've kept them the same.
Maybe there could be texture pack aliases, so that when a texture pack is loaded, textures are renamed to match the correct ones? Would require a new packet to send info to client.

**Comment by paramat** [comment]
It's more than a guideline, it'a rule. I think it's a good time to break texture pack compatibility, names are easy to change. Might as well do this now rather than any other time.

**Comment by sofar** [comment]
neutral, I'm not opposed to breaking texture packs, and texture packs could provide textures with the old and new names simultaneously.

**Comment by paramat** [comment]
#1207 merged.
