### ISSUE TITLE
Deprecations warnings in default mod

### ISSUE THREAD

**Issue by everamzah** [minetest/minetest_game#1205]
The sapling growth uses `get_mapgen_params`, which is deprecated.

```
<WARNING> 2016-07-18 09:03:24: [Server] get_mapgen_params is deprecated; use
get_mapgen_setting instead
```

**Comment by Zeno-** [comment]
I'm treating it as a bug because it should not happen in the default game (we should use up to date methods)

**Comment by paramat** [comment]
Missed this, will do.

**Comment by paramat** [comment]
#1206 merged.
