### ISSUE TITLE
Rotated stair rendering not perfect

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1211]
Here is basic scenario with reversed stair (look in middle and little below). Minecraft rendering is way better, while Minetest has rotated texture that looks bad and out of place. I think slabs also have this problem. Any concerns about this?
![2016-07-19 23_20_13-minetest 0 4 14-04fb109-6621dae opengl 4 5 13416](https://cloud.githubusercontent.com/assets/16494741/16965570/750611de-4e09-11e6-96c8-5fc3f268e589.png)
How it looks in Minecraft:
![2016-07-19 23_20_31-minecraft 1 10 2](https://cloud.githubusercontent.com/assets/16494741/16965571/75068a2e-4e09-11e6-8fba-03ddaae89246.png)

**Comment by RHRhino** [comment]
@Fixer-007 Not only the texture is a problem, also the lighting. Nodeboxes are lighted differently than full blocks. I think it is not fixable until the lighting has been fixed before.

**Comment by paramat** [comment]
This is expected, the texture is rotated as is necessary for most uses.

**Comment by Fixer-007** [comment]
I understand that in some way it is a feature actually, but it looks not good in some cases. Not sure if needs closing, maybe this needs discussion? Or everyone is fine with the way it is made?

**Comment by paramat** [comment]
Indeed it looks bad here due to the shading. The fix would be to have an option to not rotate the textures when the shape is rotated.

**Comment by tobyplowy** [comment]
@Fixer-007 I also think the textures Look bad on upside down stairs 
@paramat it's not only the shading it's also the textures, it's mostly the textures actually.

**Comment by paramat** [comment]
Yeah i mean the shading (highlight and shadow) i used on the texture, that assumes light coming from above.

**Comment by tobyplowy** [comment]
@paramat oh okay sorry for the misunderstanding :D

**Comment by Fixer-007** [comment]
>The fix would be to have an option to not rotate the textures when the shape is rotated.

That will be nice, maybe even specified on per block basic in lua.

**Comment by paramat** [comment]
Yes per-node.

**Comment by tobyplowy** [comment]
@Fixer-007 @paramat @RHRhino will this get fixed?

**Comment by Fixer-007** [comment]
maybe in a future

**Comment by RHRhino** [comment]
Maybe we can solve this by adding another tool next to the screwdriver? One tool to only rotate the node and one tool to only rotate the texture?

**Comment by tobyplowy** [comment]
@RHRhino I doubt that will work but +1 for me

**Comment by paramat** [comment]
I'm not sure it would be possible to have an option to not rotate textures when a nodebox is rotated, the textures may be locked to the shape. Creating differing nodes to fix this would result in 24 nodes for the 24 rotations.

**Comment by RHRhino** [comment]
> I'm not sure it would be possible to have an option to not rotate textures when a nodebox is rotated, the textures may be locked to the shape.

@paramat Oh I should have mentioned that I only mean rotations for nodeboxes with the same textures on all sides (like in this example of the stone bricks stairs), so I'm talking about all stairs and slaps in minetest_game. It does not make sense to only rotate the shape of a cube or to only rotate the textures of a nodebox with different textures, which are propably shape depenend.
BTW while thinking about it, I recognized that we don't really need texture rotation (therefore also the other tool) for nodeboxes with the same textures on all sides at all.

**Comment by rubenwardy** [comment]
It seems this is an engine issue? Fixable by adjusting lighting or stopping textures from rotating with the node box

**Comment by paramat** [comment]
Yes it's more of an engine issue, but not sure this should be closed.

**Comment by paramat** [comment]
We could add another bit to facedir that selects whether to rotate the texture too.

**Comment by Fixer-007** [comment]
Should I open this in engine section?

**Comment by paramat** [comment]
Yes please.

**Comment by Fixer-007** [comment]
and I forgot to reopen this in engine section...
