### ISSUE TITLE
Add more groups to nodes

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest_game#1213]
It would be helpful sometimes if nodes have more groups to find them.

e.g. fence group for all fences and gates, door group for doors, trapdoors and gates, a glass group for any glass node (glass block, glass pane, obsidian, glass door...)

This would make "find_node_near" and any other function that uses groups more powerful

**Comment by paramat** [comment]
We only add them when needed for simplicity, so instead of adding as many as possible, please request them when needed in modding.

**Comment by MarkuBu** [comment]
I have a current need for fences and doors for my mobs mod, maybe some other groups. I can overwrite the nodes, but I think it doesn't hurt if they are in minetest game

I can make a PR if that helps

Are there any disadvantages when adding more groups?

**Comment by paramat** [comment]
The problem then is what you want in each group may differ from what others want.
However we can deal with that if it arises, since you have a need do go ahead with a PR.

**Comment by MarkuBu** [comment]
There might be situations where people have different needs, but there are things where everything is clear. Currently I can only see it from my mobs mod. I need to search for groups of nodes with find_node_near, find_nodes_in_area and similar functions, which can use groups for search.

Doors can have the group "door", ladders can have the group "ladder", fences and fence gate can have the group "fence", stairs can have the group "stair" and so on

There are already examples for that like wood, tree, leaves and even saplings.

**Comment by paramat** [comment]
No problem, what you suggest so far seems reasonable.

**Comment by cx384** [comment]
A long time ago a have made a mod which adds a tool that do something which ores.
If group ore were available it would be easier to get all ores in this situation.

I think it is a great idea to add more groups but maybe it is not good to add too much groups because some are really unnecessary for example group fragment (mese_fragment, obsidian_fragment).

**Comment by paramat** [comment]
Author has left MT. I did ask for a PR from the author but one was not made.
