### ISSUE TITLE
Different colors of grass and leaves

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest_game#1214]
Grass in Minetest is a little bit to uniform. Some variations, maybe depending on the humidity, would be nice

![bildschirmfoto vom 2016-07-22 10-48-24](https://cloud.githubusercontent.com/assets/16163058/17051712/5a8e4aea-4ffa-11e6-97a1-4c855c419dab.png)

also some variations of leaves colors like with the valley_c mod would make minetest less monotonous

![bildschirmfoto vom 2016-07-22 10-56-49](https://cloud.githubusercontent.com/assets/16163058/17051888/452081d6-4ffb-11e6-9df3-b483a0806be8.png)

**Comment by GReaperEx** [comment]
Do you mean randomly, per biome, per type of tree, a combination or those? I too think it would be nice, but don't know how difficult it'd be to implement...

**Comment by MarkuBu** [comment]
Leave color is already done in valley_c mod. It is just random and uses the colorize tag. Harvesting leaves would give default leaves of the default color. 

Grass color could be done by humidity and maybe heat and a little bit randomness. Dark green grass in wet biomes, yellowish grass in dry biomes

Maybe I try to make a little mod to demonstrate how different grass colors would look like

**Comment by paramat** [comment]
Per-tree variation of leaf colour may not be too complex and might be acceptable in mtgame.

As for MC-type per0node smoothly-varying grass colour i strongly oppose, and have argued at length with RBA and others. Being a mapgen / biome dev i know how complex this is, but also smooth transitions are unsuitable for MT character where every other aspect of biomes changes abruptly at biome borders.

To get some variation we could subdivide biomes and use varying colours per biome. The biome system allows up to 256 biomes (currently we use 28). The drier grasslands could have a different colour to the wet forests.

**Comment by DonBatman** [comment]
I would like to see different grasses in different biomes. This would make a number of things including a couple of my mods better. You can get biome info from grass vs deserrt sand and a few other things but you can't get what you truly need. At least this will give a little more.

**Comment by MarkuBu** [comment]
I don't know how, but a bit more variation would be nice. I like the woodsoil from plantlife mod and the different colored trees from valley_c mod. But they cost performance because they are in Lua

And the 28 biomes are pretty useless because some of them look equal, so we need more plants and color variations to see differences between the biomes

**Comment by paramat** [comment]
The 2 grasslands look the same if you can't see the sandstone. Sandstone grassland was added to control the behaviour of the biome voronoi diagram, but i'm not too happy with having to do that so might change it in my biomes rework coming for next release.

**Comment by tobyplowy** [comment]
I would love some more coloring in the leaves and grass (no offense but the landscape looks a bit boring this would fix it) so +1 from me

**Comment by everamzah** [comment]
Texturing issues are controversial at best.  Better are pulls.

**Comment by tobyplowy** [comment]
@MarkuBu @paramat @DonBatman

**Comment by Fixer-007** [comment]
I do certainly miss jungle grass block IMO. Yesterday I've noted that there could be more variants of the same trees for greater variability.

**Comment by paramat** [comment]
What's the jungle grass block? if it's MC you can't miss it in MT, we never had it. We have a dedicated rainforest surface node now anyway.

**Comment by Fixer-007** [comment]
My comment is irrelevant since what I wanted was introduced in jungle.

**Comment by paramat** [comment]
Sorry for some reason i thought your previous comment was recent.

**Comment by paramat** [comment]
![newbiomes9](https://user-images.githubusercontent.com/3686677/28243731-846a9f2e-69cd-11e7-80cd-4d68991a800b.png)

We now have 'dirt with rainforest litter' for rainforest.
I have been considering a grey-brown dead needles surface for temperate coniferous forest, need to make a texture.
That only leaves grassland and deciduous forest with identical surface nodes, maybe we could have 'dirt with forest litter' with some dropped leaves and twigs?
Related #1570

**Comment by paramat** [comment]
Coniferous litter surface node added for temperate coniferous forest.
Hardware colouring i strongly oppose for reasons explained elsewhere.
Surface node variation is done per-biome already.
Leaf variation would require additional leaf nodes, not sure it's worth it. There is variation already between tree types.
Sorry i'm going to have to say absolutely not on this one.
