### ISSUE TITLE
Hide Nyan Cat and Nyan Cat Rainbow from creative inventory

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#1218]
This is a very simple change request: Hide the blocks Nyan Cat and Nyan Cat Rainbow even from the creative inventory, so the only ways to obtain them is by huge luck or cheating (`/giveme`).

The idea is to make those blocks more like easter eggs and possibliy a huge surprise when they are first encountered naturally. :-)
What do you think of the “easter egg” idea? Please discuss. The change itself is trivial, the question is whether we really want it.

Currently, it is quite easy to enable creative mode and then get “spoilered” all over the place, so when later actually finding a “real” spawned nyan cat, the surprise is not as big anymore.

**Comment by paramat** [comment]
Need input from builders, these might be popular building materials, creative after all makes everything available.

**Comment by Fixer-007** [comment]
I disagree, I seen lots of builds with nyan cats, huge -1

**Comment by paramat** [comment]
Yeah even mese block in creative :-1:

**Comment by everamzah** [comment]
I'd like to see creative inventory use not_in_creative_menu > 1, such that some may be hidden, but others not.  Maybe then a priv could be used for a fuller creative inventory.
