### ISSUE TITLE
v7 trees grow into the ground

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest_game#1223]
I noticed, that trees from v7 biome system (v5, v7, valleys) grows into the ground. If you dig those trees there is always an ugly hole. This does not happen in v6 mapgen.

But only trees placed by mapgen grow into the ground. Manually placed saplings grow on top

![bildschirmfoto vom 2016-07-28 10-56-32](https://cloud.githubusercontent.com/assets/16163058/17206858/0d6890d8-54b2-11e6-978d-a4028673250c.png)

**Comment by Fixer-007** [comment]
It is made on purpose to avoid tree in tree spawn, it is also more realistic, if you don't like the hole, you can put sapling in it to regrow which is even better.

**Comment by MarkuBu** [comment]
Ok, I understand. Closed
