### ISSUE TITLE
Blowing up containers can halt server

### ISSUE THREAD

**Issue by everamzah** [minetest/minetest_game#1224]
I can't see why anyone would put an itemstack with a count of 65535 inside these containers, but, for what it's worth, blowing them up results in a halting of Minetest as these items are being added to the world.  Most of them will be deleted because of a max limit within each block.

Edit:  default/chest, default/bookshelf, and default/vessel shelf

**Comment by tenplus1** [comment]
This should help: https://github.com/minetest/minetest_game/pull/1232

**Comment by paramat** [comment]
#1232 merged.
