### ISSUE TITLE
Getting stuck in snowy pine forests

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#1233]
This is a minor but annoying and common issue I have with Minetest Game:
If you just walk around the surface of a snowy pine forest, you can easily get stuck by not being able to walk under the trees.
Why? Because when you walk on the “Snow” (`default:snow`) nodes, they make you slightly higher. This is enough for you to collide with the pine needles, which are only 2 node lengths above the ground.
You either have to walk around or mine something, but both things are rather annoying IMO.

My suggestion is to increase the minimum height for pine needles of pine trees to 3 node lenghts above ground to avoid this pretty annoying getting-stuck thing, at least for new snowy pine forests.

**Comment by Fixer-007** [comment]
Try holding shift in those places.

**Comment by DonBatman** [comment]
I would like the snow to be not walkable. It would help with this and with jumping.

**Comment by paramat** [comment]
Will consider, it is a little inconvenient.

**Comment by paramat** [comment]
It happens because i made snow nodeboxes thicker (1/4 node), one solution (which i'm not sure about) is to make them just a little thinner (3/16 node).

**Comment by paramat** [comment]
In testing 3/8 node is still too high, i'm seriously considering returning to 1/8 node. Having a 2 node high space that looks high enough for a player but isn't does actually annoy me and gives a poor impression, and will cause problems elsewhere such as snow outside a door.

Wuzzy can you make a PR? I'll probably +1 it.
```{-0.5, -0.5, -0.5, 0.5, -0.375, 0.5},```

**Comment by Wuzzy2** [comment]
paramat, haven't you considerered or tested raising the minimum pine needle height of pine trees by 1?

I am not sure about lowering snow. I should test this sooner or later.

**Comment by paramat** [comment]
Yes, i don't want to raise pines, i'm actually considering allowing some to drop lower to within 1 node of the ground, as pines do under weight of snow. I like to have a wide variation of heights and don't want a nodebox problem to dictate the freedom on this.

I admit the thinner snow is not as pretty though.

**Comment by paramat** [comment]
Thinking on this i don't want to make snow thinner, thinner nodeboxes cause rendering bugs (nodebox flicker) at shorter distances.
Perhaps we should consider making it non-walkable? This would look cute having player's feet sunk into the snow.

**Comment by Wuzzy2** [comment]
> Perhaps we should consider making it non-walkable?

Interesting. This would also have the questionable benefit of working around one of the most frustrating bugs on Minetest, https://github.com/minetest/minetest/issues/329 
;-)

**Comment by ExeterDad** [comment]
@paramat 
> This would look cute having player's feet sunk into the snow
Very true. In fact a observation even my kids pointed out long before this "headroom" issue.
Adding to that, it's rare to find snow that has no tracks when walked on.

**Comment by paramat** [comment]
Unless anyone can think of a good reason not to i will support non-walkable snow.

**Comment by t4im** [comment]
Should be tested with falling nodes then.
There is some specifics with both leveled and unwalkable nodes.
But it could work or made to work.

**Comment by paramat** [comment]
Falling nodes seem to work well, they replace the snow as before but without the falling node stopping momentarily a node above, the snow disappearing and the falling node then continuing, it all happens faster and smoother.

**Comment by paramat** [comment]
Any other dev agree to non-walkable snow?

**Comment by paramat** [comment]
@Wuzzy2 would you like to open a PR for non-walkable snow?

**Comment by Wuzzy2** [comment]
Not really. Why?

(I agree with the change, however.)

**Comment by paramat** [comment]
Lol.

**Comment by Wuzzy2** [comment]
Well, its not actually unwillingness to contribute.
I am just confused that you actually bother me to do such trivial changes instead of just doing it yourselves as you already spent time in figuring out a solution and already know *exactly* what to do. This process seems arbitrarily convulated since this is just a senseless back-and-forth and even causes overhead since now this stuff has to go through the PR acceptance process, etc.
I have the feeling this request of yours was actually just of symbolic nature. Are you doing this to “test” me?

Whatever. If this issue is still open in a week or so, I do it anyways. I don't want to end this in drama.

**Comment by paramat** [comment]
Actually it helps us and saves us time if someone else makes the PR, if a dev makes the PR it still has to be reviewed and merged so no time is saved that way.
The reason i or we ask people to submit PRs is because it helps save dev time, and because the person requesting a feature is very likely to be happy to make the PR themselves if they are able to code it. This is normal procedure and nothing to do with 'testing' people, we rely on contributors to do a lot of the work, devs are already overloaded with work.

**Comment by DonBatman** [comment]
#1240

**Comment by paramat** [comment]
#1240 merged.

**Comment by paramat** [comment]
I almost raised pines, but noticed that pines with 2 nodes space beneath are only 25% of them (the trunk height is 2, 3 or 4 nodes) i like some pines to be low-hanging and impassable, and the problem only occurs if there is a snow nodebox next to a pine tree, so i decided against. It is a little annoying but my intention is that some pines cannot be walked under. Raising pines would make the forest feel less dense.

**Comment by paramat** [comment]
Pines now have more height variation so are on average higher, also, the new MTG 0.5.0 player model is shorter so no longer gets stuck when walking on a 0.25 node snow nodebox in a 2 node high space.
