### ISSUE TITLE
Incorrect/inconsistent/confusing item categorization in creative inventory

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#1237]
In the creative inventory, some items appear under strange categories. 
- Buckets are not in tools
- Doors are not in Nodes, but beds are in Nodes

I suggest these changes:
- Move all buckets to Tools
- Move all doors to Nodes

The general rule for “Nodes” could be “Everything which can be placed and appears in the form of one or more node”. So this includes all classic 1×1×1 nodes but also stuff which is made of multiple nodes, like beds and doors.

Possible implementation:
My guess is that the creative inventory categorization happens depending on whether the item was registered with `minetest.register_craftitem` etc. If possible, try to change this to a more appropriate value. It would also make life a lot easier for modders trying to analyze the items (like with my Documentation System).
If this is not possible for some reason you could maybe use some groups to “overwrite” the item category (at least for the creative inventory).

**Comment by rubenwardy** [comment]
This is on my to-do list

**Comment by tobyplowy** [comment]
@rubenwardy How High on your to do list is it?

**Comment by rubenwardy** [comment]
After #1179

**Comment by sofar** [comment]
Buckets can be made tools (without wear) without much problem I think, and that would be nice.

Doors are a bit harder to make into nodes, since you'd run into placement prediction problems, node naming issues etc.. One solution would be to make each door part a node, but make sure to never place it in the world and replace it immediately in `on_place` with the actual door nodes.

**Comment by Wuzzy2** [comment]
The problem with sofar's idea is, there will always be items which cannot be reasonably implemented as tool/craftitem/node and the “fake” node/tool/craftitem practice is sometimes actually needed since there simply isn't a viable alternative. And I think for doors this will be very difficult without breaking compability (again).

Better give mods a generic way to learn the “real” (intended) item type. For example, Minetest could pretend that the door items (internally implemented as craftitems) are nodes. This solution would not only clean up creative inventory, but help other mods as well. One way I imagine is by introducing a special group which is only used for the rare case that an item “pretends” to be of another type (e.g. door craftitems pretending to be nodes).
This special group would be a global Minetest thing and is not limited to Minetest Game, of course. It could be seen as a purely “declarative” group with no engine change required (but documented in `lua_api.txt`).

**Comment by sofar** [comment]
groups could likely solve this - assume default groups for items, tools and nodes, and allow nodes to override them using group attributes.

e.g. `tool = 1` in bucket `nodedef`.

Then filling the creative detached inventory becomes trivial - just select nodes based on group.

**Comment by An0n3m0us** [comment]
I think we need another category for all of the slabs/stairs/innerblocks/outerblocks since they take up five pages of the Nodes category.

**Comment by An0n3m0us** [comment]
> Doors are a bit harder to make into nodes, since you'd run into placement prediction problems, node naming issues etc.. One solution would be to make each door part a node, but make sure to never place it in the world and replace it immediately in on_place with the actual door nodes.

Why do they need to be made into nodes?

**Comment by An0n3m0us** [comment]
I've come up with a solution based on Sofar's comment; but this issue is assigned to Rubenwardy. Can I still create a PR?

**Comment by paramat** [comment]
You are free to make PRs whoever is assigned, but it may be wise to discuss this with @rubenwardy first.

**Comment by paramat** [comment]
@rubenwardy what is your preferred implementation of this? I think we should perhaps follow your preference if we do this.
Sofar's suggestion of adding groups to everything is a lot of bloat for a minor issue, not sure it is worth it.

**Comment by An0n3m0us** [comment]
I didn't add groups to everything; just 'group overrides', like for doors I added `node = 1` to set the category to node instead of it being in items. For buckets, it already has the `tool = 1` group so there was no change there.

**Comment by paramat** [comment]
Ok i see, sorry.
