### ISSUE TITLE
Optional 2x2 crafting field

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest_game#1242]
Minetest should have the option to enable a 2x2 crafting field and an optional workbench

It is difficult for mods to add this and if a new version makes changes to the ui the mod doesn't work like blockmans inventory mod

**Comment by C1ffisme** [comment]
Making a feature like this optional is not a really good idea. A workbench is meant to add some (tiny) level of progression to the game, and giving a player the ability to select whether or not they want to play with a piece of game balance means that developers have to develop a game that is balanced for two difficulties. And it's hard enough developing good enough balance for one.

**Comment by MarkuBu** [comment]
Why has a developer has to develop for two?  A workbench doesn't really add difficulty?  The player needs four wooden planks and has to carry around a workbench. 

But you can make games you can't make with only one option

Just making it a tini tiny bit more difficult, if any, for game developer is no reason to make it impossible or at least much more difficult to develop games they need a 2x2 crafting grid.

**Comment by paramat** [comment]
:-1: 2x2 is not very useful, even 3x3 starts to run out of possible combinations.

**Comment by MarkuBu** [comment]
It is just an option, not default. If you like to add a 4x4 you can add also a 2x2

**Comment by rubenwardy** [comment]
:+1: It should be possible for mods to change the craft grid size without having to use set_inventory_formspec, as that will break support  for mods such as sfinv and UI. It shouldn't be a user setting though.

Smaller starting grid + workbenches add a little progression. Although I wouldn't want to see it in the default game. From a game dev point of view, and not necessarily for MTG, I'd like to have work benches that are good for certain purposes like smithing, wielding and circuit board making

**Comment by tobyplowy** [comment]
@rubenwardy I know this is terribly off-topic but I just have to say it! i would love to see a Mod about, circuit board making

**Comment by C1ffisme** [comment]
@rubenwardy I'm okay with this being an API feature, but as a feature in MTG, no.

@MarkuBu 

> Why has a developer has to develop for two? A workbench doesn't really add difficulty?

Well, for a start, most recipes have to be 2x2 so that people who don't have the wood to build a workbench can make those things.

**Comment by MarkuBu** [comment]
@C1ffisme as long as it is possible to build a workbench (i.e. getting wooden planks somehow) you are fine. If you can't get wood to make planks you also can't make sticks, so you can't make any tools, doesn't matter if you have 2x2 or 3x3 crafting grid.

If I design a game I will design it for 2x2 or 3x3 crafting grid, not for both. I don't see any problem for game developers. 

But I want to make a game where I need a 2x2 crafting grid because the player shouldn't be able to craft everything everywhere. Workbenches are placed around the map and he may have lost the game if he stuck somewhere without a tool to dig him out

I don't care about the implementation, but I think it is the only way that it is implemented in Minetest somewhere and not leave this to a mod. So maybe Minetest Game is the wrong place for this issue. I can close this and open a new one in Minetest, if that makes more sense

**Comment by rubenwardy** [comment]
> @rubenwardy I'm okay with this being an API feature, but as a feature in MTG, no.

I never said that 2x2 inventory craft grid should be a MTG feature

**Comment by C1ffisme** [comment]
@MarkuBu I may have misunderstood you the first time, thinking you wanted this as a config setting. I would be fine if this was an API thing.

@rubenwardy Oops. The other half of that sentence was for @MarkuBu .

**Comment by paramat** [comment]
Yes i think this is an engine issue.

**Comment by Ferk** [comment]
Can't sfinv be used to overwrite the crafting tab from the mod?

**Comment by rubenwardy** [comment]
> Can't sfinv be used to overwrite the crafting tab from the mod?

Yes, you can override tabs - but if more than one mod tries to override the tab, you may end up with overlapping elements

**Comment by Ferk** [comment]
@rubenwardy shouldn't each tab be specific to one usage?
If two mods are sidestepping in the same tab, either one of them is misbehaving by going over its scope or they are really incompatible mods that probably shouldn't go together.

**Comment by rubenwardy** [comment]
True, and armour tab would be a better way to do it

**Comment by Ferk** [comment]
It would also be more friendly towards phone screens, giving it more space instead of cramming everything next to the crafting grid. It'll also allow for the armor/equipment tab to have more space to add information or whatever.

Imho, this could be closed once #1179 gets merged.

**Comment by MarkuBu** [comment]
Sounds OK for me

**Comment by Doloment** [comment]
To be honest, I think it is better to do in the 2x2 inventory, and "blind" benches with several levels. It is desirable then to add an anvil, and completely change the layout of crafting weapons and smelting system.
PS I'm from Russia, and was to blame Google translator -_-
Для тех кто русский:
Если честно, я считаю, что лучше сделать в инвентаре 2x2, и "слепить" верстаки с несколькими уровнями. Желательно тогда добавить наковальню, и полностью изменить схему крафта оружия и систему выплавки. 
П.С. Я из России, и во всем виноват переводчик Гугл -_-

**Comment by rubenwardy** [comment]
Sfinv allows mods to override the crafting tab without breaking support for creative

**Comment by paramat** [comment]
I feel 2x2 is not remotely needed enough to be an option in MTG code, it should be done by an optional mod, and looks like it can.
:-1: this should be closed.
