### ISSUE TITLE
Water & Walking 

### ISSUE THREAD

**Issue by MichaelWilcox** [minetest/minetest_game#1250]
It would be be better if moving in water without holding space moves the character up , but not so much. For example holding up + w/a/s/d

**Comment by C1ffisme** [comment]
That wouldn't be very helpful if you were building, say, an underwater base... (Or simply mining underwater.)

**Comment by MichaelWilcox** [comment]
Yeah, but you would only rise like, 1/4 block per block (while moving in any direction except up/down)
if you are stationary you'll still fall normally  . Mining straight down would be the same it could be beneficial to normal mining once you get the hang of it. Building a base with this could also be useful for placing blocks faster or to just remove the water

**Comment by red-001** [comment]
You should open this in minetest/minetest instead as this is related to the engine.

**Comment by paramat** [comment]
> if you are stationary you'll still fall normally

:-1: This means splitting vertical motion in water into 2 components, i don't feel the complexity is justified, there's no need for this. Please open an engine issue if you want to.
