### ISSUE TITLE
inventory in inconsistent in creative mode (armor options missing)

### ISSUE THREAD

**Issue by ensonic** [minetest/minetest_game#1251]
See https://github.com/stujones11/minetest-3d_armor/issues/69
when I am in creative mode the armor options are not shown.

```
creative damage inventory
no       no     armor shown
no       yes    armor shown
yes      no     no armor
yes      no     no armor
```

Also the inventory design is different in creative mode and non-creative mode.
creative mode: non transparent with tansparent tabs
non creative mode: transparent

**Comment by paramat** [comment]
Probably engine issues as the code is in 'builtin'.

**Comment by ensonic** [comment]
What does engine issue mean? Should I move this issue to minetest instead?

**Comment by DonBatman** [comment]
Yes. The issue should be in minetest instead of minetest_game.

**Comment by rubenwardy** [comment]
> Probably engine issues as the code is in 'builtin'.

Nope, the code is in the creative mod

This is a mod issue though, mostly

**Comment by paramat** [comment]
Oops my apologies.

**Comment by rubenwardy** [comment]
I think this is a mod bug

**Comment by paramat** [comment]
I agree. Open an issue in the mod first, then try to find out if there is a problem in MTGame.

**Comment by ensonic** [comment]
I did not install a separate creative mod or patch it in any way (as far as I know). The mod is part of this git repo: minetest_game/tree/master/mods/creative. So where would I open an issue against the mod if not here?

**Comment by rubenwardy** [comment]
No, it's a bug with stujones11/minetest-3d_armor#69

**Comment by paramat** [comment]
See https://github.com/stujones11/minetest-3d_armor/issues/69#issuecomment-239445120

**Comment by ensonic** [comment]
Would it make sense to enhance the creative_mod to allow additional formspecs? Otherwise people need to replace the inventory with e.g. cornernote/minetest-inventory_plus (which imho is a quite confusing one) or  minetest-technic/unified_inventory.

**Comment by rubenwardy** [comment]
See sfinv. It already does allow additional formspecs. Also see creative.formspec_add
