### ISSUE TITLE
If you break ore blocks you get stone And ore

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest_game#1254]
Basically if you break any ore (coal gold etc) block you get stone And ore ( I thought this would be a cool feature to set minetest apart from Minecraft) it's also never made sense to me in real life if you break ore you would get more stone than actual ore so with that logic you would get literally 1 Stone and one pixel of ore ( I don't know maybe I'm thinking too much about this XD)

**Comment by DonBatman** [comment]
It is ore ine stone.  If you break it you get the ore that was in stone plus the broken stone which is cobble.

**Comment by paramat** [comment]
(Another idea is to make the ore texture completely ore, so no stone shows, this would allow placing any ore in any biome stone type without it looking weird)

**Comment by Wuzzy2** [comment]
I am actually fine with “only” getting 1 ore as normal stone. But in reality the change is really, really minimal since stone is extremely abundant in Minetest Game.

**Comment by MarkuBu** [comment]
+1 for the idea of @paramat. This makes it easier to place ore in different stone biomes and you don't need  to define a new node for each stone type

**Comment by paramat** [comment]
It would obviously be cobblestone dropped..

**Comment by tobyplowy** [comment]
@MarkuBu isn't the ore an overlay? So you could put it on every block even dirt riht?

**Comment by tobyplowy** [comment]
@paramat > Another idea is to make the ore texture completely ore, 
I don't know about that I actually like if the stone is there but it could look good I just have to see it in game ( I'm neutral)

**Comment by paramat** [comment]
Yes ores are overlays, but that still requires new nodes to be defined. My suggestion up there is unlikely to be popular.

**Comment by tobyplowy** [comment]
@paramat well your idea sounds good but I just have to see it in game ( how does it look in a cave?)

**Comment by MarkuBu** [comment]
We had to create new textures for each ore. It would look better if we had the overlay over each stone texture. But as mentioned we had to define a new node for each stone/ore combination, which will be a lot if you have e.g. 10 stone types and 6 or more ores

**Comment by C1ffisme** [comment]
I don't need more stone than I already get from trying to get to diamond spawning levels, let alone finding them.

**Comment by Fixer-007** [comment]
Another way is minecraft way, you get stone with ore you can smelt or place again.

**Comment by paramat** [comment]
Each ore is mostly stone so ore plus cobblestone makes sense, if we do this.

**Comment by sfan5** [comment]
I see it this way:

When there's ore in stone it takes up the most of that nodes volume. When breaking it you just mine away the (small) pieces of stone at the edges. The resulting pieces of stone are so few and so small that they are barely useful (-> it doesn't drop anything else).

**Comment by tenplus1** [comment]
Gravel ?

**Comment by Fixer-007** [comment]
I'm the only one who misses possibility to have stone with ore in survival? As decorative blocks.

**Comment by paramat** [comment]
You mean the dropped node is 'stone with ...'? Consistent would be cobble plus ore.

**Comment by tobyplowy** [comment]
@paramat I think full ore blocks would look good

**Comment by tobyplowy** [comment]
@Fixer-007 yeah maybe they could be dropped by tnt, but I'm more a fan of the idea of @paramat (full ore blocks)

**Comment by Fixer-007** [comment]
paramat, this will break a lot of texture packs I guess

**Comment by sofar** [comment]
I'm OK with having crafting recipes to combine stone with ores to re-create the original stone-with-ore blocks, for decoration use.

As far as drops are concerned, the current drops of ore from stone-wit-ore is fine, and I would not recommend changing it.

**Comment by paramat** [comment]
Anyway, on this issue suggestion i'm neutral.

**Comment by octacian** [comment]
When it comes to drops, I like it as it is. As @sofar said, a recipe to combine the ore with stone to get the "Stone with Iron" would be nice though.

**Comment by paramat** [comment]
:-1: I'm fairly neutral but would prefer no change.
Closing due to 3 disapprovals.
