### ISSUE TITLE
Fast sound glitch

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest_game#1257]
If you have a corner in your house ( or just a corner) and put a ladder on the wall and walk into the corner ( do not climb the ladder) the sound of the block underneath you will be played insanely fast

**Comment by paramat** [comment]
This happens in several situations, probably an engine issue.

**Comment by tobyplowy** [comment]
This is quite an interesting bug though XD

**Comment by paramat** [comment]
I'm sure i saw an engine issue for this. This is an engine issue so closing.

**Comment by Wayward1** [comment]
Yep, https://github.com/minetest/minetest/issues/1460
