### ISSUE TITLE
New nodes for tundra

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1260]
An issue for discussion, texture submissions.

Currently tundra uses 'dirt with snow' which is essentially dirt with green grass and snow and is very unsuitable.
I suggest two new nodes: permafrost, and a surface node with perhaps red-brown mosses, this is often called the tundra 'active layer' but could be called 'permafrost with moss'.

Currently i'm searching through online images to get a feel for textures. Permafrost dirt seems to be dark and greyish/blackish, perhaps somewhat gravelly too, the absence of rich colour will look suitable for such a barren biome.
Perhaps for the surface node the permafrost texture can be used with a mossy overlay texture.

Another issue is will there be thin snow on top? This would hide the moss though.

Depth of the active layer: since we place tundra at below 0 degrees celcius in the biome system and because there isn't any seasonal temperature variation i would prefer a thin active layer less than one half of a node, so that we can use the permafrost texture plus a moss overlay for the surface node.

**Comment by paramat** [comment]
See #1261

**Comment by DonBatman** [comment]
I would suggest snowy with bare spots the show the permafrost node. I do like the idea of new nodes. This will make the biome stand out more. 
Also small shrubs and flowers grow in tundra biomes. Would be nice to include that but that might be off topic.

**Comment by paramat** [comment]
I realised we can add patchy snow using decorations, good idea.

**Comment by paramat** [comment]
Closed #1261 to reconsider, see discussion there.

**Comment by paramat** [comment]
I've had a change of atitude, i'm not sure about adding permafrost and moss nodes for tundra, we could perhaps use existing nodes and just have stone and patchy snow.
This is best discussed in the biome PR #1022
