### ISSUE TITLE
missing mushroom aliases

### ISSUE THREAD

**Issue by VanessaE** [minetest/minetest_game#1264]
One of my worlds has a bunch of old mushroom:red_natural and mushroom:brown_natural that are no longer defined.  Looks like aliases to those got missed when porting the mushrooms to minetest_game.

**Comment by Megaf** [comment]
```<ERROR> 2016-08-21 17:01:14: [Server] Item "mushroom:brown_natural" not defined theres also this missing alias```
for example

**Comment by paramat** [comment]
@VanessaE please can you check the node names are correct in the PR?

**Comment by VanessaE** [comment]
> @VanessaE please can you check the node names are correct in the PR?

I don't know what the node names are currently, but the old ones as used in #1265 are correct.

**Comment by paramat** [comment]
Thanks.

**Comment by paramat** [comment]
#1265 merged.
