### ISSUE TITLE
Remove cape from player model

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1266]
* These were not added for any real need, only because Minecraft has them and because they were made famous through the Minecon cape exclusives.

* Although also existing as mods, Minecraft capes are primarily known as an exclusive Minecraft / Minecon perk, and are therefore very much known as a 'Minecraft thing'. Adding them to Minetest without much actual need was a distasteful move, an analogy could be Minecraft adding Mese, which is very much known as a 'Minetest thing'.

* This is potentially not good for Mojang's and Microsoft's perception of Minetest.

* Their addition adds complexity to our model even if not used, this being done when there is little need for capes, few players use them. Much more useful would be the addition of full-body overlays if we decide to do that.

* This is seemingly something that can be done in a mod, and seems more a mod thing.

Capes commit https://github.com/minetest/minetest_game/commit/428a8127cb1ef91d11fe4795468f05e1c873079e

**Comment by paramat** [comment]
@sofar as far as i know you have the skills for this, what do you think?

**Comment by C1ffisme** [comment]
@paramat 
> This is potentially not good for Mojang's and Microsoft's perception of Minetest.

Um... Why do we care what our competitors think of us? Just look at modern advertising, every company wants to make the other company look terrible compared to themselves.

It is strange though that Minecraft seems to have taken some of it's features from us, like changing Block IDs from numbers to strings. (You wouldn't say `/give @p 1 64` anymore, it's `/give @p minecraft:stone 64` now.)

**Comment by paramat** [comment]
Mojang: Before now they have shown respect towards Minetest and it's best we keep it that way.
2nd reason: Microsoft.

**Comment by ExeterDad** [comment]
If I recall correctly @Jordach  added capes when he was trying to find a use for a little blank area in the default player texture. He did quite a bit of fixes to the model at the same time. I'm not a fan of capes, but I've seen many comments (even within the week) of those who like them.

**Comment by paramat** [comment]
I guess MC 1.8 skin format doesn't include capes?

**Comment by stujones11** [comment]
> I guess MC 1.8 skin format doesn't include capes?

The docs make no mention of capes, however, I have no idea how MC capes are done. While
I am not a big fan of capes either, I personally don't think it is worth removing now unless we do upgrade to skin format 1.8.

**Comment by rubenwardy** [comment]
it makes much more sense to support body overlays anywhere, rather than just capes. But I'm not particularly knowledgeable when it comes to models

**Comment by paramat** [comment]
Indeed we should decide on 1.8 format before doing this, to avoid 2 changes.

**Comment by octacian** [comment]
After consideration, I agree with you @paramat. The cape honestly needs to be "optimized" so that it is nicer when moving, as does the whole player model. But right now, I think support for more of a "3D" player model should be the focus for any work done on the player. By that I mean having extra "layers" in the skin, as with the head and the extra "hat" layer.

It is also **very** important to maintain the respect of competitors. And though MC is not necessarily a direct competitor, maintaining the respect of both Mojang and Microsoft is more than worth it.

**Comment by paramat** [comment]
For example a while back a lead dev of Minetest (Jeb maybe?) on reddit recommended Minetest as a good project to contribute too, we then had a massive spike in internet traffic and interest.

**Comment by C1ffisme** [comment]
@paramat Do you have any links? I'm actually interested in a Minecraft developer noticing Minetest.

**Comment by paramat** [comment]
Link was in dev channel 1-2 years ago, it was just a few words like 'Minetest is a worthwhile project to contribute to'.

**Comment by pinkysnowman** [comment]
i think they should remain in the model, i dont have a cape but i use the layer for my ponytail, so it moves as i walk :3  us girls do have hair needs!

**Comment by paramat** [comment]
That's cute.

**Comment by sofar** [comment]
fwiw I have nothing against the cape being in the model (especially if the animations are well done).

**Comment by FreeLikeGNU** [comment]
I found the cape useful for creating backpacks.  Its nice to have an example of hidden geometry.

**Comment by paramat** [comment]
Ok perhaps it should only be removed if / when we get full-body overlays.
There's an issue about supporting MC 1.8 skins but i can't find it.

**Comment by paramat** [comment]
Closing, if or when we get full body overlays that can replace capes, or we might even decide to keep capes optional. No point in removing capes before that work is done.
