### ISSUE TITLE
New snow causes false foot step sounds

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest_game#1271]
The new non walkable snow causes false footstep sounds. If you walk over the snow, but below the snow is dirt, ice or another node, the corresponding sound is played instead of the snow sound

**Comment by paramat** [comment]
This happened sometimes with the nodebox too. Not sure how to avoid this.

**Comment by paramat** [comment]
A possibility would be to use a nodebox just thin enough to allow playrs to walk in 2 node gaps, but the intent is for thick snow and for the player's feet to sink into the snow. Inevitably the player is walking on the node below so it is in a way correct behaviour. Luckily there is often a 'dirt with snow' node below which provides the correct sound.
Some complex way to detect snow nodebox above i think is not worth doing.

**Comment by DS-Minetest** [comment]
in real life when you walk through snow lying on asphalt you hear the step sounds muffled

**Comment by paramat** [comment]
I was just watching a Minetest video of a terrain with snow nodeboxes on bare stone, the snow was walkable and made the crunchy snow sounds. I was thinking how bad it would be if stone sounds were being player instead.
I'm thinking it's worth reverting the change to snow nodeboxes, if necessary we can always make pinetrees a little higher.

**Comment by Wuzzy2** [comment]
This also partially seems to be a missing engine feature. Would it be possible to play the footstep sound for non-solid nodes when walking through them?

Of course, making pine trees higher would fix this in Minetest Game and I am of course OK with that.

But I think there is another more fundamental issue here because other subgames will run into similar issues.

**Comment by paramat** [comment]
#1377 merged.
