### ISSUE TITLE
Play sounds ordered instead of random

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest_game#1272]
The randomization of sounds is sometimes weird. Especially footsteps sound strange if the same sound is played four or five times behind each other.

I propose that sounds can be played random like now or in the order given by the number. It might sound better if you have e.g. four footstep sounds and play them in their original order

**Comment by rubenwardy** [comment]
Minetest issue, that's where the randomisation code is

**Comment by tobyplowy** [comment]
This wuld make sounds really boring and repetitive :\

**Comment by rubenwardy** [comment]
This could be fixed by disallowing more than X repeats of the sound:

```cpp
Sound sound = getRandomSound();
while (sound == m_last_sound && m_sound_count + 1 > max_sound_plays) {
    sound = getRandomSound();
}
if (sound != m_last_sound) {
    m_last_sound = sound;
    m_sound_count = 0;
}
m_sound_count++;
```
