### ISSUE TITLE
new grass texture

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest_game#1275]
the base grass is to bright and too cartoony
i propose a less contrasty and less cartoony texture (see the pictures below for example)
![naamloos](https://cloud.githubusercontent.com/assets/16853304/18212744/15dd79d6-7145-11e6-9efb-ca939766ef23.png)
![default_grass_side](https://cloud.githubusercontent.com/assets/16853304/18212768/34d69782-7145-11e6-8a35-b106a5accb93.png)
![default_grass](https://cloud.githubusercontent.com/assets/16853304/18212770/34f03926-7145-11e6-8c1f-3980e43a0f81.png)

**Comment by sofar** [comment]
Make a pull request please. Having this discussion again isn't productive. It'll get 30 comments and nothing happens. If it's a pull request at least people can vote on a specific change, not just a request.

**Comment by tobyplowy** [comment]
@sofar someone is gonna have to do the pull request for me I don't know how to do it ( also I tryd to learn it but for some reason I can't seem to understand it) Maybe @tenplus1 would be interested to do the pull request for me? 

Bdw sorry I don't really like to ask for this :(

**Comment by sfan5** [comment]
We've changed the grass texture like 20 times in the last few months, can't we keep it the same for at least a single release?

**Comment by tobyplowy** [comment]
@sfan5 It's the same texture it's just a bit darker ( and the fact that it's changing so much means that it's not good and needs Improvement :D )

**Comment by MarkuBu** [comment]
It's still bright. Right side is your grass, left is my own (32px)

![screenshot_20160902_201736](https://cloud.githubusercontent.com/assets/16163058/18213842/783027be-714a-11e6-8f37-9434458c7819.jpg)

**Comment by sofar** [comment]
Please, can we close this issue? Without a pull request this is just a waste of time.

If you want to learn how to do a pull request, check out my guide on the forum:

https://forum.minetest.net/viewtopic.php?f=3&t=14262

**Comment by tobyplowy** [comment]
@MarkuBu i meant less contrasty and less cartoony

**Comment by tobyplowy** [comment]
@sofar i think just saying that is unproductive :/
