### ISSUE TITLE
New snow texture needed? (20 / 20 vision)

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1287]
![screenshot_20160913_022004](https://cloud.githubusercontent.com/assets/3686677/18458395/c3054560-7958-11e6-86f6-ec25ef7d7c1b.png)

Perhaps we can use an improved snow texture? This one has '20' in the bottom left corner.
Gambit's snow texture is good, it sparkles, maybe we can tune it as it is a little dark.

![default_snowg](https://cloud.githubusercontent.com/assets/3686677/18458487/68e2b0b2-7959-11e6-921a-db26fbaea6e7.png)

![default_snowballg](https://cloud.githubusercontent.com/assets/3686677/18458495/6da1a144-7959-11e6-88cd-e583c7a30a70.png)

His snowball is much better too.

**Comment by paramat** [comment]
![screenshot_20160913_023630](https://cloud.githubusercontent.com/assets/3686677/18458682/ef490efc-795a-11e6-94ce-9ed2f2977f41.png)

Brightness +63 in Gimp.

**Comment by paramat** [comment]
Looks so good i'll make a PR.

**Comment by NathanSalapat** [comment]
oooh, I  like the new snow texture.

**Comment by paramat** [comment]
PR #1288 
Gambit's talent amazes me, and the PixelBOX texture packs have a huge amount of textures for specialised items.

**Comment by paramat** [comment]
#1288 merged
