### ISSUE TITLE
Rotating doors with a screwdriver fails to rotate the 'Hidden Door Segment'.

### ISSUE THREAD

**Issue by jhcole** [minetest/minetest_game#1290]
Allowing the screwdriver to rotate doors as in 60cf3f85b6e661482ec2705cadbdc1b04e388d19 fails to rotate the 'Hidden Door Segment' that is in the hinge of the top half of the door. For players, this segment causes unexpected collision with a hidden object.

**Comment by paramat** [comment]
For simplicity i would prefer to not allow screwdriver to rotate doors, and revert that commit.

**Comment by t4im** [comment]
Ah, i didn't see, that the hidden node had any collisionbox defined. Or any sense of facedir for that matter.

I suppose it being walkable is to deal with falling nodes, but is the collisionbox really necessary? Removing selection and collision box (i.e. setting it to 0) could already fix this, and the door should already provide for a collisionbox, that stops falling nodes.

The code comment explaining it, doesn't seem to consider setting the selection_box  property.

**Comment by paramat** [comment]
See #1299

**Comment by paramat** [comment]
#1299 merged
