### ISSUE TITLE
wrong comment in player.lua

### ISSUE THREAD

**Issue by DS-Minetest** [minetest/minetest_game#1296]
in minetest_game/mods/default/player.lua (line 28) is written:
```
		 -- Extra animations (not currently used by the game).
		sit       = { x= 81, y=160, },
```
but minetest_game includes the boat mod which uses the sit animation.

**Comment by sofar** [comment]
Yeah. Should be a simple patch - you can make this yourself perhaps? Just add a comment that it's used by the `boat` mod.

**Comment by DS-Minetest** [comment]
now i wanted to write here that ive made a PR but its already here ^^

**Comment by paramat** [comment]
#1298 merged
