### ISSUE TITLE
Technic Screwdriver allows to rotate doors, which crashes the server if you want to open it

### ISSUE THREAD

**Issue by adrido** [minetest/minetest_game#1297]
I created an Issue for the technic mod thread already but @t4im [mentioned this is a minetest issue](https://github.com/minetest-technic/technic/issues/287)
[EDIT by paramat: Note this is the wrong backtrace, see below]

```
2016-06-30 17:03:40: ERROR[Main]: ServerError: Lua: Runtime error from mod '' in callback ScriptApiItem::item_OnPlace(): ...\doors\init.lua:175: attempt to index a nil value
2016-06-30 17:03:40: ERROR[Main]: stack traceback:
2016-06-30 17:03:40: ERROR[Main]:   ...\doors\init.lua:175: in function 'door_toggle'
2016-06-30 17:03:40: ERROR[Main]:   ...\doors\init.lua:361: in function <...\doors\init.lua:360>
```

Hope this will be fixed some day. Thanks.

**Comment by t4im** [comment]
I also asked to recheck, if it might already have been fixed. But that's the same stack trace from 2016-06-30, which points to empty lines.

Please recheck with a current version of MTG, if you can reproduce the crash.

**Comment by adrido** [comment]
If this wouldn't exist any more I wouldn't create a new issue. ;-)
But Im sorry, somehow the old stack backtrace got into clipboard.
Here is the new one with actual minetest_game, technic and minetest. (28.09.2016)
```
2016-09-28 16:46:14: ERROR[Main]: ServerError: Lua: Runtime error from mod '' in callback ScriptApiItem::item_OnPlace(): ...\..\games\minetest_game\mods\doors\init.lua:168: attempt to index a nil value
2016-09-28 16:46:14: ERROR[Main]: stack traceback:
2016-09-28 16:46:14: ERROR[Main]: 	...\..\games\minetest_game\mods\doors\init.lua:168: in function 'door_toggle'
2016-09-28 16:46:14: ERROR[Main]: 	...\..\games\minetest_game\mods\doors\init.lua:362: in function 'on_rightclick'
2016-09-28 16:46:14: ERROR[Main]: 	...\minetest-master\bin\Release\..\..\builtin\game\item.lua:335: in function <...\minetest-master\bin\Release\..\..\builtin\game\item.lua:328>
2
```
Steps to reproduce:
place door
right-click with Sonic Screwdriver
right-click the door to open

In my opinion doors should not rotated by screwdriver. This luxury is only difficult and causes mistakes that leads to crashes.

**Comment by paramat** [comment]
> In my opinion doors should not rotated by screwdriver. This luxury is only difficult and causes mistakes that leads to crashes.

Agreed, solves another problem too.

**Comment by t4im** [comment]
The crash is independent of the rotation. Technic screwdriver doesn't support `on_rotate` yet, so the deactivation would not work around the crash. A proper fix is needed in doors either way.

**Comment by sofar** [comment]
I never found door rotation to be worth it - doors are diggable by hand, and placing them is easy. Much better than both writing the code and making it bug-free ;)

**Comment by paramat** [comment]
We perhaps should prevernt the default screwdriver from rotating doors? Due to #1290

**Comment by sofar** [comment]
Just revert 60cf3f8 imho

**Comment by paramat** [comment]
Ok.

**Comment by paramat** [comment]
Making PR for this.

**Comment by paramat** [comment]
#1299 
Will this PR fix this issue?

**Comment by t4im** [comment]
> #1299
> Will this PR fix this issue?

No

**Comment by paramat** [comment]
But the issue is in technic so this could be closed?

**Comment by t4im** [comment]
No, the crash is in doors. It will still crash doors.
The PR doesn't change it for either screwdriver, because it only crashes for non-Y rotation, which wasn't allowed before anyway.

**Comment by paramat** [comment]
Ok, but the crash occurs after rotation by a technic screwdriver, so that mod should attempt a fix first before any issue is opened here. Stuff works ok with default screwdriver.

**Comment by paramat** [comment]
Ok. It seems to me, if the crash only occurs after rotation by technic screwdriver, it's a mod issue and a fix should be attempted in the mod before an issue is opened here.

**Comment by t4im** [comment]
I wouldn't be sure technic is the only mod triggering it; but sure, an `on_rotate` support should eventually be added there anyway.

Don't hold your breath for that though.

RBA died, Vanessae left the minetest-technic organisation and both @ShadowNinja  and @Ekdohibs seem busy, and can currently not find the time to even review and apply patches there, let alone write some, which is understandable, but makes applying a patch to the doors mod a lot easier at this time.

**Comment by sofar** [comment]
I'd like to have technic move to @minetest-mods, then we could take care of these issues as a community, without relying on absent developers. offtopic here, sorry.

**Comment by ShadowNinja** [comment]
Feel free to make a PR :-)
Actually, I wonder if the Technic screwdriver is relevant anymore now that there's one in minetest_game...

**Comment by rubenwardy** [comment]
This seems to be a mod issue

**Comment by paramat** [comment]
@sofar i'm confused about this, is there actually any remaining issue here?

**Comment by adrido** [comment]
It seems neither mintest_game nor technic got updated, so it still happens with latest Minetest, Minetest Game and technic

```
2017-01-14 09:14:00: ERROR[Main]: ServerError: Lua: Runtime error from mod '' in callback item_OnPlace(): .../mods/doors/init.lua:177: attempt to index a nil value
2017-01-14 09:14:00: ERROR[Main]: stack traceback:
2017-01-14 09:14:00: ERROR[Main]: 	.../mods/doors/init.lua:177: in function 'door_toggle'
2017-01-14 09:14:00: ERROR[Main]: 	.../mods/doors/init.lua:372: in function 'on_rightclick'
2017-01-14 09:14:00: ERROR[Main]: 	../builtin/game/item.lua:337: in function 
```

**Comment by paramat** [comment]
Ok, but it's a mod issue? Or is there some work needed n MTGame?

**Comment by sofar** [comment]
#1518

**Comment by adrido** [comment]
The bug is still not resolved. But got closed now on technic.
> It's up to minetest_game not to crash if a door gets weird.

Latest error message:
```
AsyncErr: ServerThread::run Lua: Runtime error from mod '' in callback ScriptApiItem::item_OnPlace(): ...\doors\init.lua:182: attempt to index a nil value
stack traceback:
	...\doors\init.lua:182: in function 'door_toggle'
	...\doors\init.lua:377: in function 'on_rightclick'
	...\builtin\game\item.lua:347: in function <...\builtin\game\item.lua:340>
```

**Comment by paramat** [comment]
@sofar can this be closed? I cannot judge it.

**Comment by HybridDog** [comment]
https://github.com/minetest/minetest_game/commit/667e130c52af62494e12721384279181b3738ff6

**Comment by Fixer-007** [comment]
@adrido Can you check it out please and close the issue?

**Comment by adrido** [comment]
Fixed. Finally. Thanks.
