### ISSUE TITLE
Fences do not work when placed

### ISSUE THREAD

**Issue by alienhunter3010** [minetest/minetest_game#1301]
I'm running a nightly build minetest server from my Raspberry Pi 3 (Raspbian).

Running my own world, fences are full blocks. So I try to run a new world w/ minetest_game only and they are full blocks yet!

![mts-bug](https://cloud.githubusercontent.com/assets/4917032/19014983/fee8d550-87fa-11e6-9561-e9cfb5ea8e48.png)

Thank you for your work,
Alex.

**Comment by everamzah** [comment]
Hi Alex.  Judging from the screenshot, the server is running Minetest 0.4.13.  Fences now require 0.4.14.

**Comment by paramat** [comment]
You need to use MTGame and MTEngine that match in version number. I guess you're using a recent MTGame with 0.4.13 MTEngine?

**Comment by sfan5** [comment]
@paramat As you can see from the screenshot his client is `0.4.13` while the server is on `0.4.14-dev`, which means that yes, the version mismatch _is_ the problem.
