### ISSUE TITLE
Change: Can be ignite TNT (or/and lit up gunpowder) with Flint & Steel and it will gets -1 durability damage. 

### ISSUE THREAD

**Issue by WSDguy2014** [minetest/minetest_game#1302]
I would like to change feature TNT (or/and gunpowder) activation with Flint & Steel, instead of torch (should be get -1 durability damage for Flint & Steel, if lit up TNT or gunpowder by left-clicking), rather than torch.

**Comment by paramat** [comment]
? Flint and steel always gets wear when used https://github.com/minetest/minetest_game/blob/master/mods/fire/init.lua#L90

**Comment by t4im** [comment]
I think he is asking for removal of ignition by torch.

**Comment by paramat** [comment]
The request is unclear and could mean many thiings.

**Comment by rubenwardy** [comment]
you can already ignite tnt with flint and steel. It is correct for torches to be able to ignite as well
