### ISSUE TITLE
TNT should ignore unbreakable nodes

### ISSUE THREAD

**Issue by tchncs** [minetest/minetest_game#1305]
Hi there, i just realized that TNT should check for unbreakable nodes since it currently just smash them away.

**Comment by paramat** [comment]
What do you mean by 'unbreakable'? 'level = (high number)' in node groups?

**Comment by stujones11** [comment]
Would it not make more sense for the 'unbreakable nodes' to simply ignore TNT using `on_blast`?

**Comment by tchncs** [comment]
@paramat i meant `groups = {unbreakable = 1}`

@stujones11 yeah this was my thinking but on the moment i looked into the code i didn't got how. 
Still learning...

**Comment by paramat** [comment]
I see, i forgot about that group.
Doing this by 'on blast' seems good as tnt already checks this.

**Comment by sofar** [comment]
The `unbreakable` group does not exist in minetest_game, anywhere. It is not a minetest_game thing.

**Comment by stujones11** [comment]
@sofar I didn't think so, otherwise there may have been a case for TNT respecting that. `on_blast` was added for this very purpose so I think this is really a non-issue.

**Comment by paramat** [comment]
Yeah use on_blast.
