### ISSUE TITLE
Adding 'boost cart' mod to MTGame

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1311]
An issue for discussing how to add 'boost cart' mod by Krock / SmallJoker.
https://forum.minetest.net/viewtopic.php?f=11&t=10172
I added this to the 0.4.15 milestone but it may not be ready in time.
Addresses part of #515 

Experiences with the mod and any issues with it.
What needs rewriting.
Which features (if any) to trim for simplicity and performance.
Whether default rails should be moved into the mod and dealing with backwards compatibility.

@SmallJoker

**Comment by paramat** [comment]
I guess it should be called 'carts' when added? Or is it better to distinguish it from PilzAdam's mod?

**Comment by stujones11** [comment]
While I would love to see decent railcarts in minetest, I do not think there is a stable enough implementation yet. boost_cart is a good mod but should not be included with mt game atm (imo)

**Comment by Fixer-007** [comment]
It is stable enough for merge (mostly problem free), I don't remember much crashes with it, servers are using it without problems, and it behaves much more better than Pilz Adam original one. I traveled on them for thousands of blocks on few servers.

**Comment by stujones11** [comment]
> servers are using it without problems

You could say that about many other mods like mob_redo for example, players will love it but expect an issue fest ;-)

**Comment by Megaf** [comment]
Not happening, carts and mobs are way too unstable in performance. The whole mod thing has to change and how we deal with active objects.

**Comment by SmallJoker** [comment]
I like the idea to finally give the rails an use. We already have boats and they're part of MTG for a long time.
The performance of the boost_cart is way better than the original version from PilzAdam, maybe the same or better as the boats. It is proven that servers have no problems with it. The question is, if the singleplayer mode works good aswell.
But - Is it a good idea to extend MTG? Why not add mobs too? We would end up with a huge game that offers all content the players ever will need. I think the players should learn to install mods on their own.

**Comment by tenplus1** [comment]
Boost_cart works really well on Xanadu with no issues, even added cart sounds and drops as item when cart unattended...

**Comment by paramat** [comment]
> if the singleplayer mode works good aswell

What are the issues in singleplayer?

> Is it a good idea to extend MTG? Why not add mobs too?

My opinion is that important and much desired features such as carts and very simple mobs should be moved into MTGame (and be optional in the case of mobs), because any mod within MTGame tends to be far better maintained and kept up to date than an independent mod.

Rails are in default so we really should have carts too. Everyone knows boats can be buggy with lua lag and carts will be too but that's no reason to avoid them, who would want to remove boats from MTGame?

**Comment by everamzah** [comment]
boost_cart overrides default:rail, however, and it can act differently depending on the presence of the mod.

I bring this up because if you put this mod on an pre-existing world which features placed rails, then there can be glitches.  boost_cart works reasonably well, but I would expect some issues, anyway.

**Comment by paramat** [comment]
@Megaf i need to say sorry for something, somewhere i asked you to not use the 'review' feature, i was wrong to do so, this is not a dev-only thing, anyone can review a PR.

**Comment by Megaf** [comment]
@paramat oh, I didn't even see that. But yeah, it is supposed to be used by anyone as far as I know.

**Comment by maikerumine** [comment]
I would like to chime in here.  I have been hosting very active servers for the past year and a half and have used boost_cart as the main cart mod and have had no problems whatsoever.  I feel it would be a neccessary mod to add to the default minetest game.  What is the point of having default:rail if you cannot even use them?  Moreover, I personally have ridden tens of thousands of blocks with boost cart on fully loaded servers 30+ players and have had no issues.  it is time we move forward instead of sitting in the dust, himming and hawing about things that really are not that important.

**Comment by stujones11** [comment]
I guess it can do no harm to give it go but I think it needs stripped back a little feature wise, the boost_cart mod could always become an add-on pack for those removed.

**Comment by rubenwardy** [comment]
It's okay for carts to opt depend on mesecons

**Comment by stujones11** [comment]
> It's okay for carts to opt depend on mesecons

Soft dependency is okay I suppose but in general mtg mods should not depend on outside mods. I guess mesecons is something of an exception so long as items have some other use without it.

**Comment by Ferk** [comment]
Is it actually necessary for it to depend on mesecons?

It seems the "boost_cart:detectorrail" is the only thing in "boost_cart" that uses mesecons, perhaps that could be left out to a mod. The logic that triggers the detectorrail to act could be generalized by calling an "on_cart_step" callback on the rail nodes that implement that callback, "boost_cart:is_rail" could give the node back as a second return value, which could be used for this. That would also save a second minetest.get_node.

This way mods could add any other special rail nodes with whatever other effects too.

**Comment by sofar** [comment]
please review and discuss #1318.

**Comment by paramat** [comment]
Yeah anything in there that's only usable with mesecons should be removed.

**Comment by amadin** [comment]
Cart must be accelerate by pressing button too, not only by punshing inside or outside cart.

**Comment by paramat** [comment]
Not needed, that's what punch is for anyway, to get the cart rolling onto power rails.

**Comment by Wuzzy2** [comment]
The idea as such is a real no-brainer. I mean, come on! We have rails but nothing to put on the rails? This just doesn't make sense.

I think `boost_cart` is a stable and mature mod, I am not aware of any serious issues. It has been used on @test@ for a while now and it works nicely! It even has sounds, something which `boats` is lacking.
If you know of any bug, please post it here to warn us.

I think the wielding image could look better (it's a bit flat) but that's it.

Note that `boost_cart` not only includes the carts, but also 3 new rail types.

**Comment by amadin** [comment]
> Not needed, that's what punch is for anyway, to get the cart rolling onto power rails.
Button can't be used as a push button? I mean player must press button again and again for moving in cart on steel rails.

**Comment by paramat** [comment]
Well, i'm fairly neutral about an external button, but i doubt sofar wants to include this feature, although it seems the API will allow it by registering your own custom rails.

**Comment by paramat** [comment]
#1318 is merged.
