### ISSUE TITLE
Proposing "Sandstone Column" node

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1321]
Some people, including me will really like "sandstone column" block with vertical marks like on this screenshot: https://urbanisticainitalia.files.wordpress.com/2011/10/img_1330.jpg

What do you think?

My very rough example based on Quartz mod pillar. I dislike them somewhat, needs total rework. Thats just rough visualisation:
![column3](https://cloud.githubusercontent.com/assets/16494741/19279562/8f13e98e-8fea-11e6-8923-338836c12863.png)
![column2](https://cloud.githubusercontent.com/assets/16494741/19279561/8ebd78d8-8fea-11e6-804d-dfa93884061c.png)
![column1](https://cloud.githubusercontent.com/assets/16494741/19279560/8ebc2276-8fea-11e6-811b-8c50d1508e5f.png)

**Comment by sofar** [comment]
Neutral, the default game could use a few more "decorative" blocks I think, and this could be good, but it's not very creative, per se. Also, texture bikeshed follows... :)

**Comment by paramat** [comment]
More a mod thing, too specialised for MTGame.

**Comment by C1ffisme** [comment]
@paramat If you were asked about a year ago if carts, beds, boats or even 3d torches belonged in the game, you would have said that they were "a mod thing". Maybe it's time to expand the small box of ideas of what belongs in MTG?

**Comment by paramat** [comment]
Nope, beds and boats were part of MTGame a year ago, and i liked the idea of adding carts. Torches i'm still unsure about, but now neutral. We are expanding what MTGame contains. This has nothing to do with these pillars.

**Comment by C1ffisme** [comment]
@paramat Fine, so what makes this a "mod thing"? Do we have an actual line between what belongs and doesn't belong in MTG?

I'm sure this block has more uses than the vessels, which are currently a waste of steel/glass for decoration.

**Comment by paramat** [comment]
Yes the line is created by what is included. You can see that MTGame nodes are mostly very fundamental, some are not (i agree about vessels) but those that are now in may be difficult to remove, also they were added before i had any say here.

**Comment by tobyplowy** [comment]
@paramat These pillar blocks have a Lot of Decoration uses at least if you have the possibility to turn them horizontal and vertical (The Same way tree blocks work) also What @C1ffisme Said is True you have to think more outside of the box, but You're an amazing Guy and We can't Do This Without You
Also @Fixer-007 the Texture is not terrible i quite like it :D

**Comment by tobyplowy** [comment]
@paramat i think the vessels should be removed to

**Comment by C1ffisme** [comment]
@tobyplowy Vessels can't be removed, because then maps with the blocks and items from the mod will be unknown nodes.

I'd like to keep the glass bottle in the game, if only because it means other mods don't need to register their own. The other ones are a little bit excessive. (The cup, and the bottle.)

**Comment by Wuzzy2** [comment]
Is there any definition of what constitutes a “mod thing”? Maybe you should just write it down one day. Otherwise, any decision of accepting/rejecting this just seems random. Does anyone of the main developers have any idea of what Minetest Game is supposed to be?

Oh, and if this idea is ultimately rejected, please say so. I would then like to use the sandstone column texture for my `mtg_plus` mod. :-) Please post in my thread if you're OK with this.

@Fixer-007

**Comment by sofar** [comment]
This is an `issue` and not a `pr`.

The problem with feature requests like this, that don't have any code, is that it's entirely open ended, and even if we'd accept or approve it, there is no code to go with it.

And it's code that talks. It's code that shows if something is well integrated, has some sort of in-game utility, entices survival mode players to use or gain something, etc..

Without code this is just a nice idea. It doesn't even matter if it's rejected now or not. Until there's code, it's just one of many random ideas that is unusable.

**Comment by Wuzzy2** [comment]
I disagree.

If the *idea* is rejected outright, then there's no point in keeping this issue open, and even less point in coding it.
I think a general hostility towards ideas (calling them “useless”) is not good. If something is well-thought out, it makes sense to keep it open. As a goal (of some sort).

Also, not all ideas are equal. There are good ideas, and terrible ideas.
I think ideas can still be useful as long you precisely define what you actually want. Being precise is something many people (sadly) forget. And on this basis, it is perfectly reasonable to decide whether we want a particular feature or not.

It is also useful to learn whether it is worth the time to actually code something. If the idea for that code would have never had a chance, then the contributer would just have wasted time coding.

And for this particular idea, the code for it would be rather trivial (1 node and 1 crafting recipe).

**Comment by Fixer-007** [comment]
I will close this, you can continue discussion anyway.

**Comment by paramat** [comment]
Suggesting a new node in this way seems ok to me.

**Comment by C1ffisme** [comment]
Hey, be optomistic, at least the suggestions aren't... [this](www.minecraftforum.net/forums/minecraft-discussion/suggestions/2755407-you-need-to-add-it-mojang) or... [that](http://www.minecraftforum.net/forums/minecraft-discussion/suggestions/2753773-airplanes) (These are two semi-recent Minecraft Forum Suggestions. You can see why these are frowned upon).

We could open up a seperate project for suggestion related feedback, though, similar to how [some Minecraft mod githubs](https://github.com/CoFH/Feedback) do it. (Githubs, is that even a term, let alone the correct one?) Or open a thread on the forum specifically for suggestions. (Feature Discussion would be for features that are already in the game, or half-baked ideas of features that aren't actually suggestions.)

**Comment by paramat** [comment]
:-1:

**Comment by paramat** [comment]
If you want it, you'll have to code it, devs seem not interested.

**Comment by C1ffisme** [comment]
@paramat I don't think node definitions are very hard to do... A sandstone column is basically a copy-paste of a log block with changed tool groups and textures.

**Comment by paramat** [comment]
So make a PR.

Someone will have to code this if they want it, MTG devs are not interested in doing so.
Note i will -1 a PR, we already have sandstone, sandstone brick and sandstone block. Although we intend to add more nodes to MTG, 3 sandstone building nodes is enough. The column is not very general, seems useful for greek temples only. You can use the new 'block' node for these uses.

Will close at 1 year.

**Comment by SmallJoker** [comment]
What if we add a fresh mod to MTG which extends the default mod with building nodes like this? The players want content and we don't want to overload "default" with too many new nodes.

**Comment by Fixer-007** [comment]
Since addition to MTG of various sandstone/desert-stone/silver-stone block kinds I no longer see a need for this kind of block in game. Closing.
