### ISSUE TITLE
Sapling grow function doesn't check for dirt

### ISSUE THREAD

**Issue by tchncs** [minetest/minetest_game#1323]
Hi folks, 
as expected today, sometimes saplings are growing to trees, also on stone.

![screenshot_20161011_222522](https://cloud.githubusercontent.com/assets/10698140/19287360/b1f7a0b4-9001-11e6-823c-b280b5ea83e4.png)

**Comment by sofar** [comment]
The code clearly reads:

```
 15         local is_soil = minetest.get_item_group(name_under, "soil")
 16         if is_soil == 0 then
 17                 return false
 18         end
```

That suggests that your stone has the `soil` group set?

**Comment by sofar** [comment]
I wonder if you're using a mod that modifies `default.can_grow` as well.

**Comment by paramat** [comment]
Some servers are doing that because they don't like the new light level requirements.

**Comment by tenplus1** [comment]
Some servers are also doing that because the do not like the sapling placement checks as well.

**Comment by sofar** [comment]
@tchncs needs to confirm where he found this (a custom server, or a plain mtg machine).

**Comment by tchncs** [comment]
> That suggests that your stone has the soil group set?
I... honestly don't know but i also don't see any reason why it should be like this.

> I wonder if you're using a mod that modifies default.can_grow as well.
Well i have moretrees on my server but does it touch it?
Didn't see this in the code... .
Sounds like i should reverse check with a testworld.. .

**Comment by paramat** [comment]
Are they moretrees saplings?

**Comment by tchncs** [comment]
No. Only tested with default saplings yet.

**Comment by sofar** [comment]
I've had a plain vanilla minetest_game with `default:aspen_sapling` on top of `default:stone` for a few hours, and nothing grew.

**Comment by tchncs** [comment]
@sofar i guess it took over a half day 'til the first plant was grown on the screenshot...

**Comment by sofar** [comment]
You can use minetest-mods/inspector to see when the timer runs out, at which time the sapling should attempt to grow.

**Comment by paramat** [comment]
Looking at your screenshot, there isn't enough light to grow those saplings, so i expect 'can_grow' has been overriden. Saplings require a meselamp (light level 14) directly beside them.

**Comment by paramat** [comment]
Closing since dirt is obviously checked for in the code.
