### ISSUE TITLE
sticks from regular wood and jungle wood are different items.

### ISSUE THREAD

**Issue by Megaf** [minetest/minetest_game#1329]
And you can't stack them together.
Not sure if it's a bug or not. But perhaps they should be the same item?
Or maybe an alias at least?
Give your opinion on this please.

Reported by a player on my server.

**Comment by Wayward1** [comment]
There isn't a jungle stick in default Minetest Game. I do see them in moreblocks though

**Comment by sfan5** [comment]
can't reproduce

**Comment by Megaf** [comment]
Perhaps moretrees related then?
