### ISSUE TITLE
River color such as the color of lakes and sea

### ISSUE THREAD

**Issue by amadin** [minetest/minetest_game#1330]
I think if Minetest is engine then color of all water must be the same. Then Valleys mapgen was a separate mod this was normal because mod creator can do whatever he wants. But now i think this is not good for game engine. I think textures for river and sea can be different but with the same color.

**Comment by sfan5** [comment]
The minetest <i>engine</i> ([this thing here](https://github.com/minetest/minetest)) doesn't enforce any water color. Having differing sea and river water colors is the decision of this subgame. (which just happens to be the official subgame)

If you were to create your own subgame you could have as many different water colors as you want or just one.
