### ISSUE TITLE
Flint and steel: grass, jungle grass, flowers not burning

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1338]
I've noticed that I can't burn grass, jungle grass and flowers, while dry shrub, cotton, wheat, papyrus are burning. Chests are not burning too btw but it is probably intended.

**Comment by paramat** [comment]
This was done by me but i've changed my mind, i don't mind these being flammable.= 1.

**Comment by paramat** [comment]
#1339 merged.
