### ISSUE TITLE
Leaves have unnecessary 'visual scale' definition

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1345]
`
        visual_scale = 1.0, --[[
        ^ Supported for drawtypes "plantlike", "signlike", "torchlike", "mesh".
        ^ For plantlike, the image will start at the bottom of the node; for the
        ^ other drawtypes, the image will be centered on the node.
        ^ Note that positioning for "torchlike" may still change. ]]
`

Leaves have `visual_scale = 1.3` anyone know why? it doesn't affect the appearence when wielded.
It's been this way since MTGame's first commit on 26 Mar 2012. I assume there's no reason then.

**Comment by Napiophelios** [comment]
I think all leaves use this to make trees look more filled in with the "overlap"
Jungle grass is the same way, it just looks denser when their is  alot of it.

**Comment by paramat** [comment]
Ok i'll make a PR.

**Comment by paramat** [comment]
#1353 merged.
