### ISSUE TITLE
Remove vessels mod

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1354]
Seems out of place amongst the basic stuff in MTGame. I suggest moving it to the minetest-mods organisation, and giving server admins a long period of warning before they have to install it independently.
If there's not enough time before 0.4.15 to warn people perhaps it could be done after release?

**Comment by rubenwardy** [comment]
https://github.com/minetest/minetest_game/pull/6

@celeron55

**Comment by sofar** [comment]
Neutral, but I'd rather do something with them instead. Soemthing like alchemy.

**Comment by everamzah** [comment]
No.

**Comment by C1ffisme** [comment]
Removing altogether? No. Removing steel bottle and glass cup? Go right ahead, they really have no use. I can see that those two might be useful in a thirst mod, but a server only ever needs one thirst mod, so they don't have to worry about having multiple liquid storage devices.

**Comment by Wuzzy2** [comment]
No, this is just wrong for so many reasons:

* The glass bottle is used quite a lot in mods for crafting, for example, potions
* The vessels are actually being used as decoration in worlds, for example, in the server `@test@`. I have seen all 3 kinds of vessels.
* The vessels shelf is of course also used in worlds and thus can't be removed

**Comment by C1ffisme** [comment]
@Wuzzy2 I really can't see any places where the steel bottle would look good. The fact that the vessels are about half a meter high when placed also doesn't help.

**Comment by stujones11** [comment]
I must admit I've never liked the look of these but I do not see any great benefit in removing them. You could consider making them 'shapeless' so they can only be used in crafting but that would still break existing mods and worlds.

**Comment by Fixer-007** [comment]
I'm using vessels as a decor

**Comment by rubenwardy** [comment]
Vessels is a very useful mod compatibility tool. Before vessels, a few mods defined their own vessels which made mod dependency annoying.

At the moment I'm leaning towards keeping it, but am close to neutral.
I'd like to see either:

* More logic to tie vessels into the vanilla world
* or if vessels are to be removed, then it is important to advertise the standalone copy very well. Mod devs tend to avoid dependencies, as they are more annoying for the user to install - so it may be worth waiting for the mod store to work again™

**Comment by paramat** [comment]
Fixer that's no argument.
I'll close this.

**Comment by tobyplowy** [comment]
@paramat yes it sortof is :/
