### ISSUE TITLE
Can't build door in front of door

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#1364]
As of 56d6eaed85fb959c2c5e6145038d408d795b262f, sneak-rightclicking on a door while wielding a door does not place the wielded door in front of the existing door, but instead opens/closes it.

The way I understand it, sneak-rightclicking is reserved for a *guaranteed* build (and not usage of the pointed thing) so I guess this is a bug.

**Comment by paramat** [comment]
See #1487
