### ISSUE TITLE
default_privs = fly in ~/.minetest/minetest.conf not applied

### ISSUE THREAD

**Issue by ensonic** [minetest/minetest_game#1369]
On the server side:
```
$ grep default_privs ~/.minetest/minetest.conf
default_privs = interact, shout, fly
```
There is no ~/.minetest/auth.txt file (neither on client or server side). Modifying default_privs on the client side has no effect either 8as expected). 

Still when a client joins teh game (local non public server) he has no fly privilege and one has to /gant <username> fly first. According to
https://github.com/minetest/minetest/blob/master/minetest.conf.example#L854-L857
this should work though.

**Comment by rubenwardy** [comment]
This should be in minetest/minetest
