### ISSUE TITLE
Remove snow footstep 1

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1378]
This is the one that sounds like a door slamming, seems out of place with a double attack.
https://github.com/minetest/minetest_game/blob/master/mods/default/sounds/default_snow_footstep.1.ogg
Snow footsteps are ok, for now at least, with just the other 2.
If acceptable i will make a PR.
I don't feel too strongly about this.

**Comment by Fixer-007** [comment]
This sound is fine to me.

**Comment by DS-Minetest** [comment]
maybe split the sound into two halves

**Comment by paramat** [comment]
I tried that it didn't work.

**Comment by paramat** [comment]
Better to find new sounds than have just 2.
