### ISSUE TITLE
Make nyancat and nyancat rainbow luminous

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1380]
Was watching a Minetest video and thought this looked really good, especially  underground. Rainbows are luminous by nature, nyancats may not seem suitable for luminosity but it looks good and consistent with the whole structure.
See this section of the video https://www.youtube.com/watch?v=vV9Y7nOAJIc&feature=youtu.be&t=940
If approved i will make the PR.

**Comment by Fixer-007** [comment]
@maikerumine has this feature on his servers, and it looks great to be sure.

**Comment by stujones11** [comment]
One minor concern, wouldn't this make them extremely easy to find using no-clip? Otherwise,  looks good.

**Comment by Fixer-007** [comment]
hackers have no problems find it anyway

**Comment by paramat** [comment]
I don't think they'll be visible when flying underground, only meselamp does that because it's 'glasslike' drawtype.

**Comment by stujones11** [comment]
It's probably not that big a deal but I know lava is sometimes visible even without no-clip in some cases.

**Comment by rubenwardy** [comment]
I agree with this

**Comment by paramat** [comment]
I'll make a PR.

**Comment by maikerumine** [comment]
Here is my fork if you can merge:  https://github.com/maikerumine/nyancat

**Comment by paramat** [comment]
#1382 merged.
