### ISSUE TITLE
First item disappears in creative inventory after first arrow click

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#1381]
How to reproduce:

* Open creative inventory
* Click on any of the 4 creative inventory tabs
* Click on “>” and remember the items of page 1 and 2
* Click on “<”
* Look on the items on page 1 and see if you see any differences
* Now click on “>” again and look again if you see any differences on page 2
* Click on “>” several times until you made a full circle. Start over at page 1

Expected: You see the same items on each page every time.
Actual: After you first went back to page 1, the first item has disappeared and all items after that are moved one slot to the right. This effect stays the same on the following pages.
If you made one “full circle” (i.e. go right on the last page to end up on page), the items seem to be displayed correctly.
This bug can be repeated if you click on another tab, then everything starts over.

Revision: 6e00ddee2ae21490efbe7723a946b68715ac7a07

**Comment by Wayward1** [comment]
I can confirm.

Before:
![screenshot_2016-11-09-21-53-18](https://cloud.githubusercontent.com/assets/8821916/20163021/2d158410-a6c7-11e6-817c-77961e47dfaf.png)

After going to the second page and back:
![screenshot_2016-11-09-21-53-27](https://cloud.githubusercontent.com/assets/8821916/20163038/506e200c-a6c7-11e6-991b-31e5134550d6.png)

**Comment by DS-Minetest** [comment]
i can confirm, too
but you can then see an item at the end of the page which didnt appear on the next page

**Comment by paramat** [comment]
#1384 merged.
