### ISSUE TITLE
Replace snow sounds

### ISSUE THREAD

**Issue by masrourmouad** [minetest/minetest_game#1388]
the snow sounds are bad, we should replace it.

**Comment by paramat** [comment]
Related #1378 
2 of them are okay for me at low volume, but yeah they could be softer.

**Comment by tobyplowy** [comment]
@paramat yeah they should definitely be softer

**Comment by paramat** [comment]
Since i have complained too i might look for new sounds.

**Comment by tobyplowy** [comment]
@paramat I think it Should Be Less Loud And More crispy also you're the best paramat :D

**Comment by DS-Minetest** [comment]
i think, [this one](http://www.freesound.org/people/luminadii/sounds/336763/) got potential

**Comment by tobyplowy** [comment]
@DS-Minetest I like those Sounds really crispy That's nice :)

**Comment by DS-Minetest** [comment]
well, if you go on freesounds.org and search for `snow` its the first sound, you can find
=> my comment my be unneeded (like this one)...

**Comment by paramat** [comment]
See #1499

**Comment by paramat** [comment]
I will submit new snow sounds extracted from #1499 for release.

**Comment by paramat** [comment]
Will work on these during feature freeze.

**Comment by masrourmouad** [comment]
no new sound added :(

**Comment by paramat** [comment]
I'm still intending to work on this. I didn't see it as a priority for last release.

**Comment by masrourmouad** [comment]
ok

**Comment by jastevenson303** [comment]
What would you like to replace it with?  All the sounds need (some amount of) work, this isn't the only one.

It's really one of the worst, though.  Crunch, crunch.

For what it's worth: snow_footstep.2 and .3 are 48kHz.  snow_footstep.1 is only 22kHz.  (Yes, this makes a difference, 25,950 of them.)

**Comment by paramat** [comment]
That's bad, i'll work on this ASAP.

**Comment by paramat** [comment]
PR #1920

**Comment by paramat** [comment]
#1920 merged.
