### ISSUE TITLE
Don't automatically pick up blocks When broken If in Creative

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest_game#1389]
Don't automatically pick up blocks When broken If in Creative 

Example you just removed a dirt block out of your inventory because you don't need it anymore you close your inventory and just two seconds later you break a grass block and you get dirt again it's really annoying! And it happens alot

Keep in mind I'm talking about Creative mode not survival!

**Comment by paramat** [comment]
" removed a dirt block out of your inventory" can you clarify? is the dirt block moved into trash?

**Comment by RHRhino** [comment]
@paramat 
No he just meant that he does not want that every block he breaks in the world gets added into the inventory. If you remove a building for example your inventory gets filled with all blocks you used there, although you might not need them again. You have to put them into trash before you can take the blocks you need from your creative inventory.

I'm afraid one can argue this behaviour into both directions: 
Some people prefer to get the blocks they break in the world into their inventory, other people just prefer to choose the blocks in the creative inventory and don't want to get spammed with blocks they remove in the world. 😕

**Comment by tobyplowy** [comment]
@RHRhino yes that's what I meant 

@paramat look at @RHRhino s comment Sorry If that wasent clear i did My Best To Explain It :/

**Comment by paramat** [comment]
I see, i also misread grass as glass.

**Comment by tobyplowy** [comment]
@paramat sorry I really did my best to explain it as good as I could I'm not native English :/

**Comment by paramat** [comment]
No problem it was actually fairly clear, my head wasn't clear and i misread.

**Comment by DS-Minetest** [comment]
i solve this problem by putting the not needed item somewhere out of the hotbar
i dont see a real problem

**Comment by tobyplowy** [comment]
@DS-Minetest becouse It Fills up your inventory with trap You Don't Need

**Comment by DS-Minetest** [comment]
if your inventory is already full, it cant be filled more and with shift click its that easy to clean the inventory

**Comment by tobyplowy** [comment]
@DS-Minetest jeh But That's The Problem If You Clean your inventory it Just gets Field with crap again

**Comment by DS-Minetest** [comment]
why do you need an empty inventory?

**Comment by C1ffisme** [comment]
@DS-Minetest Because the hotbar in Minetest Game is only so long, and there isn't a good way to empty your entire inventory immediately.

**Comment by tobyplowy** [comment]
@C1ffisme yes and even if you have a button to clear your full inventory you would also lose all the stuff you still need so that means that you have to pick everything again which would take a little minute ( I'm obsessed with comparing color palettes when I'm building That's Why it takes so long XD)

**Comment by DS-Minetest** [comment]
well, shift clicking the inventory  takes <10 seconds

**Comment by paramat** [comment]
Picking up 1 node is desirable though, i often need to quickly grab a node to build with by digging a nearby node.
Maybe instead request that only 1 node be picked up?

**Comment by tobyplowy** [comment]
@paramat well Do It Like Minecraft Does it Have a Block Pick Button

**Comment by rubenwardy** [comment]
:-1: from me, it's possible that mods might give you an item with meta data that might want to be kept

**Comment by tobyplowy** [comment]
@rubenwardy uhhh you're in Creative if you need something you just take it from the inventory

**Comment by rubenwardy** [comment]
you didn't read what I said. What if there's meta data attached?

**Comment by DS-Minetest** [comment]
I know a mod where you place a node, give it data via formspec, and then dig it to get an item, which uses this. => There might be other mods which would break a bit, too.
(If you want to know what mod I mean: [basic_machines](https://forum.minetest.net/viewtopic.php?t=12033), item: ball spawner)

**Comment by tobyplowy** [comment]
@rubenwardy 

> you didn't read what I said. What if there's meta data attached? And also, it's usually easier to dig an item to get a copy than to use the creative inventory

Well You Can Do It Like Minecraft did it you hold ctrl and use the pickblock button and you get the block with metadata, boom it's fixed now we have a good gameplay mechanic and all this stuff that could be wrong is good now ( the only thing that has to be Done Now is someone that is not Lazy)

**Comment by paramat** [comment]
We don't need another special key press combination for this.

**Comment by tobyplowy** [comment]
@paramat oh yeh Just Like we don't need people to like minetest!

**Comment by Ezhh** [comment]
Auto-pick up in creative saves a lot of time. Much better to dig one node then have it in inventory than to search for it. Sure, there are times when you also pick up unwanted things, but I think the advantage of auto pickup far outweighs the bother of deleting items every so often.

**Comment by tobyplowy** [comment]
@Ezhh I doesent ay you have to search for it in the inventory I said that The needs to be a button to do that so you don't automatically pick up shit you dount need

**Comment by paramat** [comment]
Disapproval from sfan5 http://irc.minetest.net/minetest-dev/2017-01-02#i_4776434
Closing due to 3 dev disapprovals.

**Comment by tobyplowy** [comment]
@paramat waw I didn't see this one coming Daaaarrrrrr

**Comment by dsohler** [comment]
Yeah, not important enough. Ivory Tower, anyone?
