### ISSUE TITLE
debug spam with "nodeupdate: deprecated" message

### ISSUE THREAD

**Issue by JurajVajda** [minetest/minetest_game#1402]
Can we cleanup a bit please, the debug log is full of "nodeupdate: deprecated" messages lately.

Applies for:
* core.check_for_falling
* core.check_single_for_falling

**Comment by paramat** [comment]
Check for a mod which may be calling nodeupdate. We'll check MTGame.

**Comment by paramat** [comment]
These need changing in MTGame https://github.com/minetest/minetest_game/search?utf8=%E2%9C%93&q=nodeupdate

**Comment by JurajVajda** [comment]
@paramat i did checked and fixed all not minetest_game standard mod and still getting the warnings, therefore this issue ;)

**Comment by paramat** [comment]
#1405 merged.
