### ISSUE TITLE
Carts: pass through on_rightclick to doors

### ISSUE THREAD

**Issue by sofar** [minetest/minetest_game#1415]
Currently if you wield a cart you can not open doors. This should be fixed in the same way torches and a bunch of other items were fixed recently.

**Comment by GreenXenith** [comment]
I believe this also happens to beds as well...holding certain items stops you from sleeping. What if my furnace is my teddy bear? D:

**Comment by sofar** [comment]
#1563

**Comment by Ekdohibs** [comment]
Closing as #1563 was merged.
