### ISSUE TITLE
Cart rails should be 'ground content = false'

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1417]
If placed in 'on generated' they will be eaten by overgenerating caves. As non-natural nodes they should be 'false'.

**Comment by DS-Minetest** [comment]
wouldnt the rails float then?

**Comment by SmallJoker** [comment]
They would float if there's not another non-natural node below. The modders will have to care about this problem.

**Comment by paramat** [comment]
If rails are placed in 'on generated' they will likely be part of a schematic and non-ground content nodes would likely be present below in the schematic to avoid floating.

**Comment by paramat** [comment]
#1425 merged.
