### ISSUE TITLE
Boats dissapears after taking in creative

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1426]
In creative - place boat in inventory, place it on water, go in a boat, remove boat from inventory, dismount it with mouse click - no boat in inventory.

This fix for carts may potentially help for boats: https://github.com/minetest/minetest_game/commit/788ae97ba17891aea44c81adc269c88ea6f18c90

**Comment by paramat** [comment]
Confirmed bug, and the issue doesn't occur for carts.

**Comment by paramat** [comment]
In fact boats are never added to inventory in creative mode when dug. You can place one without entering it, remove the boat from inventory, then dig the boat.

**Comment by paramat** [comment]
#1427 merged.
