### ISSUE TITLE
Dig sound needed for snappy group.

### ISSUE THREAD

**Issue by BluebirdGreycoat** [minetest/minetest_game#1430]
Here are two code excerpts. The cactus is missing digging sounds when the player digs with a *sword*, however digging sounds are played when the player digs with an *axe*.
The wood node has these sounds. As far as I can see, there is little functional difference between these two nodes, so what can be going wrong? Unless it has to do with the groups?

```lua
minetest.register_node("default:cactus", {
	description = "Cactus",
	tiles = {"default_cactus_top.png", "default_cactus_top.png",
		"default_cactus_side.png"},
	paramtype2 = "facedir",
	groups = {snappy = 1, choppy = 3},
	sounds = default.node_sound_wood_defaults(), -- This appears buggy?
	on_place = minetest.rotate_node,
})
```

```lua
minetest.register_node("default:wood", {
	description = "Wooden Planks",
	paramtype2 = "facedir",
	place_param2 = 0,
	tiles = {"default_wood.png"},
	is_ground_content = false,
	groups = {choppy = 2, oddly_breakable_by_hand = 2, flammable = 2, wood = 1},
	sounds = default.node_sound_wood_defaults(),
})
```

**Comment by maikerumine** [comment]
I confirm this occurs, it doesn't seem logical.

**Comment by maikerumine** [comment]
Maybe if it is added to wood group then the sound will be fixed?

**Comment by BluebirdGreycoat** [comment]
I think this is a bug in the engine, I've opened a new issue here: http://github.com/minetest/minetest/issues/4818

**Comment by paramat** [comment]
I think this is a lack of a 'default_dig_snappy' sound, see https://github.com/minetest/minetest/blob/785a9a6c1af424b0a46f334de7176c9e67341cfb/src/game.cpp#L4131
```
	if (sound_dig.exists() && params.diggable) {
		if (sound_dig.name == "__group") {
			if (params.main_group != "") {
				soundmaker->m_player_leftpunch_sound.gain = 0.5;
				soundmaker->m_player_leftpunch_sound.name =
						std::string("default_dig_") +
						params.main_group;
```
Try addng a sound called 'default_dig_snappy.ogg' to the sounds folder.

**Comment by BluebirdGreycoat** [comment]
I copied `default_dig_choppy.ogg` to `default_dig_snappy.ogg`, and lo, it works!

**Comment by sofar** [comment]
does it have to be choppy and snappy at the same time? I think that is the culprit.

**Comment by BluebirdGreycoat** [comment]
I think players are used to being able to use both axes and swords to chop cactus (this goes for wool, too).

**Comment by paramat** [comment]
Excellent.

Nodes with snappy group:
Wool.
All flowers.
Beds.
Saplings.
Leaves.
Bush leaves.
Xpane glass.
Farming crops.
Straw.
cactus.
Papyrus.
Dry shrub.
Junglegrass.
All grasses.

So a sound of a sword or scythe hacking at stems may be good.

**Comment by paramat** [comment]
Could you change the thread title to something like 'Dig sound needed for snappy group'?
Time for freesound.

**Comment by BluebirdGreycoat** [comment]
Done.

**Comment by paramat** [comment]
Note the gain is set in the engine so the sound loudness will have to be adjusted in the sample itself to balance with other dig sounds.

**Comment by sofar** [comment]
I'm fine with multiple sounds based on the tool btw, seems like a reasonable thing.

We don't have any sword sounds right now.

**Comment by paramat** [comment]
I found a sound of a scythe cutting grass, but it was too specfic so would be unsuitable for many of the uses, need a more choppy sound.

**Comment by paramat** [comment]
ALso i think we can remove 'snappy' from cactus, it's a metre thick after all so more 'choppy'.
Not sure about xpanes glass.

**Comment by paramat** [comment]
Found a sound, incoming.

**Comment by paramat** [comment]
See #1450

**Comment by paramat** [comment]
#1450 merged.
