### ISSUE TITLE
Corner stairs

### ISSUE THREAD

**Issue by SpaghettiDeveloper** [minetest/minetest_game#1443]
Hi guys. Add the corner block stairs, it is very useful. This block of Minecraft using a great deal to build buildings, and generic structures such as roofs, gardens, and more.

Here's one that I found screenshots on the official forum.

<a href='#' target='_blank'><img src='https://s17.postimg.org/g8ohsolnj/corner_stairs.png' border='0' alt='corner-stairs'/><br /><a target='_blank' href='https://postimage.org/index.php?lang=french'></a>

In mod "moreblocks" it is already present this block, but I think it would be very useful to include this block in Minetest_Game. I think makes Minetest even more complete, and all that is useful to build is a good thing for the improvement of the vanilla game.

Thank you all, and I sincerely hope to have made a request useful, which is appreciated by the community.

**Comment by tobyplowy** [comment]
@SpaghettiDeveloper +1 totally agree

**Comment by tenplus1** [comment]
https://github.com/tenplus1/stairs <-- corners and slopes :P

**Comment by SpaghettiDeveloper** [comment]
TenPlus knew you were great, and I was expecting a spectacular your answer like this. Thank you. Your mod is updated 17 days ago, so I hope to see it implemented in Minetest_Game vanilla? I take it for a "yes" Thank TenPlus;)

**Comment by paramat** [comment]
Seems reasonable.

**Comment by RHRhino** [comment]
If the corner stair parts are added to minetest_game, we should also discuss if they will be added by placing stairs and auto replacement to corner parts like in MC or if they are just craftable blocks.

**Comment by tobyplowy** [comment]
@RHRhino I want it to work automatically

**Comment by paramat** [comment]
No not automatic, that will often result in unwanted behaviour when the nodes are being used artistically or in a unique way, which is what players will want to do. Any auto placement will often act when not wanted, or not act when wanted, or act in the wrong way..

**Comment by tobyplowy** [comment]
@paramat It can be automatic but be Changed back to normal with the screwdriver

**Comment by SpaghettiDeveloper** [comment]
Thanks paramat :+1:

**Comment by sofar** [comment]
I'm not necessarily opposed to this, but in order to make this actually not look bad, you're going to need 2 (possibly 4) nodes for each corner type, because of the way how the textures align.

I'm not a fan of that at all, so I'd say, don't do this.

The only real way to solve this is to make a new stair drawtype in the engine, and I'm no fan of that solution either.

**Comment by SpaghettiDeveloper** [comment]
Sofar. I support the idea of Paramat, to implement corner blocks for each type of stair in the game, as a separate block! nothing automatic node, for the moment, then in the future we can improve. The stairs are very useful corner blocks to build.

The community also will appreciate this addition. Building is the soul of gameplay for Minetest.

**Comment by RHRhino** [comment]
> you're going to need 2 (possibly 4) nodes for each corner type, because of the way how the textures align.

Do we really need them? Currently mainetest_game stairs and slabs textures also do not align perfectly as well as the corner parts of moreblocks and most people still have no problems with that. So perfect texture alignment shouldn't be blocking this feature/addition if we really want it.

**Comment by sofar** [comment]
> Do we really need them?

The sole reason people are asking for this feature is "to make stairs look better".

The first comment when people actually see this will be "but it looks ugly and the textures do not connect:.

I'd rather leave this problem to mods. I have yet to see a mod that solves this problem and actually looks better and fixes texture alignment problems.

**Comment by Fixer-007** [comment]
I think we need this in long run for sure.

**Comment by SpaghettiDeveloper** [comment]
Have you included the walls In 0.4.14, Although I still do not connect well the nodes, and even The iron bars (now work much better), Have Done a great job, From 0.4.10 Minetest has Continuous improvements.

The corner stairs are undoubtedly an important feature of the game, a lot of Minetest you use to build the roofs of houses, gardens, floors, and much more. I vote for the "YES"

**Comment by C1ffisme** [comment]
@sofar 
> I'd rather leave this problem to mods. I have yet to see a mod that solves this problem and actually looks better and fixes texture alignment problems.

I hate to get a bit offtopic, but the sad thing is that mods are not a reliable source of content. Most Minecraft mods are usually medium or high quality because of how much effort goes into learning how to program them. (With the exception of the often poor quality 'Emerald/Obsidian Tool' mods made with [MCreator](https://mcreator.pylo.co/) or similar 'code generators'.)

A Minetest mod, on the other hand, is very easy, because it does not require a development environment to compile, nor does it require fairly good knowledge of how to program. In fact, if someone had enough skill to read and understand code, they could copy-paste from MTG to create the simplest mod. This means that you will find a lot of small, 'only adds static nodes and items and sometimes tools, with the occasional oregen.', mods, to clutter good ones like pipeworks or mesecons.

Back on topic, I support corner stairs. I suppose we could avoid adding too many nodes if we either (1) added a new 'stairlike' drawtype, or (2) made the connected type more customizable. Although option 2 means a much better API feature, I would be fine with option 1, since it could be useful as a ground-block. (No more jumping up hills!)

**Comment by sofar** [comment]
@C1ffisme I don't disagree with you. But it's really easy to merge something once the concept has been proven to work well and look good in a mod. (3D torches, or carts, anyone?). This is how minetest_game has grown fairly well, and there are definitely many mods out there which are totally eligible for merging (e.g. playeranim, or 3dwield, others).

My intent wasn't to say "it'll be in mods forever", but "show me a good mod that does this, and I'll work on merging it", as I have with several mods in the past.

**Comment by C1ffisme** [comment]
@sofar 
> My intent wasn't to say "it'll be in mods forever", but "show me a good mod that does this, and I'll work on merging it", as I have with several mods in the past.

That's actually an okay compromise I can live with, the only problem is that mods can't edit the engine, so certain limitations pop up.

**Comment by paramat** [comment]
I'm fairly neutral on this, however i can't see a problem with textures not aligning perfectly, this already happens a lot, it's not worth even trying to create perfect alignment, it's broken by rotation.

**Comment by rubenwardy** [comment]
I like the idea of corner stairs

**Comment by Ferk** [comment]
minetest#682 could help with the problem of the textures not matching

**Comment by MarkuBu** [comment]
After adding the new stairs placement I think about to add this feature, including automatic placement (optional)

**Comment by Fixer-007** [comment]
@MarkuBu Any progress on this?

**Comment by paramat** [comment]
These need to be meshnodes to reduce interior faces.

**Comment by MarkuBu** [comment]
> Any progress on this?

Not yet. Working on the pathfinder, but I don't have much time anyway. But I didn't forget it

**Comment by MarkuBu** [comment]
I will use the node box from moreblocks for the first time. They can be replaced by mesh nodes later.

Auto placement is really tricky.

**Comment by MarkuBu** [comment]
That was the easy part 

![screenshot_20170516_114258](https://cloud.githubusercontent.com/assets/16163058/26100023/eaf9dfdc-3a2c-11e7-8ed7-5ffb317109f5.jpg)

**Comment by paramat** [comment]
We don't need auto-placement, just rotation according to player's diagonal view direction.

**Comment by MarkuBu** [comment]
Will try it anyway. 

It's now possible to build something like this without a screwdriver

![screenshot_20170516_202718](https://cloud.githubusercontent.com/assets/16163058/26121959/3157228e-3a76-11e7-8987-b0e9a8fa11e4.jpg)

**Comment by paramat** [comment]
#1820 merged.
