### ISSUE TITLE
Remove 'oddly breakable by hand' from glass?

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1451]
Currently it takes a long time to break glass or xpanes glass pane using a pick, but is instant using the hand or anything else, because anything else registers as a hand.
Is there a reason glass has this group?

**Comment by RHRhino** [comment]
I think it is because it is more realistic to break glass with your hand than a tree. 😄 
In MC glass gets destroyed and disappears when you dig it. It makes more sense that you can destroy it by hand, but less sense that you can dig and collect it.

**Comment by paramat** [comment]
Well, tree has to be breakable by hand, glass does not. A solid cubic metre of glass is pretty tough.

**Comment by DS-Minetest** [comment]
the glass node has cracks, because when you burn it, it cools from outside and there is a reduced pressure inside the glass relative to outside => its not that tough
obsidian glass doesnt have cracks for some reason
braking glass by hand would hurt the player in real life, what about hurting sam, too if he digs glass by hand?

**Comment by RHRhino** [comment]
@paramat Is our block of glass really filled entirely with glass? I always thought it just has thin glass faces and air inside of it, so easily breakable. (but that discussion is a bit offtopic)
What I meant with my comment was that in MC the glass just gets smashed and not collected/digged and smashing windows should work with your hand as fast as with a pickaxe. I hope that answers your question.

**Comment by paramat** [comment]
Yes solid glass, as it has no visible inner glass faces.

**Comment by paramat** [comment]
Any objections? WIll make a PR.

**Comment by paramat** [comment]
Closing as i might have a better idea.
