### ISSUE TITLE
New textures trees wood!

### ISSUE THREAD

**Issue by SpaghettiDeveloper** [minetest/minetest_game#1452]
Hi everyone. About a year ago, I drew new textures for wood of trees. Then I had problems and I dropped my forum account.

Fortunately my textures are not lost! I am working to make a good editing, to send them to you, hoping to see them included in minetest_game.

The textures of default trees have a big flaw! create textures breaks, have you noticed? my idea has always been to create new textures based on the defaults, which have the same visual effect of Minecraft!

Here are some screenshots with descriptions, so you can see the differences.

------------------------------------------------------------------------------------------------------------------

Original texture:

<img src='https://s18.postimg.org/q279dfvwp/screenshot_20161211_201016.jpg' border='0' alt='screenshot_20161211_201016'/><br /></img>

My Texture:

<img src='https://s29.postimg.org/rv8546xzb/screenshot_20161211_201043.jpg' border='0' alt='screenshot_20161211_201043'/><br /></img>

No textures of Minecraft! I created them, starting with the default textures Minetest! I invite you to check every detail :D

I carried the wood for all the trees! I just made a new editing of Jungletree.

I hope you like it, I'm happy to have found the work I have done long ago, initially for a texture pack that I never finished.

If for you it is ok, I finish the final details and send the finished textures. Thank you all.

I can show the technique I use to create these textures. is very simple, I take a default textures, and I change the colors, and the design of more pronounced wood grain. The standard Minetest textures have badly faded colors, I was inspired by minecraft course, but none of these textures have a single pixel equal to minecraft textures! I hope I explained myself, my english is bad :)

**Comment by Ferk** [comment]
Honestly, I like the current tree texture better than this or than Minecraft's.
I don't understand why people are so in love with Minecraft textures, to be frank.

**Comment by SpaghettiDeveloper** [comment]
I'm not in love with Minecraft, are the only one who has not bought Minecraft and we do not play. But the standard textures of Minetest trees, do not create continuity, and have little detail. The woods are very important in the building, for this reason eight months ago, I worked with these textures. The difference is remarkable. So much work to make the textures similar to Minecraft style, but by using only the Minetest textures. I am satisfied with the result, and I think it's a welcome addition for many users.

If you do not like to give up, but to grow Minetest are also important the little details. @Ferk Thanks for your comment.

**Comment by sofar** [comment]
Make a PR so this can be properly discussed. This is an "Issue" and we don't use issues to approve features.

**Comment by SpaghettiDeveloper** [comment]
@sofar Sorry, the public throughout the forum then? at least you have given me hope! Ok I open a post for voting on the forum, listen to the voice of the people. Thank you.

**Comment by tobyplowy** [comment]
@SpaghettiDeveloper wait a second are you this guy? https://forum.minetest.net/memberlist.php?mode=viewprofile&u=19343 also you should do this in a pool request

**Comment by SpaghettiDeveloper** [comment]
@tobyplowy Easatto! Thank you, you knew right away that I wanted to express the concept. StepDevelop am I, but I had to leave the account for personal problems, now I'm back with this new account, that I also use for my blog, fb, and more. At least now it's all clear, I'm always afraid of being misunderstood.

**Comment by tobyplowy** [comment]
@SpaghettiDeveloper Hey I did some Research on your Texture its again a edit from Minecraft but Upside Down And recolord

**Comment by SpaghettiDeveloper** [comment]
@tobyplowy I changed the color, the bark is made using the cutting area and to move pixels one by one. If you look at the texture acacia, it is the default with improved color and sharper bark. In conclusion is an editing job, When I have time, I make a comparison (screenshot gimp project). I want to change the jungletree, and increase the effect on the mossy bark, cyl color I took it from the mossy cobblestone default, but would like to improve the visual effect.

**Comment by tobyplowy** [comment]
comperason of @SpaghettiDeveloper s texture and minecraft texture
![dsgfhj](https://cloud.githubusercontent.com/assets/16853304/21083283/37da9cb6-bfed-11e6-8d60-1968795b2d63.png)

**Comment by tobyplowy** [comment]
@SpaghettiDeveloper No Need to make a comparison I already did, Sorry For The bad layout and crappy photo editing

**Comment by SpaghettiDeveloper** [comment]
They look the same? inspired design, but equal not! 8 months ago, many users have used my texture pack, no one said the opposite. Realizable screenshots of the Gimp project which I did.

<img src='https://s24.postimg.org/t1picd6id/Minecraft_screenshot.png' border='0' alt='Minecraft screenshot'/><br /></img>

**Comment by tobyplowy** [comment]
@SpaghettiDeveloper I'm having trouble to understand your comment Are You saying You Made it similar but not really the same (it's 95% the same in my opinion)

**Comment by SpaghettiDeveloper** [comment]
Near You see him as perhaps better.

<img src='https://s28.postimg.org/j426hgnkd/screenshot_20161211_221828.jpg' border='0' alt='screenshot_20161211_221828'/><br /></img>

**Comment by SpaghettiDeveloper** [comment]
But it is not at all like it! the time to publish the enlarged textures, the default Minetest, and those mine, then you see that are editing the original Minetest, I only took inspiration from Minecraft bark, but it is totally redesigned, with no loss of quality, redesigned pixel by pixel . Are raster images, you can see if you make only scaling.

**Comment by tobyplowy** [comment]
@SpaghettiDeveloper Can you give me the original 16x16 texture

**Comment by SpaghettiDeveloper** [comment]
Of course! Audience All textures What I did trees wood. A minute.

**Comment by tobyplowy** [comment]
@SpaghettiDeveloper they are the same top is your bottom is minecraft (they are also a bit lihter so you can see it better)
![naamlohtyjos](https://cloud.githubusercontent.com/assets/16853304/21083480/dadd661a-bff1-11e6-9ff4-ecce65503151.png)

**Comment by tobyplowy** [comment]
@SpaghettiDeveloper they are a bit Different but not Enough

**Comment by SpaghettiDeveloper** [comment]
Not published the previews ??? here goes, I did cut region of gimp

<a href='https://postimg.org/image/pkpakumzj/' target='_blank'><img src='https://s27.postimg.org/th2mgu7z7/acacia.png' border='0' alt='acacia'/><br /></img>

<a href='https://postimg.org/image/lhyq56zjd/' target='_blank'><img src='https://s28.postimg.org/tngs3cnsd/tree.png' border='0' alt='tree'/><br /></img>

<a href='https://postimg.org/image/5z8hpcrjx/' target='_blank'><img src='https://s30.postimg.org/59ppczr0h/jungletree.png' border='0' alt='jungletree'/><br /></img>

**Comment by SpaghettiDeveloper** [comment]
They are different from those you have published. In screenshots it is much less noticeable, as you see there are differences, and see the shades of colors.

**Comment by tobyplowy** [comment]
@SpaghettiDeveloper the gray texture looks like a new texture ( that's a Good thing I Guess)

**Comment by tobyplowy** [comment]
@SpaghettiDeveloper the gray texture is nice is it acacia wood?

**Comment by C1ffisme** [comment]
Maybe I'm making a mistake posting on this closed issue, but I'll go ahead and say it anyway, this texture doesn't match up with the rest of Minetest's textures.

If you look at the flowers in those screenshots, you can see that they contain quite a few different colors, while Minecraft textures only have a small number of colors to keep a 'retro' feel to them. (That might also save hard-disk space, but I don't really know if that's true or not.)
