### ISSUE TITLE
Weapons very slowly wear off

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#1454]
I feel the amout of wear added to weapons (swords, pickaxes, shovels, axes) is very small when you use them as a weapon. It is much smaller compared to the usual digging use counts.

When you use a weapon to attack other players, the wear seems to be reduced by a small amount only. This even seems to be the same wear count for all weapons. Wooden tools appear to wear out as fast as diamond tools, when attacking with them.

Even using a wooden shovel as weapon wears it off very slowly.

Is this maybe intentional or have discovered a legit game balancing issue?
Or is this maybe a bigger issue with Minetest's damage system?

**Comment by sofar** [comment]
There is no wear when you punch a player with *any* tool, not even swords.. I've submitted PRs to `minetest` for this a while back.

**Comment by Wuzzy2** [comment]
Oops, you are right. Don't ask me what I've smoked yesterday. This is a non-issue.
