### ISSUE TITLE
Diamond axe breaks earlier than mese axe

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#1456]
It turns out the diamond axe breaks much earlier than the mese axe.
According to my calculations, it already breaks after only 270 uses on tree blocks (`choppy=3, level=0`), compared to 540 uses of the mese axe.

Proof:
Recall the formula to calculate the real use count:
`real_uses = uses * (3 ^ (maxlevel - level))`

`groupcaps` of mese axe:

    choppy={times={[1]=2.20, [2]=1.00, [3]=0.60}, uses=20, maxlevel=3},

Uses on level 0: `20 * (3^(3-0))` = `540`

`groupcaps` of diamond axe:

    choppy={times={[1]=2.10, [2]=0.90, [3]=0.50}, uses=30, maxlevel=2},

Uses on level 0: `30 * (3^(2-0))` = `270`

---

Suggested bugfix: I guess the problem lies in `maxlevel=2` in the diamond axe's `groupcaps`. It should probably be 3. That way, the use count will increase to 810.

**Comment by paramat** [comment]
Maxlevel needs to remain unchanged, but uses could be tuned, diamond and mese are considered roughly equal in strength.
A PR would be appreciated.

**Comment by paramat** [comment]
Apparently:
"All the diamond and mese tools have maxlevel=3.
Except the axe, so to make it consistent the diamond axe should have maxlevel=3"
So i agree with this suggestion.

**Comment by paramat** [comment]
PR #1854

**Comment by paramat** [comment]
#1854 merged.
