### ISSUE TITLE
Cart stucks and jitters when punched while going up and doing sharp turn

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1458]
Explanation: Cart stucks and jitters when punched while going up and doing sharp turn. Bug happens if I punch just near the top before the turn. If without punching - no problems.
Demo of the bug: https://imgur.com/a/3gTMb
Pic: 
![carts bug](https://cloud.githubusercontent.com/assets/16494741/21203249/53f04ce2-c25a-11e6-83ec-dd0eaf876d9e.png)

Minetest Game: 12 dec 2016
Reproduced on: Cash World server

**Comment by sofar** [comment]
Punching is weird, if you use enough powered rail and *not* punch the cart all the time, does it work properly?

**Comment by Fixer-007** [comment]
Yes, bug happens if I punch just near the top before the turn.

**Comment by sofar** [comment]
I'll certainly look at the punch weirdness, it's bothersome, but continuously punching isn't what I'd like to see in minetest_game anyway, and I hope players are not relying on it.

**Comment by paramat** [comment]
The intention is to use continuous power rails on climbs that provide a gentle uphill acceleration so that punching is not necessary, so i think this is low priority.

**Comment by Fixer-007** [comment]
>Are you still able to dig the cart to escape the situation?
yes

**Comment by paramat** [comment]
Ok not so bad then. We can tackle this after release.

**Comment by Fixer-007** [comment]
I wonder how it works now, and as usual server of interest is down. Will post an update later.

**Comment by Fixer-007** [comment]
Since that server has boostcart mod, I decided to test this on localhost with carts, tried many times and had no problems. I guess I will close it and reopen if someone reconfirms it again.
