### ISSUE TITLE
Furnace afterburn can be used to smelt hundreads of blocks after been away from area

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1459]
I had 6 furnaces with about 10 cacti in each as fuel, I've put about 10-20 of sand in each to smelt and went away for few minutes (<5 min) 160 blocks away, I came back and saw smelted glass and burning out cacti suspiciously slowly (for many minutes). You can smelt huge amounts of stuff, feels like longer you was away - more it can cook. In my testing I calculated that 1 cactus afterburn can cook on the order of thousand sand blocks.

Bug was reproduced on minetest/minetest@2886f0c (after that Dec 7 furnace change 4a5206e) in singleplayer.

I also consider this gameplay cheat-bug as potential blocker.

**Comment by sofar** [comment]
I've rebased #1457 to include a fix for this.

**Comment by Fixer-007** [comment]
It only partially fixes the problem, here is copy-paste from chat for others to follow:
```
[01:27:06] <Fixer> sofar: damn, long cook bug is more complex
[01:27:46] <Fixer> sofar: it is fixed when sand cooking is done and you approach it -> furnace shutdowns
[01:27:53] <Fixer> here is bad part
[01:28:47] <Fixer> sofar: there were 2-3 cacti remaining so I've put 30 sand in it and fly away - wait few minutes - come back, still cooks the sand... BUT, now this bug again, it still overcooks loots of sand :(
...
[01:46:09] <sofar> the problem is the fuel_totaltime variable
[01:50:16] <Fixer> sofar: demo https://imgur.com/a/ZY3wM
```

**Comment by paramat** [comment]
I'm beginning to wonder if we should revert the ability of furnaces to work while distant, for the release. These bugs are worse than losing that ability.

**Comment by sofar** [comment]
It's either fix it right, or revert (and frankly, after having looked at the code for 2 hours today, including myself coming up with my own solution as to how I'd want to see it work, I'm pretty unimpressed by the code, and the patch just messed it up.)

So, I might indeed want to revert the original patch as well.

**Comment by paramat** [comment]
Revert is fine by me.

**Comment by Fixer-007** [comment]
#1457 fixed the problem for me

**Comment by paramat** [comment]
#1457 merged
