### ISSUE TITLE
Runtime error from mod 'default' in callback LuaABM::trigger()

### ISSUE THREAD

**Issue by tchncs** [minetest/minetest_game#1461]
Heyo, i just merged the latest mtg changes and ran into the following error:

```
ServerError: Lua: Runtime error from mod 'default' in callback LuaABM::trigger(): 
         ...st/bin/../games/minetest_game/mods/default/functions.lua:359: attempt to 
         call field 'check_for_falling' (a nil value)
stack traceback:
         ...st/bin/../games/minetest_game/mods/default/functions.lua:359: in function 
         <...st/bin/../games/minetest_game/mods/default/functions.lua:332>
```

**Comment by sofar** [comment]
Do you need to update minetest as well?

**Comment by paramat** [comment]
Yes 'check for falling' is the new name for 'node update'https://github.com/minetest/minetest/commit/649448a2a91fbf3e944b2f2e739f4e2292af1df0 you need to update the engine.

**Comment by tchncs** [comment]
Ah right, my minetest build was from 2nov or something and 'til now it seems stable.
Thanks for the hint and sorry for the false alarm. :)
