### ISSUE TITLE
Change brick texture

### ISSUE THREAD

**Issue by garywhite207** [minetest/minetest_game#1463]
I created a new brick texture to be considered for possibly 0.4.16, as I don't want to back up the release of 0.4.15 trying to get this reviewed.

![screenshot_20161217_121456](https://cloud.githubusercontent.com/assets/19475031/21289509/c8ab6760-c453-11e6-9186-146d96105fe3.png)

This is my texture above

Below is the regular brick from 0.4.14 for comparison:
![screenshot_20161217_121628](https://cloud.githubusercontent.com/assets/19475031/21289514/e795033e-c453-11e6-93c0-0c185450705d.png)

**Comment by paramat** [comment]
Is this a 32x32 texture?
It lacks the texturing of the current one so the bricks and mortar are too uniform.
The lowest row of bricks seem narrower than the others?

**Comment by garywhite207** [comment]
@paramat it's in snow, so it's cut off. Should have thought that one through

**Comment by paramat** [comment]
Yeah i guessed it was cutoff, but the lowest layer of bricks visible in the top node look narrower.
Note this texure must be 16x16 to match the other mtgame textures.

**Comment by paramat** [comment]
Oops sorry thought this was closed accidently.

**Comment by garywhite207** [comment]
I can probably redo it as a 16x16, but it'll probably look worse
