### ISSUE TITLE
Buckets should not run out of water in creative

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest_game#1464]
The title says it all, Buckets should not Run Out Of Water in Creative (i tested minetest with a  couple of children and they all Use the Buckets and dount understand How to get Infinite water so they just filled up their inventory with water buckets it was quite funny but I don't really blame them (pardon my language but) but for God's sake you're in creative mode everything needs to be infinite (I know one of the first comments Will Be There is a water source Block also there will be a couple people saying theres mods for this I know so Please Don't) that's it also this description is way too long for what I'm asking for XD

**Comment by C1ffisme** [comment]
That's what water/lava sources are for.

> (i tested minetest with a couple of children and they...

Are probably used to Minecraft.

I wouldn't mind replacing the water sources with Minecraft's more sensible behaviour, though. Even in creative mode, carrying blocks of water seems a bit debug-ish.

**Comment by Napiophelios** [comment]
Funny, I can't stand the infinite supply of everything in creative.
Its really annoying when placing doors and boats and beds.

You can nab anything from the inventory at anytime in creative,
I don't understand the desire for this infinite supply behaviour.

If I place a boat it should be gone from my hand,
If I need another just open the inventory...voila

**Comment by tobyplowy** [comment]
@C1ffisme yes they are, at least only two of them the others are completely new to mintest and have never played Minecraft

**Comment by tobyplowy** [comment]
@Napiophelios 

> Funny, I can't stand the infinite supply of everything in creative.

Why are you in creative mode in the first place then why not survival XD

> If I place a boat it should be gone from my hand,
> If I need another just open the inventory...voila

That's not How creative mode shuld work that ruins The workflow of building

**Comment by Napiophelios** [comment]
I think you are missing my point.
creative mode already gives you an infinite supply of whatever you want;
why does the stack in my hand need to be infinite, 
if I can just get more from inventory as needed.

Its just my opinion, I am not saying its wrong
I just don't like it.

**Comment by tobyplowy** [comment]
@Napiophelios ok Sorry For The misunderstanding :/

**Comment by sofar** [comment]
>I think you are missing my point.
>creative mode already gives you an infinite supply of whatever you
>want;
>why does the stack in my hand need to be infinite

I disagree 

Building a water feature in creative is terribly unpleasant as it is right now. I constantly have to open my inventory to get more water buckets, and then the inventory is flooded with empty buckets. 

It's just terrible.

**Comment by tobyplowy** [comment]
@sofar true

**Comment by paramat** [comment]
Why not just place water source nodes, which are infinite?

**Comment by tobyplowy** [comment]
@paramat Yes I know I use water blocks but It Would Be More logical to be able to use brackets, Why are they not Infinite You're in Creative (also water source blocks look a bit strange to use The Minecraft players and noobs will find it more logical to use buckets and it looks better in my opinion)

**Comment by NathanSalapat** [comment]
I know most tools don't take damage in creative, should be a relatively trivial code change, just a check for if the game is in creative mode, and then returning a full bucket rather than an empty.

**Comment by DS-Minetest** [comment]
but then also please do the same with air filled bucket, you could place air nodes to delete fluids but if buckets with fluids dont get empty buckets with gas shouldnt do neither

**Comment by paramat** [comment]
The water node is usable and is intended for infinite water. Creative infinite water buckets are exactly that, each bucket empties and returns an empty bucket, it makes sense.
:-1:

**Comment by tobyplowy** [comment]
@paramat Why would you need to empty out a bucket in creative mode :/

**Comment by NathanSalapat** [comment]
@tobyplowy you realize of course that the exact same question can be asked in regards to why you'd need a full bucket in creative. Make a mod that uses your idea if you think it is so useful. I'd do it myself if I had more time, might try over this extended weekend.

**Comment by tobyplowy** [comment]
@NathanSalapat because of inconsistencies You're in Creative Why is it not Infinite?

**Comment by paramat** [comment]
> Why would you need to empty out a bucket in creative mode

You don't need to, but this is irrelevant.
Creative provides an infinite number of items, each of which acts as normal, so buckets empty.
Use the source nodes for infinite water.
Only use the buckets for, for example, filling up a machine which uses them for some purpose.
Changing bucket behaviour in creative is unnecessary extra code.

**Comment by tobyplowy** [comment]
@paramat I have already see where this is going you disapprove the idea so it's a no (I guess it is what you call a mod thing >:)

**Comment by Ferk** [comment]
> Why would you need to empty out a bucket in creative mode 

@tobyplowy Actually, you *do* need an empty bucket to remove liquid nodes, whereas you *don't* need a full bucket to place a liquid node (since you can place sources directly in creative).

To me, this request would have made more sense if it was asking for empty buckets in creative to never get filled and be always empty, since this way you can use a bucket to clear up an area of water, which currently wouldn't be possible otherwise.

Actually, currently you can clear an area of water if every time you put water in an empty bucket you immediatelly empty the bucket back into some other water source (which would drain your water without really creating a new water node). 
If your suggestion was implemented this would be no longer possible.

You could say that you want both (never empty a bucket and never fill up a bucket), and while this would be more reasonable I would still not recomend it if you really want to keep consistency across mods. Because the bucket mod from MTG cannot ensure this will work for other mods that fill up (or empty) buckets in unconventional ways (milking cows?). This could be done nicely, though, if there was an API to clear/empty the bucket in the bucket mod that was used by other mods.
But I'm not sure if it's worth the effort.

> @NathanSalapat because of inconsistencies You're in Creative Why is it not Infinite?

According to that logic you could also argue that picking up an item from a chest should never remove the item from the chest inventory if you are in creative. You could think of you placing something from your bucket to the world the same as when you place something from your chest to your inventory.

The bucket is an item that completelly switches to a different state when used. There's no other item in MTG that does this. The tools losing durability are not comparable.

**Comment by paramat** [comment]
> you disapprove the idea so it's a no

Other devs may support your idea though.

**Comment by rubenwardy** [comment]
I'm not keen on this, it makes the bucket pointless

**Comment by tobyplowy** [comment]
@rubenwardy I don't understand Why you have to empty a bucket in Creative if you want an empty bucket You just take it from the inventory

And the water source block looks really crappy like someone was too Lazy to program a proper mechanic oh wait

**Comment by juhdanad** [comment]
I think infinite empty bucket would be a great help in removing liquids. This is (mostly) why I support infinite buckets.

**Comment by paramat** [comment]
>  I don't understand Why you have to empty a bucket in Creative if you want an empty bucket You just take it from the inventory

Just because there is an empty bucket does not mean that the full buckets should have infinite liquids.
Re-read https://github.com/minetest/minetest_game/issues/1464#issuecomment-268746054

We could have a separate issue for infinitely empty bucket.

**Comment by paramat** [comment]
@sfan5 @Ekdohibs @ShadowNinja any opinions?

**Comment by Fixer-007** [comment]
Just use water source in creative instead of bucket

**Comment by numberZero** [comment]
That might be an option that some people would like. But I don’t consider it necessary. Moreover, buckets are used in machines that could be broken by such change.
So, I suggest removing full buckets from creative inventory in favor of liquid sources.
And, well, liquid removal tool would be nice to have too, it might be even craftable (bucket+mese+sand?)

**Comment by paramat** [comment]
Full buckets are needed in creative inventory, there may be crafting recipes that use them or a machine that uses them in large numbers.
Players will soon learn to use the sources instead.
I feel this can be closed now.
