### ISSUE TITLE
make bookshelf craftable with written books

### ISSUE THREAD

**Issue by DS-Minetest** [minetest/minetest_game#1466]
wouldnt it be more logical to craft a bookshelf with written books, too?

**Comment by C1ffisme** [comment]
If the bookshelf gives you back the book in the bookshelf inventory, then I can agree with that.

**Comment by paramat** [comment]
The written books would disappear on crafting :-1:

**Comment by DS-Minetest** [comment]
ill close this since @SmallJoker opened the PR

**Comment by C1ffisme** [comment]
@DS-Minetest No, keep this open. The issue is closed when the PR is closed.

**Comment by DS-Minetest** [comment]
ok

**Comment by DS-Minetest** [comment]
Now that @paramat closed the PR, should I close this issue, too?

**Comment by paramat** [comment]
Closing.
