### ISSUE TITLE
Possible to fall off the edge of the world with boat

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#1469]
Here's a funny bug:

1. Go to the edge of the world
2. Find an ocean at the edge
3. Place boat on the water
4. Sit on the boat and ride to the edge
5. Wheeeeeee! You will now fall off the world :D

**Comment by Fixer-007** [comment]
Funnily I did the same thing few days ago to test that crash on world border.

**Comment by paramat** [comment]
Can't wait to reproduce this.

**Comment by paramat** [comment]
Being able to sail off the edge of the world is somewhat cool, but if it happens and you fall a long way it may be difficult to escape the situation.
This probably needs engine work.

**Comment by MT-Modder** [comment]
> it may be difficult to escape the situation

Trapped outside of reality..!?

**Comment by paramat** [comment]
Fixed by https://github.com/minetest/minetest/pull/5856

**Comment by Wuzzy2** [comment]
What happens to the player on the boat then?

**Comment by paramat** [comment]
The player is automtically detached and is left standing on the world edge, so seems fine.

**Comment by paramat** [comment]
https://github.com/minetest/minetest/issues/5889 merged.

**Comment by paramat** [comment]
Alternative fix #2044
