### ISSUE TITLE
ChangeLog for 0.4.15 missing

### ISSUE THREAD

**Issue by ensonic** [minetest/minetest_game#1470]
There are no changelog entries for the 0.4.15 release at
* https://github.com/minetest/minetest_game/releases/tag/0.4.15
* http://dev.minetest.net/Changelog

**Comment by rubenwardy** [comment]
Wrong repo, you want minetest/minetest

**Comment by paramat** [comment]
The changelog is not present in the tag page, and wiki issues are not suitable for issues here (otherwise we would have hundreds of wiki issues, it's very out of date).
We won't forget the changelogs, devs are very aware these need doing.
