### ISSUE TITLE
Cactus and papyrus have no light checks for growing

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1471]
Currently they can grow in the dark, inconsistent with all other plants and saplings.
Since the light level would need to be checked at the node above the top, grow lamps would need to be a column 3 nodes tall to work.
Luckily the grow functions for both are global so can be overriden by those who want to unreasonably grow stuff in the dark.

**Comment by Wuzzy2** [comment]
But … but … I like my underground cactus and papyrus farms! :-(

**Comment by paramat** [comment]
Sure, this is similar to the sapling issue. From the start all plants and crops have required level 13 to grow, light checks were just missing from saplings, cactus and papyrus. Fixing this will annoy some but perhaps you agree it's reasonable and consistent? You will need meselamps to grow these.

**Comment by Wuzzy2** [comment]
Well, if they just require light, but not sunlight, I might be OK with it.

**Comment by paramat** [comment]
I wouldn't do anything to make farming underground impossible, you would need meselamps directly beside the plants, mese ore is not rare.

**Comment by DS-Minetest** [comment]
> sunlight

there is no real sunlight, it doesnt distinguish from other light

**Comment by paramat** [comment]
#1472 merged.
