### ISSUE TITLE
Bad item descriptions: Too generic descriptions among specific descriptions

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#1473]
Minetest Game has a strong tendency towards mixing generic item names among more specific item names. This is a bad naming practice IMO and it makes Minetest Game look a bit unprofessional.

Example: We have 5 tree species (jungle tree, acacia tree, …), but one of them is just called “Tree” without qualifier. Why this is bad? “Tree” doesn't sound like a species on its own.

Another reason why this is bad: In documentation, you can't just say “Place sand into the furnace” when you meant to say “Place `group:sand` into the furnace”, because the name “sand” is already used for the specific item `default:sand`. And obviously, nobody should literally write `group:anything` into user-directed documentation.
If all 3 types of sand have distinct qualified names, you can now safely say “sand” to refer to the group and “yellow sand” (or whatever name we'll pick) for `default:sand` (as opposed to the group). This will make writing user documentation much easier and less wordy.

As a general rule of thumb, I suggest adopting this practice:
Whenever there are 2 or more similar items (e.g. 3 types of sand) which clearly belong to the same group (from the player perspective, not neccessarily from a technical perspective), none of these should have a generic (unqualified) name, instead all of the items should have a qualifier.
For example, if you have sand, desert sand and silver sand, the word “sand” is ambigious as “sand” could equally refer to the group.
Bad: Sand, desert sand, silver sand.
Good: Yellow sand, desert sand, silver sand.

How to fix this: Rename all items with an overly generic name and make sure all item names have proper qualifiers (when adding such a qualifier makes sense).

Here are my rewording suggestions and ideas:

- Sand: Rename to one of these (pick your favourite): “beach sand”, “yellow sand”, “golden sand” (an allusion to the silver sand)
- Stone: Gneiss, granite, gray stone, graystone, common stone, plain stone, true stone
- Water: Ocean water, sea water (as opposed to river water)
- Sapling, Wooden Planks, Tree, Leaves, Wooden Fence, Wooden Fence Gate.: These are the worst offenders. It drowns the game in generic words for a specific tree species. We should start to actually give the awfully generic “tree” (the ACTUAL tree, not the node (`default:tree`)!) a proper species name. I don't really have an idea. “Apple tree” maybe, because of the apples?
- Rename “Tree” (the node) and all other trunk nodes to “tree trunk”. Clearly the single block is not a tree itself, so the name ”Tree” is just plain wrong.
- Rename “Cotton” (`farming:string`) to “string” or “cotton string”. Why was this named “cotton” anyways? Even if this is correct English, this is very confusing as the plant is also called like this
- While we're at it, assign the cotton plant and wheat plant the description “cotton plant” and “wheat plant”, respectively. Yes, the player is not supposed to get those, but some mods want to parse the node definition
- Bush Leaves, Bush Stem: No idea, but since we also have acacia bushes, the “generic” bush name should be changed

Feel free to add your own renaming suggestions or post item names you don't like.

**Comment by C1ffisme** [comment]
I'll give my opinions in order:

* White Sand (It honestly looks more white after it was changed from older versions)
* While I like the idea of more advanced geology in Minetest, nobody actually likes the idea of revamping the current system. I'd be fine with Greystone or Commonstone, though. Just don't use the description: "Commonstone Cobblestone".
* How about Saltwater and Pure Water? That could mean purified water has some actual value in the game, especially so if (realistic) mods require Pure Water rather than Salt Water.
* Make it Apple Tree. Don't make Oak Trees give apples, unless you plan on replacing apples with whatever Oak trees grow.
* How about just 'Log'?
* While you're at it, go ahead and rename wool to cotton. It made sense when wool couldn't be crafted, and now it doesn't.
* I actually don't know of any mod that would need the definition of a node that's `not_in_creative_inventory`. (BTW, that description itself should probably have a shorter alias, and the longer name be depreciated.)  If you know of one, link me to it.
* I'm clueless on this one.

**Comment by tenplus1** [comment]
Sometimes it's handy to have generic items in-game for use with custom mods and adventure games without the need to add new nodes for every little thing, letting the players imagination fill in the gaps themselves :)

**Comment by paramat** [comment]
:-1: I agree with using non-generic names from now on, but changing existing names would be a nightmare and just not worth the disruption, there was a thread in the forum about 'tree' where this was discussed.

> And obviously, nobody should literally write group:anything into user-directed documentation.

Yes they should, that would be the clear and precise langauge to use, groups are part of the game so need to be mentioned.

I deliberately used generic 'bush' names to allow multiple uses for those nodes, for example using the 'bush leaves' as nodes to create hedges or hedge mazes. The one stem could be used with many different bush leaf species. The bush stem drops a generic 'wood' plank so had to be generic.

Aliases should be avoided if possible and only used when absolutely necessary.

Water is not necessarily sea water, it is also present in lakes and ponds and in mgv7 rivers, so is therefore generic.

**Comment by Wuzzy2** [comment]
>> And obviously, nobody should literally write group:anything into user-directed documentation.

> Yes they should, that would be the clear and precise langauge to use, groups are part of the game so need to be mentioned.

I am not saying groups should not be mentioned at all. My point is, user documentation should look like proper English and not like a programming language. In my mods, I just refer groups by their internal (and sadly, only) name for now (without the `group:` prefix). It's still not perfect IMO but it's better than nothing. But this is off topic, sorry.

> Aliases should be avoided if possible and only used when absolutely necessary.

Agreed. I do not want to change any itemstring, I just want to change the user-visible names. The itemstrings should not change; those are important identifiers.

> I actually don't know of any mod that would need the definition of a node that's not_in_creative_inventory. (BTW, that description itself should probably have a shorter alias, and the longer name be depreciated.) If you know of one, link me to it.

`doc_items`, `doc_minetest_game`.

OK, I see that changing most of the names now is probably too disruptive (sadly) since many mods build on assumptions now. Sigh.

I hope at least my suggestion “Tree” → “Tree Trunk” is uncontroversial.

(BTW: Why Do Item Names Have To Start With A Capital Letter In Each Word?)

**Comment by garywhite207** [comment]
Too many changes would need to be made...I found that out the hard way. 
-1

**Comment by paramat** [comment]
Tree to trunk is a good idea of course but has the same problems of disruption, i'd rather keep it unchanged to avoid aliases.

**Comment by Wuzzy2** [comment]
Nobody said we have to use aliases. Just change the `description` while keeping itemstrings intact.

**Comment by C1ffisme** [comment]
@Wuzzy2 Agreed. There's no use trying to keep descriptions similar to itemstrings, since some are already bad enough.

E.G:
item name: tool_pick_bronze
description: Bronze Pickaxe

**Comment by paramat** [comment]
Sure we can change the descriptions to 'tree trunk', sorry, you weren't clear on that.

**Comment by DS-Minetest** [comment]
but the descriptions shouldnt differ too much from the item name, it would confuse

**Comment by paramat** [comment]
Now that we're talking about descriptions, some of the other suggestions migh tbe okay: Golden Sand, Grey Stone, Cotton Fibre, (Blue Water?). Then these still have multiple uses and remain generic, but have a more unique description.

**Comment by C1ffisme** [comment]
@paramat 
![default_sand](https://cloud.githubusercontent.com/assets/9893266/21575869/4c3a7b3c-cee2-11e6-8906-9a29cb4a1d66.png)

It honestly doesn't look very 'gold'.

I'd say silver sand should go with silver stone, but then everyday stone would be confused with some kind of silver ore.

**Comment by DS-Minetest** [comment]
> Blue Water

lol, isnt it only blue so that you see that there is water and not air? there is no dye in it, right?

how about beach sand? it is only generated at beaches in v5 and v6
or call it describing the consistence? desert sand has more round sand grains

**Comment by paramat** [comment]
Sand is found in sandstone desert too as the surface node.

**Comment by DS-Minetest** [comment]
not v5 and v6 but the name should describe the appearance of sand in all mapgens, its difficult

**Comment by paramat** [comment]
Mgv5 has the same biomes as all other non-mgv6 mapgens.

**Comment by DS-Minetest** [comment]
ok, but mgv6 had no sandstone deserts

**Comment by paramat** [comment]
Correct.

**Comment by paramat** [comment]
I would be fine with fairly generic but more descriptive descriptions.

> Sand: Rename to one of these (pick your favourite): “beach sand”, “yellow sand”, “golden sand” (an allusion to the silver sand)

This sand is in sandstone deserts so not 'beach sand', the other 2 are ok.

> Stone: Gneiss, granite, gray stone, graystone, common stone, plain stone, true stone

No specific stone type, 'grey stone' is descriptive, the last 3 not descriptive enough.

> Water: Ocean water, sea water (as opposed to river water)

Nope, as we are avoiding forcing 'water' to be sea / salt water, just 'water' seems ok.

> Sapling, Wooden Planks, Tree, Leaves, Wooden Fence, Wooden Fence Gate.: These are the worst offenders. It drowns the game in generic words for a specific tree species. We should start to actually give the awfully generic “tree” (the ACTUAL tree, not the node (`default:tree`)!) a proper species name. I don't really have an idea. “Apple tree” maybe, because of the apples?

'apple tree' is ok with me.

> Rename “Tree” (the node) and all other trunk nodes to “tree trunk”. Clearly the single block is not a tree itself, so the name ”Tree” is just plain wrong.

Fine for me.

> Rename “Cotton” (`farming:string`) to “string” or “cotton string”. Why was this named “cotton” anyways? Even if this is correct English, this is very confusing as the plant is also called like this

There's another issue about sorting out the cotton mess, maybe leave the redescription to that issue. I suggest calling this 'cotton fibre' and crafting it into 'string'.

> While we're at it, assign the cotton plant and wheat plant the description “cotton plant” and “wheat plant”, respectively. Yes, the player is not supposed to get those, but some mods want to parse the node definition

Fine for me.

> Bush Leaves, Bush Stem: No idea, but since we also have acacia bushes, the “generic” bush name should be changed

Nope i deliberately chose a generic bush as explained above.

**Comment by Wuzzy2** [comment]
Good reply.
I suggested “beach sand” before the normal sand became actually part of a new desert biome. Now this suggestion does not make sense anymore, of course.

**Comment by Wuzzy2** [comment]
May I summarize?:

* Cotton Plant
* Wheat Plant
* `farming:string`: String
* “Tree” → “Apple Tree Trunk”
* “Sapling” → “Apple Tree Sapling”
* “* Tree” → “* Tree Trunk”
* “Stone” → “Grey Stone” or “Gray Stone” (I don't know if we use U.S. or British English)

**Comment by C1ffisme** [comment]
@Wuzzy2 

> “Grey Stone” or “Gray Stone” (I don't know if we use U.S. or British English)

Maybe we'll just compromise, how about Græy Stone?

Okay, all joking aside, it seems like "grey" is used in the wool mod.

**Comment by paramat** [comment]
Yes best to match the spelling of 'grey' to dyes and wool mods.

**Comment by paramat** [comment]
related #1817 and @Ezhh may be interested in considering these ideas.

**Comment by paramat** [comment]
This is mostly done now.
