### ISSUE TITLE
New growlamps needed

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1478]
Non-cubic mese growlamps have been requested so that meselamp doesn't have to be used when growing stuff underground.
I'm thinking a simple ground-only mese torch or narrow lamp (a simple nodebox).
The recipe can be generous to compensate for now needing mese lights to grow saplings underground.
I'm happy to work on this and keen to partially address the complaints about not being able to grow saplings in darkness, i would like to make mese growlamps easier to acquire.

**Comment by rubenwardy** [comment]
I suggest giving meselamps a node box to make them look nicer

I also suggest renaming them to sun lamps to make their use more obvious

**Comment by C1ffisme** [comment]
Rather than another mese-related lamp, I would prefer something more original. Save mese torches for mesecons.

Although, I don't want it to be an early game item, as I pointed out in #1476. Making it mid-to-late game means that vertical transportation or mobile inventories have more value in the game.

**Comment by DS-Minetest** [comment]
maybe make the lamp slowly consume mese as fuel to make it the use of it more temporary
or mese and normal fuel to keep the mese molten

or make a magnifier but this would be hard i think...

**Comment by paramat** [comment]
Rubenwardy, we need a full-cube lamp to build with, and it is being used as a full cube already, so we can't change it, but wecan add something new.

C1ffisme, apart from torches, fire and lava, which should not be able to grow plants, there is nothing else to use as a bright light source, mese is ideal.

**Comment by paramat** [comment]
Just saw that meselamps require 3 mese crystals, that's 3 mese ore nodes, too much, will change to 1 mese crystal per lamp.

**Comment by sofar** [comment]
How about a `lantern` that's made with e.g. sticks/wood, a torch, maybe a metal bar, some glass panes? The model should be a bit more complex so the textures don't look too dumb (can you specify multiple tiles for nodebox nodes?).

That should be a nice luxury node that looks good, needs a bit more material and crafting.

```
- s -
p t p
- w -
```
s - steel ingot
p - glass pane
t - torch
w - wood plank

I'd make a nice .obj file for something like this:

```
----------------
----------------
-------BB-------
-BBBBBBBBBBBBBB-
--p.....ss...p--
--p....ss....p--
--p...XXXX...p--
--p...XXXX...p--
--BBBBBBBBBBBB--
------SSSS------
------SSSS------
------SSSS------
------SSSS------
------SSSS------
------SSSS------
````

anyway, just throwing out an idea. Maybe this is too complex for `mtg`.

**Comment by paramat** [comment]
I was thinking of something similar, but simpler, and mese powered for this issue.
Mese because this is specifically a light for growing plants (level 14), so cannot be torch-based.

**Comment by Fixer-007** [comment]
>I suggest giving meselamps a node box to make them look nicer

or crappie underwater ;)

**Comment by DS-Minetest** [comment]
such a lantern would spray the light in every direction, so even through the top and the floor of the lantern where is inside the light source:
![lamp1](https://cloud.githubusercontent.com/assets/7613443/21578292/fd71ac02-cf7a-11e6-9733-05dda254cddd.png)

so i would suggest a lamp which has a dome out of glass:
![lamp2](https://cloud.githubusercontent.com/assets/7613443/21578297/1b411d12-cf7b-11e6-9324-5eebb3ad005c.png)

**Comment by C1ffisme** [comment]
@DS-Minetest So, like, a lightbulb? Makes sense to make it out of mese, I guess.

**Comment by Zeno-** [comment]
There would have to be a migration script (or code) that converts all existing torches to these torches if this is a suggested solution to growing and farming underground.

**Comment by NathanSalapat** [comment]
Why would a miner need to make that many of these torches, they can still use the normal torches for lighting their caves.

**Comment by Zeno-** [comment]
> Why would a miner need to make that many of these torches, they can still use the normal torches for lighting their caves.

When you're -10000 deep in a mine and have no way to get to the surface and back down (e.g. on a server without teleport) you need to grow forests so that you have a wood supply for more torches, ladders, more saplings, etc. It's not uncommon to need to grow a large forest at regular intervals in the deep world mines

**Comment by NathanSalapat** [comment]
99 torches that often seems like an awful lot of forests to be growing underground, but I guess everybody has their own playing styles.

**Comment by Zeno-** [comment]
Yeah it is a lot for one person. But in a team of say 6 on a server it's not *that* many

**Comment by Zeno-** [comment]
> That's not possible, we can't replace normal torches, and those are still needed for a low-cost method of lighting made from ores accessible at the surface..

Of course it's possible. I think you missed the word "existing". I.e. replace all the _existing_ torches (those currently in the database) with the mese lamps so that everything doesn't break. Then after that people can use normal torches as per normal.

Have you ever played a game where you mine very deep? Growing trees one at a time is not a viable option in my opinion.

Breaking all existing worlds is not an option (but I see you may have already done that with a previous commit).

**Comment by Zeno-** [comment]
> Plus, saplings requiring meselamps happened over a year ago so many players are already getting used to the new situation.

That should not have been merged. I think that because most devs are prohibited from contributing to minetest_game that it got merged due to oversight. If the PR that did that was more widely reviewed it would have been met with strong opposition. It might be the reason why no current servers seem to be boycotting the _game updates (but that's just conjecture on my part, I don't know the real reason).

Every single server I have visited in the last 2 days has underground forests or farms with normal torches. It is (was?) a big, big part of the game.

**Comment by paramat** [comment]
Changing all existing torches to meselights will cause a revolution, it will extremely unpopular, we wouldn't dare try it.
Growing trees underground will not be as hard as you think, especially once i make meselamps 3 times easier to craft.

> Breaking all existing worlds is not an option.

No worlds are broken, as i have said many times torches were never bright enough to grow plants, sapling requiring meselamps happened a year ago.

> I think that because most devs are prohibited from contributing to minetest_game that it got merged due to oversight

See https://github.com/minetest/minetest/pull/4873#issuecomment-269340876 i even opened an issue asking if it was reasonable. Eventually 3 weeks later 2 people complained so we made the 'can grow' function global, a simple mod can override it for those who want the old behaviour.
Now see IRC logs, even hmmmm realised there was little opposition and the change had support, so he said "if it was popular then so be it".

> It might be the reason why [no] current servers seem to be boycotting the _game updates

I assume you mean they are boycotting everything in MTGame since Oct 2015? I doubt they are, they can simply override the function.

I accept it was unpopular with some, but it was a bug that people got used to, and totally unreasonable to grow saplings in darkness when all other plants have always required something brighter than torchlight. Those who want the old behaviour can use a mod to override the function, or can add level 14 torches.

**Comment by Zeno-** [comment]
> No worlds are broken, as i have said many times **torches were never bright enough to grow plants**, sapling requiring meselamps happened a year ago.

That is NOT true. If they were never able to grow plants how come everybody was able to do it with... torches?

**Comment by paramat** [comment]
Check the code yourself.

**Comment by Zeno-** [comment]
oops, sorry paramat. I edited your comment by mistake. The reply is mine. Your text is unmodified. Change it back if you like and I will respond properly

**Comment by paramat** [comment]
Before Oct 2015 saplings grew in darkness, yes, but all other crops, flowers, and grass needed 13 at the node (so a neighbouring light of 14) to grow.

**Comment by paramat** [comment]
So back then, if saplings needed light to grow, they would have been given the same requirement as other plants, 13 (light source 14).

**Comment by paramat** [comment]
In which version? could you link the code? Growing grass on dirt isn't very critical though.

**Comment by paramat** [comment]
Note that a lack of a lighting check is different, it is not a positive action that chooses a necessary light level, a few things (saplings, cactus, papyrus) lacked light checks simply through neglect, laziness or just not thinking about it yet.

**Comment by DS-Minetest** [comment]
i dont remember in which versions it was but im sure it took light to grow, a torch gave enough

**Comment by paramat** [comment]
More generous meselamp recipe #1481

**Comment by Zeno-** [comment]
> Note that a lack of a lighting check is different, it is not a positive action that chooses a necessary light level, a few things (saplings, cactus, papyrus) lacked light checks simply through neglect, laziness or just not thinking about it yet, grass may have been the same.

And 13 for can_grow was chosen because.... ?? There doesn't appear to be a reason.

**Comment by DS-Minetest** [comment]
@Zeno- 13 was chosen because the plants should need sunlight, but the sunlight doesn't differ from other light. Sunlight is 14 and in a node next to a node with 14 is light level 13.

**Comment by Zeno-** [comment]
@DS-Minetest Ok I guess what I meant is, who decided that saplings need that much light to grow? I mean minetest has been out for, what, 6 years(?) and all throughout that time until the patch a year ago plants were able to grow without that much light. I think that something that has been part of the game for so long needs a bit more attention than someone just deciding that they need 13 light to grow.

**Comment by paramat** [comment]
> I mean minetest has been out for, what, over 6 years(?) and all throughout that time until the patch a year ago plants were able to grow without that much light.

Not true. I've explained this to you multiple times already, why hasn't the message got through?:

Throughout Minetest history plants have either required more light than a torch, or, have been missing lighting checks (saplings, cactus, papyrus) very probably due to MTGame neglect rather than a decision to allow plant growth in darkness.

Growing plants with a torch is the unusual and uncharacteristic behaviour, you are stating completely the opposite.

Now zeno, please explain to me why after explaining this to you about 4-5 times you still misunderstand? You are a talented and intelligent person so i am bemused.

**Comment by Zeno-** [comment]
paramat, I recall you once insisting that you would not fix floating blocks of land in the mapgen because they added to the charm and character of minetest. Other than being silly and floating they served no useful purpose. And yet here you are twisting words and saying that saplings have never been able to grow underground. Underground forests and farms add significantly to the "charm and character" of minetest _and_ they have a useful function. And yet you insist on basically destroying them and adding a hack to make them possible again. You're an eco-terrorist I think :p

**Comment by sofar** [comment]
I'm still in favor for a compromise: use longer nodetimers to grow any crop in low light conditions. Set the minimum at ~ 10, and scale the timer length so that at 14, it's 1.0x, at 13 it's 1.5x, at 12 it's 2.0x, at 11 it's 2.5x and at 10, it's 3.0x. 

These numbers are just an idea. 3x slower farming wouldn't be so bad for saplings (6 days for most trees to grow) at all, considering you need little resources and only create a large space for them).

This will unlock new and interesting underground uses while still encouraging players to farm in sunlight for efficiency.

**Comment by DS-Minetest** [comment]
> at 14, it's 1.0x

It would never reach 14 as long as it isn't a light source.

I would prefer an exponential increase of time per light level. Yes, linear would come in mind since the light level brightness is linear now, too. But we could say that plants grow with exponential speed depending on light.

**Comment by sofar** [comment]
The numbers are just an idea. Exponential is possible as well, but 6 days for a sapling is already really really long IMHO, and with an exponential curve it would likely be much more.

**Comment by paramat** [comment]
> And yet here you are twisting words and saying that saplings have never been able to grow underground

I have never said that. I'll say it for the 5-6th time: saplings could be grown in darkness because they had no light check.

> Underground forests and farms add significantly to the "charm and character" of minetest and they have a useful function. And yet you insist on basically destroying them

Again, for the 5-6th time i'll say it: saplings requiring meselamps was done over a year ago. Nothing i am doing currently makes it more dificult, this issue is about making underground farming easier and i have just made meselamp recipes more generous.

If you don't believe me check the code and commits yourself.

Zeno you are a talented and intelligent person, so why are you consistently misunderstanding or ignoring my multiple explanations? It's out of character and somewhat concerning.

**Comment by Zeno-** [comment]
@paramat This is your comment, and there are similar ones in other places:

>[...] torches were never bright enough to grow plants

Whether or not that was because of an omission in the code or whatever, it's NOT true. You are twisting words and history to your advantage. The ability to grow plants underground *was* possible. And many people relied on this "feature" (I don't care if the feature was due to a bug or an omission of a check... it became a feature)

**Comment by rubenwardy** [comment]
It seems by "plants" he means farming and flowers, not trees

**Comment by paramat** [comment]
> torches were never bright enough to grow plants

This can be misunderstood i admit, and i did mean saplings too here. What i mean is 'there was never a lighting check that was satisfied by torches'. The lack of a lighting check does not mean 'torches were bright enough for saplings' because there wasn't a positive choice of torches being bright enough, it was just neglect.

**Comment by paramat** [comment]
sofar i feel that's complex and not what is asked for. Those like zeno, hmmmm and others want to be able to grow plants by torchlight and have them grow just as fast.
So i suggest we add a setting to MTG 'required plant growth light level' set to 13 by default.

**Comment by sfan5** [comment]
> So i suggest we add a setting to MTG 'required plant growth light level' set to 13 by default.

No :-1: Putting quite important game elements into some settings is just lazy engineering and doesn't solve the problem at all.

**Comment by rubenwardy** [comment]
It's possible for mods to change it: https://github.com/rubenwardy/torches_grow_saplings

**Comment by paramat** [comment]
Yeah the can grow function is overridable, we did that on request in response to the few people who complained.

Sfan5 that's fine by me, i don't think we need a setting.
A small number of people are making a big fuss over this but it's not a big issue and doesn't need a complex compromise as sofar suggests.

**Comment by DS-Minetest** [comment]
Needing for every plant one lamp could be really annoying.
=> Using @sofar's suggestion (to let it grow more slowly with less light) not fully but only for 2 or 3 different light levels (13-12) could be useful so that you don't need so many lamps for the plants, especially for many small plants like farming stuff (one lamp per one big tree would be ok).

**Comment by paramat** [comment]
> Needing for every plant one lamp could be really annoying.

That's the way it's always been, apart from the plants with missing light checks.

**Comment by paramat** [comment]
sofar i don't feel we need a compromise as default, since this goes against how MTG has always been in requiring more than a torch. The compromise is better done as a setting, which is also much simpler.

**Comment by Zeno-** [comment]
@paramat Stop insisting that minetest has always required more than a torch. You're still twisting words. Hmmmm found proof in the source code last night that the design, before you changed it, was intentional.

```
18:58 	hmmmm 	https://github.com/minetest/minetest/bl​ob/stable-0.3/src/environment.cpp#L1095
18:58 		there's 0.3
18:59 		dunno how much farther back you want to go but
18:59 		sorry paramat, you're just wrong here, it's not a bug
```

**Comment by tenplus1** [comment]
@paramat - It may be true that most players are not game devs, but they do have valid opinions and points to be made about the gameplay.

**Comment by fermionic** [comment]
@Zeno- how does that code show that the design was intentional? I don't see it

**Comment by paramat** [comment]
> Hmmmm found proof in the source code last night that the design, before you changed it, was intentional

In MTv0.3, that was a very long time ago and pretty much a different game.

**Comment by paramat** [comment]
Zeno i'll respond to things you wrote on IRC:
> things are being merged now without regard for what coredevs think

We are mergng commits according to the rules and based on MTG dev agreement.

> we are not allowed to commit to minetest_game otherwise I'd just revert the silly commits

So you are suggesting you would like to revert MTG commits yourself with no agreement, that would get you kicked out of MT.

> paramat is still twisting words insisting that saplings have NEVER been able to be grown underground

I've explained clearly about 10 times now that i have never said that.

> But why don't our opinions count?

Your opinion does count, to me too, but you have no dev authority in MTG.

> even nore objected to 1476 and it was ignored until sofar said he agreed with hmmmm

I was very aware of that, a dev objection is no reason for the author to stop promoting a PR. At that point i had sofar's support so there was still a chance it may be eventually approved.

> but when something comes up that is very controversial we're basically ignored

I think we can agree i have not been ignoring you :) I have also been woring hard to address the concerns, and your concerns, i have made meselamps cheaper and am adding new light types.

> it is when nobody is happy :(

Slight exaggeration.

> (e.g. hmmmm is not a mtg dev so his opinion doesn't matter)

His opinion does matter, to me too, my comment was to state that he doesn't have dev authority in MTGame.

> I just think that we are not listened to

You are.

> basically breaking underground farms and forests is IMO a bad idea

The solution i propose will add a setting to get the old behaviour back. I want to keep you happy.

> if it was a config option, though, nobody could complain
18:45 		I wouldn't
18:45 		it would not break older worlds for a start

That's what i'm suggesting.

**Comment by paramat** [comment]
More:
> Also, I don't think it's right to ignore the poll just because the results might not be want you want

I'm not, i'll ignore it if 1 is chosen too.

> also, your opinion as well as mine are basically to be ignored because we're just players

Never said that. I mean you don't have dev authority. Player's opinions count and MTGame devs listen to them.

> I really don't know what's going on. It's like he's a different person from a month ago

That's what i think of you, you have been quite unpleasant towards me for the last 2 weeks, it suddenly started after xmas. I have patiently argued with you without being unpleasant towards you, but my patience is wearing thin now.

> He seems to want to ignore everyone

I'm arguing with everyone, that's not ignoring. I'msimply taking issue with a poll where my suggested option is being refused inclusion.

**Comment by paramat** [comment]
Concerning the above, for 2 weeks you have been on IRC doing this, stating that i have been saying the most ridiculous and nasty things, it is very irritating, please stop. I have repeatedly posted in Github at great length to correct you, explain what i actually said, and explain the facts, but it doesn't seem to get through. I know MTGame far better than you do.

**Comment by Zeno-** [comment]
>    we are not allowed to commit to minetest_game otherwise I'd just revert the silly commits

> So you are suggesting you would like to revert MTG commits yourself with no agreement, that would get you kicked out of MT.

Umm, excuse me. Do not put words in my mouth. Read what I said again:

> we are not allowed to commit to minetest_game **otherwise** I'd just revert the silly commits

That's very different to what you seem to think I said :/

**Comment by rubenwardy** [comment]
That implies: 

> If I were allowed to commit to minetest_game (ie: was a MTG dev) I'd just revert the silly commits

Two dev approvals would be required for such a thing - you'd effectively be merging a PR as the commit is old

**Comment by Zeno-** [comment]
@rubenwardy correct. But for the sake of brevity I didn't see that it was necessary to explain in IRC the entire process of which we're all fully aware. Let's just say my comment was a truncated version of "we are not allowed to commit to minetest_game otherwise I'd review the rules, get another core dev to support, and just revert the silly commits"

@paramat I am sorry if I am coming across as aggressive towards you personally. That's unfortunate. However, I make no apology for being aggressive (I'd prefer passionate, though) about the issue. I will henceforth try and make my comments more directed towards the issue rather than referring to you.

**Comment by paramat** [comment]
@Zeno- thanks for your messages, much appreciated. I intend to stop arguing now. Sorry for getting wound up over this and being rather argumentative.

**Comment by paramat** [comment]
#1480 merged.
