### ISSUE TITLE
Increase TNT cost

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest_game#1482]
Currently TNT costs:

* 1x Coal
* 1x Gravel
* 4x Wood

@paramat 

Spawned from https://github.com/minetest/minetest_game/pull/1474#issuecomment-269530835

**Comment by tobyplowy** [comment]
@rubenwardy +1 totally agree!

**Comment by DS-Minetest** [comment]
Maybe make the normal recipe, which is now for TNT, make little TNT, which has a radius of 0, then craft some of these together to one real TNT? The small TNT should have a little nodebox. It would be useful to make damage to players without destroying everything.

**Comment by rubenwardy** [comment]
> little TNT

It could be a TNT stick, and you then use multiple sticks to make a bomb

**Comment by DS-Minetest** [comment]
Maybe add to craft recipe string?

**Comment by DS-Minetest** [comment]
So, let every TNT stick cost 3 gunpowder (and 1 cotton string), and replace at the current TNT recipe the gunpowder with the TNT sticks. => increase threefold the costs
idea for TNT stick:
p=paper
g=gunpowder
```
pgp
pgp
pgp
```
Then replace at current TNT recipe the wood with cotton?

**Comment by paramat** [comment]
I agree TNT needs to be more expensive. Please move TNT stick to a new issue (although i don't see a need, the TNT API allows defining low-power TNT already).

**Comment by rubenwardy** [comment]
I was suggesting tnt stick as a craft item, rather than an explosive item

**Comment by sofar** [comment]
I don't think we need more items, that seems like a mod thing. So I'm not in favor of adding a 'tnt stick'.

**Comment by C1ffisme** [comment]
@sofar @rubenwardy Instead of the TNT stick being a node, what if you could throw it? (To balance it, it wouldn't destroy nodes, but it would harm entities.)

@DS-Minetest I don't think cotton should be required for TNT, that seems a little overboard, considering cotton already requires that you find a jungle biome, which (depending on your world and mapgen type) may not be the easiest biome to find.

**Comment by sofar** [comment]
@C1ffisme `minetest_game` has no entities, so adding a stick that can be thrown to nothing would make no sense.

**Comment by DS-Minetest** [comment]
@sofar `minetest_game` has players which are entities.

**Comment by sofar** [comment]
Ha!, yes, they indeed are. Obviously PvP isn't high on my radar :)

**Comment by sofar** [comment]
Way too powerful IMHO to do that though, you could seriously spawnkill players if you gain flying privs and throw explosives at /spawn.

**Comment by C1ffisme** [comment]
@sofar PVP was my intention. Considering that we already have swords which also serve little purpose besides PVP, I thought that this could also fit in.

> Way too powerful IMHO to do that though, you could seriously spawnkill players if you gain flying privs and throw explosives at /spawn.

It wouldn't have to do that much damage, enough to be worth it, but definitely not insta-kill. And how did you gain flying privs if you were the kind of person who spawn-kills?

**Comment by paramat** [comment]
Please discuss TNT sticks in a new issue, although note the idea has 3 dev disapprovals.

**Comment by C1ffisme** [comment]
@paramat Currently working on a pull...

**Comment by numberZero** [comment]
> how did you gain flying privs if you were the kind of person who spawn-kills?

Well, some servers have no anti-cheat... :blush: But I never spawn-kill =)
Anyway, I’m for the TNT sticks, but not as throwable items. Throwing should be kept in a complete mod, either in MT_game or outside it. They should be either mere craftitems (just like the paper itself), or small explosives e.g. with radius of 1 (obsidian mining?), maybe falling.

**Comment by C1ffisme** [comment]
> They should be either mere craftitems (just like the paper itself)

As I've explained in another issue, I do have some issues with items purely dedicated to crafting, or worse, purely dedicated to only one crafting recipe.

**Comment by paramat** [comment]
Gunpowder has become less expensive, and TNT takes more gunpowder, so cost is the same.
How about a TNT stick craftitem that requires multiple gunpowder, then TNT is crafted from 9 sticks? The sticks only being a step in crafting, not individually usable.

**Comment by C1ffisme** [comment]
*Mumbles something about adding sulfur and saltpeter to the game.*

@paramat 
> How about a TNT stick craftitem that requires multiple (3?) gunpowder, then TNT is crafted from 9 sticks? The sticks only being a step in crafting, not individually usable.

Is there a use for the TNT sticks besides TNT itself? If there isn't, then it doesn't need to exist.

All one-use item types should be frowned upon.

**Comment by paramat** [comment]
Yes good point, another way to make it more expensive would be better.

**Comment by DS-Minetest** [comment]
Mods could perhaps override the TNT stick and so eg. make it throwable.

**Comment by paramat** [comment]
3 devs already disapprove of a TNT stick, as stated above.

**Comment by Ferk** [comment]
In addition to x3 the gunpowder, what about adding clay to the mix?
It's a sorbent for some explosives, like dynamite. And requiring access to clay will make it a bit more elaborate gathering the components for tnt.

**Comment by C1ffisme** [comment]
@Ferk I dunno about that. Considering we're already making TNT out of gunpowder, which are two different kinds of explosives, I don't think we need to add a third explosive into the mix to confuse things.

**Comment by Ferk** [comment]
@C1ffisme nitrate is not, on its own, an explosive.

**Comment by C1ffisme** [comment]
@Ferk Mostly I'm concerned because very few people will know that clay is a sorbent for an explosive. If I saw clay in a recipe for an explosive before you told me about it, I would have thought it was a typo or a joke.

**Comment by paramat** [comment]
There is some support for crafting TNT stick items into a TNT node. The TNT texture is a bundle of 16 red TNT sticks but 9 is better for crafting. 9 sticks in the texture won't divide well so we could leave the texture unchanged.
Then later a stick could, if desired, be made a low-power explosive.

**Comment by paramat** [comment]
#2128 merged.
