### ISSUE TITLE
Add a "disable_locking" minetest.conf setting for disabling crafting of locked stuff

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest_game#149]
Would be nice for "chaos" PvP servers. Adding a minetest.conf setting (which is perfectly possible) would make it easier to enable or disable the ability to craft locked stuff.

**Comment by C1ffisme** [comment]
This can be done in a pull request. There is an "enable_tnt" setting, so I imagine it must be possible to make custom settings.

**Comment by MT-Modder** [comment]
@C1ffisme yes it's probably one of the easiest things to do. Really the only hard part to it is get everyone to agree :smiley:.

**Comment by C1ffisme** [comment]
Getting people to agree, yes, it will be hard, but we can still talk and agree in a pull request, and issues _are_ for bugs and crashes. I just want to close lots of issues.

**Comment by C1ffisme** [comment]
ACTUALLY.... This can be closed. Just focus attention to the pull above.

**Comment by MT-Modder** [comment]
Yeah this can be closed considering it's over two years old and there is a pull. I wish I was a contributor, but I don't think I'm known (trusted) enough in the community, yet.

**Comment by C1ffisme** [comment]
Ah... I wish we were able to say, vote for it's removal.

**Comment by MT-Modder** [comment]
You can do that on IRC.

**Comment by C1ffisme** [comment]
I could, but I mean some official, github based way of pressing a button to vote.

**Comment by MT-Modder** [comment]
Yeah that would be helpful.

**Comment by C1ffisme** [comment]
Well then, I :+1: the removal of this issue.

**Comment by C1ffisme** [comment]
Hey @nerzhul , can you please close this now that there is a pull request? I chose you because I knew you were pretty active in the github community.

**Comment by paramat** [comment]
Issues are not closed until the PR is merged, re-opening.

> Would be nice for "chaos" PvP servers

Why is it useful?

**Comment by paramat** [comment]
And .. closing again as no core dev support for 6 years.
