### ISSUE TITLE
Some dyes are unobtainable

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest_game#1491]
cc @tenplus1

**Comment by tenplus1** [comment]
Flowers give red, orange, yellow, blue, violet and white only... plus Coal lumps make black, leaving the rest of the dye's available from mixing these 7 colours together in some very strange recipe's...  I feel we need to simplify the dye mod and make it easier to craft the missing colours.

**Comment by paramat** [comment]
What is unobtainable? Surely all dyes are obtainable even if they are second-generation mixes?

**Comment by sofar** [comment]
#1496 has some relevant discussion.

cyan, magenta and yellow and black/white are the primaries you need for all mixing.

cyan can be crafted through mixing green (blue+yellow) and violet (directly)
magenta can be crafted through mixing violet (directly) and red (directly)

I can make my way from there to dark_green, dark_grey, grey, etc. just fine.

**Comment by rubenwardy** [comment]
The report they gave was that you can't obtain them at all - it's fine if you need to mix them

**Comment by paramat** [comment]
Yes this issue title is wrong, it's more a request for new dye crafting.
