### ISSUE TITLE
The plant growth poll is biased and invalid

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1497]
The author of the poll https://forum.minetest.net/viewtopic.php?f=3&t=16332 is refusing an option i have requested for ridiculous technical reasons, although an option has been added on request for another dev.
As obviously one of the primary people involved in this discussion i should be allowed to have an option added of my choosing and worded how i want.
The analogy is a dictatorship that holds a fake democratic election by choosing who is allowed to stand.

The poll is therefore biased and invalid and i will ignore the result, and ask other MTG devs to do the same.
The bias is obviously not intentional, just a mistake by the author who is an excellent dev.
Please do not take part. The polls here and on the forum should be scrapped. I hope you will see the problem and raise your concerns about the poll.
Even if my requested option is included, there is the problem of those who have already voted not returning to see the new options.
If we must have a poll it needs to re-run with more options included.

Mostly though i encourage devs to realise that polls are not very useful as they only represent those who saw the thread and were bothered to vote. They present a narrow range of options when all options should be considered, a discussion thread is much more constructive and less hassle. Devs are devs because they are the ones trusted to take the final decision, even though they will of course listen to the discussion and take into account the wishes of players. We of course would not be bound by a poll result anyway, development by democracy would be a disaster.

**Comment by paramat** [comment]
All options in this poll are unsuitable as a solution.

Those (in the minority) who want the old sapling behaviour want to grow saplings, cactus and papyrus by torchlight and have them grow at normal speed.
For consistency all other plants should have the same light requirement.
The current behaviour, which has been the behaviour or intended behaviour throughout MTG's history should be preserved as the default.
None of the options do all of this.
My suggested compromise (which is being refused inclusion in this poll, making the poll invalid) is to have a simple setting 'plant_growth_light_level' set to 13 (current behaviour) by default, which applies to all plants. This keeps everyone happy while also being very simple.

**Comment by C1ffisme** [comment]
And this is why Minetest Game never moves forward, because we put so much emphasis and drama on something as small as whether or not a sapling grows underground.

This isn't even that big of a balance issue, considering my usual mining trips only take about as long as my torches (The only thing that requires wood that you would need underground) last. You can even play the game in complete darkness if you're skilled enough, and there are also light sources that don't require wood. (Such as lava, or mese lamps.)

Can we please stop arguing over the smallest features of the game?

**Comment by sfan5** [comment]
what is this bullshit

discuss this in #1493

**Comment by paramat** [comment]
One dev closing this is unreasonable, but i don't mind so much now, so it can stay closed.

**Comment by paramat** [comment]
I was going to copy-paste this into #1493 but with discussion i am feeling a bit happier now.
