### ISSUE TITLE
All 3 sands craft to sandstone, sandstone crafts to 1 sand type

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1498]
```
minetest.register_craft({
	output = 'default:sandstone',
	recipe = {
		{'group:sand', 'group:sand'},
		{'group:sand', 'group:sand'},
	}
})

minetest.register_craft({
	output = 'default:sand 4',
	recipe = {
		{'default:sandstone'},
	}
})
```
Therefore sand can be converted into another sand and silver sand creates yellow sandstone.
I suggest sandstone is linked exclusively to default:sand as it's the correct colour.
I'll make a PR.

**Comment by Fixer-007** [comment]
>Therefore sand can be converted into another sand and silver sand creates yellow sandstone.
You mean, you can take silver sand - and make yellow sandstone from it, and than simple sand from this sandstone?

**Comment by paramat** [comment]
Yes.

**Comment by tenplus1** [comment]
Which makes it better to include this change: https://github.com/minetest/minetest_game/issues/1477

**Comment by paramat** [comment]
Natural stones tend to be added when needed in mapgen, so new sandstones are unlikely to be added.

**Comment by paramat** [comment]
PR #1504

**Comment by paramat** [comment]
#1504 merged.
