### ISSUE TITLE
Add suffocation (in sand or gravel)

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest_game#1501]
The player doesn't get damage when buried by sand or gravel. He just stuck.

Should be default in MTG

**Comment by rubenwardy** [comment]
#473

**Comment by rubenwardy** [comment]
Situations may have changed since

**Comment by MT-Modder** [comment]
I highly doubt @PilzAdam @sfan5 or @paramat have changed their view on the noclip issue.

**Comment by MarkuBu** [comment]
What has a noclip issue to do with damage?

**Comment by MT-Modder** [comment]
Sorry I assumed you meant you wanted to add drowning as well. If the player is just stuck I don't think there would be a noclip issue. But of course without noclip how would you get unstuck?

**Comment by MarkuBu** [comment]
I'm not sure wat you mean. An example: I dig a node above my head. Above that node is sand. This sand falls down, I stand inside the sand, I just see black (noclip disabled) and I can dig the sand. But I don't get damage as long as I am inside the sand

Another issue is, that I just can walk out of the sand

**Comment by MT-Modder** [comment]
lol Yeah I spaced that one. If I remember correctly there's two ways to do that. One way is by checking player position every global step which is server heavy but you can't move at all while in the node. The other way is by making these nodes liquids and adding viscosity to them, you'll be able to move but extremely slowly.

So basically suffocation would never happen.

**Comment by Fixer-007** [comment]
>noclip issue.

Why it is so big of a problem? If user has noclip priv (usually it is admin) - than no suffocation for him. Problem solved. %)

**Comment by paramat** [comment]
See https://github.com/minetest/minetest_game/pull/691#issuecomment-145213406 for explanation of the problems.

**Comment by MarkuBu** [comment]
Ignoring some (for me) important gameplay elements just because of some flying admins? Seriously?

Minetest should be a game for players. They are playing normally without noclip. 

Sorry guys, but this becomes ridiculous

**Comment by paramat** [comment]
No need to close this, there may be things we can do in the engine to make it practical.
