### ISSUE TITLE
Add 'group:color_green' to grasses to allow crafting of green dye

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1503]
Grasses are found where flowers are, in several common biomes, so are ideal for a source of green dye.
This would complete the directly craftable colours: red orange yellow green blue violet. Green would no longer have to be a mix of other dyes, allowing the dye mod to be simpler.
I'll make a PR.

**Comment by sofar** [comment]
I'm not a fan - imho dyes can remain hard to obtain and require more mixing to get all the colors.

**Comment by C1ffisme** [comment]
Why not require a bit of travel for the "luxury" (Depending on whether or not you need it for your builds) of dye?

**Comment by paramat** [comment]
This request makes good sense. Currently all the basic colours of the spectrum are directly craftalbe, except green which is a fundamental colour. I'm very often aware of how green is missing from the sequence provided by flowers: red orange yellow .. blue violet. Adding green would make this a consistent and complete system. There are many other dye colours that still require mixing.

**Comment by C1ffisme** [comment]
@paramat I suppose that makes sense, although it does make cactus semi-redundant. (Maybe late game, if you mined all nearby grass, but there currently isn't a lot of demand for dyes besides wool.)

**Comment by paramat** [comment]
I was thinking of MC, cactus doesn't craft to green dye. With the extra biomes the desert type that contains cacti is rarer now, and cacti rare within that biome, so it is not a good source for green dye.

**Comment by paramat** [comment]
PR #1505

**Comment by tenplus1** [comment]
Cooking cactus to give 2x dark_green dye would be more of a challenge and give more uses for cactus.

**Comment by C1ffisme** [comment]
@paramat Wait, cactus doesn't smelt or craft into green dye? I should really start paying more attention...

**Comment by paramat** [comment]
I agree with sofar now, grasses are too common, i have a better idea.
