### ISSUE TITLE
Farming: Log it when you plant a crop ?

### ISSUE THREAD

**Issue by mgl512** [minetest/minetest_game#1508]
If you dig a crop, there's a log. If you plant it, there's not. I believe there used to be but I'm not sure.

**Comment by paramat** [comment]
Confirmed, because seeds override 'on place'.

**Comment by paramat** [comment]
Should be an easy fix to add a log of seed placement, anyone feel like making a PR?

**Comment by Ezhh** [comment]
Yes - while certainly not a big priority, it should be logged if there's an easy way to do it.
