### ISSUE TITLE
Fire should be affected by explosions

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest_game#1510]
Perhaps a minor issue, but it seems strange that explosions can cause fire (on nearby trees), but further explosions will not extinguish the fire. Not only is that unnatural, it means exploding TNT in fire has not effect at all.

Looking at the code in mods->fire->init.lua that seems to be on purpose.
Removing:
```
       on_blast = function() -- Unaffected by explosions
       end,
```
Fixes the issues. So why is it there? Happy to send a trivial pull request if folks agree. Otherwise we can just close this.

**Comment by sofar** [comment]
What do you propose? Something like `if intensity > 0.5 then remove_fire_node end` ?

**Comment by lhofhansl** [comment]
I just removed the on_blast callback. That has the desired effect (IMHO). Fire nodes are blown away, just like all other nodes.

**Comment by sfan5** [comment]
Why is that unnatural? If you blow something up it doesn't stop burning

**Comment by sofar** [comment]
Explosions can extinguish fires. I don't think we should extinguish fires with a low intensity, though - let some fire nodes remain.

**Comment by Fixer-007** [comment]
Actually I think IRL there are some cases where explosives are used to treat fires (like gas fires or other)

**Comment by lhofhansl** [comment]
I found that once (say) a tree is on fire, further explosions have absolutely no effect on it.

When removing said lines from the code it behaves as expected: An explosion ignites flamable nodes around it; an explosion also extinguishes fires in it's vicinity, but not as far as the initial ignition went. That seems quite natural to me.

Perhaps you guys can try it out and see what you think...?

**Comment by paramat** [comment]
Not keen this. If the first explosion ignites fires a second one should also. Surely the second explosion would then be igniting and extinguishing at the same time?

**Comment by paramat** [comment]
Seems good. Since an explosion removes nodes in the blast radius it should remove the flames too, otherwise you get flames hanging in air without the flammable nodes that are their fuel source.

**Comment by lhofhansl** [comment]
Exactly that. I think the ignition (turning flamable things into flame) is controlled by the damage radius and destruction is controlled by the tnt radius (which is usually smaller). But I need to double check.

**Comment by lhofhansl** [comment]
Well... Not quite. If you set off an explosion close to a tree, the tree would be on fire as before.
The tree is already on fire and you set off an exploring again, it would now within the blast radius extinguish the flames, which seems natural enough. Without changing this the explosion has no effect whatsoever on already existing flames - in real life folks use explosives to extinguish fires in oil wells for example :)

(It's not super important, just something I noticed as strange).

**Comment by paramat** [comment]
#1511 merged
