### ISSUE TITLE
player on farthest edge of node can't jump

### ISSUE THREAD

**Issue by Napiophelios** [minetest/minetest_game#1516]
I don't know if anyone has ever noticed, but when you move to the farthest edge of a node,
I mean the very farthest edge before you fall, jump seems to be disabled.
Is this on purpose?

**Comment by Fixer-007** [comment]
It is known bug. There is even PR proposed to fix this problem https://github.com/minetest/minetest/pull/3810

**Comment by rubenwardy** [comment]
This is a minetest/minetest issue
