### ISSUE TITLE
Idea for improving "creative" mod

### ISSUE THREAD

**Issue by WSDguy2014** [minetest/minetest_game#1519]
I would like to add a feature in creative menu: giving for example bread by middle-click mouse button to get 10 per middle-click, quicker than 1 item per left-click/right-click.

**Comment by sofar** [comment]
This would be an engine feature, refile against `minetest`?

**Comment by WSDguy2014** [comment]
@sofar Sure, do it the best...

**Comment by rubenwardy** [comment]
Creative should be a subgame setting, imo

I may make a PR to allow subgames to put checkboxes on the main menu

**Comment by sofar** [comment]
@rubenwardy this isn't a feature request discussing "creative" mode. He just wants middle click to pick up 10 items from an itemstack.

@WSDguy2014 please close this and open an issue against `minetest` instead.

**Comment by rubenwardy** [comment]
My point is that it should be a subgame thing, rather than an engine thing. The subgame currently does infinite digging and creative inventory

**Comment by sofar** [comment]
@rubenwardy my point is that the entine is incapable of providing a middle click handler to manipulate itemstacks, irregardless of your grievances with unrelated subgame settings.

Middle click in survival to pick up 10 items from an itemstack has nothing to do with creative and could very well be a survival thing too.

Yes, the OP said he wanted this feature for "creative" but I think that was a mistake, he obviously likes to pick up 10 items at a time, and if "creative" supports that, there is no reason why "survival" shouldn't support the feature either.

**Comment by WSDguy2014** [comment]
Opened issue on Minetest Engine again. https://github.com/minetest/minetest/issues/5058
Due in Minetest Engine issue sfan5 removed additional feature idea texts and issue title in https://github.com/minetest/minetest/issues/5051
