### ISSUE TITLE
Bug in App

### ISSUE THREAD

**Issue by Lukas7240** [minetest/minetest_game#1523]
![screenshot_2017-01-22-23-25-17](https://cloud.githubusercontent.com/assets/25287184/22186804/1d6bf340-e0fc-11e6-9226-30704b338b7f.png)
I don't really think that that's supposed to happen!
General info: Samsung Galaxy Note 3, Android 5.0, App version 0.4.14.15
Note: Happens instantly and always after loading (starting the App)

**Comment by Wayward1** [comment]
Most likely an engine issue, so probably belongs in https://github.com/minetest/minetest/issues
