### ISSUE TITLE
"Clear Crafting Field" button

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest_game#1524]
Sometimes the crafting field is full of items and you have to pick each one to move it in the inventory.

I suggest a button, that cleans the crafting field and moves all items to the inventory

**Comment by paramat** [comment]
I don't feel this is needed enough.

**Comment by DS-Minetest** [comment]
You can already use the listring (shift+leftclick).

**Comment by MarkuBu** [comment]
Still have to click on each item

**Comment by DS-Minetest** [comment]
Maximal 9 clicks are ok for me. How often is your crafting field full?!

**Comment by GreenXenith** [comment]
Dunno bout you, but I can hold shift and rapid click back and forth 9 times no prob. DS-Minetest also has a point. If I ever have something in my crafting grid, it is usually to craft into something.

**Comment by MarkuBu** [comment]
Maybe we have different preferences or most of the players play in creative mode. 

I am annoyed if I craft something like a few blocks or whatever and some items are left in the crafting field because I don't have enough and I have to clear the crafting field manually. Even Minecraft has a solution for this. If you close the crafting form each item drops and they are picked up automatically.

**Comment by DS-Minetest** [comment]
Handy players would need this maybe but Minetest is a pc game and on pc I never had problems with making the crafting field empty.
Also if we had a clear graft grid button or something like that people would also want other buttons for other things, like making chest empty. => Minetest would be crowded with buttons everywhere.
