### ISSUE TITLE
Lava cooling issue?

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest_game#1525]
It seems that there is something wrong with the lava cooling. I watched lava while flowing over a river water source. But instead of clearing the water source the lava builds some kind of igloo around the water source.

Is that the desired behavior?

![screenshot_20170124_183731](https://cloud.githubusercontent.com/assets/16163058/22259222/c2e02562-e264-11e6-8cd8-180d6354865b.png)

**Comment by MT-Modder** [comment]
Yes this is normal.

**Comment by MarkuBu** [comment]
Ok, than I close this again
