### ISSUE TITLE
Bush leaves don't decay when removing the stem

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest_game#1531]
If I remove the stem of a bush the leaves don't decay. I don't know if that is by intention or an issue.

**Comment by tenplus1** [comment]
Bush leaves I think were meant as decoration for players to use so won't decay.

**Comment by paramat** [comment]
Yeah it was sort of intended but i'm not sure now, watching videos where players leave a mess or assume they decay. Placed leaves could have their param2 changed to prevent decay just like tree leaves.

**Comment by MarkuBu** [comment]
That's what I would expect. Same behaviour as normal leaves. Decay if stem is removed, don't decay if placed manually

**Comment by paramat** [comment]
Yes i'll make a PR.

**Comment by paramat** [comment]
PR #1532

**Comment by paramat** [comment]
We have a new leafdecay system so i thnk we can add bush decay now. I've seen players assume decay and leave a mess in the landscape.
@sofar @sfan5 @Ekdohibs @rubenwardy your opinions on this? any objections?

**Comment by paramat** [comment]
New PR #1612

**Comment by paramat** [comment]
~1612 merged.
