### ISSUE TITLE
Add steel railings

### ISSUE THREAD

**Issue by octacian** [minetest/minetest_game#1536]
Minetest has steel ladders and signs. Why not steel fences?

I attempted to make a texture so as to submit a PR, but it turned out a bit too "woody."

**Comment by octacian** [comment]
NVM, MT already has steel fences. Sorry.

I must be blind :rotfl:

**Comment by sofar** [comment]
There are no steel fences. There are bars, is that what you found?

**Comment by octacian** [comment]
Oh, NVM. That was from gloopblocks.

Double blind. Reopening.

**Comment by sofar** [comment]
I'm not actually for adding these :)

We don't have stone fences either. We omit a large number of block shapes and material combinations as well.

**Comment by octacian** [comment]
Speaking of other material combinations, barbed wire would also be really nice.

I'll make a second attempt at a texture.

**Comment by paramat** [comment]
I think the shape of fences is not suitable for steel fences, too high-volume and traditionally shaped :-1:

**Comment by Fixer-007** [comment]
There are steel bars available, that look quite good

**Comment by C1ffisme** [comment]
What about different shapes of wall-block for different tiers that represent technological progression?

Wood is turned into fences, which fit almost any civilized period.

Stone is turned into stronger, more medieval stone walls.

Steel/Bronze is turned into iron bars, or barbed wire to fit a modern era.

Diamond is turned into... (Nothing yet, though something futuristic would look cool.)

That would be a bit more original than just using the same shape used for fences and slapping a random texture on it.

**Comment by DS-Minetest** [comment]
Adding metal fences can be done by mods **but** if there would be metal fences in default, metal sticks would be needed. If these metal sticks would be added by default then there would be more craftitems. It's not good having so many mods adding an own steel rod.

**Comment by sorcerykid** [comment]
I'd strongly favour including chainlink fences (reference the army mod). I think they would be far more useful for general purpose builds, perhaps even moreso than the bars which really only look appropriate in high-security type structures.

https://forum.minetest.net/viewtopic.php?pid=116232

**Comment by cheapie** [comment]
homedecor adds a chainlink fence (as well as corner and gate pieces), which tend to be used rather extensively in urban areas. It uses spools of steel wire for crafting.

**Comment by C1ffisme** [comment]
Idea 2: If we ever implement mobs, higher tier fences/walls provide better amounts of security. (Not sure how, just leaving this out there for future reference.)

**Comment by tobyplowy** [comment]
@octacian I'd like to have steel fences maybe copper as well?

**Comment by paramat** [comment]
:-1: For steel fences using the existing fence models. @octacian is that what you are specifically requesting or would a new model be ok? Maybe you would like steel railings?

**Comment by octacian** [comment]
@paramat Initially I was thinking about something using the current fence models, as we already have steel bars. However, I suppose something with a new model could be OK too.

**Comment by paramat** [comment]
I think this is specialised enough to be a mod thing instead adding low priority content to MTG.

**Comment by octacian** [comment]
Yes, you're right. Looking back on this now, I completely agree. I do hope that somebody does make a mod to expand the variety of material options available for some nodes; fences and doors in particular.
