### ISSUE TITLE
Add "group:snow" to is_snow_nearby in trees.lua

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest_game#1537]
It is just an idea I had and maybe there is currently no use case for it, but I think it doesn't hurt and might be useful some time

replace "default:snow", "default:snowblock", "default:dirt_with_snow" with "group:snow" in the is_snow_nearby function in trees.lua and add the group "snow" to the nodes. 

This would make it possible for mods to add other snow nodes like snowy grass, a snowman or whatever

**Comment by paramat** [comment]
Yes good idea, because the biome API means it's likely the surface snow nodes will not be from default.

**Comment by paramat** [comment]
I think "group:snowy" is better, shorter and similar to choppy, snappy etc.

**Comment by MarkuBu** [comment]
I don't want to make a PR for this because I started a new, bigger project, sorry

**Comment by paramat** [comment]
No problem.

**Comment by paramat** [comment]
PR #1540

**Comment by paramat** [comment]
#1540 merged.
