### ISSUE TITLE
Remove inventory formspec from default/player.lua since sfinv is a part of the game

### ISSUE THREAD

**Issue by bell07** [minetest/minetest_game#1546]
please remove player:set_inventory_formspec(default.gui_survival_form) from default/player.lua since sfinv is a part of minetest_game.

By the way, please look for a way to proper replace the users inventory formspec. Currently even sfinv must uverride the "default" formspec using minetest.after(0.5..). The on_player_receive_fields is called twice.
Ok, sfinv does have sfinv.enabled that can be set to nil from other mods.

**Comment by rubenwardy** [comment]
>Currently even sfinv must uverride the "default" formspec using minetest.after(0.5..). The on_player_receive_fields is called twice.
Ok, sfinv does have sfinv.enabled that can be set to nil from other mods.

Oh! Does that mean without the code in default, the minetest.after isn't needed?

**Comment by bell07** [comment]
Yes. If you set the "creative" setting, the default code is disabled. In this case the minetest.after is not needed in sfinv.

**Comment by paramat** [comment]
#1738 merged.
