### ISSUE TITLE
[suggestion] Make obsidian glass `glasslike_framed`

### ISSUE THREAD

**Issue by numberZero** [minetest/minetest_game#1547]
`glasslike_framed_optional` is suitable for usual glass that has marks on its sides. But obsidian glass is clean, so it makes a substantial difference whether the frame is drawn: obsidian glass wall is virtually invisible without the frames. It’s great to have such virtually invisible node, but not a node that is visible for some people but not for others, depending on some loosely related setting.

**Comment by paramat** [comment]
I really like to have the possibility of a large area of glass being completely clear, it allows good views outside.
:-1:

**Comment by numberZero** [comment]
@paramat That’s what I meant, why -1 ?

**Comment by numberZero** [comment]
@paramat Fixed.

**Comment by paramat** [comment]
Oops sorry i have misunderstood,

**Comment by paramat** [comment]
Ok i understand now, i like to have the option, obsidian glass looks really good with frames around each node, This would also break player's builds if they want node frames. The invisibility dependent on setting issue is not important, if it's a problem a server admin can either redefine or use a different texture.
:-1:

**Comment by numberZero** [comment]
> This would also break player's builds if they want node frames.

@paramat these builds are broken already as only some players see the frames. Moreover, the builders may not even recognize that their buildings look extremely different for different players.

**Comment by paramat** [comment]
Yes, but at least the builds look the way the builder wants them to look according to their own setting. I would be very irritatted if all my builds with node-framed obsidian glass were suddenly forced to be frameless.
The issue you bring up is very minor and doesn't justify such a radical change.

**Comment by RHRhino** [comment]
This discussion is about allowing the glasslike obsidian node being drawn similar to the connected glass obsidian node, right? Is this a menu setting or is it a new predefined optional drawtype in the node definition or a node definition that forces connected glass? It's a bit confusing to follow about what you talk here. 🤔

**Comment by paramat** [comment]
No, the suggestion is to force obsidian glass to be connected glass always and ignore the setting.

**Comment by RHRhino** [comment]
okay I see.

**Comment by Fixer-007** [comment]
Yes, there is a setting available to connect the glass...

**Comment by numberZero** [comment]
@Fixer-007 I know there is an option (BTW, why is it off by default?), but the difference is too significant IMO to leave it on user preference. Just imagine how someone builds a glass wall thinking it’s transparent, while others see a grid. And others might build something seeing a nice borders on the outer faces while some see messy frames in hard-to-imagine parts of the building. Maybe there should be 2 nodes, one framed and one glasslike?
Note that that’s not a great problem for a plain glass as it is similarly noisy in both variants.

**Comment by paramat** [comment]
Yes 2 nodes would be the solution, but this would be rather excessive duplication for a very minor issue so i wouldn't agree to 2 nodes in MTGame. I don't even consider it a proble, player texture packs and settings already alter how everything looks per-player.

**Comment by paramat** [comment]
@sfan5 @Ekdohibs @sofar @rubenwardy @SmallJoker @ShadowNinja your opinions?

**Comment by paramat** [comment]
@rubenwardy any comments?
This is simply something that cannot be done. However, i'm ok with adding another obsidian glass node if other devs like the idea.

**Comment by paramat** [comment]
No support and no dev interest.

**Comment by numberZero** [comment]
This is the same place with different *client* settings. The difference is considerable, doesn’t it?
![screenshot_20171008_173925](https://user-images.githubusercontent.com/7352626/31317846-01e2a42c-ac51-11e7-87bf-1d30c7754e78.png)
![screenshot_20171008_173939](https://user-images.githubusercontent.com/7352626/31317847-0210faa2-ac51-11e7-9eed-68b73ea2287f.png)

**Comment by paramat** [comment]
What are we looking at here? it doesn't make sense, the glass is flat instead of cubic and the frame of connected glass is missing. Seems like a bug being used to make an argument.

**Comment by numberZero** [comment]
The frame is not missing, it is hidden under the walls

**Comment by paramat** [comment]
Ahh ok i see. rare situation though. if glass is clear then it's clear, invisibility is the whole dea for that glass type. Players will soon bump into it and realise. There's no issue. No one else has stated a problem with this so it's up to you to write a mod for yourself that overrides default obsidian glass.

**Comment by numberZero** [comment]
[Off-topic]
> Players will soon bump into it and realise.

@paramat Imagine that there are movestones... that shift that glass panel in and out... }:->
