### ISSUE TITLE
Waterlily/water flickers when viewed from below

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#1551]
If you place a waterlily on water, then dive into the water to view the water lily from below, you notice a Z-fighting issue between the waterlily texture and the water surface texture while you move.

Tested in 0.4.15.

**Comment by paramat** [comment]
Perhaps the texture on the underside of the waterlily nodebox z-fights with water. Not a big problem. We could perhaps raise the nodebox off the water surface slightly.

**Comment by tobyplowy** [comment]
@Wuzzy2 yes this is anoying

**Comment by DS-Minetest** [comment]
> raise the nodebox off the water surface slightly

Then the waterlily would float. The nodebox could also be lowered.

**Comment by paramat** [comment]
Yeah lowered might be better.

**Comment by sofar** [comment]
I'd rather have the waterlily just above the water, possibly floating, than submerged, as that would make it look blue and less colorful.

**Comment by paramat** [comment]
Well i understood the idea as having the nodebox top above the water and the nodebox base under the water, but i'm not sure this is possible as the nodebox would overlap the water below.

**Comment by sofar** [comment]
You can extend the nodebox below -0.5. I would set it just slightly above the water surface, though.

I wonder however if we shouldn't address this in the engine and lower the water surface of the top a slight bit, since this is just going to affect other nodes as well.

**Comment by paramat** [comment]
Nooo :] we can't lower water surface just for this minor issue, smooth lighting calculations as well as many other aspects of the game become much simpler and faster using full cubes. The solution is to adjust what ever few nodes are affected, only waterlilly by default.

Yes slightly raised seems fine to me.

**Comment by GreenXenith** [comment]
As I have no idea what the units of measurement are in Minetest (other than meters and pixels) this might not make any sense: Raising it by about .01 (for reference, I am using Blender's units) should fix the "Z-fight" and there would be no noticeable difference. A player would have to spend hours trying to swim/float at the right height to actually see a gap between water and the lily pad. But why would anyone do that? :P

**Comment by paramat** [comment]
```
	node_box = {
		type = "fixed",
		fixed = {-0.5, -0.5, -0.5, 0.5, -15 / 32, 0.5}
	},
```
The nodebox base could be raised by 1/64th node:
```
	node_box = {
		type = "fixed",
		fixed = {-0.5, -31 / 64, -0.5, 0.5, -15 / 32, 0.5}
	},
```
Anyone want to test and make a PR? Very simple.

**Comment by Wuzzy2** [comment]
This bugfix works.

**Comment by paramat** [comment]
#1560 merged.
