### ISSUE TITLE
Visual noise in mese_lamp, trapdoor, etc

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1565]
Trying out those new lamps, starting from some distance and beyond I get some render glitching on lamp edges, notice black vertical lines.
![r9a0lgj](https://cloud.githubusercontent.com/assets/16494741/22865251/be2f4990-f168-11e6-88ac-70bf17c924ab.png)

Something like this also happens to trapdoors on same image, but in different way.

Latest 0.4.15-dev, my graphic settings:
```
anisotropic_filter = true
bilinear_filter = false
enable_waving_leaves = true
enable_waving_plants = true
fsaa = 0
leaves_style = fancy
mip_map = true
node_highlighting = box
trilinear_filter = false
viewing_range = 240
fps_max = 85
tone_mapping = false
texture_path = 
enable_shaders = true
fog_start = 0.7
enable_bumpmapping = false
enable_parallax_occlusion = false
enable_waving_water = false
generate_normalmaps = false
smooth_lighting = true
minimap_shape_round = false 
```

**Comment by numberZero** [comment]
@Fixer-007 Certainly not a MTG problem. The lamp is nodebox, not mesh; the problem might lie in the way MT converts nodeboxes to meshes.

**Comment by paramat** [comment]
Might be mip-mapping, that causes visual bugs for me.

**Comment by Fixer-007** [comment]
Yeah, turning mipmap hides the problem.
