### ISSUE TITLE
Screwdriver does nothing when used on colorfacedir or colorwallmounted nodes

### ISSUE THREAD

**Issue by VanessaE** [minetest/minetest_game#1567]
Title says it all.

**Comment by juhdanad** [comment]
The screwdriver does not work for wallmounted nodes, either.

**Comment by DS-Minetest** [comment]
I assume, the problem begins here:
https://github.com/minetest/minetest_game/blob/master/mods/screwdriver/init.lua#L38

**Comment by LazyJ** [comment]
**Minetest Engine, 2017_02_16** [d0cd27e](https://github.com/minetest/minetest/tree/d0ce27edd8e9a30330c81a69ccca52b02056c286)
**MInetest Game, 2017_02_12** [89c4599](https://github.com/minetest/minetest_game/tree/89c45993acae89ee1bc68f42e510f5304f13ffa9)
**Dreambuilder, 2017_02_17**  [bc71eb9](https://github.com/VanessaE/dreambuilder_modpack/tree/bc71eb952f8a699180bb7f4c22449a07bb29c91e)

Confirmed.

I tested the default screwdriver on default wood planks in vanilla - the screwdriver works. Then I tested in vanilla with the Dreambuilder modpack installed and the default screwdriver and the Technic Sonic Screwdriver (from Dreambuilder) would not work on default wood planks nor the coloredwood planks.

**Comment by paramat** [comment]
#1584 merged.
