### ISSUE TITLE
Improve slab placing

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest_game#1568]
If a slab is attached to an existing slab the new slab should have the same orientation, even if the new slab has a different material. Currently only slabs of the same material are placed with the same orientation

![screenshot_20170214_152947](https://cloud.githubusercontent.com/assets/16163058/22933066/9ba919f6-f2ca-11e6-9634-94bdde91447d.jpg)
![screenshot_20170214_153053](https://cloud.githubusercontent.com/assets/16163058/22933069/9ed172ae-f2ca-11e6-8ba7-30a484649f24.jpg)

**Comment by MarkuBu** [comment]
As an addition I would prefer if wall mounted slabs are horizontal orientated instead of vertical and placed on the top or bottom position depending on the click position on the node

Most times I need horizontal slabs, even if they are mounted on a wall. And I need a screwdriver all the time to rotate them

**Comment by paramat** [comment]
For this issue perhaps check the nodename for containing 'slab'.

> Most times I need horizontal slabs, even if they are mounted on a wall.

I would agree with this.

**Comment by sofar** [comment]
Slab code is already worse than stairs in complexity.

I'd support slab-to-other-slab smartness, and that would solve your problem entirely, I think.

**Comment by MarkuBu** [comment]
Some improvement. I prefer horizontal placement of slabs, even if placed on a wall

https://youtu.be/Qkb3acMjCig

Now I have to deal with different slab types

**Comment by MarkuBu** [comment]
auto rotation works now also for different types of slabs

**Comment by paramat** [comment]
PR #1581

**Comment by paramat** [comment]
#1697 merged.
