### ISSUE TITLE
New forest floor in deciduous forests

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1570]
I suggest a new surface nodes for this biome, we already have 'dirt with rainforest litter' and 'dirt with coniferous litter'.

**Comment by C1ffisme** [comment]
So... [Podzol](http://minecraft.gamepedia.com/Podzol)?

**Comment by paramat** [comment]
Sort of, although podzol is a soil type and it would be helpful for our surface node to be 'default:dirt_with_ ..' and based on 'default_dirt' as this makes it work with the grass spread / grass death ABMs. This means we could avoid a MC reference and not call it podzol, maybe 'dirt_with_needles' or something.

**Comment by RHRhino** [comment]
I like the idea, but we need a better texture. 😄

**Comment by MarkuBu** [comment]
:+1: for the idea, :-1: for the texture in your example :-D

**Comment by Fixer-007** [comment]
Those textures may be better, take a look: https://github.com/VanessaE/dreambuilder_modpack/tree/master/woodsoils/textures

**Comment by MarkuBu** [comment]
Yes, the woodsoil is good

**Comment by VanessaE** [comment]
@Fixer-007 @paramat, you can find those textures and others in [plantlife modpack](https://github.com/minetest-mods/plantlife_modpack).  It's what provides the "forest floor" effect you see in Dreambuilder, though it works differently from paramat's plan.

**Comment by C1ffisme** [comment]
I don't see why people are complaining about the texture like this is a permanent one. Paramat even says:

> I have a branch for this and **have quickly grabbed some not-great textures for a quick test** as shown above.

**Comment by paramat** [comment]
Indeed that is a bad texture, and better fern textures are needed too. Thanks for the links to better textures.
The new surface texture cannot only be near trees because it is placed across the whole biome by the Biome API, luckily clearings like this are not too common.

**Comment by DS-Minetest** [comment]
On the picture of real life in first comment the floor and everything else is very bright and orange. Redwood trees seem to make not much shadow relative to pine.
I tried to find a more realistic one:
![img](https://s14-eu5.ixquick.com/cgi-bin/serveimage?url=https:%2F%2F2.bp.blogspot.com%2F-bIaF6rfpKQo%2FTos5zhwdfiI%2FAAAAAAAAApg%2FeEsmM1d8pDw%2Fs640%2FDSC06814.jpg&sp=2993b04d2699aa119ae607670906911a)
Btw. is there any reason why pine is so gray in Minetest? [https://en.wikipedia.org/wiki/Pine](https://en.wikipedia.org/wiki/Pine)

**Comment by paramat** [comment]
Updated first post with good textures by MarkuBu and Mossmanikin.

**Comment by sofar** [comment]
Did you intend to make the ground pattern lineair?

I'd love to see the V-shaped meshoptions plant used for ferns as well. The one from plantlife_modpack is too large (over a node) so I wouldn't use that one myself.

**Comment by paramat** [comment]
The ground texture us by MarkuBu and has some linearity yes, perhaps this can be fixed.
I tried some meshoptions, the * shape doesn't look right, the outward leaning one has potential.
I'm thinking of using the large (this one) and small ferns from plantlife.

**Comment by paramat** [comment]
Hm the ground texture is not quite good enough yet, any new submissions?

**Comment by paramat** [comment]
It needs more contrast and should not create lines on the landscape..

**Comment by Fixer-007** [comment]
agree about lines

**Comment by GreenXenith** [comment]
The ground should have more 'needle'-like texture. It is a forest full of pine trees after all. For snow-pine biomes, you could have a block for snow-on-pine under the snow instead of dirt-with-grass-with-snow.

**Comment by MarkuBu** [comment]
How would you like to show "needles" with 16*16 pixels?

**Comment by VanessaE** [comment]
lines 2 or 3 pixels long?

**Comment by GreenXenith** [comment]
That was what I was thinking. I will attempt to make an example (I am not on my usual device, so I have to use an online sprite maker. Yik).

**Comment by paramat** [comment]
Yes 1*2 pixels, in MT all details are enlarged and abstracted to work in 16*16.

**Comment by paramat** [comment]
![screenshot_20170314_195204](https://cloud.githubusercontent.com/assets/3686677/23920105/46572af0-08f1-11e7-8572-f22e60b549cd.png)

Apart from the lines (which could be fixed) how's this? It's by npx who made the rainforest litter texture, but i have reduced colour saturation and increased lightness.

**Comment by Fixer-007** [comment]
I see grid-like pattern now

**Comment by MarkuBu** [comment]
Looks similar to mine, just with a grid pattern. 

And maybe a suggestion to the first image: if you want to add fern use the meshoptions to create plantlike shape with six faces instead of four. Looks much better

**Comment by paramat** [comment]
![screenshot_20170314_203806](https://cloud.githubusercontent.com/assets/3686677/23921371/5902e82e-08f6-11e7-9b33-9939f801fed7.png)

Reduced grid effect.
> Apart from the lines (which could be fixed)

**Comment by Fixer-007** [comment]
Here what I see:
![default](https://cloud.githubusercontent.com/assets/16494741/23921736/64d16344-0908-11e7-870f-1ecac0a55f2e.png)

**Comment by paramat** [comment]
Well, obviously you will see patterns, the textures are on a grid and your eyes pick out the inevitable lines created. It's like this with any texture.

**Comment by paramat** [comment]
Hm looking at some photos of pine forests i may have made this too grey.

**Comment by paramat** [comment]
![dsc01734](https://cloud.githubusercontent.com/assets/3686677/23925727/84e8a76e-0908-11e7-8b32-d850e7b645eb.JPG)

**Comment by paramat** [comment]
![screenshot_20170314_231730](https://cloud.githubusercontent.com/assets/3686677/23926523/95fdb766-090c-11e7-95c1-59326e122197.png)

**Comment by Fixer-007** [comment]
now that's interesting

**Comment by sofar** [comment]
You have a contrast/sharpness mismatch. Parts of the textures have high contrast/sharpness, and then you have parts that are relatively smooth. Getting the contrast/sharpness ratio more equal should be more pleasing. Perhaps using a partial sharpening filter or a partial blur filter will make this easier to do.

**Comment by GreenXenith** [comment]
I think that is a bit too orange IMO... just a slight bit of grey might look better. It looks like some sort of coarse red sand TBH...

**Comment by Fixer-007** [comment]
Does not look orange on my monitor, somebody on CRT or pva/ips one should look at it (calibrated one) to be really sure %)

**Comment by VanessaE** [comment]
Looks orange-ish to me, perhaps a little less saturation is needed.

**Comment by paramat** [comment]
Yes perhaps a little less saturation, i noticed the change in sharpness (this is derived from npx's texture), not sure if it is a probem.

**Comment by VanessaE** [comment]
About the variations in sharpness, well, let's just say my OCD would go into a fit. :-)

**Comment by paramat** [comment]
I can try altering it.

**Comment by DS-Minetest** [comment]
Perhaps we are clamming a bit too much to reality. The forest floor should simply be nice to look at (and not too eyecatching), the specific colour is not that important.

**Comment by Sokomine** [comment]
What DS-Minetest says has its merits. Having a new texture in forrests without expensive costs at mapgen time is a very nice thing to have. The actual color may vary depending on RL region. Just add one texture and let's see how it works out in the game.

**Comment by C1ffisme** [comment]
@DS-Minetest That's only part of the truth, because it's the first priority. The second is trying to make whatever you're drawing try and, at the very least, _represent_ what you are trying to portray.

**Comment by cx384** [comment]
left or right?
![name](http://images.derstandard.at/2015/08/20/nadelwald.jpg)


<details>
<summary>Click me</summary>

![name](https://cdn.pixabay.com/photo/2014/09/28/17/06/forest-465024_960_720.jpg)
![name](https://cdn.pixabay.com/photo/2016/10/01/19/29/the-path-1708195_960_720.jpg)
![name](https://cdn.pixabay.com/photo/2016/02/25/22/04/forest-1223041_960_720.jpg)
![name](https://cdn.pixabay.com/photo/2015/04/13/21/49/forest-721344_960_720.jpg)
</details>

**Comment by DS-Minetest** [comment]
So, moss would be good.

**Comment by paramat** [comment]
Not sure i will be able to make a new texture before release, maybe, there are higher priorities though.

**Comment by Fixer-007** [comment]
You can merge this now and tweak texture later.

**Comment by paramat** [comment]
Removing from milestone, if i add a new surface texture we may want to add new decorations too, like perhaps ferns, this will take time.

**Comment by TumeniNodes** [comment]
Where does this stand currently? Can I help in any way?

**Comment by paramat** [comment]
I'm intending to work on a texture, that's the hard part. I was going to overlay many layers of grey-brown 1x3 1x4 1x5 pixel dead needles.
The screenshot in https://github.com/minetest/minetest_game/issues/1570#issuecomment-286552741 is getting closer but is still not 'needly' enough.
New textures always welcome, i'm thinkng something like:
![pine_needles](https://user-images.githubusercontent.com/3686677/30462087-2e942264-99bb-11e7-8345-ace1064094c5.jpg)

**Comment by TumeniNodes** [comment]
pine needles will be tough, probably gonna end up with some sort of pattern no matter what.
I'll pluck at it over the next few days

**Comment by paramat** [comment]
Yes any needle exiting on one border must have it's remaining length entering on the opposite border.

**Comment by TumeniNodes** [comment]
ummm, yes I got that ; )

**Comment by TumeniNodes** [comment]
I have currently have 2 samples to try out. I named them default_grass & default_grass_side.png just for test purposes. I normally just create a new texture folder, and add such items to test with.
Critiques needed. I have reworked this numerous times, trying to get the best look without ending up with serious pattern issues.
These hopefully, give the effect of a mix of dead leaves & dead pine needles. (pine needles are very difficult to achieve with 16px
![default_grass](https://image.ibb.co/dUn0uQ/default_grass.png)
![default_grass_side](https://image.ibb.co/cxyjM5/default_grass_side.png)

**Comment by paramat** [comment]
> would it not be better to work on mossmanikin's woodsoils mod so it could be merged into MTG

No because it doesn't use the Biome API and so is therefore too slow for mapgen. Textures may be ok to use though.

**Comment by TumeniNodes** [comment]
> No because it doesn't use the Biome API and so is therefore too slow for mapgen.

This was what I meant when I suggested possibly working on it, to integrate it as it is required.
If it is possible, I'll tinker around with it to see how much of a mess I can make. If I get anywhere, I will submit something in the future.

**Comment by paramat** [comment]
![coniferous-pine-needles-16286082](https://user-images.githubusercontent.com/3686677/30507031-ad96c374-9a78-11e7-8808-a03b7b5045cd.jpg)

Found a better example of what i'm after.

> These hopefully, give the effect of a mix of dead leaves & dead pine needles

Will test it, but i should say that it should be dead needles only, no normal leaves, and quite greyish as in the photo above.

All we can do with woodsoils is use the textures for forest biome nodes, which is not really integration. I don't like the textures though personally.
A 'grass with forest litter' texture would be good for deciduous forest, instead of the pure grass of current.
Together with a dead needles texture for coniferous forest we would then have a different surface for every biome.

**Comment by TumeniNodes** [comment]
ok... I'll start from scratch again ha.
just hold onto those ones I just did then for deciduous

**Comment by TumeniNodes** [comment]
@paramat 
Just wanted to know if you did test those textures yet? Are they ok for deciduous forest floor?
I am still working on a new coniferous floor but, it is almost impossible to end up with no linear patterns. I have wiped my brain and trying an entirely different approach.

**Comment by paramat** [comment]
Not yet, i will test them. Deciduous forest does have clearings so the surface texture needs to be based on our grass texture, with added 'litter', so i think some green grass showing is good. See our rainforest surface texture, that is very brown so anything too similar will not be a contrast.

Some degree of linear pattern is acceptable (and inevitable).

**Comment by GreenXenith** [comment]
Is this still being worked on?

**Comment by paramat** [comment]
Yeah, just busy and waiting for contributions.

**Comment by TumeniNodes** [comment]
I have had a difficult time getting anything to look/fit right. Stopped work on it for a bit as I have some other RL things going on.
I would like to suggest that possibly opening a "contest" of sorts within the community might be beneficial.
This might bring in some really good textures to choose from, and would also make the community feel more involved. As I said, just a suggestion, but one which often brings decent results, and in a smaller amount of time.
But limit entries to 1 or 2, otherwise..., well..., you know.

**Comment by paramat** [comment]
No problem, it's a difficult one.

**Comment by TumeniNodes** [comment]
@paramat  can you try these when you have a chance?
Just new rough tests for conif forest floor, it's about the best I can come close to showing pine needles on floor
![conif_forest_floor](https://image.ibb.co/cA6LvR/conif_forest_floor.png)
![conif_forest_floor_side](https://image.ibb.co/mAbEN6/conif_forest_floor_side_shdw.png)

**Comment by paramat** [comment]
Thanks will try.

**Comment by TumeniNodes** [comment]
sorry.
The bottom 2 are the overlays I made (that is just how I work)
The top texture, is the full overlay, over default_dirt. I added it just to show how they look when combined, and to test

It just makes it easier to set everything to the desired look
I have a clean, side overlay as well without the shading. I can add that if you like

**Comment by paramat** [comment]
Great, an overlay to add to dirt, as the top texture, is ideal.
I agree with altering the colour, i was thinking a more grey-brown.

**Comment by paramat** [comment]
![screenshot_20171222_002315](https://user-images.githubusercontent.com/3686677/34280282-a2b2b2a6-e6ae-11e7-9208-f95ea072f508.png)

Excellent, tiles really well too, thanks. Will now start the PR.

**Comment by GreenXenith** [comment]
2 things on those textures;
Perhaps a bit harsh, a little bit smoother might be better, I dunno.
Also, IMO they tile OK but not great because I can still see the separation lines.
Other than that, I think this is the best temperate floor yet.

**Comment by paramat** [comment]
PR #1990

**Comment by TumeniNodes** [comment]
the colour looks great, nice eye @paramat

**Comment by paramat** [comment]
Yes we still need a 'deciduous forest litter' texture so that i can create a dedicated surface node for deciduous forest, that would be appreciated, i'm not good at realistic organic textures.
A woodsoils type approach can't be done with our Biome API, and is too complex anyway.

**Comment by TumeniNodes** [comment]
Ok, I'll get on deciduous forest litter next then.
just similar, with all dead leaves or, did you mention you would like a bit of green/fresh fallen leaves mixed in?

attaching woodsoils to trees.lua might work? it would be just attaching the textures to apple and aspen trees at their base and a formula for spread and thinning out... This sounded much better in my head.

 Oh well, I'll drop the woodsoils idea, ha. (forget I said this, you didn't see anything)

**Comment by VanessaE** [comment]
:+1: for that last screenshot, @paramat.

@TumeniNodes, A bit of color is a good idea, but not necessarily green - more like autumn colors: orange, gold, yellow, etc (but muted of course).

**Comment by TekhnaeRaav** [comment]
Hey, love the textures in the last screen shot. :+1:
    But I am wondering if the 'forest litter' should kind of drop off at the bottom side of the block revealing the dirt.

**Comment by paramat** [comment]
I'm still unsure what to do for deciduous forest litter. It can't be autumn leaves because the trees are obviously in summer-leafy state.

**Comment by paramat** [comment]
#1990 merged.

**Comment by paramat** [comment]
I actually like the green grass of deciduous forest and want to preserve that green lushness. Maybe the texture can be a subtle overlay for grass with a few leaves. I certainly don't want a brownish or messy look. So a deciduous litter texture is not high priority, take your time.

**Comment by TumeniNodes** [comment]
> I actually like the green grass of deciduous forest and want to preserve that green lushness. Maybe the texture can be a subtle overlay for grass with a few leaves. I certainly don't want a brownish or messy look.

Gotcha

> take your time.

Oh..., I will. I _will_  (Yoda voice)

In my region, deep forest floor is dirt, dead leaves, twigs, etc., with random tufts of wild grass here and there.
Even though that is reality, this is a game and given the nature of 16px textures, and the way in which biomes blend in-game, this would probably look horrid.

So I agree that sticking mainly to the current grass (with a slight modification) will work best

**Comment by paramat** [comment]
To be honest, i feel i won't be happy with anything other than grass as it is now, so for simplicity i'll say don't bother and will close this. But feel free to continue discussion here.

**Comment by MarkuBu** [comment]
So many people who likes this and you close it 1inch before the finish line? Dude, I really don't understand you

**Comment by paramat** [comment]
Just being honest. Possible textures can still be posted here and it's possible i may change my mind when i see them. The close is because this is now very low priority, coniferous forest was the main issue.

**Comment by paramat** [comment]
Well i guess this can stay open for a while longer.

**Comment by TumeniNodes** [comment]
@paramat 
I think, if you want you could close this and when I or someone else do come up with a reasonable texture, a new PR can be opened.
I won't forget about it but, it is not something high on my todo list for the next few weeks. I will continue to play around with ideas here and there.

For anyone who might oppose closing it, part of having a place to post issues and submit PRs is keeping issues down and PRs up, in numbers.
Since this is such a low priority, it makes no sense to just leave an open issue sitting around which is not necessarily an "issue"

**Comment by paramat** [comment]
I don't mind keeping it open, a dedicated surface node for deciduous forest is still a good idea, just not high priority.

**Comment by TumeniNodes** [comment]
ok.

> Still interested in any subtle textures that can be overlaid over the grass texture.
yep, that is how I like to do it anyway. It makes it much easier in the long run

**Comment by TumeniNodes** [comment]
![deciduous_litter](https://image.ibb.co/fWVEsG/deciduous_litter.png)

![deciduous_litter_side](https://image.ibb.co/eU0EsG/deciduous_litter_side.png)

combined textures
![grass_with_deciduous_litter](https://image.ibb.co/mmK7CG/grass_with_leaf_debris.png)

![grass_with_deciduous_litter_side](https://image.ibb.co/iSasew/grass_with_leaf_debris_side.png)

**Comment by MarkuBu** [comment]
Is it intended that dirt with coniferous litter spreads like grass?

**Comment by paramat** [comment]
Yes, dirt with snow and rainforest litter does too. It's so that if you dig a surface node and it turns to dirt, the dirt changes to suit it's environment. All dirt-based surface nodes do this.

**Comment by TumeniNodes** [comment]
@paramat 
still waiting dude (insert smiley face here)

I know you've been very busy, this is just a reminder

**Comment by paramat** [comment]
![screenshot_20180113_105022](https://user-images.githubusercontent.com/3686677/34905397-a1214b16-f84f-11e7-9842-addf548f2b06.png)

Nothing wrong with the textures, i just don't like the messy appearence. Deciduous forests have clearings which look better if just green grass. As mentioned before i personally might find it hard to like anything other than grass as it is for this biome, even though it is unrealistic for a deciduous forest.

**Comment by MarkuBu** [comment]
It would be awesome if  there would be some litter around trees like the wood soil from the moreplants modpack. I know it is not really possible right now without performance issues. I just want to mention it.

**Comment by Fixer-007** [comment]
That litter on screenshot looks strange tbh.

**Comment by TumeniNodes** [comment]
I agree with the last three comments.
especially with MarkBu, and I honestly feel this should be closed and brought up at a later date, when working in a form of mossmanikin's wood soils mod can be worked in.

tbh, I use wood soils on it's own and have never experienced any performance impact. I also made some slight changes to it to fit my own personal desire, regarding where it is used.
I _think_ the performance issues regarding wood soils, is when it is used from within moreplants / plantlife. It's a heavy modpack, same with other mod packs which come with lag coded right into them (at no extra charge)

**Comment by paramat** [comment]
Something that changes node around a tree after mapgen may be better. This can be left open, it's low priority.

**Comment by MarkuBu** [comment]
To be honest I like the woodsoil from plantlife, but there is potential for optimization. I doesn't work all time and below some of the trees there is no woodsoil.

Probably this could be separated and optimized

**Comment by VanessaE** [comment]
You're right that woodsoils could perhaps be faster, but I'm pretty sure it's intentional that not every tree has ground litter (since biome_lib has a "stuff can grow here"/"this spot is fertile" Perlin noise "layer" and pretty much everything uses it)

**Comment by MarkuBu** [comment]
It doesn't make sense that some trees have litter and others don't. (mostly) All trees loose their leaves

And I found a strange bug in the woodsoil mod. This straight cut doesn't make sense too

![screenshot_20180115_170109](https://user-images.githubusercontent.com/16163058/34951318-223cc992-fa16-11e7-9963-66bb75faf432.png)

This cut is between X 47 and 48. But it does not appear everywhere and if I regenerate the map (dummy DB backend) this issue moves

**Comment by VanessaE** [comment]
Beats me why it does that, but this ain't the place to discuss woodsoils mod.

**Comment by paramat** [comment]
![screenshot_20180123_144156](https://user-images.githubusercontent.com/3686677/35281845-d8a9057a-004b-11e8-9744-fa99df9039ad.png)

Tuning a greyer and lighter version of coniferous litter.

**Comment by paramat** [comment]
Think i have it now, a little less colour saturation, a nice contrast against dirt.

![screenshot_20180202_003748](https://user-images.githubusercontent.com/3686677/35710865-be3484cc-07b1-11e8-94e3-30bcfe1b8a0d.png)

I'll make a PR.

**Comment by paramat** [comment]
PR #2038

**Comment by paramat** [comment]
A dedicated surface node for deciduous forest may be ok if a good texture appears, but very low priority since grass works well.
