### ISSUE TITLE
Bugs using the newest Android client

### ISSUE THREAD

**Issue by hkzorman** [minetest/minetest_game#1575]
While using the most recently updated Android client (0.4.15-bc2861e2-Android, or so it seems, please see screenshot below), I have noticed a few bugs in Minetest game.

- The following biomes are missing:
  - taiga
  - snowy_grassland
  - grassland
  - coniferous_forest
  - deciduous_forest
  - savanna
  - rainforest
  - **Cause**: when the application is updated from 0.4.14 to 0.4.15, the old "singleplayerworld" generated by mgv6 remains, causing the issues. Deleting the folder "singleplayerworld" and trying singleplayer again removed the messages and the biomes are present.
- The cart texture is missing (on tablet) or reverse (on phone), please see screenshots below.

**Screenshots**
Missing biomes:
![image](https://cloud.githubusercontent.com/assets/24514440/23094429/aebefe80-f5c6-11e6-9059-09a92217e2a7.png)

Wrong cart texture
Tablet/chromebook:
![image](https://cloud.githubusercontent.com/assets/24514440/23094438/e46c3f7a-f5c6-11e6-9da6-1cb022ac21c9.png)

Phone:
![image](https://cloud.githubusercontent.com/assets/24514440/23094442/f6678626-f5c6-11e6-848c-2d1bdee17820.png)

Version (same in phone and tablet)
![image](https://cloud.githubusercontent.com/assets/24514440/23094445/04eaef94-f5c7-11e6-91ba-336ee0a5ebc8.png)

**Comment by rubenwardy** [comment]
@paramat

**Comment by pilino1234** [comment]
The messages about the missing biomes have been present in games with mgv7 since paramat's new biome commits in mgv7, haven't looked into where the errors come from though.

**Comment by hkzorman** [comment]
For the missing biomes, I found the issue: it happens only when you update the application.
Since "singleplayerworld" folder contains a world generated by mgv6, the biomes definitions are missing. I deleted the "singleplayerworld", restarted the app, clicked on "Start Singleplayer" and the biomes error are gone. It uses mgv7 to generate the world as well.

**Comment by paramat** [comment]
Are you using latest Minetest Game? For a few days mgv6 ore generation expected biomes due to the new biome-specific ores, i then later gave mgv6 it's own dedicated ore registrations that don't expect biomes.

**Comment by hkzorman** [comment]
For the cart texture, the problem seems to be using `minetest.inventorycube()` to generate the texture cube. I grepped and it is the only instance used in vanilla Minetest Game.
FWIW, I have seen the texture issue also with other Minetest clones, like upside-down cube inventory textures.

@paramat It is the latest Android client, so I will assume it is latest Minetest Game. However, as said before, the issue happens when you have an old mgv6 generated world, update the app and try to run it using this old mgv6 world. Maybe the Android client should be updated to ensure it has the latest version of mt_game.

**Comment by paramat** [comment]
It might not be latest MTGame.

**Comment by paramat** [comment]
Ok if this is self-fixing then it may be due to a failure of this code to detect 'mg_name = v6' in settings, for some reason on Android https://github.com/minetest/minetest_game/blob/master/mods/default/mapgen.lua#L1664

**Comment by hkzorman** [comment]
What about the cart texture? Do you think it will be possible to create an icon for the cart like the boat and the bed?

**Comment by paramat** [comment]
Oops.

**Comment by sofar** [comment]
changing the cart texture wouldn't fix the bug, which appears to be in the engine.

**Comment by hkzorman** [comment]
@sofar Agreed, was just proposing a simple workaround.

**Comment by paramat** [comment]
Please could you open an issue in the engine for the cart inventory image?

**Comment by hkzorman** [comment]
Opened: [https://github.com/minetest/minetest/issues/5296](https://github.com/minetest/minetest/issues/5296)
