### ISSUE TITLE
Setting sane default settings for Minetest Game

### ISSUE THREAD

**Issue by pilino1234** [minetest/minetest_game#1576]
Different subgames may change certain settings such as gravity or the speed of time, but when switching from a subgame which changes these settings back to Minetest Game, these changes are preserved. This is because Minetest Game does not set its own settings to values required for gameplay to function as intended anywhere. 

For example, if a user plays a space subgame that changes `movement_gravity` to 0, and then switches back to a different world using Minetest Game, there will still be no gravity. 

I propose that Mintest Game should set certain settings to sane default values, to make sure that casual players can switch easily between subgames, without having to go into the advanced settings menu to change gravity to 9.81.

But, which settings should minetest game set? I think `movement_gravity` and `time_speed` are essential and should be set to default values when Minetest Game is loaded, but there may be others.

**Comment by rubenwardy** [comment]
> <rubenwardy> really those mods shouldn't be writing to minetest.conf for that
> <rubenwardy> there should be a better API for determining between game, global, and world configurations

http://irc.minetest.net/minetest-dev/2017-02-18#i_4815082

**Comment by sofar** [comment]
Making this change requires that every game modifies `minetest.conf`.

these should have never been settings in the first place.

**Comment by C1ffisme** [comment]
@sofar Although, it does mean I can set my fast speed to be a bit more like a sprint, rather than superhuman dashing.
