### ISSUE TITLE
Make skeleton key stackable (golden ones only)

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1595]
For easier storage. After putting key to use it becomes non stackable.

**Comment by DS-Minetest** [comment]
:+1:
With buckets this already works nicely. I don't think, anyone would have a problem with such a change.

**Comment by octacian** [comment]
:+1: It makes a lot more sense.

I'll open a PR in a few hours.

**Comment by paramat** [comment]
#1597 merged.
