### ISSUE TITLE
Increase climbing speed of steel ladders

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#1600]
Steel ladders could get an increased climbing speed, compared to wooden ladders. This would turn steel ladders into a serious upgrade over wooden ladders and makes it much more rewarding to craft. :-)

Currently, their only real advantage is that they don't burn which is only really needed near lava, so their use is limited.

Requires https://github.com/minetest/minetest/issues/5333.

**Comment by C1ffisme** [comment]
This sounds okay, I'm just not sure why a different material of ladder would be easier to climb.

**Comment by stujones11** [comment]
> I'm just not sure why a different material of ladder would be easier to climb.

Personally, in RL I'd feel a lot safer on a strong steel ladder than a makeshift wooden one and would therefore climb faster. I would be happy to see a moderate speed increase for steel ladders as long as it is easy enough to implement, I have no idea whether it is or not.

**Comment by DS-Minetest** [comment]
The material is not the main thing which tells you whether a ladder is save or not. In minetest ladders are static which makes them very safe.
In my opinion not being burnable is as advantage good enough.
To give steel ladders more sense we could make them cheaper. Since one steel ingot is larger than a little stick and you don't make steel constructions massive normally, it would make sense to give more out at crafting. (Perhaps add steel rod as new craftitem?)

**Comment by paramat** [comment]
Realistically steel ladders probably can be climbed faster than an old fashioned wooden one, however i would like to have climb speed increased for all ladders simply by using a new physics setting. I don't feel a per-node climb speed is justified :-1:

**Comment by sorcerykid** [comment]
A steel rod might actually be a worthwhile addition, as they could also find use in rails, chainlink fences, iron bars, and other items where a steel ingot is unjustifiably costly. Perhaps if you place one steel ingot into the crafting grid, it produces 4 steel rods. Just some thoughts.

**Comment by stujones11** [comment]
> A steel rod might actually be a worthwhile addition

I like this idea, it would be consistent with using sticks to make wooden ladders and help to make crafting steel items less expensive with more unique recipes.

**Comment by paramat** [comment]
I'll make a PR for a higher general climb speed, partly to make the loss of sneak elevators less painful, partly because MT is so vertical, partly because walking up stairs is so fast.

**Comment by paramat** [comment]
:-1: Worlds may want to use wooden ladders only for appearence reasons, so i feel all ladders shoud have equal speed.

**Comment by sorcerykid** [comment]
I just added steel rods to my server last week and changed the crafting recipe for steel ladders accordingly. Now steel ladders and wooden ladders are, I feel comparable. And I would expect them to both have the same climbing speed. The appearance factor is also a good point.

![craft2](https://user-images.githubusercontent.com/24327224/28804115-ecbcfaa8-7626-11e7-9c6c-7e2264833526.png)

**Comment by SmallJoker** [comment]
Speaking of ladders, they all should have the same speed. The climbing speed depends on the player and the quality (solidness) of a ladder. As already said by DS-Minetest, they are static, so we don't have a difference between the ladders except the flammable group. An upgrade can also be made in the craft recipe, where you get a different amount of ladders, depending on the input materal.
:-1: for this request.

**Comment by C1ffisme** [comment]
This isn't about realism, though, this is about balance.

Steel > Wood, so logically spending the more expensive resource should result in more reward.

The other option is giving more ladders per steel ingot compared to ladders per wood plank. (Although in order for that to be truly balanced, wood planks have to give an incredibly low amount of ladders in order for the upgrade to steel to be worth the effort.)

**Comment by sorcerykid** [comment]
As paramat pointed out, some people choose steel or wood ladders for appearance.

And I don't think it is true that steel > wood. **Availability of resources is entirely dependent on the mapgen parameters, and by consequence, the subgame**

Go to a server like just test or JT2. These subgames feature all stone worlds. Iron ore is abundant compared to wood which is a highly valued resource. For the same reason sand is extremely rare, but obsidian is plentiful. This is completely backward in comparison to subgames that enable biomes.

Why should the default node definitions for steel ladders and wood ladders be tuned specifically for only one type of mapgen where it is assumed that wood > steel?

**Comment by C1ffisme** [comment]
> Go to a server like just test or JT2. These subgames feature all stone worlds. Iron ore is abundant compared to wood which is a highly valued resource. For the same reason sand is extremely rare, but obsidian is plentiful. This is completely backward in comparison to subgames that enable biomes.

Dirt is very scarce in a skyblock too. But both of these examples aren't the default gameplay, and considering that this is an issue about Minetest Game, we should assume it's an issue about the default Minetest Game gameplay.

**We cannot balance Minetest Game for every combination of third-party mods or configurations.**

**Comment by paramat** [comment]
> Steel [is larger than] Wood, so logically spending the more expensive resource should result in more reward.

Not necessarily, that's a way to justify it, but other considerations override that here. We can't make everything weird and unrealistic based on material value.

**Comment by C1ffisme** [comment]
> Not necessarily, that's a way to justify it, but other considerations override that here. We can't make everything weird and unrealistic based on material value.

Gameplay > Realism

(Also, when I said Steel > Wood, I meant that Steel is more _valuable_ than Wood, not larger than. And in the case I gave above, Gameplay is more _important_ than Realism.)

Don't get me wrong. I love realism in gameplay, and I think that sometimes realism makes for good balance by itself in a sandbox game (and it's a great way to educate people on Physics, Geology, Biology, etc. in many cases), but there are many cases where realism isn't balanced for a game meant to be played by a single player with limited playing time and real-world knowledge. (Such as distance or size. Sure, oceans are supposed to be miles and miles across, but besides the obvious issue of world size, oceans in real life take a very long time to cross in boats, much longer than the average playtime.)
