### ISSUE TITLE
Choose player attribute modname prefix character.

### ISSUE THREAD

**Issue by sofar** [minetest/minetest_game#1608]
Devs only please. Please select the character that we will use consistently in player attributes to separate modnames and attributes.

- [x] - `modname:attribute`
- [ ] - `modname.attribute`
- [ ] - `modname_attribute`

**Comment by Ekdohibs** [comment]
To my mind, ":" is the most consistent with the rest of the code & API, so voting for that one.

**Comment by sofar** [comment]
`:`

**Comment by rubenwardy** [comment]
: is most consistent

**Comment by kaeza** [comment]
For reference: http://irc.minetest.net/minetest-dev/2017-03-08#i_4825959

**Comment by paramat** [comment]
: seems good.
