### ISSUE TITLE
Jungle grass experiments

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1610]
With new jungle block I've noticed that jungle grass is a bit bright (am I only one?):
![default](https://cloud.githubusercontent.com/assets/16494741/23728297/bba5c938-0464-11e7-8c0f-12f44ae1b9e3.png)

I tried to darken said jungle grass a bit, what do you think?
![default](https://cloud.githubusercontent.com/assets/16494741/23728450/8682039c-0465-11e7-8203-107ffaa4bf7f.png)

**Comment by MarkuBu** [comment]
I think a lot of nodes in Minetest are to bright. I like it

**Comment by hkzorman** [comment]
I like it as well. It has always striked me that jungle grass is a bit too
bright.

**Comment by paramat** [comment]
It would help rainforest feel darker. If you post the texture we can test it in-game.

**Comment by Fixer-007** [comment]
Texture, tbh this jungle grass always looked odd in minetest
![default](https://cloud.githubusercontent.com/assets/16494741/23767202/69a27f08-0510-11e7-8cc0-a42e79e9f06f.png)

**Comment by paramat** [comment]
![screenshot_20170309_203914](https://cloud.githubusercontent.com/assets/3686677/23769818/887aebca-0508-11e7-834b-2166406a7cca.png)

The darkness is ok but it's not quite right, it seems too colour-saturated and/or too high contrast.

**Comment by paramat** [comment]
![screenshot_20170309_204315](https://cloud.githubusercontent.com/assets/3686677/23769952/0df78a10-0509-11e7-88db-f0fab8b09997.png)

This screenshot shows what i mean, the darkening seems to have caused too high saturation.

**Comment by Fixer-007** [comment]
Yes, it can be darkened in different way.

**Comment by sofar** [comment]
You don't want to darken this texture since the contrast range is already very large. Try reducing contrast first and then adjusting brightness to match. Alternatively, use levels.

Of course, there's only like 3-4 color values in this image, so it's very pale and awkward. It could use some detailing and would look a lot better quickly.

**Comment by Fixer-007** [comment]
I used curves instead and lowered the brightness on brighter pixels, it looks more darker and less saturated now?
![default](https://cloud.githubusercontent.com/assets/16494741/23964122/1802d566-09bc-11e7-9c55-1950ec532b2b.png)

**Comment by paramat** [comment]
Seems to lack contrast and definition now.

**Comment by MarkuBu** [comment]
That's why I don't make textures :-D

**Comment by Fixer-007** [comment]
Ok, lets see alternative textures I found in my mods folder:
* carbone_ng
![default](https://cloud.githubusercontent.com/assets/16494741/23966127/e87f5d76-09c2-11e7-8279-abbf53a3f5ca.png)
* farming
![default](https://cloud.githubusercontent.com/assets/16494741/23966150/068dd9a0-09c3-11e7-9ce2-e4c8772eb352.png)
* minetest ng
![default](https://cloud.githubusercontent.com/assets/16494741/23966189/291dcc6e-09c3-11e7-8c39-0f9d776a3e58.png)
* grailtest
![default](https://cloud.githubusercontent.com/assets/16494741/23966235/49cf67f6-09c3-11e7-841d-23241fd735c1.png)

**Comment by paramat** [comment]
The Carbone NG ine looks washed out and bluey, i feel our current one will be fine as long as it retains a decent contrast.

**Comment by VanessaE** [comment]
There are quite a number of plants in my modpacks, but I couldn't say if any are suitable for this particular use.

**Comment by paramat** [comment]
Looking at current junglegrass i think it's fine as it is.

**Comment by Fixer-007** [comment]
Decided to close it for now, if someone comes up with something new, can be reopened later.
