### ISSUE TITLE
Flint and Steel sound heared by everyone on server

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1613]
Heared this on two servers already and my suspicion went through the roof, so I checked on localhost with two clients and confirmed the bug.

Newest minetest_game.

**Comment by paramat** [comment]
00:17 paramat the sound has a 'pos'
00:18 paramat maybe pointed_thing.above is failing
00:19 paramat maybe if a player uses it while not actually pointing at a node
00:21 paramat pos may need a fallback
00:21 paramat as in the player position

**Comment by paramat** [comment]
00:30 paramat yes pos is nil if not pointing at a node

**Comment by rubenwardy** [comment]
> Player pos may be better than pointed_thing.above anyway

It's the flint and steel being used, not the node, so I say that this is fair

**Comment by sofar** [comment]
>> Player pos may be better than pointed_thing.above anyway
>
>It's the flint and steel being used, not the node, so I say that this
>is fair

In a surround speaker setup, you'd hear the sound as if you're inflaming your own player character. A bit strange because the item that is supposed to make the sound is in front of you in your hands.

The sound should come from in front of the player, as much as possible. Pointed_thing.above is as ideal as it gets imho.

**Comment by sofar** [comment]
>00:19 paramat maybe if a player uses it while not actually pointing at
>a node

Just looking at the code confirms that it is just Willy nilly playing sound at pt.a even though it may not exist.

**Comment by paramat** [comment]
Yes, pt.above falling back to player pos is fine, will do.

**Comment by hkzorman** [comment]
Ehm, I'm I wrong to think that being able to hear other player's flint
isn't an issue? I actually feel this is good. I mean, fire or igniting a
TNT is dangerous. Being able to listen to another player doing it might be
beneficial.

**Comment by sofar** [comment]
@hkzorman no, that's what the logs are for. All sounds in the world should be positional, unless it's some sort of global announcement sound.

**Comment by hkzorman** [comment]
I think I have misunderstood the issue. Got it now, nevermind.

**Comment by paramat** [comment]
#1617 merged.
You can hear other's use of flint and steel, but it's positional.
