### ISSUE TITLE
Backspace stops working when writing book

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1614]
During the bug: typing and space work, but backspace and left/right arrows are not. If I use arrow up or down or by clicking other position with mouse - bug goes away.

Ways to reproduce:
+ Write a book with multiline text and save it. Open a book again and click to very end after the text and try to backspace or start typing and then try to backspace.
+ Alt-Tabing several times while writing the book may cause this problem, but I'm not 100% sure

Reproduced on newest minetest_game.

DEMO on how to reproduce, what is interesting, backspace started working again somehow near the end of the gif.
![test](https://cloud.githubusercontent.com/assets/16494741/23777600/897546f2-053e-11e7-8475-89ff553083f7.gif)

**Comment by sofar** [comment]
I've spotted this as well.

**Comment by sofar** [comment]
Prolly an engine bug though!

**Comment by Fixer-007** [comment]
Do we need to open an issue in engine? I'm not sure how to word this stuff related to formspecs.

**Comment by DS-Minetest** [comment]
> how to word this stuff related to formspecs

Well, this happens with all [textfields](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L1650). (Perhaps even with all fields, I'm not sure.)

**Comment by octacian** [comment]
I've experience this issue quite often as well. It's very annoying, though there are ways of opening stuff that sometimes avoids them. I've rarely experienced the issues in `fields`, but nearly all the time in `textareas`. First came across this when working with mesecons Lua Controllers. And yes, you should try to open this issue in the engine.

**Comment by Fixer-007** [comment]
Moved the bug into the engine section https://github.com/minetest/minetest/issues/5587
