### ISSUE TITLE
sfinv - on_leave callback crashes on player:get_player_name()

### ISSUE THREAD

**Issue by ExeterDad** [minetest/minetest_game#1616]
It is possible I'm doing this new, awesome and barely documented code wrong.

I am able to get the on_leave callback of sfinv.register_page to `print(''Random Message")` when clicking other tabs in the formspec. But as soon as I  add a
 `local name = player:get_player_name()` 
the game crashes with: `attempt to call method 'get_player_name' (a nil value)
`

**Comment by SmallJoker** [comment]
How does your code look like? Here something that should work fine:
```Lua
sfinv.register_page("foo:bar, {
	[...]
	on_leave = function(self, player, context)
		print("Foo the bar baz")
		local name = player:get_player_name()
	end,
})
```

**Comment by ExeterDad** [comment]
@SmallJoker I copied and pasted your on_leave callback into my sfinv.register page and it worked exactly as expected.
I'm happy, but also disturbed as your example is pretty much how I remember my callback looked. Unfortunately I removed my callback so I could at least keep working on the mod.

Thanks for debunking the "bug", and so sorry to waste time -- Closing
