### ISSUE TITLE
Rainforest litter can't be used for farmin

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest_game#1619]
I can't use rainforest litter as farming soil

**Comment by NathanSalapat** [comment]
Farming mod needs to have that soil added. Are the valley dirt's usable as farming soil? This may be intentional, though we should be be able to craft normal dirt if that is the case.

**Comment by MarkuBu** [comment]
> Are the valley dirt's usable as farming soil?

No. It's a good question. Which soils should be added for farming? Each node marked as soil?

**Comment by paramat** [comment]
I forgot to add this soil to farming, will do.

**Comment by paramat** [comment]
PR #1639

**Comment by paramat** [comment]
#1639 merged.
