### ISSUE TITLE
Copying book gives empty "Book with text"

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1623]
If you copy a book (by placing written book + book in receipe) you get empty "Book with text" (in survival). In creative mode i somehow ended up with unwritable "Book with text".

@octacian

**Comment by sofar** [comment]
Confirmed, book copy recipe is broken.

**Comment by octacian** [comment]
Yes, I am aware that this is broken as of several days ago. I am currently traveling, so am using my laptop. I'll see what I can do though, as I was planning on submitting a new PR to fix this but it may take a few days.

**Comment by paramat** [comment]
#1636 merged.
