### ISSUE TITLE
Right clicking on locked chest with golden key opens it instead of assigning

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1625]
Previously I would instantly assign the new key to this locked chest after right click, but now right click just opens the chest, key is assigned via shift-right click and there's no info about "how to assign the key" for a player.

**Comment by SmallJoker** [comment]
Since 78c632e other items in MTG behave this way aswell.

**Comment by sofar** [comment]
Should we just make the skeleton key use `punch` to assign it?

**Comment by Fixer-007** [comment]
Maybe, any good alternatives?

**Comment by sofar** [comment]
Punch seems reasonable, its a `tool` after all. shift-rightclick is terrible.

**Comment by Fixer-007** [comment]
Yeah, I'm leaning towards it too.

**Comment by sofar** [comment]
#1635 changes skeleton key to 'make' on left click.
