### ISSUE TITLE
TNT recipe update in Readme.txt

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1629]
https://github.com/minetest/minetest_game/blob/master/mods/tnt/README.txt#L34 needs update with new TNT crafting recipe since this commit https://github.com/minetest/minetest_game/commit/f07c4dcd839c5be09e83cae47126927bb86cb676

**Comment by paramat** [comment]
Since it's simple could you make a PR?

**Comment by Fixer-007** [comment]
Yes, but I'm having trouble how to describe recipe in words.

**Comment by paramat** [comment]
Describe it graphcally instead?
-------- wood ---------
wood gunpowder wood
-------- wood --------

**Comment by Fixer-007** [comment]
opened a PR
