### ISSUE TITLE
Create a Mediterranean biome

### ISSUE THREAD

**Issue by Pharaone** [minetest/minetest_game#1631]
why not create a Mediterranean biome? with large shore and plains with olive trees and palm trees

**Comment by sofar** [comment]
Savannah is a dry and warm biome already, there would be little difference.

**Comment by paramat** [comment]
I go by 'official' world biomes, Mediterranean could be considered Chaparral http://www.blueplanetbiomes.org/chaparral.htm which i did not include in the biome system,it may be difficult to include.

**Comment by MarkuBu** [comment]
There is no garantie that this biome spawns in a plain with a beach, That is the problem with current biome system

**Comment by paramat** [comment]
It could be limited to low altitude though with y-limits.

**Comment by MarkuBu** [comment]
It could, but if I'm not wrong then we have the problem with horizontal lines between stacked biomes

**Comment by dsohler** [comment]
@MarkuBu Unfortunately [we already have this issue](https://github.com/minetest/minetest/issues/5308) but paramat won't add a fix for it.

**Comment by octacian** [comment]
@dsohler don't give up hope yet, there's #5344 :P

**Comment by dsohler** [comment]
> I'm going to delay this

But "I'm going to delay this" isn't much to hope for :(

**Comment by paramat** [comment]
It might still happen, i just have to be careful before adding something irreversible like this.

The straight line horizontal boders don't look good but is the official intended way to vertically limit biomes. Vertical heat and humidity gradients will not necessarily be able to keep chapparal where you want it.

**Comment by dsohler** [comment]
> The straight line horizontal boders don't look good but is the official intended way to vertically limit biomes.

So there never will be anything that makes the biomes less "stacked" but more like a seamless transition because it is the *official intended way* how it looks like right now. Before having vertically blended biomes the *official intended way* of doing this has to be changed before changes to the code will be merged, I guess.

Do biomes "know" where they are in the landscape? Then it would be easy to "bind" them to defined types. Low plains get this biomes, mountains that biome up to N nodes above water level and then another biome, river sides get a river side biome, and so on.

**Comment by paramat** [comment]
> So there never will be anything that makes the biomes less "stacked" but more like a seamless transition because it is the official intended way how it looks like right now.

I didn't say that. It's the current method but i agree it looks ugly and needs improving, i'm still thinking how it can be done (without heat/humidity gradients).
Biomes are independent of terrain so they don't know what sort of terrain they are being applied to.

**Comment by raymoo** [comment]
What about a new valu separate from heat or humidity that has a height-based gradient?

**Comment by 100best** [comment]
What about both a cold-summer Mediterranean biome with conifers, ferns, mountains, snow, strong storms, fog, wind, rain, rivers, large shore, mosses,  some deciduous, stones and also a warm-summer Mediterranean biome?

**Comment by paramat** [comment]
^ Hehe.

So i'm closing this, adding a biome is a huge amount if work to rebalance the voronoi structure and chaparral is a minor biome already covered by savanna.
