### ISSUE TITLE
Signs can't be rotated by screwdriver

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1632]
This commit says it permits sign rotation and stuff: https://github.com/minetest/minetest_game/commit/f14b0a6ff5165d2858bd4e4f2586c7eaa29097fe Tried to rotate, no luck.

**Comment by sofar** [comment]
This is because of the merged PR with other stuff in between. The new PR fixes it.

#1634

**Comment by Fixer-007** [comment]
Fixed.
