### ISSUE TITLE
Dying in lava while riding a boat respawns player in a boat causing repeated deaths

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1633]
To reproduce start a clean world, make lava pool and ride a boat into it.

It is a bug and edge case, but could be useful to uncover potential problems.

**Comment by red-001** [comment]
see #5075

**Comment by Fixer-007** [comment]
Ok, I will close this once 5075 is reopened.

**Comment by Fixer-007** [comment]
dupe of 5075
