### ISSUE TITLE
Use junglegrass to convert dirt to dirt_with_rainforest_litter

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1643]
Right now placing a junglegrass on dirt converts it to "Dirt with Grass", however we now have "Dirt with fainforest litter", it should convert dirt to that now.
![default](https://cloud.githubusercontent.com/assets/16494741/23997797/9075a6f0-0a5b-11e7-8a31-2c6c8919d973.png)

**Comment by sfan5** [comment]
Why does it convert the grass anyway?

**Comment by tenplus1** [comment]
This happens because default:junglegrass is in the {grass=1} group and the dirt spread function uses that to set the dirt type to default:dirt_with_grass : https://github.com/minetest/minetest_game/blob/master/mods/default/functions.lua#L388

**Comment by paramat** [comment]
Will fix.

**Comment by paramat** [comment]
PR #1645 
I don't think junglegrass should 'seed' rainforest litter as that is dependent on jungletrees above. Grass and dry grass are essentially very similar to the grass and dry grass that appears on the seeded node below, but junglegrass and rainforest litter are very different things.

**Comment by paramat** [comment]
#1645 merged.

**Comment by Fixer-007** [comment]
So now it is impossible to convert dirt to litter outside jungle?

**Comment by hkzorman** [comment]
How about mixing jungle leaves with dirt to make rainforest litter?

**Comment by paramat** [comment]
That would be ok with me, a shaped recipe of jungleleaves over dirt.
