### ISSUE TITLE
Flora does not spread on dirt with litter

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1650]
Grasses, flowers, etc does not spread on newly introduced dirt with litter block:
![default](https://cloud.githubusercontent.com/assets/16494741/24074036/3152ff3c-0c0a-11e7-91d6-9bd045e8400c.png)

**Comment by paramat** [comment]
Working on it.

**Comment by paramat** [comment]
PR #1651

**Comment by paramat** [comment]
#1651 merged.
