### ISSUE TITLE
Can't hide chat in daily build

### ISSUE THREAD

**Issue by NathanSalapat** [minetest/minetest_game#1653]
title says it all, when you hit F2 to hide chat it hides the HUD, F1 also hides the HUD. Probably a simple mistake in a recent commit. This possibly should be an engine issue, not sure.

**Comment by sofar** [comment]
It already is an engine issue. On mobile... Can't look it up atm

**Comment by kaeza** [comment]
This was already fixed in minetest/minetest@9f4916a4528011b820c8bcbb3160bebda0cd2c2a.

**Comment by NathanSalapat** [comment]
Okay, just wanted to make sure it was known about. I'll close this as it has already been addressed.
