### ISSUE TITLE
Error when key (not skeleton) created with /giveme is right clicked on locked chest

### ISSUE THREAD

**Issue by saavedra29** [minetest/minetest_game#1655]
When i create a key with the /giveme command of course it doesn't have a chest assined to it so throws the error:
` "ServerError: Lua: Runtime error from mod 'default' in callback item_OnPlace(): ...hare/minetest/games/minetest_game/mods/default/nodes.lua:1770: attempt to index local 'key_meta' (a nil value)"   `
and crashes.
Would it be better if this error was silently ignored?

**Comment by octacian** [comment]
This was fixed 3 days back by #1641 - update MTG.
