### ISSUE TITLE
Some leaves not decaying in special cases

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1656]
**Update:**
Leaves are not decaying (probably) because I blocked brunch and upper trunk growth with ladders, as a result leaves around them are not registered for decay. That means user altered trees can have partial decay of leaves.

**More in detail below:**
I was testing various tree farms, and discovered some leaves are not decaying.
Here is the test farm I made consisting of ladders.
![default](https://cloud.githubusercontent.com/assets/16494741/24085034/46e409e2-0cfd-11e7-9172-ae59c5bbd309.png)
Now, after wood removal:
![default](https://cloud.githubusercontent.com/assets/16494741/24085063/aef59398-0cfd-11e7-807f-0eaa0554b167.png)

Here is deeper look (tree growth from right to left, made saplings grow very fast after planting). 
If I remove wood from those - they decay fine:
![default](https://cloud.githubusercontent.com/assets/16494741/24085087/0772a5d8-0cfe-11e7-9771-049087605b06.png)

**Comment by MarkuBu** [comment]
I assume you use the latest dev of Minetest and MTG with the new leaf decay. What you are doing there is really strange

With the old ABM based leaf decay the left over leaves would decay before you cut the trees because they are out of the leaf decay range

**Comment by Fixer-007** [comment]
I know why it is not decaying.

**Comment by Fixer-007** [comment]
@MarkuBu I figured out the reason, reread first message :)

**Comment by paramat** [comment]
This will only happen rarely and is not a big problem, when it happens players will just have to dig the leaves.

**Comment by MarkuBu** [comment]
The ladders shouldn't be a problem. Only the distance between the top most trunk and the leaves. Other nodes can't block the decay

**Comment by paramat** [comment]
Yes the radius here is 3, we will not want to increase the radius for rare cases like this.

**Comment by Fixer-007** [comment]
@MarkuBu thats not nodes blocking decay, thats ladders blocking generation of upper trunk and branches leading to only partial decay, since there is only 2 wood blocks generated, it is expected.

**Comment by MarkuBu** [comment]
Just increase leaf decay radius

**Comment by Fixer-007** [comment]
Not always good solution in some cases.

**Comment by MarkuBu** [comment]
Yes, a lot of leaves won't decay if one trunk node is left

But you can edit the leaf decay function, but I can tell you tomorrow first what you need to edit

**Comment by Fixer-007** [comment]
I understand that increasing the radius helps with this, @paramat thinks it is not needed.

**Comment by paramat** [comment]
Blocking trunk nodes from being placed when a sapling grows will be rare and a silly thing to do, there's no justification in making the search much larger just for this case, players will just have to dig the leaves :]

Radius from 3 to 7 (needed to cover all casei)s a huge increase in searched nodes, when players are digging trunks at 1 per second this makes the code significantly more intensive. Then every leaf within the radius has a node timer started and then each does it's own search.

**Comment by sofar** [comment]
Consider it a feature, I think we shouldn't worry about this.

**Comment by paramat** [comment]
So you can see how essential it is to minimise the radius, and a very large radius would be needed to avoid this rare and minor problem, so closing.
