### ISSUE TITLE
Grass turned into dry shrub on dirt with grass

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1657]
Update: probable explanation, since ABM was close to insta, plant generated on mapblock above while dirt was on ungenerated mapblock, that caused turning it into shrub.
![default](https://cloud.githubusercontent.com/assets/16494741/24103323/942fa668-0d87-11e7-9992-b4204d8a8097.png)

**Comment by Fixer-007** [comment]
Decided to reopen the issue since I've discovered those shrubs on actual server too, this needs some mitigation (Hometown server, coordinates above), shrubs appear at certain level in pretty long stretches of land.
![default](https://cloud.githubusercontent.com/assets/16494741/24210816/efa8bb22-0f32-11e7-90c9-1cbd15ba634a.png)

**Comment by paramat** [comment]
PR #1660

**Comment by ExeterDad** [comment]
Is this what's going on inside of flower pots as well? Kibbie was livid with me after last nights pull. Did the same on our dev server as well.

**Comment by paramat** [comment]
Might be, are flower pots a separate node? perhaps add 'soil = 1' to their groups.

**Comment by paramat** [comment]
Previously flora would only turn to dry shrub in desert sand, now any non-soil node will do this.
Hmm maybe this will cause problems.

**Comment by paramat** [comment]
Changed PR to avoid breakage, sorry about that.

**Comment by paramat** [comment]
So now it simply 'returns' if no group:soil node is found below, which is the original behaviour. We don't need to change things to dry shrub anymore, the shrub is not a dead plant just a different plant.

**Comment by paramat** [comment]
#1660 merged.
