### ISSUE TITLE
Show messages from bed above the hotbar (and other requests)

### ISSUE THREAD

**Issue by WSDguy2014** [minetest/minetest_game#1659]
If you right-clicking on bed, if it's daytime, will show a chat message, i don't like it. Improve message like this:
![screenshot_20160828_230727](https://cloud.githubusercontent.com/assets/13905392/18047749/1970fac0-6de7-11e6-9111-2f68930e5002.png)

If you standing on 4 blocks away from the bed and right-clicking, if it's night time, will show a message:
![screenshot_20160828_231044](https://cloud.githubusercontent.com/assets/13905392/18047764/26862190-6de7-11e6-882f-4ba04a610407.png)

Because, player will set a spawnpoint 4 blocks away from bed. Too far away.

Must be very closer to the bed, and then right-click to sleep. Showing marking with torches, closer to bed, to detect a player, to sleep:
![screenshot_20160828_231159](https://cloud.githubusercontent.com/assets/13905392/18047777/32ae55c8-6de7-11e6-8f6b-4d323dd04d07.png)

This feature based on Minecraft: https://www.youtube.com/watch?v=3GrPWuLmjn4&t=1m10s (Stop watching video at 1:20)
https://www.youtube.com/watch?v=9qRRQBCWDvw&t=3m28s (Stop watching video at 3:34).

Also, add the code for bed:

`if_player_sleeping:true` - Player detects if sleeping on bed. Because, it's used to prevent another player sleeping on occupied bed (If player is sleeping), using a glitch.
`if_player_sleeping:false` - Player detects if it's not sleeping on bed.

**Comment by MarkuBu** [comment]
I agree. I don't like the chat messages too

**Comment by rubenwardy** [comment]
This is also an issue with the engine - it should add a single api for this which takes into account multiple messages being shown as once. Would be nice if "fly enabled" etc could also use this, but that's a client side message.

I agree that the chat is an easily missed place to put it

**Comment by sofar** [comment]
@nerzhul +CSM?

**Comment by rubenwardy** [comment]
Csm isn't the solve all solution to everything

**Comment by matt8fr** [comment]
Can be applied on other mod message who spam the cat as worldEdit.

**Comment by paramat** [comment]
> If you right-clicking on bed, if it's daytime, will show a chat message, i don't like it. Improve message like this:

-1 Chat is the expected place for messages, only engine does otherwise.

> Must be very closer to the bed, and then right-click to sleep. Showing marking with torches, closer to bed, to detect a player, to sleep:

-1 This is determined by player-node interaction distance, it's not worth customising this in the engine just for this request.

So i assume this request is for this;
```
Also, add the code for bed:
if_player_sleeping:true - Player detects if sleeping on bed. Because, it's used to prevent another player sleeping on occupied bed (If player is sleeping), using a glitch.
if_player_sleeping:false - Player detects if it's not sleeping on bed.
```

**Comment by paramat** [comment]
@WSDguy2014 
```
Also, add the code for bed:
if_player_sleeping:true - Player detects if sleeping on bed. Because, it's used to prevent
another player sleeping on occupied bed (If player is sleeping), using a glitch.
if_player_sleeping:false - Player detects if it's not sleeping on bed.
```
I don't understand the request, sorry.

**Comment by Ferk** [comment]
> Because, player will set a spawnpoint 4 blocks away from bed. Too far away.

Are you sure this is the case? By checking at the code it seems the player gets its position set to be next to the bed before setting any spawnpoints, so in theory the spawnpoint is always right next to the bed, not 4 blocks away.

Remember that things in Minetest don't work like in Minecraft, including MC-specific glitches. Copying Minecraft is not an MTG goal.

**Comment by benrob0329** [comment]
Moving notifications out of the chat would be a big improvement IMO, servers with lots of chat make if difficult to see notifications if in chat as they can scroll by very quickly. This would also have the added benefit of allowing players to turn off chat while still seeing notifications, something you cannot do now.

**Comment by paramat** [comment]
You could add an engine request for that.

**Comment by paramat** [comment]
No response, closing.
