### ISSUE TITLE
[Revamp] We need a direction for Minetest Game

### ISSUE THREAD

**Issue by XtremeHacker** [minetest/minetest_game#1672]
First of all, yes, #1485 Does say almost the same thing, but I made this issue for two reasons
1: That issue is giant, and hard to understand due to so many replies, making it hard to remember what everyone said
2: I have so new ideas, and want to give my interpretation of some existing ideas.

We seem to have a large problem, Minetest Game lacks a real direction, "But there is a dev roadmap, why are you saying we have no direction?"
Let me explain.

 Minetest Game started out as a modding base, not much other then that, and for other games, we had subgames such as Dreambuilder, BFD - Big Freaking Dig, and Carbone NG, and others; but now Minetest game is looking more like a game (but not enough to be called an actual game), and many subgames, how to fix it, with a modding base, AND a game, nope.

Let me give a little history lesson:
 You see games came out, and some people wanted to add new content, mechanics, or even change the 
 whole game, they did so with modifications, known nows as simply, "mods".

The whole point of a mod is to add content to a game, so why would you have a modding base, **and** a game???
Makes no sense does it, and yet that is what some people want.
Q: "But XtremeHacker, without a modding base, we have nothing to start our own unique alien rocketship-chasing cowboy subgame!!!!!"
A: Let me ask you a question to help ansrwer yours, what is minetest_minimal?
 A: It's a minimal subgame for people like you, and as for it being to minimalistic, then just strip Minetest 
 game down, or add Minetest game content to your own game base made from minimal.

Q: But why do that when we can have a simple modding base, and also have an actual game?
A: Easier for Minetest game developers, It's much easier for you to remove what you don't like from MTG (Minetest Game), then have two forks of what is basically the same thing.

Q: You titled this "We need a direction for Minetest Game", but you haven't given your thoughts on a direction!
A: True, true, my idea for a general direction is below.

My take on what Minetest Game's direction could be

Setting:
Minetest game is a mix between 1800s America, Medieval Europe, and the later 1900s explaining why we A; have wheels, but [could] also have B; Mesecons.
P.S. If we wanted, we could have an optional progression throught time, i.e. Middle ages --> 1800s --> 1900s, etc

Atmosphere:
I think as for atmosphere, a fatnasy-like eniroment would be a good fit, giving us the freedom to have fiction creatures, (i,e Dungeon master, oerkii), and before you say it, no I don't think we should have zombies/mummies/skeletons/etc, why?  Too many zombies-in-everything games, they are just a weird creatures that makes less sense then a teleporting creature (it rose back to life for yout to ill it :3).

Blocks, items, tools, and weapons
 Blocks: Concrete, stone, cobblestone, brick, sandstone, logs/wood planks, TnT, Furnaces, crafting benches, and more
 Items: TnT (Yes, I said TnT in blocks too, but it is not only a building material), Furnaces, signs, torches, 
 lamps/lights, etc.

Weapons :
 Broadsword: When attacking a mob (player, or otherwise), it deals 10% damage to other 
 mobs within 1 block of the mob you attacked in the first place, deals less damage then rapier, due to it 
 being a a **broad**sword also has lower durability then rapier 
 (below) due to the "sweeping" attack
 Rapier: Deals more damage then Broadsword, but only is able to hit one mob at a time, period, also has 
 higher durability.
 
Tools:
 Axe: Cuts down trees faster then using your fist
 Pickaxe: Able to mine ores, and stone/stonelike nodes
 Shovel: Digs dirt/dirt-like nodes faster then fists
 
Please keep this comment with constructive criticism, 
 "XXX  Ideas sucks is both useless for information, rude, and also just rude thus stirring up flame wars.
If anyone has ideas better then these, I'll add them to mine/change mine if needed.
Now, let the discussions begin! :)

**Comment by C1ffisme** [comment]
> The whole point of a mod is to add content to a game, so why would you have a modding base, and a game???

You know, I think I can agree with this. Sure, a modding base is great, and maybe it provides people with resources in the form of functions, variables and other code snippets, but much better would be to document these functions, and possibly give examples through minimal, or just through very good documentation.

Minetest Game should be modifiable, but firstly playable.

**Comment by XtremeHacker** [comment]
@C1ffisme Thanks, that is right, MT Game is supposed to be just that, a game, Minimal is for making different games, or just remove the stuff that you don't like from MT Game.

**Comment by tenplus1** [comment]
+1 ... Minimal should indeed be a base for server owners and modders to build onto, and it would be amazing if a [game] tab was added to the menu so that players could see what other games are available and download to play.

**Comment by XtremeHacker** [comment]
@rubenwardy I admit that this seems to be a duplicate, but this issue is different, by combining other peoples ideas, and also the last issue had gotten to being so long, that finding ideas that were good in the whole thing was a mess, making the chance of new people participating low due to not knowing wether what they want to say, was already said.

If we could somehow add this information to the first issue that this one is very similar too, that is OK.

**Comment by paramat** [comment]
There's also #515 they might be long but it's best to add to those.
This thing about lack of direction has been discussed already, we are working on MTGame to move it towards being a more complete game, it has a direction.

**Comment by DS-Minetest** [comment]
Please remove the `Possible close` label since it is already closed.

**Comment by C1ffisme** [comment]
> A modding base will probably be a new subgame.

This is, in a sense, what the issue is against.

We can make MTG into a great game, but then nobody will want to play the modding base, because it's most likely minimal and boring. Even with mods, it would just feel like playing modded Minetest right now.

Better than that would be to have Minetest Game still be moddable, but prioritize fun, enjoyable (as well as immersive) and well balanced gameplay over all else.

**Comment by paramat** [comment]
It's possible that we won't develop MTGame excessively and that it remains a reasonable modding base.

**Comment by rubenwardy** [comment]
continue in #1485 and #515
