### ISSUE TITLE
Commit 077316b extra character on line

### ISSUE THREAD

**Issue by t0ny2** [minetest/minetest_game#1674]
Commit 077316b has added a "+" character at the beginning of line 96 in mods/carts/cart_entity.lua

**Comment by paramat** [comment]
Will fix.

**Comment by paramat** [comment]
#1675 merged.

**Comment by SmallJoker** [comment]
Oh sorry for this mistake. I haven't noticed it while merging. Thanks for the quick fix, @paramat :)
