### ISSUE TITLE
Very unresponsive creative inventory

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1680]
I've installed newest craftguide mod by jp and newest cottages mod by Sokomine, created new world in creative, creative window was very slow, search, page change and tool transfer were noticeably slow. 
I believe this happened with other mod cases to me earlier, max_lag was 0.5. World restart solved it, but it seems it is random each time. Engine minetest/fbc1432 with same time minetest_game
**Also happens in vanilla minetest_game** with good luck.
To reproduce you need to try restarting world until you get slow creative inventory.

This need investigation.
Demo (seems faster in gif than IRL):
![hasturnedtostone](https://cloud.githubusercontent.com/assets/16494741/24564100/69e8dfd4-1659-11e7-8391-52b405f4cd86.gif)

**Comment by rubenwardy** [comment]
Will attempt to reproduce

**Comment by Fixer-007** [comment]
Not always, it feels like like some sort of rhythmic queue with bottleneck to me.

**Comment by HybridDog** [comment]
The page switching is handled server side. When you click on the arrow you need to wait until the formspec button press is sent to the server, then you need to wait until the server has time to consider your request, after that you need to wait until the next formspec page is sent to you.
So you could greatly increase the amount of items shown in the formspec (try unified inventory) or
you could make creative a client side mod (you somehow need to make players install that mod) or
you could add inventory page flipping to formspec source code (l doubt they'd merge such a PR).

**Comment by paramat** [comment]
I restart worlds often in creative mode and have never experienced this, does it happen in singleplayer or when on a server or both?

**Comment by HybridDog** [comment]
It happens on both, usually on a laggy server.

**Comment by Ezhh** [comment]
The only server I experienced something like this on is Xanadu, even when the server itself seems otherwise completely playable. It doesn't seem to be icon related since the same delay is present for any page change, not just when loading a page the first time. Even working with the admins there, I've never been able to figure out the cause and other people seemed to have no problems at the same time that I did.

On every other server I play on, and any locally hosted game I run, this doesn't happen.

**Comment by paramat** [comment]
> Also happens in vanilla minetest_game with good luck.

I've never experienced this in vanilla MTG, has anyone else?
The other behaviour is probably due to craftguide mod or laggy servers.
Will close in 1 month if no reproduction by others in vanilla MTG.
