### ISSUE TITLE
Request: Bush seedlings

### ISSUE THREAD

**Issue by QwertyDragon** [minetest/minetest_game#1684]
Bush leaves give seedlings so bushes can be planted like trees.

**Comment by paramat** [comment]
Yes this is something we need to consider.

**Comment by Fixer-007** [comment]
Their leaves are good for decor, yet those bushes are quite rare and impossible to grow.

**Comment by tenplus1** [comment]
Why not place the bush stem and it randomly grows a bush block around it.

**Comment by twoelk** [comment]
maybe do it like the bushes_classic in the plantlife_modpack and use shovels to replant bushes?

**Comment by paramat** [comment]
I'd rather do it with saplings.

**Comment by twoelk** [comment]
to clarify, the suggestion would be:
punch bush with showel = bush is taken from map, player gets replantable bush or seeds or sapling
punch bush with fist = bush is not destroyed, player gets whatever can be harvested
punch bush with axt, pick, sword, etc. = bush is destroyed, player gets sticks

**Comment by paramat** [comment]
I see, will consider, thanks.

**Comment by paramat** [comment]
#1698 merged.
