### ISSUE TITLE
Screwdriver can't rotate blocks not "facedir"

### ISSUE THREAD

**Issue by thePalindrome** [minetest/minetest_game#1690]
A mod I work on defines separate blocks for rotated versions of stairs in order to make the texture align properly. Given that the screwdriver defers to on_rotate, I see no reason to limit custom rotations to nodes that have paramtype2 being "facedir"

A suggested modification comes to line 38 from
`if not ndef or ndef.paramtype2 ~= "facedir" then`
to
`if not ndef or (ndef.paramtype2 ~= "facedir" and ndef.on_rotate) then`

This allows blocks with custom rotation to be rotated with the screwdriver ( as well as allow mods to interpret the screwdriver in non-rotatating ways)

**Comment by Ferk** [comment]
Isn't that already what should be happening?

I don't find the line you reference to.
https://github.com/minetest/minetest_game/blob/077316b4cd7558eda03e6d3df631ee3aa27bff11/mods/screwdriver/init.lua#L108-L109

**Comment by thePalindrome** [comment]
My original comment was for the 0.4.15 version of screwdriver, but my point still applies, because if param2 isn't the right type it bails early. #1691 will fix this

**Comment by paramat** [comment]
#1691 merged.
