### ISSUE TITLE
[Feature Request] Use full (with keys reachable) hud slot size and resize inventory to 10x4

### ISSUE THREAD

**Issue by LNJ2** [minetest/minetest_game#1701]
The Minetest engine supports the keys 1-0 for the hud slots 1-10, I think we should use them. It would be very practical to reach more items without having to open the inventory, moving the mouse and clicking minimally three times to move an item from the inventory to the hud slots. If you have all basic tools, one stak torches and one stack for food, you already have 6 of 8 slots in use (and that without a hoe or a screwdriver). So there are only two slots left for any other nodes or items to use for building or other activities (e.g. rotating nodes, searching a crafting guide, etc.).

The engine already supports this improvement, so we should use it.

**Comment by C1ffisme** [comment]
This means that our inventory has 40 slots, which makes it a bit easier to calculate how many items you have. (Combine that with say, increasing the default max stack size to 100, and it becomes really easy to count items.)

**Comment by DS-Minetest** [comment]
This really sounds great and very useful but every other formspec will have to be changed, too.

**Comment by C1ffisme** [comment]
@DS-Minetest That's not too bad of a problem, unless you have a mod that uses a lot of formspecs.

**Comment by sofar** [comment]
Well, all of sfinv relies on the current inventory length, so, all the minetest_game forms would need fixing, as well as resizing the player inventories.

**Comment by LNJ2** [comment]
I'd like to work on a PR for this, but unfortunately I'm currently busy. If nobody else does this, I'll probably do this in some weeks.

**Comment by dsohler** [comment]
> Well, all of sfinv relies on the current inventory length, so, all the minetest_game forms would need fixing, as well as resizing the player inventories.

... aaaand?

**Comment by LNJ2** [comment]
> ... aaaand?

This has to be done.

**Comment by dsohler** [comment]
> This has to be done.

And this is where the developers come in.

**Comment by rubenwardy** [comment]
Sfinv should be made to handle arbitrary sized formspecs, but due to formspecs it'll be a pain to implement

**Comment by paramat** [comment]
👎 lots of work but also consequences for chest inventory size and mods that assume the current inventory size. I can't see a good enough reason to do this.
