### ISSUE TITLE
Torches are not instamined anymore

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1706]
You have to hold mouse for friction of second to mine the torch, it is quite annoying.

Probably because of this https://github.com/minetest/minetest/commit/858c72297409ca54092c3c908279d2a05fef58cd

**Comment by Fixer-007** [comment]
I'm probably made a mistake filing it under MTG.

**Comment by Fixer-007** [comment]
Wonder if this is related https://github.com/minetest/minetest/pull/5558

**Comment by paramat** [comment]
Yes it's engine 5558.

**Comment by paramat** [comment]
PR https://github.com/minetest/minetest/pull/5652
