### ISSUE TITLE
Dye crafting conflict

### ISSUE THREAD

**Issue by cheapie** [minetest/minetest_game#1710]
Both brown and dark_grey dye have the same shapeless crafting recipe (red+green dye) registered. See lines 84 and 92 of mods/dye/init.lua.

**Comment by paramat** [comment]
We have 4 for 'dark grey' and 2 for 'brown' so i suggest removing the 'dark grey' recipe.

**Comment by sofar** [comment]
https://github.com/minetest/minetest_game/blob/master/mods/dye/init.lua#L84

**Comment by sofar** [comment]
paramat: +1 to a one-liner that removes that one line, please go ahead and merge without a PR if you're inclined to do so.

**Comment by paramat** [comment]
Ok.

**Comment by sofar** [comment]
ae7206c0064cbb5c0e5434c19893d4bf3fa2b388
