### ISSUE TITLE
Book Erasure...

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest_game#1711]
When reading a book by another player, clicking the < and > buttons at bottom of formspec somehow erases the book ?!?!

**Comment by rubenwardy** [comment]
I can't reproduce this. What engine version are you using?

**Comment by tenplus1** [comment]
latest 0.4.15 on server

**Comment by rubenwardy** [comment]
Do you mean latest dev?

Please may you give a series of steps to reproduce?

I made a book with a lot of text, gave it to another player, clicked the arrows, and the text was still there. I dropped it, edited it again, read it again, no changes.

**Comment by tenplus1** [comment]
I had one of the players write me a book, I then read the book and clicked the < and > buttons at bottom of formspec and book erased itself.

**Comment by sofar** [comment]
Confirmed.

Book made with player 1, added several pages of `asdfg`
Book put into chest
restarted server with player 2
Picked up book, opened it (page 1/N)
clicked `>`

expected: 
book page 2 shows

actual:
empty book content edit formspec shows
escaping the form does not restore content

**Comment by ExeterDad** [comment]
I can also confirm. Opened a book left in a mailbox. I read the message. Clicked the right page arrow in case there was a second page,  and the book went clean as new. No turning back, the message was gone.

**Comment by sofar** [comment]
Root caused, PR incoming.
