### ISSUE TITLE
Ownable Doors are useless, i can just destroy the blocks around it

### ISSUE THREAD

**Issue by alugarius** [minetest/minetest_game#1712]
I suggest building blocks with protection like a chest.
Example crafting, Woodplanks + Iron Ingot (or a seperate "lock" item) = Locked Woodplanks...

Same for steel and stone blocks.

Else you should remove the ownable doors becouse its just not useful anyhow

**Comment by Fixer-007** [comment]
Yeah, it is useless in default game, unless you build your house of out locked chests, locked door is useful on modded servers that has a protection mods.

**Comment by stujones11** [comment]
> locked door is useful on modded servers that has a protection mods.

Except that you can walk straight through them :p #954

**Comment by paramat** [comment]
We're not going to remove locked doors obviously.

**Comment by alugarius** [comment]
@paramat then i recommend an ownable blocktype...

becouse i dont want to build an house made of locked chests

**Comment by NathanSalapat** [comment]
I don't understand how this is an issue, if you're playing locally there is no reason you wouldn't be able to open your door. If you are playing on a server you should be using a protection mod to keep those blocks from being broke. If the server doesn't have a protection mod maybe you should find another server. :)
@stujones11 Tenplus1's protection mod flips a player backwards when they try to break a node they don't own, preventing them from being able to glitch through doors or walls.

**Comment by paramat** [comment]
We already have ownable nodes, it's called protection, it can be configured in any way using a mod.
It would be too expensive to have every individual node store metadata containing the owner, and we cannot double the number of nodes to have unbreakable versions.

**Comment by sofar** [comment]
This isn't a bug, nor is it an issue. Please close. 

We've accepted the fact for a long time that minetest_game contains some level of protection and/or ownership, even though those mechanisms are missing from other nodes. The simple reason is that the choice was made, conscientiously, to not include a protection mod. 

This has been a wise choice if you ask me. If I had to choose a protection today, I would not be able to be happy about my choices, and I think that we shouldn't make the choice until everyone agrees on a single solution being the best, and, it's unlikely to happen any time soon.

(Note that the solutions are not all bad, they're just not *ideal*. I don't like floating protection blocks in the air for instance, but I also dislike working with markers, anyway, that is offtopic here).

**Comment by paramat** [comment]
Comment by sfan5 http://irc.minetest.net/minetest-dev/2017-04-26#i_4898979
So closing.

**Comment by Fixer-007** [comment]
Here is the idea: new kind of key (that lasts for say 100 uses) that protects _any_ block.

**Comment by DS-Minetest** [comment]
@Fixer-007 Ehm a key for what lock?

**Comment by sofar** [comment]
@Fixer-007 doesn't solve the awkward user interface, but, keep thinking (in a forum thread, perhaps?)
