### ISSUE TITLE
What is default:cloud for?

### ISSUE THREAD

**Issue by bigfoot547** [minetest/minetest_game#1714]
Or what was it for before, when it was added?

**Comment by sfan5** [comment]
IIRC it was never actually used and just ported alongside with moving all content to Lua

**Comment by paramat** [comment]
When we last considered removing it we could not, as some servers use it.

**Comment by bigfoot547** [comment]
In that case, what is `default:dirt_with_grass_footsteps`?

**Comment by paramat** [comment]
Early MT had footsteps added where players walked, this feature was removed, but since some worlds and servers still have this node it was kept.

**Comment by tenplus1** [comment]
The default:cloud block is used by many admin to build areas that cannot be dug by any player apart from admin (if they have a tool).

**Comment by bigfoot547** [comment]
> Early MT had footsteps added where players walked, this feature was removed

When and why was this feature removed?

**Comment by C1ffisme** [comment]
@tenplus1 
> The default:cloud block is used by many admin to build areas that cannot be dug by any player apart from admin (if they have a tool).

Erm... Then why don't we have a tool for this in the default game?

**Comment by tenplus1** [comment]
@C1ffisme - probably so that players cannot cheat the tool into their inventory and run amok by removing all sorts of blocks they dont own...  Mod tool only.

**Comment by paramat** [comment]
This is best kept to the forum.
