### ISSUE TITLE
Lava shouldn't be affected by the waving shader

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest_game#1721]
Lava shouldn't be effected by the waving shader for two reasons:

1. It doesn't makes sense that lava waves like ocean water
2. If the waving shader is active the lava is lower than normal and is not visible on the most outer nodes. Then you walk on these nodes because you think it is save and die

If I walk on the node I am pointing I will die

![screenshot_20170502_163109](https://cloud.githubusercontent.com/assets/16163058/25622474/cc4ad3e4-2f54-11e7-8352-09d38697f4a2.jpg)

**Comment by paramat** [comment]
Sorry it is an engine issue.
