### ISSUE TITLE
[Feature request] Change stack size from 99 to 96

### ISSUE THREAD

**Issue by XtremeHacker** [minetest/minetest_game#1724]
Why?:  Because you can't divide 99 equally, as for changing it to 100, that would work, but you 96 is a number that can be halved over & over, without any "leftovers"

**Comment by raymoo** [comment]
102 divided by two is 51 so you can only halve it once.

**Comment by XtremeHacker** [comment]
Whoops, you're right.
Looks like 96 is a good number.
As for backwards compatibility, even if the max number of a stack is there, it only limits how much you can collect and store, existing stacks of 99 will still be 99.

**Comment by paramat** [comment]
:-1:

**Comment by XtremeHacker** [comment]
I was just thinking it makes inventory related shenanigans easier, I do admit though that I don't know how many/if people would actually want this, only that I personally do.

**Comment by octacian** [comment]
I think that this can be configured using a setting in `minetest.conf`. Check the example `minetest.conf` files here in the repository. Maybe not though. Also check the Lua API (sorry, too lazy to do myself).

Also, you should update the OP and change the title of this issue. On the concept of changing to 96, I'm personally neutral. It could be a great improvement as one wouldn't have to deal with leftovers when writing more complex inventory-related mods.

**Comment by paramat** [comment]
Sorry changed my attitude to this, not opposed.
I must admit 99 is not a nice number, and 96 can be divided many ways into 3s and 2s, so it gives me 'numerical satisfaction'. But then i have a bias towards 2^n and 3*2^n numbers.

**Comment by sofar** [comment]
Just leave it as is for now. After the release we can pick a strategy perhaps.

**Comment by rubenwardy** [comment]
Needs engine support as there's no good way to set a default stack size

**Comment by Fixer-007** [comment]
Here is my idea, use 72, it divides nicely:
![default](https://cloud.githubusercontent.com/assets/16494741/25772343/5b8ad530-3271-11e7-85db-4131aff86ec8.png)

**Comment by MarkuBu** [comment]
You can set a max stack size, but didn't work for all items.

I still support a stack size of 72. It is a perfect number to split stacks. You can split it to two stacks, four stacks or nine stacks without a rest. 

I also think it would be good to increase the player inventory. Than you can carry **more different** items. Currently the inventory is 8x4, so 32 different items. I think 9x5 would be better. 

currently you can carry 3168 items. With 9x5x72 it would be 3240, a little bit more than now and 45 different items

Nevertheless, it should be possible to set a global max stack size for all items

**Comment by MarkuBu** [comment]
@Fixer-007 LOL, that was synchronous

**Comment by XtremeHacker** [comment]
Hmm, even better would be if a sub-game/mod could define the max size, I don't know if that is possible, but it would mean that different subgames/mod could have the stacksize set to what they want, which probably makes more sense then "forcing" one size via the engine.
Thoughts?

**Comment by MarkuBu** [comment]
It is possible to change the max stack size, as I mentioned. But not for all items. Dyes for example can be stacked to 99, even is max stack size is different

**Comment by DS-Minetest** [comment]
Hm, wouldn't players think, that new stacks wouldn't be filled up to the limit?

**Comment by dsohler** [comment]
`Engine change needed`? Really?

I mean. Even a simple two line mod can change the default stack size for pretty much all items/nodes (except some of the hardcoded values that ignore the `stack_max` value of the items/nodes).

I don't see why that needs an engine change.

**Comment by MarkuBu** [comment]
> I don't see why that needs an engine change.
Because there are some hardcoded items?

**Comment by dsohler** [comment]
Making hardcoded items configurable (or, not even that. It only would be fixing the bug that the function does not respect `stack_max`) count as engine change? To me an engine change to would be something fundamental, like properly flowing liquids, or proper lighting.

Making hardcoded values respect a per-node configurable default value is a bugfix, to me, not an engine change.

**Comment by MarkuBu** [comment]
Engine change is everything that has to be changed in the minetest code (not minetest game). And to change the max stack size for example for dyes has to be done in the engine, because stack_max is ignored by dyes and can't be changed by a mod

So, engine change needed!

**Comment by dsohler** [comment]
So it's only another word for "not in our scope" (where "our" is `minetest_game`)? Okay, makes sense then.

**Comment by rubenwardy** [comment]
> Engine change needed? Really?

Yep. There's no way to set a default stack size if items have already be registered, so we need engine support for this. You could hack it and override all 99 stack maxes, but that's a hack.

**Comment by XtremeHacker** [comment]
OK, issue created for Minetest Engine here: https://github.com/minetest/minetest/issues/5730

**Comment by dsohler** [comment]
> There's no way to set a default stack size if items have already be registered

You can always change the individual stack size for registered stuff which works in most cases.
