### ISSUE TITLE
Unable to load texture for default chest.

### ISSUE THREAD

**Issue by enkidu-smith** [minetest/minetest_game#1725]
The actually error message is 
`ERROR[Main]: generateImage(): Could not load image "default_chest_top.png" while building texture`

After looking at this for a bit, I found that the file did not exist so far as I could find. The following two files do exist.
```
default_chest_wood_locked.png
default_chest_wood.png
```
In an old backup I found the following files
```
default_chest_front.png
default_chest_lock.png
default_chest_side.png
default_chest_top.png
```
There was a commit about four days ago which may have a bearing on this. On the other hand, it could be possible that I have done something silly (probably related to 'git'), but I have not deleted or moved the missing file!

Client is 0.4.15-dev-de028fc and the server is the same.

**Comment by DS-Minetest** [comment]
The one texture for the new chest makes more problems than thought eg. also the crack is now very ugly.

**Comment by tenplus1** [comment]
Indeed, the new chest additions causes many problems for current mods and game.  Older textures should still be included for compatibility.

**Comment by enkidu-smith** [comment]
OK, thanks. Is this an issue which needs to be addressed here (for the game) or in the mods too?

**Comment by tenplus1** [comment]
Hopefully the textures will be re-added for compatibility and with suitable warning and time the mods themselves will use different/standalone textures to suit.

**Comment by SmallJoker** [comment]
Created a PR for this one: #1729

**Comment by enkidu-smith** [comment]
The original error has been fixed, so I guess I should close this now. However the PR [#1729](https://github.com/minetest/minetest_game/pull/1729) is ongoing as the textures are still not correct.
