### ISSUE TITLE
New flower name?

### ISSUE THREAD

**Issue by cx384** [minetest/minetest_game#1734]
White Dandelion:
![white](http://wiki.minetest.net/images/thumb/8/84/White_Dandelion.png/40px-White_Dandelion.png)
Yellow Dandelion:
![yellow](http://wiki.minetest.net/images/thumb/e/ed/Yellow_Dandelion.png/40px-Yellow_Dandelion.png)

I think the textures of white dandelions and yellow dandelions don't match with their names.
Options:

- change the texture of white dandelions

- rename white dandelions

Some possible names: `chamomile,` `daisy`

**Comment by C1ffisme** [comment]
I'm happy with `daisy` because it seems like a flower most people know about, like "rose" and "lily". (Although probably because they are so commonly used in people's names)

**Comment by paramat** [comment]
Well we should not rename, to avoid disruption and an alias.
The textures seem fairly accurate, maybe the yellow one can be smaller to match in size, and also occur in a small bunch.

**Comment by C1ffisme** [comment]
@paramat Actually, from personal experience, I think the textures are reversed. The white dandelion should be the lone, tall flower and the yellow dandelion should be several small flowers.

Also, at this level of definition, white dandelions shouldn't have a yellow core, they should just have a fluffy white ball as a flower.

[Google Images for "dandelion"](https://www.google.com/search?q=dandelion&client=ubuntu&hs=EYn&channel=fs&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi2rOfr6_DTAhUE-GMKHcOeCZYQ_AUICigB&biw=1600&bih=726)

(Actually, looking at Google Images, the core of a white dandelion shouldn't even be yellow, it's closer to dark green or even black.)

**Comment by paramat** [comment]
The fluffy ball is the seed phase, the flower itself has a yellow centre.
My feeling is to have these the same rough height, both bunches, and derive the yellow dandelion from the white dandelion texture.

**Comment by paramat** [comment]
PR #1749

**Comment by paramat** [comment]
#1749 merged. The textures do match the names well.
