### ISSUE TITLE
lava not cooling and cacti not growing...

### ISSUE THREAD

**Issue by theFox6** [minetest/minetest_game#1735]
If lava flows into water it doesn't cool down to stone, also cacti are not growing.
I already located the problem.
In minetest_game/mods/default/functions.lua after line 96:
```
minetest.register_abm({
     nodenames = {"default:lava_source", "default:lava_flowing"},
     neighbors = {"group:water"},
     interval = 1,
     chance = 1,
     catch_up = false,
     action = function(...)
        default.cool_lava(...)
     end,
})

```
The problem is, that if you use "..." as function argument, the variables given to the function, are put into a list called "arg".
Maybe this would be better:
```
minetest.register_abm({
     nodenames = {"default:lava_source", "default:lava_flowing"},
     neighbors = {"group:water"},
     interval = 1,
     chance = 1,
     catch_up = false,
     action = default.cool_lava,
  })

```
It is used in the same way for cacti and papyrus.

**Comment by Ferk** [comment]
Wasn't the on_flood callback merged? lava cooling should probably use that.

**Comment by paramat** [comment]
Lava cools for me.

**Comment by theFox6** [comment]
It doesn't work for me.
But it's better calling the functions directly, instead of calling a function that calls one of those functions.
I have created a pull request by now: [pull 1739](https://github.com/minetest/minetest_game/pull/1739)

**Comment by theFox6** [comment]
Maybe I have some old version or something. I don't know why it didn't work.
