### ISSUE TITLE
Allow reverse crafting of stairs and slabs

### ISSUE THREAD

**Issue by ForbiddenJ** [minetest/minetest_game#1737]
![stairs and slabs proportions](https://cloud.githubusercontent.com/assets/26123860/26164643/dd51cc8e-3af2-11e7-979e-53942d8ccb95.png)

As the image explains above, I noticed certain proportions when it comes to crafting. 8 stairs are made from 6 blocks and 6 slabs are made from 3 blocks. Although you can make a full block from two slabs one stacked on the other, the same is not possible with stairs.

Can you make craft recipes that can allow one to recombine slabs or stairs into blocks (like 4 stairs to 3 blocks)?

**Comment by tenplus1** [comment]
Already included in Stairs Redo ( github.com/tenplus1/stairs )

**Comment by XtremeHacker** [comment]
This would e a nice little touch, that helps the game feel a bit more "thought out".

**Comment by paramat** [comment]
2 slabs to a full cube makes sense as we can do that with placement already.
The stairs conversion might be ok too.

**Comment by Wuzzy2** [comment]
I had the exact same idea. :D

**Comment by paramat** [comment]
#1740 merged.
