### ISSUE TITLE
Stairs mod: Remove reversed MC stair recipe, or choose one of the two

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1741]
I'm thinking we should remove the reversed (for MC) recipe, we don't do this for any other recipe and players will soon learn the correct way. With the amount of stairs and slabs we now have it's just a large number of extra recipes registered.
We could even choose to use the MC recipe or whichever one is most used by players.

**Comment by dsohler** [comment]
Recipe orientation should match the orientation of the stairs in the inventory when using the default textures.

**Comment by NathanSalapat** [comment]
Sounds good, I didn't even know there were two recipes.

**Comment by C1ffisme** [comment]
@dsohler That's the one I use, and it makes sense, considering the idea behind crafting is to "draw" the item in the crafting grid.

**Comment by paramat** [comment]
> Recipe orientation should match the orientation of the stairs in the inventory when using the default textures.

Good idea.

**Comment by paramat** [comment]
Stairs rise towards the right.

**Comment by paramat** [comment]
PR #1758

**Comment by paramat** [comment]
#1758 merged.
