### ISSUE TITLE
Saving book with erased contents does not work

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1743]
If you have book with some text and erase it from contents and then save it, it will not save, instead, deleted text will reappear after reopening the book.

**Comment by paramat** [comment]
@sofar

**Comment by octacian** [comment]
From what I know, this is not necessarily a bug. Instead, it is a feature to prevent saving useless metadata to the book itemstack if no data is provided. I would suggest that a simple conditional be added to prevent saving if no `owner` is set, however, if an `owner` is set allow clearing the contents (but not title) or just clear the book meta entirely.

**Comment by ForbiddenJ** [comment]
This bug is real alright. Make a book with a bunch of random text in it's title and contents, save, then try erasing either field and save. When you open it again, you'll find that the field still has what you tried to erase.

**Comment by octacian** [comment]
No, I think that this bug should definitely be fixed. However, I don't have time to do it ATM. It just doesn't make sense as is. I see absolutely no problem with entirely clearing a book (title, contents). TBH, I see no problem with allowing contents and no title for that matter (after all, if you write a report/book IRL, you don't *have* to add a title).

**Comment by paanrama** [comment]
I have done a fix for this, I only have not decide yet if a default:book_written without title and text must be reverted to a default:book or no.

I want to do a pull request for it, but I don't know how to do it. Are there some instructions that I can read to learn how to do it?

If I can't do pull requests for minetest_game, the changes are in this file, so anybody who is authorized can do it.
[craftitems.zip](https://github.com/minetest/minetest_game/files/2130350/craftitems.zip)

**Comment by paanrama** [comment]
Don't worry, I found the info in the help.

**Comment by paramat** [comment]
Github help section -> Bootcamp.

However you are welcome to just provide code for someone else to merge.

**Comment by paramat** [comment]
PR suggests more discussion needed, i can't help much with this unfortunately.

**Comment by orbea** [comment]
I think this is fixed in PR https://github.com/minetest/minetest_game/pull/2646.
