### ISSUE TITLE
Add stair and slab for tin block

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1745]
... it was forgotten. I would like to see this in release also.

**Comment by NathanSalapat** [comment]
This would give tin more uses, as right now it can only be used for a block.

**Comment by C1ffisme** [comment]
What about using tin as a decorative metal for builds that need large amounts of metal-textured blocks?

**Comment by paramat** [comment]
I guess it should for consistency, although i find tin blocks ugly, will do for release.

**Comment by Wuzzy2** [comment]
> This would give tin more uses, as right now it can only be used for a block.

Correction: Tin has 2 uses: Crafting bronze ingots. And crafting the tin block.

**Comment by NathanSalapat** [comment]
Good point, missed that, when I searched creative inventory for tin. :P

**Comment by kingoscargames** [comment]
still almost useless

**Comment by paramat** [comment]
Very easy to do so who will?

**Comment by Wuzzy2** [comment]
Note that I added these blocks in `mtg_plus`:
http://repo.or.cz/minetest_mtg_plus.git/blob/334457267ae6b0c4bf2e62da98c084acfa59812e:/stairslabs.lua

```
stairs.register_stair_and_slab("tinblock", "default:tinblock", minetest.registered_nodes["default:tinblock"].groups, minetest.registered_nodes["default:tinblock"].tiles, S("Tin Block Stair"), S("Tin Block Slab"), minetest.registered_nodes["default:tinblock"].sounds)
```

**Comment by paramat** [comment]
#1822 merged.
