### ISSUE TITLE
Debug Menu Option

### ISSUE THREAD

**Issue by NathanSalapat** [minetest/minetest_game#1751]
When changing the debug log level options we have this screen, but the levels listed and the options available don't match.

![huh](https://cloud.githubusercontent.com/assets/8930456/26522601/b4cccfb4-42c9-11e7-8362-a567dd6df38c.png)

**Comment by rubenwardy** [comment]
This is a https://github.com/minetest/minetest issue

**Comment by NathanSalapat** [comment]
Sorry, I thought the game did the menu, but I suppose this is an engine menu, not game menu. :/ Will open issue in engine.
