### ISSUE TITLE
Digging wooden trapdoor makes white particles

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#1753]
When you dig a wooden trapdoor, the particles while digging or after digging, some of these particles have white components. That's odd.

Tested in 0.4.15.
And eec1c5a03bae544e5ac149d5affa2a1b5e229e31.

**Comment by DS-Minetest** [comment]
Probably the white parts of `doors_trapdoor_side.png` cause this.

**Comment by paramat** [comment]
The white parts of the textures could have wood texture instead.

**Comment by paramat** [comment]
#1762 merged.
