### ISSUE TITLE
Saplings don't grow on dirt with snow anymore

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#1755]
Saplings do not grow on dirt with snow anymore. Why?

It seems inconsistent since regular bushes (bush stem + bush leaves) can be found naturally in snowy biomes on top of dirt with snow.

eec1c5a03bae544e5ac149d5affa2a1b5e229e31

**Comment by paramat** [comment]
`groups = {crumbly = 3, spreading_dirt_type = 1, snowy = 1},`
Somehow 'soil = 1' is not here, should be fixed, it's just a thin layer of snow.
:+1:

**Comment by Wuzzy2** [comment]
Well, ok. I see the following alternatives:

Either dirt with snow is considered `soil` again.
Or bushes stop generating in snowy lands.
Or something completely different?! :D

**Comment by paramat** [comment]
I'll re-add the soil group. Bushes are needed in snowy grassland.

**Comment by paramat** [comment]
#1651 soil was removed from 'dirt with grass' for a reason to stop flora spreading into snow biomes. I decided we could consider this node to be partially frozen and in need of digging to turn it into dirt before planting a sapling.

**Comment by paramat** [comment]
Due to #2014 i will add the soil group again.

**Comment by Ekdohibs** [comment]
Notice we have a choice here -- either add dirt_with_snow to the soil group again, or make another group with it (snowy_soil or whatever thing like that) and make only pine saplings/some kind of bushes grow there (jungle trees growing in snow seem a bit weird).

**Comment by paramat** [comment]
I prefer keeping it simple, will add the group.
