### ISSUE TITLE
Main menu font is glitched

### ISSUE THREAD

**Issue by Profeet** [minetest/minetest_game#1759]
This happens on **every** version of minetest, except 0.4.10 at the first opening. And this isn't only on main menu, it's everywhere where text is. 

![capture](https://cloud.githubusercontent.com/assets/29172638/26759732/8c5715a2-490f-11e7-8f8b-78e571e3b2e3.JPG)
![fgdf](https://cloud.githubusercontent.com/assets/29172638/26759733/8fbf621c-490f-11e7-8c51-ef396aad7fd2.JPG)

**Comment by SmallJoker** [comment]
Please open this issue in the engine repository: https://github.com/minetest/minetest/issues/
This repository contains a subgame (pack) for the Minetest core.
