### ISSUE TITLE
Regression - overriding of default functions does not work anymore (lavacooling)

### ISSUE THREAD

**Issue by bell07** [minetest/minetest_game#1761]
The commit https://github.com/minetest/minetest_game/commit/e523c3a2965afe76b9102b67992e15fafba1594a breaks overriding of default actions by other mods. Before it was possible just to redefine the default.cool_lava to get custom cooling, now the default function reference is stored in ABM and not changeable anymore.
See: https://github.com/CasimirKaPazi/unternull/issues/7
Please revert this patch.

**Comment by sfan5** [comment]
@SmallJoker @paramat 
not trying to blame you, but if code does something in an unusual way it has a reason in most cases
though it was missing comments explaining why

**Comment by rubenwardy** [comment]
:+1: to revert

**Comment by SmallJoker** [comment]
The previous issue on this topic is unconfirmed and got somehow solved.
Creating a function to directly call another with the same arguments looked somewhat stupid but there is actually a reason for keeping them this way. I haven't noticed this problem back then and agree on reverting the commit.

**Comment by paramat** [comment]
:+1:

**Comment by paramat** [comment]
Ugh i should have checked to see why it was like that.
This is a severe breakage and i think deserves a MTG point release.

**Comment by paramat** [comment]
#1763 merged.
