### ISSUE TITLE
"No Suitable paramtype2" warning

### ISSUE THREAD

**Issue by AntumDeluge** [minetest/minetest_game#1766]
Not sure what the meaning of this warning is:

```
2017-06-07 20:16:59: WARNING[Main]: Node default:wood has a palette, but not a suitable paramtype2.
2017-06-07 20:16:59: WARNING[Main]: Node default:fence_wood has a palette, but not a suitable paramtype2.
```

Using *Minetest* server *0.4.16* with *minetest_game* mods from *0.4.16*.

**Comment by paramat** [comment]
Hardware colouring, which is unfinished @juhdanad

**Comment by juhdanad** [comment]
MTG does not use palettes, so a coloring mod causes the warning.
This warning is completely harmless, it just reminds the modders that their palettes will be ignored for that node.

**Comment by AntumDeluge** [comment]
Using [homedecor_modpack @5c52111](https://github.com/minetest-mods/homedecor_modpack/tree/5c52111).

**Comment by paramat** [comment]
Yes homedecor has implemented hardware colouring to a large degree, any more issues are probably best discussed with the author.
