### ISSUE TITLE
Point release due to important bugfix?

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1768]
0.4.16 was released with a significant bug #1761 , now fixed.
Perhaps since nothing of significance has happened since release we can make a point release?

**Comment by Fixer-007** [comment]
But 0.4.16 packages will still have outdated minetest_game :( They need to updated it too.

**Comment by dsohler** [comment]
Since SemVer is not used nothing's bad with 0.4.16.1 or 0.4.16a for example.

But changing something without reflecting this change in the version number is an absolute no-go regardless of SemVer or arbitrary numbers.

**Comment by paramat** [comment]
Since an engine point release is coming soon maybe wait until then?
