### ISSUE TITLE
Fallen Trees should be minimum 3 nodes long

### ISSUE THREAD

**Issue by IhrFussel** [minetest/minetest_game#1780]
Sorry but the fallen trees that are only 2 nodes long look silly.

I never saw a vertical tree with less than 3 trunk nodes.

**Comment by paramat** [comment]
If they were minimum 3 nodes there would be no length variation. We could avoid 1-long though.

**Comment by IhrFussel** [comment]
Wait there are ONE NODE long trees? Now that is just ridiculous...

The fallen trees should neither be 1 or 2 long

They should be 3, 4 and 5 long just like regular vertical trees or else it will not look authentic at all.

**Comment by paramat** [comment]
They can't be longer than 3 for a reason.
Logs decay and break so partial logs seem ok to me, sofar coded those and owns and maintains some woodland so i'm sure he knew what he was doing.
I'm ok with a minimum of 2 if other devs prefer that, but low priority.

**Comment by CasimirKaPazi** [comment]
Sorry paramat, but this is plain wrong. I just did it. With length from minimum 3 to maximum 5. We can't have 1 to 5, because schematics don't support that, but we don't want that anyway.

    schematic = {
			size = {x = 5, y = 3, z = 1},
			data = {
				{name = "air", prob = 0},
				{name = "air", prob = 0},
				{name = "air", prob = 0},
				{name = "air", prob = 0},
				{name = "air", prob = 0},
				{name = "default:tree", param2 = 12, prob = 191},
				{name = "default:tree", param2 = 12},
				{name = "default:tree", param2 = 12},
				{name = "default:tree", param2 = 12},
				{name = "default:tree", param2 = 12, prob = 127},
				{name = "air", prob = 0},
				{name = "flowers:mushroom_brown", prob = 16},
				{name = "flowers:mushroom_brown", prob = 16},
				{name = "flowers:mushroom_brown", prob = 16},
				{name = "air", prob = 0},
			},
		},

**Comment by paramat** [comment]
You misunderstand, of course it is possible, but when placed in the terrain you will see the issue, it is not practical. We tried longer logs and saw the problems and reduced the length because of this.
