### ISSUE TITLE
Experience factor

### ISSUE THREAD

**Issue by ThomasMonroe314** [minetest/minetest_game#1782]
While taking a break from Minetest i came across several games that were classified as "Adventure" games, as is Minetest, however the only thing Minetest is lacking is some sort of experience factor, or levels per-say. The main game i see that would probably be the best to look at is ManaPlus.
As you gain experience you level up, but the more you level up the more experience you need to complete the next level. I was wondering if something like this would give the game a sense of achievement without taking away from game-play. I think it might also add a further depth to it and also make it easier to compose RPG subgames with this.

**Comment by theraven262** [comment]
Levels would be easy to make, I think there are mods already for it (frameworks if nothing else).
Also if you add levels, then you need quests, enemies, just imagine how much work there needs to be done to add all of these.
There are of course both quests framework and mobs already there, but one could possibly make a subgame just to prove that it would work.
But, I don't see the devs making minetest an adventure game, the features that are building-oriented are usually more accepted.

**Comment by paramat** [comment]
The idea is fine, but this is stuff for mods i feel. MTG is currently a simple core to add mods to, it's not meant to be fun, exciting, a complete subgame or any kind of specific subgame. MTG is lacking many things and this is intentional.

As with most big ideas and feature requests this is a case of 'if you want something done, you need to do it yourself'. Maybe find some like-minded people on the forum and create a mod or a subgame together. It is highly unlikely the MTG devs will try to add this into MTG, we don't have the time to anyway we are very understaffed. The future of MTG is unsure so at the moment it's maintenance and minor additions only.

**Comment by ThomasMonroe314** [comment]
@theraven262: thanks for the input i was going to do that, but i didn't have any good ides for a story line. :/

@paramat OK thanks for clearing that up, but again to my point, i want to ask a critical question concerning the overall direction of the project: what exactly is Minetest and where is it heading?
Is it a clone of Mine-Craft, or will it be a unique blend of many other "adventure-like" games?

**Comment by paramat** [comment]
Hehe many ask that but even the devs don't know and are less troubled by the question than non-devs. It is unsure, see the many issues and discussions about this, but in the meantime we continue to improve MTG without adding any big new features.
You should separate MT from MTG, one is a voxel game engine, the other is a subgame, i guess you are referring to MTG.

**Comment by ThomasMonroe314** [comment]
@paramat  yes i am referring to MTG, but also to MT bcs some things built into the engine would be helpful for this feature

**Comment by ThomasMonroe314** [comment]
something like an experience API builtin to default, or MTG would be nice, as it would allow someone to build onto it

**Comment by paramat** [comment]
:-1: A specialist feature for optional mods.

**Comment by SmallJoker** [comment]
This request belongs to an optional mod.

**Comment by octacian** [comment]
I'm not sure, a feature like this would really help to improve the game feel of Minetest Game. But then too, I suppose it hasn't really been entirely decided as to whether MTG is a game or not. Maybe it *should* be essentially forked and developed as an actual game while leaving the current MTG as it is, but that's a discussion for elsewhere.

Either way, a feature like this would really improve the game.

**Comment by paramat** [comment]
Seems better included in a new, more complete, subgame.
Anyway, dev time is too limited to deal with such complexity.

**Comment by rubenwardy** [comment]
more progression is needed in MTG, but not like this. MTG isn't an RPG
