### ISSUE TITLE
Crash problem in beds mod, bad `param2` values

### ISSUE THREAD

**Issue by VanessaE** [minetest/minetest_game#1784]
The beds mod crashes if someone tries to sleep on a bed that has a `param2` value that falls outside some expected range, e.g. due to `param2` colorization:

```
2017-06-16 23:57:40: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'default' in callback item_OnPlace(): [removed]/games/minetest_game/mods/beds/functions.lua:90: attempt to index local 'dir' (a nil value)
2017-06-16 23:57:40: ERROR[Main]: stack traceback:
2017-06-16 23:57:40: ERROR[Main]: [removed]/games/minetest_game/mods/beds/functions.lua:90: in function 'lay_down'
2017-06-16 23:57:40: ERROR[Main]: [removed]/games/minetest_game/mods/beds/functions.lua:150: in function 'on_rightclick'
2017-06-16 23:57:40: ERROR[Main]: [removed]/mods/homedecor_modpack/homedecor/bedroom.lua:146: in function 'on_rightclick'
2017-06-16 23:57:40: ERROR[Main]: [removed]/builtin/game/item.lua:347: in function [removed]/builtin/game/item.lua:340
```

See [Home Decor issue #367](https://github.com/minetest-mods/homedecor_modpack/issues/367) for discussion and details of what happened (the above backtrace was copy-pasted from @redblade7).

Two things need done to solve it:  First, as @paramat suggested, the beds mod should strip out any color bits from the `param2` value it receives (keeping `paramtype2` in mind e.g. `"colorfacedir"` or `"colorwallmounted"`), before applying it to the player's sleeping orientation.

That'll stop the crash, but what's also needed is to allow mods to pass a custom sleeping yaw value to the beds code.  That way a mod like Home Decor, which uses `param2` in an unconventional manner, could do the messy work and calculate its own player orientation and pass that along to the beds mod, which in turn could use that value to directly orient the player.

**Comment by paramat** [comment]
@juhdanad

**Comment by hdak1945git** [comment]
@VanessaE has asked me to chime in this issue from the [homedecor issue](https://github.com/minetest-mods/homedecor_modpack/issues/367) above -- to cut to the chase I managed to "fix" the basic problem (homedecor beds can be slept in again) but I'm really unsure if it's the best means of doing so.

* I assumed only values 0-3 are important, is it safe to assume that? see: [local function get_look_yaw(pos)](https://github.com/minetest/minetest_game/blob/master/mods/beds/functions.lua#L11-L22) -- `minetest.get_node(...)` doesn't provide a `paramtype2` value in a multiplayer server instance, so I can't check for it. 
* There doesn't seem to be [bitwise operators](https://github.com/minetest/minetest/issues/3028) in the version of Lua supported by Minetest. Is using modulus math allowed?

I suppose if those two items are acceptable, I can put together a formal pull request and continue from there.

**Comment by paramat** [comment]
@VanessaE are wall mounted rotations 0-3 identical in directions to facedir 0-3? So if the first 6 bits are stripped will that be correct?

**Comment by VanessaE** [comment]
I don't think the actual *rotations* are identical, as such, but the range 0-3 does exclude floor and ceiling, so it should work for the beds yeah.

**Comment by paramat** [comment]
#1826 is updated and needs testing with a mod that sends an override rotation.

**Comment by paramat** [comment]
#1904 merged, this strips the colour bits as is necessary for `colorfacedir` but does not add code to cope with the mod errors or the hacky use of `colorwallmounted`, see #1826 for discussion.
I recommend that instead of supporting `colorwallmounted` for beds we add a new `simplecolordir` that has 4 rotations 0-3 that leaves 6 bits for colour, this new rotation type has already been suggested and is the correct way, it will also be consistent with facedir as the first 4 rotations are identical.
