### ISSUE TITLE
Make minimap disabled by default in survival mode

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1787]
I see that the HUD flag for minimap is enabled by default in the engine.

In MTG survival a minimap is an extreme superpower that needs to be earned by crafting the required magickal or technological (drone, radar) items. So disabled seems to make more sense for the default.
A server can always use a mod to enable it for all players in survival if they wish to keep current behaviour, or otherwise, add a mod that requires crafting the items to gain the minimap ability.

MTG itself could potentially add the crafting of items to gain the ability, but i'm unsure because we would then need to choose between magickal or technological items, both of which may be unsuitable for many player's gameplay. Seems better to leave this to an optional mod.

Zoom priv is disabled by default for similar reasons, and i might add a mod to MTG for crafting a telescope to earn the zoom priviledge. So minimap being enabled by default is inconsistent.

Work may be needed in the engine to separate surface from radar modes, see https://github.com/minetest/minetest/issues/4378#issuecomment-309622208

**Comment by octacian** [comment]
I'd like to see this honestly, now that I think about it, however, rather than disabling it completely, I'd like to see a map item implemented in MTG which when wielded would cause the minimap to show in the proper position. However, this would require some other engine features to be added in advance.

**Comment by Fixer-007** [comment]
I feel like minimap should be reworked and be enabled when some kind of map item is in inventory, right now it feels more like modded/sandbox and not survival thing.

**Comment by paramat** [comment]
A map item is a different thing that needs to save all explored areas, and surface only. Minimap is more like having a drone flying above you to get an overview, or magickal remote viewing.

**Comment by rubenwardy** [comment]
How about a "proximity scanner"?

**Comment by Wuzzy2** [comment]
Implementation is trivial. See `orienteering` mod.

**Comment by paramat** [comment]
Please could you make a PR for disabling minimap by default in survival?

**Comment by Wuzzy2** [comment]
No. You're on your own.

**Comment by paramat** [comment]
PR #1877

**Comment by paramat** [comment]
#1877 merged with different behaviour to what the title of this thread suggests.
