### ISSUE TITLE
default.can_grow() should check daytime light not current light?

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1789]
Otherwise a slow time speed will delay plant growth. Real seeds and plants continue to grow at night, what matters is that during the day they have light.
I use time speed 8 so night is 90 mins long, this could delay sapling growth by 90 mins which is a doubling of their max grow time.

**Comment by Fixer-007** [comment]
This is game balance thing, I had impression that farming was overpowered, but that's just me. I would like to see more opinions.

**Comment by paramat** [comment]
Hmmm but then what if a server has time speed set to zero for permanent night, nothing should grow.
Maybe better to alter sapling grow time if they take too long (night delays their growth).

**Comment by HybridDog** [comment]
paramat, the grow speed should be proportional to the time speed. So just multiply the growth speed with it.
There's a function to get the sun light: https://github.com/minetest/minetest/pull/5680/files#diff-1305560bd8befb32862f0feeefabd02eR2250

**Comment by paramat** [comment]
No thanks, that's overkill complexity. the period of changing light at dawn and dusk is short anyway so that would only have effect for short periods of time.
However that is irrelevant because most plants do not 'grow' gradually, it is an instant event that happens when a timer stops or an ABM runs, so your suggestion is not possible.

**Comment by paramat** [comment]
Closing due to https://github.com/minetest/minetest_game/issues/1789#issuecomment-310624416
