### ISSUE TITLE
Underground dirt blobs in v7

### ISSUE THREAD

**Issue by theraven262** [minetest/minetest_game#1793]
Growing stuff underground requires dirt, yet it can be acquired only on the surface.
Therefore i propose underground dirt blobs in v7, so the player doesn't have to use one item slot for dirt when entering the underground.
Player also requires saplings, though those can regenerate, dirt can not.

**Comment by paramat** [comment]
Mgv6 originally had dirt blobs from y = -32 upwards and gravel throughout the world. So we've never had dirt deep underground in any mapgen, it's fairly unrealistic, so i'm not sure.
Currently to survive, and eat, underground you need to take a supply of dirt and at least one sapling or one mushroom.

**Comment by theraven262** [comment]
I agree that dirt should not generate very deep, but -32 is hardly that deep that one would need dirt there.

**Comment by paramat** [comment]
:-1: For reasons above.
