### ISSUE TITLE
Question - When Is It Planned to Break minetest_game Compatibility with MT 0.4.x in Favor of MT 0.5.x?

### ISSUE THREAD

**Issue by LazyJ** [minetest/minetest_game#1797]
When will minetest_game will begin to require MT 0.5.x and no longer be fully supported by MT 0.4.x?

**Comment by SmallJoker** [comment]
Forum announcement: https://forum.minetest.net/viewtopic.php?p=278486#p278486
Compat breaking PRs: #1785 (for https://github.com/minetest/minetest/pull/6007 ), maybe there will be more in the future.
