### ISSUE TITLE
Mushrooms spawn in direct sunlight and soon die

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#1799]
The map generator sometimes generates mushrooms in direct sunlight on fallen tree logs. This is pointless because those mushrooms can not survive in sunlight and die soon.

IMO a mushroom should not be generated if it would not survive.

Relevant Minetest issue: https://github.com/minetest/minetest/issues/6053

**Comment by paramat** [comment]
Yeah, however it is far too intensive to detect light at a location before choosing to place a mushroom, decorations are placed randomly. The slowdown of mapgen would not be justified.
Likewise ground mushrooms have noise parameters designed to place them where forest is densest, but sometimes they are in a patch of direct sunlight, so they die.

**Comment by DS-Minetest** [comment]
No change needed. The fallen logs are as fresh as the ones in the standing trees. => The mushrooms were already on the tree before it fell to ground and at that time there were leaves that made shadow.

**Comment by paramat** [comment]
Also, a while ago we had a week of dark wet weather, in that time some muhrooms grew on a log outside my house in a place that normally gets direct sunlight. it's not a strong argument i know.

If i reduce the number of logs in thin forest then thin forest will have no logs at all, and logs in thicker forest will still sometimes be placed in sunlight, so i don't see that as useful to do.
