### ISSUE TITLE
New uses for tin?

### ISSUE THREAD

**Issue by ThomasMonroe314** [minetest/minetest_game#1800]
I noticed while playing MT for the first time, the MTG lacked some color balance in the caves, mainly in its ores.
i was wondering if adding a greenish ore along with a purplish ore would give the color balance needed.

**Comment by SmallJoker** [comment]
Plenty of ores can be found at the forums. The tin ore was added recently to correct the bronze recipe, but lacks in other uses. It would be great to use tin in combination with another ore to make it more attractive instead of adding more ores that aren't used often.

**Comment by paramat** [comment]
> MTG lacked some color balance in the caves,

Hehe we don't add ores for the sake of cave colour co-ordination.
We are trying to resist adding new ores, there has to be a very good reason.
Silver may be a possibility, but uses are needed before an ore is added.

**Comment by lefty-studios** [comment]
We don't have enough uses for the ores we have now.......

**Comment by ThomasMonroe314** [comment]
true, and also @SmallJoker idk why tin was added
@paramat thanks again for the input. 

I would like to say that maybe re-balancing the ores to fit the tin would be nice, bcs when i was playing single player, the tine was just annoying bcs i didnt need it.

is there a way to make it more valuable, or make it different, like lead or something like that?

**Comment by lefty-studios** [comment]
maybe a tin door?
![tin_door](https://user-images.githubusercontent.com/14797400/27595757-8d99f0f0-5b2b-11e7-927f-106bdfd079c5.png)

**Comment by ThomasMonroe314** [comment]
sound interesting, but what about something like tin cups of water, that restore health.
tin is naturally soft, which is why a door may not work to well.

**Comment by lefty-studios** [comment]
the steel bottle from vessels could be tin instead...

**Comment by ThomasMonroe314** [comment]
why not make tin be combined with another ore to make pewter for utensils, like bottles, etc.

**Comment by lefty-studios** [comment]
#1803

**Comment by paramat** [comment]
Tin is a bit weird yes because it's only there for bronze, but then, bronze crafting was a mess before that. So tin has uses: bronze, blocks, stairs, slabs, and ithas more usage than gold, so it's not something to worry about.

**Comment by theraven262** [comment]
Just don't even think of tin tools, I've seen many subgames that have those, it is highly unrealistic.

**Comment by paramat** [comment]
We really don't want another set of tools :]

**Comment by ThomasMonroe314** [comment]
@theraven262 and @paramat don't worry about the tools, I wasn't even thinking about that.

Yes it might have more "crafting" uses than gold, but gold has more economical uses.

**Comment by C1ffisme** [comment]
@paramat It might not be so bad if the tools had more advantages than being faster and more durable than the last tier. (I.E. A tier of tools that may mine tough blocks quickly, but only last for a short amount of time and require a rare mineral to craft.)

**Comment by DS-Minetest** [comment]
Well, tin is and can be used by many mods. So, tin is good because MTG is in some way a modding base. IMO it's ok as it currently is, I've already seen ores with less usage.

**Comment by ThomasMonroe314** [comment]
speaking of ores with less usage, what is copper used for now?

**Comment by lefty-studios** [comment]
crafting bronze...

**Comment by paramat** [comment]
Copper is used by many optional mods.

**Comment by paramat** [comment]
Tin has uses, and we won't add new ores for the sake of cave colour balance. We need a good reason to add a new ore.
:-1:
