### ISSUE TITLE
Remove vessels mod for 0.5

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1807]
Seems a good opportunity. Servers can simply start to provide the mod themselves, just as with the nyan cat mod.
The mod seems out of place in MTG, being a specialised home decor type mod. I feel that those who like these types of items would want more than a glass and a couple of bottles and would be using a separate mod anyway.

**Comment by rubenwardy** [comment]
We need to have a mod store to make dependencies easier, and increase intermod support

**Comment by C1ffisme** [comment]
> I feel that those who like these types of items would want more than a glass and a couple of bottles and would be using a separate mod anyway.

I actually prefer when a mod gives me a smaller supply of decorative items, because it means I have to get creative with the ones I have. Sure, you could add all the 18 types of chairs I would ever need into the game, but why not let me be creative with stairs and slabs?

**Comment by SmallJoker** [comment]
I'm against raiding MTG to get a game for everyone but doesn't offer anything. At least we have vessels as alternative for apples as table/kitchen decoration. Each mod we remove will cause end-user problems, because mods don't load any more after updating. Sure, this wouldn't be much a problem if we had an official mod manager or mod store as @rubenwardy already suggested.

**Comment by paramat** [comment]
Well it is 0.5, breakage is intentional, and we can warn for months in advance in the forum. If someone deosn't see the forum post they will soon enough once they get unknown nodes.

> I'm against raiding MTG to get a game for everyone but doesn't offer anything.

A game for everyone would have more content, and thats not the intent.
Only vessels, it makes very little difference, a drinking glass and 2 bottles is a fairly useless amount of content.

**Comment by ThomasMonroe314** [comment]
Instead of removing it completely how about adding a group of default mods?

**Comment by C1ffisme** [comment]
@ThomasMonroe314 Problem: You have to balance the game for every combination of mods that can be added. That's not a big issue with vessels, but it gets bigger when you put in more mods into the "group".

**Comment by Napiophelios** [comment]
get rid of books and bookshelves while you are at it
...and beds too.

**Comment by ThomasMonroe314** [comment]
beds are a crucial part of the game though

**Comment by Wuzzy2** [comment]
In a subgame which has little to offer, it is clearly very important to remove existing items.

And *of course* everything will become unknown nodes. Genius! Who needs aliases and LBMs? Okay, a few totally unimportant players might miss their vessels, but they will get over it soon. They are going to *love* this unique new block called “unknown node”. Oh, the joy when your chat gets ~~spammed~~ enriched with beautifully red error messages!

Minetest Game. Developing games like a PRO!

**Comment by VanessaE** [comment]
@paramat the vessels originally had no "home decoration" element to them - I intended for other mods to use them as craft items (e.g. a glass of juice, a bottle of oil, etc).

The vessels shelf was added some time later on.

**Comment by paramat** [comment]
Wuzzy2, erm, we would warn in advance. We couldn't use aliases because those who want to keep their vessels nodes need the nodes unaffected. So just like when we removed nyan cat.
Anyway seems this may be unpopular.

**Comment by dsohler** [comment]
> get rid of books and bookshelves while you are at it
> ...and beds too.

Yes, please remove anything from default except the APIs. 0.5 is THE breaking release. This would be an awesome opportunity to fix #1771 and some other before we have to wait 3-5 more years before we'll have the possible next breaking release after that with 1.0.
