### ISSUE TITLE
Possibly reconsider sapling growth time

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1815]
See this forum post that does some analysis https://forum.minetest.net/viewtopic.php?p=276694#p276694
I have asked rnd to work out what they think would be the equivalent timer settings.

**Comment by dsohler** [comment]
Agreed. I feel like it would be better for everyone if the mean time for saplings to grow will be lowered by factor 10.

**Comment by paramat** [comment]
Hehe not that much :] it has to be somewhat equivalent to the ABM method.

**Comment by dsohler** [comment]
> It's important to remember it seems to take longer because grow time is now between x and x * 2 seconds [...]

It IS longer. I remember my tree farms always were fully grown after 15-20 minutes regardless of tree farm size but now it takes up to 80 minutes on average to grow at least one single tree.

**Comment by paramat** [comment]
Yeah it is longer, what i mean is the change of method can have an effect on the perception.
I might have to do an in-game experiment to discover a better equivalent.

**Comment by dsohler** [comment]
Actually I'm not sure if it's really intended.

Leaves decay within seconds, all things that can grow are fully grown within a few minutes, all that takes forever (literally and figuratively) are trees.

**Comment by paramat** [comment]
Testing now with the old ABM acting on 100 nodes.
50 are converted in 5 mins (!).

**Comment by paramat** [comment]
So that teaches me to trust abstract statistical analysis.
How about a grow time between 5 and 25 mins, and if not enough light reset timer to 5 mins?

**Comment by paramat** [comment]
#1818 merged.
