### ISSUE TITLE
stairs:slab_junglewood doesn't follow other wood slab namings

### ISSUE THREAD

**Issue by AnderRasoVazquez** [minetest/minetest_game#1821]
I've noticed that `stairs:slab_junglewood` doesn't follow `stairs:slab_`**typeofwoodUnderscore**`wood`. I don't know if it's intended, just wanted to point that out.

**Default:**
```
"stairs:slab_wood"
"stairs:slab_acacia_wood",
"stairs:slab_aspen_wood"
"stairs:slab_pine_wood",
"stairs:slab_junglewood"
```
**Suggestion:**

`"stairs:slab_junglewood" -> "stairs:slab_jungle_wood"`

**Comment by Ezhh** [comment]
Probably not intended, but the name doesn't affect gameplay (it's the description which is generally seen by players).

Changing it would mean adding an alias, which it's usually better not to do.

**Comment by paramat** [comment]
Yes this is noticed occasionally. 'jungletree' and 'junglewood' are very old nodenames, more recent trees use correctly separated words, the reason we don't alter the old nodenames is to avoid aliases and the disruption caused.
So it's intentional, thanks for noticing anyway.

**Comment by DS-Minetest** [comment]
What about an alias in the other way? `"stairs:slab_jungle_wood" -> "stairs:slab_junglewood"`

**Comment by paramat** [comment]
That would be even worse.
