### ISSUE TITLE
Player selection box is wrong dimensions

### ISSUE THREAD

**Issue by GreenXenith** [minetest/minetest_game#1832]
I don't know what commit did this or anything, and I don't know if someone already reported this, but I noticed it.
![screenshot_20170718_104653](https://user-images.githubusercontent.com/24834740/28331631-a8027756-6ba6-11e7-8956-44653c3e7e2f.png)
As you can see, the selection box is too thin and too short. The head sticks out the top a tiny bit and the arms stick out the sides. If this was intentional, it looks horrible..

**Comment by stujones11** [comment]
Currently the player collision box is hard-coded in the engine. AFAIK the last commit to change this was https://github.com/minetest/minetest/commit/2d5bd7f414f8b8107254490af2360d6e29f1a8d2

**Comment by GreenXenith** [comment]
Alright I will move this to the engine section.
