### ISSUE TITLE
Reverse corner stair crafting method?

### ISSUE THREAD

**Issue by ForbiddenJ** [minetest/minetest_game#1836]
https://github.com/minetest/minetest_game/commit/b66a61a10fee30d3d2436ce777124c82f07623ee was recently merged into minetest_game. I took a look at the stairs and they can go good with builds that have stairs on two connecting sides.

![screenshot_20170720_163748](https://user-images.githubusercontent.com/26123860/28439949-d4a1bc26-6d69-11e7-85b5-def549908234.png)

I have [asked](https://github.com/minetest/minetest_game/issues/1737) about reverse crafting regular slabs and stairs back to their source blocks before. And wuzzy2 [implemented that](https://github.com/minetest/minetest_game/pull/1740).

What I'm concerned about is that I see no way of crafting corner stairs back to their original source blocks. Also, the craft recipes are out of proportion with the physical volume of the corner stairs though that may not matter much so you could skip the proportions section of what I'm saying.

## Proportions

Let's divide the corner stairs into smaller blocks in such a way that dividing a full block would get us 8 mini-blocks. An outer stair is made of 5 mini-blocks and an inner stair is made of 7. Each slab is made of 4 mini-blocks.

If we squished 8 outer stairs' worth of mini-blocks together, we get the equivalent of 5 blocks.
If we squished 8 inner stairs' worth of mini-blocks together, we get the equivalent of 7 blocks.

This is out of proportion with the current recipes which provide 6 outer stairs out of 4 blocks and 7 inner stairs out of 6 blocks. Though I'm having a hard time coming up with crafting recipes that make more sense. 

## Proposal

I propose making equivalent reverse craft recipes at least.

**Comment by tenplus1** [comment]
If it helps Stairs Redo has recipes to craft them back into blocks. https://github.com/tenplus1/stairs

**Comment by paramat** [comment]
The big issue here is the texture doesn't line up with the stairs either side, will check.

The priority for the recipe is that it is intuitive and easy to remember, being incorrect volume is not important, the number of inner/outer stairs returned conserves volume.

Reverse crafting, i'm not keen, it would be 2 inner + 2 outer = 3 blocks.which doesn't seem very useful.
how often do you have 2 of each? Not often. Each recipe we add is multiplied by 34 so needs justification.

**Comment by paramat** [comment]
Inner:
7 microblocks. Recipe is 6 blocks = 48 mb, Return 48 / 7 = 6.86 = 7.

Outer:
5 mb. Recipe is 4 blocks = 32 mb. Return 32 / 5 = 6.4 = 6.

**Comment by GreenXenith** [comment]
> The big issue here is the texture doesn't line up with the stairs either side @GreenXenith
._. dunno how that happened.. i'll fix.. I think turning some faces should do the trick.

**Comment by GreenXenith** [comment]
@paramat do you want the fixed models posted here?

**Comment by paramat** [comment]
Thanks. What if we alter the texture mapping for normal staiirs too?

**Comment by GreenXenith** [comment]
@paramat that would likely mess up the normal metal stair texture, but I can check.

**Comment by paramat** [comment]
Oh of course.

**Comment by paramat** [comment]
Yeah it might.

Well, it's not perfect but this unaligned wood doesn't look as bad as how the metal edges did so it's not a big problem.

**Comment by GreenXenith** [comment]
Also, re-mapping the normal stair would mis-align it with the block too :P

**Comment by paramat** [comment]
Yes. Ok so this issue is a request for reverse recipes, which i :-1:

**Comment by ForbiddenJ** [comment]
In case someone happens to have a bunch of stair type blocks and they want to use the materials for other things. For instance: gold, or wood. That someone may have crafted more stairs than a build needed.

**Comment by paramat** [comment]
Yeah i know, my reasons are here https://github.com/minetest/minetest_game/issues/1836#issuecomment-317040800

**Comment by rubenwardy** [comment]
this adds cost so :-1:
