### ISSUE TITLE
Specify generic bush as mugo pine bush?

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1841]
We are making 'tree' non generic, specifying it as 'apple tree'.
I added 'bush' as a generic bush but would like to make it specific in the description (nodename will not change).
It currently drops wood that is now specified as 'apple wood' but it is not an apple bush, so we have  a problem.

Since it drops wood it needs to be 1 of the existing woods. Bushes appear in temperate grassland and snowy grassland/tundra so jungle (rosewood) and acacia are not possible, apple and acacia trees do not usually occur as bushes and i would rather avoid the complexity of this dropping apples, that leaves pine which would be ideal for the cold conditions.
There exists a pine bush called 'Mugo Pine Bush' which is the right size and shape:

![bucegi_mountains_jnepenis](https://user-images.githubusercontent.com/3686677/28495547-d1860d82-6f47-11e7-8787-f592d4490af2.jpg)

I would change the texture and make it drop pine wood.

**Comment by TumeniNodes** [comment]
I like this idea but, couldn't it be simply named as "pine bush" as you seem to have originally felt? That seems the better idea. (always trust your first instinct)
Or did a previous opposition cause you to rename the title?

**Comment by paramat** [comment]
You mean use 'pine bush' as the nodename? I would rather avoid aliases, and we already have 'tree' which is described more specifically as an "Apple Tree".

**Comment by Napiophelios** [comment]
> You mean use 'pine bush' as the nodename? I would rather avoid aliases.

I think he meant as the new description.

**Comment by TumeniNodes** [comment]
Yes the new description

**Comment by paramat** [comment]
PR #1845

**Comment by paramat** [comment]
Closing, see PR for reasons.
