### ISSUE TITLE
Adding stairs specific textures same as doors uses

### ISSUE THREAD

**Issue by TumeniNodes** [minetest/minetest_game#1843]
I don't see where texture alignment was mentioned in the issue #1836 ? Unless I completely missed it.
I did not want to add off-topic jibberish there so thought opening this as a separate suggestion/request, on it's own seemed more appropriate.

 Just to reiterate on the texture alignment issue regarding stairs as it was mentioned in that conversation.
We went over the issue regarding corner stair textures before, and it has been mentioned other times as well.
There simply is no way to solve this mis-alignment unless others agree to use custom textures for stairs mod (similar to the doors mod) using UV layouts.
Fixing the UV's for one texture will mess up another, and will never be the way to fix it.
The way the mapping is set to make better block and metal stairs is best. The wood misalignment is not that horrible (for the time being)

I used 2 model & textures sets in one of my mods, and even this does not resolve alignment, for that each node would require 4 versions (and even two each is overkill for the minimal gain it produces)

What I am am suggesting (probably more for 0.5.0) and on, is to use custom UV layouts for the stairs mod, just like the doors mod uses.
This would be the proper way to resolve texture alignment with corner stair nodes. Texture pack creators will just have to work harder ; )
I am looking to see if this may be an acceptable idea prior to starting any work on a PR for it.
Also, perhaps someone else may have a better solution/idea as well? Because this is an issue which will continue to pop up time after time, unless it is resolved one way or another.

If this belongs in another place related to 0.5.0 , I apologize for misplacing this

**Comment by paramat** [comment]
The issue is explained here https://github.com/minetest/minetest_game/issues/1836#issuecomment-317052805 and see screenshot in first post.
It would be good to try and find a simple solution for this.

**Comment by TumeniNodes** [comment]
Yes it was a rather vague mention of texture alignment.
The only simpler solution still calls for custom texrures specific to stair
corners and, if you're going to use custom specific textures you may as
well do it right

**Comment by paramat** [comment]
![screenshot_20170724_164816](https://user-images.githubusercontent.com/3686677/28531855-f202b9cc-708f-11e7-976a-a3c8b30aec26.png)

But then, normal stairs do this already:

![screenshot_20170724_164525](https://user-images.githubusercontent.com/3686677/28531894-0f91f476-7090-11e7-809f-e73c6fa28e28.png)

**Comment by TumeniNodes** [comment]
I'll work on something in a few days, my HDD just fizzled on me. In damage control mode for a bit

**Comment by paramat** [comment]
I think the lack of alignment is preferable to any complex 'fix', it just looks like a different set of planks that don't line up, which happens anyway in the other axis and with stairs. Doesn't look bad at all.
Ideas are welcome but i will probably prefer no change to keep it simple.

**Comment by TumeniNodes** [comment]
That's fine. It's actually not that big of a deal based on the default
textures (which is what matters)
I will still mess around with a few ideas over time, and when there are a
couple ideas and if it seems worth it, this can be revisited.
I was also wondering how the world aligned textures is progressing, I'll
keep an eye on that too, seems like the best solution
Ill close this later when Im not limited to my phone

**Comment by TumeniNodes** [comment]
Closing
