### ISSUE TITLE
Dark player model below y = 0

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1852]
![screenshot_20170726_003252](https://user-images.githubusercontent.com/3686677/28598249-446b930e-719a-11e7-96f7-4346330ef444.png)

Discovered that when below y = 0, the player model goes dark if the player is standing on a node, if jumping or flying very slightly above a node the light returns. Probably an engine bug due to offset changes @TeTpaAka the point which is used to define the light level must be dropping below ground level, and maybe above y = 0 that point is just above ground level.

**Comment by paramat** [comment]
![screenshot_20170726_004840](https://user-images.githubusercontent.com/3686677/28598557-4951f28a-719c-11e7-9881-7d7c87b2bac5.png)

> the point which is used to define the light level must be dropping below ground level, and maybe above y = 0 that point is just above ground level.

Yes confirmed by flying very slightly into the ground.

**Comment by kaadmy** [comment]
The light position is probably from the 0,0,0 position, it was moved down to the bottom of the player (?), thus becoming black since it's in a node.

**Comment by paramat** [comment]
Exactly.

**Comment by paramat** [comment]
Moved to https://github.com/minetest/minetest/issues/6174
