### ISSUE TITLE
Clay brick texture size

### ISSUE THREAD

**Issue by theraven262** [minetest/minetest_game#1855]
The default_clay_brick.png has size of 16x17 instead of 16x16, which makes it slightly stretched in the inventory.

**Comment by paramat** [comment]
@TumeniNodes we use a palette of 256 colours for indexed colour, because textures are 16x16 so that allows a separate colour per pixel.

**Comment by TumeniNodes** [comment]
@paramat  hmm, odd. this is the palette I used to index, then ran through optipng but the file size has increased from 158 bytes to 213 bytes. And optipng states the texture is already optimized. I used both the default as well as ran it through optipng o7 with same result.
I'll submit a PR but I want to make sure it is right first so any suggestions would be appreciated.

I might have added a second alpha layer by mistake, I will check

**Comment by TumeniNodes** [comment]
Size is now down to 179 bytes. Is that acceptable? I cannot explain the increase in size, as I do not understand what is causing it.

**Comment by paramat** [comment]
Maybe sometimes indexed colour creates a larger file, nevermiind, it's best that textures are indexed colour if they can be (however a few cannot, such as leaves textures that need to retain the colur of transparent pixels, so have to remain RGBA).
So that's fine.

**Comment by TumeniNodes** [comment]
> I assume you stripped metadata?

yes sir. It's down to 160bytes

**Comment by paramat** [comment]
Excellent.
