### ISSUE TITLE
[Bug] Beds in low rooms can get you stuck

### ISSUE THREAD

**Issue by JRottm** [minetest/minetest_game#1865]
To reproduce, build a small room which is 2 nodes high. Place a bed in it. So, all nodes counted from bottom to top should be 1x Ground, 1x Bed, 1x Air, 1x Ceiling. Then walk towards the bed. Normally the bed blocks you from walking on top of it, because the ceiling is too low for that. BUT, if this is done below sea level i.e. bed has Y<0 coordinate then you CAN walk onto the bed and will get stuck with your head inside the ceiling.

On servers it's quite possible that the ceiling blocks may be protected by someone else so you can't dig yourself out, and you don't have noclip or teleport permissions either. In this case the only way out is dying. (If you've also slept in this bed and respawn there then you're in trouble.)

Tested locally with Minetest Game from Minetest 0.4.15 and 0.4.16 on Debian 9, 64 bit, and on a public game server running 0.4.16.

**Comment by SmallJoker** [comment]
This is an issue for the Minetest core. Please post this issue here: https://github.com/minetest/minetest/issues
