### ISSUE TITLE
Creative setting is broken on old worlds

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1866]
On old worlds singleplayer can use "Creative page" even with "Creative" disabled on world page, taking blocks works, digging blocks by hand is not working though.

Version 5d19fd6

**Comment by paramat** [comment]
Something to check: did you give singleplayer all privs? Because there is now a 'creative' priv which would then get enabled, this confused me recently.

**Comment by Fixer-007** [comment]
My privs in affected world:
![default](https://user-images.githubusercontent.com/16494741/29870779-e75645ec-8d91-11e7-95b8-906cdacfa467.png)

**Comment by paramat** [comment]
Yes you have creative priv, maybe you granted yourself all privs recently?

**Comment by rubenwardy** [comment]
This is why I didn't like the idea of a creative privilege very much, admins have the right to do everything and because creative inv is a priv it becomes a right they have.

But players disagreed, which was why the private was added.

**Comment by Fixer-007** [comment]
>Yes you have creative priv, maybe you granted yourself all privs recently?

If only I remembered when exactly... world creation date is around 05/08/2017 (normal DATE system, not american one).

**Comment by paramat** [comment]
So, no bug.

**Comment by Fixer-007** [comment]
It is a bug, that happens only during some circumstances.

**Comment by paramat** [comment]
Ok, are you sure you never granted yourself all privs?
Maybe the saved privs of a player have creative priv added automatically when moving to the engine version that has the creative priv? Although i can't see how.
It may be an engine bug.
