### ISSUE TITLE
Update mods from individual repositories under 'minetest-mods'

### ISSUE THREAD

**Issue by AntumDeluge** [minetest/minetest_game#1875]
I was reading issue #1615 & got the idea that it would be easier for sub-game developers to resist using ***minetest_game*** as a base if the mods were kept in individual repos under [minetest-mods](https://github.com/minetest-mods). Then just update ***minetest_game*** from those repos.

I'm not talking about using Git submodules either. That wouldn't be a good idea.

**Comment by AntumDeluge** [comment]
I created a sample repo [here](https://github.com/AntumMT/mod-default) that retains Git history from ***minetest_game***.

**Comment by AntumDeluge** [comment]
I guess this is related to #726 & #1771. Sorry, I didn't see those.

**Comment by paramat** [comment]
It might help subgame devs a little but seems inconvenient for MTGame devs.

**Comment by AntumDeluge** [comment]
I agree, it's not as simple. It adds an extra step to updating ***minetest_game***. Using Git submodules would make it a little easier. But might confuse inexperienced Git users when cloning the repo.

**Comment by AntumDeluge** [comment]
When I update a mod in [Antum game](https://github.com/AntumMT/game-antum), I copy the files over & reference the commit.

**Comment by paramat** [comment]
:-1: Seems a nightmare for core devs.

**Comment by tacotexmex** [comment]
> I created a sample repo for default that retains Git history from minetest_game.

@AntumDeluge How do you keep it automatically updated?
