### ISSUE TITLE
Bows

### ISSUE THREAD

**Issue by TumeniNodes** [minetest/minetest_game#1878]
This is just an idea/suggestion or feature request for discussion atm.

Add/Introduce bows to tools.lua or as a mod in MTG

Q.(why?) A. Bows are useful for hunting and fighting. Bows add enhancement to gameplay.

-------------
--Bow-Types--
-------------
--wooden_bow (maybe different wood types add different strengths/durability?)
--bronze_bow
--iron_bow
--steel_bow
--mese_bow (possibly?, as a power-bow. only avail after a certain level)

-----------
--Recipes--
-----------
{empty} {material} {string}

{material} {empty} {string}

{empty} {material} {string}

---------------
--Arrow-Types-- (by arrowhead)
---------------
--wood     -----
--stone        | 
--bronze       | 
--copper       |
--diamond      |
--gold         |--(wood is weakest, mese is strongest in reference to damage)
--iron         |
--mese         |
--obsidian     |
--steel        |
--tin      -----

-----------
--Recipes--
-----------
{empty} {empty} {feather}

{empty} {stick} {empty}

{.. shard} {empty} {empty}

Question is, which bow mod is best suited for MTG inclusion?
or, should an entirely new [bows]-code be written?

But, should bows be an additional mod, or should they be part of the tools.lua code?

Also notable is, a feather item needs to be added for crafting arrows..
how are feathers obtained? from chickens? [?] 
could there be other uses for feathers to help justify adding them? (as if arrows is not enough)

**Comment by jastevenson303** [comment]
Wielditem animations would be good for shooting the arrow.

**Comment by DS-Minetest** [comment]
>hunting and fighting

MTG doesn't include hunting and fighting, the sword is for digging leaves and co.. Shooting arrows would need some similar usage, eg. tnt arrows.

At the moment bows don't make much sense since https://github.com/minetest/minetest/issues/5212 isn't done yet.
But crossbows would perhaps make sense.

**Comment by theraven262** [comment]
I would +1, but projectile physics are so badly affected by lag that this would do no good.
Also, we need the wielditem animations support, without that they would be overall too static and would basically serve as ranged swords (technically speaking).
Feathers? Well that is easy, make them dropped from leaves with a chance.

**Comment by TumeniNodes** [comment]
@DS-Minetest maybe better then to just keep the idea in the air at least, until #5212 can be implemented then.

@theraven262 I have to admit, I had not thought about the lag on servers.
Feathers, dropping from leaves? hehe, your world sounds very... interesting.

**Comment by theraven262** [comment]
Hey! That idea was not originally mine, i saw it on some server, guess it came from the fact that birds are nested in tree branches, so leaves should contain some feathers at least.

**Comment by C1ffisme** [comment]
I don't like the idea of too many bows or arrows.

First off, bows work because of the tension in the wooden limbs of the bow, not because of how springy the string itself is. A metal bow _could_ work, but if you had the ability to pull the bow limbs at all, you would probably just bend the limbs. That's why plastic and wood are good materials for bows, and not metal. (Although, there are some springy metals, maybe those could work?)

Secondly, as for arrows, I don't feel like we need so many. I think it's a better tiering system than having tons of bows, but I don't think we need more than 3 kinds of arrow levels. (Probably stone, steel and mese.) Any other tiers should have special uses.

**Comment by TumeniNodes** [comment]
The materials in this list are just reference.
While I do agree about the types of bows, and using a reality based thinking..., this is Minetest, so...
Bows could be restricted to wood types, and set the strength levels that way, but then people will start complaining about not having unrealistic types as stone, etc... But then again, they can always make mods for those.
For the wood bows rankings, pine lowest, junglewood the highest (mese the ultimate power bow)

I like the idea of keeping anything added to MTG "basic", and let modders take it that step further.
Features directly tied into MTG should remain basic/simple, and not bloated.

As for arrows, it could be kept down to the ages of history. Wood, stone, obsidian, bronze, and so on with mese as a specialty (same for the bows with mese)

Each type could also have the possibility to be upgraded, maybe like 2 times before the next rated material is available?

**Comment by paramat** [comment]
The network lag of projectiles could be a big issue, meaning that clientside simulation would be needed, so added 'non-trivial'.

**Comment by TumeniNodes** [comment]
I thought there was an issue or PR in regards to wielditem animation in the past? Can't seem to locate it.
I know that requires engine work though.

clientside simulation for projectiles sounds right, but that will also be an involved project.
So, if I'm not wrong, sounds as if anything coded should keep all these together in one project/API?

**Comment by Ekdohibs** [comment]
Projectiles are usually with a fixed speed at the beginning, and an acceleration equal to g. In that case, since the acceleration does not change, we already have client simulation of the movement for free.

**Comment by paramat** [comment]
Oh yeah, particles. The appearence of the particle would need to be coded to look like an arrow moving away from the player.

**Comment by Fixer-007** [comment]
String has no more uses in current minetest_game, you craft wool with cotton now, this is highly suggestive to move this issue forward ;)

**Comment by TekhnaeRaav** [comment]
Throwing my opinion up there. I do think that the bows should be kept very simple
(wood_bow, and mese_bow). Also the arrows,(flint_arrow and steel_arrow).

And yes @Fixer-007, that dose pose an issue, but I think that we should just use cotton for the string of the bow.

**Comment by paramat** [comment]
Thinking on it, the arrow particle could simply be an exact rear-view of an arrow, at the speed it moves this will be good enough.

**Comment by TumeniNodes** [comment]
> Thinking on it, the arrow particle could simply be an exact rear-view of an arrow, at the speed it moves this will be good enough.

I was unsure why the current method used in the couple of existing bow mods did not suffice.
So this seems doable, currently. Just a matter of, (as I stated originally) take a look at the existing bow mods, and see where they might be improved? Or code an entirely new, original method?

As far as the action of drawing the bow, there is one mod which somewhat duplicates the method used in Minecraft, it seems just the speed between draw points is faster and using more than 3 stage images in Minecraft.
I am not saying we would be looking to duplicate MC's rendition but, afterall, how "different" could the action of a bow be done, in any case.

The crafting is easy, the materials, etc. are already available so that is a non-issue

**Comment by paramat** [comment]
Anyone know of any good MT bow mods?

**Comment by C1ffisme** [comment]
I coded a prototype of a mod that actually allows for drawback, I'll see if I can get it onto Github.

**Comment by Fixer-007** [comment]
Here is quick search of bows mods (probably missing some):
https://forum.minetest.net/viewtopic.php?t=14384
https://forum.minetest.net/viewtopic.php?t=18310
https://forum.minetest.net/viewtopic.php?t=11511

**Comment by paramat** [comment]
SmallJoker is working on a new one that uses raycast.

**Comment by C1ffisme** [comment]
@paramat This is my hacky bows mod that allows for drawback: https://github.com/C1ffisme/bows

Hopefully we won't ever have to use this kind of hack if we get better API support for holding down mouse buttons and changing textures of items dynamically. But it was an interesting problem to solve.

**Comment by paramat** [comment]
The drawback isn't very important, SmallJoker's mod just has 2 states, undrawn and drawn, with a change from one to the other on a mouseclick, that is good enough as well as being simple and lightweight, maybe it culd have a delay added to limit rapid fire. We don't need to copy MC here with it's animation.

**Comment by C1ffisme** [comment]
> We don't need to copy MC here with it's animation, there's too much attention on the drawback animation relative to other more important aspects.

I'm fine with this as long as we fix this kind of thing in the future, because nice-looking graphics are a priority to me.

**Comment by DeathRowRecords** [comment]
I have a cold but I can see it, oh yes I can so picture it already . . . a wooden bow and a torch arrow and a rope arrow to climb high or do some crazy monkey business. That rope ain't a bad idea Zip line, rope swing, rope ladder, whatever it takes, you name it. Who said i can't handle it? I can handle some sort of craziness some of the time, maybe most of the time. [BUT!](https://t00.deviantart.net/uY4jgB4tW7ClOJ4tWFLp7FldttA=/fit-in/700x350/filters:fixed_height(100,100):origin()/pre00/9ae5/th/pre/f/2016/320/8/a/symmetra_booty___overwatch_by_urbanator-da90xl1.png) obviously not handle it . . . I can't handle it ALL OF THE TIME!

**Comment by rubenwardy** [comment]
This doesn't make sense before adding mobs

**Comment by Fixer-007** [comment]
Unless PVP on servers.

**Comment by paramat** [comment]
And mods provide mobs. After all we do have swords without mobs.

**Comment by paramat** [comment]
BTW i intend to add a very simple hostile mob mod (oerkki), hopefully for 0.5.

**Comment by paramat** [comment]
Is there core dev support for this?

**Comment by Ezhh** [comment]
Neither for or against. I don't think it should be a priority either way.

**Comment by Fixer-007** [comment]
Mobs first...

**Comment by NathanSalapat** [comment]
I know some of the bow mods let you shoot arrows that place torches or fire. That could be a good use case, or shooting grappling hooks.

**Comment by Ezhh** [comment]
If there is no dev support and so it is closed, why is it on the roadmap? If there is no dev support, why was it ever added to the roadmap to begin with?
