### ISSUE TITLE
Loop in step sound while flying

### ISSUE THREAD

**Issue by lupoDharkael** [minetest/minetest_game#1883]
If you have free_move enabled and keep pressing Shift (without moving), you can hear the footstep sound in loop. The sound should be heard only when you reach the floor.

**Comment by paramat** [comment]
Engine issue, please open an issue here https://github.com/minetest/minetest/issues

**Comment by DS-Minetest** [comment]
(Moved to https://github.com/minetest/minetest/issues/6356.)
