### ISSUE TITLE
Steel doors deceive new players

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest_game#1888]
You sometimes see players who think that steel doors protect their property by letting nobody enter the room.
There are cases where players put usual chests behind steel doors and think the items are secured. https://forum.minetest.net/viewtopic.php?f=21&t=18313

**Comment by Fixer-007** [comment]
Yeah, protected steel doors serve little purpose in default game, I suggest merging very simple protection mod like this: https://github.com/cornernote/minetest-node_owner (Blocks you place are owned by you and others cannot dig them or place onto them.) It is tiny. And of course add a per world setting.

**Comment by HybridDog** [comment]
That mod is heavy, it adds the playername to the meta of every node placed by a player.

**Comment by Fixer-007** [comment]
Ofc there are other options, like landrush, simple_protection (preferred solution IMO), areas, protector_redo, etc.

**Comment by HybridDog** [comment]
Protection mods don't solve the problem, players can access chests anywhere e.g. by using the travelnet missing formspec escape bug.

**Comment by paramat** [comment]
What's the issue? Steel doors are only openable by the placer but other nearby nodes need protection. If the player misunderstands that's their problem.

**Comment by SmallJoker** [comment]
I agree with @paramat owned nodes are consistent: They can't be dug by people who have no permission to do so. There are protection mods to adapt this mechanism to nodes in a specific area.

**Comment by Fixer-007** [comment]
Actually, there is a trick available to protect everything, but you will not like it, but since 2011, you can build everything out of locked chests/doors/trapdoors.

![default](https://user-images.githubusercontent.com/16494741/30287637-78e44298-972e-11e7-8792-2fb3ba25d946.png)
