### ISSUE TITLE
Inconsistent block behaviour for creative priv

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1889]
Create world, damage enabled, creative disabled. Start it and issue /grantme all, restart world.
Open inventory and take 1 dirt and 1 tree block. Then place them, you will see that:
+ You can place multiple dirt without problems
+ Placing wood removes it from inventory, which is inconsistent (other blocks may be affected as well).

Minetest 0.5.0-dev 5f489efc

**Comment by DS-Minetest** [comment]
Can also reproduce with cactus.
I think, it's because of:https://github.com/minetest/minetest_game/blob/fe67ffda7ca4326c85f114bd02797f25348931f9/mods/default/nodes.lua#L579
As you can see in lua_api.txt:
```
* `minetest.rotate_node(itemstack, placer, pointed_thing)`
    * calls `rotate_and_place()` with infinitestacks set according to the state of
       the creative mode setting, and checks for "sneak" to set the `invert_wall`
       parameter.
```
`minetest.rotate_node` uses the creative mode **setting**.
