### ISSUE TITLE
All sounds are not the same sampling rate.

### ISSUE THREAD

**Issue by jastevenson303** [minetest/minetest_game#1894]
Some sounds are 22kHz (`default_footstep.2.ogg`), and others are 48kHz(!) (`default_footstep.1.ogg`)

I would recommend to make all sounds within minetest_game 44,100 hertz.

**Comment by paramat** [comment]
For new sounds we tend to use 44/1kHz for quality, but old sounds remain at 22kHz and there's no point increasing the rate because it won't increase the quality, we would need to go back to the source samples and redo all of them, which would be a huge and boring task not worth doing.
