### ISSUE TITLE
Door sound volume up close is too loud compared.

### ISSUE THREAD

**Issue by jastevenson303** [minetest/minetest_game#1895]
The door open/close sound when played within/next to the node itself, is far too loud.  It seems to me to be an issue with the ramping, or curve somewhere.  It's quiet enough taking one step back, for example.

Not sure where this issue really lies, as it may even be an engine problem.  I assume the sound is played positionally for all players nearby, but it is perhaps that determination that needs adjustment.  I don't know math, so log(f) is meaningless to me, but anyway.

https://github.com/minetest/minetest/pull/6440 is related I think.  (Issue it's attempting to address: https://github.com/minetest/minetest/issues/4361)

**Comment by paramat** [comment]
Just a case of tuning the gain, not a bug.

**Comment by paramat** [comment]
Actually, it's probably due to the inverse linear volume function we use, it tends towards infinity near zero distance.
AL_INVERSE_DISTANCE page 87 here https://www.openal.org/documentation/OpenAL_Programmers_Guide.pdf
Maybe we should use the CLAMPED version instead?

**Comment by paramat** [comment]
PR https://github.com/minetest/minetest/pull/6457

**Comment by paramat** [comment]
#6457 merged, please test and comment here.

**Comment by paramat** [comment]
I'll check door volume in case the gains need tuning.

**Comment by jastevenson303** [comment]
I don't know, it must be lower.  I'll reopen this, @paramat, if I'm mistaken.

**Comment by jastevenson303** [comment]
I'd like a main sound issue for the engine, where this stuff could be discussed at least.  I would be willing to resample and modify some sounds, for what it's worth.

**Comment by paramat** [comment]
The volumes for each sound are set in the subgame, so will be a subgame issue.

I'll still check doors for sound balance.
