### ISSUE TITLE
Cannot distinguish between Acacia bush and tree leaves.

### ISSUE THREAD

**Issue by jastevenson303** [minetest/minetest_game#1896]
![screenshot_20170921_010913](https://user-images.githubusercontent.com/23448162/30679750-9969a3f4-9e69-11e7-91a3-a2a344e6137e.png)
![screenshot_20170921_010913_1](https://user-images.githubusercontent.com/23448162/30679751-996ca518-9e69-11e7-9e4e-59a19117dd5f.png)

They look identical, but they are not identical.

**Comment by paramat** [comment]
Eh, they are easily distinguishable. Inventory tooltip can solve any confusion.

**Comment by SmallJoker** [comment]
I believe @jastevenson303 requests a visual difference, without having to hover the mouse over the item. This would be helpful when merging stacks that look optically the same.

**Comment by paramat** [comment]
I know, but they're visually very different, one has big white spikes and they're different colurs. I can instantly tell the difference even from the small screenshots above.
Also, we don't alter textures to make them visually distinguishable, they are textured how they need to be, if they are very similar then the tooltip is there to help.
For example look at obsidian nodes, very similar, and many other examples.
