### ISSUE TITLE
tnt.boom(pos, definition) fails to compute damage radius.

### ISSUE THREAD

**Issue by jastevenson303** [minetest/minetest_game#1901]
From game_api.txt:
```
tnt.boom(position, definition)`

^ Create an explosion.

* `position` The center of explosion.
* `definition` The TNT definion as passed to `tnt.register` with the following addition:
* `explode_center` false by default which removes TNT node on blast, when true will explode center node.
```

If you do tnt.boom(pos, {name = "tnt:tnt", description = "TNT", radius = 3}), then it will crash when tnt.boom looks up def.damage_radius.  It works if you include damage_radius manually, but this is not how tnt is registered here: https://github.com/minetest/minetest_game/blob/master/mods/tnt/init.lua#L658

And makes
>* `definition` The TNT definition as passed to `tnt.register`...

incorrect.  tnt.register_tnt() computes damage_radius as def.radius * 2 if nil, but tnt.boom assumes it's present and crashes on nil?  I'm more confused now having typed up this issue.  How to reproduce:
```
minetest.after(0, function()
for k, _ in pairs(minetest.registered_nodes) do
        minetest.override_item(k, {
                on_punch = function(pos, node, puncher, pointed_thing)
                        tnt.boom(pos, {name = "tnt:tnt", description = "TNT", radius = 3, damage_radius = 1})
                end,
        })
end
end)
```
Take out `, damage_radius = 1` from the tnt.boom() tnt def and it should crash on nil damage_radius.

Video demonstration: https://www.youtube.com/watch?v=rPzvp33gxCQ

**Comment by paramat** [comment]
`damage_radius: The radius within which the TNT can damage players and mobs. By default it is twice the radius`
So it's not falling back to the stated default, the API docs should state what parameters are needed and which are not needed for tnt.boom, for example i don't expect name, tiles and description are needed.

So mostly a docs issue.

**Comment by paramat** [comment]
#1903 merged.
