### ISSUE TITLE
player_monoids-like API for physics overrides

### ISSUE THREAD

**Issue by raymoo** [minetest/minetest_game#1909]
https://github.com/minetest-mods/player_monoids provides a way for mods that change a player's physics overrides to be more compatible with each other. I feel like Minetest would benefit from this being in a more central place though. Since minetest_game is intended partially as a modding base, I think this kind of API would fit here. It would also allow adding mechanics to minetest_game that involve changing the player's physics overrides without getting in the way of other mods much.

I imagine an API like this:
  - `player_api.add_physics_modifier(player, modifier_id, override_table)` - Multiply the current player physics override with the given override table. The `modifier_id` can be used later to cancel out the modification. If the id has not been used to cancel the last applied modifier on that id, then cancel it now before applying the new override table.
  - `player_api.remove_physics_modifier(player, modifier_id)` - Cancel the last applied modifier on the given id.

The implementation in player_monoids basically keeps a table of modifiers for each player, and `add`/`remove_physics_modifier` adds/removes from that table and then recalculates the player's override from the remaining entries.

It is important that the modifiers are **not** persistent, to support uses like sprinting that are not meant to be persistent. Persistence can be handled separately by the mod client to this API.

**Comment by tenplus1** [comment]
this would be great if included inside player api mod

**Comment by paramat** [comment]
It seems it should be in the engine, subgames should not duplicate the code. And why in Lua?
From your mod:

> Players have behavior-affecting state that can be modified through mods. A couple examples are physics overrides and armor groups. If more than one mod tries to change them, it can result in unexpected results.
For example, a player could be under a speed boost effect from a playereffects effect, and then sleep in a bed. The bed sets the player's speed to 0, and sets it back to 1 when they get out. Because the beds mod had no way of knowing that the player was supposed to have a speed boost, it effectively removed it

**Comment by raymoo** [comment]
In Lua because it can be done comfortable without touching C++. There are lots of things in builtin (for example, forceload tracking) that could be done in C++, but isn't because it's simple enough to do in terms of existing Lua API functions.

I wasn't sure if it should go in builtin or in minetest_game, since maybe some subgames would want to have a different system of managing physics overrides. I guess it could also make sense to put it in the ObjectRef metatable instead of in player_api (or wherever it would be put).

Thanks for the feedback, this issue is mainly to probe how I should approach adding this kind of API to Minetest. I think it would be easy to do in either C++ or Lua, whichever is decided on.

**Comment by paramat** [comment]
Ok in Lua might be fine, but i think it should be in the engine.

**Comment by Wuzzy2** [comment]
I agree with paramat. IThis would just force subgames to duplicate code. Why limiting this only to Minetest Game?
Either add this to engine or builtin.
