### ISSUE TITLE
Strange behaviour when manipulating full stacks in chest formspecs

### ISSUE THREAD

**Issue by Hawk777** [minetest/minetest_game#1915]
Tested in Minetest and Minetest_game 0.4.16.

Put down a chest. Get hold of two stacks of 99 cobblestone each, plus one stack of 1 cobblestone. Put one stack of 99 cobblestone in the chest, the second in your first hotbar slot, and the stack of 1 cobblestone in your second hotbar slot. Now open the chest, click on the 1-cobble stack from hotbar slot 2 to pick it up into the mouse pointer, and then click on the 99-cobble stack in the chest.

Expected behaviour: the stacks swap places. The chest contains a 1-cobble stack, the mouse pointer holds a 99-cobble stack, and the 99-cobble stack in hotbar slot 1 is still there.

Actual behaviour: The chest contains a 1-cobble stack, the 99-cobble stack from the chest teleports directly to hotbar slot 2, and the 99-cobble stack from hotbar slot 1 teleports into the mouse pointer.

If you had a >1-cobble stack in hotbar slot 2 when you started this, and you split that stack to put only some of it into the chest, then the stack unsplits when you click in the chest’s inventory and the left-behind portion teleports into the chest at the same time as the 99-cobble stack you swapped with teleports back to hotbar slot 2.

This doesn’t require that the other 99-stack be in the player inventory; it also happens if the 99-stack that you’re not touching is in the chest. However, it *does* require that the 99-stack that you’re not touching be in an earlier slot than the 1-stack that you initially pick up; if there is only one 99-stack before the 1-stack (the one that you’re going to swap with), then the swap happens normally and 99-stacks in higher slots than the original 1-stack lived in are not touched.

**Comment by SmallJoker** [comment]
This issue is a C++ side problem, this means it can happen with any inventory exchange.
Belongs to https://github.com/minetest/minetest/issues

**Comment by Hawk777** [comment]
I didn’t know whether it was a bug in Minetest_game’s Lua or Minetest core. Thanks for the info. Reported as minetest/minetest#6516.
