### ISSUE TITLE
Sfinv: 'on leave' function not called when exiting sfinv page directly to game with 'escape'

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1916]
@rubenwardy 
Sfinv 'on leave' function is called when exiting an sfinv page to another inventory tab, but not when using 'escape' to exit from a sfinv page to the game. Is this possible?

**Comment by SmallJoker** [comment]
This should solve the problem: (untested)

```Diff
diff --git a/mods/sfinv/api.lua b/mods/sfinv/api.lua
index fdb652b..2901255 100644
--- a/mods/sfinv/api.lua
+++ b/mods/sfinv/api.lua
@@ -162,6 +162,14 @@ minetest.register_on_player_receive_fields(function(player, formname, fields)
 		return false
 	end
 
+	if fields.quit then
+		local oldpage = sfinv.pages[context.page]
+		if oldpage and oldpage.on_leave then
+			oldpage:on_leave(player, context)
+		end
+		return
+	end
+
 	-- Was a tab selected?
 	if fields.sfinv_nav_tabs and context.nav then
 		local tid = tonumber(fields.sfinv_nav_tabs)

```

**Comment by rubenwardy** [comment]
Documentation should explicitly say that it's only when changing pages

**Comment by paramat** [comment]
I'm using 'on enter' and 'on leave' to trigger a certain action only when in a sfinv page, it's essential that 'on leave' is called when exiting to game, after all doing so is actually leaving the sfinv page, so i can't see why this is not done.

**Comment by rubenwardy** [comment]
I remember, the reason was that there isn't a callback for the inventory opening. I suggest making an on_close instead

**Comment by paramat** [comment]
I suspected there wasn't a callback for inventory close, thanks. There is already a request for a callback on inventory open so i can add my request to that.
