### ISSUE TITLE
'Concept approved' issues to help people contribute to MTGame

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1922]
I was contacted by someone concerned about the experienced difficulty of contributing to MTGame due to not knowing what is acceptable or wanted.

When we have a task that we want to offer to contributors to code, the request is often buried in discussions and not easily findable or searchable. In this situation i suggest that we open a new issue, labelled 'Concept approved' that specifies what is essential in the contribution, so that the contributor at least knows there is a fair chance of their work being accepted and not wasted.

I'll add the label and start with one i have in mind.

**Comment by rubenwardy** [comment]
how about an approved label? To indicate that we're willing to accept fixes

**Comment by paramat** [comment]
Maybe i misunderstand but you mean the issue needs to be approved by 2 core devs? Certainly each issue will be the place core devs can discuss what is required so i guess the requirements do need approving.

**Comment by rubenwardy** [comment]
No, just one can mark it as approved. No need to be so strict

**Comment by paramat** [comment]
Yes i'm unsure abou tthe label wording.
'PR request'?

**Comment by paramat** [comment]
Changed label to 'Specific PR request'.

**Comment by rubenwardy** [comment]
Specific PR request is still value, I do think it should be  Concept approved   or  PR Guidance Given

**Comment by rubenwardy** [comment]
how about "Contributions Welcome"

**Comment by Ezhh** [comment]
I like Concept Approved. Not knowing when a concept is approved seems to be the problem, so that would help a great deal.

The only issue I see is if one dev likes a suggestion and marks it Concept Approved, then the others don't... but marking them as such would also give the other devs opportunity to speak up if they don't agree, and we'd then (hopefully) see a debate to settle it.

**Comment by Fixer-007** [comment]
>"Contributions Welcome"

nice one

**Comment by MarkuBu** [comment]
Well, I don't contribute anymore because it is gauntlet running to make a PR. You sometimes have to wait weeks until something happens, than you should make dozens of changes an you have to rebase over and over again because something else has changed while you wait.

And all of that just because of a few lines of code.

**Comment by Ezhh** [comment]
About "Contributions Welcome" - I'd like to think they are always welcome!  What I want to know is when a concept/idea has approval. It's possible to say "Contributions Welcome" on any issue without offering any concept as to how the issue should be solved, whereas "Concept Approved" would actually require a concept.

**Comment by paramat** [comment]
Ok thanks i was finding it difficult to come up with a suitable label.

MarkBu, i can understand anyone feeling that way, contributing to an understaffed open source project is difficult.

**Comment by MarkuBu** [comment]
I can understand, that being a core dev is difficult. This doesn't change the fact that merging a PR is sometimes more strenuous than writing and testing the actual code. That takes away the fun.

**Comment by paramat** [comment]
Yes i agree that the submission and arguments, dealing with people, is the hardest part (not even sometimes, most of the time). When i was a contributor it didn't remove the fun for me, it was still worth it, just. However i can understand some people not finding it worthwhile.

I think open source development is inherently the hardest form of development, and you have to be crazy to be a core dev, luckily there are crazy people around, like me and others, the "random bunch of lunatics" as described by c55.

**Comment by rubenwardy** [comment]
done
