### ISSUE TITLE
Utilise world-aligned textures for stairs and other problematic blocks

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1931]
Since this was recently merged https://github.com/minetest/minetest/pull/6105 (https://github.com/minetest/minetest/pull/6075), https://github.com/minetest/minetest/issues/5222, it is minetest_game turn now.

![default](https://cloud.githubusercontent.com/assets/1668792/22864987/484d39ec-f15b-11e6-8099-42516d3aa87e.png)

Details: 
* https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L4439
* https://github.com/minetest/minetest/blob/master/games/minimal/mods/experimental/init.lua#L504

**Comment by paramat** [comment]
Thanks for the reminder :+1:

**Comment by paramat** [comment]
PR #1935

**Comment by paramat** [comment]
#1935 merged.
