### ISSUE TITLE
Translating minetest_game

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1932]
IIRC engine client-side translations arrived to master, so this can be utilised in minetest_game, but there is huge silence about this.

I will leave this open, please take over this issue.

**Comment by Wuzzy2** [comment]
A lot of translations are readily available here:
https://hosted.weblate.org/projects/minetest/mtg_i18n/

**Comment by paramat** [comment]
But i'm being silent in all languages ..

**Comment by paramat** [comment]
Personally i'm uninterested in working on translations for MTG, but don't mind if others do. I'm also neutral about whether MTG should have translations.

**Comment by SmallJoker** [comment]
Yet there's no C++ version of the "wheel re-inventing" gettext po file parser in the core - which significantly slows the interest in this feature. I'd love to see the translation coming, but I'm afraid this will have to wait for another release to translate it properly.

**Comment by Wuzzy2** [comment]
I believe there's a PR somewhere in the deep dark dungeons of the Minetest issue tracker which adds at least a basic toolchain for translators. I can't find it at the moment.

**Comment by runsy** [comment]
The priority of this should be super high!!!

**Comment by paramat** [comment]
Too much work to get it done before 5.0.0 though.

**Comment by Ekdohibs** [comment]
I think having the framework for the translations, even if the game is not translated but can be, should be an important goal before the release though.

**Comment by paramat** [comment]
I look forward to your PR :) I'm too busy, as are all other MTG devs.

**Comment by Zweihorn** [comment]
Please have a look at my proposal on [[Mod] Internationalization Library [intllib]](https://forum.minetest.net/viewtopic.php?f=11&t=4929&p=346447) in the [Minetest forum](https://forum.minetest.net/).

**Comment by Zweihorn** [comment]
> Intllib is not an option for online multiplayer games like Minetest Game. 

I tend to oppose and IMHO the LUA-code mod **Intllib** a helpful and realiable tool.

Please refer to the forum topic [game_intllib - Re: [Mod] Internationalization Library [intll]](https://forum.minetest.net/viewtopic.php?f=11&t=4929&p=346616#p346616) for my little **games_intllib** project and first results. Currntly, this WIP covers 36 LUA-code files of the game mods of the current _minetest_game-5.0.1_ already.

Please note the option one may disable the _game_intllib_ but could continue in using the **locale** folder and the _template.pot_ as well as the more appropriate _PO-files_ (e.g., _fr.po_, _de.po_, _ru.po)_ for a **client translation solution** independantly. The same would apply to most if not all external mod files too, I presume.

**Comment by Zweihorn** [comment]
Please have a look at my fork and I have already successfully changed about 400 lines of code of the existing mods by introduction of a `S("string")` enclosure as contribution in support of the MT game translation efforts. The 'game_intllib' mod may be not optimal but allows a MT translation with the current MT core and game software in a pragmatic way.

Please consider a visit at: 
- My fork and new branch [game_intllib](https://github.com/Zweihorn/minetest_game/tree/game_intllib/mods/game_intllib) on Github
- my 2d8d7f4 commit and report for details 

For a view on first GUI results please consider to look at my recent [contribution in the MT forum](https://forum.minetest.net/viewtopic.php?f=11&t=4929&p=346791#p346791).

There are some minor slips in the accompanying files like README.md and the need of an update to the documentation. I will irregularily check the code and seek to gradually improve my contribution before a pull request. Any advice from the MT developers would be welcome.

Thank you and happy hacking.

**Comment by Wuzzy2** [comment]
So you deliberately ignore the fact that you will basically force all clients on the same translation that the server has. But you keep pushing your approach very hard for … reasons? I don't get it. You are not making sense.
You DO realize you are working against your own stated goal of “freedom to enjoy MT in your language of choice.”, right? Your approach will give users exactly no choice, so you're not helping.

Let me also remind you that you're not the first one who attempted this and failed. MTG devs have already (and rightfully) rejected another attempt to push basically the exact same idea into MTG:

https://github.com/minetest/minetest_game/pull/1556

Your approch is exactly the same. Therefore it is going to fail.

However, the part of your commits that add the `S()`es might still be useful in some way, but it would still need lots of repairing to make it compatible with the native translation system (`minetest.get_translator`).

**Comment by Zweihorn** [comment]
[We need fresh air, some friendly thoughts and a more open attitude.](https://forum.minetest.net/viewtopic.php?f=11&t=4929&p=346812#p346812)

There is always the chance of failure but this should not matter most.

**Comment by Zweihorn** [comment]
[Add support for MT 5 game translation #2364 ](https://github.com/minetest/minetest_game/pull/2364)

Voila!

**Comment by paramat** [comment]
#2466
