### ISSUE TITLE
Beds: Allow chatting with other players while laying in a bed

### ISSUE THREAD

**Issue by orbea** [minetest/minetest_game#1933]
Can it be made so that players can still chat while laying in a bed? Currently the chat key (`t`) does nothing while laying in a bed and its quite frustrating to have to leave and reenter the bed if the need to chat arises.

**Comment by DS-Minetest** [comment]
The problem is that chat can't be opened with an open formspec.
(Engine change needed?)
It could maybe also be nice to chat while looking into a chest.

**Comment by orbea** [comment]
Yes, chests could use this too as could furnaces.

**Comment by paramat** [comment]
Engine issue https://github.com/minetest/minetest/issues/3928

**Comment by orbea** [comment]
Thanks for the link. I looked for preexisting issues, but apparently not well enough.
