### ISSUE TITLE
Can't register new chest from 3rd party mod

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest_game#1936]
If I want to call default.register_chest() from an external mod I get the naming convention error, because "default:" is automatically added to the chest name.

So if I want to add a new chest I have to edit the default mod or I have to clone and modify the register_chest() function. Or did I miss something?

**Comment by rubenwardy** [comment]
Chests should be a separate mod imo

**Comment by DS-Minetest** [comment]
If chests should be a separate mod then furnaces have to be moved out of default, too. (But imo an extra file for chests would be enough.)

So, if `":"` (that is not on first place) is found in the name, a `":"` is added to the front, else `"default:"` is added.

**Comment by paramat** [comment]
Does b75a17984a56bb05310bfe575e4ce17509fad43b solve this?

**Comment by SmallJoker** [comment]
@paramat No, it doesn't. The node name should be freely selectable, so people also could overwrite existing nodes this way, as it's already possible with the regular `minetest.register_node` function.

**Comment by orbea** [comment]
I think PR https://github.com/minetest/minetest_game/pull/2643 should fix this issue.
