### ISSUE TITLE
Wool coloring conflicts (dye group issues)

### ISSUE THREAD

**Issue by lenkaplz** [minetest/minetest_game#1940]
When trying to craft brown wool (from wool and brown dye), the output is orange wool, not brown wool. Similar thing happens when mixing dark green dye with wool - the output is green wool, not dark green wool.

The recipe for orange wool is any wool + any item from group dye excolour_orange which includes brown dye as well.

**Comment by lenkaplz** [comment]
I tried playing minetest_game without any other modpack and couldn't reproduce the issue.

**Comment by jastevenson303** [comment]
I experience this with mods, too.  Not sure which, I'm not using
unified_dyes for example.

**Comment by lenkaplz** [comment]
I experience it when I turn on technic mod. However, it is not an issue with the mod itself, but minetest_game, although it doesn't occur without mods.

https://github.com/minetest-mods/technic/issues/370
https://github.com/minetest/minetest/issues/5962

**Comment by VanessaE** [comment]
related?  https://github.com/minetest-mods/unifieddyes/issues/22

**Comment by VanessaE** [comment]
In my opinion, all the unicolor/excolor/basecolor business needs to be completely excised and replaced with simple recipes.

**Comment by qwrwed** [comment]
Issue also occurs with _Dark Grey Wool_, as [group:wool + dye:dark_grey] gives _Grey Wool_ [group:wool + group:dye, basecolour_grey], with the specific recipes for dark grey/green/brown failing to override the general recipes for the regular shades.

**Comment by paramat** [comment]
> In my opinion, all the unicolor/excolor/basecolor business needs to be completely excised

Tempting, i have never got my head around all that. But what about mod breakage?
If dyes are a mess then we could have some breakage, now's the time to do it.

**Comment by VanessaE** [comment]
Are there really any mods out there that use those groups, and can't be tweaked to just use individual dyes?

**Comment by paramat** [comment]
See https://github.com/minetest-mods/technic/issues/370#issuecomment-308819539 seems to be an issue with these base/ex/uni groups. How about we remove ex and uni groups and have just one group type?

**Comment by Ezhh** [comment]
The more I look at dye and wool the more I think they need serious rewriting...

**Comment by tenplus1** [comment]
Does any other mods use the basecolors and excolors groups ? if not rework dye to simple recipe's and use group {dye_red=1 etc.} for colours supported.

**Comment by paramat** [comment]
Even if a few do it won't be many and i think it's worth reworking dyes.

**Comment by paramat** [comment]
From https://github.com/minetest-mods/technic/issues/370#issuecomment-308819539

"This is a minetest engine or minetest_game bug, triggered partly by the default dye mod.

Default wool mod is specifying white wool and any dye in the "basecolor_green" group should produce the brighter green wool, while wool plus anything in the "unicolor_dark_green" should produce the darker green wool.

The default dyes mod puts both green dyes in the "basecolor_green" group: https://github.com/minetest/minetest_game/blob/master/mods/dye/init.lua#L38-L39

The engine is probably just picking the wrong group of the two to match the recipe against."

"So, this is an MTG bug. The engine can’t know which group is more specific (that might be a useful feature, though), so is free to choose either."

**Comment by tenplus1** [comment]
Simplify: https://github.com/minetest/minetest_game/pull/2141 ... you want green then use "group:dye,color_green" in recipe.

**Comment by paramat** [comment]
@tenplus1 do i remember correctly that you did some research and found that very few mods actually use base/ex/unicolor groups?

**Comment by paramat** [comment]
#2186 and #2202 merged. Hopefully issue fixed.
