### ISSUE TITLE
Dungeon loot for multiplayer

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest_game#1941]
It's great to finally have some use for dungeons, but how about multiplayer servers? On a survival server the first players clear the loot around the spawn point and remove the chests

It's just a suggestion: how about none removable chests with an inventory and the same loot for each player?

I know that there is still a way to hide these chests, but players will have a higher chance to get some loot at the start.

**Comment by sfan5** [comment]
I honestly don't see a problem with "first come first served".

**Comment by MarkuBu** [comment]
As long as the loot is worthless, yes. But if you add loot like stronger weapons and armor to the chests then early players have a big advantage, especially on PvP

**Comment by rubenwardy** [comment]
I don't like this. It currently encourages players to explore more to places no one's been. I'd rather the chests were given better content

**Comment by paramat** [comment]
-1 for the suggestion.
