### ISSUE TITLE
register_on_placenode() is not called when placing a tree node

### ISSUE THREAD

**Issue by Reedych** [minetest/minetest_game#1947]
[Video proof](https://youtu.be/IrzdgUUWbqk)

When I place a tree node (of any tree), register_on_placenode() is not called.

**Comment by SmallJoker** [comment]
Thanks for reporting this bug. But this time it's in the wrong repository, as the bug is contained in the builtin/script code of the core features.
https://github.com/minetest/minetest/issues
Please see the above linked PR for a possible fix.

**Comment by Reedych** [comment]
Oops, sorry.
