### ISSUE TITLE
Stable branch with backports

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest_game#1948]
Server owners are missing out on critical bugfixes (since they can't just upgrade mtg as it depends on 0.5 features)
one example: https://github.com/minetest/minetest_game/commit/a1d35f3d69dbed8cd9ce317a11f2bd2f7c816c75

What we need is a new branch e.g. `backports-0.4` with fixes applied to the 0.4.16 state of minetest_game, so server owners can feasibly patch holes found after the last stable release.
This branch can then be merged into `stable-0.4` when 0.4.17 is released

**Comment by Ezhh** [comment]
Please make this happen. :)

**Comment by paramat** [comment]
Concerning https://github.com/minetest/minetest_game/projects

Features not for 0.4.17:

Stairs: Allow crafting slabs and stairs into full blocks again
Creative: Add 'creative' privilege for survival servers
Allow mossy cobble slabs to combine
Default: Expose the formspec getter functions 
Torches: Make liquids drop torches as items
TNT: Allow a custom explosion sound to be used

**Comment by sfan5** [comment]
Backports branch updated with @paramat's changes.
