### ISSUE TITLE
Add top/bottom texture for straw nodes

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest_game#1953]
Straw stairs look weired if they use a different texture like this

<img width="179" alt="31487866-2d2e1f4c-af3c-11e7-90a0-685550df9377" src="https://user-images.githubusercontent.com/3686677/35699392-d7d588b0-0787-11e8-9dfb-3e0b6b256302.png">

If we add a top and bottom texture it could look like this

![33120569-c118e5c4-cf72-11e7-8ee2-ff61cc6ff241](https://user-images.githubusercontent.com/3686677/35699398-dd84203c-0787-11e8-8770-62f398703a75.png)

MTG can use the same texture for all sides, just make a copy of the straw texture and rename it, texturepack converters for Minecraft texturepacks can add support for the file `hay_block_top.png`

Top and Bottom texture should also be used for the full straw block and slabs

**Comment by paramat** [comment]
Good suggestion, although the reason that looks bad is because someone added a string. We should add a string ourselves in MTG if we do this.

**Comment by tobyplowy** [comment]
@paramat that someone is me :)
It makes sense how else would the straw be held together?

**Comment by paramat** [comment]
Yes, but the error is in the texture pack.
However we could make straw use 2 different textures, i'm ok with this but not inspired to do it myself. Gambit's pixelbox texture pack, from which many MTG textures are from, has sides and top/bottom textures:

![default_hay_side](https://user-images.githubusercontent.com/3686677/35698384-c79f627a-0784-11e8-89ec-fccc3b2f80f4.png)

![default_hay_top](https://user-images.githubusercontent.com/3686677/35698392-caf2a9c8-0784-11e8-9bc6-c32a5178e1d9.png)

**Comment by Ezhh** [comment]
I'd be against adding a string to the default straw node myself, because one of the main uses I saw for straw in buildings was as roofing, and a string would lead to that looking weird.

**Comment by paramat** [comment]
Good point, there are structures that will look worse with string and were made to have no string showing.
