### ISSUE TITLE
Existing MTG/MT backstory: Copy/paste into here

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1954]
When adding new stuff to MTG it is good to know the already existing backstory of MTG and MT (since MTG can be thought of as the continuation of the game material of MT0.3). But this information is scattered around in the wiki, in IRC logs and at Github.
This issue is intended to be the place to copy/paste this information as anyone comes across it, so that it is all in one place for reference.

Information about the mobs of MT0.3 is helpful (backstory and behaviour), since some of those may return.
Stuff about mese especially, and anything about celeron55's original intentions for MT (i seem to remember it was meant to be a dungeon-raiding game).

Copy/pasted stuff only, no backstory discussions or discussions of features that might use it, or anything else.
However links to sources are appreciated, and very short comments if helpful or necessary are ok.

I will also at some point see if i can get more backstory out of celeron55, if there is any more that is not documented.

**Comment by paramat** [comment]
Will reopen if/when i add stuff here.

**Comment by jastevenson303** [comment]
I heard theories but believe mese is a true mystery.
