### ISSUE TITLE
add light blue dye and wool

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest_game#1957]
The Minetest colour pallet has only 15 colours, the default Minecraft pallet has 16

That makes it difficult if you want to add coloured nodes compatible to Minecraft. Different mods may add multiple dyes.

I suggest to add light blue dye and wool

**Comment by SmallJoker** [comment]
unifieddyes adds that and many other colours if you need them. Just "because Minecraft has it" doesn't seem to be a valid reason to add it here too.

**Comment by MarkuBu** [comment]
I don't want to be forced to install a mod with 1000 colours just because I need one.

If no one is interested in adding this to Minetest I will add it myself and override others if necessary. But that doesn't really help mods that need this colour from unifieddyes

Just want to add a bit more compatibility to Minecraft colours

**Comment by paramat** [comment]
The MC thing isn't a valid reason, needs other reasons.
A new colour may then mean lots of mods then need updating, so it could be disruptive.

**Comment by benrob0329** [comment]
A 16 color palette isn't a bad idea, its consistent with the retro feel of textures and most classic sprites.

**Comment by paramat** [comment]
Yeah i 'numerically' like the idea of 16, but too much disruption for little reason.

**Comment by MarkuBu** [comment]
Minetest Game is a reference. If another color is added to MTG, mods will remove them (sooner or later). If people update Minetest they can update their mods too and everything is fine. 

If a mod adds a color, other mods won't change anything. 

And last but not least: as far as I can see unifieddyes don't add the colors to dyes namespace. Where is the disruption?
