### ISSUE TITLE
Rename inner/outer stairs

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#1958]
Please rename the inner and outer stairs. Oh, I mean the stairs outer and stairs inner. ;-)

Current names:

* “Tin Block Stair Inner”.
* “Tin Block Stair Outer”.

And so on. This is wrong. Please change it to:

“Inner Tin Block Stair”.
“Outer Tin Block Stair”.

**Comment by SmallJoker** [comment]
Why are they wrong? Looks fine to me:
For the current inner stairs, the cut-out edge is on the inside. So what results in the stair effect is on the inside.
The current outer stairs have the cut-out edges outside, which means the stair effect (step-up) occurs on the outside.

**Comment by paramat** [comment]
:+1:

**Comment by TumeniNodes** [comment]
If you rename them this way, it will reflect where they show up in inventory.
At least I "think" I remember this being the reason I set the names that way. I could be mistaken.

**Comment by Napiophelios** [comment]
@TumeniNodes : I think this is about descriptions of inventory items, 
not the actual nodes' names.

I think the proposed name changes are awkward sounding.

This sounds more natural to me:
“Tin Block Inner Stair”.
“Tin Block Outer Stair”.

**Comment by NewbProgrammer101** [comment]
Or just "Tin Inner Stair".
And "Tin Outer Stair".

**Comment by paramat** [comment]
Best it specifies the parent node, so 'block' is needed.

**Comment by TumeniNodes** [comment]
> I think this is about descriptions of inventory items,
not the actual nodes' names.

I think the proposed name changes are awkward sounding.
Maybe just leave it how it is.

@Napiophelios , probably. I seem to always forget about that.
"node name" Inner Stair
"node name" Outer Stair
Would stick to the naming theme better, I would +1 that
It is definitely something which should probably not waste too much time hanging around. If a couple devs agree on this then just make the changes and be done with it... Next! ha

**Comment by paramat** [comment]
> "node name" Inner Stair
"node name" Outer Stair

Yes that's best.

**Comment by paramat** [comment]
Actualy this is not possible as the word 'stair' is in the definition table, and if we change how the description is constructed we break mods.

**Comment by Wuzzy2** [comment]
WTF?! Are you serious? It is not possible to change *a node description*? OMG. This is just stupid.

Why is compability a concern? The inner and outer stairs have NOT been part of a release yet.

Another solution would be to add parameters to set the inner and outer stair node descriptions explicitly. This would also make them translatable, should MTG ever actually adopt the client translations. If you just use string concatenation (like now), translating will become a problem in future (not all languages use the same word order).

**Comment by paramat** [comment]
Oops i thought they were added before 0.4.16, ok will fix.

**Comment by paramat** [comment]
The description lines in each registration are for all stairs not just inner/outer, so it could break mods.
However moving 'inner/outer' before the node description would be ok.

**Comment by paramat** [comment]
I was trying to do "Tin Block Inner Stair" which would have been impossible, and forgot your suggestion is possible.

**Comment by paramat** [comment]
#1968 merged.
Good suggestion, thanks.
