### ISSUE TITLE
Player is half in the ground in 3rd person view

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest_game#1960]
If I play a subgame made for 0.4.16 in the current Minetest 0.5 dev the player is half in the ground in 3rd person view (even Minetest Game for 0.4.16)

![screenshot_20171129_104909](https://user-images.githubusercontent.com/16163058/33368949-67c18662-d4f3-11e7-8e6e-c2ce8591706d.png)

I was able to connect to a server (Mine City Extreme Survival) and it looked like this

![screenshot_20171129_105738](https://user-images.githubusercontent.com/16163058/33369265-42d1237a-d4f4-11e7-8b9e-261dbb599c44.png)

On this server it is even worse because I was able to "xray" the ground in certain positions

**Comment by sfan5** [comment]
> If I play a subgame made for 0.4.16 in the current Minetest 0.5 dev

0.5 is compat-breaking, not a bug.
