### ISSUE TITLE
Super rare item

### ISSUE THREAD

**Issue by ThomasMonroe314** [minetest/minetest_game#1961]
With the Nyan cat being removed, I think that something just as rare should be added to MTG.
It doesn't have to be even remotely related to the cat.

**Comment by SmallJoker** [comment]
Similar issue #1685, which is/was about removing PB&J and not trying to replace the nyan cat.

**Comment by raymoo** [comment]
Green mese? :P

**Comment by ThomasMonroe314** [comment]
perhaps, but I think It should be something completely different from anything previously seen before, maybe even something historical like a credits cube or something like that

**Comment by stas730** [comment]
Reference: https://github.com/minetest/minetest_game/issues/2099
Nyan Cat was removed some time ago. Many players have installed nyancat mod because they didn’t want Nyan Cat to be removed.
Nyan Cat can be added again, but name must be changed to avoid trademark issues. "Nyā Cat" is example ("nyā" is Japanese word, so it can’t be trademarked).

**Comment by paramat** [comment]
With a different name and appearence it would be a new item essentially, Nyan Cat can't be re-added with any similarity due to licensing.
I have half seriously thought about 'Cyan Cat' which could be a cyan kitty, but no rainbow tail.

**Comment by paramat** [comment]
There's not much core dev support for this and we've been through it before. A new rare item may well be good but i think a better approach is to have an idea for the item first, instead of asking for it without the idea.

**Comment by HybridDog** [comment]
There're already white dandelions in minetest: https://www.plantgoodseed.com/products/white-dandelion-seeds-taraxacum-albidum

How about adding a very rare water lily blossom which has its own detailed 3d model (mesh drawtype)?
![img](https://images-na.ssl-images-amazon.com/images/I/61QfV8XeAyL._SL1024_.jpg)
