### ISSUE TITLE
Potential copyright violation

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest_game#1970]
I suggest going through all textures and checking for similarity. In the future, we should completely change the textures (maybe going for 32x32) to be consistent and different

**Comment by Ezhh** [comment]
Would be good to see this prioritised.

**Comment by SmallJoker** [comment]
There are not enough pixels to make it look more different but still correct.
The left one is from our textures. If there are not bigger similarities I don't see a point in changing the textures.

**Comment by rubenwardy** [comment]
It could have been rotated, or a different colour. It's very clearly Minecraft-inspired

**Comment by SmallJoker** [comment]
![grafik](https://user-images.githubusercontent.com/1497498/33808631-504a1f08-ddea-11e7-86f4-5a7cf6dca40f.png)
FTFY /s

**Comment by Fixer-007** [comment]
Remove books /paramat mode off

**Comment by CloudyProton** [comment]
Recolored guidebook from a mod which probably also infringes on something somewhere
![guide_book](https://user-images.githubusercontent.com/34248863/33810977-4e47c5e4-ddda-11e7-966b-afe81d8b93eb.png)
![guide_book_large](https://user-images.githubusercontent.com/34248863/33811027-f96190f4-ddda-11e7-822c-dc0842694e37.png)

**Comment by Fixer-007** [comment]
adventuretest:
![default_book](https://user-images.githubusercontent.com/16494741/33811052-1a2713c8-de16-11e7-84c9-5ca93d3dc5a9.png)
carbone-ng:
![default_book](https://user-images.githubusercontent.com/16494741/33811053-203143e2-de16-11e7-8961-78395f9b0218.png)
grailtest:
![equipment_book](https://user-images.githubusercontent.com/16494741/33811060-31890292-de16-11e7-8c5b-240cb52208d8.png)
![equipment_book_written](https://user-images.githubusercontent.com/16494741/33811062-338404b6-de16-11e7-8a9b-41791c68f21a.png)

no idea about their licenses

**Comment by TumeniNodes** [comment]
If a move to 32x32 got a high vote, it would probably be better to set for a long term goal, somewhere into the 0.5.0 series.
 Textures take some considerable time, if the desired outcome is "nice", and unique. It might also make sense to put a small team together for the task, as well as putting up some contests for some textures, as that sort of thing is really good for community moral.

There are various ways in which this particular texture could be modified so there is no mistaking.
Set it straight on or, make as close to an M and a T on the cover or, simply just a white band.

The 4 Fixer-007 provides from other mods/TPs are decent (bordering, very nice), assuming the licenses are open.

On a side note, is it just me, or do the first 2 make one particularly hungry for an icecream sandWhich?

**Comment by C1ffisme** [comment]
Change the book if you want, but please don't make the default textures 32x32. Using High-Def textures badly is the cardinal mistake of every single generic mobile Minecraft clone.

As for the book, I feel like mentioning that Minecraft has a new graphic designer making slight edits to all of Minecraft's textures, so our texture is likely going to look less like the book after that anyway. Still, I suppose an edit might not hurt...

**Comment by Ezhh** [comment]
If Minecraft changes theirs, it doesn't make that this was so clearly a copy suddenly okay.

Random book I made:
![default_book](https://user-images.githubusercontent.com/7035183/33813977-113d52aa-de1f-11e7-80ec-b24c9b105bf8.png)
I doubt it's good enough for use, but thought it was worth looking at a book from a slightly different angle and a different colour.

**Comment by paramat** [comment]
Not 32x32, item textures should be the same resolution as node textures, also think about how each pixel is rendered with all its internal faces https://github.com/minetest/minetest/issues/6720
Very good idea to replace similar textures, and a good chance to move away from brown.

**Comment by paramat** [comment]
![default_book128](https://user-images.githubusercontent.com/3686677/33817662-88fa2f84-de38-11e7-9a01-2ac0fdd3e18b.png)

Many of our textures are from PixelBox texture pack already, which we have permission to use, this one is good, different angle, design, thickness and colour. Can anyone make a 'written' version?

**Comment by CloudyProton** [comment]
Two variations; labeled & pagemarked, and belt bound as in the past.
![proposebookwritten](https://user-images.githubusercontent.com/34248863/33818364-7a7140c2-de12-11e7-8b64-3c0482331609.png)
![proposedbookwritten2](https://user-images.githubusercontent.com/34248863/33818365-7a8d2d82-de12-11e7-886e-45bd1a06b743.png)
![33817662-88fa2f84-de38-11e7-9a01-2ac0fdd3e18b](https://user-images.githubusercontent.com/34248863/33818372-8547964a-de12-11e7-983d-c7ad4bbaf428.png)

**Comment by paramat** [comment]
Nice. I prefer the beltbound one. Can i make a PR using these with CC BY-SA 3.0 for your version?

**Comment by TumeniNodes** [comment]
Excellent, two very good replacements. Nice and quick too

**Comment by paramat** [comment]
PR #1972

**Comment by BrunoMine** [comment]
Textures 32x32 seems very pleasing to me

**Comment by CloudyProton** [comment]
Absolutely. Let me know if they need touching up.

**Comment by paramat** [comment]
#1972 merged.

**Comment by dsohler** [comment]
:-1: for 32x32 textures.

The new book texture looks good!

**Comment by Wuzzy2** [comment]
The texture has been changed, don't forget to close this!

**Comment by Ezhh** [comment]
I believe it's open since there are likely others worth checking/reviewing. I would do this, but since I've never played the other game, it would be better for someone familiar with it to check.

**Comment by rubenwardy** [comment]
Ezhh is correct, I left it open as there may be other cases of similar textures

**Comment by sofar** [comment]
Ideally, someone goes over everything doing a reverse image search at some point.

**Comment by paramat** [comment]
I'm not familiar with MC textures either.

**Comment by Ezhh** [comment]
Question: how similar is too similar? Where do we draw the line? For example, I noticed from some quick image searches of tree textures that MC birch tree looks very similar to MT aspen tree, yet the textures are actually different when you look closely. They are the same colours and have the same basic pattern and design, but so do the trees themselves and it wouldn't really be possible to do something much different with the MT texture still being recognisable as the tree. 

Sofar's suggested approach probably is what's needed here, but I struggle to know what's okay and what isn't when comparing images.

**Comment by sofar** [comment]
Doing a reverse image search should just be used to see if anything is an exact copy.

We don't care about how similar things are, what we care about is that it isn't created from a proprietary work. If someone made something from scratch that happens to looks "somewhat" like another work, that's probably OK. But if someone added a few pixels or colored some other work, that's not OK.

**Comment by TumeniNodes** [comment]
Another difficult aspect to this is, when/if someone goes through all the MC textures to compare, they will need to look through all the release versions and changes.
Even old MC textures are still covered under their license.
