### ISSUE TITLE
burn time adjustment per fuel item

### ISSUE THREAD

**Issue by ThomasMonroe314** [minetest/minetest_game#1975]
I had an idea when replying to #1974 
what if the burn time was changed using a multiplier per fuel item?
lets say you cook something with pine wood IRL, the wood would(lol) burn much faster, but also much hotter than say, for example jungle wood, which would burn slower, but with less heat.
The same goes for coal, it burns slowly, but with more heat than both of the aforementioned items

**Comment by paramat** [comment]
The 'Burn time' parameter is total energy released, not speed of burning. So are you suggesting we alter the speed of cooking by adding a new parameter?

**Comment by ThomasMonroe314** [comment]
yes that is what I was suggesting

**Comment by paramat** [comment]
Ok i think that's not worth adding :-1:

**Comment by raymoo** [comment]
It could make sense to have coal cook things faster, to balance it against cactus spam. I don't know if it's worth it to have differences between different woods though, since there is not much difference in effort required for farming the different kinds of wood.

**Comment by ThomasMonroe314** [comment]
Meh, it was a good idea, I guess just not for this game

**Comment by rubenwardy** [comment]
I personally think it's a nice feature, would have to be well to avoid overcomplication

**Comment by An0n3m0us** [comment]
This will require an engine change to add a new argument to `minetest.register_craft({` so that the value can be loaded by `minetest.get_craft_result`.

**Comment by paramat** [comment]
Hmm, supported by 1 core dev but disapproved by 2 (Ezhh thumbed up my comment above) and 2 years old. So do we close this?

**Comment by An0n3m0us** [comment]
It's a great idea and unless anyone is willing to make the engine change to add this, I think we should close it for now.
