### ISSUE TITLE
Redundant words in book interface

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1978]
Seems like a recent change:
![speg9er](https://user-images.githubusercontent.com/16494741/33968116-1ed4d97c-e06f-11e7-98f8-7a1335ad7902.png)

**Comment by SmallJoker** [comment]
Engine issue.
The issue source is the strange use of the `textarea[]` formspec element, which was changed in https://github.com/minetest/minetest/pull/6510 . That raised problems with other mods that used the label field for readonly text areas: https://github.com/minetest/minetest/pull/6510/files#diff-65f34680878a6bd86f3a59ebc0c06c6dL1119
Finally, blame points at me for the compatibility bit for these cases: https://github.com/minetest/minetest/commit/6b23cab
Will try to find a solution.
