### ISSUE TITLE
Minetest health bar offset

### ISSUE THREAD

**Issue by masrourmouad** [minetest/minetest_game#1981]
minetest health bar offset
![capture d ecran_2017-12-15_19-28-46](https://user-images.githubusercontent.com/403487/34057317-61ba23fe-e1ce-11e7-9525-168a87a7f167.png)

**Comment by SmallJoker** [comment]
This issue is not minetest_game related, as it could be observed with any other subgame. Please report it in the engine repository: https://github.com/minetest/minetest
