### ISSUE TITLE
use_texture_alpha for xpanes

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest_game#1983]
I suggest to a add use_texture_alpha option to xpanes definition. I tried to make colored glass, but it fails because this option is not available

Add

use_texture_alpha = def.use_texture_alpha or false,

to definition of xpanes and xpanes_flat. This doesn't effect other registered nodes and adds the option to add colored glass panes

**Comment by Fixer-007** [comment]
Coloured glass is also buggy because of no z-sorting :(

**Comment by MarkuBu** [comment]
But this option can be added anyway and I hope, z-sorting will be fixed soon

**Comment by paramat** [comment]
Do glass and obsidian glass need it too?
What about existing texture packs that may rely on this not being set, might they be affected?

**Comment by MarkuBu** [comment]
The colored glass bug doesn't really effect glass panes

**Comment by paramat** [comment]
It will if you use semi-transparency, although maybe to a different degree due to xpanes not being cubic nodes.

**Comment by MarkuBu** [comment]
It will, but you don't see it

**Comment by paramat** [comment]
Ok, if coloured glass xpanes are fairly usable (not too buggy) this is fine.

**Comment by MarkuBu** [comment]
Looks like this. 

![screenshot_20171218_150722](https://user-images.githubusercontent.com/16163058/34109876-3e027612-e405-11e7-8c0b-a0d8068848dd.png)

Only if you look through a pane to another pane they are invisible. But I think this is currently acceptable because in most cases you may do something like this

![screenshot_20171218_151042](https://user-images.githubusercontent.com/16163058/34110035-bbc323da-e405-11e7-8de5-771febb06a00.png)

But anyway, adding this option doesn't change the current behavior. Normal glass panes still look like before. It just adds the option to make colored stained glass panes. If z sorting is fixed the visual issues will disappear automatically.

**Comment by paramat** [comment]
Thanks, i support this then.

**Comment by paramat** [comment]
@MarkuBu that means if you make a PR it will be merged.

**Comment by Ezhh** [comment]
@MarkuBu Are you interested in doing a PR for this? If not, I've had a mod that does the same thing for over a year now, so would be happy to take a look.

**Comment by MarkuBu** [comment]
Done right now xD

**Comment by paramat** [comment]
#1997 merged, good suggestion.
