### ISSUE TITLE
furnace missing sanity check for fuel

### ISSUE THREAD

**Issue by ac-minetest** [minetest/minetest_game#1986]
PROBLEM:
1. suppose you have item with long burn time that requires a lot of fuel.

2. put item in furnace, add any fuel (1 piece of wood will do) and quickly go away so that area unloads.
wait however long is needed for smelting

3. come back.. your item is magically smelted, even though the fuel was clearly not sufficient (need to add missing FUEL CHECK here)

furnace.lua:

   ```
 minetest.register_node("default:furnace", {
    ...
    on_timer = furnace_node_timer,
    ...
    }

    local function furnace_node_timer(pos, elapsed)

    ...
    if fuel_time < fuel_totaltime then
       -- The furnace is currently active and has enough fuel
       fuel_time = fuel_time + elapsed
            if cookable then
           src_time = src_time + elapsed
          if src_time >= cooked.time then
                   -- Place result in dst list if possible
                  PROBLEM HERE, MISSING FUEL CHECK
```

FIX: check if fuel.time is enough to smelt item or abort smelt process.

**Comment by sofar** [comment]
`fuel` is `nil` at this point, therefore `fuel.time` will crash. What do you mean by `fuel.time`?

**Comment by sofar** [comment]
This is broken for sure (confirmed), but I'm stumped for now as to what is a proper fix for this issue. For testing, I changed the `cooktime` for gold lumps to 30 seconds.

**Comment by paramat** [comment]
#1988 merged.
