### ISSUE TITLE
Changing biomes with altitude

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#1993]
I used to feel that the all biomes should continue to world top, so that all biomes are present however the terrain is customised. However now i feel it would be better to remove a few biomes with altitude, especially rainforest which doesn't make sense high above the clouds.

Realistically, as  you go higher it gets drier and colder, however if we strictly apply this everything would be tundra above y = 256/512 which would be boring and lacking in resources.
So my idea is to leave coniferous forests remaining to provide wood resources, coniferous forest seems suitable for high altitude.

I am considering removing rainforest and deciduous forest, this makes survival at high altitude a little more challenging as apples are not available. You would also need to take your own cotton seeds as there is no junglegrass.
Also, savanna and desert would be removed to remove all the hottest biomes. We still have 2 other deserts so will not be lacking deserts at altitude.
I would probably remove biomes one by one with altitude so that it is not all at once and causing too much of a sudden change all at one y value.

![newbiomes9invert](https://user-images.githubusercontent.com/3686677/34323504-74f63288-e844-11e7-96dc-6f03fa201003.png)

^ Current biome system

Horizontal - Temperature
Vertical - Humidity

ICE Icesheet
TAI Taiga
COF Coniferous forest
DEF Deciduous forest
RAF Rainforest

TUN Tundra
SGR Snowy grassland
GRA Grassland
SAV Savanna

CDE Cold desert
SDE Sandstone desert
DES Desert

**Comment by Fixer-007** [comment]
Ignoring of altitude always bugged me, with this change it should be more realistic. Maybe density of coniferous forests should decrease slowly with altitude too.

**Comment by Ezhh** [comment]
Though I like the idea of biome changes with altitude (even strongly in favour of it), I would hate to see desert mountains/cliffs vanish. Those have always been the environments I loved best in the game and they are already very rare.

**Comment by MarkuBu** [comment]
I would like to see vertical blending. Then you can define the high biomes yourself.

I know that it is difficult, but would be the better solution

**Comment by paramat** [comment]
Yes i like the red stone mountains too. How about i remove those last at y = 512?

**Comment by paramat** [comment]
Maybe i won't remove those at all.

**Comment by paramat** [comment]
PR #1996

**Comment by paramat** [comment]
Vertical blending is desirable, i just haven't worked out how to yet, it's tricky.

**Comment by paramat** [comment]
So i realised that removing red desert at altitude would cause a sudden change of stone colour in a tall mountain, so decided against that.

**Comment by paramat** [comment]
I and others are unsure about this now, no need for an issue.
