### ISSUE TITLE
What kinds of new gameplay belongs in MTG?

### ISSUE THREAD

**Issue by raymoo** [minetest/minetest_game#1999]
How would I determine if some gameplay element would belong in MTG and not a mod?

These are some gameplay elements I can currently identify in MTG, for reference (definitely incomplete since "gameplay element" is not so well-defined):
* Digging / building
  * Building structures for aesthetic purposes
* Crafting
  * Making tools, with different but linear tiers of material quality
* Exploration of the landscape
* Resource collection (stone, wood, ores, plants)
* Liquids and liquid flow
* Smelting things in a furnace
* Farming (Trees, plants, field crops)
* Beds
* Boats
* Minecarts

**Comment by SmallJoker** [comment]
Development direction: #515

In general, the new mods would have to ..
* be fast (optimized), particularly on crowded servers
* offer an API that allows easy use of the mod
* be to a degree helpful in both, survival and creative

**Comment by raymoo** [comment]
@SmallJoker I don't agree with your last criterion since mobs are planned and are pretty useless in creative mode. The other three are technical requirements that I agree with, but don't really say anything about the actual feature other than it should be possible to implement / design nicely.

I'll post in #515 some thoughts I've had about how to select for new features.

**Comment by paramat** [comment]
As discussed elsewhere each suggestion can only be assessed specifically, some sort of list would be too vague to be useful. If anyone has a specific suggestion open an issue to discuss it.
This has been discussed at great length in #515 so no need for a duplicate.
