### ISSUE TITLE
Dedicated 'beachgrass' / 'marram grass' for grassy dune biomes

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2002]
Currently the standard long grass decorations are extended down onto dune biomes to create the grassy dunes. The problem is that these grasses have a low and scattered density which makes the dune biomes often very un-grassy and barely noticeable.

I suggest adding a new grass type 'beachgrass' or 'marram grass' https://en.wikipedia.org/wiki/Ammophila_(plant) for use on the grassy dunes in order to allow a higher density and a distribution tuned for the grassy dunes.

I can do this task myself but welcome any textures. The texture can have some trapped sand at it's base to help it blend.
This together with #2001 is to make the grassy dune biomes have more presence.

**Comment by TumeniNodes** [comment]
Are you open to doing these double high? Dune grass is normally long & high

**Comment by MarkuBu** [comment]
> Dune grass is normally long & high

Not necessarily. Last week I was at the Baltic sea. The grass is as high as wheat

**Comment by paramat** [comment]
I intend for these to be long but no more than 1 node high, maybe 2 or 3 different long lengths. Apparently these are realistically 60-120cms so 1 node seems ok to me, this will also keep texture pixels the correct size.

**Comment by Ezhh** [comment]
This would be nice to see, and one node high sounds about right to me.

**Comment by TumeniNodes** [comment]
You know, you _could_ just take the dry_bush texture, with the mesh option as you have at [https://github.com/minetest/minetest_game/pull/2003#issue-285298629](url) , and simply recolour to suit. Maybe make a few minor changes to the shape.

Just an idea, I think would look good

**Comment by paramat** [comment]
@TumeniNodes i am experimenting with deriving a texture from your 'refreshed' texture pack grass, is it ok to derive from that?

**Comment by paramat** [comment]
#2027 merged.
