### ISSUE TITLE
Show the name of currently wielded item on HUD

### ISSUE THREAD

**Issue by mflink3012** [minetest/minetest_game#2007]
I would like to offer my mod name\_wielded\_item [here](https://github.com/mflink3012/name_wielded_item) to be included into the default mods of the minetest-game.
It shows the currently wielded item on the players HUD.

**Here is the story/background why I request to add this mod:**
> I recently build a large building from sandstone and sandbricks.
> While building I often ran out of sandstones and had to craft some new from gathered sand.
> So often I had a stack of sand in my hand - also to use it for getting on different heights.
>
> While building it came, that I sometimes inadvertently mixed building with blocks of sand instead of sandstone, because it has very similar picture and texture.

So I decided to help me and others by showing what is wielded currently and implemented this short mod.

Including it to the minetest-game as a default-mod will help others too and make their lifes easier.

Edit: Link to my repo didn't work.

**Comment by Ezhh** [comment]
Though I understand why some people would find this helpful, personally I would find it irritating, so I would request that if such a thing is added it is purely optional.

**Comment by paramat** [comment]
> While building it came, that I sometimes inadvertently mixed building with blocks of sand instead of sandstone, because it has very similar picture and texture.

Ok, but it is very rare to have identical looking nodes that confuse, and i consider sand and sandstone clearly visually different, so this should obviously remain an optional mod. Anything in MTGame has to be very fundamental because MTGame is a simple game / mod base.
:-1:

**Comment by mflink3012** [comment]
I agree, changing the picture to differentiate sand and sandstone clearly will help (for this blocks) too.

Maybe my mod is not exactly what should be integrated into the basic game, but its idea seems to be a good idea - as an option to be de/activated?

**Comment by TekhnaeRaav** [comment]
I certainly would like this feature, but I do see why this should be an option.
Maybe it could be a minetest.conf setting? Just to not clutter the menu.

**Comment by paramat** [comment]
I find sand and sandstone visibly different, textures have to be suitable, we can't alter textures to avoid similar looking ones. In MTG we have no identical textures, so there is no need for this mod to be in MTG.

However it can happen in other mods and other subgames, so such a feature, if needed, needs to be an engine feature, showing wielded nodename perhaps in F5 debug mode or wherever. So you can open an issue in the engine.

It's not often that a player is switching between 2 visually identical nodes, and in this situation the player can use memory: 'this is in slot 1, that is in slot 2' or place one node first, then move the desired node into slot 1 to place the other node. So it'slow priority.
