### ISSUE TITLE
ERROR:sounds = default.node_sound_stone_defaults(),  and sounds = default.node_metal_stone_defaults(),

### ISSUE THREAD

**Issue by astrayar** [minetest/minetest_game#2012]
in 4.16  i see this in most of my mods like homedecor, moreores, moreblocks, technic, the main ones... and how can it be fixed cause it seems they dont exist in 4.16 or it doesn't know how to label them cause it says they have nil value...  normally you have sounds in mods but these direct to main game and if i put : in front it acts like its a foreign symbol and if i put minetest_game: ... before it  it also then says its a nil value and in sounds there is no default sound stone or metal like before  there is a dig metal  and dig... but  what do i do i want to use the mods i love  these are main mods ? ubuntu 16.04 version or in windows 10 same issues arise... i could revert back to 4.15 i guess... sigh! then i run into other issues cause mods are set for the 4.16 version supposedly?  HELP!

**Comment by paramat** [comment]
Are you using latest MTGame dev version? Metal sounds were added only recently.
Please copy paste the entire error messages you get.

**Comment by astrayar** [comment]
Says Dev version yes !  Ok I will get full code error

**Comment by paramat** [comment]
@astrayar =)

**Comment by JurajVajda** [comment]
> sounds = default.node_metal_stone_defaults()
in the title of this issue is incorrect, the correct syntax is `default.node_sound_metal_defaults()`
no wonder it throws error :)

**Comment by astrayar** [comment]
Thanks I will change them around in all the mods they show up in ... Thank
you so very much... I reverted back to 4.15 for now but with that I can go
back to the new version and fix things 😎

**Comment by paramat** [comment]
Ok closing for now, can reopen if you still have problems.
