### ISSUE TITLE
Pine trees sometimes fail to grow in snowy areas

### ISSUE THREAD

**Issue by clinew** [minetest/minetest_game#2014]
Planting a pine tree sapling on 'default:dirt' in a snowy area (there are snowy blocks nearby) causes a race condition between the pine tree sapling growing and the 'default:dirt' becoming 'default:dirt_with_snow'.  The 'can_grow' function checks for membership in the 'soil' group, of which 'default:dirt_with_snow' is not a part of.

**Comment by paramat** [comment]
Oops will fix, there was some debate about whether 'dirt with snow' should be in the soil group, now we have a reason to do so.

**Comment by paramat** [comment]
See #1755

**Comment by clinew** [comment]
It makes sense to not let sapling grow on snowy soil -- perhaps a check in the function that turns dirt into dirt_with_snow that won't do so if a sapling is above it?

**Comment by paramat** [comment]
I'd rather keep it simple, that function is nicely general currently.

**Comment by clinew** [comment]
Gotcha -- I haven't looked at it.

**Comment by paramat** [comment]
PR #2015 
This is also more consistent with all other dirt nodes, it is soil after all and not necessarily frozen ground.

**Comment by paramat** [comment]
#2015 merged.
