### ISSUE TITLE
Remove spinning inventory items

### ISSUE THREAD

**Issue by TekhnaeRaav** [minetest/minetest_game#2018]
>I downloaded the minetest_game today (not the release)

and I noticed in it that the inventory and hotbar images rotate. If there are reasons or uses for this I would like to know what, but otherwise this feature is kind of annoying. I would hope it would be removed.
My reasons may be only by personal preference but, it is just useless on the non-3D objects and just makes it so that you can't see the item for a time. I have never had a problem understanding the appearance of any of the 3D nodes so even on these it seems useless.

Any opinions on this?

**Comment by paramat** [comment]
It's an engine issue. The spinning when selected is optional and off by default, there's a setting for the option.
```
#    Enables animation of inventory items.
#    type: bool
# inventory_items_animations = false
```
