### ISSUE TITLE
Creative Inventory Icon Issues

### ISSUE THREAD

**Issue by Ezhh** [minetest/minetest_game#2019]
If you look closely at the cross in the image below, you'll see it's quite badly distorted. The lefthand side is fatter, while the single pixels at the innermost points from the top and bottom are tiny compared to the ones from the sides.

![brokenthing](https://user-images.githubusercontent.com/7035183/34966589-d380062c-fa54-11e7-9d2e-51e22bb80549.png)

I assume this is due to how formspecs adjust based on screensize, and with an image that has so few pixels in it, unless you adjust to a window size that happens to work just right (for example, full screen), you are going to see the distortion. Since I value the ability to resize MT whenever I feel like so it fits nicely with whatever else I have on my screen, this is both really noticeable and really annoying.

**Comment by Ezhh** [comment]
I much prefer how they used to be and never once had an issue with them.

This, on the other hand,  is a terrible change and looks really bad. Can it please be considered for reverting unless someone is willing to get high resolution images in instead?

**Comment by paramat** [comment]
I support a revert (except dustbin).
Are you ok with the dustbin that has been used for a long time? There isn't really a text replacement for that.

**Comment by Ezhh** [comment]
I don't mind the dustbin. The colour makes it much more subtle as well and that helps. It's just the other icons, especially that cross, which really catch my eye.

**Comment by TumeniNodes** [comment]
revert. never fix what is not broken

**Comment by paramat** [comment]
However, first let's try some high-res icons first, the original PR actually asked for an effort to reduce that distortion, so the PR was merged to quckly, a mistake, the current appearence is not acceptable.

**Comment by paramat** [comment]
Yes it seems high-res helps a lot, i made a 128x128 cross and resized the screen, note how bad the search icon becomes:

![screenshot_20180116_021245](https://user-images.githubusercontent.com/3686677/34968776-225350e8-fa63-11e7-931b-72cacc54213e.png)

![screenshot_20180116_021317](https://user-images.githubusercontent.com/3686677/34968779-26bc4388-fa63-11e7-8898-3935dd702b82.png)

![screenshot_20180116_021337](https://user-images.githubusercontent.com/3686677/34968781-2b08437e-fa63-11e7-97ba-b3d9d8fdfb22.png)

**Comment by Ezhh** [comment]
@paramat That x looks huge and awkward.

If this was done properly, you should get roughly the same amount of space around each image, and it should be roughly equal on each side of each image as well.

I really have to echo TumeniNodes: don't fix what isn't broken. This should not have been merged, and the fact that a good set of icons wasn't produced in all that time suggests it's unlikely to happen.

**Comment by paramat** [comment]
Yes that was just a test, it's too big.

**Comment by paramat** [comment]
2 hours later, i have found the solution is to create a high res image then blur it slightly, the blurring is what tames the scaling implementation. It's not perfect but much improved.

![screenshot_20180116_043946](https://user-images.githubusercontent.com/3686677/34972164-95e4026e-fa77-11e7-9c7b-6bafbeb01b06.png)

Will make a PR.

**Comment by TumeniNodes** [comment]
that looks better, and not really being able to tell, it doesn't _look_ as though blurring has left any artifacts... but, how does it scale for various resolutions?

**Comment by paramat** [comment]
There is still very slight distortion at certain window sizes.

**Comment by paramat** [comment]
In the PR #2020 i have done the same for the trash icon.

**Comment by paramat** [comment]
#2020 merged.
