### ISSUE TITLE
Issues with the flower spread ABM

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2022]
EDIT: Only issue left is should a plant only spread to a surface node identical to the one it is on? I think probably yes, to stop flora spreading into biomes it is not suitable for.
///////////////////

Flowers mod was added to MTG for mgv6 and the ABM was intended to spread flowers only so was lightweight. Long grasses were then added to the 'flora' group to make the ABM spread those, but still in mgv6 which has a very low density of grasses.

Now we have new mapgens with a new biome system and grasses can be much higher density, and very high densities may be used in some biomes, such as my plans for coastal grassy dune biomes.
The ABM has been shown by the profiler to be surprisingly intensive. For every flora node it is applied to it does 'find nodes in area' for a 9x9x9 node volume.

I suggest the ABM is now being applied to too much, grass, dry grass, junglegrass and ferns are present in high numbers and are not high priority for spreading. Some produce crop seeds but these seeds can then be obtained from the crop itself. I can't see much need for grasses to spread.

Another good reason: Flora group nodes do not spread if there are more than 3 of them in the 9x9x9 volume, since grasses count towards the total they are now very often boosting the total over 3 and preventing flowers from spreading when flowers are a valuable resource for dyes.

This wouldn't be a problem if we farmed flora using seeds as i have suggested, we could remove the ABM completely.
If some way of spreading grasses and ferns is needed we can come up with another method for those.

**Comment by Fixer-007** [comment]
I don't like this idea of removing grasses, ferns from flower spread, it is one of the things that make world alive.

**Comment by twoelk** [comment]
It has always been difficult to farm flowers or even grass. In games that have starting from an empty world as theme such as the justtest servers, the skytest games, the waterworld versions of unternull or ice and snow worlds players need a lot of space to generate enough flowers for dyes. There should be farming possabilities for any plant that offers a resource. Besides having a nice garden full of flowers should be possible without raiding the generated countryside of it's beauty. 

Indeed I think plains of high grass and lush blooming meadows are two sights somewhat missing in mtg. 

So I propose to give grass and alikes a spreading function of it's own, hopefully without adding more load ;-P  Also I would suggest to give the shovel more uses. Similar to some bush mods it could be used to move a plant as it currently is, growth stages included, while punching actually destroys the plant and generates the drops which should in my opinion also include flower seeds to be able to multiply them in farming or gardening.

**Comment by paramat** [comment]
This is a big issue:
> Another good reason: Flora group nodes do not spread if there are more than 3 of them in the 9x9x9 volume, since grasses count towards the total they are now very often boosting the total over 3 and preventing flowers from spreading when flowers are a valuable resource for dyes.

We could possibly use groups such that a flower node only counts other nearby flowers, grass only counts other grass. we have groups for grass and dry grass already and can add one for ferns.
I can do this as a start.

**Comment by paramat** [comment]
Did some profiling in mgv7.
In terms of maximum times, the flower spread ABM is the most intensive ABM by a factor of 2.6 over the next.
In terms of average times, the flower spread ABM is the most intensive ABM by a factor of 3.6 over the next.

Another issue is that this ABM was originally present in the flowers mod for flowers only, the spread is tuned to stop at a density of 4 plants per 9x9 area which was the density of mapgen flowers in mgv6. it was not meant to apply to other plants or other biome systems.
This maximum density is now applied to all flora nodes whatever they are and wherever they are regardless of local density variation by noise.
If you want to farm flowers you can't have a higher density than this.

Another issue is that the spread often halts if it reaches a steady-state distribution where there are >3 plants within 9x9 for all plants, sometimes this happens quite quickly.

@sofar any comments?

**Comment by MarkuBu** [comment]
It doesn't make sense to count grass as plant. Flowers can grow, regardless of the amount of grass. They can replace grass.

**Comment by paramat** [comment]
Profiled ABM time per server step (90ms) in grassland with dense grasses.
MTG master: Max 6.5ms Av 3.5ms.
MTG with grasses removed from flora group: Max 1.7ms Av 0.27ms.
13 times more lightweight.

**Comment by paramat** [comment]
Compromise proposal:
Remove grasses and ferns from the flora group.
Keep the flower spread ABM (no seeds for now) but apply it to flowers only, and optimise it in my PR #2016 

Grasses and ferns don't need to spread because they are not a resource. Kelp and dry shrub don't spread. Green grass and junglegrass are a resource for your first wheat and cotton seeds, after that seeds come from the crop, because of this those grasses are not likely to be harvested much, and are abundant in the world.
Dry grass and ferns are no resource so should certainly be removed from the flora group.

**Comment by Fixer-007** [comment]
>Grasses and ferns don't need to spread because they are not a resource.

Then add a way to generate them, aka bone meal >_>

**Comment by 4w** [comment]
> Meh, that's sad,

I am pretty sure that a mod can simply add grass back to the flora group.

**Comment by paramat** [comment]
It may not happen, these are only my own opinions. The optimisation PR helps.

**Comment by Ezhh** [comment]
I've been slow to reply on this one due to thinking it over, but even though I sort of like the idea of seeds, I don't really like the idea of flowers not spreading by themselves. I've always enjoyed that both flowers and grass spread and grow without my direct intervention, and the world would feel quite a bit more static and dull if this was taken away.

**Comment by Fixer-007** [comment]
Also, avg 3.5 ms actually seems very fine to me, other mods like biomelib can go into hundreds easily.

**Comment by paramat** [comment]
biomelib is a bad example, it's extremely intensive.
1ms is a long time in code, compare 3.5ms to a server step of 90ms. The maximum time profiled was 9ms, so occasionally 10% of server time was spent on one ABM from the base game.

**Comment by Wuzzy2** [comment]
If grass doesn't spread, it will become a non-renewable and finite resource which is quite a serious nerf.

Maybe just put grass and grass-like nodes into their own group and give them their own ABM, but with a lower frequency and chance to reduce server load.

**Comment by paramat** [comment]
Changed thread title as i expect removing grasses and ferns from the flora group will not be accepted.

**Comment by paramat** [comment]
#2016 merged.

**Comment by twoelk** [comment]
define identical node, you may have different types of dirt with grass for example. some might be added by a mod or some future feature.

**Comment by paramat** [comment]
Good point, but usually a different surface node is a different biome and decorations are usually intended to be limited to a certain biome. if a decration is in multipple biomes then it will already be on both surface types already, so no issue.

**Comment by paramat** [comment]
#2046 merged.
