### ISSUE TITLE
Simplify dungeon analysing in 'dungeon loot' mod

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2023]
Sorry to mention this after merge, but profiling shows the mod can add 6ms to mapgen time, for some mapgens this is a 10% increase, too much. I just noticed the profiling in the PR thread was LuaJIT, i should have checked Lua times.

How the mod works:
```
values are currently tuned so that most qualified dungeons have at least one chest
qualified = not consisting solely of small rooms
```
Most of the mod is fine but i feel that processing up to 16 rooms to find the rooms sizes to decide whether to place a chest in the dungeon is unnecessary and involves a lot of individual 'get nodes'.
Instead i suggest to process rooms until a suitable room is found (has 4 walls, this will usually be the first or second room processed) and place 1 chest only.
Seems ok to me to place in a small room and/or in a small dungeon.

From dungeongen.cpp:
```
		Find place for first room.
		There is a 1 in 4 chance of the first room being 'large',
		all other rooms are not 'large'.
```
The first room is often the largest so placing in the first room is often similar to the mod's intention.

Just wanted to ask the mod author if i can make these suggested simplifying changes to dungeon analysing?
I'll probably experiment and see if my ideas make a significant change.

**Comment by sfan5** [comment]
I'm not too keen on changing this behaviour, since I spent some time tuning it.
But I'm fine with the optimization you suggested **if** it actually brings a significant speedup.

If you have a PR for this, make sure to ping me for review.

**Comment by paramat** [comment]
@sfan5 as a minor and simple change, how about reducing the number of analysed rooms to 8? The maximum per dungeon is 16 so 8 will be the average number of rooms. Only the first room can be 'large' so the first room will likely be the one that qualifies the dungeon.
I noticed you suggested this in the PR thread https://github.com/minetest/minetest_game/pull/1921#issuecomment-338896342

**Comment by paramat** [comment]
Ok will make a PR.

**Comment by paramat** [comment]
#2024 merged.
