### ISSUE TITLE
Add fireflies mod

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2025]
![hw_the_marsh_lands](https://user-images.githubusercontent.com/3686677/35268467-20ed0794-0021-11e8-9a18-4fd7749a530d.png)

Or a variant of it.
https://github.com/Ezhh/fireflies

Fireflies were one of the 4 mobs in Minetest 0.3 http://wiki.minetest.com/wiki/Mobs#Firefly
"Fireflies are currently useless. You can currently only pick them up and release them"

* We want to add mobs to MTGame, i am considering adding a simple Oerkki mob, fireflies would be an ideal 'friendly mob' as the counterpart to the Oerkki, also being suitable for the history of MT.
* This adds a mob in a very lightweight way.
* Although mobs cannot light up the environment, these can because they are decorations.
* While the original fireflies were 'useless', this mod adds a use as a cute light source.
* This light source also adds a use for bottles from vessels mod. The bugnet adds a use for string.

The original fireflies were releasable, maybe we can allow release which will place the free firefly in the environment? Ideal for creating an atmosphere, and gentle illumination, somewhere.

I guess the fireflies should be optional, but by setting or by a future engine feature of being able to disable game mods?

**Comment by Ezhh** [comment]
The version I've released is 100% MTG compatible with no other depends at the moment, and I'd be happy to look at adding a way to release them from the bottles as well (shouldn't be difficult).

One thing we might consider is looking for an alternative net texture, since though I have direct agreement from tenplus1 to use his in this mod, it would mean using the texture from an item in a very well known mod for something in MTG, so it might be confusing for players on servers.

Happy to take feedback if anything else needs adjusting.

**Comment by Fixer-007** [comment]
It is not really a mob, but a nice decoration, since it does not move and can't be acted upon, I see a nice use for it, aka configurable light sources - bottles with fireflies (catching more flies with bottle increases its brightness).

**Comment by rubenwardy** [comment]
Looks very nice!

**Comment by Megaf** [comment]
https://github.com/Ezhh/fireflies should be make default in MTG.
And rats could get back to MTG too since we are at it.

**Comment by Ezhh** [comment]
I think as long as something is a separate mod, an option isn't needed.

Since this seems to have some support, I'm happy to work on tidying it up a bit more and will make a PR (probably on the weekend).

**Comment by TekhnaeRaav** [comment]
This looks amazing, love it! Totally original. :+1: 
If this takes any processing it should be readily optional though.

**Comment by Ezhh** [comment]
@TekhnaeRaav It's designed to be very light. Placement is on mapgen as a decoration. The fireflies themselves are simply an animated plantlike node.

**Comment by JurajVajda** [comment]
good idea, simple, nice and compliments MT ..just do it!

**Comment by jastevenson303** [comment]
@Ezhh's version relies on having waving nodes turned on, however.

**Comment by paramat** [comment]
It doesn't rely on waving but cleverly uses it for extra movement if it's enabled.

I suggest possibly using a 32 frame animation for more vertical movement and movement complexity.

**Comment by Ezhh** [comment]
@paramat Yes, I can look at adding frames. Would you also be willing to look at the register_decoration part to check if "place_on " or "biomes" should be adjusted? You know the MTG biomes far better than I do. :)

**Comment by paramat** [comment]
Yes.

**Comment by TumeniNodes** [comment]
yay, "glow jam"

I love this idea. Would add some life to the current game.
Maybe it could be tied into boosting moral in the future? (who doesn't feel happy seeing fireflies?)

**Comment by Ezhh** [comment]
I'm predicting a "glow_jam" mod with fireflies sitting in depends.txt somewhere in the future? :)

**Comment by C1ffisme** [comment]
I like it. The warm glow of the fireflies at night gives off a different atmosphere compared to Minecraft's dark, scary mob infested night.

**Comment by paramat** [comment]
#2034 merged.
