### ISSUE TITLE
Tree size variation

### ISSUE THREAD

**Issue by TekhnaeRaav** [minetest/minetest_game#2026]
Many of the forests in minetest can start to get a little repetitive sometimes. The forests (of all types) would be much more exciting with a larger tree size variety, height, width and so on.

**Comment by Ezhh** [comment]
Hmm, also see #1750, which is this, but for a specific tree type.

**Comment by paramat** [comment]
All trees do have varying height. For a single schematic width cannot be varied.
It would be good to add extra schematics for more variation:

Apple trees could have a second size that has a width of 7 nodes and slightly taller.
Small pines of width 3 could be added.
I am working on a larger (emergent) jungletree with a 3x3 trunk, ideal for treehouses.
Remember any new species adds a new wood and therefore many new items, so different shapes of existing species is a good idea.

Since i designed our trees i'll assign this to myself for design consistency.

**Comment by Fixer-007** [comment]
I think I've posted another issue about that, basicly minetest game needs more trees schematics, used randomly at mapgen time.

**Comment by paramat** [comment]
Yes there's a request for random chosen schematic decorations #4485
I'll need help with that, i would have coded that by now if i could.

**Comment by TumeniNodes** [comment]
consider also making the lowest default_tree (or apple tree, whatever) at least one node higher.
They cause issues where the is snowfall, as well as just a pain when traveling uphill.

I agree with fixer but, even just 3 schematic variants per tree would suffice. They could be labeled "young", "mature", and "old"?
The young trees could be what currently exists, the mature a taller variety, and the old is when the width kicks in
(just some suggestions)

**Comment by 4w** [comment]
Since we have [L-system trees](http://dev.minetest.net/Introduction_to_L-system_trees) do we even need schematics?

**Comment by MarkuBu** [comment]
L trees are still buggy and slower than schematics

**Comment by paramat** [comment]
L system trees are not yet designed to be added during mapgen, as each one has a separate light update. Even if that is fixed, as is intended, they are intensive and slow due to the generation method.
Schematics are essentially a small volume of world database, just mapnodes with nodename, params 1 and 2, so load in almost as fast as world does.

**Comment by TumeniNodes** [comment]
I was thinking about all of this last night, and a thought popped into my head.

What is the possibility of looking at sapiers old "growing_trees" mod (I think addi has modified it some)

But, just looking at the code, and seeing if the normal "tree" nodes could be used rather than the current nodeboxes it uses (though I have to say I do prefer the nice branches etc) but, even those could be reworked to use cubic style, opposed to the current round.

That mod produces a variety of tree sizes
(Just a thought to pass by here) it could be a profitable venture (not in terms of monetary)

link: https://forum.minetest.net/viewtopic.php?f=13&t=978&hilit=growing_trees

**Comment by paramat** [comment]
It uses a sequence of node additions to create a tree, the initial tree is placed as a small 2-node structure and the ABMs then grow it step by step. So to create complete trees on mapgen each tree would need to progress through many growth steps, this makes it similar to L system and no less intensive, too slow for mapgen.

**Comment by TumeniNodes** [comment]
This is why I mentioned modifying the growth system to more match what is used now, and other tweaks. Not focusing purely on how the mod itself is written, but looking beyond that to figure a way to make it integrate with the current trees.lua

I was looking more about the full tree results

I have to look at it more thoroughly

**Comment by Ezhh** [comment]
For small variations, can't we randomise the height the schematic is placed at relative to ground level? I know this wouldn't give us big variations, but it could help.

**Comment by paramat** [comment]
Tumeninodes, yes that's what i mean, on mapgen each tree would be rapidly progressed through many growth stages to become instantly full-grown. This is exactly what L-system does, so would be much slower and much more intensive than current schematics. A variety of schematics is a much better idea.

**Comment by paramat** [comment]
> For small variations, can't we randomise the height the schematic is placed at relative to ground level?

Random 'y offset'? That would be identical to the already present trunk height variation. Currently each schematic has horizontal slices randomly removed to alter structure and height.

**Comment by Ezhh** [comment]
Doesn't seem to do much though; surely more variation could be produced? I am thinking of the way you added roots to emergent jungle trees - part of the schematic can be concealed underground where needed to provide greater possible variation.

**Comment by paramat** [comment]
Yes i can add more height variation to schematics, but they already have quite a lot, people don't seem to notice it much. I could add a little more variation to some trees.
Appletrees have as much as they can, if the trunk gets any longer they will look out of proportion.
Acacia only has 1 node of height variation, i'll make it more.
You can see the 'y slice probabilities' here https://github.com/minetest-mods/saveschems/blob/master/init.lua
Adding to my TODO list.

**Comment by paramat** [comment]
I looked through all trees again, many have a fair amount of variation already:

Aspen variation 5. Has a maximum height dictated by needing to be shorter than both jungle tree and pine. Any more variation will make it too low to walk under.

Acacia tree variation 1. PR #2049 increases this to 3.

Apple tree variation 2. Any higher will be unsuitable for it's form. Any more variation will make it too low to walk under.

Jungle variation 4. These are intentionally high without extreme variation to create the canopy. I could add another node of variation.

Pine variation 5. I can make the maximum height 1 node higher and also add another node of height variation.

**Comment by paramat** [comment]
All that done in #2049

**Comment by Fixer-007** [comment]
>I looked through all trees again, many have a fair amount of variation already

It is not just height, but also shape of those trees and wood blocks in them, here is the worst part - apple tree:
![default](https://user-images.githubusercontent.com/16494741/36258785-ad0f4250-1264-11e8-9563-a8c752cb3c1c.png)

**Comment by paramat** [comment]
'grow new apple tree' etc. are sapling growing functions, nothing to do with mapgen.

In the decoration registration if you had a random path that random path would be randomised once only on registration, so only 1 schematic would be used.
Random schematics are high priority will try to code that.

**Comment by paramat** [comment]
![screenshot_20180303_234150](https://user-images.githubusercontent.com/3686677/36940549-ef09049a-1f3c-11e8-91c1-7a0b6b67ceb7.png)

Experimenting with small pines.

**Comment by paramat** [comment]
![screenshot_20180304_162445](https://user-images.githubusercontent.com/3686677/36947878-df272344-1fc9-11e8-8b63-5bb6bb61ecb4.png)

Smallest and largest.

![screenshot_20180304_163315](https://user-images.githubusercontent.com/3686677/36947884-ed9e2256-1fc9-11e8-971a-d542df180651.png)

These are lovely, can't wait to add them.

**Comment by paramat** [comment]
#2068 merged.

**Comment by paramat** [comment]
Emergent jungle trees have been added too.
Any more variety will have to come from adding more species, or using multiple schematics for a species. An engine feature for randomly selected schematics within a decoration registration would help.
This request is partially attended to now.

**Comment by paramat** [comment]
I disagree this should be considered high priority enough to be in the roadmap.
It's also mostly done, all forests now have a variety of trees, each tree already has height and structure variation.
This issue could possibly be closed, even though we could create more variation later.

**Comment by Fixer-007** [comment]
>all forests now have a variety of trees

I think apple forests look very homogeneous and repetitive, they need more variation, aka number 1 problem with forests imo.

**Comment by paramat** [comment]
The deciduous forest biome contains apple and aspen trees. All apple trees have per-node and height variation.
As there has been so much improvement of tree variety i no longer think it is justified to keep this issue open. However, i still support further variation in future.

**Comment by TumeniNodes** [comment]
Just a thought (and possibly will not be a popular one)

Apple trees are not common/natural in deciduous forests...

Can apple trees be moved over into farming... and only grow when planted?
And replace them in the deciduous forest with another tree such as maple, or hickory, or even ash or something?
I would say oak but... you know... "mc"
Maple may be a good choice, as we can then add (or via a 3rd party mod) a means to extract the sap for food recipes...

Though Hickory trees could be a really nice option too
https://homeguides.sfgate.com/uses-hickory-tree-99445.html
