### ISSUE TITLE
Ice Caves

### ISSUE THREAD

**Issue by GreenXenith** [minetest/minetest_game#2029]
Moved from engine discussion https://github.com/minetest/minetest/issues/6645. 
> I know this has been sort of suggested in https://github.com/minetest/minetest_game/issues/1142, but that was a while ago(ish).
_If_ the engine supports this yet, I think it would be a nice addition. Open-air ice caves only would probably be best, though. With things like ground-to-ceiling ice pillars, perhaps stalactites and stalagmites.
>
>paramat said
>> Caves in ice do not appear because ice has been made 'not ground content' to avoid ugly holes in ocean iceshelf. It would be good to have caves in 'on land' ice but we would need 2 types of ice, one that is ground content.
>
>I suspect (I could be wrong, I know little about mapgen) that you can check for altitudes before carving caves, so perhaps make it so ice caves are created at higher elevations in things like large glaciers, thus avoiding "ugly holes in ocean iceshelf".

Paramat said:
>The best way seems to be having 2 different ice nodes with different 'is ground content' values.
One is fresh ice above sea level, the other sea ice, they don't necessarily need to look different and one could drop the other.

Personally, I find the current ice texture to be a bit ugly, so either a texture redo or a new texture for fresh ice could be nice. If not, that's fine, just my opinion.

**Comment by raymoo** [comment]
An LBM or mapgen callback could also be used to convert the non-cave ice.

**Comment by paramat** [comment]
I don't plan conversion, too messy and intensive. This will be for newly generated terrain only.

**Comment by raymoo** [comment]
Fair enough

**Comment by paramat** [comment]
I think i would do this by adding a second ice node 'default:land_ice' that has an identical texture and description "Ice", that drops 'default:ice'. Then use 'default:ice' for 'node water top' and 'default:land_ice' elsewhere.

**Comment by paramat** [comment]
^ Opinions?

**Comment by sofar** [comment]
Geologically speaking, ice caves would occur only near the surface or above it, due to the thermal gradient that makes the earth hotter as you descend. Having ice caves in mountains seems highly appropriate. But, Having them placed based on low temperature / high humidity biome points seems appropriate.

**Comment by paramat** [comment]
In 'icesheet' biome the on-land ice only extends down to y = -8, so that should be ok.

**Comment by GreenXenith** [comment]
Whatever works, really. Higher makes more sense to me, but anywhere cold would work..

**Comment by paramat** [comment]
PR #2062

**Comment by paramat** [comment]
#2062 merged, turned out an excellent idea thank you.
