### ISSUE TITLE
Doors can_dig crashes on nil player

### ISSUE THREAD

**Issue by ShadowNinja** [minetest/minetest_game#2032]
The player argument to `can_dig` is optional (as specified by `lua_api.txt`, and is not used by some mods (notably the Technic quarry), however the doors mod's `can_dig` assumes that it is non-nil when calling `record_protection_violation`.

`record_protection_violation` should not be called at all in this function as this function does not actually check protection -- it only checks ownership, which is something entirely different.

A fix would be to simply remove the call to record_protection_violation`.

**Comment by paramat** [comment]
Will fix and merge as trivial.

**Comment by VanessaE** [comment]
Can this fix be backported to whatever branch of mtg is appropriate for 0.4.17?

**Comment by paramat** [comment]
Yes.

**Comment by VanessaE** [comment]
thanks.

**Comment by paramat** [comment]
PR #2039

**Comment by paramat** [comment]
#2039 merged, added to backport TODO.
