### ISSUE TITLE
We have a food problem

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#2037]
Do not deny it:
1) Consuming is instantaneous
2) Full health bar does not stop further food consuming
3) Autoeat hack (demonstrated at least since 0.4.12)
4) There is no animation
5) It is handled in engine

**Comment by paramat** [comment]
1. Is because MT is not super realistic, you're thinking about MC. Probably an engine issue.
2. Valid, needs fixing, there may be an issue somewhere. Probably an engine issue.
3. ?
4. Engine issue.
5. Engine issue, discuss there.

**Comment by Fixer-007** [comment]
Subgame has no say in how food is handled? Is it client-side or server-side?

**Comment by C1ffisme** [comment]
The function for eating is `minetest.item_eat()`, so I would assume that issues with that specific function are engine issues.

**Comment by Fixer-007** [comment]
There is no Food API? :D
