### ISSUE TITLE
Improve corals

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2040]
This is something that needs doing but i'm too busy to.

We now have the 'plantlike rooted' drawtype so plantlike corals can now be used if rooted on a cubic coral reef node.
~~More colours of the cubic 'brain corals' could be added.~~ EDIT i think we have enough of those now, best add plantlike rooted corals.
If schematics are used, to create the schematic file edit https://github.com/minetest-mods/saveschems/blob/master/init.lua#L967 and run that mod in any world, the .mts file will appear in the folder.
For textures i prefer those from the 'seacoral' mod in the 'sea' modpack by Topywo, i'm not suggesting all 6 have to be used, less is probably better.
https://forum.minetest.net/viewtopic.php?f=11&t=4627&hilit=sea+modpack

![screenshot_20171106_173019](https://user-images.githubusercontent.com/3686677/35824582-342d84fc-0aab-11e8-8f85-b6a56448477e.png)

![seacoral_coralaqua](https://user-images.githubusercontent.com/3686677/35824588-3eb0388e-0aab-11e8-83e9-bf367c6cd2a4.png)

![seacoral_coralcyan](https://user-images.githubusercontent.com/3686677/35824595-41d5556c-0aab-11e8-9cd5-1dfe6549c8cb.png)

![seacoral_corallime](https://user-images.githubusercontent.com/3686677/35824602-44ae5ea0-0aab-11e8-8de1-bb0f713fcb44.png)

![seacoral_coralmagenta](https://user-images.githubusercontent.com/3686677/35824608-475e7554-0aab-11e8-9413-0faec26ebcdf.png)

![seacoral_coralredviolet](https://user-images.githubusercontent.com/3686677/35824619-4d3af9e8-0aab-11e8-83bd-5a826e851718.png)

![seacoral_coralskyblue](https://user-images.githubusercontent.com/3686677/35824626-510b14f4-0aab-11e8-81ea-d01428ecbaef.png)

**Comment by Ezhh** [comment]
Corals really do need improvement, but we need to think carefully about what we want for them.

The current coral nodes are already in existing worlds, so we shouldn't replace them with plantlike nodes without knowing what that might do to what people have created, on the other hand, though it could be nice to have more than one type of coral, coral still has no actual use. We would also need to make sure the two types looked good together. 

This is something I'd be happy to work on, but we need to have a definite direction for it first.

**Comment by paramat** [comment]
Yes i suggest not altering the current brain coral nodes but adding new ones to those.
Corals drop coral skeleton so the coloured brain corals are only present where they were generated.

**Comment by Ezhh** [comment]
Experiment using some of these textures:
![hw_coral_test](https://user-images.githubusercontent.com/7035183/36062499-8e8204ce-0e65-11e8-80c7-cddb95b0e744.png)
This is simple enough if we can decide exactly what we want.

**Comment by paramat** [comment]
I like the idea of each 'plantlike rooted' coral being on top of a 'coral skeleton' node, as is realistic. Then the combination could either be included in the existing schematic or placed individually as here. We still need to place the prevous orange and brown cubic corals.

One possibility is to keep the schematic reefs but make them mostly skeleton plus plantlike coral, with a few of the cubic corals too. However individual placement as you have done may work out better.

**Comment by paramat** [comment]
I think it's worth trying individual placement (no schematics), each node would be a plantlike coral on top of coral skeleton, or a cubic coral (itself perhaps on top of coral skeleton?). Since these are simple decorations a list can be used for random selection on placement.
Noise params can be tuned to create dense clusters of corals in a more organic way than using schematics.

I think all corals should continue to drop only coral skeleton when dug.

I like how you have chosen the best of each colour of coral, for 3 plantike corals, which seems the optimum number.

**Comment by paramat** [comment]
If you mean you're not sure about cubic corals being on top of skeleton, i agree, possibly ugly. I'm also not sure about how to use the cubic corals. Maybe work on the plantlike ones first.

**Comment by Ezhh** [comment]
Better distribution using noise:
![hw_coral_test2](https://user-images.githubusercontent.com/7035183/36080133-78c35c2c-0f83-11e8-83aa-5f91746afe6b.png)

**Comment by ExeterDad** [comment]
@Ezhh That's pretty. It turned a baron planet surface into a sea bottom.

**Comment by DartPower** [comment]
Please, more detail
Like the https://github.com/minetest/minetest_game/issues/2040#issuecomment-364653292

**Comment by paramat** [comment]
The screenshots are from Ezhh's game. I don't like corals being placed directly on stone. Coral reefs are structures formed from calcium carbonate (coral skeleton) that build up from seabed level. For MTG i think each plantlike coral should have 'coral skeleton' as the base node, and the base node is placed on the seabed instead of in it to form the reef structure. The contrast against white will look good.

**Comment by Ezhh** [comment]
It doesn't matter what this is taken from, since for now it's just experimental and the textures used are very easy to switch. I'll do a proper MTG version at some point to see what it looks like with the different types of coral mixing, but wanted to get general thoughts on these corals first.

**Comment by paramat** [comment]
Labelled as essential for 5.0.0. :)

**Comment by Ezhh** [comment]
I'm not sure it is, but I'll take the hint. :)

**Comment by Ezhh** [comment]
So adding them to sand alongside the current coral cubes gives this:
![corally](https://user-images.githubusercontent.com/7035183/43367395-1d7a9746-9344-11e8-9c2f-1e440bc913d3.png)

Personally I feel they highlight just how drab and ugly the existing coral is. It's mostly the colours that let them down.

Question 1 - can we change the colours of the original coral? (Keep in mind, they are named by the colours, so we face either weird naming or aliases if we change them).

And here we have skeleton coral added under the new corals:
![corally2](https://user-images.githubusercontent.com/7035183/43367508-f7943792-9345-11e8-8366-6c4ead6fffbc.png)

Question 2 - Do we prefer them on sand or dead coral (or another alternative)?

Question 3 - Most plants are snappy, but cube corals are cracky. Which group should the new corals be?

Question 4 - Brown and orange corals drop coral skeleton when dug. Should the new ones also drop skeleton (even though we're then getting a solid node from a plantlike one)?

There'll probably be more questions, but these are the first points to settle.

**Comment by paanrama** [comment]
From Wikipedia, I vote that corals drop calcium carbonate but not a complete block. Calcium carbonate is the principal compound of minerals calcite and aragonite that form limestone. It has a lot of uses including soil additive and building material.

**Comment by paramat** [comment]
I don't like the existing coral schematics, so would prefer we remove those and just use the nodes in the new implementation.

I did some research into corals, they appear on a structure of coral skeleton, not sand, so we can use the existing nodes as the foundation for the plantlike nodes, in which case the unexciting colours become a benefit as they won't colour-clash too much with the plantlike nodes. So i see no need to change their colours (i hate adding aliases anyway).

The foundation could be mostly 'skeleton' with occasional orange and brown cubic corals mixed in, either as foundation or on top of foundation.

The plantlike corals could directly drop a 'calcium carbonate' resource item (which will certainly have uses later). The coral skeleton node could then craft to multiple 'calcium carbonate' items.

About distribution: Corals tend to cluster together (it seems) but i prefer placing individually instead of using schematics as before, so i can come up with noise params that cause dense clusters.

Since we will be using 'plantlike rooted' the base cube can be 'coral skeleton'. That's 3 decorations, then i would add 2 more which are the orange or brown cubic corals. All 5 could be registered as a single decoration that randomly chooses from a list of 5, so will be lightweight for mapgen.

**Comment by Ezhh** [comment]
> Q: When a plantlike rooted coral is dug does it drop the calcium carbonate item (if used) and the coral skeleton below? Or just the item and places skeleton below? (the kelp behaviour).

I'd prefer it just drops the item. You can then choose to collect the coral skeleton separately.

**Comment by paramat** [comment]
That's fine for me and consistent with kelp.

**Comment by paramat** [comment]
Removed 'blocker' label for new coral decorations. However i would like to, at least, stop placing the current decorations before 5.0.0 (while keeping the node defs of course). Ezhh is it ok if i make a PR to do that now?

**Comment by Ezhh** [comment]
How about I stop being lazy and just do this?

I'll work on it tonight or tomorrow at the latest.

**Comment by paramat** [comment]
LOL ok.
