### ISSUE TITLE
Variety of stone types underground and some ores limited to certain stone types

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2048]
I'm very keen on a variety of stone types underground, and having some ores limited to certan stone types is a solution to the 'all ores in every stone type problem' as well as adding the gamepley of searching for certain biomes (either surface or underground biomes) for certain ores.
The change of stone colour underground will be stunning.

My initilal thought is to have stone volumes as horizontal strata located by Ymin /Ymax, instead of vertical columns located by X and Z (aligned to surface biomes), because underground the primary / most natural / most interesting direction of travel is vertical, so then players would travel through different stone types.
Also underground surface heat and humidity have little relevance, while (realistically) depth is the primary factor on underground structure.
EDIT: I will think on adding some kind of undulation option to biomes to avoid horizontal borders.

Current stone types:
stone (grey)
desert stone (red)
sandstone (yellow)
desert sandstone (orange) missing from world
silver sandstone (light grey) missing from world

The 2 new sandstones are missing from the world and need adding somewhere, i am considering adding them to closely related biomes in #1998 

Because we intend to add stalactites/stalagmites, these are made from calcium carbonate dissolved from limestone, and we don't have a white stone type, so i suggest adding limestone for white.

The remaining colours missing we could consider are green, blue, violet.
Also maybe black and/or dark grey.
Not saying we have to add more, but i think limestone is needed.

Extra colours of stone give players coloured blocks to build with.

Closely related to #1168

**Comment by paramat** [comment]
The basic ores coal and iron perhaps need to remain easily findable by newbie players, so perhaps the surface biomes (that extend down to y = -112) can remain mostly grey stone and coal and iron stay in grey stone.
All other ores could be in other stone types.

One consideration for which ore in which stone type is colour contrast.
Also we could get hints from reality, looking at maps of ore distribution related to biome, if there is any correlation.

Mese block can be in multiple stone types if desired since it has no stone in it's texture.

**Comment by tenplus1** [comment]
Could we finally add the missing ores from moreores (silver, mithril) and respective tools to add even more colour :)

**Comment by paramat** [comment]
We have too many ores and tool materials already, i somewhat regret adding tin but it was done to make bronze make sense, but bronze was a mistake. Silver would need a very good reason. Mithril no, too unoriginal and is a magickal type ore, we already have mese and special ores like this should probably be in separate mods.

What we consider to add is independent from what is left in a particular mod. Even if a mod is popular it's just one mod out of many. 2 ores being left in a mod is not a reason to add them.

**Comment by Ezhh** [comment]
We already have more ores than valid uses for them. I'm not against adding more ore (just not mithril please), but it would need actual uses first. (Another tier of identical tools that can just be skipped anyway doesn't count as a use.)

Variety of stone types underground is something I have been wanting for a really long time. We do need to be mindful that any given ore type does not become too difficult to get, but a good approach might be to try and make sure each biome has at least one ore from each tool level (though if iron stays common higher up, this isn't important, because once you have iron you can mine anything anyway).

Once there are different stone types underground, underground decoration also gains more interesting possibilities and different, distinct, content can be created for each.

**Comment by Fixer-007** [comment]
>My initilal thought is to have stone volumes **as horizontal strata located by Ymin /Ymax**, instead of vertical columns located by X and Z (aligned to surface biomes)

Eh, instead invent underground biomes with different stones and exclusive ores in them via noise, it should also very greatly in shape and form, no strict limits, it may occurs twice or etc, Ymin/Ymax is lame tbh.

**Comment by Fixer-007** [comment]
Even more crazier:
![default](https://user-images.githubusercontent.com/16494741/36281264-bb7cc204-12a5-11e8-9e1e-6763f4941b0c.png)

**Comment by paramat** [comment]
We could have underground biomes that are located by heat/humidity noise in XZ and by Y limits in Y. The heat/humidity points can be different to the surface nodes so that the XZ distribution doesn't match.

Vein ore is extremely intensive, it needs 2 3D noises, maybe for another game but not for MTG.
Locating ore by stone biome is free and requires no extra noises, it's also realistic and intuitive.

Your image is impossible, biomes can only have horizontal upper and lower limits, noise only applies in XZ.
The fact is, when you understand how things work, things usually have to be simpler than ideals.

**Comment by Fixer-007** [comment]
Could it be in diagonal non-continuous shape?

**Comment by sofar** [comment]
There's no limit as to what stone surfaces look like, but it may need an engine change. I would not like to see flat underground stone layers - they may make sense for thin layers of sandstone/limestone and look great in canyons above y=0, but underground layers should have undulating surfaces and be mapped with 2d or even 3d surfaces.

Mapping stone to biomes is geologically about as incorrect as flying raptors with lasers. Biomes are climate defined vegetation and soil types, and sediments are millions of times older than the variation scale of biomes and climate, so they should be decoupled ideally, and this will result in a much more interesting and varying landscape.

This goes back to my ideal mapgen - Ideally, we have full range of geomorphology where climate (biomes) interact with the structural geology, and things like topography and soil are derived from the combination, and not solely from biome data alone.

**Comment by paramat** [comment]
I would like to avoid horizontal borders between stone types if possible, so am thinking about adding some kind of optional undulation to biome y limits, something lightweight that MTG can use, and hopefully something that is useful for surface biomes too.
When working on vertical biome blend i considered a 2D noise to vary the y limit surfaces, this idea may now be useful for underground biomes.

**Comment by paramat** [comment]
Ok i actually think using 'stratum ore' might be best for underground stone, it is coded perfectly for the job and can use 1 2D noise per stratum, each stratum can have a different noise so the structures would be more varied.

Since the stone strata will be thick (> 1 mapchunk) and because the 2D noise is only calculated within the limits of the stratum, only 1-3 2D noises will be used at any one time, which is not very intensive.

This will also avoid having to use a large number of new biomes for underground stone types, which leaves more biomes free for surface uses.
This allows underground biomes to still be used but to be independent of stone strata.

I did consider adding some kind of 2D noise variation to biome Y-limits but it's difficult and messy, i'd rather leave biomes as they are and use the new oregen we have already.

**Comment by DokimiCU** [comment]
I actually came here to suggest limestone...

So I second Paramat's idea of limestone... 

But for different reasons. Crafting. Limestone gets used in an enormous range of chemical, industrial, and building processes. If you add limestone modders will run with it for all sorts of crafting recipes. (To preempt 30 modders adding 30 versions of the same thing 30 different ways it might be necessary to add some default lime/quicklime crafts too? e.g. cement?)

My mg_tectonic map might be relevant here, as an example of what you're discussing could look like. I pretty much took every rock and sediment we had and threw them into strata. I used layering and a y-axis sine wave to split them into strata.

Some ideas for more colored rocks:
green: greenstone!, i.e. jade. A very hard rock, the stone of choice for stone tools.
black-grey: basalt. Earth's most common volcanic rock.
for blue and violet you might getting into rare and unusual territory.... blue rocks do exist though.

**Comment by paanrama** [comment]
I was reading rocks info on internet the last weeks, and there are rocks of black, white, grey, blue, orange, yellow, green, purple, red, etc. colours, some more common that others. Also I note that the same rock can have different colours and names.

I think that MTG don't have to limit itself to the most common rocks in earth surface (also we only know the composition of around 10% of earth crust), but is important that if a real rock name is used, then its characteristics in MTG must be similar of the rock in real world. 

To have some info to start from, I made a ODS file with rocks data from comparenature.com (only some images are from other sites). I chose that page as source because it besides the color, it also contains the  hardness of rocks, and, I think that is important that you consider the different hardness of rocks.

I hope this information can be useful for your discussion.

[RockTypesList.zip](https://github.com/minetest/minetest_game/files/2281437/RockTypesList.zip)

**Comment by paramat** [comment]
I suggest a first step of adding to the new underground biomes the current stone types that are in low supply.
Here are all current stone types:

default:stone (dark grey)
default:desert_stone (red)
default:sandstone (yellow)
default:desert_sandstone (orange)
default:silver_sandstone (light grey)

The last 2 are currently only available in narrow desert strata.

default:desert_sandstone (orange)
I think the most suitable biome for this would be 'desert', as this only appears in 'desert' biome strata and has an orange colour similar to desert sand.
I suggest 'desert ocean' biome continues to use 'desert stone', use 'desert sandstone' for the 'desert under' biome.

default:silver_sandstone (light grey)
Perhaps the most suitable biome would be 'cold desert', since this stone appears in the strata.
I suggest 'cold desert ocean' biome continues to use 'stone', use 'silver sandstone' for the 'cold desert under' biome.

**Comment by paramat** [comment]
Closing due to #2710
