### ISSUE TITLE
Add fossils

### ISSUE THREAD

**Issue by random-geek** [minetest/minetest_game#2050]
Fossils would be an ore found in stone near the surface, and would be somewhat rare. Unfortunately, fossils don't really have a "use", so I don't know if this feature is even a possibility. Maybe they could function as a rare item, especially if they had a small chance of actually dropping a fossil (rather than stone). Attached is a possible texture.

![default_stone_with_fossils](https://user-images.githubusercontent.com/35757396/36521088-b9765ac6-1749-11e8-9bc8-237f7814c95e.png)

**Comment by Ezhh** [comment]
The main issue is, as you've identified, giving them a real use.

**Comment by Megaf** [comment]
A good use of fossils, two good uses actually,
Would be,
1- Making oil by boiling them and them adding to a glass jar. Each unit of
boiled/cooked/smelted fossil could give 4 until of fossil fuel.
2- If fossils are bone, then they could be turned into bonemeal.

**Comment by Ezhh** [comment]
Fossils were also mentioned in #1989 as a fertiliser candidate.

**Comment by sofar** [comment]
@megaf neither those 2 uses are geologically correct.

Per definition, fossils are no longer organic components and are replaced by minerals, and therefore not usable as organic carbon based fuels.

For exactly the same reason, they're no longer usable as bone meal either.

I don't oppose having fossils, but they should be used for something realistic, like, really rare and hard to obtain trophy ornaments. Or proving that dinosaurs existed and the earth is round.

**Comment by random-geek** [comment]
`I don't oppose having fossils, but they should be used for something realistic, like, really rare and hard to obtain trophy ornaments. Or proving that dinosaurs existed and the earth is round.`

Not sure if that's sarcasm or not... Anyways, I might work on a PR for this in my spare time. I won't be offended if it isn't added.

**Comment by sofar** [comment]
:)

This is one of those "make it a mod first" things. It's probably a fun thing, but without code (that's working!) it won't get the support it deserves.

I strongly encourage that people who want to show off "a cool thing"  (not meant demeaning here) make a mod out of their concept first. That will make merging easier and the PR will be so much easier to review.

**Comment by random-geek** [comment]
> This is one of those "make it a mod first" things. It's probably a fun thing, but without code (that's working!) it won't get the support it deserves.

Ok, thanks for the feedback, maybe I won't submit a PR after all. I wasn't sure if it was a good idea in the first place :)

**Comment by TumeniNodes** [comment]
@sofar > Per definition, fossils are no longer organic components and are replaced by minerals, and therefore not usable as organic carbon based fuels.

For exactly the same reason, they're no longer usable as bone meal either.

I don't oppose having fossils, but they should be used for something realistic, like, really rare and hard to obtain trophy ornaments. Or proving that dinosaurs existed and the earth is round.

Hmmm, maybe the fossils could be collected and used to assemble a fossil display of a / an dino for a museum... this would add a decent use for them as well.
Good for educational purposes too.

**Comment by paramat** [comment]
Idea is fine, but i feel it's more a feature for an optional mod, as MTG is meant to be fairly basic and simple.

**Comment by TekhnaeRaav** [comment]
LOL! I just started on a fossils mod a few days ago then I found this. I've got some schematics for big skeletons and am working on ores and tools to. I should have the repo up there with some stuff tommorow.
Hope you like it ;)

**Comment by XenonCoder** [comment]
TekhnaeRaav OMG! Very beautiful and interesting your mod. I immediately followed the project and I ran the fork because for some time I wanted to make a mod like yours. Really interesting. Good job XD

**Comment by TekhnaeRaav** [comment]
Thank You! If you have any opinions or anything feel free ask.

**Comment by rubenwardy** [comment]
I don't like this, as we don't have any mobs currently. It doesn't make sense to have fossils without animals, unless there's some reason that all animals suddenly disappeared

**Comment by paramat** [comment]
So :-1: from me but only for inclusion in MTG.

**Comment by Ezhh** [comment]
Same thoughts here. I'm all for this being a mod, but it doesn't currently fit well in MTG.
