### ISSUE TITLE
Temporary workaround for gennotify issue

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2055]
See https://github.com/minetest/minetest/issues/6590
I don't have much hope this will be fixed soon.

I suggest doing `default.gennotify = minetest.get_mapgen_object("gennotify")` in an 'on generated' function in default mod. This will then be global for mods to use, such as 'dungeon loot', 'fireflies' and optional mods. This workaround has been tested and works.

**Comment by Ezhh** [comment]
As soon as we have a solution for this, I can make fireflies hide themselves during day time via node timer.

**Comment by paramat** [comment]
I'll have a look at the engine issue in case it's easy to fix.

**Comment by paramat** [comment]
Hopefully not needed due to https://github.com/minetest/minetest/pull/7091
