### ISSUE TITLE
Excessive fireflies in mgv6 due to lack of dedicated registration

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2059]
The decoration registrations are registered for all mapgens, but because the stated biomes are not found in mgv6 it seems to place 4 times too many fireflies, and not always in forests.
Fireflies mod needs to detect mapgen and have 2 different registrations, one for mgv6 with no biomes stated (although that will not restrict fireflies to forests).
@Ezhh

**Comment by Ezhh** [comment]
Heh, already working on it :P

**Comment by paramat** [comment]
#2060 merged.
