### ISSUE TITLE
Decorations need naming in order to use minetest.get_decoration_id()

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2065]
In 'register decoration' the first field should be a name, for example:
`name = "apple_tree",`
Should the names have the `default:` prefix?
If so, should the biome names have this prefix too? I seem to remember someone telling me they should.

**Comment by Ezhh** [comment]
Do the registrations need names even when the name won't be used? I would imagine only a very few registrations will ever use this.

**Comment by paramat** [comment]
Only decorations that are searched for in gennotify need names, but optional mods may search for default decorations so thought all might need naming, seems best.

**Comment by rubenwardy** [comment]
> Should the names have the default: prefix?

yes

> If so, should the biome names have this prefix too? I seem to remember someone telling me they should.

yes, but probably too late now

**Comment by paramat** [comment]
Yes just realised why it's too late.

**Comment by Ezhh** [comment]
Done 

#2087
