### ISSUE TITLE
Develop the biomes for mgv7 floatlands

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2066]
In default/mapgen.lua there are 3 placeholder biomes for floatlands as examples of how to add biomes to floatlands. These could be replaced by dedicated floatland biomes that are special in some way, or, the biomes could be a subset of surface biomes.

**Comment by Ferk** [comment]
It would be cool if it used special biomes with specific nodes, so that finding floatlands would be more rewarding and "magical".

Maybe something crazy like a candyland with lolipop/candybar trees, chocolate blocks for dirt and cream for grass, like in Zool.

**Comment by paramat** [comment]
Something unrealistic is fine, just not candyland =)
I don't have the ideas, time or energy for coming up with new content for this, however if necessary i can add more of the surface biomes up there, and may do for the short term.

**Comment by tenplus1** [comment]
You could use any of the biomes and decorations from Ethereal NG mod :)
