### ISSUE TITLE
Slightly too many fireflies in non-mgv6 mapgens

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2069]
![screenshot_20180304_201315](https://user-images.githubusercontent.com/3686677/36950118-2e315350-1fe9-11e8-80dd-219179046773.png)

Noticeable when forest thins out, too many fireflies makes them less special.
Also noticeable in coniferous forest where the branches are higher and less likely to intersect fireflies.
My guess is that in thick forest many fireflies are not placed because they intersect leaf nodes, this may be why they were so noticeable in mgv6.
Currently the total fill ratio is 0.004, so spacing is sqrt(1 / 0.004) = 16 nodes, roughly 1 per mapblock.

**Comment by Ezhh** [comment]
I'm unsure of the best approach here. In the rainforest the numbers seem just right, so reducing them there wouldn't be good.

Is this only a problem in the coniferous_forest biome? Maybe they shouldn't be in that biome?

**Comment by paramat** [comment]
The amount depends on the density of the forest and the height of the leaves above the ground. Yes it seems more noticeable in temperate coniferous forest because of the high leaves, but the lower density areas of deciduous forest (which have the higher aspens) may be like this too. It's a balance.
Fill ratio for a certain spacing is 1 / (spacing squared). I'll leave the tuning to you.

**Comment by paramat** [comment]
They seem a little too numerous in deciduous forest too, when i was testing water sounds in a low density area of deciduous forest i noticed fireflies seemed to be 1 every 16 nodes or so, as you would expect from the fill ratio.
I guess the way to tune them then is to reduce density as low as you can cope with while testing in rainforest. Occasionally a little rare is better than too many as it makes them nicer to discover.

**Comment by Ezhh** [comment]
Okay, consider it on my to do list.

**Comment by paramat** [comment]
#2072 merged.
