### ISSUE TITLE
Sapling trigger server crash

### ISSUE THREAD

**Issue by 00c** [minetest/minetest_game#2071]
When placed sapling server crashes. Does not happen with all saplings.
Server 0.4.16 
> ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod '' in callback item_OnPlace(): ....16/bin/../games/Liberty Land/mods/default/trees.lua:507: attempt to call field 'is_area_protected' (a nil value)
> 2018-03-05 20:43:12: ERROR[Main]: stack traceback:
> 2018-03-05 20:43:12: ERROR[Main]: 	....16/bin/../games/Liberty Land/mods/default/trees.lua:507: in function 'sapling_on_place'
> 2018-03-05 20:43:12: ERROR[Main]: 	....16/bin/../games/Liberty Land/mods/default/nodes.lua:634: in function <....16/bin/../games/Liberty Land/mods/default/nodes.lua:633>
> 
> 2018-03-05 20:54:47: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod '' in callback item_OnPlace(): ....16/bin/../games/Liberty Land/mods/default/trees.lua:507: attempt to call field 'is_area_protected' (a nil value)
> 2018-03-05 20:54:47: ERROR[Main]: stack traceback:
> 2018-03-05 20:54:47: ERROR[Main]: 	....16/bin/../games/Liberty Land/mods/default/trees.lua:507: in function 'sapling_on_place'
> 2018-03-05 20:54:47: ERROR[Main]: 	....16/bin/../games/Liberty Land/mods/default/nodes.lua:1597: in function <....16/bin/../games/Liberty Land/mods/default/nodes.lua:1596>
> 2018-03-05 20:55:58: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod '' in callback item_OnPlace(): ....16/bin/../games/Liberty Land/mods/default/trees.lua:507: attempt to call field 'is_area_protected' (a nil value)
> 2018-03-05 20:55:58: ERROR[Main]: stack traceback:
> 2018-03-05 20:55:58: ERROR[Main]: 	....16/bin/../games/Liberty Land/mods/default/trees.lua:507: in function 'sapling_on_place'
> 2018-03-05 20:55:58: ERROR[Main]: 	....16/bin/../games/Liberty Land/mods/default/nodes.lua:960: in function <....16/bin/../games/Liberty Land/mods/default/nodes.lua:959>

**Comment by Ezhh** [comment]
Could you please test whether this still happens if you disable any non-MTG mods you are using? It's again not an issue I've ever run into, either in stable or dev version, so another mod might be the cause.

**Comment by paramat** [comment]
`attempt to call field 'is_area_protected' (a nil value)` trees.lua calls this only in very recent MTGame.
Your MTEngine and MTGame versions are out of sync, i guess server is 0.4.16 stable and MTGame is very recent?

**Comment by 00c** [comment]
i have to update to dev version?

**Comment by paramat** [comment]
It's not safe to update server to 0.5, keep the server on 0.4.16 stable and only use MTGame 0.4.6 stable.

**Comment by 00c** [comment]
Thanks
