### ISSUE TITLE
Thicker pine needles texture

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2075]
![pines](https://user-images.githubusercontent.com/7035183/37246875-97aa7810-24a9-11e8-937f-db1a8f075ead.png)

The current one looks too transparent with fancy or glasslike leaves. Also, it's not great.

**Comment by paramat** [comment]
Possibility from the snow mod:

![needles_snowmod256](https://user-images.githubusercontent.com/3686677/37247607-79718828-24b5-11e8-8ed8-00458ebb6085.png)

![needles_snowmod](https://user-images.githubusercontent.com/3686677/37247609-7cee3f14-24b5-11e8-9bb2-c3cd6be50662.png)

**Comment by paramat** [comment]
![screenshot_20180310_230335](https://user-images.githubusercontent.com/3686677/37247706-6ba60faa-24b7-11e8-937a-2d3699cf94c6.png)

^ Fancy (allfaces)

![screenshot_20180310_230409](https://user-images.githubusercontent.com/3686677/37247707-710dd75c-24b7-11e8-9f98-feeda87bbc22.png)

^ Simple (glasslike)

I like it, it just needs some work to make it display correctly when opaque.

**Comment by paramat** [comment]
![screenshot_20180310_233315](https://user-images.githubusercontent.com/3686677/37247898-79dbcd18-24bb-11e8-871f-5ce3b445c931.png)

^ Opaque leaves

**Comment by paramat** [comment]
We actually have extra textures such as 'default leaves simple' which are thicker textures automatically used when 'simple' (glasslike) leaves is enabled. These suggested textures are thick enough even for 'simple'.

**Comment by paramat** [comment]
Will improve the background for the opaque leaves.

**Comment by paramat** [comment]
![screenshot_20180311_021046](https://user-images.githubusercontent.com/3686677/37248766-9f68b18e-24d1-11e8-8096-318b8cdd0acc.png)

^ Opaque
Created by making a dark version of the texture and layering this behind the normal texture.

**Comment by XenonCoder** [comment]
@paramat I really like this new aspect, it makes the trees much more "voxel style" as I like it. I find it a nice aesthetic solution because one of the fundamental aspects of MTG is vegetation.

It would be nice to see these changes even in all the trees of the vanilla (MTG). I'm very happy with this, maybe you can improve some aesthetic aspects like the jungletrees (ugly trees).

Paramat thanks for your good work, finally the 0.5.0 will bring Minetest to take the big step that many years have been waiting for.

**Comment by Ezhh** [comment]
Okay, I much prefer this texture and it looks like it will definitely handle the issue.

**Comment by paramat** [comment]
Will make a PR.

**Comment by TumeniNodes** [comment]
@paramat , nice job, it looks good

**Comment by paramat** [comment]
#2080 merged.

**Comment by paramat** [comment]
LOL i didn't know that.

**Comment by JurajVajda** [comment]
yeah, just coincidentally working on reviving an old Christmas tree from Splizard/LazyJ snow mod (when there was no snow in Minetest i guess at that time) and saved some time with updating the needles texture to the latest MTGame texture :)

https://github.com/LazyJ/snow/blob/master/textures/snow_needles_decorated.png

![x_default_pine_needles_comparison-min](https://user-images.githubusercontent.com/5089392/49418407-f930c480-f74f-11e8-8f4d-a18aab979121.png)
_left new texture, right 5 years old texture_
