### ISSUE TITLE
Marram grass has sand

### ISSUE THREAD

**Issue by tacotexmex** [minetest/minetest_game#2078]
![skarmavbild 2018-03-11 kl 12 32 28](https://user-images.githubusercontent.com/25328789/37252821-7c14f312-2528-11e8-931f-c825bc85059f.png)

The newly merged marram grass' texture has sand in it which makes it look out of place on any other node.

Either allow marram to be placed only on sand or remove the sand from the texture itself.

**Comment by Ezhh** [comment]
I really like the texture as is, so would support it being placeable only on sand instead of changed.

Let's see what others think.

**Comment by paramat** [comment]
The solution is to not place it on non-sand nodes =)

There are many nodes that look wrong on various nodes, like any plant on stone etc. but i'm sure it's not worth adding the complexity of placement functions and causing slight performance loss to check the suitability of the node beneath.

Also consider mod nodes that are sandy but are intentionally not in the 'sand' group, the placement function will not consider these as suitable.
I think it's best to go with simplicity here.

**Comment by JurajVajda** [comment]
We can always use texture packs/custom textures for removing the sand if its so inconvenient for some..

**Comment by benrob0329** [comment]
There is sand on the roots, what do you expect?

**Comment by tacotexmex** [comment]
I expect that when you pull stuff from the ground the ground doesn't come with it.

**Comment by TumeniNodes** [comment]
Leave it as is.
This is a non-issue as this is the way it was intended.
I could go into a long explanation with points but I'm too tired

**Comment by benrob0329** [comment]
>I expect that when you pull stuff from the ground the ground doesn't come with it.

Have you even done gardening? That really is what happens lol. You pull a plant and get a chunk of dirt with it.

**Comment by tacotexmex** [comment]
Really? Then we need a new issue for ”wheat with dirt” too. What about flowers, other types of grass?

**Comment by paramat** [comment]
Valid issue, but i'll close in the interests of simplicity and freedom to place stuff where it doesn't make sense.
