### ISSUE TITLE
Reduce Snowy Biome Probability

### ISSUE THREAD

**Issue by TekhnaeRaav** [minetest/minetest_game#2079]
Attributing to issue [#5201](https://github.com/minetest/minetest/issues/5201) on the engine.
This I believe is still an issue, while it may add some hardcore game play to it, there still is, if I'm right, more than four times the chance than any other biome, that the next biome that you meet is some kind of cold biome. We have **FOUR** types of cold/snowy biomes, icesheet, snowy grassland, tundra, and taiga. Not to mention the cold deserts. Not only is this unrealistic, but with this many cold biomes, if I'm right, you can end up with long chains of repeating cold biomes that hardly end on foot. And while the biomes don't need to be the same size, biomes this enormous of this type is to much. If you want more hard core, you need hardcore that comes in color.

**Comment by paramat** [comment]
I reopened the engine issue, but that is not related as these are game issues.

> there still is, if I'm right, more than four times the chance than any other biome, that the next biome that you meet is some kind of cold biome.

No, we have 12 primary biomes equally spread over cold, temperate and hot, so 5 cold biomes is reasonable and close to a third. There's no more chance than the next being temperate, or hot.

It's not unrealistic, see my threads during the designing of the biome system, i spent many 10s of hours moving points around to get a good representation of the Whittaker biome classification diagram, and worked long and hard to make it include all major biome types.

You can also end up with long chains of temperate biomes, or hot biomes, or forests, while exploring.

Hardcore in colour?

Anyway, we had a discussion and issue #2076 is a good idea and covers the valid parts of this issue.
