### ISSUE TITLE
Bones messages for player and log (separately toggled)

### ISSUE THREAD

**Issue by poikilos** [minetest/minetest_game#2083]
(See pull request https://github.com/minetest/minetest_game/pull/2082)

I have been using this on my server and thought other people might want it (feedback is welcome), especially since it is optional.
The changes include two options (for minetest.conf) which can be enabled separately, or both can be enabled:
* `enable_bones_logging` (boolean, default false): When a player dies, the code logs a message regarding whether bones were dropped (or why they werent), and the location. The bones logging option could be helpful for similar reasons as existing log messages generated by minetest (forensics, debugging, etc). You may want to consider making this option on by default (true if the minetest.conf setting does not exist).
* `enable_bones_chat_msg` (boolean, default false): When a player dies, that player gets a chat message with the same information as above. The chat option has helped reduce support requests for me, but I can understand some server owners may not want it if they believe it detracts too much from immersion or from players learning minetest navigation skills. In my case, I want to encourage building (and reduce the fallout of gang/repeat killing), so if a player dies, I'd rather have them be able to find where they left off. Even just informing them of why their bones didn't drop helps reduce support requests since otherwise it can be perceived as a bug (or as though they failed to find them and should keep looking for something that doesn't exist).

**Comment by poikilos** [comment]
added request for feedback at <https://forum.minetest.net/viewtopic.php?f=5&t=19821&p=314425#p314425>

**Comment by ritschwumm** [comment]
yes please!

**Comment by raymoo** [comment]
Seems like this was added by the linked PR (#2082) and can be closed?
