### ISSUE TITLE
TNT clears nodes metadata

### ISSUE THREAD

**Issue by vladtcvs** [minetest/minetest_game#2084]
after boom tnt ejects some amount of nodes, same as nodes, present in boom radius. But their metadata is cleared.

For example: place tnt and chest nearby. Put something to the chest. Explode tnt. Find dropped chest and place it. It will be empty.

**Comment by SmallJoker** [comment]
Depending on the definition, it either drops the items inside or isn't removed. The unfortunate third case is however when no `on_blast` is specified. TNT would then drop the node regardless on the contents. In that case we need to check against the `can_dig` callback return value to make sure no data is lost.

**Comment by sofar** [comment]
The standard chest drops the items. If you are using the mtg chest and it isn't modded by protection mods then the items will all fall on the ground.

Tested again just now. This is working as designed.

**Comment by sofar** [comment]
BTW someone made the point that dropping the chest suggests the items are still in it. Maybe we should not drop the chest but only the contents, and that would be a valid suggestion/feature enhancement I think.

**Comment by SmallJoker** [comment]
@sofar But what about other mods? TNT has potential to destroy locked chests and their contents which don't use the default API.

**Comment by sofar** [comment]
That's easily fixable in those mods. 

From what I've seen, this is widely fixed already by protection mods which make sure not to destroy chests and doors, and the API has existed for a very long time already that I know that other chest mods just don't allow blowing up chests at all.

**Comment by vladtcvs** [comment]
@sofar and what about other mods, which contains nodes with metadata, and this metadata should be saved after blowing? They should care themselfs about this?

**Comment by sofar** [comment]
The TNT API has existed for ages, and most mods I know already implement the proper way to prevent destruction by the proper mechanisms. If you find a mod that doesn't, the mod can be easily fixed.

**Comment by HybridDog** [comment]
You could add a list of such mechanism to lua_api because finding them all is not straightforward, there are on_destruct, on_blast, the screwdriver's callback, can_dig, diggable, etc.

**Comment by jastevenson303** [comment]
lua_api.text is for the engine, game_api.text is where the screwdriver api
docs are.

**Comment by Ezhh** [comment]
game_api.txt already has some information on TNT, including for on_blast. If it's not enough, then please do open a separate issue for whatever is missing from the documentation, or make a PR to fix it directly.

**Comment by HybridDog** [comment]
The documentation should be game-independent, so it should also mention mod-specific things, e.g. mesecons mvps.
Maybe it can be put there: http://dev.minetest.net/Mod_interoperability#Indestructible_nodes

**Comment by Ezhh** [comment]
lua_api is for game independent modding information.  game_api is for MTG info. TNT information belongs in MTG's game_api because it's part of MTG.
