### ISSUE TITLE
Add butterflies mod

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2090]
I would certainly like flappy butterflies as a daytime bug, hidden at night.

Since the fireflies mod has a bug net and the 'catchable' group it seems possibly best to include butterflies in that mod? Then rename the mod to 'bugs' or whatever is suitable.
We are in dev stage so don't worry about causing some unknown nodes in some worlds.

**Comment by rubenwardy** [comment]
I'd like to see this too

**Comment by Ezhh** [comment]
I have... the issue of not being able to think of a single mod name I like even halfway as much as "fireflies". (Yes, I have the same issue on HW.) 

Bugs sounds horrible and sets an expectation for far less pretty things. 
(...and I'm a bit reluctant to literally make "bugs" a feature)

**Comment by benrob0329** [comment]
How about ``insects``?

**Comment by paramat** [comment]
Half serious: 'imobs' for 'immobile objects' :)

**Comment by Ezhh** [comment]
I guess insects is winning so far, though I'd be very happy to hear other suggestions.

**Comment by XenonCoder** [comment]
Insects give life and color to the maps, and they are very beautiful and original decorative features (MC does not own these things, so we begin to insert new ideas).

I like it, because Minetest is mainly focused on creative mode (good and right), so everything that makes the creative and artistic project makes me happy.

@benrob0329 As a good name (according to me) being a default mod (minetest_game) does not have to have a particular name, so "insects" perfectly describes the content and there is nothing else to add.

**Comment by paramat** [comment]
I'm ok with 'insects' i guess this won't ever include non-insects?

**Comment by Ezhh** [comment]
@paramat That somewhat depends on what I (or others) manage to think up and get working. I have some plans to attempt other things, but they are only ideas right now and quite possibly wouldn't be for MTG anyway.

**Comment by paramat** [comment]
Yes that's why i suggested 'imobs', however since there is a 'bug catcher' and these mobs are likely to be very small and dumbly-moving things it's likely they will be insects only.

**Comment by Ezhh** [comment]
I'd prefer insects to imobs.

**Comment by paramat** [comment]
Yes it's more descriptive so seems better.

**Comment by paramat** [comment]
With some discussion, i'm ok with butterflies being a separate mod. This issue was about discussing what to do instead of requesting all in one mod.

**Comment by Ezhh** [comment]
Test version is more or less done now: https://github.com/Ezhh/butterflies

It's just a case of how to include them.

**Comment by Fixer-007** [comment]
When I see /bugs I think of the code bugs in this game, TODO and FIX.
