### ISSUE TITLE
Experiments with translucent ice

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2092]
![screenshot_20180323_031639](https://user-images.githubusercontent.com/3686677/37810232-dd701d6e-2e4a-11e8-8b31-9954a7b902aa.png)

![screenshot_20180323_031951](https://user-images.githubusercontent.com/3686677/37810248-ed68e07a-2e4a-11e8-81a5-0f7776ae76a7.png)

![screenshot_20180323_032844](https://user-images.githubusercontent.com/3686677/37810250-f0aa645c-2e4a-11e8-8691-50245c9ef2b8.png)

^ Ice dungeon high up inside the ice mountain seen below

![screenshot_20180323_032939](https://user-images.githubusercontent.com/3686677/37810253-f50d999c-2e4a-11e8-92af-7509371cea71.png)

^ Dungeon entrance is visible

In Gimp i did 'color to alpha' using the dominant blue pixel colour to isolate the 'shine' pixels, then combined this with a plain alpha texture of those blue pixels with opacity 90%.
The high opacity and opaque shine pixels shine emphasise the surface and make the sometimes weird rendering and flicker against water less of an issue.

Even if we don't use a translucent texture in MTG this nodedef will allow texture packs to do so if desired:
```
minetest.register_node("default:ice", {
	description = "Ice",
	drawtype = "glasslike",
	tiles = {"default_ice.png"},
	use_texture_alpha = true,
	is_ground_content = false,
	paramtype = "light",
	groups = {cracky = 3, puts_out_fire = 1, cools_lava = 1, slippery = 3},
	sounds = default.node_sound_glass_defaults(),
})
```

**Comment by paramat** [comment]
Tried opacities 93, 95, 94, with 94 currently seeming optimum.

Quick unrelated note: snowblock should be 'paramtype = light' like snow, to transmit some light?

**Comment by paramat** [comment]
However i do find the ice mountains look much better completely opaque, and opaque ice looks really good.
But we could still perhaps add the nodedefs to allow this possibility using texture packs.

**Comment by XenonCoder** [comment]
@paramat Interesting idea, the ice biome is very unique with this effect. Everything that brings additions and improvements to Minetest is good for me.

It would be interesting to insert loot (as for dungeons) in the translucent ice biome, so players can see through the ice and discover hidden treasures. Obviously it is an idea that I want to experiment with my mod, but translucent ice gives new possibilities to the modders.

Paramat I really like your recent ideas on the mapgen, I trust in your power :D

**Comment by paramat** [comment]
Yes all visual bugs are present, the high opacity reduces their visibility though.

This was fun to experiment with for a couple of hours but after the novelty finished it wasn't so good, the main point being the ice mountains just look wrong being translucent, they look so much better opaque. Ambient occlusion disappears for the ice and you get isolated dark patches of ambient occlusion on the snowblocks.

I'm not even keen on supporting alpha ice textures due to the visual bugs it causes.

**Comment by Ezhh** [comment]
> ... they look so much better opaque. 

We will just have to agree to disagree there. Obviously the bugs make it unacceptable for default, but it looks much better to me when you can see through the ice and it opens up all kinds of extra building potential.

**Comment by Ezhh** [comment]
Well, my personal wish for it is as sea ice rather than mountains, and I'd be completely happy having more than one type of ice for this purpose. Applying beer's law would of course be ideal, but you already stated the issues there...

Can we just magically stop the flickering at least? Pretty please? Somehow?

**Comment by paramat** [comment]
The first 2 screenshots look ok to me, but i positioned myself to not see a bug, in-game there are more noticeable bugs, parts of ice corridors disappear in weird ways or appear rendered back to front, there is some flickering between water and ice. I think this would have to wait for z-sorting to be implemented.

**Comment by Extex101** [comment]
How about using allfaces?
You can see stuff behind it but not inside
![Screenshot_2019-03-15-13-52-26-1](https://user-images.githubusercontent.com/33675971/54461629-60d0b580-472a-11e9-82a8-713038a01949.png)
![Screenshot_2019-03-15-13-52-36-1](https://user-images.githubusercontent.com/33675971/54461654-76de7600-472a-11e9-8978-4dec32223e63.png)
There's actually an empty space inside here
![2019-03-15 13 56 15](https://user-images.githubusercontent.com/33675971/54461673-852c9200-472a-11e9-9632-633afe9ef99c.png)
With torches on the walls /\

![Screenshot_2019-03-15-13-53-06-1](https://user-images.githubusercontent.com/33675971/54461723-ac835f00-472a-11e9-8496-62f7c14e07fd.png)
 This eliminates the seeing caves problem 
And the ice layers up and gets more and more opaque  (in theory)

**Comment by paramat** [comment]
That will still have the same translucency issues, but more importantly, allfaces with translucency will render every iceface inside a volume so will be extrememly intensive to render.

**Comment by Ezhh** [comment]
If the flicker ever gets fixed, one way to approach this could simply be two layers of ice - filler layer translucent, and the stone layer with current ice below it.
