### ISSUE TITLE
Add Nyan Cat, but with other name

### ISSUE THREAD

**Issue by stas730** [minetest/minetest_game#2099]
Nyan Cat was removed some time ago. Many players have installed nyancat mod because they didn’t want Nyan Cat to be removed.
Nyan Cat can be added again, but name must be changed to avoid trademark issues. "Nyā Cat" is example ("nyā" is Japanese word, so it can’t be trademarked).

**Comment by rubenwardy** [comment]
:-1:, as in other issue

**Comment by Ezhh** [comment]
:-1: ... as in other issue.

**Comment by SmallJoker** [comment]
For reference: http://irc.minetest.net/minetest/2018-03-24#i_5259227

:-1: 

![Slapping dead horse](http://gifimage.net/wp-content/uploads/2017/06/beating-a-dead-horse-gif-11.gif)

**Comment by stas730** [comment]
@SmallJoker, please, do not remove anything. You have changed the image.
Also, we need a discussion first.

**Comment by SmallJoker** [comment]
@stas730 Moving pictures distract too much, so I took the opportunity to use the edit function which exists for a certain purpose.
If you're looking for a discussion or player feedback, then is #1685 the right issue for you.
