### ISSUE TITLE
Possible divisions by 0 in tnt mod

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#2100]
The `tnt` mod has a possible division by zero in the function `calc_velocity`.

If `pos1` and `pos2` are equal, `dist` becomes 0, but the code will attempt divisions by `dist` a few lines later.

**Comment by paramat** [comment]
What line number?

**Comment by tenplus1** [comment]
dist has a max value of 1 inserted to stop this happening, also if pos1 and pos2 are equal then it returns from the cal_velocity function.

**Comment by SmallJoker** [comment]
There is indeed the `math.max` which prevents from this case.
https://github.com/minetest/minetest_game/blob/b0e55c52c827c44770bd2575a8293544e02d5e48/mods/tnt/init.lua#L130-L132
