### ISSUE TITLE
Pause menu trigger warning while in minetest_game, minimal game not affected

### ISSUE THREAD

**Issue by juozaspo** [minetest/minetest_game#2101]
Pausing the game while in minetest_game subgame triggers warning: `WARNING[Main]: invalid use of background without a size[] element`. Nothing happens while in minimal game. Since I'm not sure if this is engine issue or subgame assets issue, I'm posting this here.
While running game with --info flag I see more messages while holding the 'esc' key to trigger the menu:
```
2018-04-04 16:51:47: INFO[Main]: Unknown DrawSpec: type=formspec_version, data="1"
2018-04-04 16:51:47: WARNING[Main]: invalid use of background without a size[] element
2018-04-04 16:51:47: INFO[Main]: Unknown DrawSpec: type=formspec_version, data="1"
```
Commit: 11b34076719ded242e73465ba0c63d1d790b5761
Minetest build  I'm running on is Run In-Place linux build
```
Minetest 0.5.0-dev-debug-392e80e3 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Debug
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
```

**Comment by rubenwardy** [comment]
This is an engine bug caused formspec prepending
