### ISSUE TITLE
Text on signs

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#2104]
Obvious feature improvement minetest_game needs, discuss here on how to implement. Also add to roadmap https://github.com/minetest/minetest_game/projects/1

**Comment by paramat** [comment]
There's an engine issue somewhere. I can't see this being a game issue until the engine feature requires a change in MTG.

**Comment by paramat** [comment]
Discuss in https://github.com/minetest/minetest/issues/1367

**Comment by Fixer-007** [comment]
This will be reopened when engine has this capability.
