### ISSUE TITLE
Division by zero in TNT mod (for real this time)

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#2105]
In `tnt` mod, function `tnt.boom`:
```
	local damage_radius = (radius / def.radius) * def.damage_radius
```

https://github.com/minetest/minetest_game/blob/master/mods/tnt/init.lua#L404
Commit: 11b34076719ded242e73465ba0c63d1d790b5761

Long story short: If `def.radius` is exactly 0, there's a division by 0. This can happen if you call `tnt.boom` by setting `def.radius` to 0 explicitly.

The `mobs` mod (Mobs Redo) does this to call `tnt.boom` only to cause entity damage, but not to delete nodes. This is a totally legit use case IMO.

**Comment by sofar** [comment]
I'll add `assert(def.radius > 0)` to the code to prevent this modding mistake, and update the documentation to clearly state that a radius of 0 is invalid.

**Comment by sofar** [comment]
Any value below 1.0 is invalid, btw.

**Comment by sofar** [comment]
We can just limit the factor to `1` here since this is about entity damage at this point.

**Comment by Wuzzy2** [comment]
OK.
But wouldn't it be more useful if you can make an explosion *intentionally* with radius 0 so you can do a fake explosion which only deals player damage?

**Comment by paramat** [comment]
You still can.
At this point in the code it is determining entity damage radius, the value is multiplied by 'def.damage_radius' which you can still set to 0, the PR just avoids doing 'infinity * 0'.

**Comment by paramat** [comment]
#2106 merged.
