### ISSUE TITLE
Use plantlike_rooted on papyrus

### ISSUE THREAD

**Issue by tacotexmex** [minetest/minetest_game#2112]
Now that underwater plantlikes are possible, papyrus should grow from shallow sea bottoms, not from overwater dirt nodes.

**Comment by paramat** [comment]
Good idea for placement in mapgen, i don't like having to place them on cubes. We would need to alter the growing and 'dig_up' functions for papyrus.

**Comment by tacotexmex** [comment]
Ezhh's solution is acceptable for that specific node but the tradeoff of breaking the rule of generally being able to "place any node on any node" feels limiting.

(I didn't realize how rigid plantlike_rooted is. I realize it's probably called rooted as a consequence of what technical solution was available (and not plantlike_in_water for example)?)

**Comment by Ezhh** [comment]
Yes, the plantlike rooted node is actually not the plant, but the node under it. You need to define textures for both the node it's on as well as the plant itself, so if you wanted to let it grow from multiple different nodes you'd need to register one node for each, and make any associated checks increasingly more complicated as a result.

**Comment by tacotexmex** [comment]
Okay but just to be sure, and sorry for straying off topic, this is the only way to put plantlike-looking nodes under water and not create air bubbles? Is there a simple, more general solution in sight (that not involves connected nodes and the like)?

**Comment by Ezhh** [comment]
This is currently the only way to place plants in water without the air bubble issue.

> If so then papyrus would perhaps be a better fit for that solution than this.

Do you mean you would prefer to leave papyrus as they are then take the approach I suggested?

**Comment by tacotexmex** [comment]
Okay.

> Do you mean you would prefer to leave papyrus as they are then take the approach I suggested?

I'm unsure. It seems that plantlike_rooted is a solution for completely underwater plants only, nothing else. 

The solution seems quite hacky but I guess if it works well people won't know the code behind it. With that in mind I support it as an intermediate solution.

**Comment by Ezhh** [comment]
It's totally possible to use it for plants that are partly above water as well; it's just that (in my opinion) it won't work well unless you are happy to count it as a single plant/mode, instead of multiple nodes like papyrus currently is.

**Comment by tacotexmex** [comment]
I agree with you that papyrus behavior shouldn't change.

**Comment by paramat** [comment]
If papyrus was new i would certainly prefer plantlike_rooted, the only issue is MTG history and players being used to how it has been and maybe having farming machines or mods depending on how it has been. Although i don't mind a little breakage. It depends on how the implementation turns out and how much players complain :)

**Comment by TumeniNodes** [comment]
Introduce both. keep the node mounted (meaning current) closer to shore, or even attached to shoreline, and then the new 'plantlike_rooted' beyond that, in the water.

satisfies fans of both old and new style (because I _really_ like this idea, and enhances the visuals. That;s a win-win in my view

**Comment by tacotexmex** [comment]
What if we want to put stacked papyrus nodes in two node deep waters?

**Comment by tacotexmex** [comment]
I agree. We need a proper ”water with plantlike” drawtype that’s independent from its surrounding nodes.

**Comment by paramat** [comment]
It's unfortunate as i would really like to use that drawtype for papyrus. But we would have to break previous behaviour of papyrus.
Closing for now but we can continue to discuss here.
