### ISSUE TITLE
toolrepair with addition_wear yields incorrect results

### ISSUE THREAD

**Issue by NathanSalapat** [minetest/minetest_game#2113]
If you create a craft to repair two tools and add additional wear the engine seems to ignore the recipe if the result from the craft should have no output.

minetest.register_craft({
   type = "toolrepair",
   output = "default:shovel_wood",
   recipe = {"default:shovel_wood", "default:shovel_wood"},
   additional_wear = 1
})

If you have two shovels that have a lot of damage, enough that they can't supply the additional 1 wear that the craft calls for the engine will just combine the tools as normal, rather than not giving any output.

Lua_api doesn't mention this, nor does the dev wiki. Not sure if it's actually an error, or if the documentation should just be updated to mention it.

**Comment by SmallJoker** [comment]
That's an engine issue.
-> https://github.com/minetest/minetest/issues
Related code: https://github.com/minetest/minetest/blob/master/src/craftdef.cpp#L573-L599

**Comment by NathanSalapat** [comment]
My bad, should I open an issue in the engine for this? I'm unsure if it's actually a bug or just lacking documentation.

**Comment by NathanSalapat** [comment]
Okay, I'll open a bug in the engine. Thanks.
