### ISSUE TITLE
Keyring sfinv tab

### ISSUE THREAD

**Issue by tacotexmex** [minetest/minetest_game#2115]
Instead of wasting valuable space by housing a bunch of keys in the main inventory, add a "Keyring" sfinv tab with its own inventory.

**Comment by paramat** [comment]
I don't see keys as fundamental enough to create a new inventory section for, they're just a feature of one mod :-1:

**Comment by Ezhh** [comment]
With the way keys are right now, sorry, but also a :-1:  from me.
