### ISSUE TITLE
Configurable starting biomes in spawn mod

### ISSUE THREAD

**Issue by tacotexmex** [minetest/minetest_game#2116]
Now with #2091 merged, some configurability of the mod is needed for adding new biomes to it.

My suggestion is the following API functions:
- `minetest.clear_registered_spawn_biomes(biome_id)`: Empties the `biome_ids` table.
- `minetest.register_spawn_biome(biome_id)`: Adds an entry to the `biome_ids` table.
- `minetest.unregister_spawn_biome(biome_id)`: Removes that entry in the `biome_ids` table.

**Comment by paramat** [comment]
Hmm i'm not sure, the starting biomes are set to those friendly for new players, i don't yet see much need to change those, the mod can already be disabled by a setting for a more challenging spawn. If necessary it is very easy to edit that list in the mod.

**Comment by tacotexmex** [comment]
This would be for when registering (spawn friendly) biomes in addition to the existing ones (or when using a another set of biomes completely).

**Comment by Ezhh** [comment]
Might it instead be worth having a conf setting to list starting biomes in if you want alternatives? I can maybe see a use for that, but an API seems overkill.

**Comment by paramat** [comment]
I see, new biomes or alternative biome systems, but then additional biomes are quite rarely done by mods, and a new biome system tends to be done by entirely new games. Worth considering but seems low priority and i'm not sure how to implement it. An API does seem overkill.
It's very easy to edit the list in the mod if necessary.

**Comment by tacotexmex** [comment]
> quite rarely done by mods

I disagree, I found the sumpf, mcnodes, extra_biomes, grassland and Future_pack mods in just seconds.

> It's very easy to edit the list in the mod if necessary.

I the case of modifying MTG into a new subgame, yes.

**Comment by tacotexmex** [comment]
Sounds about right.

**Comment by paramat** [comment]
Ok so this can be combined into #2117
