### ISSUE TITLE
Spawn mod: make the spawning code a global function usable by mods

### ISSUE THREAD

**Issue by tacotexmex** [minetest/minetest_game#2117]
With a good spawnpoint finding algorithm in place, it could be utilized in order to teleport multiple players apart in a specific radius with a specific coordinate as center point. It can be part API function, part chat command:
- `minetest.spreadplayers(x, z, min_range, max_range, player)`
- `/spreadplayers x z min_range max_range player`

(the player variable would be optional)
////////////////////

EDIT by paramat: Request changed, see new thread title and discussion.

**Comment by paramat** [comment]
Good idea, something i have wanted to do for a long time, see https://github.com/minetest/minetest/issues/6229
There are some issues, where does a player get respawned? Their initial spawn might need to be stored in a world file to be used for respawn, which could get big and slow to access on a popular server.

**Comment by tacotexmex** [comment]
In my mind this would be a specialized teleport command and function and thus not update tespawn point.

**Comment by tacotexmex** [comment]
> the spawnpoint search should be available as a global function for mods to use as they wish for various purposes, so a function that is more neutral and universal.

Yes, I also realize that the feature is a bit niched so this would provide a good general solution to solving this specific problem.

Let’s reframe and rename the issue?

**Comment by paramat** [comment]
I agree.

**Comment by tacotexmex** [comment]
With the new direction in mind, I want to state my wish for a method of getting and setting the friendly biome IDs.

**Comment by paramat** [comment]
Rolling #2116 into this, biomes could be an argument of this function.

**Comment by paramat** [comment]
Related issue: I'm thinking this spawn mod should function 'on respawnplayer' too, i've noticed after a death a player respawns a long way from their initial spawn and in unfriendly biomes. With engine spawning, initial spawn and respawn are similar places.

**Comment by paramat** [comment]
PR #2257

**Comment by paramat** [comment]
Looks like #2257 will be moved to an API in engine 'builtin' for use by all games.
