### ISSUE TITLE
Un-selectable node with Big Pumpkins

### ISSUE THREAD

**Issue by eric-presbitero** [minetest/minetest_game#2119]
Make and place a big pumpkin.
It occupies a center node, half a node around it and a top node.

If you use to node replacement tool to put something in the surrounding nodes (not the central). For example pointing to the ground and right clicking. You get the pumpkin section, which has no name and once placed somewhere is un-selectable. The only way to remove it is by using the node replacement tool again.

**Comment by Ezhh** [comment]
Neither pumpkins, nor node replacement tool are part of minetest_game. You may need to speak to the creators of the mods you are using if you have a problem with these.
