### ISSUE TITLE
Sink into snow a little using a custom collisionbox

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2132]
A while ago we made the snow slab non-walkable so that players are sunk into it, but we then caused false footstep sounds coming from the node below, so it was reverted.
Just realised we can make the collisionbox lower to make the player sink into snow a little while still triggering the correct footstep sound.

I suggest:
Snow slab is 1/4 node thick, make collisionbox 1/8 node thick.
Snowblock: Lower collisionbox top by 1/8 or 1/4 node.

**Comment by paramat** [comment]
![screenshot_20180530_013625](https://user-images.githubusercontent.com/3686677/40692524-40c39870-63aa-11e8-987f-932cd95b13b0.png)

```
	collision_box = {
		type = "fixed",
		fixed = {
			{-0.5, -0.5, -0.5, 0.5, -0.375, 0.5},
		},
	},
```

![screenshot_20180530_013729](https://user-images.githubusercontent.com/3686677/40692541-56c91b18-63aa-11e8-84ee-7a44b6e1f6a0.png)

Deep snow.
```
	collision_box = {
		type = "fixed",
		fixed = {
			{-0.5, -0.5, -0.5, 0.5, 0.25, 0.5},
		},
	},
```

**Comment by paramat** [comment]
Confirmed correct footsteps play.
With sinking 1/4 node into snowblock jumping up onto a raised node is still possible.

![screenshot_20180530_015408](https://user-images.githubusercontent.com/3686677/40692925-770f77d0-63ac-11e8-80f6-08499c659646.png)

Correct footsteps with a 1/16 node collisionbox.

**Comment by Ezhh** [comment]
You know I'm in favour of sinking into snow (because it's me doing that elsewhere that seems to have sparked this), but I really don't like the idea of adding that change to snowblocks. It would mean dropping the player down to the wrong level compared to walking on other nodes.

**Comment by paramat** [comment]
Leaving snowblocks as they are is ok with me.

**Comment by Ezhh** [comment]
Full support from me if those are left. :)

**Comment by Fixer-007** [comment]
Possibly good idea.

**Comment by benrob0329** [comment]
IMO snow shouldn't be treated as a normal build material, you can only stand on it under very specific circumstances IRL.

**Comment by paramat** [comment]
Actually, i very much want snowblocks to have the same sinkage, will make a PR.

**Comment by Ezhh** [comment]
Sorry then, but it will be :-1:  from me. I feel very strongly about this.

**Comment by paramat** [comment]
Why?
PR #2133

**Comment by Ezhh** [comment]
1 - No matter how logical it is or otherwise, snowblock has been used as a regular node too much and you have no way to know what depends on that.
2 - I've always viewed snowblock as hard compacted snow that has become solid (otherwise it should fall as well, which would create even more issues for existing worlds).
3 - Walking from another node onto snow would create the effect of dropping the player down slightly, and that doesn't look good to me. This is not an issue with snow itself because it's not a full node to begin with.

**Comment by paramat** [comment]
1 - Yes, i would like any input on possible breakage, however if no specific examples are explained then this is not a valid obstruction. If in future someone has a valid complaint we can revert snowblock.

2 - I've always viewed snowblock as thick snowfall and not compacted snow, and that's what it actually is because that's how it is used for biomes, and a node's properties should be defined by the natural biome occurrence, not what they were used for afterwards in builds (because in builds there will be many interpretations, some use it as thick snowfall, others as compacted snow).
Snowblock is not a construction node, it's a natural snowfall node that occurs in biomes in vast quantities. The overwhelming experience of the node is of natural thick snowfall.

3 - I discovered when i tested it that the sink into a snowblock together with the sound gives a lovely feeling of walking in snow, like in real life. It really adds to the lovely experience, after this it then seems unpleasantly solid to not do this.

If sinkage is done for snow then not doing it for snowblock will be weird and inconsistent. One makes no sense without the other.

We can always add a compacted snow node, in fact we should have done this long ago instead of encouraging snowblock as a construction node. The texture could have a little less contrast and have the surface 'waves' removed, because it has flatter faces.

Maybe we could add a new node that is 'thick snowfall' for use in biomes, use the current snow texture for it, and make 'snowblock' the solid construction node with a new texture? The 'waves' on the texture are not suitable for a flat-sided compacted snow construction node.

**Comment by paramat** [comment]
Or maybe a new 'thick snowfall' node could be added that is then used for biomes, leaving snowblock unchanged? It would be a little weird because then existing icesheet biomes would have snowblock as surface node while new areas have the new node, however, the biome currently has solid snow nodes as surface so not much change.

Snowblock would then have a new texture with the surface 'waves' removed, because it is a compacted flat-faced construction node. Many players don't like the waves anyway and they are unsuitable for builds.

**Comment by Ezhh** [comment]
1 - Players build using the node in its current form. This means there will be issues. This is already a "valid complaint".

2 - Your interpretation of what a snowblock is doesn't make sense to me because, if it was what you say, it would fall (and always should have). It's also players who get to say what is a construction node, because they are the ones doing the constructing. 

3 - That's your subjective experience. Personally I find the drop in height extremely unpleasant. It doesn't make sense that on flat ground you walk into snow and suddenly drop below where you were standing while not in snow. Snow doesn't cause ground level to drop like that, so there's nothing natural about it.

I don't disagree with sinking into snow in general, but it needs to be done properly. Your alternative suggestion of an additional node sadly doesn't address the third point, unless you are willing to switch to using a thicker, but still partial, deep_snow node (I'd favour this, because then it could be falling, and I really don't like the current use of snowblock as a dust node).

**Comment by paramat** [comment]
Some more number ping-pong :)

1 - The issues are currently imagined, they need to be explained, i can't think of any issues, or only minor rare ones.

2 - Yes it was chosen as non-falling to allow building with it, so certainly it has been somewhat presented as a construction node. About falling, some nodes don't fall when they probably should, for example dirt, MTG doesn't make sense sometimes.
It's not players who decide the properties of a node, it is game creators, and in MTG the node occurs as thick snowfall so should be considered as that. Players are of course then free to use a node in construction if they want, they can 'consider' a node a construction node if they want.

3 - Anyone who likes walking in snow will like sinking into a snowblock, it really completes the snow experience in MTG. It's weird you don't like it.
>  It doesn't make sense that on flat ground you walk into snow and suddenly drop below where you were standing while not in snow

It does actually, obviously. Imagine walking off a step into thick snowfall of the same height, it compresses, and you go 'aahhh lovely snow' :)

The new thick snow has to be a normal cube not a nodebox because nodeboxes significantly reduce FPS.
In addition, we could then make it 'falling' to solve the other issue we have discussed about thick snow on leaves not falling.
Makes a lot of good sense to me. So i'm suggesting the new node approach as my preference.

**Comment by Ezhh** [comment]
> It does actually, obviously. Imagine walking off a step 

Problem being, I specifically referred to flat ground.

**Comment by paramat** [comment]
#2133 merged.

With some IRC discussion we may now have an agreement for a new approach.
