### ISSUE TITLE
Dye basecolor groups are weird

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#2134]
If you look into the dye mod (<https://github.com/minetest/minetest_game/blob/master/mods/dye/init.lua>), and then look into the groups, you notice something:

The `basecolor` groups for dyes are defined as:

`dye.basecolors = {"white", "grey", "black", "red", "yellow", "green", "cyan", "blue", "magenta"}`

However, `basecolor_orange` and `basecolor_brown` are used for the orange and brown dye, respectively, although those `basecolor` groups should not exist. These questionable groups are also not mentioned in `game_api.txt`.

This doesn't look right. Was this added by accident? Can somebody please check this and maybe clarify things?

**Comment by paramat** [comment]
Dyes certainly are weird, i don't understand the basecolor excolor unicolor stuff.

**Comment by paramat** [comment]
#2186 merged.
