### ISSUE TITLE
Creative Mod Inventory Shows and Is Usable with Other Tabs

### ISSUE THREAD

**Issue by ChristianSirolli** [minetest/minetest_game#2138]
I don't know what the scope of the issue is, whether it is just with the Creative mod or with Sfinv too. The issue here is when there are multiple tabs, the world is not in Creative mode, and the user switches tabs in their inventory, the creative tabs appear. I noticed this with the 3d_armor mod, whenever I switch to the Armor tab, the Creative tabs appear and stay there. Also odd is that when I switch to another tab, leave the world and come back, I go into the inventory and am presented with the All tab. Is this a known issue? I am using the latest Minetest engine source code and the latest Minetest Game mods.

**Comment by Ezhh** [comment]
Regarding the switch to creative tab, even when adding mods (including 3d_armor) that create additional tabs, I can't recreate this issue. I have seen the creative tab flicker into visibility in the past, only to then be replaced by the correct tab, but from I remember that was with inventory plus, not sfinv, and it was a long time ago. 

For the second point: I would think which tab you are on not being saved between relogs is not a bug.

**Comment by rubenwardy** [comment]
Sounds like you have the creative privilege

**Comment by SmallJoker** [comment]
`/revoke singleplayer creative` and switch the inventory tabs or rejoin. This is probably caused by `/grantme all` after you joined the world for the first time.
Please reopen if the issue still persists afterwards.
