### ISSUE TITLE
A chance to make sediments and soils logical

### ISSUE THREAD

**Issue by DokimiCU** [minetest/minetest_game#2143]
I see we've got permafrost coming so... it made me realize we are very close to being able to do realistic soils with only two more nodes.

To explain, a crash course in soil science!

Soil = organic matter + inorganic particles.

Inorganic particles are classed by size:
Gravel>sand>silt>clay.

With the addition of permafrost we have the frozen version of organic matter (i.e. peat). This is a little like adding ice but not water. Hence if we are going to have permafrost, then logically we ought to have peat.

As for the inorganic... We have gravel, sand, and clay. All that leaves is silt.

Dirt would then become a loamy soil. Loam is the combo of sand, clay, and silt. True living soil contains organic matter. Therefore "Dirt" would be Sand + Clay + Silt + Peat (maybe crafting? maybe not?).

Seeing as sand can be farmed, then silt and clay should also be enabled for farming (peat is probably unfarmable, swamps have to be drained normally).

Peat would be in swamps. It should drop iron ore like how gravel drops flint (look up bog iron). It should be able to be used as a fuel (this is its historical use).

Silt would be in estuaries, lake beds, river bottoms. (it is the most easily eroded sediment type, so ends up there).

It seems fairly simple. Add Peat, and Silt and we have everything we need for realistic soils and sediments.

**Comment by paramat** [comment]
Permafrost means frozen ground, it's not necessarily frozen peat, it's just frozen dirt.
But we could perhaps add peat for other reasons, and silt may be good instead of sand for riverbeds and seabed.
I disagree with how sand and desert sand was made farmable, seems a mistake but we now have to support it.

**Comment by DokimiCU** [comment]
Permafrost is indeed frozen ground, which means dirt... and sand... and clay... and silt... and gravel... and rock... and peat.

Given the extremely slow decomposition rates due to the cold, a huge amount of permafrost is peat (or at least extremely carbon rich soil). Hence why climate scientists are freaking out over permafrost melting and releasing all that carbon.

So for in-game simplification: Permafrost is either frozen dirt, or frozen peat.

Regarding farming: Yes, farming sand (or any other organic matter free sediment) is indeed weird. So... yes... one of those situations!

Another thought. If we are looking to expand the number of rock types, we have a chance to make sedimentary rocks logical too:

sediment ->consolidated sedimentary rock

We have already have sand ->sandstone.

Following the same pattern:

clay -> claystone
silt -> siltstone
gravel -> breccia
(also peat -> coal  ...probably not one to make craftable though)

**Comment by paramat** [comment]
Ok, thanks for explaining that a lot of permafrost is peat, i didn't know :)

**Comment by DokimiCU** [comment]
(...technically it probably isn't peat... but close enough! Lot's of carbon anyway,... and 10000 yr old frozen bison, that kind of thing!)

If peat does get added in would be best in a "peatland" biome, and as a layer above permafrost.

1. permafrost. 

I see permafrost has been given some surface layer nodes (moss, stones...). This is not technically correct. The surface layer is subject to freeze-thaw cycles... thus is not permanently frozen (i.e. not _perma_-frost). This surface is also the only thing plants can grow in (nothing grows in ice!). From some reading it looks like permafrost is often underneath peat. (possibly also forest... I'm no expert on permafrost! I do have a natural sciences background though... hence why I can get technical here!).

2. Peatlands. 

Location/form: These form anywhere that is waterlogged. e.g. hollows, oxbow lakes, etc. They especially form in cold places (this slows decomposition even more). So as a biome it would require lots of surface water. These watery hollows slowly fill up with peat, eventually forming peat domes. So it would also have small hills of peat. 

Plant species: mainly grasses (and grass-like things), shrubs, reeds (so papyrus?). Perhaps some trees at the edges. If we want to add more plant species then - sphagnum moss. This actually builds peatlands. (it does have cultural uses too, therefore crafting potential...but they are fairly niche. e.g. dressing wounds).

Aesthetics: lots of browns, and greyish greens. Dull and moody colors.

So... if we want more biomes in Minetest, I think that would be a good one. And with peat (and silt) we would be setting soils/sediments on a logical basis that will avoid any _bronze-sharper-than-steel_ issues further down the line.

**Comment by paramat** [comment]
Yes tundra has an 'active layer'. For tundra lowland i decided to make it cold season tundra, so no flowers and water pools, the surface is therefore frozen which allows simplifying it to be permafrost nodes also, even though strictly it is not permanently frozen. But i expect frozen 'active layer' is very similar to deeper permafrost.

**Comment by paramat** [comment]
Peatlands / wetlands could certainly be added as a biome stacked below an existing biome. I sometimes think about adding a marshy biome, would this be suitable as peatlands?

I'm quite interested in adding silt for lakebed/seabed, possibly below a certain y, so that shallow water still has beach sand.

Varying riverbeds with altitude is difficult as that would require several stacked biomes where there is currently one biome. However where we do have stacked biomes already this variation could be added.

Useful input, thanks.

**Comment by DokimiCU** [comment]
Classifications of wetlands gets confusing. Lot's of names, (bogs, fens, moors, mires, swamps, marshes, .... on it goes), varying classification systems, and they all blur together.

My educated guess is that we have three options:
- "marsh": lots of water, no trees (e.g. basically lake edge stuff with lots of reeds)
- "swamp": a wet forest (e.g. a little like mangroves? but freshwater)
- "peatland": shallow pools of water, massive layers of peat. No trees. (e.g. like I described above)

You could fudge a little and get away with peat in any of these three, but obviously peatlands is where it truly belongs  (apparently peatland is the most common too: "50 to 70% of global wetlands". [https://en.wikipedia.org/wiki/Peat](https://en.wikipedia.org/wiki/Peat))

Unless you want 3 types of wetlands, I suggest doing generic "Wetland". Perhaps you can figure out some way to roll them into one. Combining marsh and peatland is easy (marsh is the water, peat the land). Perhaps just leave "swamp" trees out of it?

**Comment by paramat** [comment]
We have rainforest swamp already as a biome.

**Comment by Gael-de-Sailly** [comment]
Having 3 different types of swamps could be good.
I suggest: rainforest swamps (already present) in warm places, marshes in temperate climate and peatlands on cold climate.
This is yet not completely right (i.e. peatlands are not exclusively found in cold climate) but I think it's a good balance between scientific exactitude and simplicity.
And by adding some plants, we can give them a different look, which could be very enjoyable.

This is in short what I wanted to do in my old 30-biomes mod but never finished my project.

**Comment by DokimiCU** [comment]
Turns out you can get peat swamp forests in the topics (I had thought peatlands were always tree-less!). So peat could be added to the existing swamp forest?

I looked up some mini-documentaries to help inspire people's designs. Photo's are good, but these help show how people live and move in these places. These show both modern and traditional issues.

Peat cutting in ireland. [https://www.youtube.com/watch?v=-maa5Bu1qxo](https://www.youtube.com/watch?v=-maa5Bu1qxo)

The marsh arabs. [https://www.youtube.com/watch?v=WhQhtOgXBvo](https://www.youtube.com/watch?v=WhQhtOgXBvo)

(It was too hard to find a decent one on tropical peat forest)

**Comment by paramat** [comment]
This is good input for consideration, but i am :-1: for the specific suggestion as i feel it is an unnecessary level of realism.
