### ISSUE TITLE
Move torch.lua credits and license to correct place. Also, chest suff

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2149]
Currently in torch.lua.

**Comment by Ezhh** [comment]
It's more complicated than this.

default has 4 torch textures... readme info has 7 listed... including two occurrences of default_torch_on_floor.png attributed to two different people.

**Comment by paramat** [comment]
```
Originating from G4JC's Almost MC Texture Pack (CC BY-SA 3.0):
  default_torch.png
  default_torch_on_ceiling.png
  default_torch_on_floor.png

VanessaE's animated torches (CC BY-SA 3.0):
  default_torch_animated.png
  default_torch_on_ceiling_animated.png
  default_torch_on_floor_animated.png
  default_torch_on_floor.png
```
I expect we need to remove G4JC's credits. The animated textures will be the most recent so 'torch_on_floor' is likely by VanessaE.

**Comment by paramat** [comment]
Possibly also new chest stuff.

**Comment by paramat** [comment]
Also, move chests out of nodes.lua into a new file in default.

**Comment by paramat** [comment]
PR #2171
