### ISSUE TITLE
Cobble Obsidian etc.

### ISSUE THREAD

**Issue by Der1248** [minetest/minetest_game#2153]
If I dig stone I get cobblestone (broken stone)
Obsidian will also broke if you dig it.
So I request cobble obsidian.
You dig Obsidian --> you get cobble obsidian--> you put them into furnace-->you get obsidan.
Like normal Stone.

I would also like mossy desert cobblestone and mossy cobble obsidian

**Comment by paramat** [comment]
:-1: Stone dropping cobble was a mistake i feel, trying to copy MC. I actually want stone to drop stone and be craftable to cobble, but this is not popular with other core devs and might cause disruption.

**Comment by SmallJoker** [comment]
It's boring when every single material behaves the same way. Adding cobble obsidian, cobble obsidian glass, cobble wood planks, cobble leaves or cobble apples does not add any variety.

**Comment by Ezhh** [comment]
I have to agree with the others here. :-1 for me.

**Comment by Der1248** [comment]
Ok, yes stone dropping cobble is a mistake and I also want stone to drop stone and be craftable to cobble.
But...
1. I realy think obsidian should be added to the group of stones, because they already have the same sounds, you dig them with the same tools and they also look like stone only in black/dark blue.
2. If you do not like cooble stone, why was cooble desert stone added?
3. It could confuse some players if you have differend ways to drop an item.
![screenshot_20180627_001426](https://user-images.githubusercontent.com/40540814/41942779-1eba4712-79a1-11e8-92e3-a0db79b53317.png)
4. I think everyone can see that something is missing here

**Comment by Ezhh** [comment]
Similarities does not mean the same. No one has said they don't like cobble, but obsidian is a bit of a special case due to how it forms in game. It's entitled to be different. Not all nodes will behave in the same ways.

**Comment by paramat** [comment]
1 Obsidian isn't stone.
2 The dropping of desert stone was another mistake, the other core devs overruled me :) but was done for consistency with stone->cobble.
4 Sand isn't cobble, and we have decided against sandstone cobble, we already have bricks and blocks. Obsidian doesn't make sense as a cobble building material.

**Comment by Extex101** [comment]
A better example:
![screenshot_2018-09-15-11-35-34-1](https://user-images.githubusercontent.com/33675971/45589509-8bf15e00-b8db-11e8-8bd5-0f9269d70ba5.png)

**Comment by benrob0329** [comment]
I would also agree, no obsidian cobble please. Its bad enough we treat obsidian like a stone.
