### ISSUE TITLE
Remove dependence of farming on grass

### ISSUE THREAD

**Issue by paanrama** [minetest/minetest_game#2161]
Now farming depends on grass because is the only form to obtain the seeds necessary for farming (wheat seed on grass and cotton seeds on jungle grass).

I propose change it, replacing the item_override of grass and jungle grass done by farming (in node.lua), by a register_decoration instruction in the farming API. It can be part of register_plant function, for the grow up plant.

What do you think about it? Can it be done without break compatibility with mods that extend farming?

**Comment by paramat** [comment]
Doesn't seem possible, grass and junglegrass have to be registered in default.
Many other aspects of farming depend on default mod anyway.
:-1:

**Comment by paanrama** [comment]
I only think about that we can add wheat and cotton as mapgen decoration (must be rare, maybe the equivalent to fill ratio 0.01 or less). Making the full grow plant part of mapgen we can obtain the seeds from the plant instead of grass (which is strange) and and some color to the landscape.
If is this is done after register the plant (in init) it don't affect the farming API.
Now we have an infinite surplus of wheat and cotton seeds in grass, I only need put and take the same grass in floor again and again.

**Comment by paramat** [comment]
> I only think about that we can add wheat and cotton as mapgen decoration

Ah i see, i misunderstood. It's a little weird because currently it simulates how crops were created by breeding certain wild plants, the final form of the crop shouldn't really appear wild.
Instead we could perhaps have 'wild wheat' and 'wild cotton' that have to be found and which drop the first seeds.

**Comment by paanrama** [comment]
I like the idea of a wild plant, is better than using the full grow plant
