### ISSUE TITLE
Leaf texture requirements [temporary]

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2164]
MTE has 3 ways of rendering leaf textures (as long as the leaf has the 'allfaces_optional' drawtype):
* Fancy:
Uses the texture specified in 'tiles'. This texture should have transparent pixels and be RGBA.
Faces of every leaf node are rendered even if they are part of a solid volume of leaves. This gives a dense appearence.

* Opaque:
Uses the texture specified in 'tiles' but makes it opaque by converting each transparent pixel into an opaque pixel that use the colour information of that transparent pixel.
Due to this the 'tiles' texture must be RGBA not 'indexed alpha' to allow each transparent pixel to have individual colour information.
The colours of the transparent pixels should be set for a good appearence in 'opaque' mode instead of all being black.
In Gimp i do this by painting the pixels the desired colours then erasing them. Then when saving the texture using the 'save colour information from transparent pixels' option.

* Simple:
Uses the texture specified in 'special_tiles' if it exists, if not, the 'tiles' texture. The 'special_tiles' texture should also have transparent pixels but can be 'indexed alpha'.
The newest mode which is a middle ground in appearence and rendering load.
The nodes are rendered using the 'glasslike' drawtype, only showing the surface nodes for any solid volume of leaves, not the internal faces.
Due to this the appearence can, depending on the 'tiles' texture used, seem lacking in density. So the 'special_tiles' texture option is there to provide an alternative texture with transparent pixels but a denser appearence.
This alternative 'special tile' is not essential as the standard texture may already have a thick appearence. Some MTG leaves have 'special tiles' named '.. simple', but some do not as the 'tiles' texture is already dense in appearence.

**Comment by Ezhh** [comment]
Is this currently an issue with any MTG textures? If not, this is good to document somewhere, but it should not be preserved in an issue.

Given we've also talked about how schematic tables are preserved, it seems we need to think more about MTG documentation that is available for contributors.

**Comment by TumeniNodes** [comment]
Maybe this can be worked into rubenwardy's modding book, somewhere in the textures section.

**Comment by paramat** [comment]
No issue with MTG leaf textures, i just wanted to store it somewhere for now, i was also thinking of adding it to documents somewhere in the engine (it's not MTG-specific).
Temporary then.

**Comment by paramat** [comment]
In discussion we propose moving this into engine 'texture packs' docs. When doing this the advice about correct colour profile to avoid error mesages could be added too (needs to be 'default RGB workspace').

**Comment by paramat** [comment]
PR https://github.com/minetest/minetest/pull/7637

**Comment by paramat** [comment]
Done in engine https://github.com/minetest/minetest/commit/03f89e8ffca84e2ff2f6cea8dcee49b067280cc4
