### ISSUE TITLE
Add car to game

### ISSUE THREAD

**Issue by that-other-guy123** [minetest/minetest_game#2165]
I need car can u plz add

**Comment by SmallJoker** [comment]
Install the mods yourself, here are some examples:
[mesecar](https://forum.minetest.net/viewtopic.php?t=7967)
[cars](https://forum.minetest.net/viewtopic.php?t=13988)
[cars](https://forum.minetest.net/viewtopic.php?t=7459) (older version)
[car](https://forum.minetest.net/viewtopic.php?t=7381)

Re-opening if anyone else thinks we need more content in MTG.

**Comment by that-other-guy123** [comment]
@SmallJoker thx

**Comment by that-other-guy123** [comment]
Wy not add in back @SmallJoker
