### ISSUE TITLE
Add small boulders/cobbles on surface

### ISSUE THREAD

**Issue by random-geek** [minetest/minetest_game#2174]
This is something which MTG seems to be lacking, and if done properly could balance the otherwise soil-dominated terrain. I don't think it is too specialized, as boulders and other rocky outcrops are quite common in the real world. There would obviously be different types for different biomes as well, i.e. desert stone and cobble for deserts, et cetera. Here's a concept screenshot:

![unknown](https://user-images.githubusercontent.com/35757396/42588756-90a57d9e-84f3-11e8-93a9-675d91219fbe.png)

**Comment by paramat** [comment]
I've had the same idea for some biomes, like desert or tundra, i might try it sometime.

**Comment by random-geek** [comment]
Yes, I think they would work for most biomes. Adding another node seems a bit excessive though.

**Comment by TumeniNodes** [comment]
I have to stay true to my name

But, either way, I like the idea. Farlands uses these and I find it does break up the landscape nicely.

**Comment by TumeniNodes** [comment]
@random-geek are you intending to do this?
If not I've been working on it a little...
let me know

**Comment by random-geek** [comment]
@TumeniNodes Not really. If you're working on it, that's fine.

**Comment by paramat** [comment]
Closing due to #2710
