### ISSUE TITLE
Apple tree logs are too long

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2182]
The trunks of the apple trees are either 3 or 4 nodes long, the logs can be 5 nodes long.
I suggest making it a 4 node long schematic with one or both ends having probability (don't mind which).
@Ezhh

**Comment by Ezhh** [comment]
I had considered this at the time I worked on them, but I don't really see it as a problem, given that the 5th node could easily be one of the top parts that are usually at an angle.

**Comment by paramat** [comment]
Ok but the branch would then still be at an angle to the log. We could make the log have one end node offset to be one of the branches:

![screenshot_20180723_091546](https://user-images.githubusercontent.com/3686677/43065219-0dbb3e54-8e59-11e8-975b-a9f88cfcb478.png)

**Comment by Ezhh** [comment]
That wouldn't look good. 

I really don't think this needs to be changed; the five node logs are extremely rare and there is actually no reason a tree couldn't. The way I thought of it is take your screenshot and turn it 90 degrees, then the branch drops. The tree does have the height even if it's not all straight when upright.

**Comment by paramat** [comment]
Apple trees are never that high though ;) It does look weird, i was in a clearing with two 5 node long apple logs, surrounded by apple trees with either 3 or 4 trunk nodes in a straight line. The logs looked ridiculously long and out of place. Anyway i won't assign you, i'll fix it.

**Comment by Ezhh** [comment]
They have to stay straight no matter what.

I don't think this is needed, but I'm fine with you changing it. Will check the PR later.
