### ISSUE TITLE
Minetest for android screen is not usable

### ISSUE THREAD

**Issue by DavidRotert** [minetest/minetest_game#2190]
Device: Samsung Galaxy A5 2017
OS: Android 8
Minetest Version: 0.4.17

If I start Minetest on my android phone, it shows a start screen like you can see in the picture attached to this issue. I already tried to reinstall Minetest from Google play, but the bug is still there. I noticed that the controls do not react if I touch them directly but if I touch 1 cm under the control (the red point in the screenshot marks where I touched to start the game). It is also not possible to play in a world.

![screenshot](https://user-images.githubusercontent.com/27674913/43467712-a19b910c-94e2-11e8-97e6-e10be3046e44.jpg)

**Comment by SmallJoker** [comment]
Could you please confirm that this issue persists in version 0.5.0/5.0? APK can be found here: https://forum.minetest.net/viewtopic.php?p=316739#p316739
