### ISSUE TITLE
New dirt/grass textures

### ISSUE THREAD

**Issue by random-geek** [minetest/minetest_game#2193]
The default dirt with grass textures currently seem unnecessarily bold and saturated, and thus end up overpowering the surrounding trees and plantlife. I fine-tuned the values a bit, and below are screenshots of my proposed modifications. In my opinion, these textures look significantly better and improve the general aesthetic.
I also changed the dirt texture to have less of a visible pattern, but I think it might be _too_ clean.

![unknown 2](https://user-images.githubusercontent.com/35757396/43997144-f690f9dc-9d88-11e8-8123-717abc0e6c85.png)
![unknown](https://user-images.githubusercontent.com/35757396/43997145-f6adbd60-9d88-11e8-8543-ace9979bd673.png)
![default_dirt](https://user-images.githubusercontent.com/35757396/43997155-1b380f6e-9d89-11e8-931d-589ce6c25750.png)
![default_grass](https://user-images.githubusercontent.com/35757396/43997156-1b58d302-9d89-11e8-9e51-8da7b9666aa9.png)
![default_grass_side](https://user-images.githubusercontent.com/35757396/43997157-1b74fc94-9d89-11e8-8190-b1f7cd7ca579.png)

**Comment by random-geek** [comment]
![compare3](https://user-images.githubusercontent.com/35757396/43997324-9a1a10c2-9d8c-11e8-98b1-a3a8f912362b.png)
It might be difficult to tell, but the right half of the image is with the new textures.

**Comment by ExeterDad** [comment]
I think your dirt is much improved over the original.

**Comment by Megaf** [comment]
:+1:

**Comment by paanrama** [comment]
I am not sure of the grass, but your dirt is much better.

**Comment by tenplus1** [comment]
I prefer the original grass textures.

**Comment by Ezhh** [comment]
I'm not too keen on the colour change. I disagree about the contrast issue; In your own screenshot there are two kinds of leaves and the change is making it too similar to the second type.

**Comment by C1ffisme** [comment]
I like the brighter grass, although I do think some of the leaves textures should be a bit brighter just for consistency.

**Comment by paramat** [comment]
> The default dirt with grass textures currently seem unnecessarily bold and saturated,

By 'bold' do you mean contrast? I assume saturation means colour 'saturation'.
What are the details of the changes you made?
I assume this is not the effect of 'tone mapping'.

I see no obvious problem with the grass so am hesitant to change it.

**Comment by paramat** [comment]
For dirt, it looks very similar close up (which is good), and i can see from your screenshot that over large areas a repeating 'dark blob' is no longer visible, which is potentially good.

**Comment by random-geek** [comment]
Thanks for the feedback. Below is a slight variation, which may or may not be good; I just added some pebbles. It makes it look a little more like actual dirt.

![unknown 3](https://user-images.githubusercontent.com/35757396/44012364-6f244382-9e73-11e8-8b98-d3d712c6a7d2.png)

**Comment by Ezhh** [comment]
I'd support the dirt change (undecided about the pebbles either way) but not the grass change at the moment.

**Comment by paramat** [comment]
I'm also undecided about the pebbles, but they are done well and look ok to me.

**Comment by SmallJoker** [comment]
The proposed dirt texture looks less repetitive on a large scale, which is already quite good. I don't mind the grass texture since grass itself has a rather large color range in nature (or at least it's what the eye can distinguish).

**Comment by paramat** [comment]
@SmallJoker pebbles or no pebbles?

**Comment by SmallJoker** [comment]
@paramat It's natural to have some pebbles in the dirt so that's fine to keep them.

**Comment by paramat** [comment]
@random-geek please do open a PR for the dirt with pebbles texture.

**Comment by random-geek** [comment]
I had to do some additional tweaking, as the previous texture was not indexed. Below is the final indexed texture and a screenshot.
![capture21](https://user-images.githubusercontent.com/35757396/44130459-956cf986-a002-11e8-8dc4-97bc27f03ec8.PNG)
![default_dirt](https://user-images.githubusercontent.com/35757396/44130467-a1527a78-a002-11e8-91a6-c537a3c0b1ae.png)

**Comment by TMcSquared** [comment]
It looks a bit overwhelmingly brown IMO, like wet dark-brown paint. Maybe go a tad lighter or something.

**Comment by paramat** [comment]
I would not agree to lighter, it needs contrast with the coniferous litter and i personally prefer darker dirt. Best keep lightness unchanged.
I'm fine with those 3 pale pixels being made less visible.

**Comment by random-geek** [comment]
How about this?
![capture22](https://user-images.githubusercontent.com/35757396/44163116-4d1b7e80-a077-11e8-81f2-9dc6fbfaf50c.PNG)
![default_dirt](https://user-images.githubusercontent.com/35757396/44163130-5b699a80-a077-11e8-81b7-2d62957305b2.png)

**Comment by paramat** [comment]
Looks good to me.

**Comment by random-geek** [comment]
Unfortunately, I can not currently open a PR for this, as I already have forked minetest_game for my huckleberry PR and I forgot to apply the changes to a branch. :-(
