### ISSUE TITLE
Replace hotbar textures

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2195]
Just realised how bad the hotbar slot frames texture looks (doubled in size with no interpolation):

![badhotbar](https://user-images.githubusercontent.com/3686677/44304496-12eefd00-a355-11e8-9602-2ea9c1938126.png)

The borders around each slot vary in width from slot to slot and from edge to edge. The texture itself is not irregular (doubled in size with no interpolation):

![gui_hotbarx2](https://user-images.githubusercontent.com/3686677/44304548-834a4e00-a356-11e8-915b-cf2ecf61f892.png)

~~It seems an unavoidable alignment mismatch between the texture and the shaded squares.
If we remove this texture it can look like this, which is cleaner and less visually intrusive when a slot is empty:~~

Now see the selection frame (doubled in size with no interpolation):

![gui_hotbar_selectedx2](https://user-images.githubusercontent.com/3686677/44304553-de7c4080-a356-11e8-8b5e-a7e29541b761.png)

It's a rather fancy, rounded, smoothed, blurry, high-res stone effect by BlockMen which obviously goes with the old header image by BlockMen last used in 0.4.13 and replaced 3 years ago (actual size):

![header](https://user-images.githubusercontent.com/3686677/44304561-066ba400-a357-11e8-901a-0d5c4ca4a4d4.png)

Which was embarassingly similar to the MC logo:

![ripoff](https://user-images.githubusercontent.com/3686677/44304646-e5588280-a359-11e8-8889-01a645963f7f.png)

MTG has a low-res header now. I feel that this selection frame needs changing to be more consistent with MTG's now cleaner, crisper and low-res general appearence.
Now see the hotbar from MC:

![qa7](https://user-images.githubusercontent.com/3686677/44304667-63b52480-a35a-11e8-8013-a6b697ba3a71.jpg)

The stone frame selector is again an almost identical copy, but at least MC's is clean and crisp instead of blurry like ours.

**Comment by Fixer-007** [comment]
>Just realised how bad the hotbar slot frames texture looks (doubled in size with no interpolation):

Thank you for bringing this up, bothered my OCD for a long time as well, it is not just textures, but weirdly displaced hearts and other indicators, minecraft one is so much better and ａｅｓｔｈｅｔｉｃａｌｌｙ pleasing.

**Comment by paramat** [comment]
> Modders will still hold ability to add their own texture of it via texture pack?

I hope so, try it. If not there's a workaround.
Your hotbar texture still has uneven edges, it's an unavoidable alignment issue, so i think best to just not use a texture. There's no need for surrounding boxes, that was BlockMen trying to duplicate MC.

If a stone frame selector is still wanted i can make a new one, but it might be good to do something different and possibly abstract like the rest of our GUI.

**Comment by paramat** [comment]
> Modders will still hold ability to add their own texture of it via texture pack?

Yes but this causes the engine to display an error message, see https://github.com/minetest/minetest/issues/7661

**Comment by benrob0329** [comment]
Not showing what slot the user is holding will make it confusing under various situations, such as if the player has multiple stack of something and wants to know which is being wielded at a glance. Or really, wanting to know what you're wielding spatially compared to the other things in your hotbar at a glance.

**Comment by paramat** [comment]
To allow texture packs to still provide the 8-slot texture we can use a workaround by providing a dummy transparent 1x1 texture in MTG. Seems better than removing the engine warning https://github.com/minetest/minetest/issues/7661

**Comment by paramat** [comment]
The hotbar selected frame has light coming from top right, inventory nodes have light coming from top left.

![screenshot_20180901_093020](https://user-images.githubusercontent.com/3686677/44944164-e5c93280-adc9-11e8-9e35-9794f3a300f4.png)

I'll make a better texture.

**Comment by paramat** [comment]
![gui_hotbar_selectedx4](https://user-images.githubusercontent.com/3686677/44944445-99ccbc80-adce-11e8-8222-f3f7fbacff8f.png)

I sampled the lightest and darkest greys from the current selector and added a shade halfway between.

**Comment by paramat** [comment]
Change of approach, for visibility against light and dark environments it is necessary to use the 8-slot texture, so i am keeping it but improving it.
