### ISSUE TITLE
Fence Rails Look Bad Next To A Wood Block

### ISSUE THREAD

**Issue by benrob0329** [minetest/minetest_game#2201]
![screenshot_20180822_183631](https://user-images.githubusercontent.com/19180682/44498566-34016780-a64d-11e8-88a7-37bb622d1469.png)

**Comment by paramat** [comment]
Indeed they shouldn't connect to wood nodes, only fences.

**Comment by Fixer-007** [comment]
This is debatable topic

**Comment by paramat** [comment]
Yes, but any fence rail next to wood, tree or wall will then have that weird connection. It would then be so that if you want to connect a fence to wood, tree or wall you would use a fence post, which is reasonable.

**Comment by paramat** [comment]
Let's see what other core devs think, but it seems to me that fence rail middle sections should only connect to fence posts.

**Comment by Ezhh** [comment]
From what I recall of the PR, this is intentional behaviour?

**Comment by paramat** [comment]
It was intentional that fence rail ends connect to wood, tree and wall, but i don't think this kind of 'no post' 3/4-way sideways connection was intended

**Comment by Ezhh** [comment]
Maybe not, but it would be sad to lose the ability to connect to wood completely. It's worth noting this is a weird place to build a fence. There is nothing to fence to fence off.

**Comment by benrob0329** [comment]
The fence wraps around behind and to the right of the shot, can't rails be disallowed from connecting on the flat faces?

**Comment by paramat** [comment]
I see this problem as worse than losing the connection possibilites. For example each time a fence rail passes a tree that weird connection would occur. Having a rail junction without a post makes no sense IRL and would be structurally weak. It also looks bad.
If a connection to wood, tree or wall is wanted then a fence post can be used at that position instead.

it's not possible to stop a connection in certain directions depending on what directions are connected to fence posts.

**Comment by TumeniNodes** [comment]
> Indeed they shouldn't connect to wood, tree or wall nodes, only fences.

In the initial PR, I intended them to be used only in between the existing fences. All the extra connecting was added later. (just sayin)

**Comment by paramat** [comment]
Interesting, i forget why the connections were added. Anyway, i agree with your original intention.

**Comment by TumeniNodes** [comment]
> Interesting, i forget why the connections were added

Because you said, they should behave like fences,
and I said "Nooooooooooooooo",
and then you said "Yes",
so I said "ok" ; )

**Comment by paramat** [comment]
If there are no objections i'll make a PR in a while to only conect to fences.
