### ISSUE TITLE
Make fences connect to stone/all visible nodes

### ISSUE THREAD

**Issue by ChimneySwift** [minetest/minetest_game#2205]
Currently fences will only connect to fence, wood, tree and wall groups. This is annoying when building with fences that should connect to nodes like cobblestone.

Making fences connect to stone nodes could cause issues:

> Paramat: consider a fence running parallel to a cobble wall, there will be connections to every node, which looks weird.

However this already happens with fences running parallel to wood nodes.

A possible solution to this problem might be to have a manual tool to adjust which sides are connected, along with the automatic connecting process when initially placing the fence.

**Comment by sofar** [comment]
> A possible solution to this problem might be to have a manual tool to adjust which sides are connected, along with the automatic connecting process when initially placing the fence.

This would entirely undo the idea of, and benefit of, connected nodes.

So, it's already possible, but, I hate the idea.

**Comment by paramat** [comment]
I disapprove of more connections, i don't even like connection to walls and trees :-1:

**Comment by Ezhh** [comment]
:-1: for me as well.

Closing based on dev disapprovals.
