### ISSUE TITLE
Add playeranim to default

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest_game#2210]
As we all may have noticed, the player looks quite stiff and robotic.
![2018-09-09 13 01 25](https://user-images.githubusercontent.com/33675971/45268403-92418f00-b430-11e8-988d-c45bb6a96477.png)

So I would like it if you could add ***PLAYERANIM***
![screenshot](https://user-images.githubusercontent.com/33675971/45268318-1c88f380-b42f-11e8-9881-7c25c3174f3a.png)

playeranim is a mod made by Rui [Link](https://forum.minetest.net/viewtopic.php?t=12189)
It adds animations to the players arm and head

Just add the playeranim [Init.lua](https://github.com/minetest/minetest_game/files/2364792/file.txt) code to the player code in default.

But we get a glitch where his arms are up in the air 

To fix just replace the player model with the one in playeranim

**Comment by benrob0329** [comment]
Playeranim mod makes all animations very blocky, and personally I think it looks much worse. The mod is a nice concept but we need things like head animations done by the engine (and smoothed).

**Comment by Extex101** [comment]
It's better than it's current state
Just a temporary fix for 0.5.0 it can be perfected in later versions.

**Comment by Ezhh** [comment]
It's extremely unresponsive from all my testing and not everyone likes it. :-1:

**Comment by Extex101** [comment]
I still think it's good for a temporary fix until we come up with a better one.

**Comment by Extex101** [comment]
I still think it's good for a temporary fix until we come up with a better one.

**Comment by Extex101** [comment]
Oops

**Comment by DS-Minetest** [comment]
>>I still think it's good for a temporary fix until we come up with a better one.

>Fix implies a bug.

Nah, perhaps @Extex101 likes this so much that it's for him like a drug. Drug users always search for their next fix, aren't they? Isn't this more likely than that he's claiming that there's a bug?
https://en.wiktionary.org/wiki/fix
[Do not take anything seriously, correct?](http://c55.me/blog/?p=1491)

Currently the clients get the animation with the model sent as media, the client has the animation and can play it smoothly. The server tells the client every server step, what animationframes they should play smoothly.
With playeranim the bones are not animated in the model file (at least this animation is not used) but the bones are animated in lua on every lua global step (default all ~0.1 seconds) on the server, which sends the new bone positions and rotations to the clients so they can render this position as one frame. -> :crying_cat_face: 
:-1:

**Comment by benrob0329** [comment]
It would make much more sense to add the extra animations for things like swimming, while allowing games to register a head bone that would be animated separately based on the pitch and yaw of each player. @sofar had plans to do this some time ago.

**Comment by sofar** [comment]
This was discussed before. A proper solution would be for the engine to do this client-side. Potentially CSM can do this, efficiently, too.

**Comment by paramat** [comment]
:-1: As explained in the thread, this is serverside animation so is unusable.
