### ISSUE TITLE
Virtual camera

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest_game#2212]
We need (non-player) virtual cameras

This would allow for security cameras (possibly on a node)

And have it so the camera view can be displayed to the player

This could allow for an RPG themed cutscenes

e.g. {
`minetest.register_camera ("security:camera", {`
`location = {x=5,y=0,z=800},`
`})`
}

And some way to move the camera, rotate yaw. ***ect.***
### Could this addition be added to `0.5.0`

**Comment by benrob0329** [comment]
Duplicate of #7575

**Comment by benrob0329** [comment]
So, you also make a fake entity to represent and track the player's supposed position and health. This is well beyond anything that should probably be in MTG but I can see a very useful mod being made.

**Comment by paramat** [comment]
Engine issue.
