### ISSUE TITLE
Restore ability to rotate slab/stairs textures

### ISSUE THREAD

**Issue by Ezhh** [minetest/minetest_game#2216]
I would like to invite you to look at this nicely decorative wooden floor:
![tile_before](https://user-images.githubusercontent.com/7035183/45823005-a0bb6080-bce4-11e8-85df-957be9d05c37.png)

It took less than five minutes to make, but I think we can agree that it is somewhat interesting, especially when compared to the alternative:

![tile_after](https://user-images.githubusercontent.com/7035183/45823052-b6c92100-bce4-11e8-9ab9-f80b70083c53.png)

#1935 was merged back in November 2017, but I assume has not really been playtested much because it's not in stable. The idea - prevent upsidedown stairs looking so weird - is great. The problem is that it changes the nicely decorative flooring above into the rather more plain and boring non-decorative version when you update an existing world to current dev version of MTG.

Personally I find this kind of breakage of existing builds, and removal of creative potential, completely unacceptable.

 I don't believe enough consideration was given before merging and I would like this reverted, or some adjustment made so that this change in behaviour is optional, not default.

**Comment by Fixer-007** [comment]
You can use a a screwdriver to rotate it,

**Comment by shivajiva101** [comment]
#1935 reduces the artistic content value dramatically, you can't expect servers to 'upgrade' to something that instantly negates the effort players made to create something unique.

**Comment by Fixer-007** [comment]
Show some examples?

**Comment by Ezhh** [comment]
Look more closely - you can rotate the node, but the texture orientation does not change.

**Comment by Fixer-007** [comment]
Texture rotates on full block, but not on slab/stair, otherwise it will look bad on various architecture forms, like columns, etc. But is not you can set some nodes to have rotatable textures?

**Comment by benrob0329** [comment]
I have mixed feelings about this. Yes, artistic freedom is a very valid argument, but having misaligned textures is the biggest pain for me whenever I try to build something. Especially with slabs.

**Comment by Ezhh** [comment]
@Fixer-007 In stable you can rotate them all. This has been actively used by players to create variation in their builds. 

I'd also add the stairs don't even look good. It makes very little sense to me that some steps would have wood lengthways and others widthways. 

The whole point is you should not break one thing that has already been depended on to fix another.

**Comment by tenplus1** [comment]
Stairs and slabs need to be rotatable and adhere to the surface pointed at when placing e.g. place slab flat when on floor or upright when against a wall...  Make use of the sneak key when placing to copy the rotation of the slab/stair you are pointing at.

**Comment by paramat** [comment]
Oops, #1935 was a mistake then, we need to reconsider.

**Comment by SmallJoker** [comment]
The largest issue is basically that you cannot specify whether the world alignment should be used (or not) on a specific node. Whereas the PR arised this issue, it's a major improvement for pillars and architectural decoration based on stairs which all had different orientations. I don't mind reverting the PR but please consider both sides before doing it.

**Comment by Ezhh** [comment]
I fully recognise the original issue is a genuine one, and it's one that's annoyed me personally in the past as well, but a fix that does this is, in my opinion, a pretty poor fix. 

I feel there are some nodes (stone/cobbles for example) where using this can only be a positive, but for more structured materials like planks and bricks which have a definite direction that players might want to change, it's not so good. 

Can it be made optional? Would we want to go that way, or would it make more headaches through not all nodes then being consistent in behaviour?

**Comment by paramat** [comment]
I do see both sides of this, but existing worlds did not specify what should or should not have world aligned textures, so we shouldn't have set all nodes to be world-aligned. Ideally it needs to be decided for each node placed in a world, which will be a lot of rebuilding work, but is the correct way to apply the feature.
Not sure how to make it optional, first thought is each stair node has 2 versions, the new nodes being the world-aligned ones. Inventory will explode somewhat.

**Comment by Ezhh** [comment]
Yea, I don't think the original issue justifies having two versions of nodes. If doing that, you may as well have special upsidedown_stairs nodes and have done.

I think it's much better to assess which specific nodes it's worth applying this to, but there will be disagreements there anyway, since the ones where the original issue is most visible will also be the ones that most need to be preserved.

**Comment by Ezhh** [comment]
More issues:
![stairssss](https://user-images.githubusercontent.com/7035183/45839230-ac6e4d80-bd0b-11e8-8e0d-c918bce21a3e.png)

1 - Planks go one way across top of stairs, another across the back. I find this visually icky, especially since staircases going round corners won't be consistent.
2 - Brick texture has four rows of bricks. It makes sense to split a stair between these horizontal rows, two on each level. Here we're splitting in the middle of individual bricks instead. It just looks bad.
3 - The join between the bricks on the lower step doesn't match up (inversion of which side is light/dark).

**Comment by Ezhh** [comment]
@paramat 1, 2, and 3 are not issues at all in current stable. They only exist as issues due to #1935.

**Comment by paramat** [comment]
Ok i see. That makes it more tricky @numberZero is that an engine bug?

I was too quick to support a revert. The current code can possibly be altered into the solution.

A random initial suggestion:

It seems that many nodes are fine being world-aligned only (ice etc.) so we could first decide those.
In the stair/slab registration function add a field that decides between world-aligned, non-world aligned or both, then register 1 or 2 nodes.
I think adding extra nodes to provide the choice is acceptable, it won't double the number because many will be chosen to only be world-aligned.
All existing MTG stair/slab nodes revert to non-world-aligned, then builders can use the new nodes where they want world-aligned nodes.

**Comment by Ezhh** [comment]
It's not en engine bug; it's the expected effect of world-aligned textures when the textures themselves have not been created with that in mind and/or are not suitable for it.

Doubling stairs/slabs nodes for MTG feels crazy to me.

**Comment by numberZero** [comment]
No that’s not a bug but the only way it could work. Take a look at a screenshot:
![](https://user-images.githubusercontent.com/1497498/32404256-d8600cf0-c14c-11e7-8fc0-43127a2380c0.png)
Here you can see that there is no single orientation for horizontal faces consistent with all the vertical ones. The problem is that that’s unsolvable, just like the [hedgehog theorem](https://en.wikipedia.org/wiki/Hairy_ball_theorem): there *may not* be any single correct orientation for an arbitrary object (that was the reason I didn’t add the feature to mesh nodes).

**Comment by paramat** [comment]
Sorry, i see. Yes, it's unsolvable.

**Comment by Ezhh** [comment]
More:
![stairendswhere](https://user-images.githubusercontent.com/7035183/45843980-f6a9fb80-bd18-11e8-9a67-b5a96ac6498b.png)
Some kind of weird physical strangeness where a brick is split on the top but not the bottom.

This should not have been merged.

**Comment by numberZero** [comment]
My suggestion is to disable the feature for all nodes that have well-defined orientation (like wood), but keep for those that don’t (like stone). That would be most logical.

On the other hand, the original problem was with stone bricks. Basically, there were 2 reasons for misalignment:

1. Highlights are encoded in the texture, and thus (physically incorrectly) rotated with the node,
2. Splits are encoded as well, and thus (physically correctly) rotated with the node.

The latter may only be solved correctly by adding a separate node that is split differently. The former should be solved in some other way, but that’s certainly non-trivial.

**Comment by paramat** [comment]
So an extra field in registration to decide WA per-node?
Let's suggest which node gets which.

**Comment by Ezhh** [comment]
I'd suggest judging purely by whether something can be rotated or not in full-node form.

**Comment by paramat** [comment]
Possibly good. Then auto-decide on node's paramtype2?

**Comment by Ezhh** [comment]
I think so. Probably worth reviewing that everything you'd expect the screwdriver to work on, it does work on, as well.

**Comment by paramat** [comment]
Looked through all stair nodes and checked facedir for each parent node, seems fine.

**Comment by Ezhh** [comment]
Yes, from a quick check, also seems fine to me.

**Comment by paramat** [comment]
I'll give this a little longer for input, then make a PR.

**Comment by numberZero** [comment]
I just remembered that there is a client-only option to disable world-aligned textures, is that of any help?

**Comment by TumeniNodes** [comment]
Is it possible, to add a new tool to the stairs mod, which is used to place stairs with rotated textures, and then when placing stairs without the tool, maintains the world aligned textures?

It's just an idea, I have not even though as to whether it is actually doable, or thought of any way to code it.

**Comment by benrob0329** [comment]
Using more rotation tools sounds like a hack for a broken placement system imho.

**Comment by paramat** [comment]
A tool to quickly convert a non-world-aligned wood/brick stair to the (possibly) added world-aligned wood.brick stair is a good idea for the rebuilding that will be needed. Nothing to do with an alledged 'broken placement system'.

**Comment by Ezhh** [comment]
> ...for the rebuilding that will be needed

What rebuilding?

I'd actually favour a tool to convert the nodes over having them all need to be separately crafted, though no idea what that tool should be called, but the default state of existing nodes needs to remain non-aligned.

**Comment by paramat** [comment]
Well, it's optional rebuilding. If we add additional world-aligned wood/brick stair nodes, then many builders will want to use these because they look better, so they will want to replace their non-world-aligned nodes.

> the default state of existing nodes needs to remain non-aligned.

But surely the stair nodes of non-rotatable nodes (stone, snow, ice) should be world-aligned? The textures should not rotate because the parent nodes are not rotatable.
You supported this here https://github.com/minetest/minetest_game/issues/2216#issuecomment-423319604 and both versions of my PR were coded that way.

**Comment by Ezhh** [comment]
> But surely the stair nodes of non-rotatable nodes (stone, snow, ice) should be world-aligned?

I'm just talking about the ones that are rotatable. Sorry for any confusion. I'm simply not considering non-rotatable nodes when thinking about the default state they are in, because they have only one default state.

I don't think there will be as many nodes getting converted as you seem to think. The alignment issues are only major and really bad to look at when you start placing upside nodes, which is (sadly) not something your average player seems to even think about.

**Comment by TumeniNodes** [comment]
as of now, screwdriver is used to rotate nodes, and uses left/right clicks

not sure how adding the ability to choose between the two types of nodes would work..., it may over complicate screwdriver.

A new tool may really be required, but it would be created within the stairs mod, itself.
This silly little issue, is actually a fairly complex matter

**Comment by paramat** [comment]
Ezhh ok great.

Fixer in order to do what? Duplicated nodes is necessary anyway.

There is the issue of crafting, it may better to only craft the nonWA and apply a tool to it to convert it.

**Comment by Fixer-007** [comment]
Leave all nodes as world-aligned but make screwdriver override it once you use it on block?

**Comment by Linuxdirk** [comment]
For anyone finding this and wonder how to have properly world aligned textures (a feature that is in the stairs mod but is not used for “critical” nodes). Here’s a quick-and-dirty snippet.

```Lua
for id,definition in pairs(minetest.registered_nodes) do
    if definition.groups.stair or definition.groups.slab then
        local tiles = definition.tiles
        tiles[1].align_style = 'world'
        minetest.override_item(id, { tiles = tiles })
    end
end
```

Make a mod from this and depend it on `stairs`.
