### ISSUE TITLE
Canyon biomes

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest_game#2218]
Minetest should add a canyon biome
With 3 different types
Sandstone, desert sandstone, desert stone, (Silver sandstone)

Canyon is a high biome of sandstone extending around 30 blocks high with a flat layer of sand on top
![screenshot_2018-09-20-19-51-01-1](https://user-images.githubusercontent.com/33675971/45858261-5ef4df00-bd11-11e8-840a-5d0c2805dbee.png)

Like so:
![screenshot_2018-09-20-19-57-57-02](https://user-images.githubusercontent.com/33675971/45858059-77182e80-bd10-11e8-9a9d-d7a0dfed2c8e.png)
![screenshot_2018-09-20-19-55-16-01](https://user-images.githubusercontent.com/33675971/45858069-80090000-bd10-11e8-8fc0-e2391a96d222.png)
![screenshot_2018-09-20-19-52-07-01](https://user-images.githubusercontent.com/33675971/45858075-85fee100-bd10-11e8-84cd-2628b488a3a9.png)
![screenshot_2018-09-20-20-15-35-1-1](https://user-images.githubusercontent.com/33675971/45858400-138f0080-bd12-11e8-9a76-67d51017af5e.png)

So raise the ground level up and add a ton of tall extruded caves and vwala although you'll be able to make it look nicer than my example's

And thanks for viewing!

**Comment by Ezhh** [comment]
A canyon would be a mapgen feature, not a biome.

Some mapgens are already capable of generating things that look like canyons.
