### ISSUE TITLE
Flat mapgen is not flat

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#2223]
If you generate a flat map without caves, dungeons, lakes, hills and decorations, in MTG, the map is *still* not perfectly flat.

As soon you teleport to the border of a snow biome, there is a difference in height because of a layer of Snow and Snow Block. I suppose this comes from `node_dust` in the biome definition.

Proposed bugfix: Don't generate the extra layer of snow when in `flat` mapgen so the map is truly flat again.

Tested in MTG 0.4.17.1.

Proof of height difference:

* Coords: (-220, 9, -218)
* Mapgen: flat
* Seed: 13046004985160237512

**Comment by paramat** [comment]
This is silly, flat doesn't mean perfect flatness, it means the mapgen surface level is flat, which it is. Naturally the biome 'dust' is added on top, in some biomes the dust is snowblocks, in others snow.
If you need to remove dust you can remove and redefine the biomes to have no dust.
