### ISSUE TITLE
Angle player arms forward, separate legs, for additional multipurpose sitting/driving/rowing animation

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2227]
The player looks bad sitting on the boat with arms straight down at the sides. The boat also moves around as if by magic.
I was thinking about possibly adding simple oars to the boat model. These would be stationary oars, but at least some kind of propulsion is then indicated and it will look better than a magic raft.
I then thought that these oars would look best if the player's arms were angled forward as if holding them and rowing.

This would also be good for driving vehicles and riding animals.
If they are not angled forward by too much then this would still be suitable for sitting, it would be like placing your hands on your knees, or gesturing during conversation. I'm thinking about angling the arms forward by between 45 and 60 degrees to the vertical.

Maybe also separate the legs a little? See how MC has a multipurpose sitting animation which also angles the legs down a little. It looks fine for sitting, driving, riding, rowing.

This would require someone with the modelling skills i lack.

**Comment by NathanSalapat** [comment]
This shouldn't be too much work to do. The model already exists, and has bones, it would just need some tweaking. Should this replace the current sitting pose, or be added as an extra pose?

**Comment by paramat** [comment]
That model is exactly what i had in mind. I suggest replacing the current sit animation with that.
Does that have the same 'breathing' animation as currently?

**Comment by NathanSalapat** [comment]
I think the breathing animation just effects the chest, and the arms as they are children objects, so yes, the animation would be the same for that. I can make a PR if you'd like.

**Comment by DS-Minetest** [comment]
Actually sitting with an angle of 90° is really uncomfortable, moving your arms in front of you doesn't make it better.
I suggest leaving the current sitting animation as it currently is and adding more sitting animations. Eg. one for sitting on the floor ([like this](https://www.shutterstock.com/de/video/clip-4419614-beautiful-little-girl-sitting-on-floor-living) (I'm referring to the sitting posture, not to the movement nor to the creepy smiling.)) or sitting in the boat (and moving hands). The boat thing should be added when it will also be used, not before.

**Comment by paramat** [comment]
The current sitting animation is not good for anything, as far as i know, it looks bad for any usage.
A multipurpose sitting animation is a good idea, otherwise we will end up with endless requests for specific extra animations. It's better to be restrained with this. First let's add what will be a useful multipurpose sitting/riding/driving/rowing animation.

Let's consider whether to angle the legs down a little or not, what are the arguments for this?
It seems in MC this was done to make the posture more suitable for riding animals and make sitting in chairs look better.
On the MTG boat the legs would be angled down into the raft a little, but i am thinking about a new boat model anyway that will hide this or have a seat.
It wouldn't be good for sitting on the floor, but that doesn't happen in MTG yet. The priorities seem to be: boat, and in mods: vehicles, animals, chairs.

**Comment by paramat** [comment]
Ok thanks we would have to not break mods that specifically use frames from the current sit animation. So this would have to be a new animation.
