### ISSUE TITLE
Player walking animation: No head turning, improve limb swing

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2230]
Since we're on the subject in #2220 and #2227 here's another issue that bothers me.

The walking anmation doesn't look quite right somehow, mostly it is the robotic side to side head motion that bothers me, i feel that may look better not happening.
When MC players walk they look cute, in MT it looks a little weird and awkward, maybe someting to do with limb angles? More swing angle might look cuter.

**Comment by paramat** [comment]
Cute probably means different things to different people, i mean likable, lovable. The MC type model is inherently cute due to it's proportions and 1-piece limbs. In a way, there's nothing 'natural' about the player model, it's essentially an abstract cartoonlike character and needs a suitable motion.

**Comment by Ezhh** [comment]
Natural within the context of what it is. The robotic movement you refer to is not "natural" for the model's default appearance (Sam) which is an obvious  imitate of a real person, not of a machine.

MC is a valid point of comparison, but if we change the animation it should stand on its own merit within MT. This means the animation should not look "awkward" or "robotic" and it should look reasonably natural for what it's intended to represent.

**Comment by DS-Minetest** [comment]
[What about adding knees and elbows](https://forum.minetest.net/viewtopic.php?f=5&t=5768)[?](https://github.com/minetest-australopithecus/minetest-australopithecus-player-model)
<details>

![2018-10-06-161435_1920x1080_scrot](https://user-images.githubusercontent.com/7613443/46572268-2ac12580-c983-11e8-901c-c15c356b9c17.png)
</details>

**Comment by JurajVajda** [comment]
Current animation is just moving the legs and arms in cycles without any other body/shoulder/head motion. While this was improvement when replacing the 2d player model it has still lot improvement to do in order to achieve at least basic realistic animation cycle: https://youtu.be/CzccZLmRvpc the head/body is moving slightly up and down while walking, also shoulders are moving back and forth when walking. This should not be hard at all to implement basic realistic animation.

**Comment by paramat** [comment]
Knees and elbows are offtopic and i very strongly disapprove of that.

**Comment by paramat** [comment]
Watching MC walking animation it seems to have no body up and down movement and no turning of shoulders, quite surprising. I think i notice that the swinging of the limbs is faster at mid-swing and slower near the end points, which might be why it looks better than MT. MT limb swing seems (not sure) to be a constant speed throughout, which might be causing the robotic appearence.

I feel we need to be very careful about 'more realism' as it may not necessarily look better, it can sometimes look creepy instead (the uncanny valley). Too much realism will certainly look worse. The player model is highly unrealistic, super-simple, abstract, cartoonlike so a suitable motion may also have these qualities. I find MC has a good motion even though it's very simple.

Essentially i find the head turning irritating and the limb swing not right.

**Comment by tenplus1** [comment]
Mc animation is cuter because the player model is more expressive due to head movement.
