### ISSUE TITLE
Unexpected fire behaviour

### ISSUE THREAD

**Issue by poikilos** [minetest/minetest_game#2231]
Minetest version: 5.0.0-dev (client, updated yesterday--init.lua from fire is also dated yesterday Oct  7)
![screenshot_20181008_144544](https://user-images.githubusercontent.com/7557867/46628060-6cc8a380-cb0a-11e8-8af2-f478f621a9d9.jpg)
This fire spread from the tree to the water, then last to the wheat sprout (this fire apparently started from lightning from minetest-mods/lightning). There was no algae there, but algae should not burn anyway (hopefully it is not considered flammable)--the lack of algae seems to be confirmed by the behavior of fire being that its fuel source is below it (as shown in 4th screenshot below). I put the fire out by hand, and it stopped spreading, and the fires seem localized around where the jungle trees were:
![screenshot_20181008_144928](https://user-images.githubusercontent.com/7557867/46628065-6f2afd80-cb0a-11e8-82e7-de1a8add5121.jpg)
I'm not sure why, unless it has something to do with checking above for fuel source instead of below it:
![screenshot_20181008_145133](https://user-images.githubusercontent.com/7557867/46628074-73efb180-cb0a-11e8-99fc-191dc35bc98e.jpg)
 or has something to do with the trees dropping something but they usually don't drop anything due to fire. Eventually the fires die. However after several minutes, the fire spread to a node above the replanted wheat (strange, since the fire that burned the sprout occupied the space where the sprout was--see first screenshot):
![screenshot_20181008_145322](https://user-images.githubusercontent.com/7557867/46628078-75b97500-cb0a-11e8-9d3e-f95c194251f7.jpg)
The seeds eventually burned up and the rest of the fire went out.

**Comment by poikilos** [comment]
After started inpecting the area, I discovered that the fire seemed to have a baffling level of potential--unless caused by a high number of lightning strikes in a small area, which I'm not sure is possible. The swamp on the left of the first screenshot is the source of the fire shown in the original post (screenshots in original post are from a cove under the mountain shown below):
![screenshot_20181008_150601](https://user-images.githubusercontent.com/7557867/46628633-283e0780-cb0c-11e8-98f5-248bab318a09.jpg)
![screenshot_20181008_150615](https://user-images.githubusercontent.com/7557867/46628634-28d69e00-cb0c-11e8-900a-5226401bfef1.jpg)

**Comment by poikilos** [comment]
View from opposite side of ground-level forest:
![screenshot_20181008_151124](https://user-images.githubusercontent.com/7557867/46628740-9edb0500-cb0c-11e8-943d-14a824c0fe7e.jpg)

**Comment by Ezhh** [comment]
Are you getting the behaviour over water with only MTG, and no other mods?

**Comment by poikilos** [comment]
This seems to confirm that it happens only with MTG:
![screenshot_20181008_152454](https://user-images.githubusercontent.com/7557867/46629411-b4e9c500-cb0e-11e8-8e40-9564887ed129.jpg)
![screenshot_20181008_152501](https://user-images.githubusercontent.com/7557867/46629412-b6b38880-cb0e-11e8-9487-c7503a828f3d.jpg)

**Comment by Ezhh** [comment]
That's burning the tree to the side, not burning the water. In your first screenshot, it appears that the fire is where trees have burned down and you haven't waited for al the fuel to be consumed, at which point the fire will eventually go out.

**Comment by poikilos** [comment]
But from further testing there is some fancy sideways fire that seems to be what is supposed to happen in that case, but it is not where one would expect (see last screenshot below) and fire burns along the air nodes above grass (apparently normal) but then beside the grass after the grass disappears:
![screenshot_20181008_152948](https://user-images.githubusercontent.com/7557867/46629809-19f1ea80-cb10-11e8-9817-c5dd4b327420.png)
![screenshot_20181008_153122](https://user-images.githubusercontent.com/7557867/46629813-1cecdb00-cb10-11e8-8b85-c98ff47c3dbb.png)
![screenshot_20181008_153459](https://user-images.githubusercontent.com/7557867/46629896-66d5c100-cb10-11e8-9a69-8d32ad6b09f5.jpg)

**Comment by paramat** [comment]
This is very weird.
4th screenshot: you have jungletree roots under the water but no tree above, as if the trees are invisible above the roots.

**Comment by paramat** [comment]
> This fire spread from the tree to the water

A flame above water doesn't mean the water is on fire, it is a flame node placed diagonally to it's fuel source (the jungletree)
> The seeds eventually burned up and the rest of the fire went out.

So it seems normal behaviour.
> However after several minutes, the fire spread to a node above the replanted wheat

That's not seeds on fire, it is a flame diagonal to it's fuel source (the short wheat).

I think all of this is confusion caused by flames being diagonal neighbours of their fuel source, i can't see any bug behaviour.

**Comment by poikilos** [comment]
Thanks, understood
