### ISSUE TITLE
stable-0.4 bump version tag to 0.4.17.2

### ISSUE THREAD

**Issue by tverrbjelke** [minetest/minetest_game#2235]
fresh install of 0.4.17.1 crashed on startup, see [Issue 2234](https://github.com/minetest/minetest_game/issues/2234) where the fix was to **not** checkout 0.4.17.1 but instead checkout stable-0.4.

So something has been fixed, which should be worth a new tag. ?

**Comment by rubenwardy** [comment]
Done

**Comment by paramat** [comment]
@rubenwardy what tags did you just add, 0.4.17.1 and 0.4.17.2?
