### ISSUE TITLE
binoculars doesn't delegate on_use to nodes

### ISSUE THREAD

**Issue by sofar** [minetest/minetest_game#2241]
just like the bucket and a few more items, the binoculars should be allowed placement in itemframes etc. The current code doesn't check that the pointed node has a handler and always makes it toggle zoom modes.

https://github.com/minetest/minetest_game/blob/0ea6065a09f1fee014c7f2a9a36605d57986a209/mods/binoculars/init.lua#L61

**Comment by paramat** [comment]
Ok :]

**Comment by paramat** [comment]
The mapping kit of map mod too it seems.
https://github.com/minetest/minetest_game/blob/382e2acd9b4320866d2bfdc29dd5e122bcb54994/mods/map/init.lua#L57

**Comment by paramat** [comment]
PR #2242

**Comment by paramat** [comment]
Tested 'frame' mod with binoculars and map added to the list in init.lua, works with MTG master:

![screenshot_20181024_103119](https://user-images.githubusercontent.com/3686677/47421344-49436100-d778-11e8-95e9-8638265da98b.png)
