### ISSUE TITLE
use_texture_alpha, or alpha = do not pick up nodebox drawtype

### ISSUE THREAD

**Issue by TumeniNodes** [minetest/minetest_game#2243]
This may be an engine bug but, I noticed that if a node's defs include
use_texture_alpha = true or
alpha = <given setting>
then you cannot see any node which uses the nodebox drawtype.

This happens with glass_like and framed optional but when it comes to water, nodebox drawtypes only disappear from 2 directions (which is another oddity)

Not sure if this has ever been brought up before, and if some solution can be worked out.

In this shot, the entire ceiling is done with wood slabs, and there are some stairs thrown in to show the result. The obsidian glass panes are using an alpha def due to experimenting with tinting.
![screenshot_20181015_160929](https://user-images.githubusercontent.com/18484258/46975774-867f6300-d095-11e8-9083-93d36296a95b.jpg)

**Comment by paramat** [comment]
Engine issue.
Semi-translucency is already very buggy in MT, however not seeing nodeboxes is a surprise.

**Comment by paramat** [comment]
See https://github.com/minetest/minetest/issues/95 for details.

**Comment by TumeniNodes** [comment]
Yeh, I've known about many issues in this area, one also involves using the water shader (water waving) to have the water appear slightly lower than the shore... anything which sits one node above the water produces the x-ray effect on the water node just under it.
This is just yet another.
If you notice as well though, nodebox also does not block any light, as a full node does.
Seems focusing on the nodebox drawtype a little might be good, eventually. Maybe there is some way to shore up their properties somehow?
