### ISSUE TITLE
key secret is crashing the server when opening chest

### ISSUE THREAD

**Issue by JurajVajda** [minetest/minetest_game#2244]
Hi i have recently collected the same error every day now, is there a way how to add an extra check for this?

MT Game 0.4.17.1
MT Engine 0.4.17.1 (Linux)
Irrlicht 1.8.3
Build info: VER=0.4.17.1 BUILD_TYPE=None RUN_IN_PLACE=0 USE_GETTEXT=1 USE_SOUND=1 USE_CURL=1 USE_FREETYPE=1 USE_LUAJIT=1

```
2018-10-15 09:24:44: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'default' in callback item_OnPlace(): ...hare/minetest/games/minetest_game/mods/default/nodes.lua:2225: attempt to index a nil value
2018-10-15 09:24:44: ERROR[Main]: stack traceback:
2018-10-15 09:24:44: ERROR[Main]: 	...hare/minetest/games/minetest_game/mods/default/nodes.lua:2225: in function 'on_key_use'
2018-10-15 09:24:44: ERROR[Main]: 	...hare/minetest/games/minetest_game/mods/default/tools.lua:415: in function <...hare/minetest/games/minetest_game/mods/default/tools.lua:387>
```

nodes.lua line:2225
```
key_meta:set_string("secret", minetest.parse_json(itemstack:get_metadata()).secret)
```

tools.lua line:415
```
on_key_use(pos, placer)
```

tools.lua line:387
```
on_place = function(itemstack, placer, pointed_thing)
```

**Comment by paramat** [comment]
Which line of code is line 2225 in nodes.lua of your MTGame?

Your version of MTGame is not 0.4.17, which version are you actually using?
What version of MTEngine are you using?

**Comment by paramat** [comment]
https://github.com/minetest/minetest_game/blob/d6a66860af6fc39957d8e947824b9c56c3686b8e/mods/default/tools.lua#L387
https://github.com/minetest/minetest_game/blob/d6a66860af6fc39957d8e947824b9c56c3686b8e/mods/default/tools.lua#L415

**Comment by JurajVajda** [comment]
I have updated the description with more clear and specific information to answer your questions.

I am not using modified MTGame, i keep MTGame without any code changes so i can update/merge new changes to MTGame without issues when there is new release.

It makes complete sense to me:
```
-- attempt to index a nil value
key_meta:set_string("secret", minetest.parse_json(itemstack:get_metadata()).secret)
```
Seems to me that we are trying to reach index "secret" in metadata of the "key" item which is "nil".

Why is key metadata nil?
I am suspecting recent item duplication bug (on my server) using machines - key item got duplicated but metadata will not be duplicated (makes sense to me). When trying to open chest with this dupe key, the metadata are missing. Could be the reason or it also could be completely something else, you can never get more impressed with what the players comes up on public servers.

What ever is the cause of missing metadata from the key item, this can be prevented in MTGame in the future. Since MTGame is one big modding factory place, its question of time when more errors like this start poping up while it can be easily prevented in MTGame with an extra check if the metadata exists or not. Assuming perfect scenario where the metadata always exists is unreal when having public servers and some mods.

This is just my opinion on what the error is and what it could cause at this point of time. I could be completely wrong but until i don't get more information or investigate more, this is what i would bet on.

**Comment by JurajVajda** [comment]
confirmed, the metadata is empty string "" so the parse json will result in "nil" since empty string "" is not a valid json format and everything after that goes down down

i can open a PR if that makes things easier

this is all what it is:
```
--- a/mods/default/nodes.lua
+++ b/mods/default/nodes.lua
@@ -2221,8 +2221,14 @@ function default.chest.register_chest(name, d)
                        local itemstack = player:get_wielded_item()
                        local key_meta = itemstack:get_meta()
 
+                       if itemstack:get_metadata() == "" then
+                               return
+                       end
+
+                       local key_meta_json = minetest.parse_json(itemstack:get_metadata())
+
                        if key_meta:get_string("secret") == "" then
-                               key_meta:set_string("secret", minetest.parse_json(itemstack:get_metadata()).secret)
+                               key_meta:set_string("secret", key_meta_json.secret)
                                itemstack:set_metadata("")
                        end

```

**Comment by paramat** [comment]
Thanks! A PR will be very welcome.
