### ISSUE TITLE
Fancy Bed Texture - Head inside texture misdefined

### ISSUE THREAD

**Issue by sirrobzeroone** [minetest/minetest_game#2251]
Hopefully not a duplicate.

Fancy bed is currently defined with `default_wood.png` as the inside of bed head texture. However this texture can be seen by the player as the bed head sticks up, creating a visual issue.  I corrected the line to confirm which one was the issue but for consistence it maybe better to reuse the appropriate bed head/foot texture for the reverse side of both.

**Potential Fix:**
```Lua
beds.register_bed("beds:fancy_bed", {
	description = "Fancy Bed",
	inventory_image = "beds_bed_fancy.png",
	wield_image = "beds_bed_fancy.png",
	tiles = {
		bottom = {
			"beds_bed_top1.png",
			"default_wood.png",
			"beds_bed_side1.png",
			"beds_bed_side1.png^[transformFX",
			"beds_bed_foot.png",
			"beds_bed_foot.png",
		},
		top = {
			"beds_bed_top2.png",
			"default_wood.png",
			"beds_bed_side2.png",
			"beds_bed_side2.png^[transformFX",
			"beds_bed_head.png",
			"beds_bed_head.png",   -- the one that can be seen by the player easily
		}
	},
```

EDIT by SmallJoker: Add formatting

**Comment by Napiophelios** [comment]
can you take a screen shot illustrating what your talking about;
preferably a before and after shot with the fix.

it looks the same to me, with or without the changes made.
which makes me think I don't really understand what you mean.

**Comment by sirrobzeroone** [comment]
No worries at all attached. Works fine on the base texture pack, it's when you starting getting more interesting floorboard patterns it starts to become noticeable. 
![texture difference](https://user-images.githubusercontent.com/44497598/47603512-7756c880-da38-11e8-9def-b6b8a3021439.png)

**Comment by Ezhh** [comment]
From a quick test, I can't see any issues within MTG from doing this.

**Comment by paramat** [comment]
Ok i see. Current code is:
```
	tiles = {
		bottom = {
			"beds_bed_top1.png",
			"default_wood.png",
			"beds_bed_side1.png",
			"beds_bed_side1.png^[transformFX",
			"default_wood.png",
			"beds_bed_foot.png",
		},
		top = {
			"beds_bed_top2.png",
			"default_wood.png",
			"beds_bed_side2.png",
			"beds_bed_side2.png^[transformFX",
			"beds_bed_head.png",
			"default_wood.png",
		}
	},
```
In texture pack 'default_wood' may often have a different design style to bed textures.
I agree that:
```
		top = {
			"beds_bed_top2.png",
			"default_wood.png",
			"beds_bed_side2.png",
			"beds_bed_side2.png^[transformFX",
			"beds_bed_head.png",
			"beds_bed_head.png",   -- the one that can be seen by the player easily
		}
```
Is better.

**Comment by TumeniNodes** [comment]
While textures for the fancy bed are being tended to here, how about fixing the rails under the bed as well?
I know they are 'under' but, that is no reason to half a$$ it.

The 'slats' under the mattress are fine... it is the two side-rails, underside that bug me.
![screenshot_20181028_023129](https://user-images.githubusercontent.com/18484258/47612865-f4466a00-da59-11e8-9da7-3a64c5621131.jpg)

if wee add these two textures
![beds_bed_under1](https://user-images.githubusercontent.com/18484258/47612972-383a6e80-da5c-11e8-93c9-4213336e02cd.png) beds_bed_under1.png
![beds_bed_under2](https://user-images.githubusercontent.com/18484258/47612973-3d97b900-da5c-11e8-9694-e4f621a67530.png) beds_bed_under2.png

and then these other two changes, I will sleep better

```tiles = {
		bottom = {
			"beds_bed_top1.png",
			"beds_bed_under1.png",
			"beds_bed_side1.png",
			"beds_bed_side1.png^[transformFX",
			"beds_bed_foot.png",
			"beds_bed_foot.png",
		},
		top = {
			"beds_bed_top2.png",
			"beds_bed_under2.png",
			"beds_bed_side2.png",
			"beds_bed_side2.png^[transformFX",
			"beds_bed_head.png",
			"beds_bed_head.png",
		}
	},```

**Comment by paramat** [comment]
I think that's not worth being fussy about as the underside is rarely seen.
If you add new textures you will then break texture packs, doesn't seem worth it.

**Comment by Napiophelios** [comment]
texture packs have to adjust to all the other additions to the game,
why would this be any different?

if a texture pack is already using default_wood.png for the under side of the bed,
how hard is it to just duplicate the texture and rename it?

@TumeniNodes why cant you just use one texture twice?

**Comment by TumeniNodes** [comment]
> texture packs have to adjust to all the other additions to the game,
> why would this be any different?
> 
> if a texture pack is already using default_wood.png for the under side of the bed,
> how hard is it to just duplicate the texture and rename it?
> 
> @TumeniNodes why cant you just use one texture twice?

due to the 'knots' in the wood on default wood. This aligns with the other bed's underside... take a closer look

**Comment by paramat** [comment]
Napiophelios yes, but it's a case of balancing the disruption of texture packs against the fact that the bed underside is almost never seen, and that being concerned about plank divisions on the side rails is being very fussy, and that many texture packs will have wood textures that won't have divisions so that there is no issue.

However, the best approach would be to not use the default:wood texture and use bed mod textures for all tiles. So add a dedicated bed underside texture, flipped 180deg for one half of the bed. I won't object to that.

**Comment by paramat** [comment]
Actually, since attending to the first issue removes the use of default:wood, this would be a good time to also remove the use of that for the underside, and make the mod self-contained in terms of textures.
So i'll +1 a PR that attends to both issues. 1 new mod texture for underside, using a texture transform to flip it for one bed half. @TumeniNodes interested in making a PR?

**Comment by TumeniNodes** [comment]
Yeh, I can do that.
So you just want to add one new underside 'beds_bed_under.png' and flip it for the other half, and add the head/foot board changes from this issue.
This will make the mod completely independent as you said.

**Comment by TumeniNodes** [comment]
@paramat #2253

**Comment by TumeniNodes** [comment]
and btw... @Napiophelios  was right.
He's my texture/code efficiency mentor... 'never question the Nappi' : )

**Comment by paramat** [comment]
#2253 merged.
