### ISSUE TITLE
Fence needs to connect to Mese lamps

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest_game#2258]
![screenshot_2018-10-31-16-40-31-1](https://user-images.githubusercontent.com/33675971/47824816-de6fc800-dd2b-11e8-921f-fc21259d19ae.png)
Screenshot basically explains it

**Comment by Fixer-007** [comment]
Interesting question.

**Comment by benrob0329** [comment]
I'm pretty sure you're supposed to put it on top of the fence, if the fence connects to it it'll look funny.

**Comment by TumeniNodes** [comment]
Recently, I thought the same thing, and redid the texture for meselamps so the light is in the center/vertically, just for my own craziness.
Not sure if it's something enough people would care for.

This is a perfect example of when it is a good time to whip up a mod and make it available for others who may like it.
That way, everyone can have both versions. ;)

So, I have to down-vote this idea, as I feel it is better done as a mod.

**Comment by Ezhh** [comment]
Definitely better for a mod in my opinion. :-1:

**Comment by paramat** [comment]
:-1:

**Comment by paramat** [comment]
The light section itself would have to be very different, small and central (ugly) or very small and at the top.
These only come in one wood type so would have limited use as part of fences.

The main issue seems to be breakage of worlds. I can imagine these used between a path and a fenced area, there would then be ugly connections with any nearby fence. Post lights look best when, and are intended to be, free-standing.
