### ISSUE TITLE
Fence texture map for top of bars rotate by 90 degrees for better fit

### ISSUE THREAD

**Issue by sirrobzeroone** [minetest/minetest_game#2259]
This is more a suggestion/cleanup/improvement, although i do feel it would provide more versatility to those creating texture packs as you could then for example have bark texture on the posts and cross bars bark free for an interesting new look for fences (literally how I stumbled on the issue)

**Issue**
In the picture below I have color coded the texture map to blue - post, red-rails, green - unused proposed rail tops/bottom. I applied a slight color gradient to the colors to show the potential mismatch issue of reusing the post texture as the rail top. At the moment the tops of the fence rails reuse the post texture. Which can cause some graphic mismatch issues for example if the posts are textured differently to the rails eg raw bark posts, cut wood rails or decorative carved posts and plain rails. The top two pictures illustrate the current mapping with the green section unused and the blue post texture laid across the top of the fence bars.

**Proposal/Idea**
Realign the texture by rotating it 90 degrees when mapping the image along the top of the fence rails (green portion). This part of the texture is currently unused by the fence schematic as far as I can see. this would give the top (and bottom) of the fence rails a unique texture segment that can be used without adding a whole new texture. The lower half of the attached image is a mock up of this, although i couldn't test this in game as I can't find were the fence texture mapping is stored...sorry not enough experience with minetest/Lua.

edit - the top of the post is also another minor bug bear but less so than the rails. I quick fix there might be to map a middle part of the post side to the top rather than starting the texture from the top edge on the left side - can be seen in the below picy if you look carefully at the gradient. Happy to raise a separate suggestion if it also has merit.

![fence](https://user-images.githubusercontent.com/44497598/48095940-1f0a9c80-e26a-11e8-847f-581ed8d92ab0.png)

**Comment by Napiophelios** [comment]
After such a precise, clear cut presentation;
an in game example with working textures 
would be the icing on the cake.

Do you have a prototype/W.I.P. texture for comparison?

**Comment by paramat** [comment]
Clever idea.

**Comment by TumeniNodes** [comment]
@paramat  if you like, have a look at https://github.com/TumeniNodes/aufbauen/blob/master/mods/wood/fence.lua#L124 and then the textures to see a similar method I have been using, could easily implement this as well. Check the textures too
 All combined offer a new way of doing fences, which will allow users/modders to create various types of fence combinations
 I had planned to try a PR for this at a later date

**Comment by DS-Minetest** [comment]
>I can't find were the fence texture mapping is stored

Fences use connected nodeboxes.
Nodeboxes are defined using multiple boxes (or only one box) that have each 6 sides. You can only give a maximum 6 textures to a nodebox.
Connected means that you can define extra boxes for when the neighbor node is of the same type.
A box is defined by two positions (x1, y1, z1, x2, y2, z2). The corners of the box are (relative to the position of the node (a layperson would call it block)) at (x1, y1, z1), (x2, y1, z1), (x1, y2, z1), (x2, y2, z1), (x1, y1, z2), (x2, y1, z2), (x1, y2, z2) and (x2, y2, z2). (y is height.)
The mapping of nodeboxes is simple: one texture is mapped on all box sides that are in x+ direction, one for all in y+ direction, ….
You can't manipulate the mapping of nodeboxes in mods.

With one texture this would be problematic. The top faces of the railings in x direction will be green but the one in z direction will be blue or vice versa.

The fences @TumeniNodes showed use two textures and [could already be implemented with the current fence API](https://github.com/minetest/minetest_game/blob/ad486bc863e9b0f27f69904f7a9c82bac422842f/mods/default/functions.lua#L309).

Maybe I've misunderstood something, sorry. >_<

**Comment by paramat** [comment]
>  if facedir is included

It can't be though for connected nodeboxes.

**Comment by TumeniNodes** [comment]
@paramat I realize this has been closed but, just want to show you the difference..
without paramtype2 facedir
![without paramtype2 facedir](https://user-images.githubusercontent.com/18484258/48236787-c9311400-e391-11e8-85f2-ce30657fa80d.jpg)

with paramtype2 facedir
![with paramtype2 facedir](https://user-images.githubusercontent.com/18484258/48236794-cf26f500-e391-11e8-9c51-caa4c7f8da56.jpg)

The ability to be able to place the node in the direction the texture matches up, can make a visible difference at times.

**Comment by paramat** [comment]
That seems something possibly fixable by altering textures. Can facedir even be applied to 'connected to'? Even if it can that would create confusion and issues.

**Comment by paramat** [comment]
Consider that the connections will not rotate even if the node is rotated using facedir (or do they?), that's confusing and likely to cause issues, MTG should not do this.

**Comment by TumeniNodes** [comment]
I definitely agree on taking the texture approach first. Adding the use of 3 textures (which just means adding another texture, per fence type, should be able to serve as most of the solution.
Only one downside... this means also creating another new texture for either a - to use with the fence-overlay for inv and wielded image or, b - just use straight up individual (still requires new inv/wield image) and toss the fence-overlay

Just some points to consider there before even thinking about making any changes
