### ISSUE TITLE
Incorrect sRGB profiles in stairs textures

### ISSUE THREAD

**Issue by stujones11** [minetest/minetest_game#2261]
`WARNING[Main]: Irrlicht: PNG warning: iCCP: known incorrect sRGB profile`

Offending files:
```
/stairs/textures/stairs_obsidian_glass_stairside.png
/stairs/textures/stairs_obsidian_glass_outer_stairside.png
```

Fix: https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile/40368994

**Comment by TumeniNodes** [comment]
It is possible I did not check this with the obsidian textures during that PR.
I'll check this shortly. Thank you stujones11

**Comment by TumeniNodes** [comment]
#2262
@stujones11 can you test and let me know if it;s all set please?

**Comment by stujones11** [comment]
@TumeniNodes Those were the only two images that were flagged when scanning all textures. Here is the script I use.
```sh
#! /bin/sh
find . -name '*.png' -print | while read pngfile; do
  libpngoutput=$(pngtogd $pngfile /tmp/test.gd 2>&1)
  if [ -n "$libpngoutput" ]; then
    echo $pngfile
  fi
done
rm /tmp/test.gd
```
You will need to have `libgd-tools` installed otherwise it flags very image as bad. Of course, you can easily see if your changes fix the warning by simply launching the client from a console ;)

**Comment by TumeniNodes** [comment]
Thank you stujones11.
Oooh, I like that script, will come in handy.
