### ISSUE TITLE
Steam Era of Minetest Game

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#2264]
You have all those useless metals sitting in, so lets add some fun into the game. I know lots of people love steam engines, so:

+ Steam engine is crafted from metals, mese (etc), uses different materials as fuel providing different amount of power
+ Two kinds of transport: unpowered and powered (boats and carts)
+ Unpowered cart can be used downhill only
+ Powered cart can go any way
+ Unpowered boat is slightly faster than walking
+ Powered boat is even more faster (maybe 6-7)

In future its use can be expanded to directly drive automation.

**Comment by paramat** [comment]
Steampunk! I actually tend to think of MTG as fantasy-floating-island-steampunk =)

**Comment by TumeniNodes** [comment]
heh, the thing I'm working on right now will eventually be steampunkish, will eventually also entail quite a few animations

**Comment by DS-Minetest** [comment]
Aren't the boat and the cart a bit small for carrying a steam engine?

**Comment by paramat** [comment]
Could have a small steam engine :) Requiring water and coal.
We can't remove powered rails and carts obviously, but a small steam train could run without powered rails (as long as this doesn't cause problems in the carts mod).
A steam boat is a nice idea. I have been wanting to add oars to the current boat to make clear how it is powered.

**Comment by TumeniNodes** [comment]
The idea of steampunk still carries a lot of weight in the gaming world... adding similar characteristics will probably draw more interest.
It would also be a decent way to somewhat draw attention away from the lack of mobs.

Since pathfinding remains a big enough issue, it makes sense to try adding other game mechanics which are easier to obtain/execute and add interest and value to the idea of being a 'game'

**Comment by TumeniNodes** [comment]
Working on a universal steam power system, will involve furnace, boiler, belt drives,  and generators to power lights, and various machines.
Thankfully with all the new energy being focused around formspecs, this may actually be "_fun_" to work on.

**Comment by paramat** [comment]
This is a good idea, but new vehicles seem more suited to optional mods, because there are so many possible vehicles and everyone wants something different of varying eras.
Doesn't seem essential to me, so best not added to MTG, much as i love vehicles.

**Comment by rubenwardy** [comment]
Backlog means long term. I don't see why it's "certainly not in backlog"

**Comment by paramat** [comment]
Sorry, i misunderstood 'backlog', thought it meant 'urgent backlog of things that should have been done by now'.
