### ISSUE TITLE
Have a book_database in the world folder

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest_game#2266]
Instead of saving books in item meta or player inventory
Save into a folder. This way books will never be lost

**Comment by jastevenson303** [comment]
Can be done with modding.  Great idea for a mod IMO.

**Comment by paramat** [comment]
But item meta is just as reliable. Books need to be deleted sometimes, so losing is necessary.
Do you mean saved in text form to be readable?

**Comment by Extex101** [comment]
I play on a server and books are very precious. But once in a while a player will suffocate in a wall and lose the book forever.
Which is why I want books to be saved in this way

Maybe genorate a book_number stored in the meta and then gets the book text with the code of the book

**Comment by paramat** [comment]
I see. Why not do this in a mod since it's a feature likely only wanted by a few people?

**Comment by Extex101** [comment]
And have a "bookeeper" priv or just server where you input the code and the book is created

**Comment by Ezhh** [comment]
I don't think there is any need for this in MTG, and I've never had any player on my servers ask for it, so I'm fairly sceptical. You can also retrieve book content from the log if this is a major issue for you.

https://github.com/minetest/minetest_game/blob/21f5eaade052684d2694f6584496f8b5dc48d4ea/mods/default/nodes.lua#L2511

**Comment by paramat** [comment]
Best done by mod i think :-1:
