### ISSUE TITLE
HUD texture changes

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest_game#2267]
#### NEW HEART
![giant heart](https://user-images.githubusercontent.com/33675971/48875347-671ed880-edad-11e8-875f-47f8ccf2fa72.png)
#### Original heart
![ugh](https://user-images.githubusercontent.com/33675971/48875511-56229700-edae-11e8-8439-2456b5ee944a.png)

#### IN GAME SCREENSHOT
![screenshot_2018-11-21-16-32-24-1](https://user-images.githubusercontent.com/33675971/48875295-f4156200-edac-11e8-8914-4130eb390f66.png)

Raw format: 
![hud_heart_fg](https://user-images.githubusercontent.com/33675971/48875382-a51bfc80-edad-11e8-9bba-05968cf0dc4c.png)
bg heart
![hud_heart_bg](https://user-images.githubusercontent.com/33675971/48875399-ba912680-edad-11e8-8c4c-ec6546b2b651.png)

/////////////////////
EDIT: XD all the hearts ⬇️

**Comment by LoneWolfHT** [comment]
That looks a lot better

**Comment by Ezhh** [comment]
It looks too flat to me, and I don't think this needs changing. Maybe you should consider making your own texture pack though, since you clearly have some skill with textures.

**Comment by SmallJoker** [comment]
Not saying that it looks bad, but I also think that it would fit better into a texture pack.

**Comment by Extex101** [comment]
@Ezhh (advise taken) started texture pack!
![screenshot_2018-11-22-12-59-34-1](https://user-images.githubusercontent.com/33675971/48921831-4f039380-ee57-11e8-8b3d-a9279f121f52.png)

**Comment by Ezhh** [comment]
@Extex101 Is it okay to close this?

I suggest you post about your texture pack on the forum. I think a lot of people will want to try it. :)

**Comment by paramat** [comment]
I much prefer the current heart, fuller shape, shiny and more 3D.
