### ISSUE TITLE
Pine tree leaves do not decay properly

### ISSUE THREAD

**Issue by Snipie** [minetest/minetest_game#2277]
The pointy top of 2 blocks of the pine tree does not decay and that is because the decay radius is set to 2 (mapgen v7) while the pointy top is of 4 blocks length.

Two possible solutions:
Change the radius to 4 **but** this will cause a problem in case of two adjacent trees.
Shorten the pointy top to 2 blocks length so it decays with the rest of the tree.

https://github.com/minetest/minetest_game/blob/da10af919eddc8f7e73c14f802290a5ea8f7b5f0/mods/default/nodes.lua#L2775-L2815

https://github.com/minetest/minetest_game/blob/da10af919eddc8f7e73c14f802290a5ea8f7b5f0/mods/default/trees.lua#L263-L270

![screenshot_20181231_024104](https://user-images.githubusercontent.com/8315338/50553377-7ee75780-0c9d-11e9-8ddf-3080f5525fa8.png)
![screenshot_20181231_024347](https://user-images.githubusercontent.com/8315338/50553382-91619100-0c9d-11e9-9629-6728ad662282.png)

**Comment by paramat** [comment]
Thanks, the small pine tree needs a larger radius, i may extend the trunk up 1 node and increase the radius to 3.

**Comment by paramat** [comment]
PR #2284

**Comment by MarkuBu** [comment]
Is this really fixed? I downloaded the current versions of Minetest an an MTG form Github, but I still have this bug

**Comment by paramat** [comment]
It should be, will check.
