### ISSUE TITLE
Need for mapgen_lua.cpp as a mapgen option.

### ISSUE THREAD

**Issue by oiaohm** [minetest/minetest_game#2278]
I have run into a intermittent problem with skyblock mod.   Where due to high IO load I can at times enter and die before the skyblock mod map gen has completed.

This is when I notice following
1)No option that I can see when creating map to say there is expected to be a lua mapgen.   
2)No auto deplaying for lua mapgen.

Issue 1 results in you being able to enter game by mistake when you have failed to select the lua mapgen this would be better if the game server error with lua mod mapgen missing.

Issue 2 results in me at times being able to enter the server before the lua map gen is 100 percent ready and fall to death in skyblock mod while watching the skyblock island appear above me.

This could be that mapgen_lua.cpp gets added next to the likes of mapgen_v6, v7....   So that lua map gens are not second interfaces.    You could even allow the lua mapgen to use multi mapgen cpp modules in different areas of the map so a map that is in fact a mix of mapgen v6/v7, valleys... with how that layout is decided by the lua.

**Comment by paramat** [comment]
This is an engine issue, please post at https://github.com/minetest/minetest/issues
