### ISSUE TITLE
Need for mapgen to inform server of a list of valid spawn locations.

### ISSUE THREAD

**Issue by oiaohm** [minetest/minetest_game#2279]
I have attempt to create a described world mapgen with a locked spawn point at 0, 0, 0 as something to start with.

At this point I noticed a problem.

getSpawnLevelAtPoint(v2s16 p)  allows me to say location is invalid to and cause Server::findSpawnPos() to try again.

Lets say I have created a map for pvp to be a bit like Xonotic/doom/quake.   Where there are like only 12 valid spawn points.   Current api design means we end up with a huge loop between findSpawnPos and getSpawnLevelAtPoint until it find one of the magical 12 spawn points or after 4000 attempts fail and attempt latter as you can see here.
https://github.com/minetest/minetest/blob/3d66622772e66154b7624957a27f9be54c4c7c28/src/server.cpp#L3478

It would be useful if there was a method to set list of valid spawn points/ spawn zones.

Of course the list may or may not be random-ally applied.

So in my eyes
getMapgenParams()->getSpawnRangeMax();   This is ok if you want spawning in a limited block area.
but we need a getSpawnList() that returns a list nodepos2d or void and  getSpawnListCycle() that returns random/cycle/fixed. 
If getSpawnList() is Void do what  findSpawnPos currently does.   If not void get  getSpawnListCycle() if random use random to choose a spawn point out of the spawn point list.   If cycle simple start at the top of the spawn point list and as each player enter give them the next spawn point in list and when get to end go back to start.   Fixed is simpler is each player enters they get a spawn point until they leave it is theirs.

I would like to make it simpler to make some static generated world segments for minetest.   This could be useful to RPG mods and the like.

getSpawnZoneList () as well.   Think pvp team play.   area could be like two nodepos2d that player have to spawn inside.   So areas of the map have to be travel to and you cannot just random-ally spawn.

I do see mods using Lua to force way around this limitation but really not  the best path.   I am not sure if this should be a mapgen Params or a global server param possible settable by minetest.conf, mapgens and lua mods and stores in the world file.

**Comment by paramat** [comment]
This is an engine issue, please post at https://github.com/minetest/minetest/issues
