### ISSUE TITLE
Pointless code? 'default.gui_bg/bg_img/slots'

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2280]
```
-- GUI related stuff
default.gui_bg     = ""
default.gui_bg_img = ""
default.gui_slots  = ""
```
```
`default.gui_bg`

 * Deprecated, remove from mods.

`default.gui_bg_img`

 * Deprecated, remove from mods.

`default.gui_slots`

 * Deprecated, remove from mods.
```
However these 3 are used everywhere in MTGame mods, but seem non-functional. Why are they still present?
EDIT for clarification:
Can we keep the definitions but remove their usage in creative mod, chests, bookshelves etc,?

**Comment by sofar** [comment]
Used in many mods, which will crash the lua stack if they are no longer defined. Retain these for compat reasons, please.

**Comment by paramat** [comment]
Ok. To be more clear, can we keep the definitions but remove their usage in creative mod, chests, bookshelves etc,?

**Comment by jastevenson303** [comment]
Yes, those formspec strings are now set using player:set_formspec_prepend.

**Comment by paramat** [comment]
The placed where these 3 are used can be seen here https://github.com/minetest/minetest_game/search?q=default.gui_bg&unscoped_q=default.gui_bg

**Comment by rubenwardy** [comment]
This variables can be removed from any usages, but the definitions should be kept

**Comment by paramat** [comment]
Great thanks.

**Comment by paramat** [comment]
PR #2282
