### ISSUE TITLE
Conclusion/Roadmap/Plans on world-aligned textures for upside-down stairs, etc.?

### ISSUE THREAD

**Issue by Linuxdirk** [minetest/minetest_game#2287]
Since we finally have an option for having properly aligned textures on upside-down stairs it is not used on stairs with problematic textures which still leaves a mess.

![screenshot_20190116_072238](https://user-images.githubusercontent.com/46120351/51230272-ae65b780-195f-11e9-9f92-d6fe2ca6913d.png)

It is assumed in https://github.com/minetest/minetest_game/issues/2216 that misaligned textures are caused by world-aligning them. This is actually wrong. The weird look also happens when not world-aligning the stairs textures.

![w](https://user-images.githubusercontent.com/46120351/51230440-46fc3780-1960-11e9-89ef-0e9aa1d99625.png)

To me it seems like the base texture is not rotated properly in the first place (i.e. on definition of the node itself, using some sort of texture modifier like `[transformR90` for the bottom or top texture.).

Since the “illogical” look does not depend on world-aligned or not I think it would be okay to set world-aligned textures by default. The screwdriver of course should reset the texture to *not world-aligned* to allow texture-based designs.

But what are the actual plans on that?

Related/Relevant:
* https://github.com/minetest/minetest_game/issues/1931
* https://github.com/minetest/minetest_game/issues/2216
* https://github.com/minetest/minetest_game/pull/2219
* https://github.com/minetest/minetest/issues/5222

**Comment by paramat** [comment]
Oh crumbs this issue =) It was controversial but decisions were made in the linked issues.
> Since we finally have an option for having properly aligned textures on upside-down stairs it is not used on stairs with problematic textures which still leaves a mess.

That was discussed at length and decided upon by the core devs. World aligned nodes can be added using a mod and must be separate nodes from the originals already being used in worlds.
> It is assumed in #2216 that misaligned textures are caused by world-aligning them. This is actually wrong. The weird look also happens when not world-aligning the stairs textures.

Faklse logic. Your 2nd statement, while true, doesn't negate the alleged assumption.
> Since the “illogical” look does not depend on world-aligned or not I think it would be okay to set world-aligned textures by default.

You're then using this false logic to justify something that has been ruled out by the core devs.
///////////////

However, we can certainly consider rotating certain textures to make brick edges line up properly, if that is possible. But this is unrelated to the world-alignment.

**Comment by Fixer-007** [comment]
>The screwdriver of course should reset the texture to not world-aligned to allow texture-based designs.

That is what I suggested as well.

**Comment by paramat** [comment]
If the screwdriver has the ability to switch world-alignment, the default would have to be not world-aligned.

Concerning the other issue of some textures not being orientated to textures of other node faces in a way that makes sense:
Changing the orientations of some tiles would change the appearence of builds in worlds, possibly in ways the player does not like.
So again is a possible problem: It improves appearence in some ways, but also changes the appearence of existing builds. When trying to balance these two effects, the priority seems to me to be keeping the original appearence of builds unchanged, assuming that the builder intentionally bult something to look that way (which is likely).

However of course, from now on, any new nodes added can have the textures carefully orientated to other faces.

**Comment by Linuxdirk** [comment]
> If the screwdriver has the ability to switch world-alignment, the default would have to be not world-aligned.

Is it even possible to change the texture alignment after the node was registered? As far as I can see texture alignment is not node metadata but tile definition on node registration.

**Comment by paramat** [comment]
> Is it even possible to change the texture alignment after the node was registered?

Indeed, this could only be done by adding another node, the screwdriver would swap one node for the other.

**Comment by Linuxdirk** [comment]
> this could only be done by adding another node, the screwdriver would swap one node for the other.

So it is not possible. I think I will hardcode-modify the stairs generation for my server/world by altering the stairs and slabs nodes after registration. Not a clean solution but better than the current state.

Are there any plans to properly allow altering the texture alignment via meta data?

**Comment by paramat** [comment]
Sorry, correct, it is not possible.
There are issues and abandoned PRs for meta-set nodedefs in the engine, but it seems to have issues.

Sorry to close this but the decisions were already made in the issues, you could perhaps continue discussion in #2216 if you want.
I suggested we add additional nodes with world-alignment so that there is a choice, but that was very controversial and i don't feel strongly enough to fight for that and am also somewhat unsure.

**Comment by Linuxdirk** [comment]
> you could perhaps continue discussion in #2216 if you want.

Which is also closed and abandoned.
