### ISSUE TITLE
Stairs texture alignment is broken (specifically stone brick nodes, full nodes too)

### ISSUE THREAD

**Issue by Linuxdirk** [minetest/minetest_game#2289]
Issue derived from https://github.com/minetest/minetest_game/issues/2287

The alignment of stairs textures is broken in Minetest game. It seems like textures are not rotated properly to match the sides of the nodes. For example: This resulting in bricks that are broken on top and on the sides but not at the bottom.

![w](https://user-images.githubusercontent.com/46120351/51230440-46fc3780-1960-11e9-89ef-0e9aa1d99625.png)

It seems like the base texture is not rotated properly (i.e. on definition of the node itself, using some sort of texture modifier like `[transformR90` for the bottom or top texture.).

**Comment by Linuxdirk** [comment]
> Brick floors will no longer have an interlocking brick pattern

This will actually be the most noticeable change when fixing this bug as implied. But actually I don’t see the full node as too critical here because it’s usually used for walls/ceilings/floor so you only see one face at a time.

Stairs are much more used in free space and it’s more likely to see a stair from more than one face at a time so having stair face textures matching might me a little more important than full node textures matching.

**Comment by paramat** [comment]
I wouldn't accept only changing the stairs, sloppy and inconsistent. Multiple faces of the full nodes are seen often too.

**Comment by Ezhh** [comment]
:-1: for the concept of changing this (I am sorry, because I do understand why you might request it).

There is simply no way of using texture transforms that will align the textures correctly on all faces unless multiple textures are used, which is an approach with its own issues.

**Comment by paramat** [comment]
Yes i'm :-1: too due to the unfortunate problems, would break texture packs too.
