### ISSUE TITLE
bed formspec requires no_prepend[]

### ISSUE THREAD

**Issue by jastevenson303** [minetest/minetest_game#2291]

**Comment by rubenwardy** [comment]
The bed formspec should use `position[]` and `anchor[]`, and not `no_prepend[]`

**Comment by jastevenson303** [comment]
Whatever the solution, it looks like this currently:

![image](https://user-images.githubusercontent.com/23448162/51680372-96b9af00-1faf-11e9-88d6-bda7294a289b.png)

**Comment by SmallJoker** [comment]
2ff9058
