### ISSUE TITLE
crafting inventory formspec hotbar has a slight offset

### ISSUE THREAD

**Issue by jastevenson303** [minetest/minetest_game#2292]
This was introduced with sfinv, and is slight, and does not match the creative inventory, or chest, or any other inventory hotbar.

**Comment by jastevenson303** [comment]
![image](https://user-images.githubusercontent.com/23448162/51681520-d33ada00-1fb2-11e9-8df7-0db7ad8f335d.png)


https://github.com/minetest/minetest_game/blob/master/mods/sfinv/init.lua#L12
^ These should be 4.7, not 4.75...

**Comment by paramat** [comment]
PR welcome.

**Comment by jastevenson303** [comment]
Yeah, right.
