### ISSUE TITLE
Add sneak animations

### ISSUE THREAD

**Issue by ClobberXD** [minetest/minetest_game#2294]
I was working on adding sneak animations for CTF (see MT-CTF/capturetheflag#318), and thought it'd be useful for MTG as well. Please do let me know if this is a good idea, and what the actual animations should be. Just bending the torso forward looks very awkward, as the legs would still be upright. Legs bent at the knees with a forward-leaning torso, would be very realistic and ideal, IMO, but isn't directly possible as there is only one bone for the whole leg. Should the collision/selection box be altered as well?

**Comment by paramat** [comment]
No knees! The player doesn't have knees so adding them makes no sense =)
Current sneak just being a slow normal movement doesn't look good so a dedicated sneak animation could be good.
Not sure what the animation could be yet, let's do it when we have a good idea.
I guess it will work with the existing bones, can bones be shortened in an animation?

**Comment by benrob0329** [comment]
I think that the "MC Style" sneak animation looks fine with the limited articulation that our current model has.

**Comment by LoneWolfHT** [comment]
Knees are fine if you do it right

**Comment by An0n3m0us** [comment]
Sneak animation (I made this quickly so it still needs to be tweaked a little):
![sneak](https://user-images.githubusercontent.com/49789044/59197849-415ef280-8b8a-11e9-88ea-37af84fd7ba9.gif)

**Comment by DS-Minetest** [comment]
Tbh, that looks like Sam is going to vomit to the left.

**Comment by An0n3m0us** [comment]
I did say it needed improvement.

**Comment by LoneWolfHT** [comment]
Needs the chin lifted a little. Might look good with the arms out to the side a little too. Kind of like the Skyrim crouching if you've ever played that game

**Comment by An0n3m0us** [comment]
![walk](https://user-images.githubusercontent.com/49789044/59210134-c1925180-8ba4-11e9-91a5-4cef4474ff80.gif)
(As you can see in this gif his head bobbing too much, but I've fixed that in the model now)

**Comment by LoneWolfHT** [comment]
In the gif it just looks like they're slouching badly. I think something needs to be done with the arms/legs to make them look a little more involved in their sneaking

**Comment by An0n3m0us** [comment]
There. I made the bobbing less prominent:
https://my.pcloud.com/publink/show?code=XZT9mN7Zo5gYNGNt23YsmJFflzYTYJOj6DGy

**Comment by paramat** [comment]
I think head tilted downwards as before looks better, as sneaking is usually done when carefully creeping along edges where you would be looking downwards a little.
Anyway, potentially good work.

**Comment by Tomracer** [comment]
I like the animation and the idea!
Will be cool when it will be added to mtg!

**Comment by benrob0329** [comment]
Maybe move the arms out a little while sneaking, almost like you do when slinking along a wall or keeping one's balance (but not quite as much as either of those examples).

**Comment by ClobberXD** [comment]
Regarding what paramat suggested, I think the head should be tilted down very slightly, and should still be facing forward.

**Comment by DS-Minetest** [comment]
May I suggest not doing such a minecrafty sneak animation but more something like this:
[sneak.m4v.zip](https://github.com/minetest/minetest_game/files/3421727/sneak.m4v.zip) (download, dezip, then watch)

**Comment by An0n3m0us** [comment]
Looks good, but I think the body rotation is a little too much.

**Comment by An0n3m0us** [comment]
I changed the sneak animation a little:

https://my.pcloud.com/publink/show?code=XZOBMc7Za82YqUlKqn8ryhQdeyUsCHmxjNPk
https://my.pcloud.com/publink/show?code=XZIBMc7ZyGjvP4ctIzLnpARTxqruuSbl498V

**Comment by ClobberXD** [comment]
Nice! I like how the arms are pointing a little outwards.

I prefer the first one more than the second - the second one swings the arms a tad too much.

**Comment by An0n3m0us** [comment]
Haha they are the same animation! Just different views.

**Comment by An0n3m0us** [comment]
Here's the latest; the arm movement is a little weird still but I'm working on it.
https://my.pcloud.com/publink/show?code=XZbQgBkZdkxGPiGeWn5QGrAjC0oATjOlhBuX

**Comment by An0n3m0us** [comment]
@DS-Minetest How did you manage to play the sneak animation? I've battled with the player api for around 2 hours now but with little success. 

I can get the animation to play when the player isn't walking but holding control, but I cannot get it to work otherwise unless I remove the "local_animation" table in init.lua.

**Comment by LoneWolfHT** [comment]
https://github.com/minetest/minetest/issues/8335

**Comment by An0n3m0us** [comment]
So it isn't possible?

**Comment by DS-Minetest** [comment]
>@DS-Minetest How did you manage to play the sneak animation? I've battled with the player api for around 2 hours now but with little success.

I've just set the client-side `walk` animation (in `set_local_animation`) to `nil` and added a `player_set_animation` call for server-side animation. :/

**Comment by paramat** [comment]
Closing due to #2710
