### ISSUE TITLE
Forbid swimming in lava

### ISSUE THREAD

**Issue by vladtcvs** [minetest/minetest_game#2296]
In real world, you can not swim in lava because lava has much greater density, than human body. So you can not sink in lava. What about make such option in MT?

**Comment by vladtcvs** [comment]
https://youtu.be/lPqhCSDvNrs?t=11

**Comment by Wuzzy2** [comment]
Screw the real world! I'd say this is a classic case where you should ignore realism for gameplay.

**Comment by rubenwardy** [comment]
First they take away my renewable lava, next they take away my nyan cats, now they want to take lava swimming - Resist! Rise up, and seize the means of production!

**Comment by vladtcvs** [comment]
> ignore realism for gameplay.

How does lava swimming help the gameplay?

**Comment by vladtcvs** [comment]
> now they want to take lava swimming

But instead you will run on the lava, which is impossible now.

**Comment by paramat** [comment]
What's a simple alternative, walkable = true? If that works, if the player doesn't enter the lava are they still damaged?
I prefer to go with simplicity and practicality on this. Also, some may depend on being able to swim in lava, with damage disabled somehow.
So i'm probably -1.

**Comment by vladtcvs** [comment]
> If that works, if the player doesn't enter the lava are they still damaged?

Yes, they should be still damaged.

**Comment by jastevenson303** [comment]
i think some mods/games/servers have lava protecting armor.  don't see that
in "real life" either.

lava is pretty hard to move around in already in my experience, but i agree
that player sinks into it too quickly.  getting out seems to be a bit
trickier.

**Comment by paramat** [comment]
:-1: because it will probably break someone's game, mod or server.

**Comment by LoneWolfHT** [comment]
Wouldn't be hard to make a mod for this

**Comment by Ezhh** [comment]
> Also, some users may depend on being able to swim in lava, with damage disabled somehow.

Would break the use of crystal armour, which is frequently used with ethereal.

**Comment by LoneWolfHT** [comment]
> > Also, some users may depend on being able to swim in lava, with damage disabled somehow.
> 
> Would break the use of crystal armour, which is frequently used with ethereal.

Same for the armor in my PFP lol

**Comment by HybridDog** [comment]
Maybe you can change the lava item description (to something like "Light Lava") to define Lava to be liquid lava with low density.

**Comment by paramat** [comment]
Valid suggestion but impractical, thanks anyway.
