### ISSUE TITLE
Random spawn after sleeping in a bed

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest_game#2298]
> i respawned on random places everytime i died even already slept on my bed

Minetest 5.0.0
Latest MTG

**Comment by jastevenson303** [comment]
Any more details?  I just tested in current HEAD singleplayer, slept during night, and typed /killme and respawned atop the bed as per usual.

**Comment by rubenwardy** [comment]
Mods:

mobsredo,clouddlands,dynamyliquid,caverealm,facade,mesecon,notsosimplemobs,animalsmobs,rangedweapons,valleymapgen,workingvillages

**Comment by jastevenson303** [comment]
any of those use minetest.register_on_respawnplayer?

**Comment by paramat** [comment]
Possibly an issue like #2236 fix was #2240 
A mod may have it's own spawning code that is overriding beds 'on respawnplayer', my guess is the lua valleys mapgen.
