### ISSUE TITLE
Player can respawn in bad position due to bed

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#2300]
It is possible for a player to spawn in a deadly position with no chance of escaping, forcing the player to be stuck in an eternal die-respawn loop.

This is possible because of beds.

How to reproduce:
1. Wait for night
2. Go to bed
3. Destroy the bed
4. Place a lot of lava around the place where the bed was
5. Die

You will respawn where the bed was. The bed is gone, but you still respawn in the death trap.
You're now literally in hell and you suffer eternal damnation, i.e. you die and respawn, and die, and respawn, for all eternity, with no chance of escaping.
Of course, you can be creative and try any other inescapable death trap, i.e. deadly drop, a locked room full of water, and whatnot. Or you could place obsidian all over the place, making it even more annoying.

**Comment by Fixer-007** [comment]
Yeah, it is weird, if bed is destroyed, you should lose your spawn point :)

**Comment by paramat** [comment]
>  if bed is destroyed, you should lose your spawn point

I'm surprised this doesn't already happen.
Can other players destroy a bed that is another player's spawn point? If so this is more urgent.

**Comment by jastevenson303** [comment]
oh dear.  there is no protection in stock mtg.

**Comment by DS-Minetest** [comment]
This doesn't look hard to fix.

>Ps. if there is protection, it can prohibit others to use another's bed, and/or to prohibit another's ability to use your bed as respawn position.

This is already done:
https://github.com/minetest/minetest_game/blob/0291c6b2107de9f270b24ed22889a597033c52bd/mods/beds/spawns.lua#L57-L60

**Comment by paramat** [comment]
> if bed is destroyed, you should lose your spawn point

I now disagree with this and the solution in #2357 , see my comment there for why.
