### ISSUE TITLE
Mushrooms glow in the dark

### ISSUE THREAD

**Issue by LoneWolfHT** [minetest/minetest_game#2303]
I haven't heard of any mushrooms that glow in the dark
![image](https://user-images.githubusercontent.com/28972859/52315974-43ac0880-296e-11e9-8bf0-b3ea9c7dc86d.png)

**Comment by NathanSalapat** [comment]
They don't. Not in the dev build and most recent code for Minetest_game. Must be a mod thing.

**Comment by benrob0329** [comment]
bio-luminescent plants in caves would be a nice addition though.

**Comment by LoneWolfHT** [comment]
Hmm. Might be caverealms. I though they registered their own mushrooms though

**Comment by LoneWolfHT** [comment]
Yeah, looks like it's caverealms. Next time I'll make sure the 'bug' appears in unmodded MTG too
