### ISSUE TITLE
Info on the need for can_dig() check when rotating nodes

### ISSUE THREAD

**Issue by entuland** [minetest/minetest_game#2305]
I'm not sure about the actual need of this check here:
https://github.com/minetest/minetest_game/blob/ad6c2cf0352e6e27e09a72334a97044454ea486a/mods/screwdriver/init.lua#L127-L129

The above check prevents players from rotating nodes such as filled chests, which could be rotated just fine if it weren't for that conditional.

Is there any node I should avoid rotating even though all other checks pass, or should I stick to check can_dig() as well and eventually add exceptions for nodes that I know to be fine?

I'm using the same checks in my own https://github.com/entuland/rhotator screwdriver and as such my tools are prevented from rotating nodes which at a first glance could be rotated without any problem.

EDIT: Code was added in https://github.com/minetest/minetest_game/commit/697b39d40dfe7a36b4487ddbb0ba3eb758df4714

**Comment by HybridDog** [comment]
You could check for a `can_rotate` callback and if it is present, use it instead of `can_dig`.

**Comment by entuland** [comment]
The question there is actually if checking can_dig() is important for some reason I ignore - the very default screwdriver mod runs both checks, and being part of the core, I assume it's doing that for a reason.

In my rhotator mod I'm planning to do exactly what you suggest - bypass can_dig() if can_rotate() is present instead. I just don't feel confident doing so without a full understanding of how that stuff works.

**Comment by HybridDog** [comment]
Mod creators add the can_dig function to nodes to disallow digging it under certain circumstances, for example a can_dig in the chest node definition can prevent digging the chest if it is not empty. https://dev.minetest.net/Player-World_Interaction
If a mod creator adds can_rotate to the node definition, he/she knows that this function is used to test if the node can be rotated. He/She probably would not add a can_rotate if can_dig suffices to test whether a node can be rotated. Therefore I think that bypassing can_dig is the right decision.

**Comment by entuland** [comment]
Sorry, I'm still confused, and I realize my previous message didn't expose my standing point: I plan to ignore can_dig() altogether when rotating nodes.

The default chests don't have any on_rotate(), but have a can_dig().

The default screwdriver cannot rotate filled chests because of can_dig() preventing it.

The question, posed in a different way, is: why should anyone ever worry about can_dig() when rotating nodes? 

We're not digging it, we're just rotating it, but that's just a logical reasoning. My question is whether there is any traceable technical need for that.

**Comment by HybridDog** [comment]
> My question is whether there is any traceable technical need for that.

If a cable node is connected to another cable node, and the player is not allowed to dig the cable without a special tool, he/she should also not be able to rotate the cable, which makes it look broken. (assuming the mod uses param2 for the cable rotation and not the connected_nodebox drawtype)

**Comment by entuland** [comment]
Okay, but the case you're mentioning looks more like a situation where the problem is the mod providing the cable failing to properly set on_rotate() to false or something.

Besides, I believe that any mod providing any cable (I guess you're referring to Technic or something) isn't part of of core.

I'm really only concerned in any technical reason behind using on_dig() to prevent rotation within the core "design", so to speak.

For instance, I know for sure that the NodeBreaker from Pipeworks (assuming I recall the mod name and node name properly) used to provide an on_rotate() that allowed the default screwdriver to rotate them, but the way that on_rotate() callback was implemented made the NodeBreaker lose the tool the player put in its inventory (it used set_node() instead of swap_node() or something like that, losing the node metadata). That case was a bug in the mod implementing on_rotate() and has been fixed by now (at least in the official repo, as far as I can tell).

My main point in yet another way: if the "official" stand on can_dig() is that it shouldn't be used to prevent rotation, but expects mods to use on_rotate() instead, then this should be made clear by removing such check from the default screwdriver, or at least by openly stating that interpretation, so that other types of screwdrivers (such as mine) can properly rely on the intended use of the various callbacks.

**Comment by HybridDog** [comment]
> Okay, but the case you're mentioning looks more like a situation where the problem is the mod providing the cable failing to properly set on_rotate() to false or something.

I removed the comment because it was a bad example.

> I'm really only concerned in any technical reason behind using on_dig() to prevent rotation within the core "design", so to speak.

If a mod adds a node which must not be changed by a player, e.g. a bedrock node, and this node has a rotation (maybe bedrock chair), then the player should also not be able to rotate this node. To implement such an immutable node, the can_dig function is used. As far as I know, this is the reason for using can_dig.

**Comment by entuland** [comment]
> > Okay, but the case you're mentioning looks more like a situation where the problem is the mod providing the cable failing to properly set on_rotate() to false or something.
> 
> I removed the comment because it was a bad example.

No problem, I edited my previous post accordingly, it still fits cause it let me elaborate better on the two ways this question of mine could be looked at.

> > I'm really only concerned in any technical reason behind using on_dig() to prevent rotation within the core "design", so to speak.
> 
> If a mod adds a node which must not be changed by a player, e.g. a bedrock node, and this node has a rotation (maybe bedrock chair), then the player should also not be able to rotate this node. To implement such an immutable node, the can_dig function is used. As far as I know, this is the reason for using can_dig.

Still lost there. If that mod implements a node that cannot be dug and cannot be rotated, why should that mod only rely on can_dig() and not set on_rotate() to false?

I understand that the API and the core code can be interpreted or misinterpreted in various ways by mod creators and exactly for that reason I'd really like an official reply from the core designers to clarify this.

**Comment by entuland** [comment]
I see, if that's the only reason to stick with can_dig() losing the usefulness of being able to rotate perfectly valid nodes such as filled chests, then I'll remove the check for can_dig() from my own screwdriver and I suggest doing the same for the default one, 4 years should be more than enough to get rid of such burden.

Thanks for the clarification.

**Comment by paramat** [comment]
> Still lost there. If that mod implements a node that cannot be dug and cannot be rotated, why should that mod only rely on can_dig() and not set on_rotate() to false?

Maybe because can_dig is an engine thing, on_rotate is part of an API specific to the screwdriver mod used in MTGame.

However, i cannot remember seeing any node still using 'can_dig', it sohuld probably use 'diggable = false' instead. This section of code could perhaps be removed.
What do other core devs think?

**Comment by paramat** [comment]
This code was added in https://github.com/minetest/minetest_game/commit/697b39d40dfe7a36b4487ddbb0ba3eb758df4714
See comments in PR #375
"I'd like to see a some priv being required in order to use the screwdriver. It is a dangerous tools that can open steel doors and wipe chests inventories."
"added a fix for opening steel doors (by checking can_dig())"

**Comment by entuland** [comment]
Sorry, missed the notification about the messages on January.

I'll keep the check in place for the time being, it would be nice to have a core function to support scenarios like this where special nodes like chests can be rotated and not be dug, but that would be a feature request.

Thanks for the additional details.
