### ISSUE TITLE
Some recipes use default:stick instead of group:stick

### ISSUE THREAD

**Issue by FaceDeer** [minetest/minetest_game#2306]
There are several places where a default:stick is a required ingredient rather than group:stick:
- map:mapping_kit
- doors.register_fencegate registers recipes for all closed gates using default:stick
- fireflies:bug_net

Looks like a batch of fixes like this was done a while back in issue #284, these must be newer mods.

Additionally, it'd be nice if basic item types such as farming:cotton, farming:straw, default:clay_lump, default:ice, and so forth, could have generic groups corresponding to them so that mods using the default minetest game as a base could get into better practice defining recipe inputs by group. If this is something that would be welcomed I could put together a pull request adding a bunch.

**Comment by paramat** [comment]
Hmm why do we have group:stick when we only have 1 type of stick?

**Comment by Ezhh** [comment]
I support more use of groups where possible/reasonable because, as you say, it's better practice for mods to use groups in recipes when they can.

**Comment by paramat** [comment]
#2337 merged.

**Comment by paramat** [comment]
https://github.com/minetest/minetest_game/blob/24900f7da571f9851e50be35753c091f11b7be1e/mods/map/README.txt#L23
^ I forgot this.
https://github.com/minetest/minetest_game/blob/bae58b38067ffec52eb3c3c67d5a2f71190c22e8/mods/doors/init.lua#L781
https://github.com/minetest/minetest_game/blob/ccf03ea404181affeb355b05b57b34c422918cc8/mods/fireflies/init.lua#L116
