### ISSUE TITLE
Kelp selectionbox is smaller than the kelp

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#2307]
How to reproduce:

1. Place some kelp
2. Hover it

Expected:
Selectionbox is about the same size as the kelp.

Actual:
Selectionbox is often much smaller (namely: much shorter) than the actual visible kelp. It appears the selectionbox is of constant height, while the kelp plant might vary in height.

I am not sure if this is actually an MTG issue, or a Minetest issue.

Minetest version: f5bdc04ab5b47bd094ba0ced5f086e8fe6b12298
MTG version: 6b2887e3bfc0e8db1d8149bc95039af43922ffc6

**Comment by Wuzzy2** [comment]
OK, it seems to be an engine curiosity.

The height of `plantlike_rooted` depends on `param2`, but the selection box size is constant and ignores the `param2` completely.

**Comment by Ezhh** [comment]
@Wuzzy2 Yes, this is an engine issue. When deciding the height for the kelp selection box I made it appropriate for the lowest height because a selection box higher the the visible node just looked too weird.
