### ISSUE TITLE
Sea plants (kelp, rooted corals) are missing sounds

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#2308]
There are no footstep, dug or placement sounds for the “base node” of kelp, cyan coral, green coral and magenta coral.

**Comment by paramat** [comment]
Will fix.

**Comment by paramat** [comment]
Kelp should have a sand sound for footstep, as you walk on the base cube, but dig/dug/place should be plant sounds as only the kelp itself is obtained.
Similarly for corals: Footstep as coral skeleton, others as the coral above.

**Comment by paramat** [comment]
Odd, i'm getting a dig sound from kelp but no sounds are defined for it?

**Comment by Wuzzy2** [comment]
Yes, me, too.

**Comment by paramat** [comment]
Oh, the sound comes from the group 'snappy' for both kelp and coral.

**Comment by paramat** [comment]
PR #2311
