### ISSUE TITLE
Optional prospector map for radar mode (in survival mode)

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#2315]
~Right now acquiring map gets you all modes of minimap operation, including cave view, that is too cheaty and OP.~

What I see:
* ~Remove cave view when carrying map, allow surface only~
* Add prospector map, will allow cave viewing in minimap, with ridiculously hard recipe like 9 rare individual items from many biomes, add ability for server owners to disable cave view entirely

EDIT by paramat: Crossed out untrue or invalid text.

**Comment by paramat** [comment]
Radar isn't enabled in survival mode, only in creative.
A while back i planned to only allow radar in survival mode after crafting a magical item (all-seeing eye thing).

**Comment by Fixer-007** [comment]
>Radar isn't enabled in survival mode, only in creative 

You sure? I've create world in creative, gave myself a map, then switched back to survival, minimap still has radar mode.

**Comment by paramat** [comment]
Using '/grantme all' will give the creative priv to the player, which will enable radar, maybe that's why?

**Comment by Fixer-007** [comment]
I was not using /grantme all, just entered world in creative mode, took map from creative inv list reexited with survival mode.

**Comment by paramat** [comment]
Confirmed in singleplayer.
When the creative setting is changed in the menu, 'creative_mode = true' in minetest.conf does not update until you completely restart MT. However, even once it updates, minimap radar is still usable, and i do not have 'creative' priv. Odd.

**Comment by paramat** [comment]
https://github.com/minetest/minetest_game/blob/196f206d3e0943a55dffa922acd144dd7f53f025/mods/map/init.lua#L15-L17
Assuming the cache correctly gets the correct setting, it may be `creative.is_enabled_for(player:get_player_name()` causing the problem.

**Comment by paramat** [comment]
Nope `local creative_enabled = creative_mode_cache` doesn't fix it either.

**Comment by paramat** [comment]
Printing the value of `creative_enabled` shows it has the correct value, so must be a problem with `player:hud_set_flags()`

**Comment by paramat** [comment]
If i start a survival world, grant myself 'give', give myself a mapping kit, revoke 'give' from myself, i can still use radar.

**Comment by paramat** [comment]
```
function map.update_hud_flags(player)
	local creative_enabled =
		(creative and creative.is_enabled_for(player:get_player_name())) or
		creative_mode_cache

	if creative_enabled then
		print("creative_enabled == true")
	else
		print("creative_enabled == false")
	end

	local minimap_enabled = creative_enabled or
		player:get_inventory():contains_item("main", "map:mapping_kit")
	local radar_enabled = creative_enabled

	player:hud_set_flags({
		minimap = minimap_enabled,
		minimap_radar = radar_enabled
	})

	local flags = player:hud_get_flags()
	if flags.minimap then
		print("minimap == true")
	else
		print("minimap == false")
	end
	if flags.minimap_radar then
		print("minimap_radar == true")
	else
		print("minimap_radar == false")
	end
end
```
Even though 'set flags' is setting 'false' for radar, get flags is showing that the hud flag 'minimap_radar' is true.

**Comment by paramat** [comment]
Behaves the same in a locally hosted multiplayer server.

**Comment by paramat** [comment]
Bug fixed in engine by https://github.com/minetest/minetest/commit/1942660955bc3684a60d527e2fafa0ec3e02dd54
