### ISSUE TITLE
Unlocking map zoom levels

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#2316]
Currently, the mapping kit unlocks all zoom levels of the minimap. This may be a bit too fast and OP.

The first fact: The more “zoomed out” your minimap is, the more powerful it is, because you can see further on the minimap. Therefore, the lowest zoom level (×1) must be reserved for the highest tier of items.

I have a suggestion:

Add multiple map items. The first and easiest one grants access the the highest zoom level only (currently ×4).
Then there are map items at higher tiers which grant access to lower and lower zoom levels. Crafting them will require exponentially more items.
The final map would grant access to all zoom levels.

See also: #2315

**Comment by paramat** [comment]
I don't think the engine can control map levels using `hud_set_flags()` yet.

**Comment by Extex101** [comment]
Minetest's first progressive aspect....
