### ISSUE TITLE
Player can sleep in occupied bed

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#2318]
You can sleep in a bed that is occupied by another player.

Version: 0.4.17.1.

**Comment by paramat** [comment]
Maybe fixed by #2125 ?

**Comment by paramat** [comment]
#2125 replaced by #2327 which is merged.
This bug needs testing to see if still present.

**Comment by An0n3m0us** [comment]
Tested; still possible to sleep in an occupied bed.
