### ISSUE TITLE
Some dropped items sit in ground

### ISSUE THREAD

**Issue by NathanSalapat** [minetest/minetest_game#2320]
Noticed this when digging a tree, saplings and apples sit a few pixels below the ground, other items display fully about ground. It looks like nodes display correctly, and craft items are drawn a pixel too low.

![screenshot_20190222_075022](https://user-images.githubusercontent.com/8930456/53246584-bc051000-3676-11e9-90e4-81321086ee07.png)

![screenshot_20190222_075422](https://user-images.githubusercontent.com/8930456/53246741-228a2e00-3677-11e9-8edc-cb9cc3447857.png)

**Comment by paramat** [comment]
Engine issue to do with calculated collision box size of item entities.

**Comment by SmallJoker** [comment]
Issue within builtin. There seems to be a scaling mismatch when using the the `wielditem` entity draw type for different node draw types.
This issue belongs to minetest/minetest.
