### ISSUE TITLE
Make screwdriver-rotating of placed nodes a natural ability

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2321]
I remember this was discussed somewhere.
It seems to me that the ability to rotate a node any way you want should be a natural ability, not something that requires the creation of a steel ingot (a fairly developed stage in game progress) and the crafting of a tool.
Stair and slab nodes can already be rotated upside down on placement without a special tool, but the other rotations of them require the screwdriver.

Not sure how to implement this though.
Items seem out of place in the engine so i'm not sure if rotation ability can be moved into the engine, or how to do that.
~Maybe at first in MTG we can simply use the 'give initial stuff' API to give players a screwdriver?~
EDIT:
Suggestions:
Make the screwdriver mod give a screwdriver to new players.
Perhaps disable wear for the screwdriver, as this should be a natural ability, which the screwdriver item acts as a symbol for.

**Comment by Fixer-007** [comment]
I would rather keep screwdriver in game, it is used all over the place in mods (including in --)

**Comment by paramat** [comment]
Ok yes it will have to be kept in MTG whatever happens.

**Comment by Fixer-007** [comment]
But having ability to naturally place them will be nice as well.

**Comment by Ezhh** [comment]
> Maybe at first in MTG we can simply use the 'give initial stuff' API to give players a screwdriver?

Please let's not go this way. It's a lazy _fix_ for something that doesn't actually _need_ fixing (note: not the same as a better approach not being desirable) and not something everyone is going to want, but we'd be making this the default for so many things. It would also open up all kinds of awkwardness (if we start with screwdrivers, why not start with < many possible things > that are much more practical?)

The screwdriver exists in its current form because for gameplay purposes no one came up with something better. The way to improve it is actually coming up with something better, not just giving them out by default to new players.

**Comment by jastevenson303** [comment]
otoh give_initial_stuff is a setting that is by default disabled in mtg

**Comment by Ezhh** [comment]
Then it's pointless to have there regardless because it would not solve the issue. (I don't feel it's much of an issue at all either way.)

**Comment by paramat** [comment]
Yes using 'give initial stuff' for this is a little messy, although i think the API doesn't depend on that setting.

**Comment by benrob0329** [comment]
Having the placement rules allow for all rotations (even if a little awkward in some circumstances) between holding and not holding shift would help immensely.

**Comment by Linuxdirk** [comment]
Maybe place according to orientation. When someone wants to rotate they need a screwdriver. Otherwise they need to mine the node and re-place it in the desired rotation.

**Comment by paramat** [comment]
I think the screwdriver mod should give a screwdriver to new players.
There's no reason why a player shouldn't be able to place a node in any rotation they want as an inherent ability, and this ability should really be given by the engine, so insisting on the smelting of steel before being able to create a screwdriver is rather harsh.

**Comment by Linuxdirk** [comment]
Maybe implement the screwdriver as regular tool, so it can be crafted from wood, stone, etc. Unrealistic? Absolutely. But fits to MTG logic like wooden pickaxes that can mine stone 🙂

**Comment by paramat** [comment]
Yes we may need a compromise solution as Ezhh may not want a screwdriver provided.

How about making it a wooden screwdriver, crafted from only sticks or wood?

**Comment by TumeniNodes** [comment]
Add a keybinding which switches the hand i to rotation mode and move the rotating code from the screwdriver to the hand

Done

**Comment by DS-Minetest** [comment]
Ripping out the node, drawing it and gluing it back to where it was before with just ones bare hands seems a little weird.
The rotation should normally done before placing. Something like a with-keys-rotatable ghosty node appearing client-side when you hold an item in your hand (or maybe while you hold the place button and sneak) would be nice, but that's an engine issue.

**Comment by paramat** [comment]
An engine solution may make the most sense, but will be complex and possibly cause problems with all the mods that work with the current screwdriver methods. I cannot face that, so i am proposing an imperfect but simple improvement.

**Comment by SmallJoker** [comment]
For now it would be totally fine to remove the wear out functionality. Giving it to all players is superfluous because it'll only be useful when you start building a serious house (after hours in-game probably).

**Comment by paramat** [comment]
I disagree about it being superfluous, as the first rotatable nodes can be crafted long before acquiring steel. Besides, this is about the principle of rotating as an inherent ability that is there from the start.

**Comment by paramat** [comment]
Closing due to #2710
