### ISSUE TITLE
Add some useful groups (tool types, mushroom)

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#2323]
As per discussion from <https://forum.minetest.net/viewtopic.php?f=5&t=22075&p=344407#p344407>, I propose to add some tool-related groups that will be useful for mods:

* `pickaxe=1`: For all pickaxe items
* `axe=1`: For all axe items
* `shovel=1`: For all shovel items
* `hoe=1`: For all hoe items
* `sword=1`: For all sword items

Justification: There are many many uses for these groups: In crafting, for achivements (e.g. “craft any pickaxe”) and whatnot.

Moreover, I also suggest:

* `mushroom=1`: For the fruit body of mushrooms (Red Mushroom, Brown Mushroom, but not huge mushroom blocks should they ever be added)

Justification:

> just because there are mods such as nsspf and mushrooms_redo that add mushrooms, and a universal reference ought to be available.

**Comment by Ezhh** [comment]
I'd like to see more use of groups for the same reason given above, and these all seem like perfectly reasonable ones to add.

**Comment by cx384** [comment]
I also would like to have this groups:
- `stone_with_ore=1`: For every stone with ore.

Justification: Item drop modifications like dropping the node or multiple ore drops. And many other things like quarrys, vein mine, ore detection, ...
- `sandstone=1`: For all sandstones (bricks and blocks included like group stone)

Justification: There is already a sand and stone group but sandstone belongs to none of them.

Groups for crystals, lumps, ingots and metals would be nice too, but I don't think they would worth it.

**Comment by cx384** [comment]
I also would like to have this groups:
- `stone_with_ore=1`: For every stone with ore.

Justification: Item drop modifications like dropping the node or multiple ore drops. And many other things like quarrys, vein mine, ore detection, ...
This would be a little bit like the spreading_dirt_type group.

- `sandstone=1`: For all sandstones (bricks and blocks included like group stone)

Justification: There is already a sand and stone group but sandstone belongs to none of them.

Groups for crystals, lumps, ingots and metals would be nice too, but I don't think they would worth it.

**Comment by HybridDog** [comment]
I'd like to have the `hot` and `melts` group. The snow mod uses them to test if an ice node should melt.
https://github.com/Splizard/minetest-mod-snow/blob/dc799f344f15ade2f8fb66cd6745dafb317c8515/src/abms.lua#L23
https://github.com/minetest/minetest_game/commit/60f6564c753494dcb8597ba8d67a4202cc8601c4

**Comment by paramat** [comment]
MTG doesn't have melting nodes, so the snow mod should code this itself by overriding nodedefs.
New groups should be useful for MTG, not added for optional mods, otherwise the bloat would be massive, with most of the bloat unused.

**Comment by Ezhh** [comment]
I support the ones wuzzy identified in the top post because I can imagine nice clear cut uses for them.  I am less sure about the others.

**Comment by An0n3m0us** [comment]
@paramat Should this be closed because of #2378?
