### ISSUE TITLE
Node formspec screws up if node got destroyed

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#2329]
If you look at the formspec of a node and the node is destroyed, your formspec screws up.

How to reproduce:

1. Place a furnace, vessels shelf or bookshelf
2. Place TNT right next to it
3. Ignite the TNT
4. Rightclick the other node to open the formspec
5. Wait for TNT to blow up

Expected:
The formspec node should be destroyed and the formspec be closed (since the node got destroyed).

Actual result:
The node is destroyed by TNT, but the formspec does not close properly. Instead, it screws up. You see a big gray empty rectangle on the screen. You can close it with Esc, however. It's not a critical bug, but it's ugly.

Note:
Does not affect chests and locked chests.
Is probably related to a known engine bug which I can't find right now.

**Comment by SmallJoker** [comment]
Such formspecs are bound to the node position and thus need a general fix in the engine.
