### ISSUE TITLE
Torch crashes when placed in protected area

### ISSUE THREAD

**Issue by LunaSquee** [minetest/minetest_game#2330]
The title says it all. Occured with minetest-protect mod.

```
13:48:30: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod '' in callback item_OnPlace(): ...netest/bin/../games/minetest_game/mods/default/torch.lua:62: attempt to index local 'itemstack' (a nil value) 
```

**Comment by cx384** [comment]
Well, it's probably a badly made protection mod, which doesn't handle on_place properly.
Which protection mod do you use?

**Comment by cx384** [comment]
Well, it's probably a badly made protection mod, which doesn't handle on_place properly.
Which one do you use?

**Comment by jastevenson303** [comment]
#2288

**Comment by LunaSquee** [comment]
Sorry I didn't have time to dig deeper, apparently Zeg9's protector is very old and shouldn't be used. I'm using redo now.
