### ISSUE TITLE
Move loot registration to individual mods

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest_game#2334]
Currently [loot.lua](https://github.com/minetest/minetest_game/blob/master/mods/dungeon_loot/loot.lua) contains lots of items from "foreign" mods that dungeon_loot does not (soft-)depend on.

Instead those mods should call `dungeon_loot.register` on their own to register loot.
affected: `default`, `bucket`, `vessels`, `farming`

**Comment by paramat** [comment]
This is causing errors when users remove certain mods.
