### ISSUE TITLE
Add emotes

### ISSUE THREAD

**Issue by Niwla23** [minetest/minetest_game#2336]
Whats about emotest like MC has?
https://www.youtube.com/watch?v=5Z57r0-n98k
Taht would be soooo cool for servers or for the Content Creators like me.

**Comment by paramat** [comment]
@sofar has coded something like this.

**Comment by Niwla23** [comment]
Can you link it pllease

**Comment by paramat** [comment]
https://forum.minetest.net/viewtopic.php?f=11&t=16374

**Comment by sofar** [comment]
It's not difficult. I made a version that did things like:

- shake head yes, no, "indian" yes (head nod sideways)
- wave
- point
- shrug
- freeze (hands up in the air)

It requires some consensus though, as everyone who provides a custom model like 3d armor now has to also make those animations. This is likely, for now, better done in mods until people settle on a format for the base model.

**Comment by benrob0329** [comment]
Would be nice to have a way of defining custom animations for models without having to manipulate the bones in Lua.

**Comment by sofar** [comment]
The animations are made in blender, not lua. I wouldn't ever want to do this in Lua. It would look bad, be horrible for latency, and probably buggy.

**Comment by benrob0329** [comment]
@sofar I feel you've brushed over most of my comment.
