### ISSUE TITLE
Use mod.conf and modpack.conf; remove corresponding deprecated files

### ISSUE THREAD

**Issue by ClobberXD** [minetest/minetest_game#2340]
I hope this isn't a duplicate issue, but I don't see `mod.conf` or `modpack.conf` being used in MTG. Being the official game bundled with Minetest, shouldn't this have been the first to adopt the new, official approach? Is there a specific reason for not doing this yet?

**Comment by paramat** [comment]
Heh, no reason, this should be done yes.

**Comment by rubenwardy** [comment]
Would be good to make a script for this
