### ISSUE TITLE
beds can not be dug

### ISSUE THREAD

**Issue by JamesTobin** [minetest/minetest_game#2341]
I'm running a server on Minetest 5.1.0-dev-426bdba7 with minetest_game master. There are a problem with both the simple and fancy beds, as people are able to set them, but not to break them at all. The bed starts to break but puts itself back after being fully broken, similar effect to breaking a block in a protected area.

**Comment by paramat** [comment]
Confirmed on a local server, damage on, survival mode. Once a player places and lies on a bed (even without a night skip) they then cannot dig the bed.
@sofar maybe https://github.com/minetest/minetest_game/commit/b853c8a5097a9f88a27f8005e41fb08697e1bf02 which was after MTG 5.0.0.

**Comment by paramat** [comment]
Confirmed bed bug not in 5.0.0.

**Comment by JamesTobin** [comment]
Don't let the bed bugs bite™
😂

**Comment by pgimeno** [comment]
This should squash'em.

```diff
diff --git a/mods/beds/functions.lua b/mods/beds/functions.lua
index 64c6288..ae632a9 100644
--- a/mods/beds/functions.lua
+++ b/mods/beds/functions.lua
@@ -59,6 +59,7 @@ local function lay_down(player, pos, bed_pos, state, skip)
        if state ~= nil and not state then
                local p = beds.pos[name] or nil
                beds.player[name] = nil
+               beds.bed_position[name] = nil
                -- skip here to prevent sending player specific changes (used for leaving players)
                if skip then
                        return
```

**Comment by paramat** [comment]
IRC
http://irc.minetest.net/minetest-dev/2019-03-21#i_5516431
http://irc.minetest.net/minetest-dev/2019-03-22#i_5516560
sofar approves the fix.

**Comment by JamesTobin** [comment]
Yay

**Comment by fwhcat** [comment]
Tested on my server and the fix works indeed.

**Comment by paramat** [comment]
I'll merge the fix soon.

**Comment by paramat** [comment]
PR #2345
