### ISSUE TITLE
Potential crash in boats mod

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#2342]
`mods/boats/init.lua`:

```
                 minetest.after(0.2, function()
                         player_api.set_animation(clicker, "sit" , 30)
                 end)
```
If `clicker` is gone, server goes BOOM.

Version 5.0.0.

**Comment by paramat** [comment]
Has anyone actually tested if crashes occur? I intend to but can't get a local server working for some reason, the client just times out.

**Comment by An0n3m0us** [comment]
How would one go about testing this? If I can have some information, I might be able to try it out.

**Comment by paramat** [comment]
I have managed to get local server functional again, so will test.

**Comment by paramat** [comment]
I tested for problems by setting the detach and attach delays to 5s, running a local server, joining the server as another player, then leaving the server immediately after a detach or an attach.
No crash, no issues, i do not know why.
I did not test for the delayed `self.object:remove()` as a comment in the PR suggests that is not needed.
So, close issue and PR? @SmallJoker 

This suspected bug was useful to know, but please try to reproduce a bug if reporting one, it would have saved a lot of time.

**Comment by paramat** [comment]
Closing until actually reproduced.
