### ISSUE TITLE
Fast tools repair

### ISSUE THREAD

**Issue by trukoil** [minetest/minetest_game#235]
An enhancement that could help in firsts phases of the game: adding a recipe to repair damaged tools, made with the tool in the center and the tool's ingot over it, that gives a new, repaired tool.

Scheme:
T = tool
O = ingot
X = nothing

[X][O][X]
[X][T][X]
[X][X][X]

**Comment by C1ffisme** [comment]
Maybe we could add anvils to minetest and do what minecraft does. Or what about a repair shop that can repair tools if you have the resources to repair?

**Comment by C1ffisme** [comment]
Okay, this issue is over a year old. I request that it be closed.

**Comment by FreeLikeGNU** [comment]
or make torches from wood and coal burnout and get removed from the game server after some time?

**Comment by paramat** [comment]
-1 because of this:
> A stone pickaxe is made from stone and 2 sticks, and its utility is to mine stone. So it gives a lot of stone, and we can repair it from one of these cobblestones

@trukoil tagging you because this PR is old, do you still want to submit this or close it?

**Comment by paramat** [comment]
Closing because no reply.
