### ISSUE TITLE
Can't search by translated names in creative

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest_game#2367]
In creative it is not possible to search by translated item names. This can easily be fixed, however - just cache all possible translations and always search in the one matching the player using creative.

**Comment by SmallJoker** [comment]
Minetest core issue https://github.com/minetest/minetest/issues/8398

**Comment by rubenwardy** [comment]
This is still an issue on this repo, but does need an engine changed. Locked to avoid discussion which should probably be on the engine repo

**Comment by Wuzzy2** [comment]
The required engine change has been done. #9733
