### ISSUE TITLE
Mouse buttons not toggled or can get stuck

### ISSUE THREAD

**Issue by An0n3m0us** [minetest/minetest_game#2379]
Sometimes LMB doesn't get recognized:
https://my.pcloud.com/publink/show?code=XZU2DA7Z9nQExBjXNq7lPvhzUqYsqLIgxfJk
For a proper example, see: #2375 
I hit the purple butterfly more than once and it didn't die, even though it was supposed to.

For RMB, it can sometimes get stuck on true/false or not be recognized at all:
https://my.pcloud.com/publink/show?code=XZJWDA7ZVgwlei24JKYLc8zEvUzM9hb5WAvX

**Comment by paramat** [comment]
Please open an issue in the engine.
