### ISSUE TITLE
Large Cactus Seedling Destroys Underlying Sand Block

### ISSUE THREAD

**Issue by benrob0329** [minetest/minetest_game#2385]
When you plant a large cactus seedling atop a single piece of sand, the sand will be pulverized once the cactus grows.

**Comment by paramat** [comment]
You mean the sand is replaced by a cactus node? That's expected, just like a tree, it's the cactus root.

**Comment by benrob0329** [comment]
Trees don't, and should not do that. This breaks farms and destroys sand in the process, its bad behavior.

**Comment by paramat** [comment]
Sorry, i see. Sapling-grown trees only force-place the node that replaces the sapling, i forgot, was thinking about mapgen trees. Large cactus should do the same. Will fix.

**Comment by paramat** [comment]
#2389
