### ISSUE TITLE
Dungeon loot mod should not use mapgen aliases to find walls

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2391]
The dungeon node mapgen aliases are probably going to be removed from the engine in https://github.com/minetest/minetest/pull/8594
Also, dungeon nodes are no longer determined by the mapgen aliases, they can be defined in biome definitions. If dungeon nodes are altered in a biome definition this mod will no longer detect dungeons in desert or sandstone desert.
It's better to directly detect biome using the new 'biome at point' functions.

It's probably good enough to just consider a non-air node as wall.

**Comment by sfan5** [comment]
How does detection of the dungeon type work then?

**Comment by paramat** [comment]
```
	local mapping = {
		[wall_ss] = "sandstone",
		[wall_ds] = "desert"
	}
	return {
		walls = ret,
		size = {x=mindist.x*2, z=mindist.z*2},
		type = mapping[wallnode] or "normal"
	}
```
I see, i forgot that dungeon type was detected as normal, sandstone or desert and that determines loot type.

Instead we can use the new 'get biome at point' to determine the biome.

**Comment by paramat** [comment]
I'll work on this soon if no objections.

**Comment by paramat** [comment]
PR #2398

**Comment by paramat** [comment]
Issue is invalid, see closed PR for why.
