### ISSUE TITLE
Minetest_game 5.0.1 and 5.1: screwdriver rotates chests, deleting items

### ISSUE THREAD

**Issue by JamesTobin** [minetest/minetest_game#2402]
I had a frustrated user in a 5.1 minetest server with minetest_game 5.1. The issue was: hitting a chest with a screwdriver would rotate it, and all the items in the chest would be gone. I tried swtiching to 5.0.1 subgame but got the same issue. I also tried a different 5.1 minetest server and saw the same issue. Finally, it tested in vanilla 5.1 singleplayer with 5.1 subgame, and the same issue occured. 

To prevent more people from losing lots of items, I suggest patching 5.1 and 5.0.1 subgames to prevent chests from rotating or at least prevent items from being destroyed when it is rotated.

**Comment by DS-Minetest** [comment]
I can't reproduce. I'm only able to rotate empty chests.

**Comment by SmallJoker** [comment]
Are you sure it's really vanialla, without any changes in MTG?

**Comment by JamesTobin** [comment]
I see that i didnt actually try putting items in the chest in vanilla.

Survivalworks ng is using vanilla minetest game but has other mods. in that server it will delete items

Is it supposed to be possible to rotate chests?

**Comment by paramat** [comment]
Empty ones yes.

**Comment by paramat** [comment]
Can't reproduce, can't rotate chests or lockable chests if items are contained.
