### ISSUE TITLE
New 'Dry dirt' node and texture for savanna

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2405]
Do an image search for savanna and see. The dirt is dry, lighter in colour, colour is slightly sandy or reddish, texture is finer and a little sandy. The current temperate, damp, rich soil is not very suitable.
If anyone works on a texture for this please post it here. Then i can do all the mapgen coding stuff.

I'm also thinking of making savanna have patches of bare dry dirt instead of complete dry grass coverage. This means that automatic dry grass spreading will have to be disabled, but this seems suitable for savanna. I can imagine grass spreading over rich fertile soil but it wouldn't necessarily do so completely over dry dirt.

**Comment by paramat** [comment]
PR #2412

**Comment by TumeniNodes** [comment]
> ~~Screenshots in #2412~~
> TumeniNodes has been working on this and has made a texture, but we are waiting for more core dev input on the concept before proceeding.
> @Ezhh

This is the newest PR https://github.com/minetest/minetest_game/pull/2422
@paramat 
@Ezhh 
@SmallJoker 
@rubenwardy 
@sofar 
(just knockin on everyone's door I can think of this time)

**Comment by paramat** [comment]
#2422 merged.

**Comment by paramat** [comment]
#2426 merged.
