### ISSUE TITLE
New wooden ladder texture.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest_game#2424]
I`ve just made a new texture of the wooden ladder:
![image](http://www.imageup.ru/img281/3433943/screenshot_20190723_213757.jpg)

Download:
https://ufile.io/i9w5gpay

**Comment by DS-Minetest** [comment]
I don't like the current wooden ladder texture (and therefor use a texture pack to get back the old texture, but darkened), it looks so minecrafty. Ergo, I'm :+1: for this.

**Comment by paramat** [comment]
The image in the first post doesn't display correctly for me, i see either blank white or this:

![687474703a2f2f7777772e696d61676575702e72752f696d673238312f333433333934332f73637265656e73686f745f32303139303732335f3231333735372e6a7067](https://user-images.githubusercontent.com/3686677/61831222-1e9c4b00-ae65-11e9-93b4-c4395ddee148.jpeg)

Anyone else?

An image in the ladder model issue didn't display correctly for me either.

**Comment by paramat** [comment]
New texture:

![default_ladder_wood128](https://user-images.githubusercontent.com/3686677/61831518-fb25d000-ae65-11e9-9cb5-238cb2b74931.png)

![default_ladder_wood_profile](https://user-images.githubusercontent.com/3686677/61831583-1f81ac80-ae66-11e9-9e81-abcf0330809b.png)

**Comment by paramat** [comment]
Anyway, assuming the issues are sorted, i don't support changing the texture to one that removes the side-projections :-1: 
The current texture is high quality.
Being an old-looking ladder design (rungs roughly attached to uprights) makes it suitable for many old-world uses like pirate ships, castles etc. For a modern ladder we have the steel one.
Removing the side-projections makes it look very similar to the steel ladder.

Since it's a case of personal taste, i think it's best you use a texture pack.
Sorry to disapprove, and thanks for contributing.

**Comment by SmallJoker** [comment]
I also prefer the current texture over this proposed one. The texture borders are not so suited for tiling the texture due to the clear node borders. Maybe that's intended, but it does not look too great. Also the old side "bumps" looked quite good as a variation to the normal, simple and straight ladder.

**Comment by DS-Minetest** [comment]
Actually, it's a bit off how the rungs are currently connected to the poles. From both sides of the ladder, the rungs look as if they were behind the poles, which suggests that the rungs were sticked through the poles.
It does happen that rungs are sticked into the poles:
![](https://live.staticflickr.com/1261/1383886766_3e43c3fc68.jpg)
(["Red Ladders" by JenWaller (CC BY-NC-SA 2.0)](https://search.creativecommons.org/photos/2985c9a4-7636-4745-88bf-43f613ebc6c1))
But putting them through the poles is much more unneeded effort.
The side-projections would only make sense in a design like this:
![](https://live.staticflickr.com/6191/6044826156_aa5b18171a_b.jpg)
(["Ladder to loft" by jamesabbott1963 (CC BY-SA 2.0)](https://search.creativecommons.org/photos/8f6eca6b-0b60-434a-908b-4ff8484951cf))
This, however, would need something to hold it together, like nails, which is not used in the crafting recipe.

Btw. here's the PR that introduced the current texture: #332

>For a modern ladder we have the steel one.

It's new to me that modern houses would forgo wooden furniture. :P

**Comment by benrob0329** [comment]
Usually things like nails, saws, glue, etc are all implied and not part of the recipe, after all we dont require a workshop to craft literally anything.

**Comment by LoneWolfHT** [comment]
> This, however, would need something to hold it together, like nails, which is not used in the crafting recipe.

You would need a drill for the holes if you went the other way around. Not really a problem IMO

**Comment by LoneWolfHT** [comment]
Once the contrast is fixed then :+1:
![image](https://user-images.githubusercontent.com/28972859/61997349-3df9ca80-b055-11e9-933d-3cd4715919a9.png)

**Comment by TumeniNodes** [comment]
I prefer the current texture, though it would be nice if ladders could be rotated to double as a sort of picket fence (which is off topic, sorry)

But, if some want nails added to the current texture, I can do that in a jiffy xD

**Comment by Linuxdirk** [comment]
> The current texture is high quality.

Actually yes. The proposed new texture looks ugly as hell. Sorry. The default texture is absolutely fine.

**Comment by DS-Minetest** [comment]
>ladders could be rotated to double as a sort of picket fence

I agree that the current texture looks more like a rotated picket fence than a ladder.

Actually, the color changes at top and bottom make the new texture look very interesting.
The new texture is premium quality. :P

**Comment by Andrey2470T** [comment]
Well, I agree probably my texture looks like not very good, especially a sharp contrast occurs to aligned upright ladders. That`s why I suggest new texture (the light scatters under the right angle throughout the ladder):
![image](http://www.imageup.ru/img21/3439581/screenshot_20190730_204823.jpg)

**Comment by LoneWolfHT** [comment]
:+1:

**Comment by Andrey2470T** [comment]
I think all nice, at least with light spreading.

**Comment by Andrey2470T** [comment]
A little bit darkened:
![image](http://www.imageup.ru/img21/3439584/screenshot_20190730_210758.jpg)

**Comment by DS-Minetest** [comment]
That newest ladder texture is too repetitive (eg. the rungs all look exactly the same). Also the difference in brightness is too much. And the saturation is too low.

**Comment by Andrey2470T** [comment]
It doesn`t look like repetitive as you can see all rungs change their colors along entire their lengths. And I also don`t see big difference in the brightness.

**Comment by DS-Minetest** [comment]
Here's what I meant:
![687474703a2f2f7777772e696d61676575702e72752f696d6732312f333433393538342f73637265656e73686f745f32303139303733305f3231303735382e6a7067](https://user-images.githubusercontent.com/7613443/62242102-bf958380-b3da-11e9-85b5-a8230bd1579c.png)

**Comment by paramat** [comment]
The new contribution is 'ok', but not as high quality as the current texture, certainly not an improvement.
2 core devs want to keep the side bumps.
Thanks, but i suggest using this in your own texture pack.
