### ISSUE TITLE
dig_immediate = 2 nodes dig slowly in creative mode

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2427]
I'm using creative mod in a simple game of my own.
I have some nodes that have group `dig_immediate = 2`, with or without other dig groups, to be diggable by hand at moderate speed. In creative mode these nodes dig slowly.

To reproduce in MTG:
Alter sapling to change `dig_immediate' from 3 to 2:
```
	groups = {snappy = 2, dig_immediate = 2, flammable = 2,
		attached_node = 1, sapling = 1},
```
In creative mode, try digging a row of saplings.

I suspect this hasn't been noticed in MTG yet because the only `dig_immediate` nodes are value 3 which digs very fast.

Adding `dig_immediate = caps` to the hand redefinition doesn't seem to help.

Hmmm but then, 'dig immediate' suggests that only the value of 3 should be used to make it immediate. Using 'oddly breakable by hand' seems wrong for nodes that make sense to be diggable by hand.

**Comment by DS-Minetest** [comment]
TNT, unpowder, rails, bones and unknown nodes use `dig_immediate = 2`.

Anyway, the dig times of `dig_immediate` can't be changed in lua. See https://github.com/minetest/minetest/blob/bba4563d89b6708d75a4053c69873dff0d747538/src/tool.cpp#L175-L183.
>Group dig_immediate has fixed time and no wear

**Comment by paramat** [comment]
Thanks!

**Comment by paramat** [comment]
Thanks.
Ok so `dig_immediate = 3` should be used.

**Comment by DS-Minetest** [comment]
> Ok so it seems `dig_immediate = 3` should be used for those nodes you listed.

No, then digging those nodes would be as fast as digging torches.

**Comment by paramat** [comment]
Ah good point, i'm forgetting about dig speed in survival mode.
I'll test using 'oddly breakable by hand'.

**Comment by paramat** [comment]
Yes, `oddly_breakable_by_hand = 3,` is close to the same dig time and the only alternative.

Unknown nodes should probably be `dig_immediate = 3`, maybe gunpowder too.

**Comment by sfan5** [comment]
> `// Group dig_immediate has fixed time and no wear`

This is retarded, why does the engine not allow mods to override this?

**Comment by paramat** [comment]
I agree.

**Comment by TumeniNodes** [comment]
Some of this I can relate to, due to a version I have been working on for some time now which is strictly creative (for those who simply like to build)
Sometimes variations in dig times can throw you off, and become annoying (especially those unknown nodes)
Even in MTG, there should be a completely different setup for creative.
Creative should be viewed/treated as somewhat of an ingame editing mode.

**Comment by paramat** [comment]
Engine change done https://github.com/minetest/minetest/commit/3296952ae55231d601686b69c037ec1366381fc5
I'll make the necessary MTG changes.

**Comment by paramat** [comment]
PR #2433 merged.
