### ISSUE TITLE
Clean up use of 'gui_furnace_arrow_bg.png'

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2438]
This texture is stored in default and is of course used in the furnace code.
However it is also sloppily used in 2 places for the crafting arrow:
In `default.gui_survival_form` in default:
https://github.com/minetest/minetest_game/blob/a6a719967a4ec8d4aec332806532f78cf4c563de/mods/default/init.lua#L33
In `sfinv.register_page("sfinv:crafting", {` in sfinv:
https://github.com/minetest/minetest_game/blob/5b1d5819e5a9617832fba17db8da1a8d8fa690dc/mods/sfinv/init.lua#L9

Problems:

It is better to have a separate texture for the crafting arrow, to allow this to differ.
The furnace background arrow is designed to be used blended together with a foreground arrow, so it is highly likely it will need to differ from a crafting arrow.

In MTG, `default.gui_survival_form` requires the texture and is defined in default, furnace code is in default so the furnace arrow texture is in default. However, in other games the furnace textures are highly likely to be in a separate mod, as they should be, so `default.gui_survival_form` really shouldn't use the furnace arrow.

The current situation makes creating new games, by copying and modifying MTG code, more difficult (from experience).
I think that mods that are likely to be used mostly unmodified in other games, such as player_api, creative and sfinv, need to be more self-contained and not so reliant on default, to help people make new games. It would be best if new games can use creative and sfinv unmodified for easy updating of those mods.

MTG is too much coded as a collection of mods that are always used together, i think the mods need to be more self-contained, even if this creates some duplication.

Proposal and questions:

Add a separate crafting arrow texture to default.
~However, should it be added to sfinv as well?~ EDIT: Yes, in fact sfinv is the primary location (see comment below).
Why doesn't sfinv contain a crafting arrow texture to be more self-contained?
Why doesn't sfinv have some kind of dependency on default as it requires this texture?
Is it because the `sfinv:crafting` page is only opened by the creative mod, which already depends on default?
@rubenwardy i would appreciate your input on this.

I became aware of this issue through creating a very simple game and unravelling the structural mess of MTG to do so.
Once i know what is the best thing to do i can make a PR.

**Comment by TumeniNodes** [comment]
>MTG is too much coded as a collection of mods that are always used together, i think the mods need to be more self-contained, even if this creates some duplication.

When you open a discussion on this bit, I have some opinions I will definitely share.

**Comment by paramat** [comment]
LOL =)

Ok, `default.gui_survival_form` is actually only in default to support mods that use it, it has no other function in MTG.
So the crafting arrow in sfinv seems to be the primary location. I'm guessing the new crafting arrow texture should be there (but of course in default too as it is required in `default.gui_survival_form`).

**Comment by paramat** [comment]
PR #2439
