### ISSUE TITLE
Hotbar textures and code are out of place in player_api mod

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2444]
The setting of hotbar textures is out of place in player_api mod.
From player_api init.lua:
```
-- Update appearance when the player joins
minetest.register_on_joinplayer(function(player)
	player_api.player_attached[player:get_player_name()] = false
	player_api.set_model(player, "character.b3d")
	player:set_local_animation(
		{x = 0,   y = 79},
		{x = 168, y = 187},
		{x = 189, y = 198},
		{x = 200, y = 219},
		30
	)
	player:hud_set_hotbar_image("gui_hotbar.png")
	player:hud_set_hotbar_selected_image("gui_hotbar_selected.png")
end)
```
This function sets the model and animation, but then also sets the hotbar images, which are unrelated to the player_api mod.
These HUD textures belong in default mod together with the other HUD textures: 'bubble', 'heart', 'gui_hb_bg' (the hotbar background texture).
The code belongs together with `default.get_hotbar_bg` and the `GUI related stuff` here:
https://github.com/minetest/minetest_game/blob/4eadf806349e9acfc817db8cdcdc85bc879c1558/mods/default/init.lua#L11
There's even a `minetest.register_on_joinplayer` function present it can be moved to.

Looking at older MTG versions, it looks like this code is only here because it was here when all this code was part of default.
I'll make a PR soon to move it back into default ... and yes i know moving stuff into default is best avoided, but in this case it is the only proper place for this code.

Again i noticed this through working on a very simple game of my own, creating a logical mod structure, and removing this code due to it obviously being in the wrong place.
player_api is (along with creative and sfinv) a mod highly likely to be used in new games, so should only contain relevant content. A priority for this mod is being in a form usable in new games.

**Comment by TumeniNodes** [comment]
Shouldn't HUD be self contained as well?

**Comment by paramat** [comment]
As in, a separate mod? Probably, but as always the practicalities may limit what we can do.

**Comment by Linuxdirk** [comment]
The best place for the HUD is a HUD API that is independent from the games. All game-specific HUD should be done in a dedicated HUD mod used by the game.

Don't stick stuff in default. It is already too bloated and should be deprecated and disembled piece-by-piece inton individual mods and eventually being removed.

**Comment by paramat** [comment]
> It is already too bloated and should be deprecated and disembled piece-by-piece inton individual mods and eventually being removed.

Ideally yes, however, default may well be split up in future, for now, with the current structure, it is the only acceptable place for these textures and code.

**Comment by paramat** [comment]
And here's a second suggestion for player_api mod:

Remove the ancient 2D sprite player textures. They are highly unlikely to be needed by anything, and besides, this is MTG 5.0.0 so we can make some small breakages, and is a good timw to clean stuff up.

Removing these and the hotbar textures allows the textures folder to be removed.
We can also remove the code that applies the 2D sptrite player texture, simplifying the code.

**Comment by DS-Minetest** [comment]
I don't think that 2D players are really that uncommon.
Some subgames are not meant to be played in multiplayer and hence the player appearance doesn't really matter. (However, this is a bad argument, as such subgames don't have any real reason to use `player_api`, I think.)
What is more important is that there's not much code for 2D players. (I only found [this](https://github.com/minetest/minetest_game/blob/4eadf806349e9acfc817db8cdcdc85bc879c1558/mods/player_api/api.lua#L54-L60).) And removing this code wouldn't make the `player_api` code much simpler.
There are probably still some people somewhere somewhen, who would be displeased if this feature was removed.

**Comment by paramat** [comment]
2D players are very uncommon.
Removing unnecessary code is good however few lines it is.
Alternatively the code could be left in and textures removed, such that the fallback remains (if that is particularly useful) but players show up as coloured 'missing texture' rectangles.
> There are probably still some people somewhere somewhen, who would be displeased

This is always the case with any change, but it will be a very small number of people.

**Comment by paramat** [comment]
I discovered that these sprite textures should be present in the engine to result in a functional engine fallback https://github.com/minetest/minetest/pull/8823
This makes it more possible to remove the textues and code from player_api mod, because some kind of fallback will remain.

**Comment by paramat** [comment]
I changed my mind =D I won't try to remove the sprite code and textures.
Lying in bed this morning, i was thinking about how i dislike situations where the use of blender is a requirement for modding / game creation, so i realised i want to support non-model players like sprites. Also, i would like to add support for nodebox players too.
So my PR will just be for moving the hotbar stuff.
