### ISSUE TITLE
Discussion about adding rivers to MGflat (calm down)

### ISSUE THREAD

**Issue by TumeniNodes** [minetest/minetest_game#2446]
This is just to hopefully open a discussion.

I am proposing an idea which has been mentioned before... adding a river system to MGflat.

Already MGflat has options to use hills & lakes (which I love) but, adding rivers, or even just one wide, winding river right down the center of the map would make MGflat (imp&ho) EPIC! There _perfect_ building mapgen.

I propose a system similar to the ridges in MGv7, or something even easier to customize the settings.

I know there are some who greatly oppose this but, the fact is... it can be added as a setting (same as hills & lakes) and does not need to be used if people do not like it.
And with those two options mentioned, why not just go the full mile and add this one additional option to make this mapgen even better?
But this would a _very_ welcome change for me, and I am sure many other users.

If I had the means, I would gladly offer a bounty for this but sadly, some unforeseen events made my ability to do so atm (hopefully I can offer one some time in the near future though)

Making adjustments within MGv7, it is difficult to get just the right look & feel and leaves a lot of oddities in the landscape.

So I am looking for some non-hostile discussion regarding this request.

* I just realized perhaps this should have been put up in minetest

**Comment by benrob0329** [comment]
As someone who uses mgflat as a base for a Lua mapgen, a new default setting would break my game. **This is fine**, so as long as it's clearly documented as doing so; this way I can update my code accordingly.

**Comment by paramat** [comment]
Please open in engine issues.
