### ISSUE TITLE
Creative mod should 'override item', not re-register, the hand tool

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2455]
The 'creative' mod re-registers the hand tool of 'default' mod, but some of the fields do not need to be altered, for example 'wield_scale'.

I noticed a problem when experimenting with modifying the 'wield_scale' and the 'wieldhand' texture for the hand tool to make it appear as an entire arm. At first it didn't seem to work, then i realised i was in creative mode and the 'creative' mod had re-registered the hand tool, i would have needed to make the changes in 2 places unnecessarily.

Any known issues with using `minetest.override_item()` instead?
If no problems i will make a PR.

**Comment by TumeniNodes** [comment]
I never even thought of that, when I had the same problem about a year ago...
I'm gonna have to try that out

**Comment by DS-Minetest** [comment]
I guess creative is older than `minetest.override_item()`.

I'll leave [this](https://github.com/HybridDog/nether-pack/blob/870b6a9d476556271c34c805ab4a35078c6103d1/nether/items.lua#L1012-L1017) here, maybe it helps. :slightly_smiling_face:

**Comment by paramat** [comment]
Meh, `minetest.override()` doesn't work for an item called ":" for some reason.
`Attempt to override non-existent item :`

If i try
```
local ws = minetest.registered_items[":"].wield_scale

	minetest.register_item(":", {
		type = "none",
		wield_image = "wieldhand.png",
		wield_scale = ws,
```
then
`attempt to index field ':' (a nil value)`

**Comment by paramat** [comment]
Yes that works, register hand tool as ":", then override as "", will make a PR.

**Comment by paramat** [comment]
PR #2457

**Comment by DS-Minetest** [comment]
If a mod wants to register an item which has another mod name, it has to add `":"` in front of the name. `":"..""` -> `":"`

**Comment by paramat** [comment]
I see, thanks.
