### ISSUE TITLE
Turn "README.txt" into the markdown language

### ISSUE THREAD

**Issue by Panquesito7** [minetest/minetest_game#2456]
Shouldn't `README.txt` be `README.md`?
The words will not look that small. Also, it will have support for headers and other cool stuff.

What do you think?

**Comment by TumeniNodes** [comment]
I :+1: this because I know that @Panquesito7  does nice work in this area.

**Comment by paramat** [comment]
:+1: yes please.

**Comment by Panquesito7** [comment]
Creating pull request right now.
