### ISSUE TITLE
Add contributing guidelines

### ISSUE THREAD

**Issue by Panquesito7** [minetest/minetest_game#2465]
Currently, contributing guidelines do not exist.
IMHO, contributing guidelines would be a great addition to the repository.

**Comment by paramat** [comment]
A contributing document seems a good idea, of course written by the core devs.

I can see a valid argument for templates, but in practice they often result in something quite messy, with random bits of the template left in, creating visual mess, and inapplicable questions of the template answered awkwardly instead of deleted. There's some benefit in some cases, but at an expense in all cases.
I'm officially neutral on templates (honestly personally, i would rather not have them).

**Comment by Panquesito7** [comment]
> I can see a valid argument for templates, but in practice they often result in something quite messy, with random bits of the template left in, creating visual mess, and inapplicable questions of the template answered awkwardly instead of deleted. There's some benefit in some cases, but at an expense in all cases.
> I'm officially neutral on templates (honestly personally, i would rather not have them).

I'll modify the title to be `Add contributing guidelines`. At least contributing guidelines are good! 🙂

> A contributing document seems a good idea, written by the core devs.

👍

**Comment by paramat** [comment]
The other core devs may want issue/PR templates.

**Comment by rubenwardy** [comment]
I'm less fussed with Minetest game, as there tend to be less issues anyway

**Comment by TumeniNodes** [comment]
I have enjoyed the free/casual feeling of contributing to MTG, as opposed to the more "stricter" guidelines with MT.
I view the engine portion of the project as more professional, and a definite need for such templates and guidelines... as it is more precise/technical work involved.

When it comes to a game, you are going to have more contributors who are most likely more hobbyists/artists (whether in visual, audio design or code)
It is not to say that gaming development is less professional, but I _do_ feel it is best to offer a more laid back/casual environment, which will attract more contributors... just as the more technical aspect of the engine will attract more technical contributors.

**Comment by rubenwardy** [comment]
I think MTG would benefit from less bureaucracy

**Comment by rubenwardy** [comment]
I think MTG would benefit from less bureaucracy (than the Minetest engine)

**Comment by paramat** [comment]
Closing due to #2710 and being low priority.
