### ISSUE TITLE
Proposal for a slight altering to Jungletree schematics

### ISSUE THREAD

**Issue by TumeniNodes** [minetest/minetest_game#2467]
Normally I would just do a PR but I want to check/hear thoughts before I delve into palying with tree schematics again :P 
I feel like a leaf node should be present atop all of the lower tree nodes for jungle trees. It tends to look a bit odd without them?
Any thoughts?
![here and here](https://user-images.githubusercontent.com/18484258/64492291-7f7ab980-d240-11e9-8311-e3eed6c07942.jpg)
(sorry for not using the default textures in this image, it was the quickest image I could grab atm)

**Comment by paramat** [comment]
The reason behind the current structure is that each of those branch node layers has y-slice probability, so it is not possible to know for sure that the requested additional leaf nodes would actually be above a branch, some would end up floating and away from any branches.
So it seems best to not add them, if they were added, the y-slice probabilites would have to be removed, which would be worse.
So i must :-1:

**Comment by TumeniNodes** [comment]
Which is exactly why I did an issue rather than a PR : )
You know I'm just good enough with schematics to be dangerous

Closing in 3... 2...
