### ISSUE TITLE
Interactable items missing infotext

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest_game#2469]
Nodes:
* ~~Wooden Sign, Steel Sign: no infotext when placed, shows `""` when you write nothing to it~~
* ~~Vessels Shelf: no infotext at all~~
* ~~Furnace: no infotext upon placement, works when used once~~
* ~~Steel Door, Steel Trapdoor: infotext present but it doesn't say what the thing is (only `owned by foo`)~~

Entities: (engine support needed, but I think it's worth considering)
* Cart
* Boats

**Comment by DS-Minetest** [comment]
>Entities: (engine support needed, but I think it's worth considering)

Related: https://github.com/minetest/minetest/issues/5042

**Comment by farooqkz** [comment]
I wonder what infotext should we use for... a door! "Owned by foo and only them can open it"?

**Comment by sfan5** [comment]
Entity infotexts aren't so necessary after all.
