### ISSUE TITLE
Escape translated texts in formspecs

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest_game#2470]
Such as this one:
https://github.com/minetest/minetest_game/blob/bb9279ccb843937bc8001ce333e3ccb71b0dba2d/mods/beds/init.lua#L17

This is however not a big deal nor a security-relevant issue as the parameters are not user-controlled and come from translation files (problems could be spotted at review).

see https://github.com/minetest/minetest_game/pull/2466#issuecomment-529231088 for more information

**Comment by Wuzzy2** [comment]
Add `local F = minetest.formspec_escape` at the top of each offending file, then just turn S("blabla") into  F(S("blabla")) whereever it's needed to keep everything nice and readable.

**Comment by DS-Minetest** [comment]
Does `S` add braces (`[`,`]`), commas (`,`) or semicolons (`;`) to the string?
