### ISSUE TITLE
Add niter ore and charcoal to rationalise TNT (gunpowder) crafting

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2472]
Current mess:
TNT is crafted from gunpowder.
Gunpowder is crafted from coal and gravel.

I think we should consider TNT to be gunpowder, as gunpowder doesn't look like TNT, but TNT could easily be gunpowder. But also to make it suitable for all eras:
Gunpowder "...  is the earliest known chemical explosive. ... Gunpowder was invented in 9th-century China and spread throughout most parts of Eurasia by the end of the 13th century."
TNT "... Its explosive properties were first discovered by another German chemist, Carl Häussermann, in 1891".

////////////////////////////////

EDIT: New proposal: 

Add charcoal to default (TNT mod depends on default), it's useful anyway for crafting torches without needing coal.

In the TNT mod:
Register niter ore to provide the other main ingredient of gunpowder, potassium nitrate.
Change the TNT node texture to a crate of gunpowder.
Possible changes:
Add a 'fuse' or 'gunpowder trail' item to use instead of 'a barrel of gunpowder per node of gunpowder trail', allowing us to raise the cost of the gunpowder item and therefore improve the crafting of 'TNT' and not use those useless TNT sticks.

**Comment by NathanSalapat** [comment]
ooh, I like this idea. The current craft recipe never made any sense to me.

**Comment by An0n3m0us** [comment]
Great idea! Although, TNT and gunpowder seem to be quite different from each other.

Gunpowder: "consists of a mixture of sulfur (S), charcoal (C), and potassium nitrate (saltpeter, KNO3)."
TNT: "is made by adding 3 NO2 groups (from nitric acid) to toluene" (simplified)
So TNT is not gunpowder, and neither is gunpowder TNT. Gunpowder was first used around the 9th century and TNT in 1863.

Anyway, back to the topic;

The Technic mod has a really nice texture for sulfur ore:
https://github.com/minetest-mods/technic/blob/master/technic_worldgen/textures/technic_mineral_sulfur.png

And sulfur lump texture:
https://github.com/minetest-mods/technic/blob/master/technic_worldgen/textures/technic_sulfur_lump.png

Sulfur dust texture if needed:
https://github.com/minetest-mods/technic/blob/master/technic_worldgen/textures/technic_sulfur_dust.png

**Comment by paramat** [comment]
Yes, i relaise TNT and gunpowder are very different, i was considering which to consider as the other.

**Comment by Extex101** [comment]
XD I was actually making a mod for this
![gunpowder_softwood_charcoal](https://user-images.githubusercontent.com/33675971/65095452-14cf2980-d976-11e9-8be7-37c5f707c607.png)
^ Softwood charcoal which is required for gunpowder.
![gunpowder_hardwood_charcoal](https://user-images.githubusercontent.com/33675971/65095450-14369300-d976-11e9-965d-998363ccfb63.png)
^ Hardwood charcoal just to be consistent
![gunpowder_saltpeter](https://user-images.githubusercontent.com/33675971/65095451-14369300-d976-11e9-8445-a684b9cb459b.png)
^ Saltpetre 
![gunpowder_sulphur](https://user-images.githubusercontent.com/33675971/65095454-14cf2980-d976-11e9-8bcc-afbf1e26a337.png)
^ Sulphur

Crafting:
Using correct ingredient proportion
![v4-760px-Make-Black-Powder-Step-5](https://user-images.githubusercontent.com/33675971/65095808-822f8a00-d977-11e9-8690-4b7a28db9414.jpg)
![Screenshot_2019-09-17-18-13-47-1](https://user-images.githubusercontent.com/33675971/65095812-8491e400-d977-11e9-96ef-ce2b076a0f95.png)

I think we should change the names and textures to be more accurate.
TNT is not made of gunpowder

Maybe change the texture to be a bomb or something


A few functionalities in order to obtain the items
Sulphur gathers above lava
![2019-09-17 20 36 49](https://user-images.githubusercontent.com/33675971/65105917-3e468000-d98b-11e9-8731-d3b5daa5f3b7.png)
Lava checks for cave ceiling after a timer or something 
Adds sulphur to ceiling (sign-like node)
This means that you can have sulphur farms (which would be cool)

And Saltpetre as an ore of some kind ore found in the mountains

Charcoals are made by cooking

I think that adding a group hardwood and softwood to all the trees would be the best way to do it

Tell me what you think

**Comment by jastevenson303** [comment]
Ah, so that's how you make TNT!

>I think we should change the names and textures to be more accurate.
>TNT is not made of gunpowder

>Maybe change the texture to be a bomb or something

I think it's interesting, how we strive for "realism" at times.  I really
like this quake3 mod called Urban Terror, but at least there they have a
slogan: "Fun over Realism."  Cheers!

**Comment by Ferk** [comment]
It might be a bit more accurate to add niter (or nitre, whatever spelling) as an ore.
It's mineral form of saltpeter.

TNT and gunpowder are different, but the one thing they have in common is the presence of nitro radicals, which is the one thing that saltpeter provides. But having sulfur in TNT makes no sense, since that's not part at all of its atomic formula. At least coal could be considered a relative to toluene.

**Comment by Extex101** [comment]
OK so after some research I've found that gunpowder can be sulphur free
The purpose of sulphur is to decrease the explosion temperature but it's much much harder to ignite

But I think that sulphur would make it harder to craft, which is what we want isn't it?

**Comment by Ferk** [comment]
I still think it's better to add nitre (or at least some nitro compound) than sulfur. And then make nitre as hard to find as you want to make gunpowder harder to craft.

**Comment by Extex101** [comment]
I think Nitre is a good idea
I was just saying that gunpowder can be made without sulphur so that is an option. 
But if we want a harder crafting it's still an option

**Comment by paramat** [comment]
> Saltpetre is the main ingredient.

Heh ok, i thought it was the more minor ingredient.
> Maybe change the texture to be a bomb or something

Fine for me.

There is no way for the Biome API decoration code to place sulphur only near lava, using Lua code to do this would be too slow/intensive.
> It might be a bit more accurate to add niter (or nitre, whatever spelling) as an ore instead of sulfur.
It's the mineral form of saltpeter:

Ok, this seems a good idea, sulphur is difficult to integrate into mapgen anyway.

If charcoal is used as an ingredient for gunpowder it needs to be added to the TNT mod not default.

**Comment by paramat** [comment]
Updated first post with new proposal.

**Comment by Extex101** [comment]
![screenshot_20190918_210942](https://user-images.githubusercontent.com/33675971/65212951-11f93500-da59-11e9-988a-e69e80ae11cb.png)
![default_mineral_nitre](https://user-images.githubusercontent.com/33675971/65212971-250c0500-da59-11e9-96d9-d1f0de032c4d.png)

Nitre Ore

**Comment by sfan5** [comment]
> There is no way for the Biome API decoration code to place sulphur only near lava

Is there anything (such as complexity) preventing the implementation of such feature?
I can see it being useful for in more situations.

**Comment by paramat** [comment]
It is inherently intensive as per-ore volume searches would be needed.

A decoration can be placed on cave ceilings, but this would be on all ceilings not just caves flooded by lava. Such a decoration can be limited to biomes that have lava-flooded caves, but that doesn't help much.

I can't think of any reasonably non-complex non-intensive way to do this. Ores/decorations that depend on a particular cave liquid are rarely required so i don't think it is justified in core mapgen code.

Besides, i prefer to not get too realistic with this recipe, niter and charcoal are the primary ingredients, that seems enough.

**Comment by paramat** [comment]
Reply to IRC comments:

The intention here is not to have an ultra-realistic gunpowder recipe, we are leaving out sulphur after all. The issue is how ridiculous it is to craft from coal and gravel, both easily found at the surface in large amounts. Explosives need to have higher cost.
MTG isn't ultra-realistic, but it is loosely realistic, and coal and gravel was a sloppy recipe choice.

**Comment by Extex101** [comment]
The point of sulphur in gunpowder is to reduce the explosion temperature.
Which isn't exactly needed when you're blowing holes into cave walls

**Comment by paramat** [comment]
It's probably too disruptive to remove the TNT words from node name and mod name. Mods and games register TNT so the registration API can't be changed. We could change the texture and description of the 'TNT' registered in the mod though.

**Comment by Extex101** [comment]
We could do something like create a global variable called bomb or something and make another called tnt and make tnt equal bomb

**Comment by Extex101** [comment]
An idea: Maybe we could put nitre ore in desert stone

**Comment by paramat** [comment]
IRC http://irc.minetest.net/minetest-dev/2019-12-21#i_5625404

19:15 Krock     for game#2472: The recipe should be kept simple. It's not accurate but I doubt there will be many mods that make use of the new ores
19:15 Krock     they don't have any other purpose in the game
19:15 Krock     as long it's solely for TNT: no. If it finds more use-cases: welcome.

**Comment by Extex101** [comment]
Nitre/Potassium Nitrate can be used as a fertilizer and to cure meats

**Comment by paramat** [comment]
@SmallJoker 
I disagree that an ore must have more than one use, most ores only have one use even if used by multiple mods. For example: iron ore is only smelted to steel.
However, potassium nitrate does have other uses that mods can use. From Wikipedia:
> Potassium and other nitrates are of great importance for use in fertilizers and, historically, gunpowder. Much of the world's demand is now met by synthetically produced nitrates, though the natural mineral is still mined and is still of significant commercial value.

So there are other uses, and fertiliser is something modders seem to like due to the MC influence.
So perhaps you support this?

A big problem with the current gunpowder recipe is it is far too easy to find the ingredients. Gunpowder should have higher cost and deeper ores.
MTGame is of course only loosely based on reality and not precisely realistic, but the gunpowder recipe is not even loosely realistic, it is just crude and stupid and something we would not accept in a PR today.
As for simplicity, the proposed resource and recipe is a simplification of gunpowder crafting, this is still simple.

**Comment by paramat** [comment]
Ugh, i have just seen that the crafting of gunpowder into TNT comes from Minecraft, so the original mod was just cloning MC even though it is a mess of 2 types of explosive.
I dislike how early MTG development cloned Minecraft in so many ways.

**Comment by Ferk** [comment]
Another very clear MC carry over is wool. Imho, it should have been named "cloth".
With no sheep it makes no sense for there to be wool, or for it to be crafted from cotton.
The issue is that wool has been a primary block for a long time and changing it would probably not be a popular move.

**Comment by paramat** [comment]
> imagining it's some sort of synthetic imitation of wool made of cotton.

I agree with this. Node descriptions could possibly be changed to 'synthetic wool'.
And i disagree with having sheep producing the same MTG 'wool' nodes, as that makes this mess even worse.

Shows how standards in MTG have risen so much, any old MC-clone crap used to be accepted =)

**Comment by tenplus1** [comment]
All for adding charcoal to the game but please keep tnt recipe simple without the need for new ores.

**Comment by paramat** [comment]
Please can core devs state their opinion on this? I get the impression it is possibly disapproved, but cannot close the issue because no-one is stating this here.
Even if it was approved i could not be bothered to work on this.
@sfan5 @SmallJoker @rubenwardy

**Comment by sfan5** [comment]
Sounds like a good change to me but if there's no interest in working on this go ahead on close it.

**Comment by paramat** [comment]
Closing due to #2710
