### ISSUE TITLE
Furnace fuel percentage infotext increases instead of decreases

### ISSUE THREAD

**Issue by An0n3m0us** [minetest/minetest_game#2478]
Shouldn't the fuel percentage decrease instead of increase? It's confusing why it increases.

Here's how I suggest it works: Decreasing percentage (sped up x5):
![img](https://user-images.githubusercontent.com/49789044/64897044-e4d40d80-d679-11e9-9477-4ecf0051d846.gif)

**Comment by benrob0329** [comment]
It's showing how much is there, not how much has been used. It'd be more confusing if it looked like we were gaining fuel.

**Comment by An0n3m0us** [comment]
No, that's not how it originally works. That's how I've suggested it works.
Here's how it originally looks like (sped up x5):

![test](https://user-images.githubusercontent.com/49789044/64905276-acf6b580-d6cd-11e9-9bac-8838f50b3367.gif)

Actually, I kinda get what it's showing; how much fuel has been used. But then it's not very clear.

**Comment by paramat** [comment]
I agree with this, because the word is 'fuel', the percentage should be amount of fuel.
If the word was 'fuel used' it would be ok as it is.

**Comment by An0n3m0us** [comment]
I think adding 'fuel used' will make the infotext even longer than it already is.

**Comment by paramat** [comment]
PR merged.
