### ISSUE TITLE
Texture for empty vessels shelf and bookshelf

### ISSUE THREAD

**Issue by An0n3m0us** [minetest/minetest_game#2479]
Do the vessels shelf and bookshelf need a bare shelf texture when empty? Otherwise, it's not clear which ones contain items and which ones don't without having to open them and check.

Since they now have infotext, it doesn't really matter if they both have the same empty shelf texture.

**Comment by TumeniNodes** [comment]
![vessels_shelf_empty](https://user-images.githubusercontent.com/18484258/64899280-aa0dad80-d658-11e9-9b6d-9d5e5bed0ef0.png)

**Comment by An0n3m0us** [comment]
Ref #2477: Vessels shelf and bookshelf code is currently being changed so this will have to wait a while.

**Comment by TumeniNodes** [comment]
Of course, the textures would need to be swapped when an item is put into it/them.
A matter of minor code

**Comment by An0n3m0us** [comment]
Yeah, I already have the code complete.

**Comment by sfan5** [comment]
Bookshelves don't do this so I wonder whether others should.

**Comment by An0n3m0us** [comment]
Well, I've implemented it for the bookshelves and the vessel shelfs if that's what you mean.

**Comment by paramat** [comment]
I think people like the look of bookshelves as they are and possibly generally would prefer they do not look empty when empty. It is difficult to decide, but due to that and in the interest of simplicity i think i prefer no change, for vessels shelves too.

**Comment by An0n3m0us** [comment]
Actually, I agree with that. After writing the code, I realized how much I had to change/add to the code just for a minor 'improvement'.
