### ISSUE TITLE
Add barrier block

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#2483]
Not inventing wheel here, it is "transparent solid block used to create impenetrable boundaries", used by server admins to create boundaries for various purposes.

**Comment by mbartlett21** [comment]
@Fixer-007 
You can use default:cloud.
It is unbreakable except with TNT.
You have to use /giveme to get it
It is not transparent though :(

**Comment by An0n3m0us** [comment]
I've created it, but it is TNT-able. Not sure how to prevent that.

**Comment by LoneWolfHT** [comment]
You can return true/false (I forget which) with on_blast in your node def to prevent TNT from destroying it

**Comment by An0n3m0us** [comment]
Thanks; it worked.

![test1](https://user-images.githubusercontent.com/49789044/65631238-0d8bc980-dfcf-11e9-9846-ad14376fd820.png)
0.06% alpha. I've also made the inventory image white (using the cloud texture).

Which tool should be used to break the barrier?

**Comment by An0n3m0us** [comment]
![default_tool_adminpick](https://user-images.githubusercontent.com/49789044/65819759-4ec2ea00-e218-11e9-9f75-efd1c398e2bf.png)

How about an admin pick or something of the type?

**Comment by LoneWolfHT** [comment]
An admin pick like the superpick in Minetest would be nice. But I think for now it would be better to just set barrier blocks to be able to dig themselves

**Comment by paramat** [comment]
I am not convinced this is a good idea for MTG. Such barriers are usually a specialist usage by servers, and servers likely need differing characteristics according to their need.

**Comment by paramat** [comment]
See PR (closed) for more discussion.
