### ISSUE TITLE
Improve steel bar door/trapdoor sounds

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#2495]
I offer you free of charge and under MIT License two improved sounds for the steel bar door and steel bar trapdoor:

Close door: https://repo.or.cz/minetest_mtg_plus.git/blob/HEAD:/sounds/mtg_plus_door_iron_bar_close.ogg
Open door: https://repo.or.cz/minetest_mtg_plus.git/blob/HEAD:/sounds/mtg_plus_door_iron_bar_open.ogg

@TumeniNodes

**Comment by sofar** [comment]
MIT is not a good license for media. Can you do CC-BY-4.0 or something instead?

**Comment by Wuzzy2** [comment]
I now also offer you the sounds under CC0.

**Comment by TumeniNodes** [comment]
These are sort of "clicky", appreciate the offer though, but they are just too weak sounding.
Definitely need new sounds for these doors _and_ steel doors, best if the sounds can cover both.

The hunt is on for better metal doors sounds.

**Comment by sofar** [comment]
CC0 is just as bad. Can you please just do CC-BY?

**Comment by Calinou** [comment]
Minetest already includes a fair amount of CC0-licensed assets, I don't see anything wrong with adding more. CC0 isn't OSI-approved, but it's fine for artwork.

**Comment by TumeniNodes** [comment]
Y'know... I have that little steel door at the base of my fireplace to clean all the ashes and bones (ummm chicken bones... yeh) which makes perfect sounds when opening and closing... I wonder if I can get some decent sounds from that xD

**Comment by sofar** [comment]
I disagree. We should over time remove all CC0 material with CC-BY or better. It shouldn't grow in size, for sure.

Please, understand, the CC0 allows anyone to assume copyright over items and (maliciously) potentially cause problems. Having a clear and simple ownership declaration that avoids this problem is obviously preferred in a time when plagiarism is easy and ubiquitous.

**Comment by sofar** [comment]
If he's offering the item under MIT/CC0, I don't see why we can't merge it as CC-BY though :)

**Comment by TumeniNodes** [comment]
All CC BY-SA 4.0
Just woke up from a loud noise outside my home... figured I'd post these for feedback.
I'm going back to sleep for about an hour :P 
I worked on these for about an hour off and on...
played with pitch and stretch, echo etc... all from a 6"x6" metal door at the base of my chimney xD
Amazing how much can be done with sounds
[sounds.zip](https://github.com/minetest/minetest_game/files/3646165/sounds.zip)

**Comment by Wuzzy2** [comment]
> If he's offering the item under MIT/CC0, I don't see why we can't merge it as CC-BY though :)

Yes! Finally you have figured it out! Congratulations! :D

I don't really like @TumeniNodes' sounds. Too … dull. Somehow. Idk.

**Comment by TumeniNodes** [comment]
@Wuzzy2 I fully understand you're not too crazy about the sounds I created, and I truly appreciate the offers you gave... however, my feeling is that those sounds would go great with something like a fence gate latch... yet not do not fit with large steel bar doors.

The current default steel door sounds do not fit with them either.
So these are what I have come up with.

**Comment by An0n3m0us** [comment]
TumeniNodes; the sounds you have made are a bit muffled but they still sound good. The only thing I can say is that they are not similar to the other door sounds, but does that matter?

Wuzzy; the sounds you have made are like the current door sounds but I like them _because_ they are similar. But the sounds are much too 'soft' for a steel door I think, and _maybe_ a bit too quick (or quiet; I can't tell).

**Comment by Wuzzy2** [comment]
@An0n3m0us: The proposed sounds are for the steel _bar_ door, not the steel door. HUGE difference!

**Comment by An0n3m0us** [comment]
I meant steel bar door instead of steel door.
Not a huge difference; the same material, but the steel door isn't hollow in some parts like the steel bar door is.

**Comment by TumeniNodes** [comment]
> TumeniNodes; the sounds you have made are a bit muffled but they still sound good. The only thing I can say is that they are not similar to the other door sounds, but does that matter?

the doors from doors mod all use a sort of "woosh" sound on open, which definitely do not fit for these bar doors.
I'm still now, not completely happy with the open sound I liked my original one better but, I still may try to come up with another sound for it altogether later tonight.
The close sound I am happy with.

Not sure about the "muffled" part though, I experience no muffle on my end. I tested the volume against the other doors and for me they are equal.

**Comment by paramat** [comment]
#2497 merged.
