### ISSUE TITLE
Make steel bar doors/trapdoors easier to dig

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#2496]
Currently, steel bar doors and steel bar trapdoors are as difficult to dig as steel doors.

I suggest to make them easier to dig.

@TumeniNodes.

**Comment by paramat** [comment]
Why would they be easier to dig than steel door/trapdoor? Equal seems suitable.

**Comment by TumeniNodes** [comment]
Are you suggesting this merely for the reason they are made of less material?
I am only asking as I am trying to think of a valid reason for this.

**Comment by Wuzzy2** [comment]
> Are you suggesting this merely for the reason they are made of less material?

Yes. And the dig time is quite long.

**Comment by TumeniNodes** [comment]
My view is, steel bar doors are typically associated with security, and tough to bypass.
Used throughout prisons and other facilities IRL for that specific reason.
I think if anything, maybe they should be tougher to dig/break (afterall they are already/properly more expensive to craft) but, leaving them equal to the current steel doors may be best.

**Comment by paramat** [comment]
Equal seems fine to me.

**Comment by paramat** [comment]
Yes, steel bar doors are extremely tough.
