### ISSUE TITLE
SFINV: Add 'on_open' and 'on_close' callbacks for 'register_page' function.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest_game#2502]
Or make 'on_enter' is called when a player opens his inventory. Although, when he is opening it is setting up necessary default page (named 'All') and that should be called also. I`d propose to add it for 5.2.

**Comment by rubenwardy** [comment]
This is not possible to implement with the minetest engine. Please see the respective issue in the engine repository, no need to track it here too

**Comment by Andrey2470T** [comment]
what`s respective issue?
