### ISSUE TITLE
Declare string freeze and update template.txt one last time

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#2504]
The German translation is already outdated because strings have been touched.

Please declare a string freeze and or update the `template.txt`s one final time. I will work on the final update for German when that has been done.

If updating `template.txt` is not possible for you, I can do it. I will not do anything before I get an official OK that strings are frozen.

**Comment by paramat** [comment]
Note: I am hopeless with translation stuff, don't expect me to understand or sort this out for 5.1.0, someone else will have to do so =)

**Comment by sfan5** [comment]
#2512 has taken care of the templates. And while there is no formal string freeze, we don't expect anything that changes the strings. So, this can be closed.
