### ISSUE TITLE
Fix broken background 9 slice

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest_game#2510]

**Comment by lhofhansl** [comment]
Can you explain what this is about? :)

**Comment by rubenwardy** [comment]
This 9slice element in the prepends needs to be amended to background9 instead of background in order to suppress errors on 5.0.1 clients

**Comment by DS-Minetest** [comment]
Instead of using `background9`, one could set formspec version to 2.

**Comment by SmallJoker** [comment]
1c413ed
