### ISSUE TITLE
Water is too transparent

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest_game#2513]
In fact this has bothered me for a while, but I never knew what it was.
Islands don't really look like islands, beaches not like beaches.

I finally figured that it was the water's transparency. IMHO (and just in IMHO) it looks much better when the transparency is set to 180 or even 200 (from the current 160).

Examples below. Notice how the landscape looks more real when you can see the water better.

160 (current value):
![screenshot_20191003_234445](https://user-images.githubusercontent.com/446130/66186766-f8024980-e637-11e9-8ea2-d6420f8582c5.png)

180:
![screenshot_20191003_234531](https://user-images.githubusercontent.com/446130/66186767-f8024980-e637-11e9-8a41-63b8349fa0f3.png)

200:
![screenshot_20191003_234846](https://user-images.githubusercontent.com/446130/66186848-34ce4080-e638-11e9-8eb6-588c979ce241.png)

Looking for opinions.

**Comment by lhofhansl** [comment]
180 seems to be a good compromise so that one can still see objects under water. Even 200 is OK (IMHO(

160:
![screenshot_20191003_235728](https://user-images.githubusercontent.com/446130/66187352-757a8980-e639-11e9-81f1-46a84268a297.png)

180:
![screenshot_20191003_235632](https://user-images.githubusercontent.com/446130/66187350-757a8980-e639-11e9-84f4-5bcdd168e910.png)

200:
![screenshot_20191003_235659](https://user-images.githubusercontent.com/446130/66187351-757a8980-e639-11e9-9857-94c7b5fc1dd7.png)

**Comment by Andrey2470T** [comment]
The water would get looked just amazing if it had reflections on its surface like in this: https://www.youtube.com/watch?v=uz1douFQcok

**Comment by TumeniNodes** [comment]
I've felt the same and made comments on this in HW.
I also prefer underwater to be cloudy enough to look like you are actually "under water", rather than complete clarity as is current.

It is also annoying that when one goes under water at night, everything is suddenly brighter.

**Comment by TumeniNodes** [comment]
> The water would get looked just awesome if it had still reflections on its surface like in this video: https://www.youtube.com/watch?v=uz1douFQcok

@Andrey2470T that is completely OT for this discussion .
Yes, we are _all_ aware of kilbith's recent teaser...

**Comment by sfan5** [comment]
180 is fine by me, however I think the much bigger problem is that you can see through large masses of water as if it were a tinted panel of glass:
![grafik](https://user-images.githubusercontent.com/1042418/66195922-f49eaa80-e697-11e9-9974-a5c6c6312514.png)
IMO fixing that would even have more benefits than reducing texture transparency.

**Comment by LoneWolfHT** [comment]
180 or 200 looks great :+1:

**Comment by lhofhansl** [comment]
@Andrey2470T Agreed, but that's a different topic. We'd need @kilbith to post the code :) (I'd be very much in support as long as it is optional. That's also an engine change, not a game change.)

@sfan5 Agreed. Not sure how we'd that without rendering non-surface water nodes. Possibly we do something in the shader based on the viewing angle (which would actually reflect reality somewhat).

Back to this... The more I look, the more I like 200 as a setting. Simple change, increases immersion immensely (still MHO). If it's hard to agree we could make this configurable, but I'd prefer remove config option rather than adding more. :)

@paramat ?

**Comment by paramat** [comment]
180 or 200 does look better to me than 160, which i agree looks too clear.
In the 1st set of screenshots 200 looks best, however how about a number more suitable for a 0-255 range, like 191 (3/4)? This could be a nice balance between 180 and 200.
Values like 160, 180, 200 don't make much sense as numbers to choose in a 0-255 range.
I also prefer this is not made configurable.
:+1: for 191 or 200, whichever looks best or whichever is preferred by core devs.

Seeing clearly through large masses of water is something i very much like about MT. Clear water, like some tropical waters in real life, is inherently pleasant to look at and be in, cloudy water is not.
But perhaps we could slightly reduce view range when in water, seems the simplest way and it shouldn't be shader-dependent.
This alpha change will partly solve the issue when looking at water from above.

**Comment by kilbith** [comment]
> We'd need @kilbith to post the code

This is being worked on currently.

**Comment by lhofhansl** [comment]
@kilbith cool!

@paramat I had exactly the same observation. 200 looks best for a complete scene, whereas 180 seems better when you're looking for something under water. 191 sounds like an excellent compromise I'll test with that.

**Comment by TumeniNodes** [comment]
Will under water visuals be addressed as well, or will that go into another, future PR?
If changing the visuals from above, to me it makes sense to go the full way and address water visuals completely from above and under.
The only thing I am unsure of, is how to change the light levels for underwater.
Changing the clarity and colour underwater is simple... and it can be made configurable via the conf file, which would be a nice option for game creators.

**Comment by lhofhansl** [comment]
@TumeniNodes I think we should. There're already parameters in MTG:

```post_effect_color = {a = 103, r = 30, g = 60, b = 90}```

We can tweak those, and/or increase "fog" density underwater.
I think we should initially limit this to simple changes like this one.

Eventually - and I know this is controversial - I'm a super big fan of more photo-realistic rendering at least where it adds to the immersion.

Underwater particles... Like snowdrift? That could be an interesting thing. It's pretty server-expensive, though. It's (relatively) cheap to do things at the surface - shader based fog, waves, reflections, etc. If we have to render the intermediary stuff nodes (like water or air) it's gets quite a bit more expensive.

Then again I work on globe spanning distributed databases for a living and know fairly little about shaders. :)

**Comment by lhofhansl** [comment]
Here's an example when I a to 203 (instead of 103):
![screenshot_20191004_170935](https://user-images.githubusercontent.com/446130/66246554-b91cd400-e6c9-11e9-967d-ea7757969c8f.png)

Current:
![screenshot_20191004_171000](https://user-images.githubusercontent.com/446130/66246555-b91cd400-e6c9-11e9-8d82-5c15225980eb.png)

203 is not a good number, just for exploration.

**Comment by paramat** [comment]
Concerning 'post effect colour': Increasing that is very problematic. It is uniform across the screen so looks increasingly bad at higher values. It is also what makes water so bright at night and in very deep water where light level is low. So it is best to have PEC as low as possible, for just a subtle colour tint, as now. Increasing 'fogginess' is best done in other ways in the engine.

**Comment by lhofhansl** [comment]
Yeah agree. Let's have a separate discussion for the underwater behavior independent of this one.
Something like the fog-in-clouds stuff that we did! We can change the fog color under water and increase the density.

Also note I'm not suggesting we change the river water. Somehow there it seems ok, although we could of course change it there too.

You guys want a PR for the alpha change for water?

**Comment by paramat** [comment]
Yes please for a PR. I'll +1 and i expect another MTG core dev will too.

**Comment by Extex101** [comment]
Maybe have fog in the water so the deeper it is the foggier it will look

So like normal fog but only within the water blocks
And when within the water too

**Comment by lhofhansl** [comment]
@Extex101 It's actually not that easy to tell. You can't go by the water height, as there might be caves. 

So you'd have to check how many water blocks are above you, even then there might be cave, so you can't tell. Hmmm...

Perhaps we can come with something that takes the light level or the day-night ratio and calculate the fog strength from that.

Lemme file a separate issue for that, then we can discuss.

**Comment by lhofhansl** [comment]
@sfan5 Actually there are two ways to render the water such that won't appear perfectly transparent.
(1) we can calculate the fresnel-effect, which makes water more reflective at lower angles, and (2) we can draw a depthmap, and calculate the "length" of the water to the floor that way.
(2) is pretty expensive, and (1) won't work until we have the fixed the shaders to do reflections correctly.

**Comment by paramat** [comment]
Option (2) is overkill and far too intensive to be practical.
