### ISSUE TITLE
Use submodules to allow other games to easily integrate mods from minetest_game

### ISSUE THREAD

**Issue by Niwla23** [minetest/minetest_game#2518]
So putting all mods from mt_game in the minetest organisation and link to them by submodules

**Comment by rubenwardy** [comment]
This has already been rejected as it will make the maintenance much harder. There is an organisation that automatically creates repos for each game in MTG

Also, a lot mods in MTG are unsuitable for direct inclusion in another game without modification

**Comment by SmallJoker** [comment]
#1875
