### ISSUE TITLE
[Sethome] Add a reset cmd to preceding home.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest_game#2526]
Often the situations happen when a player needs often (or not) entering '/home' cmd by some circumstances (e.g falling down onto lava while coming a parkour level, falling down from a mountain cliff to be saved or other accidents concern to falling down) and he selects the previous cmd (/home) with pressing upper arrow key to enter it as rush as it`s possible. And that player may select '/sethome' by such way in a rush is the previous implemented or any other inappropriate cmds and not able to get to that spot where former homepoint was set. So to avoid a such accidential entering of incaution I propose to add still cmd (let '/resethome') that resets to the previous home point.

Other reason of adding such command is just a player wants to reset to the former homepoint and also can not reach that spot.

**Comment by paramat** [comment]
Seems to me the chance of /sethome and /home both being recently used commands, and being  subsequently used commands such that the wrong one is selected, and the player making such a mistake, is very small.
The second usecase makes more sense.

**Comment by An0n3m0us** [comment]
How about a popup dialog when setting a new home? Like an "Are you sure? (This will override your previous home coordinates!)" dialog with a yes and no button.

**Comment by An0n3m0us** [comment]
Something like this (the formspec is a little messed up at the moment for some reason; I'm going to recompile the Minetest engine to fix it):

![image](https://user-images.githubusercontent.com/49789044/67128904-fc606200-f1f4-11e9-8a6f-81d047ab2591.png)

**Comment by Andrey2470T** [comment]
> How about a popup dialog when setting a new home? Like an "Are you sure? (This will override your previous home coordinates!)" dialog with a yes and no button.

This is already offtopic. The idea may look like nice to prevent an accident set
, but this issue is about certainly adding a reset cmd for a player could switch to the previous homepoint and not just in security goals.

**Comment by An0n3m0us** [comment]
Paramat already said:

> We would then need to store each player's previous homepoint, i am not convinced it is worth doing.

I think that's more effort (correct me if I'm wrong) than making a simple warning box popup when one enters the sethome command. And it also prevents players accidentally overwriting their previous home so easily.

> And that player may select '/sethome' by such way in a rush is the previous implemented or any other inappropriate cmds and not able to get to that spot where former homepoint was set.

It solves that problem so it's actually not offtopic.

**Comment by paramat** [comment]
> How about a popup dialog when setting a new home?

There's no need as explained above:
> Seems to me the chance of /sethome and /home both being recently used commands, and being subsequently used commands such that the wrong one is selected, and the player making such a mistake, is very small.

**Comment by paramat** [comment]
> Other reason of adding such command is just a player wants to reset to the former homepoint and also can not reach that spot.

Although this is a more valid usage, i think it is not much needed and so does not justify the complexity of implementation and having to store the previous homepoint for players.
So :-1: for the request.
