### ISSUE TITLE
Problems with Russian translation

### ISSUE THREAD

**Issue by Doloment** [minetest/minetest_game#2532]
Need to choose the correct translations for following in-game subjects:
- Mese stuff
- Fancy Bed
- Powered Rail
- Boat cruise mode On/Off
- Nodes
- Locked /insertnodename/
- Skeleton Key [Ключ Скелета]
- Dye
- Flint and Steel
- Mapping Kit
- (left-click rotates face, right-click rotates axis)
- Crafting
- TNT-related stuff

Is this correct to translate 'Fancy Bed' to 'Детализированная кровать'('Detailed Bed')?

Use with 'Zoom' key -- previous translator translated this "Используется с привилегией 'Zoom'"("Used with the 'Zoom' privilege") /facepalm/

What is the 'Boat cruise mode'?

Locked Chest -- previous translator translated this 'заблокированный сундук' ('Blocked Chest') lol

Default mod is translated pretty good

What's better for 'Dye' translation: 'Краситель'(Literally) or 'Краска'(Shorter than 'Краситель', but also means 'Paint')?

What's better for 'Flint and Steel' translation: 'Кремень и Сталь'(Literally, rare in use), 'Кремень и Кресало'(Same, but sounds better),  'Огниво'(Same, but much shorter) or 'Зажигалка'('Lighter')? The problem is that in Russian 'Кремень'(Translates 'Flint'), which is the element of 'Огниво' and doesn't mean actual mineral, is made of steel. So i would prefer 'Огниво'.

What's better for 'Crafting' translation: 'Крафтинг'(Transliteration) or 'Создание'(Adapted, because there's not literal translation)?

P.S.:"Бурая Шерсть" - это отличный перевод, @Andrey2470T!

**Comment by Andrey2470T** [comment]
1. **Fancy bed**: It was translated as 'детализированная' because it`s the most appropriate variant. The bed has more complicated shape and consists of greater number of nodeboxes rather than the simple bed. Such literal translations as 'маскарадный', 'причудливый', 'фантастический' just don`t make sense.

2. **Nodes**:  The translation selection rationale is in: https://github.com/minetest/minetest_game/pull/2525#issuecomment-548117065

3.**Mese Stuff**, **Powered rail**, **Locked chest**, **Use with 'Zoom' key**, **Skeleton key**: I don`t understand what you consider here wrong and doubtful. ?

4. **TNT**: Yes, I translated it as 'тротил' because it means a burst matter and it is not translated as 'динамит', (dynamite будет по-английски).

**Comment by Doloment** [comment]
1. 'Роскошная Кровать' or 'Необычная Кровать' are not too bad translations
2. I think (and not just me) that this is a bad translation.
3. The translation of these words or expressions depends on the context. 
And about Mese. How it is should be translated? There's no Russian word that would fit within the meaning. So we need to create a new word, huh. 
About "Use with 'Zoom' key". There's clearly written about key, but not the privilege. So why did you translated 'key' to 'привилегия'('privilege')?
4. There a little mess in game itself. Trinitrotoluene (TNT, Тринитротолуол Тротил) is translated right. But if we talk about TNT-sticks... The problem is... There's no TNT-sticks IRL. There's **Dynamite sticks**. So, how we should translate this? 'Тротиловая Шашка' or 'Динамитовая Палочка'? 2nd sounds strange, so I would prefer 1st, but it's not exactly what currently in game.

**Comment by paramat** [comment]
> What is the 'Boat cruise mode'?

It is a mode where the boat will move forward without the player needing to hold down 'W'. Useful for long ocean journeys. Similar to player 'autoforward'.
Details: https://github.com/paramat/minetest_game/blob/master/mods/boats/README.txt

**Comment by Andrey2470T** [comment]
3. 'Use with 'Zoom' key': Well, I dont know what key is meant. Or probably is this meant 'Z' key on a keyboard?

**Comment by paramat** [comment]
'Use with 'Zoom' key' should be exactly that, not 'Use with 'Zoom' privilege'.

'Mese' is a silly made up word so should be a made-up russian word that sounds like 'Meh-seh'.
See celeron55's post: https://forum.minetest.net/viewtopic.php?p=75712#p75712
"    4aiman wrote:
    However sometimes I pronounce it like two separate words: "me-ce" ("e" like in "America", "c" like in "celebrity")

^ That is relatively close to how it's originally said in Finnish. Me being Finnish, that's how I say it."

**Comment by Andrey2470T** [comment]
Ok, then 'Boat cruise mode' it may be translated like as 'режим авто-плавания лодки' or 'режим автолодки' to clarify what its meant.

**Comment by h4ml3t** [comment]
@Doloment 
About the 'Skeleton Key', it is a reference to an unbreakable lockpick found in the game 'Skyrim' [(source)](https://en.uesp.net/wiki/Skyrim:Skeleton_Key).

In the Italian translation I have used the form 'Key of the Skeleton', to allow people that never played Skyrim to understand that it is a special item by the fact that it has a unique name.

Thus between:
Exact but unclear 'Skeleton Key' -> 'Chiave scheletro'
Not exact but functional 'Key of the Skeleton' -> 'Chiave dello Scheletro'
I've chosen the second form.

 (If someone is trying to pronounce those Italian words, 'ch' is pronounced as 'k'.)

**Comment by adem4ik** [comment]
Just my 50 cents:

- Mese - "Мезе"
- Fancy Bed - "Роскошная кровать"
- Powered Rail - "Электрическая рельса" (from Minecraft)
- Boat cruise mode On/Off - "Режим самостоятельного плавания лодки"
- Nodes - I prefer "ноды" tbh ("блоки" is too specific, and there are already "blocks" term in the game, "узлы" - I don't think anybody would understand it correctly)
- Locked /insertnodename/ - "Запертый" (from Minecraft)
- Skeleton Key - "Ключ скелета" is fine (optional suggestion - "Скелетный ключ")
- Dye - "Краска" is fine
- Flint - "Огниво" is fine
- Mapping Kit - I think "Комплект картографа" would be a bit better and shorter than "Картографический комплект"
- (left-click rotates face, right-click rotates axis) - (левая кнопка мыши вращает грань, правая — ось)
- Crafting - I'm fine with "Крафтинг"
- TNT - "Тротил" is great

**Comment by Andrey2470T** [comment]
Basing on all previous posts I can make a conclusion of what is really needed to be changed:
* Fancy bed should be translated as **'роскошная кровать'**,  **'детализированная кровать'** is too long.

* Locked chest/steel door/trapdoor should be translated as **'запертый сундук'**, **'запертая стальная дверь'** and **'запертый стальной люк'** respectively.

* Use with 'Zoom' key as **'Используйте нажатием клавиши 'Zoom'**.

* Boat cruise mode On/Off - **'Режим самоходной лодки'**, I think such translation is better than which I proposed.

**Comment by MoNTE48** [comment]
'Режим самоходной лодки' - чего-чего? Ну не ломай мозг людям :)

**Comment by Andrey2470T** [comment]
Ха-ха, тебе даже здесь ломать мозг нужно? :) По-моему, здесь и так уже все понятно и ясно, понятнее и быть не может!

**Comment by kostya13** [comment]
May be this:
Boat cruise mode On/Off - "Автопилот лодки Вкл/Выкл"

**Comment by kostya13** [comment]
>  But if we talk about TNT-sticks... The problem is... There's no TNT-sticks IRL. There's **Dynamite sticks**. So, how we should translate this? 'Тротиловая Шашка' or 'Динамитовая Палочка'? 

"Тротиловая шашка"  - это широко используемый термин в русском языке. Поэтому однозначно
TNT-sticks  - Тротиловые шашки.

TNT - можно назвать "Ящик тротила". Можно, конечно, еще "ТНТ", но у многих это с  телеканалом может ассоциироваться :)

**Comment by Andrey2470T** [comment]
@kostya13, на счет перевода 'ящик тротила' согласен, т. к. он более понятный и полно отражает сущность объекта, чем просто 'тротил'. 

TNT sticks можно перевести как 'тротиловые бруски' или дословно 'тротиловые палки', т.к. возможно не всем будет понятно что значит 'тротиловые шашки'.

**Comment by kostya13** [comment]
Дословный перевод не всегда правильный. 
В каждом языке есть свои термины для одних и тех же понятий.

Даже яндекс переводчик переводит "TNT sticks" как "Тротиловые шашки".

Кому не понятно, загуглив "тротриловая шашка" сразу поймет в что это.

**Comment by paramat** [comment]
And the TNT sticks are made of gunpowder =D it is a messy mod.

**Comment by Andrey2470T** [comment]
> Also possible :
> Boat cruise mode On/Off - "Автопилот лодки Вкл/Выкл"
> 
> But according to the description:
> [#2532 (comment)](https://github.com/minetest/minetest_game/issues/2532#issuecomment-548931605)
> This is typical "Круиз-контроль". This is term used in Russian.
> For example:
> https://ru.wikipedia.org/wiki/%D0%9A%D1%80%D1%83%D0%B8%D0%B7-%D0%BA%D0%BE%D0%BD%D1%82%D1%80%D0%BE%D0%BB%D1%8C
> 
> So you can translate this:
> Boat cruise mode On/Off - "Круиз-контроль лодки Вкл/Выкл"

А при чем здесь вообще круиз-контроль? Этот термин ассоциируется исключительно с автомобилестроением, по крайней мере так гугл выдает. Но даже если это устройство и применяется в реальности в морском транспорте, очень сомнительно, что автор при создании предполагал ее "скрытое от глаз игрока наличие". Тогда, оно бы, скорее всего, как-нибудь фигурировало в ее конструкции.

**Comment by RichardTry** [comment]
Мне кажется "Запитанная рельса" больше подходит под "Powered rail", чем "Механизированная рельса". Никаких механических частей там вроде не предполагалось.
И "Тормозящая рельса" звучит благозвучнее чем "Рельса с тормозом", на мой взгляд. Ну и тормоз это обычно всё-таки то, что стоит на движущемся объекте, а не статичном.

**Comment by Wuzzy2** [comment]
FYI: There will be a release soon.

**Comment by amadin** [comment]
Do not forget that most players are children. The words "Запитанная", "Круиз-контроль" etc., may not be familiar to them.

**Comment by RichardTry** [comment]
Как насчёт "Режим автохода лодки" или просто "Режим автохода" для boat cruise?
Текущее "режим путешествия на лодке" всё же непонятно.

**Comment by Andrey2470T** [comment]
Как по мне, мой вариант перевода "режим самоходной лодки" был все же яснее и понятнее, чем текущий буквальный перевод. По-другому, это значит "режим автоматического движения лодки" ("самоходный" = "движущийся на собственной тяге", из толкового словаря Ушакова).

И кстати, на сколько я знаю, "автоход" нет такого слова в русском языке.
