### ISSUE TITLE
Consider switching eating and using buckets to right click only

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#2540]
Current behavior in minetest is confusing, solution is simple - you eat/place/take liquids with right click. Yes, just like in another popular block game, it just works, easy and simple.

**Comment by paramat** [comment]
Why is current behaviour confusing? And why is this better? More explanation needed.
The behaviour that players are used to is likely to be the less confusing.
Is this influenced by your playing of MC? =)
I seem to remember discussion of how we consider left/right click and use/place.

**Comment by rubenwardy** [comment]
It's not possible to switch eating to right click without modifying every mod that makes things edible

**Comment by Fixer-007** [comment]
Left click causes punch after eating, mining crops causes eating them, and buckets are just confusing in general

**Comment by paramat** [comment]
The alteration to eating might have good arguments, but rubenwardy's observation means it is probably not worth altering.

For buckets, you still have not explained =/
It seems intuitive to me:
LMB digs a node using either the hand or a digging tool, the bucket can be considered a digging tool.
RMB places a node, when used with a bucket it places a liquid node.
I agree that other approaches might be equally as intuitive, but the current one seems fine so i cannot see a good reason to change it :-1:

**Comment by LoneWolfHT** [comment]
Current bucket dig/place method is fine and prevents accidentally digging/placing in the same click

**Comment by paramat** [comment]
No response and buckets seem intuitive as they are.
