### ISSUE TITLE
Broken downloads link in README.md

### ISSUE THREAD

**Issue by adem4ik** [minetest/minetest_game#2542]
- Open the link https://minetest.net/downloads/ from https://github.com/minetest/minetest_game/blob/master/README.md#compatibility

Result: NET::ERR_CERT_AUTHORITY_INVALID

I believe it should be replaced with https://www.minetest.net/downloads/

**Comment by paramat** [comment]
I agree.
The current address for me results in 'Warning: Potential security risk ahead'.
The 'www...' version works fine.
Also, the link does not appear as a clickable link like the others, not sure if that is intended.

**Comment by paramat** [comment]
PR #2543

**Comment by MoNTE48** [comment]
Isn’t it worth it to fix the DNS record and put the site back without 'www.'?
Nobody uses 'www.' in 2k19!

**Comment by paramat** [comment]
Please do not unassign a contributor without discussion and agreement.
