### ISSUE TITLE
Rotating wall torch with screwdriver may lead to "invalid" rotation

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#2545]
Version: 5.1.0

Just place a torch at a wall somewhere and play around with the screwdriver a bit.

You might end up with the torch in an "invalid" position, that is, the wall torch is "attached" upwards or downwards. This can look very odd. I do not think this is intentional.

Note there's a separate node for upwards and downwards torches.

**Comment by paramat** [comment]
An invalid position seems ok to me, it does no harm. Many nodes can be rotated or positioned in non-realistic ways. Unless a 'fix' is very simple i do not think it is worth doing.
Thanks anyway.

**Comment by An0n3m0us** [comment]
I can't seem to reproduce this in the latest version of Minetest?

**Comment by paramat** [comment]
Sorry, i may have misunderstood the first post. If you are suggesting that the screwdriver should not function at all on torches, i am fine with that. As far as i know that is very simply done, if so i will support a PR that does that.
Torches rotate on placement according to the surface they are placed on, so screwdriver rotation is not necessary.

**Comment by DS-Minetest** [comment]
>I can't seem to reproduce this in the latest version of Minetest?

It is not possible to rotate the torch in a way that it will float afterwards., that's probably because of this function:
https://github.com/minetest/minetest_game/blob/10824667963a78f8f0d098b233ef2badff985f69/mods/screwdriver/init.lua#L20-L31
Torches currently don't have an `on_rotate` field in their def.

**Comment by paramat** [comment]
Ok it is possible to cause a strange result. With the structure below a wall torch can become an upside-down ceiling torch, and back again, when right-clicking screwdriver:

![screenshot_20200209_233135](https://user-images.githubusercontent.com/3686677/74112414-6af67080-4b94-11ea-927e-eeb510b9eecb.png)

![screenshot_20200209_233143](https://user-images.githubusercontent.com/3686677/74112421-6f228e00-4b94-11ea-9da3-329507e2eb75.png)

**Comment by An0n3m0us** [comment]
That's what my PR fixes.

**Comment by paramat** [comment]
With the structure below a ceiling torch can become a ceiling torch placed on a vertical surface, and back again, when right-clicking screwdriver:

![screenshot_20200209_233659](https://user-images.githubusercontent.com/3686677/74112516-38994300-4b95-11ea-80c7-d5eea7aa2044.png)

![screenshot_20200209_233710](https://user-images.githubusercontent.com/3686677/74112519-3df68d80-4b95-11ea-8f23-ad31e0ad8fca.png)

**Comment by An0n3m0us** [comment]
Both of those issues were solved by the first commit in my PR; by using on_rotate and param2 to determine the correct torch placement.

**Comment by paramat** [comment]
Yes, but your PR can solve this a simpler way.

More weirdness can occur.
Generally, a torch in any 2 or 3 node corner can be rotated into invalid rotations using screwdriver left or right click.

**Comment by An0n3m0us** [comment]
Yeah, that was all done in my PR.

**Comment by paramat** [comment]
Yes i know =)

**Comment by An0n3m0us** [comment]
Hah sorry; I spent a good hour fiddling around with the code to write the on_rotate function correctly, and for all of it to end up as three `false` statements; I already did that at the beginning, so one can probably imagine how I feel xD

**Comment by paramat** [comment]
Well, i did make clear what implementation i prefer, see https://github.com/minetest/minetest_game/issues/2545#issuecomment-569465568 above.

**Comment by An0n3m0us** [comment]
My fault; I didn't read that comment fully.
Anyway, since torches are `dig_immediate` too, it makes sense why rotation using a screwdriver isn't really required. I thought of keeping it since most nodes can be rotated.
