### ISSUE TITLE
Player model: Invalid "Arm_Right" bone rotation in certain frames

### ISSUE THREAD

**Issue by SmallJoker** [minetest/minetest_game#2547]
The attachment position of the wielded item (wield3d mod) jitters in two frames. The attached entity suddenly swaps position with the left hand's back side (180° rotation).

**Affected bones:**
 * `Arm_Right`
 * `Arm_Left` (swapped again)

**Affected frames:**
 * `182`: Entity is attached to the back side of the left hand
 * `187`: Entity is attached an arm-length above the player's head

**How to reproduce:**
1) Install the mod `wield3d`
2) Walk, to see frame 168 ... 187 (inclusive?)
3) The attached entity swaps positions in certain frames
```diff
@ minetest_game/mods/player_api/init.lua

-               walk      = {x = 168, y = 187},
+               walk      = {x = 182, y = 182},

-               {x = 168, y = 187},
+               {x = 182, y = 182},
```

**Comment by LoneWolfHT** [comment]
I see this too, at least the teleportation to the left hand and rotation.

With the model I made for Nodecore I get the attached bandolier ents flipping 180 degrees along the MT y axis whenever a bone is rotated in my animation
Haven't gotten around to reporting until now. Bit lazy about setting up an example mod. Which I guess I can force myself to do if requested

**Comment by An0n3m0us** [comment]
Slow motion video of the glitch:

https://my.pcloud.com/publink/show?code=XZtUChkZ8iKSd5GBsRugXBhSbGLnWhoviTU7

**Comment by LoneWolfHT** [comment]
We get this in the Nodecore game too, I think this is an engine bug

**Comment by SmallJoker** [comment]
Very likely fixed by https://github.com/minetest/minetest/pull/9577.
