### ISSUE TITLE
Grass footstep sounds are now in stereo which causes problems

### ISSUE THREAD

**Issue by fluxionary** [minetest/minetest_game#2548]
#2538 turned the grass footstep sounds into stereo audio files. Trying to use stereo sound files for positional sounds causes them to be audible at the same volume anywhere on the server. 

See https://dev.minetest.net/Modding_Tips#Positional_sounds_are_either_full_volume_or_completely_silent

To test:
* Create a new world
* Log in w/ 2 players.
* Put them in an area w/ grass
* Teleport one far away (but not beyond player_transfer_distance)
* Have the other player walk around on the grass
* Far away player will hear the sounds.

**Comment by sfan5** [comment]
@kevin-nel

**Comment by paramat** [comment]
LOL i will fix this.

**Comment by paramat** [comment]
PR #2549

**Comment by kevin-nel** [comment]
Wow, sorry 🤦‍♂️did not notice I bounced them to stereo
