### ISSUE TITLE
Add wild cotton as source of agricultural cotton seed

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2551]
Cotton seed from junglegrass makes no sense (the species are very different) and is based on old Mapgen V6 biomes where the variety of flora was very limited and mostly hardcoded. Wheat seed came from grass so cotton seed was chosen to come from junglegrass.

In the farming mod i suggest adding a 'wild cotton' decoration to the suitable biome(s).
It should have lowish density so that use of the farming mod does not overcrowd decorations, and so that it is not too easy to find.
Cotton from junglegrass may unfortunately still have to happen to avoid disruption.
A benefit is that, assuming junglegrass still drops cotton seed, having these seeds available in multiple biomes makes them a little easier to find.

I can do the work but would like concept approval and support from a core dev first.

**Comment by paramat** [comment]
Got my cotton and wheat mixed up.

**Comment by paramat** [comment]
Core devs: Any support or objections?

**Comment by sfan5** [comment]
Sounds fine to me.
> Cotton from junglegrass may unfortunately still have to happen to avoid disruption.

How about making junglegrass additionally drop cotton with a low chance?

**Comment by paramat** [comment]
Thanks, i might start work on this then.
> How about making junglegrass additionally drop cotton with a low chance?

Fine for me.

**Comment by rubenwardy** [comment]
I support this

> How about making junglegrass additionally drop cotton with a low chance?

This already happens

**Comment by paramat** [comment]
Thanks.
I assumed sfan5 meant that junglegrass would continue to drop but at a lower chance.

**Comment by paramat** [comment]
History of cotton:

https://en.wikipedia.org/wiki/Cotton
"The earliest evidence of the use of cotton in the Old world, dated to 5500 BCE and preserved in copper beads, has been found at the Neolithic indian site of Mehrgarh, at the foot of the Bolan Pass in Balochistan, Pakistan."
https://en.wikipedia.org/wiki/Gossypium_arboreum
"Gossypium arboreum, commonly called tree cotton, is a species of cotton native to India, Pakistan and other tropical and subtropical regions of the Old World. There is evidence of its cultivation as long ago as the Harappan civilization of the Indus Valley for the production of cotton textiles."

So i will choose biomes based on 'tropical, subtropical, Indus Valley'.
Indus Valley seems to be desert / grassland / savanna / tropical-subtropical dry forest.
Being in 'grassland' biome seems a little too easy as wheat seeds are there too. Grassland seems unsuitable as it is often far from being subtropical.
In 'rainforest' is nicely consistent with the previous source from junglegrass.
So maybe in 'rainforest' and 'savanna' MT biomes, 2 biomes is good to make it a little easier to find.

**Comment by paramat** [comment]
"Tree cotton is a shrub attaining heights of one to two metres. Its branches are [...] purple in colour."

![450px-Gossypium_arboreum1](https://user-images.githubusercontent.com/3686677/73573856-43085e00-446c-11ea-9d05-8711bf50d128.jpg)

**Comment by paramat** [comment]
Texture wanted.

The code part of this will be easy, but i am not good at plant textures, would any talented texture artist (@Extex101 ?)like to submit a texture for this?

A 16x16 texture that will be used as a "plantlike" drawtype.
The plant should fill the full height (16 pixels) but be a little narrower than 16 pixels wide.
It should have a few recognisably cotton-like seed pods with clumps of fluffy white fibres.
See images and description above: purple branches.

**Comment by Extex101** [comment]
I'd be glad to

**Comment by paramat** [comment]
Good to know, thanks.

**Comment by Extex101** [comment]
![temporary_1583432954011](https://user-images.githubusercontent.com/33675971/76013274-82432800-5ecc-11ea-8ada-7703befea847.png)

**Comment by paramat** [comment]
Thanks, will test in -game.

**Comment by paramat** [comment]
PR #2627

@Extex101 i have assumed CC BY-SA 3.0 as with your other MTG textures, i hope this is ok for you.
