### ISSUE TITLE
Audio not played for other clients

### ISSUE THREAD

**Issue by An0n3m0us** [minetest/minetest_game#2562]
I'm not sure if this one is intended or not; the sounds for placing and digging nodes aren't played for other clients on the server. I've made a video below demonstrating it:

Client 1 has the audio muted and is digging/placing nodes. Client 2 has audio on and is doing nothing. We can hear the footsteps of client 1(which seem to have a delay), but not the digging and placing of nodes.
https://my.pcloud.com/publink/show?code=XZEx42kZc2xcqejzytLFfJg1At24bF1pBCvV

Using `on_construct` and `minetest.sound_play()` in the node definition will play the sound for all of the clients when one client places a block.

**Comment by SmallJoker** [comment]
Duplicate of https://github.com/minetest/minetest/issues/7996

**Comment by An0n3m0us** [comment]
Closing issue
Reason: Duplicate
