### ISSUE TITLE
Papyrus wants default:dirt but only default:dry_dirt exists in savanna_shore biome

### ISSUE THREAD

**Issue by o11c** [minetest/minetest_game#2577]
Unless I'm completely missing something, 5.1.0 generates no papyrus at all, since it includes #2422 (which broke this) but not #2535 (which added an alternative).

**Comment by An0n3m0us** [comment]
Do you mean specifically in a savanna biome or all of the biomes? I found naturally occuring papyrus on dirt in a jungle biome (Minetest 5.2.0 dev)

**Comment by paramat** [comment]
Sorry for this bug, i will fix it soon using a second papyrus schematic.

**Comment by paramat** [comment]
PR #2580
