### ISSUE TITLE
Inner and Outer Stairs translation is broken in external mods in non-english languages

### ISSUE THREAD

**Issue by louisroyer** [minetest/minetest_game#2582]
In [stairs module](https://github.com/minetest-game-mods/stairs): 
Since in `init.lua` at lines 488 and 490, registration is done as
```lua
stairs.register_stair_inner(subname, recipeitem, groups, images, "",
    sounds, worldaligntex, S("Inner " .. desc_stair))
stairs.register_stair_inner(subname, recipeitem, groups, images, "",
    sounds, worldaligntex, S("Outer " .. desc_stair))
```
instead of
```lua
stairs.register_stair_inner(subname, recipeitem, groups, images, "",
    sounds, worldaligntex, S("Inner @1 Stair", desc_stair))
stairs.register_stair_inner(subname, recipeitem, groups, images, "",
    sounds, worldaligntex, S("Outer @1 Stair", desc_stair))
```
External mods cannot have Inner and Outer Stair rendered correctly when using this function.
As example, nether mod use `stairs.register_stair_and_slab` with `"Nether Stair"` as `desc_stair` parameter, and with translation support in minetest-mods/nether/pull/15, will use it with `S(Nether Stair")`.

In french, this result in `Inner Escalier du nether` and `Outer Escalier du nether` instead of `Escalier intérieur du Nether` and `Escalier extérieur du Nether`.

Since `S("Inner" .. desc_stair)` cannot take translations from external mods locales files, this cannot be solved without changing the format of the `desc_stair` which would be like `Wooden` or `Nether` instead of `Wooden Stair` or `Nether Stair` would and this requires changing all translations in stairs mod’s locales, but also breaking api in some kind: for the moment, this works well for english-only mods, but this change would result in external mods using this function having twice the word Stair in resulted descriptions of stairs they have defined.

Considering all the above, should we do this change ?

**Comment by SmallJoker** [comment]
This almost happened in other MTG mods too.. apparently this case was missed.

Affected code: (link)
https://github.com/minetest/minetest_game/blob/176ddba1761fe0d9a7031dae7873033e7f089084/mods/stairs/init.lua#L487-L490
Also hidden:
https://github.com/minetest/minetest_game/blob/176ddba1761fe0d9a7031dae7873033e7f089084/mods/stairs/init.lua#L326

**Comment by sfan5** [comment]
> in init.lua at lines 488 and 490, registration is done as

The function you linked is local to the stairs mod, it can not be called from other mods and how it does translation is irrelevant.

> `S("Inner @1 Stair", desc_stair)`

This was intentionally not done and an incorrect way to go about translation.
Imagine a language where "inner wooden stair" is written in a different order than "inner stone stair", such a case would be impossible to translate if you use `S()` like this.

<hr>

You can achieve correct translations by doing it the same as the function you linked:
```lua
local S = minetest.get_translator("nether")

local function stair_slab_register(subname, recipeitem, groups, images,
		desc_stair, desc_slab, sounds, worldaligntex)
	stairs.register_stair(subname, recipeitem, groups, images, S(desc_stair),
		sounds, worldaligntex)
	stairs.register_stair_inner(subname, recipeitem, groups, images, "",
		sounds, worldaligntex, S("Inner " .. desc_stair))
	stairs.register_stair_outer(subname, recipeitem, groups, images, "",
		sounds, worldaligntex, S("Outer " .. desc_stair))
	stairs.register_slab(subname, recipeitem, groups, images, S(desc_slab),
		sounds, worldaligntex)
end

stairs.register_stair_and_slab(
	"nether_brick",
	"nether:brick",
	{cracky = 2, level = 2},
	{"nether_brick.png"},
	"Nether Stair",
	"Nether Slab",
	default.node_sound_stone_defaults()
)
```
The will give you the following strings to translate:
<pre>
Nether Stair=
Inner Nether Stair=
Outer Nether Stair=
Nether Slab=
</pre>

**Comment by louisroyer** [comment]
Would it be possible to change
```lua
function stairs.register_stair_and_slab(subname, recipeitem, groups, images,
		desc_stair, desc_slab, sounds, worldaligntex)
		desc_stair, desc_slab, sounds, worldaligntex)
	stairs.register_stair(subname, recipeitem, groups, images, desc_stair,
		sounds, worldaligntex)
	stairs.register_stair_inner(subname, recipeitem, groups, images, desc_stair,
		sounds, worldaligntex)
	stairs.register_stair_outer(subname, recipeitem, groups, images, desc_stair,
		sounds, worldaligntex)
	stairs.register_slab(subname, recipeitem, groups, images, desc_slab,
		sounds, worldaligntex)
end
```
to
```lua
function stairs.register_stair_and_slab(subname, recipeitem, groups, images,
		desc_stair, desc_slab, sounds, worldaligntex, full_desc_stair_outer, full_desc_stair_inner)
stairs.register_stair(subname, recipeitem, groups, images, S(desc_stair),
		sounds, worldaligntex)
	stairs.register_stair_inner(subname, recipeitem, groups, images, desc_stair,
		sounds, worldaligntex, full_desc_stair_inner)
	stairs.register_stair_outer(subname, recipeitem, groups, images, desc_stair,
		sounds, worldaligntex, full_desc_stair_outer)
	stairs.register_slab(subname, recipeitem, groups, images, S(desc_slab),
		sounds, worldaligntex)
end
```
This would keep compatibility while allow to get expected behaviour without redefining this function in all modules using stairs.

**Comment by Wuzzy2** [comment]
I suggest to close this as invalid.

I have 0 problems with the German MTG translation in 5.1.1. Inner and outer stairs work 100%.

**Comment by Wuzzy2** [comment]
Oh, sorry, I see now this was about external mods. Never mind.

**Comment by paramat** [comment]
Removing 'invalid' as the later request above and the corresponding PR #2584 is supported.
