### ISSUE TITLE
Add varieties of mese post light

### ISSUE THREAD

**Issue by TooDumbForAName** [minetest/minetest_game#2597]
Right now, there is only one variety of mese post light (default:mese_post_light). I propose that additional varieties be added, to match the existing fence types. For example, default:mese_postlight_junglewood, default:mese_postlight_pine_wood, default:mese_postlight_acacia_wood, and default:mese_postlight_aspen_wood. This would enable users to have post lights that they can place on any of the existing default fences, without compromising the look with a mismatched light.

**Comment by paramat** [comment]
The request is fine, but looking at what MTG tends to include, we usually do not have a range of all wood types for every node that includes wood, because the number of nodes would then explode. Due to this i am uncertain, an optional mod could (and perhaps should) do this instead.

**Comment by paramat** [comment]
PR #2599

**Comment by sfan5** [comment]
Shouldn't this also be closed due to #2710?

**Comment by paramat** [comment]
Correct, i only closed feature requests without corresponding PRs. We still need to decide which existing PRs progress. I think that if an existing PR is supported and progresses then the corresponding issue is best left open until merge.
