### ISSUE TITLE
Support jumping, sneaking and walking backwards animations in player_api

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest_game#2610]
Support for jumping and sneaking animations in the player_api
I'm not saying to add jumping and sneaking animations to the player. But to add support for mods that want to add jumping or sneaking animations
Edit: and walking backwards

**Comment by paramat** [comment]
Walking backwards? Seems low priority.

**Comment by Extex101** [comment]
I might submit a PR for this tommorow

**Comment by runsy** [comment]
My vote for this!

**Comment by orbea** [comment]
This issue is related.

https://github.com/minetest/minetest_game/issues/2294

**Comment by paramat** [comment]
Closing due to #2710
