### ISSUE TITLE
player_api should disable knockback when player_api.player_attached[name] is set

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest_game#2619]
For example, `beds` sets player_attached when the player is in bed and is supposed to be immovable.
This caused a bug where you the player could fly off the bed, because beds didn't handle knockback.

But since other mods are coded identically (e.g. [ts_furniture](https://github.com/minetest-mods/ts_furniture)), it would make sense to fix this issue for once and disable knockback <i>inside player_api</i> if a player is set to be attached.

thoughts? @SmallJoker @paramat

**Comment by SmallJoker** [comment]
Yes, disabling the knockback feature for this case would be a good solution.

**Comment by paramat** [comment]
Seems good .

**Comment by An0n3m0us** [comment]
Need to remove it out of [#2566](https://github.com/minetest/minetest_game/pull/2566/files#diff-7726ca3d4d173bb4c8cadea80cda435eR255) after this.
