### ISSUE TITLE
There is ambiguous license information in the player_api README.txt.

### ISSUE THREAD

**Issue by poikilos** [minetest/minetest_game#2621]
In README.txt in player_api, there is the part that is not clear:
```
stujones11 (CC BY-SA 3.0):
  character.b3d
  character.blend -- Both derived from a model by MirceaKitsune (CC BY-SA 3.0)

An0n3m0us (CC BY-SA 3.0):
  character.b3d
  character.blend -- Player animation improvement
```

**Comment by sfan5** [comment]
What is not clear here?
`character.b3d` and `character.blend` are derived from a model by MirceaKitsune, licensed under CC BY-SA 3.0 and were modified by stujones11 and An0n3m0us.

**Comment by paramat** [comment]
Perhaps the `Player animation improvement` comment should refer to both items of media? It looks like it refers to `blend` only.

However, perhaps both media items should be licensed under `An0n3m0us` only, with comments detailing the history and mentioning MirceaKitsune and stujones11?
When media is altered, the credit goes to the most recent person to work on it, here we have a possibly unnecessary credit?

The original model was by MirceaKitsune. stujones11 implemented the correction of proportions and removal of cape for MTG 5.0.0, An0n3m0us added walk bobbing and reduced breathing amplitude.

**Comment by poikilos** [comment]
@paramat Thanks. I see that the first commit back in the one in the default directory is 2015, but the commit message (even for the first commit) talks about changes.

Where was it in version control before that? We may be able to put a year on it while we're reviewing this wording.

**Comment by TumeniNodes** [comment]
https://github.com/minetest/minetest_game/commit/609646b9b525982018fa1315e4bc3a1e07b9d6c2

You will want to look at commits from both https://github.com/minetest/minetest_game/commits?author=MirceaKitsune
and 
https://github.com/minetest/minetest_game/commits?author=Jordach
to follow the history of the player model (not sure whom else has contributed to it aside from them)

**Comment by poikilos** [comment]
@TumeniNodes Thanks. I see now that it was authored by MirceaKitsune in default, but was originally called player (.x and .blend). One player_api commit says "...remove cape" ("Player model: Remove vertical stretch of body and limbs, remove cape") so that is definitely the caped one. However, in the [history of that one](https://github.com/minetest/minetest_game/commits/master/mods/player_api/models/character.b3d) (character.b3d) says, "Added a caped player model, which works like the"--so, did @Jordach make it from scratch (making it not a version of the MirceaKitsune one, but rather a work-alike replacement)?

**Comment by An0n3m0us** [comment]
`character.b3d` is just the blend file exported to the B3D format. They're the same model, just in a different format.

**Comment by poikilos** [comment]
@An0n3m0us I realize that, but good point. I checked the blend file history. Oddly, there is no message indicating when the cape was added (in the [blend file history in the player_api mod](https://github.com/minetest/minetest_game/commits/master/mods/player_api/models/character.blend), where the b3d had that message). Is there any explanation for that, or was it just not noted? Either way, it seems that since there is no "add" or "replace" wording in the blend file history, that Jordach's is based on the 2012 MirceaKitsune model. It seems safe to say unless Jordach responds otherwise.

**Comment by TumeniNodes** [comment]
possibly in here somewhere https://github.com/minetest/minetest_game/search?q=character&type=Commits
Happy hunting ; )

**Comment by poikilos** [comment]
@TumeniNodes Thanks, but I think it is clear now, unless Jordach has something to say. The only problem now is the original issue, that being the wording of the license (not so much the content). There are a few problems: "both" is after one item on the list, and the word isn't even necessary since the b3d is from the blend file; regardless, visually, the annotation is after one of the files and applies to both; There are two separate entries for the same set of files, resulting in 7 lines to describe 2 files. The suggestion below (assuming that Jordach's work is no longer in it since the cape is gone, otherwise he would be after MirceaKitsune) may not be what people ultimately prefer, but it seems to make more sense:
```
MirceaKitsune, stujones11, An0n3m0us (player animation improvement) (CC BY-SA 3.0):
  character.b3d
  character.blend
```

**Comment by TumeniNodes** [comment]
I have seen situations where the original author is mentioned this way, and then a line along the words of "and other contributing members" (which I feel works fine) but core devs should make that call.

Continuously adding all who make adjustments to the original could become quite long after some time.

Jordach and sofar both also worked on the model, adding improvements over time

**Comment by paramat** [comment]
> MirceaKitsune, stujones11, An0n3m0us (player animation improvement) (CC BY-SA 3.0):
  character.b3d
  character.blend

The details after 'An0n3m0us' are inconsistent, details of what each person did should be present, or no details for any person.
I suggest waiting for @Jordach to inform us more about the history, i expect his name should be included here too.

poikilos, the historys you linked only go back to when player_api mod was recently split from default mod, we need to trace the history of these files in the default mod history.

**Comment by TumeniNodes** [comment]
Maybe after the initial author of the model, source file and credits and license...
simply add `contributors` and then list each name.

If anyone has further interest they can always trace the contributor's history via github

**Comment by TumeniNodes** [comment]
> @TumeniNodes Thanks, but I think it is clear now (using all information available), unless Jordach has something to say. The only problem now is the original issue, that being the wording of the license (not so much the content). There are a few problems: "both" is after one item on the list, and the word isn't even necessary since the b3d is from the blend file; 
> ```

It _is_  necessary, as credit is being given for the source file `.blend` , and the raster file the `.b3d` file which were submitted by the author at the time.

**Comment by paramat** [comment]
I will make a PR, as i have searched all history now.

**Comment by paramat** [comment]
PR #2741
