### ISSUE TITLE
Proposition for big change regarding Apple Trees

### ISSUE THREAD

**Issue by TumeniNodes** [minetest/minetest_game#2623]
Just a thought (and possibly will not be a popular one)

Apple trees are not common/natural in deciduous forests...

Anyone opposed to or for me moving apple trees over into farming... and only grow when planted?
(or perhaps still in farming but be extremely rare in the forests?, as one still needs a means to obtain apple seeds to grow them in this case)
And replace them in the deciduous forest with another tree such as maple, or hickory, ~or even ash or something?~
I would say oak but... you know... "mc"
Maple may be a good choice, as we can then add (or via a 3rd party mod) a means to extract the sap for food recipes...

Though Hickory trees could be a much better option, as they produce nuts which can be a food source/ingredient
https://homeguides.sfgate.com/uses-hickory-tree-99445.html

Part of my thought is also related to path finding, and player movement.
Low apple trees can be a hindrance to both, and often annoying when navigating forests.

**Comment by rubenwardy** [comment]
I'm against this. Apples are the only natural food source and are needed in early game

**Comment by TumeniNodes** [comment]
> I'm against this. Apples are the only natural food source and are needed in early game

Which is why I am suggesting Hickory as a replacement, as it produces nuts, and we can give them the properties apples currently use as far as an early food source.

And apple trees could still be found in a forest, just extremely rare.
And only because you need to get apple seeds to plant from somewhere.
So if the progression toward being able to grow apple trees is made fairly easy, then I feel this would be less of a problem

**Comment by paramat** [comment]
:-1:
Apple trees (of some form) do exist in the wild.
Too much disruption and work for very little or no benefit.
Removes the basic food source from default mod (some may not be using farming mod).
Farming mod is for agriculture, apple trees can be considered a wild and natural source of fruits. A player starts the game with no agriculture and it is obviously useful to have a wild source of food.

**Comment by Extex101** [comment]
Woah, that's a lot of edits paramat. Lol
I think this is a good idea!
The only thing I'm concerned about is that it may be easier for new players to realize apples as food than nuts in a tree. 

Keep in mind that @TumeniNodes isn't saying to remove apple trees or make them rare. He's just saying to put not to put them in the deciduous biome.
In fact apple trees don't even grow in deciduous areas.
(It would make more sense for Figs, nectarines or stone fruit see [here](http://www.grangettosnews.com/news/12/05/fruittreetypes.html) for more information) 
In fact our deciduous forests don't really look anything like they actually do.

![COOLIO](https://million-wallpapers.com/wallpapers/5/99/516158923317861/deciduous-forests.jpg)
![Ö ¬~# STICK EM UP!](https://www.muralsyourway.com/media/catalog/product/cache/1/base/1200x/040ec09b1e35df139433887a97daa66f/f/o/forest-sun-wallpaper-mural.jpg)
(Sry about having so many comments containing reference images. Besides the fact that these pics are GORGEOUS!! Lol)

**Comment by paramat** [comment]
> Keep in mind that TumeniNodes isn't saying to remove apple trees or make them rare

They are saying to make them 'extremely rare' to get the initial seeds.
> In fact apple trees don't even grow in deciduous areas.

Interesting ...
"From DNA analysis, we now know that the primary ancestor of all the apples we eat is the wild apple tree native to the forested slopes of Tian Shan, the ‘heavenly mountains’ of eastern Kazakhstan."
Which seems to be mostly coniferous forests. However, now they do grow in temperate deciduous areas. I think they would look more out of place in the coniferous forest. So i think they should stay in the deciduous forest biome.

**Comment by Extex101** [comment]
Oh wait... I just realized that all forests that have apple tree are deciduous forests...
How are aspen trees placed? Because I always thought that the areas with aspen was a separate biome..

Ok so I think that hickory or whatever should go in the place of apple tree in areas with aspen... XD (Feel like I've got no idea what I'm talking about. And I probably dont lol)

**Comment by TumeniNodes** [comment]
Closing. Makes more sense to do in another game, than to make such a drastic change in MTG
