### ISSUE TITLE
'spawn' mod should have an API

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest_game#2630]
### Problems

- When you install a mod such as [Ethereal](https://forum.minetest.net/viewtopic.php?t=14638) or [Australia](https://forum.minetest.net/viewtopic.php?t=14412) that clears the biomes and registers its own, respawning does not work.
Even though this is fixed by #2631, such mods still cannot make use of MTG spawning code since there is a hardcoded whitelist of 5 biomes.
- The `spawn` mod includes beds-specific support code, this is unportable and third-party mods do not have this opportunity.
https://github.com/minetest/minetest_game/blob/fbbc7fc9969a86ad820be68b2e5ad5b495629759/mods/spawn/init.lua#L151-L153

### Suggestions

- `spawn` should have an API that allows mods to add biomes they deem suitable for spawning.
`default` should use this API itself.
- To allow interoperability, `spawn` should accept registrations from other mods to allow them to override the (re-)spawn position.
`beds` would then call `spawn.register_on_respawn` instead of the Minetest API. `spawn` would call its registered callbacks or fall back to its own spawning code.

**Comment by paramat** [comment]
See #2117 and #2257 
It was then suggested that part of the API should be moved to builtin (which has not been done yet) so #2257 is WIP and would need a rework.
Although somewhat of a duplicate i think this issue should stay open as it has more useful detail and suggestions than #2117 , perhaps we should close that one instead?
:+1:

**Comment by sfan5** [comment]
I'd say keep both open.
Making the spawn algorithm a public API function is also something I'd expect from an improved `spawn` mod.

**Comment by paramat** [comment]
See https://github.com/minetest/minetest_game/pull/2257#issuecomment-611135137
I suggest someone could adopt that PR, alter it if necessary, and merge it. Moving some code to builtin could perhaps be done later.

**Comment by FaceDeer** [comment]
I just ran into some trouble trying to override default game's spawning behaviour myself and on digging through the code found the "engine_spawn" setting. If you add engine_spawn=true to minetest.conf then it will disable this mod and let other mods have their way with dead players.

However, this strikes me as an unhappy hack. I didn't find any documentation for "engine_spawn" but I'm assuming based on its name and behaviour that it's supposed to cause Minetest to fall back to the engine's player spawning system when set. So I would assume that my own mod should also be disabling its spawning code when engine_spawn is true, and I'm being a naughty modder by ignoring that setting.
