### ISSUE TITLE
Crash when mods call tnt.boom(), when TNT is disabled

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest_game#2634]
It seems that get_content_id will crash minetest if the node no longer exists (didn't before), so when TNT is disabled on a game and there's a boom it'll crash the game because tnt:tnt is no longer registered...  I've added a quick change to tnt mod init.lua:295 to stop this on server:
```
local c_tnt
if enable_tnt then
	c_tnt = minetest.get_content_id("tnt:tnt")
else
	c_tnt = minetest.get_content_id("tnt:tnt_burning")
end

**Comment by sfan5** [comment]
Who is calling `tnt.boom()` though?
Since the TNT node isn't even registered, it can't explode.

**Comment by rubenwardy** [comment]
Mods may be using it for custom explosives

**Comment by tenplus1** [comment]
Yep, tnt.boom() is used for many other mods like mobs and lucky blocks etc. and even if the node tnt:tnt_burning is placed it still uses that function to explode.
