### ISSUE TITLE
Tools break nodes without wear without the correct capabilities.

### ISSUE THREAD

**Issue by orbea** [minetest/minetest_game#2650]
##### Minetest version
```
$ minetest --version
Minetest 5.2.0 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/usr/share/minetest"
```

##### Summary

I have noticed that sometimes when using any tool that doesn't have the correct tool capability to break a node, the node will still break and the tool will incur no wear. This leads to the impression that these tools are able to break these nodes infinitely with no consequences.

However what is happening under the hood in the engine code is that it detects the tool does not have the correct capability, but does determine that the node can be broken by the player's hand and falls back to that silently. Before I spent time putting printf all over the engine code base I was rather confused about this and I imagine I am not the only one.

I think this can be improved by making all of the tools capable of breaking nodes that the hand can also break, but when it does not have the correct capability it will do so at a slower rate, higher wear and fewer uses. This would reward players for using the correct tools or by explicitly using a non-tool item (hand) when applicable.

I am not sure if this is better handled in the engine or in MTG? If it was handled in the engine this would be presumably fixed for all tools in third party mods too.

Otherwise it can be left alone and considered as not a bug at the risk of confusing users and having less gameplay mechanics.

If this is going to be fixed in MTG then PR https://github.com/minetest/minetest_game/pull/2649 would be beneficial in reducing the burden to solve this.

##### Steps to reproduce

Dig dirt with a sword, pick or axe. 

Note: This affects any node that is `crumbly` or has `oddly_breakable_by_hand`. Its probably fine to let this be for `snappy`.

**Comment by SmallJoker** [comment]
That's because Minetest uses the hand to dig them; not the tool.

https://github.com/minetest/minetest_game/blob/36b2bcb5f3379cfc28b74974ce74e965821d1493/mods/default/tools.lua#L15-L17

**Comment by orbea** [comment]
> That's because Minetest uses the hand to dig them; not the tool.

Yes I know,, I explained as much in the OP.

Regardless maybe this can be improved?

**Comment by SmallJoker** [comment]
https://github.com/minetest/minetest/issues/5844

**Comment by orbea** [comment]
Yes, thanks, I didn't find that one, do you think its better fixed in the engine or by tweaking the tools in MTG?

**Comment by SmallJoker** [comment]
First of all it must be clear whether the hand toolcaps should be ignored when a tool is used, or whether to use the shortest dig time of both (hand or tool). IMO this is a concept discussion, where the decisions should then be applied to the Minetest Engine - and perhaps to minetest_game (if needed).
Taking the faster dig time would be handy, but the hand realistically cannot be used when you're holding a shovel. Also changing the default toolcaps doesn't make much sense, because a pickaxe is very useless for digging dirt. Thus I don't have any opinion on this topic.

**Comment by orbea** [comment]
> Also changing the default toolcaps doesn't make much sense, because a pickaxe is very useless for digging dirt. Thus I don't have any opinion on this topic.

Exactly, so one idea would be to give a pickaxe `crumbly`, but with worse wear, usage and speed than it's `cracky` or the equivelent shovel's `crumbly`.
