### ISSUE TITLE
Change to GitHub actions

### ISSUE THREAD

**Issue by Panquesito7** [minetest/minetest_game#2653]
GitHub actions is faster, better and easier to use.
I think it would be nice to change to GitHub actions.

Besides, the [Minetest](https://github.com/minetest/minetest) repository is [now using](https://github.com/minetest/minetest/pull/9641) GitHub actions.

**Comment by paramat** [comment]
This seems fine to me.

**Comment by Panquesito7** [comment]
Shall I use the same method that is implemented in [Minetest](https://github.com/minetest/minetest/blob/master/.github/workflows/lua_lint.yml)?
