### ISSUE TITLE
heart.png and bubble.png are distorted

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#2655]
The heart and bubble textures look kind of distorted.

Probably that's because 12×12 is expected, but 16×16 is the actual texture size.

2 possible solutions:

* A: Change the texture size to 12×12
* B: Overwrite the builtin statbars to use MTG's size

**Comment by SmallJoker** [comment]
Related: https://github.com/minetest/minetest/pull/9237

**Comment by paramat** [comment]
I prefer solution A.

**Comment by sfan5** [comment]
Perhaps the engine should just fix its texture scaling.

**Comment by An0n3m0us** [comment]
I prefer an engine change; but a 12x12 heart icon could probably work:
![image](https://user-images.githubusercontent.com/49789044/80307499-5c961900-87c1-11ea-924a-85f551f656d9.png)

Top: 16x16
Bottom: 12x12
![image](https://user-images.githubusercontent.com/49789044/80307504-6750ae00-87c1-11ea-8201-7c8b16da3104.png)

**Comment by sfan5** [comment]
Note that the default size of these icons isn't 12x12 but 24x24, so they shouldn't be scaled down to 12x12:
https://github.com/minetest/minetest/blob/6c607e20828f97f950038dfb86891a74afb6f755/builtin/game/statbars.lua#L12

**Comment by sfan5** [comment]
Applying the engine's gui scaling filter (scales to 24x24) to the images would look like this (old | new):
![screenshot_20200513_201510](https://user-images.githubusercontent.com/1042418/81855986-64dfa980-9560-11ea-9759-0d387b40bba7.png)
![screenshot_20200513_201135](https://user-images.githubusercontent.com/1042418/81855975-6315e600-9560-11ea-8ed9-ad0ccefb3e25.png)

Looks much less pixel art-y so maybe not desirable to use these.

**Comment by paramat** [comment]
Ok, 24x24 then.

I prefer crisp pixel art to what that scaling filter does.

**Comment by Wuzzy2** [comment]
Is there any way to disable the scaling filter for the statbar icons?

**Comment by sfan5** [comment]
The scaling filter is not enabled by default, but if someone chooses to enable it you cannot avoid it.

**Comment by An0n3m0us** [comment]
I prefer crisp pixel art too.

**Comment by Wuzzy2** [comment]
So this issue can't be fixed at all? No matter what we do, we always might end up with blurry textures if a user decides to use weird settings?

Is there really no way to force pixel art in the statbars?

**Comment by sfan5** [comment]
> we always might end up with blurry textures if a user decides to use weird settings?

Yes? The user gets what he chooses.
When the size on screen is not evenly divisible by the texture size you can have either distorted scaling or smoother scaling (at the expensive of some blurriness).

**Comment by Wuzzy2** [comment]
So how should this issue be fixed in your opinion?

**Comment by sfan5** [comment]
Change the textures to be either 12x12 or 24x24 so they don't look distorted with default settings on the default DPI.

Long term the "gui scaling filter" (yes it's called that) in the engine should probably be improved if necessary and enabled by default so that textures do not look distorted if the user is on an "odd" DPI.
