### ISSUE TITLE
Turn on the alpha channel for glass and transparent objects.

### ISSUE THREAD

**Issue by CandyFiend** [minetest/minetest_game#2665]
I draw textures and I got the idea to make the obsidian door and glass 30% transparent. But I can’t do it, because by default, the alpha channel is off and if someone downloads my texturepack, he will not be able to see through the obsidian door and glass. And there are some problems with drawing, but this, if I understand correctly, is a problem with the engine. 
`use_texture_alpha = true,`
![screenshot_20200430_172731](https://user-images.githubusercontent.com/16528385/80700484-03ebb680-8b08-11ea-9d26-14cf99083530.png)
![screenshot_20200430_172736](https://user-images.githubusercontent.com/16528385/80700517-0ea64b80-8b08-11ea-8fba-83468d2a8718.png)
![screenshot_20200430_172740](https://user-images.githubusercontent.com/16528385/80700528-12d26900-8b08-11ea-9fb6-fbf970dcef78.png)
![screenshot_20200430_172754](https://user-images.githubusercontent.com/16528385/80700536-16fe8680-8b08-11ea-8da4-6aa5b443eb31.png)
![screenshot_20200430_172805](https://user-images.githubusercontent.com/16528385/80700541-182fb380-8b08-11ea-8799-a8d1c74f202e.png)

**Comment by CandyFiend** [comment]
I thought a little and made a new model for glass doors. In my opinion, it looks better, but for some reason transparency does not want to work correctly.
![screenshot_20200430_222208](https://user-images.githubusercontent.com/16528385/80728941-bbe18980-8b31-11ea-8427-0257e2302718.png)
![screenshot_20200430_222212](https://user-images.githubusercontent.com/16528385/80728949-be43e380-8b31-11ea-9f62-3827807c7cbe.png)
![screenshot_20200430_222220](https://user-images.githubusercontent.com/16528385/80728954-c00da700-8b31-11ea-91e2-00a32dadbf25.png)
![screenshot_20200430_222225](https://user-images.githubusercontent.com/16528385/80728960-c3089780-8b31-11ea-93d8-b7c4adf0be0b.png)
![screenshot_20200430_222318](https://user-images.githubusercontent.com/16528385/80728966-c56af180-8b31-11ea-89cb-e37646b9f400.png)
![screenshot_20200430_222338](https://user-images.githubusercontent.com/16528385/80728971-c69c1e80-8b31-11ea-989e-5272fff94403.png)
[door_models.zip](https://github.com/minetest/minetest_game/files/4559293/door_models.zip)

**Comment by SmallJoker** [comment]
This was intentionally disabled in #1003.

**Comment by paramat** [comment]
Semi-transparency is very buggy in MT.

**Comment by TumeniNodes** [comment]
It wreaks too much havoc in-game, visually glitchy.
You would like it at first for a bit, then become annoyed

**Comment by orbea** [comment]
Are there any issue reports for the underlying visual glitches? I rather like this idea, but I agree that it should not be done until it doesn't cause bigger problems.

**Comment by CandyFiend** [comment]
I’m studying the engine now and I’ll figure it out too, maybe there are workarounds.  For 6 years there have been no corrections for transparent textures, this is very bad.

**Comment by paramat** [comment]
See https://github.com/minetest/minetest/issues/95
Second oldest issue. It is not trivial to add depth-sorting for translucency.

**Comment by CandyFiend** [comment]
I also thought about it. this is not a problem that needs to be put off for 6 years. But her decision would help improve the overall impression of the game and expand the community. I do not program in C ++, so I can not do anything.

**Comment by paramat** [comment]
I think #1003 is higher priority than translucent doors, even though those look good. A mod can always override the node definitions if you want to do this. So closing, we can reconsider if alpha sorting is implemented.
