### ISSUE TITLE
grass block is very off putting.

### ISSUE THREAD

**Issue by kingsjack123** [minetest/minetest_game#2668]
the default grass block comes of as weird it even took me a few hours to realize why, it doesn't look like grass, it looks like leaves on the ground, when playing a game you pick up on the who sense and if you see something that doesn't fit the scene then it will come off as wired, this is true regardless of weather or not you consciously or unconsciously pick up on the inconsistency of the scenery, some people find this off putting and will just leave. 

i understand that the function of minetest is not to be a game itself but enable voxel games by functioning as its foundation, there for the real value ins in its programing and utility not its visual appeal, but you cant denies that a good looking set of textures cant be good for advertisement.

**Comment by SmallJoker** [comment]
minetest/minetest is for the engine development (modding API, rendering etc)
minetest/minetest_game is for the in-game content you're probably using

**Comment by TumeniNodes** [comment]
I've thought about putting up an almost entirely new TP for merge but tbh, everyone has different taste, and literally sees everything differently.
Which is usually why it is best just to offer alternative TPs to users.

Redoing the entire MTG default textures would be a very long and painful on the development process which not many could endure as an artist/designer, hence why _I_ have refrained from attempting it.

**Comment by paramat** [comment]
:-1: 
Looks good to me and was only recently added, it is also much better than all the ones that came before.
A huge amount of time, effort and discussion has gone into the grass textures we have used over the years. It is difficult to create and is so commonly seen. We do not change it casually.

Some people will always dislike this or that texture, this is obviously inevitable, so we cannot take much notice of individual texture complaints. You should simply use a partial or complete texture pack according to your taste. It is very likely that every player will deeply dislike 1 or more default textures in MTG.
> some people find this off putting and will just leave.

These people should override the texture or use a texture pack instead, there is no need to leave.
