### ISSUE TITLE
Death in cart is not handled correctly

### ISSUE THREAD

**Issue by random-geek** [minetest/minetest_game#2681]
I'm not sure if this has been mentioned before; I couldn't find a duplicate issue.

**Steps to reproduce:**

1. Create a new world
2. Place a cart somewhere
3. Get in cart
4. `/killme`
5. Now your eye level is wrong, and you have to right-click on the cart three times to get back in it.

**Comment by random-geek** [comment]
This seems to fix it, not sure if it's the right solution though:

```diff
function cart_entity:on_detach_child(child)
	if child and child:get_player_name() == self.driver then
		self.driver = nil
+		carts:manage_attachment(child, nil)
	end
end
```

**Comment by random-geek** [comment]
@SmallJoker b787fcf fixes the eye level problem, but `self.driver` still needs to be set to `nil`. In multiplayer, the cart still thinks it contains the driver who died, so no other players can enter the cart.

**Comment by SmallJoker** [comment]
@random-geek Thank you for pointing this out. I totally assumed the driver of the old parent (cart) was also handled in `carts:manage_attachment`, which is wrong. Will push another patch soon.
