### ISSUE TITLE
Duplication on Death

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest_game#2697]
Start a new world, give yourself 20x flowers:mushroom_red , eat until death occurs, check bones or drops and you have just duplicated your mushrooms.

Same goes for most items used and returned that cause harm to player.

**Comment by SmallJoker** [comment]
Duplicate of https://github.com/minetest/minetest/issues/6546

**Comment by tenplus1** [comment]
@SmallJoker - Apologies, a search didn't show it was a previous issue.
