### ISSUE TITLE
Papyrus spawns on Savanna Dirt but does not grow on it

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#2703]
Papyrus can generate on Savanna Dirt but can't grow on it (only Dirt and Dirt with Grass). Intentional?

**Comment by paramat** [comment]
Aha, another bug caused by the savanna dirt change. Will investigate.

**Comment by paramat** [comment]
https://github.com/minetest/minetest_game/blob/d03d7e9bdc4ab3325b632ed22338c1ab2c9b0a5c/mods/default/functions.lua#L210-L213

https://github.com/minetest/minetest_game/blob/d03d7e9bdc4ab3325b632ed22338c1ab2c9b0a5c/mods/default/functions.lua#L247-L250

Should grow on 'dry dirt with dry grass' too for consistency.
I will fix this for 5.3.0.

**Comment by Moth-Tolias** [comment]
is there no "fertile" group?

**Comment by paramat** [comment]
Hm there is a 'soil' group ...

**Comment by paramat** [comment]
I just realised, we cannot use the 'soil' group to decide because papyrus should only grow on nodes of the biomes it appears in, not on 'dirt with snow' or 'dirt with coniferous litter'. This is why the nodes are listed instead of using the 'soil' group.

PR #2705

**Comment by Moth-Tolias** [comment]
why should papyrus not grow on those nodes, though?

**Comment by jastevenson303** [comment]
I don't know about the litter, but, I have a hard time imagining much of
anything growing out of dirt_with_snow.

**Comment by LoneWolfHT** [comment]
Doesn't it turn to dirt if there is a node over it anyway?

**Comment by jastevenson303** [comment]
You mean dirt_with_snow?  I don't think so, but it's hard to tell from the
code so I'll have to test in-game.

**Comment by LoneWolfHT** [comment]
Unfortunately it looks like it isn't converted to dirt

**Comment by paramat** [comment]
> why should papyrus not grow on those nodes, though?

Because realistically papyrus is native to hot biomes, like rainforest or savanna.
('dirt with grass' is a temperate biome node, but this is only done for Mapgen V6 which places papyrus (wrongly) in grassland/forest areas.)
This is why the 'soil' group was not used to decide growth before now, nodes are checked to limit the areas it can grow in.
