### ISSUE TITLE
More ways to craft glass fragments

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#2709]
To make more glass items recycable, I propose these (shapeless) crafting recipes:

* 1 glass door → 6 glass fragments
* 8 glass panes → 3 glass fragments

**Comment by paramat** [comment]
There's more: glass nodes, glass stairs ...
I am wondering if this can be considered necessary maintenance or not, not sure if this should be closed.

**Comment by Wuzzy2** [comment]
Closing since nobody implemented this, and Minetest is in maintenance mode. No point in keeping (semi-)feature requests open forever.
