### ISSUE TITLE
Jumping and moving

### ISSUE THREAD

**Issue by themagicalcats** [minetest/minetest_game#2712]
Please make the movement a bit faster on walk and bit higher for jumping cause I've been playing for a bit and its getting annoying

**Comment by tenplus1** [comment]
This can be altered within a mod already using player physics override:

https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L6123

**Comment by SmallJoker** [comment]
For singleplayer, you can change following settings to walk faster:
https://github.com/minetest/minetest/blob/master/minetest.conf.example#L1445-L1498

Physics are not handled or modified by MTG. It's up to you whether you'd like to use a mod or change the settings to get the desired speeds.
