### ISSUE TITLE
No damage from falling if mounted on boats:boat

### ISSUE THREAD

**Issue by FeXoR-o-Illuria** [minetest/minetest_game#2721]
When a player is on a boat he does not get any damage when stopping no matter the height of the fall or the speed he is falling with or the block/item/whatever causing the fall to stop.

Reproduce:
1) build a tower of width and depth 1 and arbitrary height and place a water source on the top (To prevent the water to spread one can dig a moat around the base)
2) Place a boat on the water source, mount it and drive over the edge
3) Notice that no damage was dealt when hitting the ground (or whatever got in the way) to the character by falling

(While this may be really helpful to go down fast and secure through mine shafts it is clearly a bug)

**Comment by paramat** [comment]
Seems a low priority bug, but thanks for making us aware.
This situation is rare, the boat needs to be on water at the top of the drop, and this water will usually spread and fall to the base of the drop, in which case the boat lands in water.
Also generally, i think it is reasonable to choose to disable player velocity change damage when in a vehicle.

**Comment by FeXoR-o-Illuria** [comment]
I agree with "it is reasonable to choose to avoid player fall damage when in a vehicle".
So you are probably right about not considering a bug though it feels kindof cheaty to go down several 1000 blocks in a matter of seconds without the risk of fall damage ;)

**Comment by tenplus1** [comment]
I changed the boat so that any sudden stop which signals impact damages the boat, unmounts the player and drops wood and sticks where the boat was...  This seems more fun :+1: 

https://notabug.org/TenPlus1/boats

**Comment by paramat** [comment]
Considering my comment above, and considering that some servers might be dependent on current behaviour, even though i admit it seems a littel cheaty, i am closing this.
