### ISSUE TITLE
Mapping Kit does not work: Minimap does not open

### ISSUE THREAD

**Issue by andraaspar** [minetest/minetest_game#2726]
Hi,

I've found that the minimap does not open in minetest-5.3.0-win64. It does not work in creative mode either. I tried removing all mods & also tried a clean install. Have you got any suggestions?

Thanks

**Comment by andraaspar** [comment]
Also tested it in minetest-5.2.0-win64 and it worked just fine.

**Comment by SmallJoker** [comment]
Use V to open the minimap or change the key.

**Comment by andraaspar** [comment]
@SmallJoker : Whoa, am I an idiot. Sorry about that. I kept hammering F9. Because I was looking at https://wiki.minetest.net/Controls . Maybe it's worth updating. Thanks!
