### ISSUE TITLE
Edit repo GitHub tags

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2738]
One for @rubenwardy i guess.

I suggest removing these tags:
* 'hacktoberfest', to avoid generating unnecessary casual attention from coders unfamiliar with MT, and from one random coding event. Even more unnecessary now that MTG is feature-frozen and we are trying to divert attention away from it,.
* 'minetest-subgame', as we do not use that terminology anymore.

**Comment by paramat** [comment]
Coincidentally, #2748 was a hacktoberfest spam PR.

**Comment by rubenwardy** [comment]
done
