### ISSUE TITLE
Player API: Animation-dependent player model collisionbox

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest_game#2742]
##### Issue type
 - Feature request
 
##### Minetest version
Any I think

##### Summary

When a player dies, he leaves a dead body, which AFAIK only disappears when this player hits the respawn button. And this dead body has bad collision box & prevents for instance firearms from shooting through. IMO, dead body should disappear after 5 secs or so, and not only when respawn button is pressed. I know that might pose a problem, as the player entity has to be somewhere even while he's dead, but why not temporarily remove model & collisionbox, make them invisible ?

I'm pretty sure I can't change that outta a mod...

**Comment by paramat** [comment]
Obviously, some animations of a player model are likely to require a different collisionbox and eye_height, for example when sitting or laying down. But the player API is designed to have a single collisionbox and eye_height for all animations.
What i am thinking of is using SmallJoker's approach explained in https://github.com/minetest/minetest_game/pull/2184#issuecomment-424050175 , with collisionbox and eye_height defined as tables with values for each animation name.

It needs to be backwards compatible with registered models that do not have tables for collisionbox and eye_height. So considering collisionbox as an example i suggest this as an initial idea:

In `player_api.set_animation()`, the collisionbox field is tested for being a table or not.
If a table, set player collisionbox to the collisionbox determined by the animation being set.
If not a table (backwards compatibility or no need for differing collisionboxes), do nothing and so continue to use the model's single specified collisionbox.

Can anyone see any problems with this approach?
I am not sure if stepheight needs to alter per animation, but it could do with some uses.
`player_api.set_animation()` can already alter animation speed.

**Comment by appgurueu** [comment]
> Obviously, some animations of a player model are likely to require a different collisionbox and eye_height, for example when sitting or laying down. But the Player API is designed to have a single collisionbox and eye_height for all animations.
> What i am thinking of is using SmallJoker's approach explained in [#2184 (comment)](https://github.com/minetest/minetest_game/pull/2184#issuecomment-424050175) , with collisionbox and eye_height defined as tables with values for each animation name.
> 
> It needs to be backwards compatible with registered models that do not have tables for collisionbox and eye_height. So considering collisionbox as an example i suggest this as an initial idea:
> 
> In `player_api.set_animation()`, the collisionbox field is tested for being a table or not.
> If a table, set player collisionbox to the collisionbox determined by the animation being set.
> If not a table (backwards compatibility or no need for differing collisionboxes), do nothing and so continue to use the model's single specified collisionbox.
> 
> Can anyone see any problems with this approach?
> I am not sure if stepheight needs to alter per animation, but it could do with some uses.
> `player_api.set_animation()` can already alter animation speed.

That is the straightforward approach (except I would just check for falsy instead of checking for type)

**Comment by paramat** [comment]
PR #2743

**Comment by appgurueu** [comment]
Closed by #2745
