### ISSUE TITLE
Add a second mossy cobble node for patchy mossy cobble walls

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest_game#2747]
Currently the moss grows on a wall of cobble and in the end it's a wall of mossy cobble. In my opinion a repeated moss texture looks perceptionally unnatural when the texture is tiled on a big area (e.g. a big wall).
An alternative to this is patchy moss growth. I've opened a Pull Request (#2333) some time ago, but the related changes were rejected for performance reasons. Instead of patches which consist of cobble and mossy cobble, the ABM could use two mossy cobble nodes. The two mossy cobble textures would both contain moss but have a different growth structure drawn, and when a big area full of patchy mossy cobble is viewed from far away it would still look patchy.
The code could be something like this:
```lua
	-- node.name is initially "default:cobble" 
	if minetest.find_node_near(pos, 2, "default:mossycobble1") then
		node.name = "default:mossycobble2"
	else
		node.name = "default:mossycobble1"
	end
	minetest.swap_node(pos, node)
```

**Comment by sfan5** [comment]
I think that'd better be done in the engine using random textures (though it's unclear when that'll be implemented).

**Comment by HybridDog** [comment]
> I think that'd better be done in the engine using random textures (though it's unclear when that'll be implemented).

I'd like to see stochastic texture sampling in Minetest.
https://www.reddit.com/r/Unity3D/comments/dhr5g2/i_made_a_stochastic_texture_sampling_shader/
https://www.shadertoy.com/view/Xtl3zf

**Comment by paramat** [comment]
:-1: for multiple moss nodes, that is overkill for something that is not really a problem.
In real life, eventually the entire surface is covered too.
In MT, repeated textures are everywhere anyway.
We cannot start a precedent in MTG of multiple nodes for texture variation, and it would be insane to try to implement texture randomisation in Lua.
Engine texture randomisation is the correct approach, an issue exists.

Patchy cobble and mossycobble would make some sense, like how it appears in parts of dungeons, but dungeons also have continuous areas of moss, so continuous is consistent.

Besides all that, MTG is feature-frozen and this is not bugfix or essential maintenance.
