### ISSUE TITLE
Bush leaves should not wave

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2752]
![screenshot_20201015_180310](https://user-images.githubusercontent.com/3686677/96306838-5fe3c200-0ff8-11eb-8781-e6b138468e6f.png)

Bushes are small and rather 'stiff' (short branches), so the large amplitude slow swaying of waving leaves looks wrong.
Also, since bush leaves are adjacent to the ground, the mesh gap glitch is made very noticeable (see screenshot).
I can make a PR if other core devs agree.

EDIT:
Bush leaves are intended to give an alternative leaf for other uses such as hedges, hedge mazes etc., these should not wave. Not waving makes them more useful for alternative uses.

**Comment by sfan5** [comment]
The engine should probably support different intensities of waving, but until it does not waving sounds fine.
