### ISSUE TITLE
Creative shows nodes that should not be in creative inventory

### ISSUE THREAD

**Issue by Desour** [minetest/minetest_game#2754]
Burning TNT, burning gunpowder and bed top nodes shouldn't be in creative inventory imo, but they are.

**Comment by sfan5** [comment]
This is broken by https://github.com/minetest/minetest/commit/f3ae45b2b245dd0aeb4a7d9b76afaf078871104c

**Comment by Desour** [comment]
Ah, I see. It's because description is now set to name by default, in `.registered_`.
Mtg relies on being able to set no description.
`not_in_creative_inventory` groups should be added anyway.
Afaik `lua_api.txt` didn't explicitly state description to be optional. For consistency, a default value of `"Steel Axe"` would be good.
Actually, it isn't new that the default description is the item name. `itemstack:get_description()` already did this before: https://github.com/minetest/minetest/commit/008b80fe1ca9d46610b8971e2ac92fb56da8e69f
It might be better to fix this in mtg.

**Comment by sfan5** [comment]
I disagree, if a game/mod doesn't want to set a description it should be allowed to do so without the engine forcing a fallback.

> It might be better to fix this in mtg.

Another reason with this is a that this could break many mods too, which can't or won't all be fixed.

**Comment by kilbith** [comment]
Ah, this is our favorite regression-maker that did this again ...
