### ISSUE TITLE
Player API: Calculate current frame of "walkmine" animation

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest_game#2756]
Player API tends to stutter when mining while walking, as it starts the walkmine animation from it's first keyframe. This can easily be fixed.

**Comment by paramat** [comment]
Easily? Seems complex to me to sync animations through calculations and support this in the API.
I am not convinced it is worth doing, especially with MTG feature frozen.
Maybe you can convince me otherwise?

**Comment by paramat** [comment]
The frames of 'walk' and 'walk mine' for the MTG player model might be synced, allowing a calculation, but that is not necessarily the case for other player models, animations might even be differing lengths.
So all we could do is provide adjustable parameters to set how to switch from one animation to the other.
This seems very complex.

Besides ...
When animation switches from one to another there are already unavoidable 'stutters' and discontinuities: between 'stand', 'lay', 'sit', 'walk', 'mine' and all the possible custom animations used.
The 'problem' already exists in several other ways and is unavoidable.
I do not consider it a problem anyway, MTG player animations have always been jerky and discontinuous and this is just consistent with the 'non-smoothness' and simplcity of many MT games. No-one has complained before now.
So i think such excessive perfectionism is unjustified.
Also: feature freeze.
Interesting idea though.

I suggest you write a new improved 'player API' mod for use in new games, as i am doing. Then you can make it as perfectionist as you want. We need to stop focussing on MTG.

**Comment by appgurueu** [comment]
> I suggest you write a new improved 'player API' mod for use in new games, as i am doing. Then you can make it as perfectionist as you want. We need to stop focussing on MTG.

Yeah, will do.
