### ISSUE TITLE
Slovak Translation

### ISSUE THREAD

**Issue by daretmavi** [minetest/minetest_game#2757]
Hi,
what is the correct way to upload new translation?

I translated all mods to slovak language:
https://mega.nz/file/ycxU3LbR#Hjh8GWg78hMLdmZv1I5sz3vTjzfpHm5BzJlZEONKyII

**Comment by paramat** [comment]
I know nothing about contributing translations, maybe @Wuzzy2 or seomone else can advise?

**Comment by Wuzzy2** [comment]
PRs are preferred.

… and the PR was already merged, lol.
