### ISSUE TITLE
Walking sounds play even when player stands at a place sometimes.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest_game#2780]
I assume this bug was caused by #2605 . The walking sounds play from time to time with different frequency even when player is not moving.

**Comment by paramat** [comment]
New sounds cannot cause a bug like this.
Such a bug is an engine issue, i seem to remember an issue exists already, try searching.

**Comment by Andrey2470T** [comment]
It is just strange, but I had ever not come across that bug before that PR was merged. Does it not occassionally contain any engine changes?

**Comment by paramat** [comment]
@Andrey2470T 
Weird that you noticed this bug after #2605 was merged. I cannot see a reason why that would cause this.
There is an engine issue https://github.com/minetest/minetest/issues/6959 which is perhaps the same bug. Perhaps you could report your experience in that issue with more detail.
