### ISSUE TITLE
Fun with "Sphere Mapping"

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest_game#2783]
I was playing around with how to reveal the edges of the world.

Have a look:

This is with a strong effect to just see it:
https://www.youtube.com/watch?v=XTndl4PxL6I

This is a softer effect:
https://www.youtube.com/watch?v=RbhvpQ5hDso

It can be varied easier.

I wish I could say I did some super complex sphere mapping. The actually logic is shader only, very simple, and essentially free in terms of performance.

Mostly for fun.

**Comment by lhofhansl** [comment]
Oops... Meant to MT, not game.

**Comment by sfan5** [comment]
FYI you can transfer issues between repos, there's a button on the bottom right.
