### ISSUE TITLE
LUA API: minetest.register_tree()

### ISSUE THREAD

**Issue by ChefZander** [minetest/minetest_game#2810]
Adds the ability to create custom trees more easily.
#### Usage
minetest.register_tree(tree_definiton)

the tree definiton contains:
- biomes: table to specify the biome names the tree can generate in
- stem_node: node reference to what will be the stem of the tree
- stem_height_min: minimum stem height
- stem_height_max: maximum stem height
- leaves_node: node reference to what will be the leaves of the tree

**Comment by ExeVirus** [comment]
This is a feature, and because MTG is officially in maintenance mode, this will likely get closed.

 I would recommend making your own mod that implements this function. You should not need any changes to MTG or the Engine to pull this off.

**Comment by appgurueu** [comment]
> This is a feature, and because MTG is officially in maintenance mode, this will likely get closed.
> 
> I would recommend making your own mod that implements this function. You should not need any changes to MTG or the Engine to pull this off.

1. Everything that writes to the `minetest` table like that sounds like it should be an engine feature
2. This can be done well as a standalone library mod (as pointed out already)
3. MTG is in maintenance mode (as pointed out already)

So yes, this should be closed.
