### ISSUE TITLE
Glass doors Z-fighting

### ISSUE THREAD

**Issue by MysticTempest** [minetest/minetest_game#2812]
Glass doors are very glitchy/flickering; in the most recent commit that changed the doors. It looks like they're too big now, and slightly extending outside their nodebox into other nodes.

**Broken:** 
https://github.com/minetest/minetest_game/commit/3fdd5cdb5fb772d84618e57b346f6ccbf9380d57

Tested in v5.3 & v5.4-dev(a01a02f); easily reproducible; by downloading the previous commit to minetest_game, and seeing that glass doors work without issue.

**Previous commit with no glitching glass doors:**
https://github.com/minetest/minetest_game/tree/e1e793d4da76cc2fd714f3a3d4cabb12858609fe

**Preview:**
Top half is the glitchy new door model.
Bottom half is from the previous working commit.

![GlassDoorsBrokenwithNewModels](https://user-images.githubusercontent.com/32621758/106402847-415fd600-63f1-11eb-92a7-b08a04f4d0ac.png)

**Comment by sfan5** [comment]
@An0n3m0us

**Comment by An0n3m0us** [comment]
Hmm, I see.

> It looks like they're too big now, and slightly extending outside their nodebox into other nodes.

No, they are the correct size; that is why the faces are exactly overlapping and causing this issue.

There is only one fix for this, really. And that is creating spacing between the edges.

Still, the PR I submitted was valid as all sides were smaller (only the 4 side faces need to be a touch smaller)

**Comment by An0n3m0us** [comment]
Meh, scrap the PR; these dimensions were all intentional; the front and back were so that it does not glitch if the glass door is against a block (like when it is opened).
But maybe a note should be written somewhere for clarity.

**Comment by An0n3m0us** [comment]
TOP --> OLD
BOTTOM --> NEW
![test](https://user-images.githubusercontent.com/49789044/106452492-df01e680-647f-11eb-853e-6ab832b4b6c5.png)
![test2](https://user-images.githubusercontent.com/49789044/106452493-e0331380-647f-11eb-81a2-8221eb901535.png)

Well, I've decreased the size offset, and that has fixed the glitching and the line between the doors.
But it's up to you @sfan5 if you want to bother with this again. I've got the commit ready for a PR (just need to test it a bit more to make fully sure).

**Comment by An0n3m0us** [comment]
On the topic of Z-fighting; is it possible to implement something in the engine which lets an objects mesh take precedence when it comes to overlapping faces?

I don't have much experience in game dev, but there probably is a method, no?

That will solve this problem and so many other problems to do with transparent objects.

**Comment by MysticTempest** [comment]
> Well, I've decreased the size offset, and that has fixed the glitching and the line between the doors.
> But it's up to you @sfan5 if you want to bother with this again. I've got the commit ready for a PR (just need to test it a bit more to make fully sure).
> 
> I personally don't mind my PR being reverted; the doors do look better without the glitchy line in-between being so visible, but it's not worth all the trouble.
> 
> EDIT: If anyone wants to test; https://github.com/An0n3m0us/minetest_game/tree/doormodelfix2
>

@An0n3m0us
I tried your branch:
https://github.com/An0n3m0us/minetest_game/tree/doormodelfix2

There's still some minor Z-Fighting at the bottom of the doors. But, I don't see any on the sides. So, overall it looks much better than the current commit(3fdd5cd).
However, the original doors had no Z-Fighting at all; from what I could tell.

**Preview:**
Top image is the test of doormodelfix2; with minor z-fighting.
Bottom image is from the last working commit: e1e793d

![doormodel2Test](https://user-images.githubusercontent.com/32621758/106507134-3d36c580-6490-11eb-96fa-08999d35a1ed.png)

**Comment by An0n3m0us** [comment]
Thanks for testing!

I tested again, and I only notice this when traveling quite far away and using the zoom key. Then I see the glitching at the bottom and on the sides.
