### ISSUE TITLE
No lava environment sound

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#2817]
e193f9fda3aff548bf0b6cd7890462eff82345dc claims that "lava environment sounds" were added but I hear nothing, both at lava source and flowing lava. Intentional? Flowing water works and makes sounds.

@sfan5.

How to reproduce:
1. Place lava and make it flow
2. Listen

**Comment by sfan5** [comment]
Tested, still works. You need more than a couple of lava nodes so it can be heard.
