### ISSUE TITLE
Noticable clicking noise at lava environment

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#2818]
If the `env_sounds_lava` sound plays, you will hear a clicking that drives me nuts. It is slightly noticable without headphones, but with headphones, it is clearly noticable.

And it's a bug in the sound file: In Audacity I see the sound wave doesn't end at 0 dB, so it's not surprising that there is a click. This affects both lava sounds.

Version: 5.4.0-dev

**Comment by sfan5** [comment]
I can see what you mean looking at the waveform but I disagree that it's "clearly noticable" or I would have noticed this when adding the sounds half a year ago.
(or maybe something about my sound setup makes the artifacts disappear)

**Comment by An0n3m0us** [comment]
Yeah, I had to amplify my headphone audio to 125% to hear the clicks.
All the same, they are there, but very slight.

**Comment by Wuzzy2** [comment]
They are definitely audible *to me*, even without headphones. I didn't need to "cheat" and look at the waveform to notice this. It's a bit subtle w/o headphones (hearable when everything else is silent), but it's clear as day w/ headphones. Maybe I just have awesome ears. :D

In any case, the fix would be to do a very short fade-in at the beginning and fade-out at the end for both sounds. Do you still have the lossless versions of these files? Because "editing Ogg" isn't great (lossy).

**Comment by An0n3m0us** [comment]
> In any case, the fix would be to do a very short fade-in at the beginning and fade-out at the end for both sounds.

Well, the sounds are both around 7s long, but the loops are played from 0-3.5s
So in my PR I had to fade out at 3.5 but still keep it smooth from 3.5-7s, and it worked fine.
