### ISSUE TITLE
Warning spam about use_texture_alpha

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#2819]
The console is completely spammed with warnings like:

```
Texture "doors_door_glass.png" of doors:door_glass_d has transparency, assuming use_texture_alpha = "clip".
```

Can you please fix this? Is there a recommended way to fix this warning? Or would it be better to downgrade the log level of this to `action` or `info`?

Tested in 6a9cbcad827c9e04eee53321844b170dfa63e388, under Minetest 5.4.0-dev.

**Comment by sfan5** [comment]
#2729 was supposed to do this but the alpha changes were not fully ready by that time.

> Or would it be better to downgrade the log level of this to action or info?

Absolutely not, the warning warns of something that **will** stop working if the nodedef is not adjusted. (the explanatory text even says so)

**Comment by Wuzzy2** [comment]
Oh, this change has completely stumped me. To be fair, I did not know about this, it was not in the changelog *at all*. I will add this to the changelog, this is a very important change.

Oh, I just saw another warning:

```
Field "alpha": Obsolete, only limited compatibility provided; replaced by "use_texture_alpha"
```
