### ISSUE TITLE
[Bug] Not able to break stone using sticks

### ISSUE THREAD

**Issue by Thewisem** [minetest/minetest_game#2841]
##### Minetest version

```
5.4.0
```

##### OS / Hardware

Operating system: 7 Nougat
CPU: Samsung Exynos

GPU model:
OpenGL version:

##### Summary

I couldn't break blocks using stick. Noither could I break using blocks.

##### Steps to reproduce

1) Create a map
2) dig down using stick
3)reach stone level and try digging using stick and wood blocks

**Comment by An0n3m0us** [comment]
I'm neutral on the idea, but what will the effect be on the item?
Will it be destroyed or partially damaged after mining a block?

If the former, then this is simple.

The latter; this is more complicated as crafting will have to be affected in some way (or not?)
Or maybe the crafted item (e.g wooden pickaxe) will inherit the damage on the stick.

But then in the case of blocks against other blocks (or sticks used in crafting things other than tools), what would the outcome be?

**Comment by Thewisem** [comment]
None of your answers

**Comment by Thewisem** [comment]
My take on this is that each thing should have different time to break each other blocks. Like pickaxe would take 10 seconds to break and dirt would take 17 second to break stone. The duration of time should be different for each case scenario

**Comment by Thewisem** [comment]
Every block should be able to break every other block. The only change is duration of breaking the block.

**Comment by Thewisem** [comment]
:)

**Comment by Montandalar** [comment]
Minetest game has always been like this as far as I'm aware. It doesn't need to copy Minecraft. The behaviour you want is how it works in MineClone 2.

**Comment by SmallJoker** [comment]
Craft a wooden pickaxe and dig the stone like that. It's how MTG works. Not a bug.
