### ISSUE TITLE
No dirt layer when creating a new world

### ISSUE THREAD

**Issue by 3raven** [minetest/minetest_game#2847]
Hi,
I recently noticed that when I create a new world with the minetest game, there is no dirt layer on the stone, I tried all mapgen (v5,v6,v7, flat, valleys..). I dont have this problem with other subgames (I tried to create a test world with lott and it worked) so I think it comes from MTG.

I got no error message.

**Comment by 3raven** [comment]
It was the 5.4.0 latest release of mtg

**Comment by sfan5** [comment]
Make sure there are no mapgen settings left in `minetest.conf`.

**Comment by 3raven** [comment]
You were right, the problem was the conf file. Thanks for your help !
