### ISSUE TITLE
Reclassify some items as tools

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#2848]
The following items are classified as items (instead of tools) in the Creative Inventory:

* Binoculars
* Mapping Kit

I suggest to reclassify them as tool *in the Creative Inventory*. Note this is only about the Creative Inventory tab (from the player's point of view), I do not care about the internal/technical classification of items.

It might also be consider to classify Boat, Cart and Skeleton Key as tools, although the category of these items is more debatable.

**Comment by An0n3m0us** [comment]
Boats and carts are not items for sure, but whether the skeleton key is a craftitem or a tool is debatable.
