### ISSUE TITLE
Embed YouTube videos on cubes

### ISSUE THREAD

**Issue by vanillajonathan** [minetest/minetest_game#2853]
Add support for embedding YouTube videos on cubes.

This would let players create museums, art galleries, as well as arrange conferences, conventions, concerts, event arenas, release parties, cinemas, etc.

This example features [Rick Astley - Never Gonna Give You Up](https://www.youtube.com/watch?v=dQw4w9WgXcQ) on YouTube.

![image](https://user-images.githubusercontent.com/10222521/111906394-ada1a200-8a50-11eb-82d4-a321d423b987.png)

**Comment by sfan5** [comment]
Wrong place, seeing as you've already opened one in the right place I'll close this one.
