### ISSUE TITLE
mtg_craftguide - feature request: progressive mode

### ISSUE THREAD

**Issue by ghost** [minetest/minetest_game#2857]
Like Minecraft has would be nice.

**Comment by sfan5** [comment]
And what exactly is a "progressive mode"?

**Comment by voxel-minetest** [comment]
=) sorry I thought everyone knows cause there are some crafting mods in minetest that already try to implement it (but as far as i tested them none of them works... craftguide, i3 etc.) 

The progressive mode (you can give it a different name of course) makes that the craftguide shows you only recipes that you can craft from the items you have. 
In Minecraft it is default in survival mode, you can switch between show my only recipes that I can make from the stuff I carry at the moment and show me recipes that I can make from all the stuff I got at the moment (this includes storages like chests).

**Comment by NathanSalapat** [comment]
i3 and craftguide both have it, I think both default to off. You have to change the settings to enable it.

**Comment by voxel-minetest** [comment]
@NathanSalapat 
Of corse I've done that but it doesn't work. 
I always test new mods vanilla in minetest_game.

**Comment by SmallJoker** [comment]
This sounds like a good idea for a game like MineClone2, if that's not already implemented yet.

**Comment by Emojigit** [comment]
#2710
