### ISSUE TITLE
 mtg_craftguide - feature request: opt-out cursor focus on the search bar

### ISSUE THREAD

**Issue by ghost** [minetest/minetest_game#2858]
The default keybinding for the inventory is "i", I have it on "e". 
The problem is, that I can not close the inventory with "e" when I am in the "Recipes" tab or any of the crative tabs. 
Instead it fills in an "e" in the search bar, so I have to use Esc.
It would be nice to have an option (not the default behavior) where the player have to click on the search bar everytime she or he want to do a search, no matter in wich tab.

**Comment by Emojigit** [comment]
#2710

**Comment by Emojigit** [comment]
No morefeature requests (feature freeze) afaik


rubenwardy ***@***.***> 於 2021年9月5日週日 上午4:35 寫道：
