### ISSUE TITLE
Sleeping on boats

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest_game#2860]
You can sleep on boats by rightclicking a bed while on a boat:

![Screenshot](https://user-images.githubusercontent.com/34514239/113477795-c4022180-9484-11eb-83b2-ece6811530ee.png)

When you leave the boat, your physics aren't reset and you can't move.

Possible solution: Check whether the player is attached. Don't allow them to enter a bed, or detach them.

**Comment by voxel-minetest** [comment]
lol nice found! 
=D
