### ISSUE TITLE
Allow to set use_texture_alpha when registering a door

### ISSUE THREAD

**Issue by grorp** [minetest/minetest_game#2866]
When you register a door, `use_texture_alpha` is always set to `clip`, even if you specify a different value in the door definition. That makes it impossible to register e.g. tinted glass doors.

### Solution
Change [this line](https://github.com/minetest/minetest_game/blob/c6171a8f29a0d6bea2566a74a8bc89121149df93/mods/doors/init.lua#L439) from
```lua
def.use_texture_alpha = "clip"
```
to
```lua
def.use_texture_alpha = def.use_texture_alpha or "clip"
```

**Comment by sfan5** [comment]
Sounds good. It'd be helpful if you provided a PR with this change (don't forget the documentation in `game_api.txt`).
