### ISSUE TITLE
[Carts] server crash on punch cart

### ISSUE THREAD

**Issue by debagos** [minetest/minetest_game#2867]
Rarely but sometimes when a player punches a cart, my server crashes with this message:
`ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Invalid float vector dimension range 'x' (expected -2.14748e+06 < x < 2.14748e+06 got -nan).`
The log message right before the crash is always like:
`ACTION[Server]: player redacted (id=720, hp=20) punched LuaEntitySAO "carts:cart" at (-2761,-3,4324) (id=6420, hp=10), damage=0`

MT: 5.5.0-dev
MTG: 5.5.0-dev

**Comment by SmallJoker** [comment]
The only occurrence I could think of is in the following snippet:
https://github.com/minetest/minetest_game/blob/c6171a8f29a0d6bea2566a74a8bc89121149df93/mods/carts/cart_entity.lua#L136-L141

Does it help if you change it like so?
```Lua
end
punch_interval = math.max(punch_interval, 1) -- new line
time_from_last_punch = math.min(time_from_last_punch or punch_interval, punch_interval)
```
This would indicate a faulty tool registration which uses a punch interval of `0`, resulting in a division by zero.

**Comment by debagos** [comment]
I tried to reproduce the bug but could not achieve it. I also ran a search for `full_punch_interval` on my mod directory, but couldn't find any tool with a `full_punch_interval = 0`.
I applied your suggestion now and will report back. Either when I see a crash again, or in one week to tell you that it seemed to fix it.

Thank you for your help @SmallJoker :smiley:

**Comment by debagos** [comment]
I report back:
It helped. I newer saw this crash happen again.

And your guess was right @SmallJoker, it was a faulty tool registration...
The **alien_material** mod has a typo and registers a sword like this:
`full_punch_interval = 0,3`
Source: [alien_material/tools.lua#L71](https://gitlab.com/debiankaios/alien_material/-/blob/master/tools.lua#L71)

Thank you very much for you quick help, have a nice day.
