### ISSUE TITLE
The player inventory allows to take items in survival mode.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest_game#2869]
When you disable creative mode, you can freely take any items from your inventory as if you are in creative mode. This bug appears in the newest minetest_game (since 4945f4b commit).

**Comment by sfan5** [comment]
Please provide a step-by-step way to reproduce this on a new world including settings set in the main menu.

**Comment by Andrey2470T** [comment]
I have tested now from the official Minetest 'master' branch with the latest commit 7c2826c
 (before I discovered it on 0xLiso`s 'PSM' branch of the forked repo) and there was no the creative inventory in the survival mode. It means the bug is in his branch.
