### ISSUE TITLE
Can't Pick Up Carts on Mobile Client

### ISSUE THREAD

**Issue by AntumDeluge** [minetest/minetest_game#2870]
The instructions say to hold "sneak" (Shift) & punch to pick up a cart. However, this does not work from the Android mobile app. At least not without attaching a physical keyboard (unconfirmed). Touching & holding the down arrow, which I assume is supposed to be the equivilant of pressing the Shift key on a physical keyboad, & punching does nothing.

**Comment by sfan5** [comment]
Engine issue: https://github.com/minetest/minetest/issues/8022
