### ISSUE TITLE
Carts: Please add  stop rails

### ISSUE THREAD

**Issue by mk-pmb** [minetest/minetest_game#2874]
Hi! Could we please add rails that actually stop a speedy cart in their center point? As opposed to break rails that just slow it down. On a server I like to play, we have lag issues, so it would be nice to have cart stops (like bus stops) where the default is to stop and wait until the player chooses their next direction of travel.

**Comment by SmallJoker** [comment]
FWIW: The mod that `carts` is based on, `boost_cart` does have start/stop rails and implementing [this feature](https://github.com/SmallJoker/boost_cart/blob/b05a49afb5721d09ceac3c5f4acfb793fe946914/cart_entity.lua#L275-L283) in `carts` would be pretty trivial (although without mesecons controls).

**Comment by mk-pmb** [comment]
Thanks for that hint!
