### ISSUE TITLE
Carts: Please add carts that stop at each intersection

### ISSUE THREAD

**Issue by mk-pmb** [minetest/minetest_game#2875]
This feature is similar to #2874 , but puts the decision in players' choice: Please add a recipe to upgrade a regular cart with an automatic brake that brakes at each intersection/switch so it stops in the center of that block.

Also please add a cheap recipe to dismantle it into a normal cart and the brake.

**Comment by sfan5** [comment]
Minetest Game is frozen for features, this should be doable in a mod.
