### ISSUE TITLE
Flowers code cleanup/simplification desert_sand check

### ISSUE THREAD

**Issue by sirrobzeroone** [minetest/minetest_game#2878]
Flowers currently checks for desert_sand with a note saying it's needed due to desert_sand being in soil group:
https://github.com/minetest/minetest_game/blob/master/mods/flowers/init.lua#L164

I checked and desert_sand is no longer in the soil group, but in the sand group - guessing a past change:
https://github.com/minetest/minetest_game/blob/master/mods/default/nodes.lua#L581

It's not much but line 165 could be removed from flowers as the check is no longer needed as desert_sand can never be returned as soil group at line 152 in flowers:
https://github.com/minetest/minetest_game/blob/master/mods/flowers/init.lua#L152

updated code
```
	local soils = minetest.find_nodes_in_area_under_air(
		pos0, pos1, "group:soil")
	local num_soils = #soils
	if num_soils >= 1 then
		for si = 1, math.min(3, num_soils) do
			local soil = soils[math.random(num_soils)]
			local soil_name = minetest.get_node(soil).name
			local soil_above = {x = soil.x, y = soil.y + 1, z = soil.z}
			light = minetest.get_node_light(soil_above)
			if light and light >= 13 and
					-- Only spread to same surface node
					soil_name == under.name then
				minetest.set_node(soil_above, {name = node.name})
			end
		end
	end
```

I'm happy to do a pull request but wasn't sure if it was worth it for a 1 line cleanup?

**Comment by sfan5** [comment]
> I'm happy to do a pull request but wasn't sure if it was worth it for a 1 line cleanup?

Definitely. We can merge PRs with one or two clicks from the web interface, not so much with a snippet of code pasted manually.
