### ISSUE TITLE
Very soft dependency between Binoculars and Player_api mods

### ISSUE THREAD

**Issue by sirrobzeroone** [minetest/minetest_game#2879]
More noting this one than anything, I dont understand enough to identify how adding/removing player_api mod has the effect it does on binoculars as I thought the "player" object was still created without player_api but theres clearly something going on.

**To Test**
1. Remove mod player_api
2. Load a new game in creative
3. grant yourself all privileges
4. Press Z 
5. You will be unable to zoom and you will recieve the error:
  "Zoom currently disabled by game or mod"

6. Restore player_api mod
7. log back in
8. Press Z
9. Zoom as normal

I thought the issue may have been line33 of the binoculars mod but I tried commenting that out and redoing the above test but it didnt fix anything.

More noting this than anything as at the moment there is no indication in the binoculars mod that there is any dependancy to player_api mod but there does appear to be a very very soft dependancy on something from player_api.

Standard Binocular functionality is unaffected its only when player is in full creative and trying to zoom without binoculars in their inventory. 

Just aware someone may attempt to rip out and use the binocular mod without player_api or whatever functionality player_api adds that binoculars needs.

**Comment by sfan5** [comment]
I debugged this and this is an engine bug, the engine says the zoom fov already is 15 and so `binoculars` won't try to set it again.
