### ISSUE TITLE
Destroying blocks miss

### ISSUE THREAD

**Issue by Ygarr** [minetest/minetest_game#2887]
##### Minetest version
last

Behaviour: When you make 1 move to detroy block - its not enough to destroy 1 block.
                But when you make 2 moves by hand you destroy 3 blocks.

So you need to select duration of click mouse button to destroy only what you need, which depends on fps of your game e.g. And it`s hard...

Think it would be enough copy from minecraft`s creative mode behaviour in this case. 1 click or 1 hand move to destroy respectively 1 block

**Comment by SmallJoker** [comment]
Minetest only handles `dig_immediate` groups in a special way. https://github.com/minetest/minetest/blob/edf098db637bf74d4675ce900dc9c0b8ee528a03/src/tool.cpp#L189-L199

This is a Minetest Game issue. Relevant code:
https://github.com/minetest/minetest_game/blob/c96cc55c406b00abaaf1f847eab8dbe4abc03286/mods/default/tools.lua#L6-L20

Please tweak those values and propose a PR so it can be discussed.

**Comment by appgurueu** [comment]
I believe `safe_dig_and_place` basically fixes the issue though (and this is thus not a MTG issue)? Krock seems to be suggesting that the values could be tweaked to "slow down" digging of some nodes?
