### ISSUE TITLE
explosions spawn fire on air

### ISSUE THREAD

**Issue by 10maurycy10** [minetest/minetest_game#2891]
##### Minetest version
```
5.4.1 (flatpack)
```

##### OS / Hardware

Operating system: Debian Buster

##### Summary
An explosion can spawn fire on air nodes.

##### Steps to reproduce
0. find a location with grass or flowers.
1. Create a TNT node.
2. Ignite it,
3. Stand back.

**Comment by sfan5** [comment]
Can't reproduce here.
Any special conditions for this to happen? If you have one please post a screenshot.

**Comment by Dieter44** [comment]
Minetest version: 5.4.1
OS/Hardware:  macOS 11.5.2 on iMac

I can reproduce the issue. If the issue exists on Debian Buster and macOS, is it possible that the problem is UNIX-related? On what OS are you on sfan5?

![Bildschirmfoto 2021-09-23 um 21 57 48](https://user-images.githubusercontent.com/55900078/134575332-9f2ac125-7327-4228-b9fb-6be2a28d11b2.png)

**Comment by Dieter44** [comment]
Just after posting the other comment I found out that the floating fire is related to grass/flowers destroyed by the TNT. It looks like every flower/grass block gets turned into fire when it is destroyed by TNT.

For example before TNT:
![Bildschirmfoto 2021-09-23 um 22 09 02](https://user-images.githubusercontent.com/55900078/134576971-d08b4b63-03b6-4731-9d29-614d75fac88b.png)
And after:
![Bildschirmfoto 2021-09-23 um 22 09 16](https://user-images.githubusercontent.com/55900078/134576918-d33fea1a-ae42-4806-9525-412cdc965c11.png)

VS

Before TNT:
![Bildschirmfoto 2021-09-23 um 22 09 34](https://user-images.githubusercontent.com/55900078/134577029-8e7f9350-0c42-490b-ad94-81337979e859.png)
and after:
![Bildschirmfoto 2021-09-23 um 22 09 47](https://user-images.githubusercontent.com/55900078/134577065-92819f94-9e12-4d6f-955a-c0b04a18b9c8.png)

**Comment by sfan5** [comment]
> On what OS are you on sfan5?

I generally test with Minetest 5.5.0-dev on Linux.
The grass thing looks like the reason though, thanks for reporting.

**Comment by 10maurycy10** [comment]
updated reproduction guide.

**Comment by Desour** [comment]
Afaik this is expected behaviour.

It might look nicer though if there would only be fire where flamable nodes that did not explode are nearby.

**Comment by 10maurycy10** [comment]
yes

> Afaik this is expected behaviour.
> 
> It might look nicer though if there would only be fire where flamable nodes that did not explode are nearby.
