### ISSUE TITLE
Add Computer Block that can be programmed with Lua

### ISSUE THREAD

**Issue by Destroyinator69420** [minetest/minetest_game#2893]
The computer block as I imagine it can connect to components with Wires, or a Receiver, which should be much more difficult to craft, since it would be wireless.

Possible components could include:
Piston
Double Piston
Piston Clamps (used to attach the end of a piston to blocks, including other piston clamps)
Pipe (used to transport items from one place to another) (interfaces with dispenser)
Dispenser
Motion Sensor (does not detect motion when sneaking)
Repeater
Observer
Rails
Powered Rails
Minecarts
Levers
Buttons

When components are connected to a computer via a wire, they become available to the computer to control. The maximum range of the wire is should be 35 wire blocks, if more wires are needed, then a repeater will be needed.

Why?
The lack of an official tech system in Minetest makes it difficult to commit to learn how to use them. Great contraptions in Minecraft are only possible becuase there is a standard way to build them. There is no standard ruleset to build contraptions in Minetest, so it is difficult for the community to share creations with one other, and the existence of a standard ruleset to build contraptions will make building them much more worthwhile, as other people can build them too. Minetest will be much more successful when the official game has more blocks to play around with, which means more possibilities, and contraptions are a great start.

**Comment by NathanSalapat** [comment]
Check out the mesecons and digilines mods.

**Comment by sfan5** [comment]
As mentioned a very good mod to do this already exists. In addition note that Minetest Game is not taking feature requests anymore (and definitely not ones this size) as it's in a maintenance mode.
