### ISSUE TITLE
[Bug] Mac client - Menu rendered wrong

### ISSUE THREAD

**Issue by darkspirit510** [minetest/minetest_game#2907]
Hi all,
when running minetest it looks like attached image. The menu is rendered on the bottom left, but the actual menu seems to be in the middle (can't click where it is rendered).
Is this a known issue
<img width="1792" alt="Screenshot 2021-11-08 at 21 11 09" src="https://user-images.githubusercontent.com/17259447/140813153-aa0fd5e5-19cb-4c58-b344-cc365b4247d6.png">
?

**Comment by sfan5** [comment]
This is a known bug which was tracked in https://github.com/minetest/minetest/issues/10654, it will be fixed in 5.5.0.
