### ISSUE TITLE
Crash due to faulty minetest.find_nodes_in_area is easily triggerable

### ISSUE THREAD

**Issue by corarona** [minetest/minetest_game#2908]
The fire mod calls minetest.find_nodes_in_area with the player position every 3 seconds for every player. Since player position is pretty much under client control this leads to a situation where clients can crash the server easily (by teleporting down to the coord value in question).

In the long run this obviously needs to be fixed in the engine but short term this leads to a situation where every player can crash the server pretty much at will.

I would consider handling those coordinates in lua so find_nodes does not get called with said coord values (I won't publish them here, they're not hard to guess but I'll gladly tell any dev who wants to work on this in dm).

For testing this i recommend using a utility client like dragonfire since /teleport does not allow to teleport out of map bounds - it is possible to noclip-fly there of course.

Minetest issue:
https://github.com/minetest/minetest/issues/11769

Fix in mineclonia (would probably work just like that in mtg):
https://git.minetest.land/Mineclonia/Mineclonia/pulls/169

Minetest: 5.4
mtg: 5875820542c739ff223a8a6ef8a3e698685b6405

**Comment by corarona** [comment]
I would like to repeat: 

> In the long run this obviously needs to be fixed in the engine but short term this leads to a situation where every player can crash the server pretty much at will.
> 
> I would consider handling those coordinates in lua so find_nodes does not get called with said coord values[...]

This makes it trivial for clients to crash any server that is based on mtg (or to be exact which include the fire mod of mtg). This probably applies to the vast majority of minetest servers out there.

I strongly recommend to handle this in lua (or not call minetest.find_nodes_in_area() with player controlled values) and not wait for it to be fixed in the engine as the tagging would suggest. I know of at least one not entirely good willing person who has been known to do this on servers.

**Comment by sfan5** [comment]
I know that this is fixable in Lua.
The reason I tagged it was "engine change needed" is that Minetest and Minetest Game release on the same schedule. Whether it's fixed in MTG now or in the engine a week later makes no difference to the end user.
