### ISSUE TITLE
attempt to call method 'get_name' (a nil value)

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest_game#2927]
#### Minetest Version
```
# minetestserver --version
Minetest 5.5.0 (Linux)
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
STATIC_SHAREDIR="/usr/local/share/minetest"
STATIC_LOCALEDIR="/usr/local/share/locale"
```
#### Error message
```
ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod '' in callback item_OnCraft(): ....minetest/games/minetest_game/mods/default/functions.lua:696: attempt to call method 'get_name' (a nil value)
ERROR[Main]: stack traceback:
ERROR[Main]: 	....minetest/games/minetest_game/mods/default/functions.lua:696: in function 'func'
ERROR[Main]: 	...ocal/share/minetest/builtin/profiler/instrumentation.lua:107: in function 'func'
ERROR[Main]: 	/usr/local/share/minetest/builtin/game/register.lua:306: in function </usr/local/share/minetest/builtin/game/register.lua:304>
```

**Comment by appgurueu** [comment]
Relevant MTG code: https://github.com/minetest/minetest_game/blob/0c1252bcf540d6d6582f3cae8fbabbc5845fdf04/mods/default/functions.lua#L696

It looks like `itemstack` isn't actually an `ItemStack` but perhaps instead a string or table (must be indexable)

**Comment by SmallJoker** [comment]
C++ side generates a proper ItemStack reference.
https://github.com/minetest/minetest/blob/1c73902005bb5c7a40be5571bff9c232d8c69536/src/script/cpp_api/s_item.cpp#L164
.. which is then forwarded to the callbacks:
https://github.com/minetest/minetest/blob/1c73902005bb5c7a40be5571bff9c232d8c69536/builtin/game/register.lua#L304-L309

Blame a mod of yours which returns either a table or string rather than a proper ItemStack like documented here:

https://github.com/minetest/minetest/blob/1c73902005bb5c7a40be5571bff9c232d8c69536/doc/lua_api.txt#L4984-L4985

**Comment by Emojigit** [comment]
Hmmm... maybe no way to reproduce in MTG. But we should still add checking codes. Here is a patch, done on `stable-5` but should work on `master`:
```patch
diff --git a/mods/default/functions.lua b/mods/default/functions.lua

index d1dbf63..4d89a38 100644

--- a/mods/default/functions.lua

+++ b/mods/default/functions.lua

@@ -693,7 +693,7 @@ function default.register_craft_metadata_copy(ingredient, result)

        })

 

        minetest.register_on_craft(function(itemstack, player, old_craft_grid, craft_inv)

-               if (itemstack.get_name and itemstack:get_name()) ~= result then

+               if itemstack:get_name() ~= result then

                        return

                end
```

**Comment by Emojigit** [comment]
To moderators: please add tag "Invalid" and remove "Unconfirmed Bug" from this issue, thanks.

**Comment by appgurueu** [comment]
> Hmmm... maybe no way to reproduce in MTG. But we should still add checking codes. Here is a patch, done on `stable-5` but should work on `master`:
> 
> ```diff
> diff --git a/mods/default/functions.lua b/mods/default/functions.lua
> 
> index 4d89a38..d1dbf63 100644
> 
> --- a/mods/default/functions.lua
> 
> +++ b/mods/default/functions.lua
> 
> @@ -693,7 +693,7 @@ function default.register_craft_metadata_copy(ingredient, result)
> 
>         })
> 
>  
> 
>         minetest.register_on_craft(function(itemstack, player, old_craft_grid, craft_inv)
> 
> -               if itemstack:get_name() ~= result then
> 
> +               if (itemstack.get_name and itemstack:get_name()) ~= result then
> 
>                         return
> 
>                 end
> ```
> 
> EDIT: nonono, invalid issue.

Such patches are what ruins the code quality. Throwing an error is the right thing to do here. You should fix this at it's root cause - i.e. a mod passing invalid arguments - instead of covering up the "symptoms" (not throwing the error and no-oping instead).

**Comment by Emojigit** [comment]
> Such patches are what ruins the code quality. Throwing an error is the right thing to do here. You should fix this at it's root cause - i.e. a mod passing invalid arguments - instead of covering up the "symptoms" (not throwing the error and no-oping instead).

even VERBOSE cannot give which mod caused it!

**Comment by appgurueu** [comment]
> > Such patches are what ruins the code quality. Throwing an error is the right thing to do here. You should fix this at it's root cause - i.e. a mod passing invalid arguments - instead of covering up the "symptoms" (not throwing the error and no-oping instead).
> 
> even VERBOSE cannot give which mod caused it!

Why don't you `grep` for `register_on_craft` and then have a look? That should be the fastest way to debug this.

Alternatively, if you want to debug this programmatically, you can just throw an error if the `itemstack` doesn't have `get_name` by overriding `minetest.on_craft`:

```lua
function minetest.on_craft(itemstack, player, old_craft_list, craft_inv)
	for _, func in ipairs(core.registered_on_crafts) do
		itemstack = func(itemstack, player, old_craft_list, craft_inv) or itemstack
		if not itemstack.get_name then error(dump(debug.getinfo(func, "nSu")) end
	end
	return itemstack
end
```
