### ISSUE TITLE
[feature] adding more default nodes

### ISSUE THREAD

**Issue by hacknorris-aka-penguin** [minetest/minetest_game#2934]
so yes. my node ideas:
- air node in inventory (as a joke, would do nothing)
- slime node (slows player when goes on, doubles jump while jumping or falling on)
- light node - walkable (air-like) which produces only white light
- darkness node - walkable (air-like) makes darkness aroud (gradient). even at day
- time changing nodes (day and night; 12:00 and 00:00)
- vertical rails (or a lift for carts)
- fake player node (figure)
- mirror node - shows player both with enviromnent
- boost node - speeds up layer 5 times for 3 secs
- slow node - slows down player 2 times when walking on it
- ceiling ladder node - for 'walking' on a ceiling. like riding on line
- dust/smoke node - walkable (air-liike) node for shorting visiblity to max 10 nodes when player looks through
- full nodes of: gold, coal, copper, diamond, tin. (not only materials, yes i know bout mods. but here we talk about core minetest, not mods like peeps on minetest repo)
- weeb armor (pinky, sea and purple colors. working like steel ones): swords, showels, pickaxes, axes, and wear.
- chair node - to sit in. (might be even two - for one and 2 players) or a sofa
- 'behindoculars' - reversed to binoculars. makes you able to see whats behind you
- inventory node - similar to chest but opens inventory of player instead
- death node - similar to fire but is black. if you touch it - your immediately dead
- also - a node which is broken (normal node without textures)
- fishes (as a decoration)

also other feature request:
- would it be good to make middle click as inventory by default (i know i can customize. im saying bout default things)
- while riding in carts turn player seeing to current track (while going left or right - look at left or right automatically).

**Comment by rollerozxa** [comment]
MTG is currently in feature freeze and is not accepting large new features. Feel free to implement it as mods though.

**Comment by hacknorris-aka-penguin** [comment]
i know ye. just a future update request ;) nothing more ;)
btw - dya know that update freeze might cause more viruses for platform? hope

**Comment by appgurueu** [comment]
What @rollerozxa pointed out is correct.

> btw - dya know that update freeze might cause more viruses for platform? hope

This is *not* an update freeze. It's a feature freeze.

> air node in inventory (as a joke, would do nothing)

Should already be possible through builitin's `/giveme`; the air nodes are invisible though and don't show a count, IIRC. They "do nothing".

> slime node (slows player when goes on, doubles jump while jumping or falling on)

See https://github.com/minetest/minetest/issues/7785. The bouncy part is possible though.

> light node - walkable (air-like) which produces only white light

Sounds useful for experienced builders & admins but messy and hard to distinguish from air, lighting bugs etc.
 
> darkness node - walkable (air-like) makes darkness aroud (gradient). even at day

Engine change needed. Open an issue if you want this.

> time changing nodes (day and night; 12:00 and 00:00)

But *how* should they change the time? There already is a chatcommand.

> vertical rails (or a lift for carts)

Wouldn't work too well and would pretty much defy the laws of physics. The 45° rotation is already fairly problematic; such a rotation would constantly have the player's head in stone, assuming a 1x1 hole. Why can't you build a 45° staircase for your carts?

> fake player node (figure)

Better suited for a [troll](https://content.minetest.net/packages/niwla23/troll/) mod.

> mirror node - shows player both with enviromnent

Again, engine change needed.

> boost node - speeds up layer 5 times for 3 secs
> slow node - slows down player 2 times when walking on it

Both need the same engine change as your "slime" block for a movement speed modifier.

> ceiling ladder node - for 'walking' on a ceiling. like riding on line

I don't quite get this. How would it differ from just ladders?

> dust/smoke node - walkable (air-like) node for shorting visiblity to max 10 nodes when player looks through

Engine change needed.

> full nodes of: gold, coal, copper, diamond, tin. (not only materials, yes i know bout mods. but here we talk about core minetest, not mods like peeps on minetest repo)

I don't get this either. There are full nodes for these materials?

> weeb armor (pinky, sea and purple colors. working like steel ones): swords, showels, pickaxes, axes, and wear

Very redundant (and not exactly funny)

> chair node - to sit in. (might be even two - for one and 2 players) or a sofa

Better suited for a furniture mod; taste vastly differs here. Although MTG does provide doors.

> 'behindoculars' - reversed to binoculars. makes you able to see whats behind you

Engine change needed.

> inventory node - similar to chest but opens inventory of player instead
 
Why have a node when this is literally just one keypress away?
 
> death node - similar to fire but is black. if you touch it - your immediately dead

Pretty simple. Perhaps too simple, somewhat annoying / trolling.

> also - a node which is broken (normal node without textures)

But why?

> fishes

Those should rather be entities.

> would it be good to make middle click as inventory by default (i know i can customize. im saying bout default things)

Please file that issue on the engine repo.
 
> while riding in carts turn player seeing to current track (while going left or right - look at left or right automatically)

That does indeed sound like a nice & doable feature, but unfortunately the game is in feature freeze currently.

**Comment by hacknorris-aka-penguin** [comment]
> # The feature freeze
> 
> What @rollerozxa pointed out is correct.
> 
> > btw - dya know that update freeze might cause more viruses for platform? hope
> 
> This is _not_ an update freeze. It's a feature freeze. Bugfixes are very much merged.
> # About your features
> 
> Most need engine changes to be implemented. Doesn't really matter for MTG, which is in feature freeze.
oh, okay ;-;
> 
> > air node in inventory (as a joke, would do nothing)
> 
> Should already be possible through builitin's `/giveme`; the air nodes are invisible though and don't show a count, IIRC. They "do nothing".
AS A JOKE
> 
> > time changing nodes (day and night; 12:00 and 00:00)
> 
> But _how_ should they change the time? There already is a chatcommand.
AS AN ADDON (yes i ofen use his command. why i still didnt setted static time? lol)
> 
> > vertical rails (or a lift for carts)
> 
> Wouldn't work too well and would pretty much defy the laws of physics. The 45° rotation is already fairly problematic; such a rotation would constantly have the player's head in stone, assuming a 1x1 hole. Why can't you build a 45° staircase for your carts?
rotating player 90° ?
> 
> > ceiling ladder node - for 'walking' on a ceiling. like riding on line
> 
> I don't quite get this. How would it differ from just ladders?
ladder cant be placed on ceiling (or just normally. sliding rope)
> 
> > full nodes of: gold, coal, copper, diamond, tin. (not only materials, yes i know bout mods. but here we talk about core minetest, not mods like peeps on minetest repo)
> 
> I don't get this either. There are full nodes for these materials?
means - nodes are but only partial ores (to dig). after digging it produces materials. im thinking about adding similar nodes to it (not ores). like gold node which is fully made of gold. is diggable and placeable. not made from gold AND stone but pure gold. 
> 
> > weeb armor (pinky, sea and purple colors. working like steel ones): swords, showels, pickaxes, axes, and wear
> 
> Very redundant (and not exactly funny)
sad TwT
> 
> > chair node - to sit in. (might be even two - for one and 2 players) or a sofa
> 
> Better suited for a furniture mod; taste vastly differs here. Although MTG does provide doors.
yes. provides doors, beds, bookshelves. just that chair also could have a function to for example have a private message to a person sitting nearby and the rest similar to bed just that sitting instead of laying
> 
> > inventory node - similar to chest but opens inventory of player instead
> 
> Why have a node when this is literally just one keypress away?
yes but for a joke. same as air ;p
> 
> > death node - similar to fire but is black. if you touch it - your immediately dead
> 
> Pretty simple. Perhaps too simple, somewhat annoying / trolling.
or if you stand on it for 3 secs if really too annoying (wouldnt be by deafult. only placeable. not for seed) + would contain skull to show that will cause death
> 
> > also - a node which is broken (normal node without textures)
> 
> But why?
joke. same as air and inventory
> 
> > would it be good to make middle click as inventory by default (i know i can customize. im saying bout default things)
> 
> Please file that issue on the engine repo.
later. ok =]

**Comment by MidnightPhantom** [comment]
I have many nodes for the default mod. But I will apply them in a fork of minetest called ultimatest

**Comment by hacknorris-aka-penguin** [comment]
> I have many nodes for the default mod. But I will apply them in a fork of minetest called ultimatest

didnt knew bout it... thanx. gonna try ;)

**Comment by hacknorris-aka-penguin** [comment]
ouch... cant find it... o.O

**Comment by MidnightPhantom** [comment]
If you want new nodes for default, when my fork of minetest called ulimatest is released please try it. I am aiming to add huge amounts foilage, ores, nodes, tools, and blocks with API's too
