### ISSUE TITLE
World generation problem

### ISSUE THREAD

**Issue by MidnightPhantom** [minetest/minetest_game#2943]
Please help me with the world gen limit.
My world is supposed to load till -31000 but it loads only till -30912.
Please tell me how to fix that and also how to disable the caves and caverns below -30900.
And please add blueberry bush stems and more corals to the game

**Comment by Niklp09** [comment]
**more corals**
https://content.minetest.net/packages/Nathan.S/more_coral/
https://content.minetest.net/packages/StarNinjas/xocean/
https://content.minetest.net/packages/runs/aquaz/

**Comment by MidnightPhantom** [comment]
Actually, I have codes for more corals. But where will I get blueberry bush stem

**Comment by MidnightPhantom** [comment]
Does anybody know solution to my question of world generation

**Comment by SmallJoker** [comment]
1. The limit of ± 31000 is not accurate. It may vary by a few mapblocks, depending on how the map generator is configured to avoid over-/underflows in the calculations.
2. Disable the caverns upon world creation. There's a checkbox for it.
3. Use mods to extend Minetest Game, as new items are unlikely to be added anytime soon. See #2710 for details.
4. Please do not open one issue for various requests or questions. I assume this is answered now, hence closing.

**Comment by MidnightPhantom** [comment]
I have tried that disabling caverns too but still, my world generates till -30912 only.

**Comment by MidnightPhantom** [comment]
So should I try changing the init for this.

**Comment by SmallJoker** [comment]
You cannot extend this limit. Minetest stops generating chunks (generally 5\*5\*5 mapblocks) when they are too close to the technical limit (+32767 or -32768) to avoid miscalculations. If you desperately need some more mapblocks, you could try a recent Minetest 5.6.0-dev build which extends this limit by a few mapblocks.

**Comment by MidnightPhantom** [comment]
I tried but still result is the same.  I remember my Avast antivirus took out a file of minetest 5.6.0 saying it was infectious. It was having a name like ziplib.

**Comment by MidnightPhantom** [comment]
Or please could you tell me how can I limit cavern generation only till -30000. Is there a way to do this

**Comment by SmallJoker** [comment]
There is no lower limit for caverns in particular. All you could do is to reduce the world limit to -30000 which then might just fit within 375 times a 5\*5\*5 chunk. Please open a feature request in https://github.com/minetest/minetest or use a mapgen mod to overwrite the bottom with your desired node. Example mod. https://forum.minetest.net/viewtopic.php?t=9231

**Comment by MidnightPhantom** [comment]
I have a question. Can I add a new crop to the game

**Comment by appgurueu** [comment]
This is the wrong issue for that!? Please ask such questions on IRC.
