### ISSUE TITLE
Ensure sign content is retained on dig

### ISSUE THREAD

**Issue by Panquesito7** [minetest/minetest_game#2952]
I'm not sure if this is more of a bugfix or feature, but I don't see it as good if people can dig signs that have content. I was once making a building and destroyed a sign with important information by accident. I had a backup of the text, but for people that do not have a backup or if it's just a very important text, and they lose it, it'd be bad for our users.

What do you think? Thanks. 🙂
**EDIT:** I already have the code for this implementation.

**Comment by debagos** [comment]
Makes removing sings a bit more laborious, but I like the idea.
What do you think about a button in the form to remove it?

**Comment by Panquesito7** [comment]
> Makes removing sings a bit more laborious, but I like the idea.
What do you think about a button in the form to remove it?

That'd be a good option as well so that you don't have to remove the whole text for all signs.

**Comment by rubenwardy** [comment]
It would be better to save the sign text in the item metadata, and restore it when placed
This is probably too close to a feature to be accepted by MTG though

**Comment by Panquesito7** [comment]
That's another good idea, but as you said not sure if that's considered a feature.

**Comment by appgurueu** [comment]
> This is a feature request and should be rejected. Preventing players from digging signs, or adding ownership to signs is a gameplay change, not a bugfix. Use protection mods.

I believe you're misunderstanding the issue: This is not about protection but rather about accidentally digging *your own signs*, losing the text. Ruben has described the proper fix.

**Comment by thevbw** [comment]
This could be used for griefing, because it would take ages to remove a large number of signs one by one

**Comment by Panquesito7** [comment]
> Your **feature request** (again, note that MTG is currently in bugfix-only / maintenance-only mode) would basically lock signs
> like locked chests. It's not well-written either since you have written nothing about how to ensure backwards-compability,
> because it will be surprising if signs from old world are now suddenly locked.
>
> Since MTG is currently not accepting new features anyway, I suggest using a mod for that instead.

But this isn't locking the signs to everyone and just the owners. This issue is about _not_ being able to dig a sign if it has content, regardless if you're the owner or not. Currently, chests with content cannot be diggable regardless if they're the owner or not. That doesn't make it a locked chest. I'm trying to do the same functionality the chest has (a normal chest, not a locked chest). I think this is more of a bugfix rather than a feature, IMO.

I hope I get to understand. Thanks. :)

**Comment by appgurueu** [comment]
> The vast majority of signs will have text on them, this will destroy user experience. Either signs should store their text in item meta and restore on place, or nothing should change.

I'm starting to doubt the item meta approach because without registering a second item the two types of signs will be distinguishable only by their descriptions. This may get users wondering why they can't merge their sign stacks...

**Comment by Wuzzy2** [comment]
Sorry, but all of this will just create a compatibility nightmare. There's a reason why MTG is in maintenance mode.

**Comment by thevbw** [comment]
> > re griefing 
> Could you please explain?
It would take a long time to fumble around in a GUI for each sign if someone spammed them

**Comment by Panquesito7** [comment]
Any updates on this, or is this going to be rejected? Thanks.

**Comment by appgurueu** [comment]
Marking this as a possible close as being an UX change it's pretty much an (albeit minor) feature request.

**Comment by sfan5** [comment]
This is clearly a feature IMO and should be rejected.
