### ISSUE TITLE
Error in mod weather

### ISSUE THREAD

**Issue by PrairieAstronomer** [minetest/minetest_game#2961]
When I try to open a minetest_game in singleplayer on minetest 5.5.1, I get this issue:

```
AsyncErr: Lua: Runtime error from mod 'weather' in callback on_joinplayer(): ...inetest/bin/../games/minetest_game/mods/weather/init.lua:117: attempt to call method 'set_lighting' (a nil value)
stack traceback:
	...inetest/bin/../games/minetest_game/mods/weather/init.lua:117: in function 'update_clouds'
	...inetest/bin/../games/minetest_game/mods/weather/init.lua:134: in function <...inetest/bin/../games/minetest_game/mods/weather/init.lua:133>
	/home/prairiewind/minetest/bin/../builtin/game/register.lua:429: in function </home/prairiewind/minetest/bin/../builtin/game/register.lua:415>
```

I did try recloning minetest_game, but still the same issue.

**Comment by appgurueu** [comment]
You'll need [MTG 5.5.1](https://github.com/minetest/minetest_game/releases/tag/5.5.1). The latest master targets & is only compatible with the engine latest master (5.6.0-dev) due to the use of `player:set_lighting` in the weather mod. Alternatively you can upgrade MTG to the newest dev version.

**Comment by PrairieAstronomer** [comment]
I dont know if it was due to me doing a shallow clone, but last time I tried to use the current dev version, I couldn't even open a singleplayer world, so I dont want to upgrade at the moment.

**Comment by appgurueu** [comment]
> I dont know if it was due to me doing a shallow clone, but last time I tried to use the current dev version, I couldn't even open a singleplayer world, so I dont want to upgrade at the moment.

That's fine. You'll have to "downgrade" MTG then though.
