### ISSUE TITLE
why does default:glass have paramtype2 = "glasslikeliquidlevel"?

### ISSUE THREAD

**Issue by fluxionary** [minetest/minetest_game#2962]
I see https://github.com/minetest/minetest_game/pull/1673, but that was closed without merging. Instead, it just got committed, but without a texture? https://github.com/minetest/minetest_game/commit/2f46103ff8fc6f0e9bf2cf6dc507ccc5f4fb6ea8

Currently, the behavior just creates a randomly-colored (on the client side) unknown texture if glass somehow accidentally gets imbued w/ a param2 value. It's been like this since I started playing (0.4.17.1). 

![screenshot_20220615_130708](https://user-images.githubusercontent.com/25628292/173917580-7dbdee7d-38af-464c-b9f1-c2ee6e61cf12.png)

**Comment by fluxionary** [comment]
I am willing to code up a PR to "fix" this, but what do the minetest gods prefer? 
* change paramtype2 to `glasslike`/`glasslike_framed_optional`/whatever
* add alternate glass nodes which properly point `special_tiles` @ water texture or something.  
* add `special_tiles` to the existing glass nodes (i don't like this)
* something else?

**Comment by sfan5** [comment]
IRC log from that time: https://irc.minetest.net/minetest-dev/2017-03-28#i_4843313
Looking at https://github.com/minetest/minetest/pull/5478 confirms that `glasslike_framed` always had a a liquid level before the paramtype2 option was added, hence this will have been changed in MTG to keep compatibility with previous behaviour.

However I agree that having this paramtype and then no texture for it makes no sense. I'd support just removing it.
