### ISSUE TITLE
Dungeon loot seems to not work on mods outside mtg.

### ISSUE THREAD

**Issue by CowboyLva** [minetest/minetest_game#2967]
Even when chance is set to high like 0.9 I can't seem to get it work.

**Comment by sfan5** [comment]
Can you show the code you used? Which version of Minetest and Minetest Game are you using?

**Comment by sfan5** [comment]
https://github.com/CowboyLva/ebiomes/blob/b20f75bed3a5c76cfbc5854ee5fe2bae3ecb96fe/loot.lua#L8-L10
You're overwriting `dungeon_loot.register` with a table, remove the equals sign.
