### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Natalect** [minetest/minetest_game#2978]
Jumping on side of block causes player to go two blocks instead of one
Water does not negate fall damage
I could not upload a video explaining this because GitHub does not allow videos more the 10MB.
<img width="656" alt="Screen Shot 2022-08-09 at 9 13 02 PM" src="https://user-images.githubusercontent.com/93022049/183813597-cb439c93-a784-414a-b856-c9228c7c52b9.png">

**Comment by rollerozxa** [comment]
These are intentional features of the Minetest engine and not bugs.
