### ISSUE TITLE
(Question) How node breaking time is calculated

### ISSUE THREAD

**Issue by oong819** [minetest/minetest_game#2981]
its seem like there is no hardness and blast resistance, so how node breaking time work? also TNT can blow up any nodes?

**Comment by Skamiz** [comment]
Here is the relevant section of the official documentation: [https://github.com/minetest/minetest/blob/5.6.0/doc/lua_api.txt#L1940](url)
And here is a forum topic to answer your question: [https://forum.minetest.net/viewtopic.php?f=47&t=27811](url) which you might find easier to understand.
