### ISSUE TITLE
Make TNT dont destroy low cracky value nodes

### ISSUE THREAD

**Issue by oong819** [minetest/minetest_game#2983]
from what i know, there is a cracky value that affect node breaking time
but TNT can destroy everything, so pls make it dont destroty low cracky node

**Comment by appgurueu** [comment]
> but TNT can destroy everything, so pls make it dont destroty low cracky node

This is not accurate. Nodes can override `on_blast` to not be destroyed. Depending on `ignore_protection` of registered TNTs, protected nodes won't be destroyed either.
