### ISSUE TITLE
Why is the skeleton key a skeleton key? And whats so special about it? 

### ISSUE THREAD

**Issue by ixPost** [minetest/minetest_game#2985]

**Comment by appgurueu** [comment]
A skeleton key is a key "template". The first time you use it - e.g. by punching a steel door - it becomes a key to that protected node, in this case the steel door. You can then give this key to other players, allowing them to open your steel door using it.

**Comment by ixPost** [comment]
> A skeleton key is a key "template". The first time you use it - e.g. by punching a steel door - it becomes a key to that protected 
> node, in this case the steel door. You can then give this key to other players, allowing them to open your steel door using it.

You mean that that's the reason why it's called a skeleton key?

**Comment by appgurueu** [comment]
Yes
