### ISSUE TITLE
Multi-ownership

### ISSUE THREAD

**Issue by ixPost** [minetest/minetest_game#2986]
Shouldn't we have a possibility too have multiple key that unlock the same thing and one key too unlock multiple things?

**Comment by appgurueu** [comment]
Perhaps worth a thought, but Minetest Game is in feature freeze unfortunately; and even if it wasn't, this would be low-priority.

**Comment by ixPost** [comment]
Does this mean no features are excepted?

**Comment by appgurueu** [comment]
> Does this mean no features are excepted?

Pretty much, yes.

**Comment by ixPost** [comment]
???

**Comment by ixPost** [comment]
> Perhaps worth a thought, but Minetest Game is in feature freeze unfortunately; and even if it wasn't, this would be low-priority.

Why is it in feature freeze.
