### ISSUE TITLE
Please reduce ore generation limit

### ISSUE THREAD

**Issue by MidnightPhantom** [minetest/minetest_game#2991]
Please reduce the ore generation limit to -30000. It creates a lot of ruckuses if one punches gravel ore sand above open spaces causing them to fall below the world limit which cannot be even corrected without a mod. So please do this required change

**Comment by appgurueu** [comment]
That would not be a "required change" but rather a workaround. Falling nodes hitting the world edge should be turned into nodes by the engine. See https://github.com/minetest/minetest/issues/11343.
