### ISSUE TITLE
Ugly opaque leaves: blueberry bush with blueberries, and aspen

### ISSUE THREAD

**Issue by Desour** [minetest/minetest_game#3001]
Screenshot of all leaves in opaque leaves mode (forgot pine needles, but they look fine):
![screenshot_20221124_143821](https://user-images.githubusercontent.com/7613443/203798099-f14cebf8-7086-41f3-bbaf-a9e38fb59b48.png)
Blueberry bush leaves with blueberries (bottom left) and aspen leaves (bottom right) are ugly.
The corresponding textures (`default_blueberry_overlay.png` and `default_aspen_leaves.png`) need better transparent colors.

(Btw. aspen could also use a thicker texture for simple leaves mode.)

**Comment by Loppansson** [comment]
Aspen tree suggestion:
![image](https://github.com/minetest/minetest_game/assets/61879422/8fa5c83d-0914-453b-a247-d2f6b31e4be5)

16x16 resolution:
![image](https://github.com/minetest/minetest_game/assets/61879422/85c2db49-d76d-4551-9d94-fc7b30942785)

**Comment by Loppansson** [comment]
As these has been merged, it seams appropriate to close it?:)
