### ISSUE TITLE
Door handle of glass door inventory image is on the wrong side

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#3002]
On the inventory image of the glass door and obsidian glass door, the door handle is on the wrong side. The handle is to the left but if you place the door (without any neighboring door), the handle will be at the right.
Interestingly the handle for the steel bar door is correct.

Suggested bugfix: Edit the inventory images to put the handle at the other side.

**Comment by Loppansson** [comment]
Has this been resolved as of "Flip textures of glass door"?:)

**Comment by appgurueu** [comment]
> Has this been resolved as of "Flip textures of glass door"?:)

Yes, thanks for the reminder.
