### ISSUE TITLE
Grass in the void

### ISSUE THREAD

**Issue by JeanPaulLucien** [minetest/minetest_game#3006]
You should manipulate with distance view using - and + buttons to find same situation. I recommend to use fly, because this bug breaks your beatifull panoram view from buildings.

In the middle of screenshot you can see grass without ground. Ground was not removerd, ground under grass, but distance view shows grass without ground.

![screenshot_202212_05](https://user-images.githubusercontent.com/24779886/209865381-da10f905-eadc-4bb5-b85c-e2a95567f2a6.png)

**Comment by rollerozxa** [comment]
> This is akin to saying it's a bug that I can't see a mountain fifty metres ahead when my view range is the minimum 20. Or that a building in the distance right at the view range border is cut off. Either raise the view range or enable fog to hide the mapblock seams.

**Comment by SmallJoker** [comment]
Rendering is done in minetest/minetest. Minetest Game aka MTG is a game that only adds content without actually controlling how it's sent to the graphics pipeline. 

Wrong repository. Duplicate. Closing. Please stop this.
