### ISSUE TITLE
re-aligned wood and junglewood textures

### ISSUE THREAD

**Issue by VanessaE** [minetest/minetest_game#302]
...so that the dark lines line up with the center and bottom edge of the tile (fits better with stairs et al.)
![default_wood](https://cloud.githubusercontent.com/assets/1733537/3940772/d4fc7be2-24f2-11e4-9676-c30ed2afc186.png)
![default_junglewood](https://cloud.githubusercontent.com/assets/1733537/3940773/d882440e-24f2-11e4-8c34-4762809b8d24.png)

**Comment by C1ffisme** [comment]
Why is this an issue and not a pull request? Also, It hasn't seen any talk for almost 2 months.

**Comment by BlockMen** [comment]
@C1ffisme because it won't get merged until engine has changed

**Comment by C1ffisme** [comment]
Ah, I see.

**Comment by paramat** [comment]
I feel this should be closed. The dark line is the join between pieces of wood, if this join is at the extreme upper or lower edge of a side texture it means the top or bottom node textures are also the join and should be coloured to match the join, this of course would look very wrong having a dark join surface next to air. The rows of pixels at the extreme upper or lower edge of a side texture are the sides of the micro-voxels forming the top or bottom surfaces of the node.

**Comment by VanessaE** [comment]
Seems not to be wanted.  Fair enough.
