### ISSUE TITLE
`default_apple.png` not mentioned in license

### ISSUE THREAD

**Issue by Panquesito7** [minetest/minetest_game#3025]
### Description

The `default_apple.png` file is not mentioned in the license file of the `default` mod.
I tried searching the original authors, and it appears they are Celeron, PilzAdam, and Vanessa Ezekowitz (see [file history](https://github.com/minetest/minetest_game/commits/master/mods/default/textures/default_apple.png)).

We have the authors, but what license exactly is used here? I assume CC BY-SA 3.0, but we have to be 100% sure about this.

**Comment by Desour** [comment]
https://github.com/minetest/minetest_game/blob/833ed776204b194d96b50e400861dec07b5c16aa/mods/default/README.txt#L13-L16

**Comment by Panquesito7** [comment]
Ooh, my bad, how could I miss that? 😅
Thanks, though. Closing.
