### ISSUE TITLE
One can drop gravel forever if the chasm is too deep

### ISSUE THREAD

**Issue by herbert-west2** [minetest/minetest_game#3026]
Problem is demonstrated in attached video

https://user-images.githubusercontent.com/108707524/232319062-3edb6e2f-a015-4017-a7ff-d153ad8652d0.mp4

**Comment by appgurueu** [comment]
Is this not in creative mode? If so, that would be an engine bug, since our gravel node definition is just:

```lua
minetest.register_node("default:gravel", {
	description = S("Gravel"),
	tiles = {"default_gravel.png"},
	groups = {crumbly = 2, falling_node = 1},
	sounds = default.node_sound_gravel_defaults(),
	drop = {
		max_items = 1,
		items = {
			{items = {"default:flint"}, rarity = 16},
			{items = {"default:gravel"}}
		}
	}
})```

**Comment by herbert-west2** [comment]
I first noticed the problem in survival mode.

It indeed seems to be an engine bug. Perhaps I should post this there instead.
