### ISSUE TITLE
Add a crafting table and anvil(for crafting hard stuff ex. steel sword)

### ISSUE THREAD

**Issue by ixPost** [minetest/minetest_game#3028]
You can craft any thing with your hands even iron tools

So the player should have a 2x2 crafting grid the crafting table should be made of 4 wood planks or rather a wooden log and a wood plank on top, then the anvil should be made like this:    S - stone   N - Nothing
S S S
N S N
S S S

**Comment by appgurueu** [comment]
See https://github.com/minetest/minetest_game/issues/2710.

**Comment by fluxionary** [comment]
@ixPost you may be interested in the [MineClone2](https://content.minetest.net/packages/Wuzzy/mineclone2/) game, available from the content DB.

**Comment by ixPost** [comment]
> @ixPost you may be interested in the [MineClone2](https://content.minetest.net/packages/Wuzzy/mineclone2/) game, available from the content DB.

I know about it but what about MTG and games based off of it?
