### ISSUE TITLE
Player API: is animation blend still broken?

### ISSUE THREAD

**Issue by MisterE123** [minetest/minetest_game#3033]
I thought that animation blend is no longer broken; nodecore uses it.
https://github.com/minetest/minetest_game/blob/996fea7cd051895375b99b79926bf12966933603/mods/player_api/api.lua#L4

This line in player api disables animation blend and claims it is broken due to a bug in irrlicht. Is that still the case or can animation blend be re-enabled?

Probably, if it is no longer broken, a fix should expose animation blend as a game setting, possible turning it on by default, but easily reverted in minetest.conf

**Comment by MisterE123** [comment]
Yep it is still broken. Sorry to bother you guys

**Comment by wks** [comment]
Is there any updates to this?  I am using Luanti 5.16.1 and the latest Minetest Game as of July 2026.  I set the `animation_blend` variable to 0.5 and it seems to work fine.  There are other games, such as [backroom](https://content.luanti.org/packages/Sumianvoice/backroomtest/) that [aggressively uses the blend argument](https://codeberg.org/SumianVoice/backroomtest/src/commit/0a4770b7f19018e280c09a4b12614909de5baba5/mods/player/br_player_model/init.lua#L11) and still works fine.

**Comment by appgurueu** [comment]
See https://github.com/luanti-org/luanti/issues/14817. As far as I'm concerned, it should be working as expected.

Whether MTG should use it, leave it at zero or make it configurable (if so, probably API-wise rather than setting-wise) is a different question. The comment should be updated either way.
