### ISSUE TITLE
“access” privilege for bypassing protection (chest, furnace, door, node…)

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest_game#304]
Add an **“access”** privilege for bypassing protection (chest, furnace, door, node…).

This way, we have a standard way of bypassing protection. No need to check for `name` in minetest.conf, since the `name` player already has all privileges.

**Comment by tenplus1** [comment]
Removing a locked chest on a server can easily be done by using the Admin Stick tool from the forums, it allows players with privelage to remove ANY block (chests, doors, cloud block etc.)

**Comment by thatgraemeguy** [comment]
Presumably the proposed "access" privilege would allow for a suitably privileged player to access the content of such locked items, not just to simply remove them, and would thus be different to an admin pick.

**Comment by C1ffisme** [comment]
Why do we have another issue on this? We have a pull request!!! We don't need another issue!

**Comment by BlockMen** [comment]
closing. further discussions here: #242
