### ISSUE TITLE
Setting the player animation silently fails

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#3042]
Is it just me or did the setting of player animations suddenly stop working?

Install `luacmd`, create a new world, enable only the `luacmd` mod, start the world, then write into chat:

```
/lua player_api.set_animation(me, "sit", 30)
```

The player model should sit but it keeps standing. I also tried other animations like "mine" but it all fails. There is no error message or warning.

I'm not sure if I use `player_api` just incorrectly or if it actually broke.

Tested in 5.7.0.

**Comment by rollerozxa** [comment]
I've had this issue too for some time now, but it's odd because sometimes it works and sometimes it doesn't.

**Comment by appgurueu** [comment]
Can reproduce with boats; sometimes it works and sometimes it doesn't. Very odd. Might be related to local animations.
