### ISSUE TITLE
Stairs mod does not support translation of Inner and Outer Stairs

### ISSUE THREAD

**Issue by TheOnlyJoeEnderman** [minetest/minetest_game#3048]
The English words Inner and Outer are hard-coded into the stairs mod. When the language is switched, these words are always in the same place, and always in English. I believe this is unintended behavior. Attempting to add the proper translation keys for Inner and Outer variants even crashes the game.

This is an example of code that should work but will instead crash the game:
	S("Example Stair"),
	S("Inner Example Stair"),
	S("Outer Example Stair"),
	S("Example Slab"),

This example is the only current way stairs mod accepts:
	S("Example Stair"),
	S("Example Slab"),

**Comment by TheOnlyJoeEnderman** [comment]
![screenshot_20230817_183603](https://github.com/minetest/minetest_game/assets/95948552/9dc0c603-8cc0-4fb1-a426-b8fdeeda76d4)
![screenshot_20230817_183705](https://github.com/minetest/minetest_game/assets/95948552/753011da-466e-4d26-8c6b-17339f21baba)

**Comment by TheOnlyJoeEnderman** [comment]
I had to use 5.3 because there is no later Debian port that supports language switching.

**Comment by appgurueu** [comment]
The culprits:

https://github.com/minetest/minetest_game/blob/9e77e00c650db7a49d45d94b429ff7be9fcec643/mods/stairs/init.lua#L355

https://github.com/minetest/minetest_game/blob/9e77e00c650db7a49d45d94b429ff7be9fcec643/mods/stairs/init.lua#L447

This is in the public API. There is a `full_description` parameter documented as being useful for translation and avoiding string concatenation, which the code seems to implement correctly. The blocks you're showing seem to originate from other mods, which probably fail to utilize the API properly (arguably the API is a footgun). The `stairs.register_stair_and_slab` which calls these has the same footgun.

My wild guess for the crash: It may be nesting translation strings.

**Comment by sfan5** [comment]
The API is indeed bad but it had to be this way to preserve backwards compatibility.
It is possible to register correctly translated stairs and slabs:
```lua
stairs.register_stair_and_slab("foo", "my:foo_item", groups, {"foo.png"},
    S("Foo Stair"), S("Foo Slab"), sounds, false,
    S("Inner Foo Stair"), S("Outer Foo Stair")
)
```

> I had to use 5.3 because there is no later Debian port that supports language switching.

We can't support software that is 3 years old.

**Comment by appgurueu** [comment]
@TheOnlyJoeEnderman please point out the offending mod so that a PR with fixes can be submitted. Closing this as it's not a MTG issue.

**Comment by TheOnlyJoeEnderman** [comment]
Don't worry, I am the dev of the mod in question, I will see if I can implement a fix. Thanks for the answers.

**Comment by TheOnlyJoeEnderman** [comment]
> We can't support software that is 3 years old.

I am not expecting you to. I just couldn't verify my translations worked on the 5.7 Flatpak, and had to boot up my mod in 5.3 to see my translations at all.

**Comment by TheOnlyJoeEnderman** [comment]
After applying said fix, I still cannot get translations working.
[too_many_stones.zip](https://github.com/minetest/minetest_game/files/12449076/too_many_stones.zip)
![screenshot_20230827_184921](https://github.com/minetest/minetest_game/assets/95948552/f14a756d-121d-42fe-b4b3-a32f301a5fa8)
![screenshot_20230827_184932](https://github.com/minetest/minetest_game/assets/95948552/0fc2dc6a-95c7-4b1d-86dc-14012f3fcb1d)

**Comment by TheOnlyJoeEnderman** [comment]
Maybe, but unless there are major API changes, the mod is nearly finished. It will be so little added in future it won't be worth the major code rewrite. I guess unless I want to make it into an API that anyone can instantly add all the stone types. But that is not a current goal.
