### ISSUE TITLE
Refactor the sapling and tree growing system

### ISSUE THREAD

**Issue by aegroto** [minetest/minetest_game#3050]
## Problem

The default sapling grow function, which is default.grow_sapling at line 39 in trees.lua, is currently made of an hard-coded sequence of if statements that link each sapling type to its respective function. I believe this system is a bit messy and makes it difficult for modules to add new trees.

## Solutions

Refactor this component to add a dynamic linking between sapling node names and grow functions, using public APIs available to custom modules to register their own tree.

## Alternatives

An alternative may be to maintain the current code as legacy by adding an additional "else" statement where additional trees registered by external modules are handled.

**Comment by aegroto** [comment]
@appgurueu I forgot to write in the original post that I am willing to work on the implementation if any help is needed.

**Comment by appgurueu** [comment]
Sure, feel free to refactor it. I'll gladly review your PR.

**Comment by JoseDouglas26** [comment]
Is that issue closed?

**Comment by appgurueu** [comment]
Indeed this issue is closed, thanks for the reminder.
