### ISSUE TITLE
Replacements needed for water textures sourced from Minecraft texture packs

### ISSUE THREAD

**Issue by GreenXenith** [minetest/minetest_game#3051]
(Brought to attention by [CptCorn](https://www.planetminecraft.com/member/cpt_corn/) on the Minetest Discord)

The animated water texture (and by extension the flowing water, default water, and river water textures) added in 5497db9 is a derivative of the water texture from the (long-defunct) Minecraft [Painterly Pack](https://web.archive.org/web/20111008012144/http://painterlypack.net/files/PainterlyPack.zip). The pack does not include a license (at least during that time).

<details>
<summary>Dubious permission at best</summary>

```
Painterly Pack
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
by rhodox & friends
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unless noted otherwise, all graphics in this pack were edited and created by me.
A few textures were generously provided by various individuals and are included
in the pack with permission. These individuals are credited under their
individual contributions on the web site (www.painterlypack.net). The default
paintings are NES sprites, and so belong to whoever made those games, I suppose. 

This pack may be used freely in whole or in part by any owner of Minecraft, and
combined with other texture packs, so long as credit is given and no profit or
donations are solicited through that person's use of my textures and skins. You
don't have to credit me if you use it with your youtube videos or promoting your
server or things of that nature, but it's appreciated if you do.

The pack is given away freely, however, donations for the time invested and
ongoing development and testing of The Painterly Pack are extremely appreciated.
The Donate link can be found on at painterlypack.net, and if you got it from
anywhere else, it's not the official source and probably out of date.
```
</details>

The animated texture itself may be from an early version of the [Coterie Craft](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/resource-packs/1223548-32x-16x-coterie-craft-default-revamped) pack, which used the Painterly Pack water as a base.

Comparison of [`default_water_source_animated.png`](https://github.com/minetest/minetest_game/blob/5.7.0/mods/default/textures/default_water_source_animated.png) to Painterly Pack water:
![water_comparison](https://github.com/minetest/minetest_game/assets/24834740/679b9193-98b9-4728-8050-31306d41f432)

There is enough evidence to support it being a recolor/shift of at least one or two dubiously-licensed sources. A suitable replacement for the water textures should be created or found as soon as possible.

We should also consider (once again) vetting the MTG textures, maybe with the help of those familiar with the Minecraft texturepack ecosystem.

**Comment by Loppansson** [comment]
Hi! I would be interested in creating a new water texture! Are there any specific requirements needed for the texture?:)

**Comment by appgurueu** [comment]
> Hi! I would be interested in creating a new water texture! Are there any specific requirements needed for the texture?:)

Thanks for the offer! I'd say please try to make it fit in with the style of the rest of the textures. That's about it.

**Comment by Loppansson** [comment]
Aright!:)

**Comment by Loppansson** [comment]
Yo! After some tinkering around, i manged to make the following. Thoughts so far?:)

[Screencast from 2023-08-26 21-03-47.webm](https://github.com/minetest/minetest_game/assets/61879422/14b28850-84c0-4249-a4c4-e9199f06817e)

![default_water_source_animated](https://github.com/minetest/minetest_game/assets/61879422/8ac2d637-30f1-496a-bebb-52cfc0c33ce5)

**Comment by Loppansson** [comment]
Alrighty! I'm done:) Note that the river water is the exact same as "normal" water, but with a -15 hue shift.

Here's a preview of water:

https://github.com/minetest/minetest_game/assets/61879422/2e36b183-403f-4ab7-9633-1cb81228a5dd

... and here's all the textures as a texture pack:

[new_water.zip](https://github.com/minetest/minetest_game/files/12448431/new_water.zip)

... and here's all the textures on their own:

![default_water](https://github.com/minetest/minetest_game/assets/61879422/fae8cc61-3165-4c2e-a6e7-e113b944930a)
![default_river_water](https://github.com/minetest/minetest_game/assets/61879422/241eb9d7-5f1d-4753-b037-c0e5ab97c658)
![default_river_water_source_animated](https://github.com/minetest/minetest_game/assets/61879422/451675c2-fb7c-4b02-a705-cfa67d628b81)
![default_water_source_animated](https://github.com/minetest/minetest_game/assets/61879422/ff344b53-780f-42fa-b4a9-99724037f14a)
![default_water_flowing_animated](https://github.com/minetest/minetest_game/assets/61879422/8060dac3-7ff8-4530-b914-23122062c283)
![default_river_water_flowing_animated](https://github.com/minetest/minetest_game/assets/61879422/c80d63f2-91de-4eb1-bd0c-6c6ac933608c)

**Comment by Loppansson** [comment]
I have now made a PR: https://github.com/minetest/minetest_game/pull/3056
