### ISSUE TITLE
eye_height and collisionbox not set by player_api.set_model()

### ISSUE THREAD

**Issue by ghost** [minetest/minetest_game#3052]
I wanted to have some player models that use a different eye height and collision box. however even though I set them in the table given to register_model(), they don't take effect on set_model.

Right now i just set them manually afterwards as a workaround.

also note that this was originally posted here https://github.com/minetest-game/player_api/issues/1#issue-1570589430 but maybe it belongs here instead.

**Comment by appgurueu** [comment]
This should be the correct way to register a player model. Are you sure that it doesn't work with MTG latest master? Possibly related: https://github.com/minetest/minetest_game/commit/8d60e85dfc25dffbcfb2bf30cd57de0c5f38b97b. Do you have that commit?
