### ISSUE TITLE
add support of 0.5x and 0.25x maps

### ISSUE THREAD

**Issue by Firestar-Reimu** [minetest/minetest_game#3054]
Sometimes I think the 1x map is still to small for me (cannot show a large area), maybe smaller scale map can be supported?

**Comment by NathanSalapat** [comment]
Are you talking about the mini-map?

**Comment by appgurueu** [comment]
This should be possible using `player:set_minimap_modes`.
However MTG is in feature freeze and this is pretty clearly a feature request.

Configurable minimap size could also be treated as an engine feature request.
