### ISSUE TITLE
Trapdoor Texture Issue

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest_game#3055]
Place a wooden trapdoor, turn right and place another, now open both doors, guaranteed that one has a black strip on the top of it (at least in 5.7 and 5.8 clients), something is up with textures.

**Comment by Loppansson** [comment]
I'm unable to reproduce; am i misinterpreting the instructions?:)

![image](https://github.com/minetest/minetest_game/assets/61879422/b3af1159-430d-4d44-ba81-bab6c7b57ae8)

**Comment by NathanSalapat** [comment]
Everything looks correct for me as well.

**Comment by tenplus1** [comment]
![a](https://github.com/minetest/minetest_game/assets/8145060/3c3dd7f2-394f-4fd1-9757-84bedd6aaf70)

This is what I see on Minetest 5.7 running on AMD Ryzen 5 4600G graphics with both shaders on and off.

**Comment by appgurueu** [comment]
Can't reproduce; the trapdoor texture looks fine to me and hasn't been changed in years. This is probably an engine regression concerning changes to the graphics pipeline.

@Zughy could you please transfer this to the engine issue tracker?

@tenplus1 could you add more details, such as exact Minetest version, operating system, hardware, minimal settings needed to reproduce etc. (the usual works for reporting graphic issues)?
