### ISSUE TITLE
MTG textures overhaul? 

### ISSUE THREAD

**Issue by temhotaokeaha** [minetest/minetest_game#3061]
MTG's default textures are somewhat lacking. "It's in maintanence mode" -- been 3 years and MTG is STILL the first thing that 99% of people will see about Minetest because it's the "default game". Latest example: https://www.youtube.com/watch?v=va-YHeytvFQ -- big youtuber makes video about MT, obviously picks MTG to play, has to play with textures which could be better.

inb4 "texturepacks" -- DEFAULTS should be SANE and default textures updates are something Minecraft and Terraria went through.

Thoughts?

**Comment by appgurueu** [comment]
I am in favor of a texture redo (including making an exception to the maintenance mode for this). Waiting on input from other @minetest/game maintainers.

**Comment by sfan5** [comment]
I think the primary problem here is that MTG is still presented as default game.
Texture reworks have historically always been lots of back-and-forth with subjective opinions so I'd rather not do one now (it also doesn't fit the maintenance mode).

Lastly the question would be: who is going to create the textures?

**Comment by rubenwardy** [comment]
I think two compelling reasons to replace all the MTG textures is that you can:

1. ensure they're all original and licensed correctly
2. make it more visually distinct from certain existing games (although, this would cause mods to look more inconsistent than they already do, but oh well)

**Comment by sfan5** [comment]
> Yes, is that changing any time soon though?

Hopefully: https://github.com/minetest/minetest/pull/13550

> Okay, but should there be a complete consensus on this or how does the PR approval work exactly?

Basically two MTG devs have to agree on a PR for it to get merged.
There will just be lots of discussion if you plan something as large as replacing every texture.

**Comment by tenplus1** [comment]
The textures are fine for a base game and many texture packs exist in the Content tab for preview and download.

**Comment by temhotaokeaha** [comment]
> Hopefully: https://github.com/minetest/minetest/pull/13550

(from discord)
**TEMHOTAOKEAHA**: _i just came here with the proposal of texture overhaul and everybody collectively decided to finally flush MTG down the toilet_
**GreenXenith**: [...] _it may be more likely for MTG to start accepting new features as it wont be tied as much to the engine_

Green made a good point so since it's finally happening let's come back to textures once the dust from decoupling MT/MTG settles.
