### ISSUE TITLE
Lavacooling

### ISSUE THREAD

**Issue by MidnightPhantom** [minetest/minetest_game#3064]
Hey to anyone hearing this, I just wanted to ask why the lava takes so much time to cool. In Minecraft the speed is actually faster than in this game, please just answer, I'll close the issue once answered, and also please tell me how to fix it because I tried making an infinite cobblestone generator just like that in Minecraft but it got kind of messed up on its birth.

**Comment by tenplus1** [comment]
The simple answer is that Minetest is not Minecraft, and that lava cooling uses an ABM that runs every 2 seconds with a 1 in 2 chance of cooling lava.

https://github.com/minetest/minetest_game/blob/master/mods/default/functions.lua#L155

**Comment by MidnightPhantom** [comment]
Hey how to increase chance of lavacooling please just tell me that
