### ISSUE TITLE
Why the number of lump does not increase

### ISSUE THREAD

**Issue by Firestar-Reimu** [minetest/minetest_game#3069]
For example, if I mine an iron ore, an iron lump will appear on my menu

But if I mine 10 iron ore with my pickaxe/any other hard things, it will show only as an iron lump with no numbers on it. If I use the furnace, it acts only as 1 lump.

How can the lump of minerals increase?

**Comment by NathanSalapat** [comment]
You are probably playing with creative mode turned on.
