### ISSUE TITLE
Vessel description does not update

### ISSUE THREAD

**Issue by rollerozxa** [minetest/minetest_game#3072]
Regression caused by https://github.com/minetest/minetest_game/commit/0c2ee1e41d71899f0d5e1da603a6d125a7cda9e9, making vessel's infotext not update. Bookshelves were broken too by this commit but seems to have been fixed since then.

**Comment by Niklp09** [comment]
Bookshelves were fixed in https://github.com/minetest/minetest_game/commit/cd6ea53a524bfb6fdc95cfcd23112dc970fc15f9
