### ISSUE TITLE
Butterflies has no pt_BR translation

### ISSUE THREAD

**Issue by JoseDouglas26** [minetest/minetest_game#3084]
The butterfly mod does not have a translation into Brazilian Portuguese yet

**Comment by appgurueu** [comment]
Feel free to translate it if it bothers you. (Side note: I'm not sure what our policy is on issues pointing out missing translations, but I don't think there's much point in such issues: The translations will always be incomplete.)

**Comment by sfan5** [comment]
Indeed, I'll close this but you're obviously still welcome to contribute.
