### ISSUE TITLE
wrong drop when written book is blown up with tnt

### ISSUE THREAD

**Issue by fluxionary** [minetest/minetest_game#3096]
if you blow up a written book node with tnt, it will drop a "default:book_close" or "default:book_open" item instead of a "default:written_book", and the contents will be missing.

**Comment by tenplus1** [comment]
Tested in 5.7/5.8, dropped written book, blew it up, picked up book and read it ok.

**Comment by appgurueu** [comment]
Upon closer inspection, this is not a MTG issue. We don't have book nodes; we only have book craftitems. Another mod is probably responsible for the improper drops (unless there was a bug in the `tnt` mod).

**Comment by fluxionary** [comment]
oh right, it's from https://github.com/everamzah/books, apologies

**Comment by tenplus1** [comment]
@fluxionary - Fixed the issue and uploaded mod to forum: https://forum.minetest.net/viewtopic.php?p=432608#p432608
