### ISSUE TITLE
chest dupe

### ISSUE THREAD

**Issue by Kimapr** [minetest/minetest_game#3103]
steps of to reproduction

1. open chest (make sure there is a node on top to block it)
2. dig it (while open)
this can be done either with the help of another player, or using pipeworks breaker
draconic fire might also work but not tested
4. close it

resulted

dug chest kept and another one appears
you now have 2 chest total

**Comment by EGYT5453** [comment]
https://xkcd.com/1172/

**Comment by SmallJoker** [comment]
This should be fixed since 83c10f59e1f30, aka v5.8.0.

**Comment by Kimapr** [comment]
indeed it seems my installation is of version v5.6.0
