### ISSUE TITLE
Fire doesn't Spread anymore

### ISSUE THREAD

**Issue by DustyBagel** [minetest/minetest_game#3111]
Currently fire doesn't spread in game anymore.  I also noticed that the minetest_game setting for fire spreads doesn't exist anymore too.

**Comment by tenplus1** [comment]
Fire will spead in a singleplayer game but disable itself in a multiplayer one unless the "enable_fire" setting has been set to true inside minetest.conf file.

https://github.com/minetest/minetest_game/blob/master/mods/fire/init.lua#L10

**Comment by DustyBagel** [comment]
Oh yeah, I remember having to do something like that to get it to work. Sorry about the false bug report.
