### ISSUE TITLE
Cacti with arms have their nodes generated upside down, straight cacti don't

### ISSUE THREAD

**Issue by mruncreative** [minetest/minetest_game#3122]
Cacti with arms have their nodes generated upside down, straight cacti don't (in both v6 and v7).
I noticed that while applying an override to the top of the cactus node.
luatic on IRC asked whether it's in
https://github.com/minetest/minetest_game/blob/master/mods/default/schematics/large_cactus.mts
I loaded it with worldedit //mtschemplace and its nodes are upside down. (I build the cactus below for comparison)
![grafik](https://github.com/minetest/minetest_game/assets/67873653/ea9e09c9-d79f-43bc-a8f9-5ff8039d98c3)

**Comment by appgurueu** [comment]
Feel free to open a PR with a corrected version of the schematic.

**Comment by mruncreative** [comment]
I know mts files contain probability data and are not mere chunks of nodes. I dunno how to edit them without fucking it up.

**Comment by sfan5** [comment]
https://github.com/minetest/minetest_game/blob/master/schematic_tables.txt

**Comment by mruncreative** [comment]
I don't know how to generate an mts from that but I'll note that just removing param2 from large_cactus should work. I think it would default to 0 which is correct.
