### ISSUE TITLE
Minecart

### ISSUE THREAD

**Issue by GNUAn** [minetest/minetest_game#3140]
Minecart cannot be stopped and cannot be broken. How do I build subway in MTG?

**Comment by SmallJoker** [comment]
Please read the itemstack tooltip description. Use Sneak+Click to pick it up. You can stop it by holding the brake (backwards movement key).

**Comment by GNUAn** [comment]
> Please read the itemstack tooltip description. Use Sneak+Click to pick it up. You can stop it by holding the brake (backwards movement key).

Thanks!
