### ISSUE TITLE
Get current player class?

### ISSUE THREAD

**Issue by mrGoodWolf** [minetest/minetest_game#3154]
hi i was wondering how to get current player class for player_api.set_model()

`
player_api.set_model(currentplayerclass, blah_model)
`

**Comment by SmallJoker** [comment]
https://github.com/minetest/minetest/blob/8972c80d7d5c5abdd31a0ab7caec7076769e1adb/doc/lua_api.md?plain=1#L6164-L6165

Chats or the forums would be a more suitable place for questions.

**Comment by mrGoodWolf** [comment]
thanks!
