### ISSUE TITLE
Add connected_glass_optional to obsidian glass as well.

### ISSUE THREAD

**Issue by MT-Modder** [minetest/minetest_game#383]
Title says it all. If this is intentional then nvm. I trust the minetest_game devs.

**Comment by C1ffisme** [comment]
We could add some kind of transparency, but we all know the glitches people have with that. What about obsidian glass panes?

**Comment by C1ffisme** [comment]
Wait a minute, why haven't you just made a pull request, @MT-Modder?

**Comment by MT-Modder** [comment]
I might but I'm waiting for @PilzAdam to respond again about the detail of obsidian glass. I'm also waiting for my other pull request to be merged since I'll need to sync my fork with master.

**Comment by MT-Modder** [comment]
Closing, any further discussion should be held here: #442
