### ISSUE TITLE
Glass is always connected despite connected_glass = false in both server side and client side.

### ISSUE THREAD

**Issue by Megaf** [minetest/minetest_game#394]
Hi, Glass is always connected. It always was to me since it's implementation and I can't disable it.

**Comment by ShadowNinja** [comment]
Most likely an engine bug.

**Comment by MT-Modder** [comment]
Opened an issue for the engine.

**Comment by kahrl** [comment]
Citing [my comment over there](https://github.com/minetest/minetest/issues/2160#issuecomment-71118361):
Can't confirm. Most likely this is caused by some mod redefining glass (one offender I know of is moreblocks).

**Comment by MT-Modder** [comment]
This isn't a bug it's caused by a mod. (Specifically moreblocks)

**Comment by Megaf** [comment]
@Calinou Can you fix this?

**Comment by MT-Modder** [comment]
He already fixed it :). Here is the link: https://gitorious.org/calinou/moreblocks/commit/5e0201968e18d6fe614801e88a8ee960a976377a

**Comment by kilbith** [comment]
See : https://github.com/minetest/minetest/issues/2160#issuecomment-89992674
