### ISSUE TITLE
Screwdriver doesn't work

### ISSUE THREAD

**Issue by lightonflux** [minetest/minetest_game#398]
So i updated both MT and minetest_game to the newest git and still the screwdriver does not work. It doesn't turn blocks in any way. But it still degrades on use.

Sadly i can't say when the breakage was introduced.

Tested it in a new empty world without third party mods.

**Comment by PilzAdam** [comment]
I can't reproduce this.

**Comment by lightonflux** [comment]
Compiles the latest version earlier and tested it again (same actions) and it works. Weird.
