### ISSUE TITLE
Cotton needs a new texture (it looks like string)

### ISSUE THREAD

**Issue by davisonio** [minetest/minetest_game#404]
At the moment cotton looks like string rather than [cotton](https://www.google.co.uk/search?tbm=isch&q=cotton). Probably because little while back, `farming_string.png` was renamed to `farming_cotton.png` in https://github.com/minetest/minetest_game/commit/60ccb522.

**Comment by MT-Modder** [comment]
If the texture is changed should the recipe be changed as well? Should we be able to craft cotton into string or should we eliminate string all together?

**Comment by C1ffisme** [comment]
Bump.

I agree with MT-Modder, should string be eliminated, or cotton be made into string? If we do the first option, we save making a pointless item and making mods lose a lot of support if we rename the string. If we do the latter, we make a useless item, but it's more realistic and keeps mod support.
 
Now that I've bumped this, we'll see what other devs think.

**VOTE:**
- Replace string with cotton _OR_
- Add a cotton item, which may craft into several string.

**Comment by MT-Modder** [comment]
I vote we make cotton craft into 2 strings since it keeps mod compatibility and makes crafting wool a little bit easier. (I'm not saying it's hard to craft though)

**Comment by C1ffisme** [comment]
Ok, but what do we use cotton for, a decorative item? Fuel?

**Comment by MT-Modder** [comment]
It would be just like wheat is to flour, or flour is to bread. A middle-man. Most craftitems are.

**Comment by C1ffisme** [comment]
@MT-Modder True, but flour is an ingredient for many cooking mods, and wheat makes straw.

**Comment by MT-Modder** [comment]
Well maybe somewhere down the line they could add a clothing mod, i.e. 3d_armor. The only use for cotton is wool so... Regarding only minetest_game and no other mods the only use for flour is bread so the same would go for string. 

- cotton -> string -> wool
- wheat -> flour -> bread

This setup looks good to me.

**Comment by C1ffisme** [comment]
True, true.

**Comment by Echoes91** [comment]
My enhanced throwing mod relies a lot on strings for bows, same for other mods stuff like ropes. Losing string would require to define a new craftitem for each mod, which are going to be incompatible unless we define a new unique group etc.
What's still quite hard to imagine is how does cotton become wool...

**Comment by paramat** [comment]
Cottonwool!
Our wool is synthetic vegan wool made from cotton.

**Comment by 0-afflatus** [comment]
I don't have a huge opinion on this - I do something very similar on grailtest. I have replaced cotton with plant fibre, but it's essentially the same thing; that can be crafted into string and 'wool', that is fabric. I do a 1 to 1 conversion from plant fibre to string and 9 into wool. (String can also be crafted in to rope). Adopting this sort of approach in MTG using cotton would be a Good Thing.

**Comment by paramat** [comment]
There is already a string-cotton alias in farming mod so maybe the 2 were seperate in the past.

**Comment by 0-afflatus** [comment]
Is that because the full grown cotton in farming mod used to drop farming:string instead of farming:cotton?

**Comment by Ferk** [comment]
Can't wool be renamed to fabric or cloth?
I don't think Minetest needs to mimic every single Minecraft block, specially when doing that requires confusing recipes

**Comment by C1ffisme** [comment]
I agree with @Ferk. Cottonwool is a bit silly, and the transformation from cotton into wool is unrealistic, even for Minetest Game.

**Comment by paramat** [comment]
I feel that cotton plants should drop cotton which looks like cotton, then this is crafted into either strings or wool. But how to cope with breakage and aliases?

**Comment by rubenwardy** [comment]
> I feel that cotton plants should drop cotton which looks like cotton, then this is crafted into either string or wool

Agreed

> But how to cope with breakage and aliases?

You'd only be adding farming:string then changing craft recipes. The only breakage would be balance related - players would lose value if they have cotton in one of their inventories as cotton loses value. I think this is fine - note it was done for TNT as well previously

**Comment by Napiophelios** [comment]
I think cotton should basically remain the same as it is now (except a new texture);
string would just be a smaller derivative of cotton
used for lesser recipes

That way cotton wouldn't lose any value.

1wool= 4 cotton
1cotton= 9strings

**Comment by davisonio** [comment]
> I think cotton should basically remain the same as it is now (except a new texture);
> string would just be a smaller derivative of cotton
> used for lesser recipes
> 
> That way cotton wouldn't lose any value.
> 
> 1wool= 4 cotton
> 1cotton= 9strings
> 
> edit: what you guys think of something like this for cotton

Great!

**Comment by sofar** [comment]
The cotton texture looks fantastic. It would be nice though to get some direct use out of cotton as well, somehow. If it's purely ever only used to make wool, that would not be preferable.

**Comment by paramat** [comment]
Texture is good. I certainly support sorting out this cotton/string crafting mess.

**Comment by Napiophelios** [comment]
By itself, it looks like a flower,
but it looks kinda nice in the game.

![farming_cotton_large](https://cloud.githubusercontent.com/assets/8119411/21754007/bb3ba670-d5c5-11e6-8e39-e50644a34ebf.png)
![farming_cotton](https://cloud.githubusercontent.com/assets/8119411/21754009/c0958276-d5c5-11e6-9863-0fcf80fdd7d8.png)

**Comment by sofar** [comment]
not as good. I don't recognize the cotton ball that I envisioned.

**Comment by Napiophelios** [comment]
yeah its hard to get 4 of them in there like Ruben wants and not look like a blob :( 
I prefer the first one myself.

**Comment by GreenXenith** [comment]
Wouldn't adding real cotton and changing the current one to string break tons of mods?

**Comment by rubenwardy** [comment]
Ok, I like the first one

**Comment by paramat** [comment]
I prefer the first one, maybe it could have a 'dip' at the top of the blob to suggest the 4 balls of cotton?

**Comment by tobyplowy** [comment]
@davisonio +1

**Comment by tobyplowy** [comment]
@Napiophelios +1

**Comment by paramat** [comment]
I think we should sort this mess out, even if it means a little breakage.

> I like the idea of crafting cotton into string or cotton into wool.
Like 3 cotton in a horizontal line = string.
4 or 9 in a square = wool.

**Comment by TumeniNodes** [comment]
This PR started around 2 years ago, and has sat for 5 months since the last communication, with a good replacement texture.
The current farming_cotton.png could be used as farming_string.png?
What would need to be done to either get this done or close it? Just asking

**Comment by paramat** [comment]
Needs some consideration about how to minimise breakage, but i would also like to sort this out, and separate cotton from string. Now would be a good time if there is any breakage, at least these are items not nodes so not a big problem.

**Comment by TumeniNodes** [comment]
sounds good

**Comment by paramat** [comment]
@Napiophelios is CC BY-SA 3.0 ok for your texture? I'm using the first one in a PR.

**Comment by paramat** [comment]
PR #1876

**Comment by Napiophelios** [comment]
Yep. CC BY-SA 3.0 , that's what I usually use for textures.

**Comment by paramat** [comment]
#1876 merged.
