### ISSUE TITLE
Writable Books...

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest_game#406]
ignore this, better code below...

**Comment by 0-afflatus** [comment]
It would be wonderful.
Can you store metadata on a craft item? I thought it was specific to placed nodes.

**Comment by MT-Modder** [comment]
@0-afflatus You can, ItemStack has metadata.

:+1: I would love this feature. Can you update it so it uses the default background or is it setup like signs?

**Comment by 0-afflatus** [comment]
In that case :+1:

**Comment by ShadowNinja** [comment]
The concept is good, but this particular implementation is unacceptable:

  1. The `££` split is a huge hack.  Either make the first line the "header" (see 3) or serialize the data from a table (better).
  2. You're missing the `max_split` argument to `string.split`, which will break books with `££`s in them.
  3. `header` is very misleading.  It's really `player_name`.  I think there should be an actual title though.
  4. You should use the book's `on_receive_fields` instead of a global callback.
  5. `text` is also very misleading.  It's a `stack_table`!

**Comment by tenplus1** [comment]
I tried using on_receive_fields in the actual craftitem but it wouldnt work properly at all...  Simple solution to  a much needed feature but I will re-think code to make it better...

**Comment by MT-Modder** [comment]
Cool thanks. I'm pretty sure that ```default.gui_slots``` doesn't need to be there because it's only used for inventory slots. I could be wrong though.

**Comment by ShadowNinja** [comment]
Here's a better implementation: https://gist.github.com/ShadowNinja/e06b3fbe165bbac4ae84

**Comment by kilbith** [comment]
@ShadowNinja : pull-request please :+1: 

![screenshot_242658820](https://cloud.githubusercontent.com/assets/7883281/5845835/93a6100a-a1bf-11e4-8aeb-dc49709263b2.png)

**Comment by MT-Modder** [comment]
Does the metadata persist after placing/removing a book into/from the bookshelf?

**Comment by kilbith** [comment]
@MT-Modder : yes, checked.

**Comment by MT-Modder** [comment]
Sweet, thanks for checking.

**Comment by tenplus1** [comment]
@ShadowNinja : looks great to me :)  my only addition was a close button when reading and showing the author to stop server abuse...

```

--= Book (use to read or write to)

minetest.register_craftitem(":default:book", {
	description = "Book",
	inventory_image = "default_book.png",
	groups = {book=1},
	stack_max = 1,
	on_use = function(itemstack, user, pointed_thing)
		local player_name = user:get_player_name()
		local data = minetest.deserialize(itemstack:get_metadata())
		local title, text, owner = "", "", player_name
		if data then
			title, text, owner = data.title, data.text, data.owner
		end
		local formspec
		if owner == player_name then
			formspec = "size[8,8]"..default.gui_bg.. -- default.gui_bg_img..
				"field[0.5,1;7.5,0;title;Title:;"..
					minetest.formspec_escape(title).."]"..
				"textarea[0.5,1.5;7.5,7;text;Contents:;"..
					minetest.formspec_escape(text).."]"..
				"button_exit[2.5,7.5;3,1;save;Save]"
		else
			formspec = "size[8,8]"..default.gui_bg.. -- default.gui_bg_img..
				"button_exit[7,0.25;1,0.5;close;x]"..
				"label[0.5,0;"..minetest.formspec_escape(title).."]"..
				"label[0.5,0.5;by "..owner.."]"..
				"label[0.25,1.25;"..minetest.formspec_escape(text).."]"
		end
		minetest.show_formspec(user:get_player_name(), "default:book", formspec)
	end,
})

minetest.register_on_player_receive_fields(function(player, form_name, fields)
	if form_name ~= "default:book" or not fields.save then
		return
	end
	local stack = player:get_wielded_item()
	if minetest.get_item_group(stack:get_name(), "book") == 0 then
		return
	end
	local data = minetest.deserialize(stack:get_metadata())
	if not data then data = {} end
	data.title, data.text, data.owner =
		fields.title, fields.text, player:get_player_name()
	stack:set_metadata(minetest.serialize(data))
	player:set_wielded_item(stack)
end)

**Comment by C1ffisme** [comment]
Since you have the code, why not make this into a pull request? Feature requests are more for people who do *not* have the code available. You have the code, so why not take the latest version of minetest, add this into default or another default mod, and make a pull request?

**Comment by 0-afflatus** [comment]
It's good to get the discussion going early on a fairly large feature like this. But yeah, please turn this into a PR.

**Comment by C1ffisme** [comment]
We can close this now, right? Please?

@kilbith I'm trying to read that latin, but I'm not that good at it...
