### ISSUE TITLE
Seemingly infinite firespread / client lockup

### ISSUE THREAD

**Issue by ikeydoherty** [minetest/minetest_game#408]
Originally reported @ minetest repo, but was informed this was the correct place to do so :)

Picture says a thousand words and I decided to test a couple dozen TNT set off with a lava source block. As ya do. Anyway the fire doesn't stop spreading and the inventory UI becomes almost unresponsive :)

![screenshot from 2015-01-21 21 00 23](https://cloud.githubusercontent.com/assets/164489/5845735/75533a5a-a1b6-11e4-9ca6-932de69bbf36.png)

(Original report: https://github.com/minetest/minetest/issues/2178)

**Comment by MT-Modder** [comment]
I agree fire spreads way too fast and doesn't go out / burn things fast enough. This has been an issue for a while.

I know some games have taken the initiative and slowed it down to solve this. The "fire" mod should check to see if the center of an area on fire has gone out before spreading any further.

I think shadowninja would be best at solving this because of his experience with handling areas i.e. the "areas" mod.

**Comment by tenplus1** [comment]
I removed the fire sounds from the mod itself and placed it in the hands of Ambiance mod, this sped things up a lot and reduced lag...

**Comment by MT-Modder** [comment]
Even with reduced lag I don't think fire should spread as fast as it does. It should either go out faster or spread more slowly.

**Comment by 0-afflatus** [comment]
Forest fires cause most players to drop out due to lag. If the fire was to burn faster and have a lower change of igniting neighbouring nodes, it would help. 

Fire beyond the active block range doesn't burn out either, so you get a wall of flame that doesn't do anything until some player is within range. The same principle should apply here as with the furnace.

**Comment by Gael-de-Sailly** [comment]
The fire spreading is too fast IMO.

**Comment by BlockMen** [comment]
True, it spreads much too fast as is.

**Comment by paramat** [comment]
I agree It is too fast and spreads too easily, a thick forest like a jungle becomes a disaster for the server.

**Comment by MT-Modder** [comment]
I changed the flame removal abm interval to 3 and the two spreading abm intervals to 5 and this seemed to slow it down to my liking. Maybe I'll submit a PR for this.

**Comment by Calinou** [comment]
Fire spreading should definitely be nerfed (it already is in Carbone).

**Comment by C1ffisme** [comment]
The pull request has been pulled. Please close.

**Comment by MT-Modder** [comment]
This still happens and the only thing that pull did was slow it down a bit. I personally am still not happy with it's speed, but if @BlockMen , @PilzAdam , and @sfan5 are happy with the pull's results then yeah this should be closed.

**Comment by paramat** [comment]
Still an issue so let's keep it open for discussion. I want to look into why a large area of fire should have such an effect, we may need to tune the ABMs again.

**Comment by Ferk** [comment]
It could be that this it's not just a problem of too many ABMs, but the sound effects going overboard, judging by the experience from @tenplus1 when moving the sound effect to Ambiance.

**Comment by paramat** [comment]
I tested fire in a dense pine forest and even with the recently increased intervals the fire spread was totally insane.
So #640 was squeezed in last minute for release. The ABM intervals are similar but the chances of processing each node 8-16 times lower, looks like an excessive change but was tuned for a natural realistic behaviour, a slow initial spread that picks up speed after a few minutes. The large change in ABM chances will greatly reduce the load and lag on the lua server.
Fire mod still needs careful tuning and some changes, i will be working on improving it.

**Comment by ikeydoherty** [comment]
@paramat I'll do another test today now that #640 is in. Anything else I should do to strenuously test this? I've upgraded hardware since.. ^^

**Comment by paramat** [comment]
I guess the densest forest would be a mgv6 jungle.

**Comment by paramat** [comment]
I merged a rewrite of fire mod #651 that should reduce load.

**Comment by paramat** [comment]
Issue should be fixed now, re-open if it isn't.
