### ISSUE TITLE
Carts

### ISSUE THREAD

**Issue by C1ffisme** [minetest/minetest_game#409]
No, this is not a bug, this is a feature request, see the label (Can you put the "feature request" label on, admins?)?

I'm not suggesting a huge, laggy, feature filled addition, with 20 different functions and such, but since we already have boats (a fast way to go over water), why not make carts (a fast way to go over land)?

Pros:
- Might stop annoying sprint requests.
- Creates something else to do in the game.
- Adds a use for rails
- Fast travel over land

Cons:
- Cons depend on how someone implements this.

I tried to make my own carts based off of the boats mod, but it was very glitchy, sometimes you would fall through the earth. So I'm going to leave the coding to more experienced hands (If someone decides to do this).

**Comment by MT-Modder** [comment]
There is a long standing debate on this issue. I agree carts should be added to minetest_game at some point. The only problem with this is how glitchy entities are sometimes. Even boats are pretty glitchy. IDK when but these problems would be eliminated with client side support.

**Comment by C1ffisme** [comment]
I came up with a few (two) rules for the cart that may stop some glitches:
- The cart should not make sound (like the sound in pilzadam's mod)
- The cart should not run without a player inside it.

Although, an engine change would be really nice. I toyed around with it a bit, and it was a huge experimental job trying to get torches to appear in dungeons. Maybe some of the functions should be simplified.

**Comment by PilzAdam** [comment]
My carts mod is pretty lightweight, so that might be what you are looking for.

**Comment by C1ffisme** [comment]
@PilzAdam I know about yours, but it's kind of old, and then there are people who are paranoid about the forums. Also, it would be nice to see it in default, because while a modded minetest is fun, I want to see vanilla minetest have more added to it. (I also wanna see a new rectangular cart model)

OFFTOPIC (Well, sortof ontopic, because I was talking about models.) : By the way, PilzAdam, could you make a video to help new minetesters with modeling? I've tried to texture my models for my own personal animals mod (based off of yours), but I'm not sure how to properly assign textures to meshes. Sorry for the (akward) offtopic, but I wanted to take a chance to ask.

**Comment by PilzAdam** [comment]
@C1ffisme What I meant was that my cart mod could be added to minetest_game, so it is in "vanilla".
And what do you mean by "people who are paranoid about the forums"?

**Comment by C1ffisme** [comment]
@ PilzAdam Well, in that case, we should add it to minetest_game (But after a few tweaks maybe? I wanna see a model change, just because I'm against square minecarts.)

I don't exactly mean *paranoid*, I'm thinking more of people who dislike the language, who can't sign up because they might get in trouble with their parents/guardians, or have other problems with the forums.

Actually, I don't join the forums because of the repetitive **cursing**. Which is wierd, because a wiki page on the minetest wiki says to "watch your language" and "be appropriate, you may never know the age of the people on the channel".
 [Here is the page](http://dev.minetest.net/How_to_communicate)

**Comment by C1ffisme** [comment]
@PilzAdam Do you think I should make a pull request?

**Comment by C1ffisme** [comment]
Bump.

Hey, I thought about it for a while, and I thought about adding a block based minecart. It would move every second and use ABMs. But there are problems with this:

1. It might destroy rails
2. It might be hard to steer (unless with some kind of lever...)
3. It would be pretty darn **terrible** because it would move block-by-block and there isn't much feel of a ride.

So, I think we are going for entities.

I would make a pull request, but my current one is using the master branch of my minetest_game fork. So I cannot create a new pull until that pull gets merged or trashed. It's at #416 .

**Comment by LeMagnesium** [comment]
@C1ffisme , create a branch in your fork's clone, do your work, and commit on this branch. Give it a name that is easy to recognize for it contents, and push on your fork to a new branch. Then create a pull-request using this new branch, and you can leave master even with original minetest_game.
Also, block-based carts would indeed be horrible, because it would need a minetest.set_node() or two every 0.1 seconds to create the illusion of ride, which would overload the server. Entity carts are still the best one, even if they are buggy.

**Comment by C1ffisme** [comment]
Yes. Block carts would be terrible, as I said.

And I will try to do things to my pull...

**Comment by tenplus1** [comment]
Some initial changes to PilzAdam's carts to despawn cart when player or item not inside...
https://github.com/tenplus1/carts

**Comment by paramat** [comment]
I would like to see carts added, i worked on the boats mod to make them less glitchy, they behave reasonably as long as a lua mapgen isn't running, i assume carts are no worse.

**Comment by nerzhul** [comment]
:+1: @paramat

**Comment by paramat** [comment]
Discussion on this can continue in #515 as there is a suggestion for carts there.

**Comment by C1ffisme** [comment]
Probably a good idea.
