### ISSUE TITLE
Unvisible trapdoor

### ISSUE THREAD

**Issue by Xanthin** [minetest/minetest_game#411]
Just a small thing (matter of taste). The trap door, when selected in the hotbar, is not visible while standing. When you walk with the character it shows up but not really much.
I added: wield_image = "doors_trapdoor.png", to the trapdoor registration and now it's visible like other items (doors, rails,...).

Some pictures:
<a href="http://imgur.com/4LY4auK"><img src="http://i.imgur.com/4LY4auK.png" title="source: imgur.com" /></a>
while standing

<a href="http://imgur.com/f2CUlsn"><img src="http://i.imgur.com/f2CUlsn.png" title="source: imgur.com" /></a>
while walking

<a href="http://imgur.com/ekkNaHE"><img src="http://i.imgur.com/ekkNaHE.png" title="source: imgur.com" /></a>
with my change

What do you think?

**Comment by kilbith** [comment]
That it's obviously better and you should submit a PR.

**Comment by kilbith** [comment]
... still waiting for a PR.

**Comment by Heybye44** [comment]
:+1:

**Comment by Xanthin** [comment]
Sorry, I am a totaly newbie with github and only use it in its browser version. I was concerned about messing up the history and causing more work for the admins then this tiny modification deserves.
PR is done. Thank you very much for the feedback :)

**Comment by BlockMen** [comment]
047ecea3a28f1d516bd6a54b690affccbedfb022
