### ISSUE TITLE
Problems with infinite stone generators

### ISSUE THREAD

**Issue by C1ffisme** [minetest/minetest_game#425]
So I was building an automatic bridge builder with mesecons, that used an infinite stone generator to make stone to build a bridge.

BUT...

I got one block of stone above my node detector, the stone was pushed by piston, and then it was like the lava didn't want to flow into the space above the node detector. I thought this was a problem with mesecons, then I tried a normal stone generator. I dug the stone, and the water didn't want to flow into the lava this time.

So, this makes stone generators unusable. I think this is a bug. Because the lava/water did want to flow in a direction not towards the water/lava.

**Comment by thatgraemeguy** [comment]
This is very interesting, it sounds the same as the behavior seen on VanessaE's servers (based on dreambuilder_game) for months now.

Try building so that the lava source is directly above the water, with 1 empty space separating them.

**Comment by thatgraemeguy** [comment]
Like this:

![Screenshot showing placement of lava above water to work around bug where lava will not flow horizontally towards water](http://i.imgur.com/eYvRWSM.png)

**Comment by C1ffisme** [comment]
I don't really want to get a workaround. If we fix bugs, it stops future problems. I mean those 1 block tall stone generators.

**Comment by PilzAdam** [comment]
This might be because of laggy liquid flowing? (this would be an engine issue then)

**Comment by MT-Modder** [comment]
I don't have this problem. What version of minetest are you using? I'm thinking this is an old bug because I was having problems with liquids with the 0.4.11 release and they have been fixed recently.

**Comment by C1ffisme** [comment]
I do remember downloading the latest git. I'll see if they've fixed it since then.

**Comment by MT-Modder** [comment]
That might be the issue. I remember zeno and others working hard to fix bugs with flowing liquids. If you don't want to compile yourself you can get builds from here: https://forum.minetest.net/viewforum.php?f=42&sid=b08539ed6d77ebd1d9927a129d42ef6f (If you didn't know). There was a lot of bugs in 0.4.11.

**Comment by C1ffisme** [comment]
I can compile, or try to.

**Comment by tenplus1** [comment]
It sounds like the machine you use to harvest the stone blocks doesnt update the blocks around it when it's done, hence no lava falling...

**Comment by C1ffisme** [comment]
Actually, if I dig a block behind the lava after a pistone pushes the stone, lava flows into the block behind, but still not into the block where the stone was. And, I have tried to update the lava by putting a block where-the-stone-block-was and digging it. Still no flow.

**Comment by C1ffisme** [comment]
Bump.

**Comment by BlockMen** [comment]
Seems to be an engine issue, the lava is not flowing correct

![screenshot_40070664](https://cloud.githubusercontent.com/assets/3742497/6420575/9b832bbc-bec7-11e4-80ee-51669182ec00.png)

**Comment by C1ffisme** [comment]
It probably is. Should someone post an engine bug?

Also, why can't the owners of issues/pull requests put their own tags on their own stuff? Even if they aren't moderators?

**Comment by C1ffisme** [comment]
I'm going to close this. If a developer thinks this is a subgame bug, then please re-open. The real bug is [here](https://github.com/minetest/minetest/issues/2399) .
