### ISSUE TITLE
Make minetest_game show off functions, and build another, funner subgame?

### ISSUE THREAD

**Issue by C1ffisme** [minetest/minetest_game#426]
ORIGIONAL POST:
I know, I know. You're going to tell me to goto the forum, download a bunch of mods and try playing somemore. But really, there isn't enough features to encourage people to play minetest. Maybe for 0.5.0 at least, we should pull in some of these pull requests, and add some features that may make the game worth playing.

Consider things like:
- [ ] Bows
- [x] Beds (Got that)
- [ ] A Goal of some type. Something like achievments?
- [ ] More food. Vegetables?
- [ ] Mobs, but before you people with old computers complain, I want mobs implemented in C++, which can preform faster than most of the lua ones. And make stuff like NPCs.
- [x] More biomes and per-biome resources. This adds some exploration. (Snow biomes will do.)
- [ ] Machinery? Not mesecons, but maybe ABM conveyor belts and auto-crafters. You could use it to make your own factories, that actually work by themselves.

These are just some of my ideas. Add your's too! I wanna see new stuff before 0.5.0.
And I wanna not have to see the development of 0.4.42. Please. Limit the 0.4.x's to 15. We cannot delay 0.5.0 any longer, many people are waiting.

NEW POST:
Okay, so I've agreed that minetest is an engine, not a game. But if people are going to choose us over minecraft, lets add some entertainment to minetest. I suggest we make a new subgame, and make minetest show and example as many functions as possible, in different ways.

**Comment by C1ffisme** [comment]
Bump.

**Comment by thatgraemeguy** [comment]
> I know, I know. You're going to tell me to goto the forum, download a bunch of mods and try playing somemore.

Yeah, seems like you already have the answer. Everything you mentioned is catered for by existing mods.

**Comment by C1ffisme** [comment]
Yes, but it seems like more features could be used to make people look at this game and think "OH MY GOSH I NEED THIS!!!". Because right now, minetest has no real pros over minecraft other than being free and open-source. If we had some really cool feature to make people excited to play the game, the community might grow a little faster.

**Comment by C1ffisme** [comment]
Consider, say, voxelands. It has a lot more features than minetest at the moment, so what is stopping the community from all becoming voxelands developers? Mostly because of the moddability, but if voxelands made some kind of C++ modding, I'm sure half the community would go over and start coding, since a lot of developers know C++ as well as lua.

**Comment by RHRhino** [comment]
voxelands and minetest are completely different:
* voxelands is a **game**  written in C++. It has the advantage that there is just one content for all players and no mods, so it is less complex to develop and has more content by default, but you can not costomize it. Voxelands does not want people to mod it!
* minetest is an **engine** written in C++ that allows people to write and costomize their own game by writing lua mods. It has the advantage that there is much more content and everyone can create and play whatever he wants, but is also much more complex to develop.

**Comment by C1ffisme** [comment]
Alright, alright. Lets make sure we don't get onto a debate about voxelands and minetest. But, I think I have a solution:

1. Pull some of these pull requests in.
2. Make some way to show an example for as many functions and such in the minetest game.
3. Make minetest_game be more of a "mod me" game.
4. Make another game called something like "minetest_play" or something.
5. Minetest_play can have some of the examples for functions and code removed that is redundant in a fun game.
6. Add fun to minetest_play.
7. Add minetest_play to the default minetest game.

Why should another subgame be made? Because I think the minetest _team_ can make a more balanced and less lagiful game then one person, and if a subgame is made by the developers, we can make new functions in the engine without having to make laggy lua ones.

**Comment by 0-afflatus** [comment]
@C1ffisme that's the solution. Write a game that fulfils your requirements.

**Comment by C1ffisme** [comment]
Allright, but even so, I think we should follow those steps. Lets make minetest show more functions, to help make more games/mods. Even then, I think a few things to play with in minetest would be nice.

**Comment by 0-afflatus** [comment]
You make some valid points.
I think the big thing is player advancement / goals. Put very simplistically - everyone wants to fly around in diamond armour with the biggest magic wand / most advanced tech. Players need enough fun and reasonably logical  challenges to get through in order to get a sense of achievement and progression.
More food is pointless without more hunger and that must be optional.
I would not want mobs entirely coded in C++ - it may be beneficial to have some generic, processor-heavy functions in hard code, but it needs to be done in a way that makes mobs easier to mod - which has to be in soft code i.e. Lua.
I actually think the best thing for minetest's development is for minetest_game to remain imperfect.

**Comment by nerzhul** [comment]
I agree with the point that the engine must be improved for modders ans basic game must be enhanced, especially forme survival (there isn't real survival at this time)

**Comment by 0-afflatus** [comment]
I think the way forward is to write sub-games and push for the necessary changes to the engine.

**Comment by C1ffisme** [comment]
@0-afflatus Probably, although I still think merging in a new subgame would be good. After all, not all of the community is modders. There might be some gamers who played minetest and forgot about it when they bought minecraft, because minetest just wasn't fun enough.

**Comment by Wuzzy2** [comment]
As I already said: As long we do not agree on what direction minetest_game should go to, minetest_game is not going anywhere.
It is still not clear to me what minetest_game is supposed to be.

A game?
A sandbox?
A base for modding?
A subgame to show off the features of Minetest the engine?
Something completely different?
And what role should multiplayer have in minetest_game?

So without any project goals, minetest_game is just a plain random subgame.

Another problem with minetest_game is that almost every change triggers endless discussions, so its development is hindered.

**Comment by nerzhul** [comment]
At this time it's not very clear, but project is moving, it's a free project, with many contributors and he can evolve. Voxel crafting worls are sandboxes, but minetest_game is a game, as its name said, and mods are very good, but the base game must be attractive for new players, and improve minetest_game can be good. Some mods can be part of minetest_game core :)

**Comment by C1ffisme** [comment]
I think minetest should be a game and a sandbox, like minecraft. Let's add goals on the game side, and cool blocks and things on the sandbox side. That dosen't mean we discontinue modding, on the modding side we need to improve the minetest engine so that we can actually use minetest on bad computers. Currently we have gone away from preformance and old computer support.

**Comment by paramat** [comment]
MTgame itself is, and should be, open ended with no goals, any goal added means goals will be acheived, and then what? a completed goal then gives the impression of Minetest being completed or finished and might encourage players to stop playing. The addition of 'the end' to Minecraft was a big mistake, uncharacteristically mainstream, as if they felt forced to add it to make it more commercial. Goals are things for other subgames, and the intention already is for Minetest to be bundled with a variety of other subgames.

Mgv6 will soon have optional snow biomes, taiga and tundra, with the new pine tree and pine wood. The biome system i am working on for mgv5 and mgv7 will have at least 6 biomes.
Basic C++ mobs would be okay but only simple friendly mobs. MTgame should not force survival or combat on players, many players do not want those aspects, those are for other subgames.

As i wrote in the other thread, the team already have an objective for MTgame, it is a simple and minimal basis for adding modules to, and should not force anything complex or specialised on players, so inherently will be slightly boring or lacking, and this is not a problem. Celeron55 has often requested new subgames to be bundled with Minetest, so get creating =) and everything you feel is missing from MTgame goes into those.

**Comment by 0-afflatus** [comment]
:+1: @paramat

**Comment by C1ffisme** [comment]
@paramat True, true.

Although I still haven't succesfully beaten the ender dragon in total survival. It's hard. Long and hard goals inspire the mind. You want to build towards the goal. Make things easier by building machines, vehicles, etc. Every goal has progression. Not only this, but video games are great, because you can just restart/create a new world and build up (sometimes litterally) towards your goal again.

However, my motto is that everything should have an option. If people want a base for modding, we should choose minetest_game. But if you want to play a game, which may still be affected by those mods, we should build a minetest_play, or minetest_fun. We need to make this game have some fun to it.

**Comment by paramat** [comment]
That's cool, sorry if my first paragraph seemed harshly worded, it wasn't meant to be, i wasn't communicating very well when i wrote it =)

**Comment by C1ffisme** [comment]
It's okay, some of us human beings like to throw out communication, a lot. It wasn't offensive or anything. :wink:

**Comment by yo-we** [comment]
@C1ffisme Being on the "user side" (player and moderator), I do understand your concerns, mainly when I am a player. Then, when I am debugging server crashes, I have to say: Keep it simple and *stable*. Everything else has far less priority.
  Four of the seven points you propose in the beginning are (or have recently been) heavy weights in making the server stall. No running server, no game at all. Thus, I am happy they are not integrated in the game by default.
  Furthermore, I wonder if providing coherent modpacks for different gameplay types would not resolve your request. Doing so, there would not be any conflict with the existing strategy (base for modding) and your targets (adding xy to gameplay). And it would permit to adapt rapidly and take mutual benefit from mod development.
  Finally, I fear that spawning branches of development might disperse working power without too much synergy.

**Comment by C1ffisme** [comment]
@yo-we Branches? Probably not. Branch? Maybe.

I just think that we should do this, either:
- Make minetest_game an actual **game**.
- Make minetest_game a base for modding and an example, then make a game like say, minetest_play which would be the game minetest_game would be if we did the first option.

This issue is to discuss the second option.

Then we would have 3 games:
1. Minimal for testing engine changes
2. Minetest Game for testing mods
3. Minetest Play/Fun for playing and having fun (Mods would still work here, but Minetest Play should not need them for players to have fun.)

Note that Minetest Play might go to the point where lag can happen, where minetest game stays simple so that mods can function properly. (Although, maybe add a /lag command to simulate lag on Minetest Play, in case you need to make sure mods work properly with lag.)

See, minetest should be a base for modding. But like minecraft, it should not NEED mods to have fun.

My target is not to add xy to gameplay, but to make minetest worth the compiling or downloading or getting-a-PC-ing.

**Comment by Calinou** [comment]
`minetest_game`, without mods, is already a playble game. It can be fun. Maybe try playing other games, if it's not fun for you.

**Comment by thatgraemeguy** [comment]
Yeah, if you want to build a game, go ahead. Dozens have done so already so
if you feel you can make a better game then feel free.

**Comment by Heybye44** [comment]
:+1: @C1ffisme 

We could put a poll about this on Tue Minetest mainpage and have everyone vote on the direction of Minetest and minetest_game




—

**Comment by FreeLikeGNU** [comment]
What if someone who just learned that there is a free (no matter their idea of such an ambiguous word) alternative to well known game decided to take a leap and download minetest?  What would you want your little brother or sister or dad to see when they start up the game so that they might be excited?
What can we show people for them to see how fun it is to explore and create?  How do we connect them to a wide world of game creators and modders right from the beginning?

I think minetest comes close for folks who can invest time in creating or are passionate about sharing or maybe just sticking it to MS.  That is the core of the community we have now, people who are not just looking for a casual game or the game they heard about on TV.  

I look at a game like LittleBigPlanet.  They made a lego-style game where people could just play a s a platformer, or make stuff or just download interesting things from other players easily.  Its very easy to look for creations, see reviews, download, play and then take little pieces from it and make something new.

I think minetest really needs an interface to connect to other players creations and a way for creators to easily share those things within the game.  Git comes close, but its not within the game environment, main menu at least.

**Comment by C1ffisme** [comment]
Good words @FreeLikeGNU .

Speaking of "What you would want your little brother/sister/dad to see" we should probably make it that way on the appropriate side (at least make the minetest screen clean and make all the you-know-what-license mods say that they are "Completely free").

**Comment by FreeLikeGNU** [comment]
@C1ffisme Thanks for the kind compliment!  However, "Completely free" is quite ambiguous and not a known license, IMHO. It is up to the creators of games and mods to chose their licenses. I'm not really concerned about about appropriateness (some might find a male only player option insensitive or offensive), as I think it is up to the parent to keep track of what their kids do. (source: I'm a parent of three younglings).   What I'm concerned with is making the game as accessible as possible to the CREATIVE process and SHARING.

**Comment by C1ffisme** [comment]
Yeah, it's not needed right now. We can clean minetest later and in another pull request.

On the point, what about adding chemistry? We could add alloys or different explosives...

**Comment by thatgraemeguy** [comment]
@C1ffisme: I'm not sure how many times you'd like to get the same answer, but afaik it still hasn't changed: "That stuff is left up to modders".

Write the code, submit the PR and if its rejected then package and release it as a mod.

**Comment by C1ffisme** [comment]
Oh come on @thatgraemeguy , there are many complaints I have about mods.

- Imbalance
- Contrast to Minetest
- Compatability Problems
- Downloading from sites like MediaFire, which pelt you with ads until you cry.

Look at Minecraft or most other games for that matter. They don't need mods or texture packs to make them fun. You can just download/buy a game and play it. You don't have to feel like you are in a rush to find fun. I barely play minetest now because my fun is "left up to modders". :( 

Come on. It doesn't have to be a huge array of atoms and mixtures. Just add very basic chemistry or science to fit the mine *test* theme. It's been discussed that minetest is more about science than magic, and I personally want to see something like that, just for something to do. Can't you see yourself building some kind of invention in minetest, and using it to explore or travel around your world. Or is that just "left up too modders". Is fun "left up to modders"?

**Comment by FreeLikeGNU** [comment]
when my kids first tried minecraft, the first thing the wanted to do was install the mods they saw on youtube channels.  From their it was a hellish realm of mod vs. minecraft version compatibility issues.  I then boycotted minecraft in favor of minetest.  They still wanted mods on top, but at least minetest mods are for more sane and tweakable to taste.
Currently they are happy with carbone-ng, mobs redo and valleys mapgen.  I think carbone-ng (currently using mg7) on its own is a really great subgame that provides alot of what is missing for a new person to minetest.

**Comment by C1ffisme** [comment]
I'm not saying remove mods altogether, but minetest shouldn't need them just to be fun.

I'll have to check out carbone-ng. What about adding it to the default minetest pack just so you can entertain yourself?

**Comment by FreeLikeGNU** [comment]
carbone-ng subgame is worth a look and showcases some of the new features in 0.4.13 (better mg7 support) as well as some of the mods (throwing, unified inventory, sprinting, simple mobs, 3d armor, maptools, etc) from the community that make minetest a better experience.

**Comment by PilzAdam** [comment]
This issue is useless. Either do this stuff yourself and submit a pull request (as @thatgraemeguy suggested) or go to the forums and get people to do it for you.

This issue can be closed.

**Comment by C1ffisme** [comment]
What @PilzAdam ?!

This is not an issue. It is a discussion and/or argument. I want people to discuss these things. Or is communication an irrelevant thing? If I submit a pull request, then people will complain that it is "too feature-full" or something along those lines. Look at minetest's development direction, we haven't added any new features or anything exciting since 0.4.12 came out. I don't play minetest at all because I can't make myself have fun. I shouldn't have to make myself have fun. Fun should not take effort.

You can't close a disscussion you don't own, @PilzAdam . This is still a very live disscussion. We need to know what to do with minetest_game, or how to replace it.

**Comment by PilzAdam** [comment]
@C1ffisme this is an issue / bug tracker. If you want discussion then go to the forums.

**Comment by thatgraemeguy** [comment]
Write the code and submit pull requests. All you are doing now is going "Hey guys this would be cool. C'mon now, someone do the code part, because I couldn't be bothered".

**Comment by C1ffisme** [comment]
Okay, okay.

Sorry I've been away for a bit, but I was getting a new laptop.

And with it, I think I'm going to try doing modding of my own. I'll try to not use other people's mods and see what I'll make. Hopefully I can come up with some interesting pull requests soon.

If you guys want to help at all, just post a few suggestions here.

**Comment by paramat** [comment]
Good to hear, lua modding is easy you'll be fine and you can make your ideas happen.

> this is an issue / bug tracker. If you want discussion then go to the forums.

^ That, so now this is a good time to close this.
