### ISSUE TITLE
snow and mese aliases registered twice

### ISSUE THREAD

**Issue by MT-Modder** [minetest/minetest_game#438]
These aliases are defined in nodes.lua and aliases.lua

Links:
- Snow:

https://github.com/minetest/minetest_game/blob/master/mods/default/aliases.lua#L69
https://github.com/minetest/minetest_game/blob/master/mods/default/nodes.lua#L354

- Mese:

https://github.com/minetest/minetest_game/blob/master/mods/default/aliases.lua#L72
https://github.com/minetest/minetest_game/blob/master/mods/default/nodes.lua#L690

**Comment by C1ffisme** [comment]
Can this be closed? We have a pull request.

**Comment by MT-Modder** [comment]
Yeah, I'm closing. Thanks @C1ffisme.

**Comment by C1ffisme** [comment]
Your welcome, @MT-Modder .
