### ISSUE TITLE
Using screwdriver on doors or beds seperates them

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#451]
If you use a screwdriver on a door node or the “back” portion of a bed, only one part of the object actually rotates, resulting in weird floating half-doors and mis-aligned half-beds.

Maybe the screwdriver mod should allow nodes to defend themselves against rotation or to somehow react on an attempted rotation with an optional callback function in the node definition, by extending the subgame API.
The beds and doors should then implement these functions to handle these rotations.

Screenshot: https://i.imgur.com/L70diSa.png

**Comment by PilzAdam** [comment]
Yes, the optional callback function seems to be the best idea.

**Comment by ShadowNinja** [comment]
Alternatively, these items could use only one node with an oversized nodebox.

**Comment by MT-Modder** [comment]
:+1: for @ShadowNinja's idea. This would also reduce the code. Maybe beds could be the first mesh nodes to enter into minetest_game?

**Comment by kilbith** [comment]
@ShadowNinja An oversized nodebox is bad...
1. Can go through another node when placing (need a checking algo).
2. Not suit with higher resolution textures (mismatching).

**Comment by PilzAdam** [comment]
@ShadowNinja that would cause problems with textures, since they are repeated when the nodebox is bigger than 1 node.

**Comment by tenplus1** [comment]
+1 for mesh nodes... same with doors, oversized nodes would be perfect...

**Comment by ShadowNinja** [comment]
@PilzAdam, with meshes you can specify the UV.  And while you're at it you can make doors look more 3d-like (make the holes/windows actual holes).

@kilbith, a few extra checks aren't so bad, especially considering all the code that goes into managing the two separate nodes as one.

**Comment by PilzAdam** [comment]
How are other mods supposed to know which positions are occupied by doors? Currently both positions are occupied by nodes; if you change it to just one node, one of the occupied positions will remain "air", so other tools (e.g. worldedit) wild happily place stuff there (e.g. /replace air grass).

**Comment by Novatux** [comment]
https://github.com/minetest/minetest_game/commit/2824562dc94da588fd2bc21415bbc193972d93a0

**Comment by Wuzzy2** [comment]
Unfortunately, screwdrivers are able to screw up beds again.
Just left click on any bed and you get a rotated half bed which can't be pointed.

d90a0817223e33996b7fc3bb1c986da3a324aa98

**Comment by paramat** [comment]
I don't think that's much of a problem, screwdriver is for single-node rotating, i would expect weird results when used on a bed.

**Comment by sofar** [comment]
fixed with #955

**Comment by paramat** [comment]
955 merged.
