### ISSUE TITLE
Minetest biomes for mgv5 and mgv7

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#459]
A thread for discussion and feedback from the Minetest Game team.
My initial unfinished work is here in the form of a mod https://github.com/paramat/biomesdev
The trees are in the form of lua tables as the worldedit .mts saving feature seems to be broken. Eventually i intend to store these as .mts files, hmmmm has now added a way to convert lua table schematics to .mts files so i can do this now.

I find the pine needles texture too dark especially when seen with snow and suggest we use VanessaE's texture instead, she is correct that pine needles are not that dark. What do you think?

There is only one appletree, but the low apple chance results in many with no apples, the two types are mixed in together instead of being in specific areas as in mgv6.

**Comment by C1ffisme** [comment]
Suggestion : If this gets implemented into the default minetest game, could you add a setting to disable default biomes? That way mods can make their own biomes, and the default ones don't intrude. (It would be rather odd seeing a forest next to a Mars biome.)

**Comment by MT-Modder** [comment]
@C1ffisme Mods should use ```minetest.clear_registered_biomes()``` and add a dependency to ```depends.txt```

**Comment by C1ffisme** [comment]
Ah, I see, another function that could be replaced with a simple setting.

**Comment by paramat** [comment]
You can also independantly clear the registered ores and decorations too in a mod.

**Comment by C1ffisme** [comment]
You know, if you have the code, why not add this as a pull request right now?

**Comment by MT-Modder** [comment]
I think it's because schematic decorations are broken and he/she wants to discuss it before submitting half finished work.

**Comment by C1ffisme** [comment]
Ah. I see.

Are we sure that worldedit isn't broken and that it is a minetest problem? Maybe we're all making a big fuss over something broken in worldedit.

**Comment by MT-Modder** [comment]
I've looked at the worldedit code and I've written my own mod. Both are using ```minetest.create_schematic``` and both produce this invalid schematic error. So it's minetest. Paramat has a better idea of what's wrong. My theory is that the schematic signature is being saved wrong and there for throws this error but I don't know much about C++.

**Comment by Echoes91** [comment]
I've been testing a mgv7 world with the latest master and your biomesdev and i think it already looks quite great! Thanks for your patience to create inline schematics which are great for quick experiments, they also grant many small variations so that every tree seems different instead of all the .mts clones. I think this is what the next default should be like

**Comment by paramat** [comment]
When i have the trees in the form of .mts files i will add mapgen detection to the sapling growing functions because different mapgen have different designs of tree, in mgv6 the lua tree generation function will be used, in mgv5/v7 the .mts file schematic will be spawned.

I have tried to make tree designs that are true to Minetest's tree character: slightly boxy, simple designs. Due to the per-node randomness of schematics they cannot be identical to the hard-coded generation code of mgv6, for example apple exists as an alternative to air, not leaf. These are not necessarily the final designs but i am fairly happy with them.

**Comment by paramat** [comment]
I can now generate .mts files for these schematics, so this biome system will soon be ready to go in for testing by players and for feedback/improvement. I am considering adding an 8th biome 'sandstone grassland' as i feel sandstone should be included and available as a resource, and would look good in cliffs and mountains.

**Comment by C1ffisme** [comment]
Oooooh!!!! I like it!!!

**Comment by RHRhino** [comment]
It looks cool, but why not adding a new dried grass block instead of normal grass? Grass/Dirt that is placed on sandstone should become a ABM that converts it to dried grass. What do you think about that?

**Comment by paramat** [comment]
A dry grass node is an okay idea, but i doubt the MTGame team will accept it, look at the trouble i had adding something as fundamental as river water =) Also i want to keep this system reasonably simple and 'Minetest classic'.

**Comment by RHRhino** [comment]
Yes I know this story as well as the dozens of other good ideas and pull request, which have been refused since I'm following the development of minetest and minetest_game. I absolutely understand the importance of keeping minetest_game as slim as possible and the existing worlds intact, but it seems that this is also the main reason that kills the development of minetest_game. Another reason is certainly the different perception of core devs, other devs and players which direction minetest_game should take to become a better and more interesting game. 

I can really understand that people who put a lot of time and efford in their ideas and pull requests become fustrated because their work got refused. It is ridiculous that on the one hand these ideas and pull requests get refused because they don't fit in minetest_game or it's gameplay feeling and on the other hand there is not even the slightest attempt of a development plan for minetest_game.

**Comment by C1ffisme** [comment]
Yeah. We should really just let minetest_game have whatever development the devs want, and start a new game with the features real people want. Then we could pull in that game and have both a simple game (minetest_game) and one with all the features people want (Well, within reason. We can't make this game be like, dreambuilder or something).

**Comment by Novatux** [comment]
Shouldn't the biomes min/max height depend on water_level? The code looks fine anyway, and about dry grass, I guess biome colors (if they are implemented) would be better suited for that, but it could be something to add while waiting :).

**Comment by paramat** [comment]
> We should really just let minetest_game have whatever development the devs want, and start a new game with the features real people want.

Please do, celeron55 has been asking for new subgames to bundle with Minetest, and wants them to be significantly different from MTGame.
MTGame does have a dev direction, that is to be a directionless, super-simple, open-ended base for modding, this inevitably makes it not very exciting.

Sandstone grassland is not the place for dry grass, it is the temperate grassland that appears alongside appletrees in the normal biome of mgv6, so should have green grass.

> Shouldn't the biomes min/max height depend on water_level?

Ideally yes it would auto-adjust, but wuld be more calculation during mapgen. Something to discuss with hmmmm.

**Comment by paramat** [comment]
Closing, i will discuss the biome system in https://github.com/minetest/minetest_game/issues/515
