### ISSUE TITLE
Add Suffocation?

### ISSUE THREAD

**Issue by C1ffisme** [minetest/minetest_game#473]
I just thought that maybe it would be nice to add something to make minetesters wary of gravel and sand. This would make mining more dangerous and harder than it is right now.

FAQ : 

Q : Why is this here and not in minetest?
A : Because we could just add suffocation code very quickly in minetest game. I think it is possible by adding ```drowning = 4``` in the sand and gravel code.

Q : What about fly+noclip?
A : Yes. My above method will make survival fly+noclip users have problems if they accidentally fly into a patch of un-mined gravel. Maybe an engine change where you can't have damage while flying could fix this, but otherwise this may be a problem.

Q : Why would we add this? It dosen't seem like it's worth adding. It's just copying minecraft.
A : True, but not dying in gravel might give the impression of a cheesy clone, rather than a good game. And it makes gravel more deadly. It could even be used in PVP, you could drop gravel on enemies.

**Comment by Heybye44** [comment]
:+1:  



—

**Comment by MT-Modder** [comment]
:+1: ```drowning = true,``` Would be the easiest and best way IMO. That solves Q1 - 3.

**Comment by tenplus1** [comment]
There's a mod for that: https://forum.minetest.net/viewtopic.php?f=9&t=10090

**Comment by C1ffisme** [comment]
@MT-Modder  :+1:  That would work.

@tenplus1 We need to expect people are not going to look for mods or cannot access the forums. No suffocation gives the impression of a cruddy piece of software than a game to play.

**Comment by 0-afflatus** [comment]
@C1ffisme : 
> No suffocation gives the impression of a cruddy piece of software than a game to play.

I disagree. This depends very much on your expectations. I don't think it is that important.

**Comment by Calinou** [comment]
`damage_per_second` hurts players even if only their feet are in the sand/gravel node.

**Comment by C1ffisme** [comment]
@0-afflatus How many people are coming looking at minetest and have come from minecraft? See the forum post "Gaining our own identity, as a gaming experience." in the "General Discussion" section. We want people to see a game, not a simulator or something.

@Calinou Yeah, I saw MT-Modder's Comment.

**Comment by 0-afflatus** [comment]
As someone who has never played MC, I don't think the lack of a particular feature you like gives the impression of a cruddy piece of software. None of my players have yet complained that they don't suffocate in sand. And they would if it was important to them.

**Comment by C1ffisme** [comment]
@0-afflatus True. Not all people came from minecraft. But still, whether or not this makes the game feel boring is another issue entirely.

**Comment by Wuzzy2** [comment]
As Calinou said, `damage_per_second` won't work.

Using `drowning` seems better to me, because this actually checks when you are actually inside the node (with the head).
This should be applied to all full solid cubes, like stone, sand, gravel, dirt, etc.

The downside of this is that it takes ridicously long to take damage. But at least it is better than nothing.

The PlayerPlus code refered to by tenplus1 looks like an interesting alternative, but I have not tested it yet.

I think the best solution would be to add suffocation support directly into the engine. Maybe the drowning routines can be reused here. Alternatively, it might also help if the drowning speed (how fast you lose bubbles) would be configurable.

**Comment by C1ffisme** [comment]
@Wuzzy2 Dude!! Read comments!!

I finally decided to change the main comment, though. So you don't have to complain anymore.

Actually, just using ```drowning``` rather than a ```suffocate``` might be better though. Since you may fly into gravel underground and die without warning.

**Comment by paramat** [comment]
Drowning in sands and gravel seems good to me.

**Comment by kilbith** [comment]
@paramat Drowning only for quicksand (idea : could be generated in desert biomes as ore blobs for efficiency).

**Comment by Heybye44** [comment]
:+1: @kilbith Definitely, but drowning in sand and gravel is a really important game dynamic.



—

**Comment by MT-Modder** [comment]
:+1: for sand and gravel.

**Comment by MT-Modder** [comment]
Just opened the PR: #691

**Comment by paramat** [comment]
Closing as the PR was not accepted.

**Comment by asl97** [comment]
@paramat the reason why that PR wasn't accepted was cause of the 'fly+noclip still get damage' flaw.
the idea itself has plenty of ':+1:'.

**Comment by 0-afflatus** [comment]
@asl97 it would still be better to open a new conversation (or re-open this one) once someone has come up with an implementation that deals with the "fly+noclip still get damage" issue. As this isn't a bug report there is no need to keep it open; the forums are a better place for ongoing discussion.

**Comment by PilzAdam** [comment]
@asl97 @0-afflatus 

> Q : Why is this here and not in minetest?
> A : Because we could just add suffocation code very quickly in minetest game. I think it is possible by > adding drowning = 4 in the sand and gravel code.

This is issue is about adding `drowning` to some nodes. This can't be done (see the PR) without undesirable side-effects. Thus, the suffocation should be handled in the engine somehow, as the first post suggests.

**Comment by asl97** [comment]
@0-afflatus the reason to why i made that comment was not due to the issue being close, it because of the reason why it is being close.

if the closing reason was because "the issue wasn't a bug/issue report",  then it's fine.

but the stated closing reason was that "the PR was not accepted".
it is a bad closing reason especially since (1)the OP of the PR wasn't even the OP of this issue and (2)this issue is well accepted.

**Comment by C1ffisme** [comment]
@PilzAdam Or you could add a ```minetest.get_player_in_state(["noclip","fly","fast","any other things worth noting"])```.

**Comment by paramat** [comment]
Yes closing this may have not been justified, sorry, however there is now a new issue #1501

**Comment by paramat** [comment]
Yes i stated the wrong reason for the close, sorry.
