### ISSUE TITLE
Farming Plow lines are not always connected.

### ISSUE THREAD

**Issue by C1ffisme** [minetest/minetest_game#487]
Sorry, just a matter of taste, But I like my plow lines in long rows, not many little ones. This is a small problem, it dosen't affect gameplay, but I just think plow lines should be more connected if possible.

Maybe some rotation code would help?

**Comment by paramat** [comment]
It would have to be dependant on player's 'facedir', so line direction could then be controlled.

**Comment by C1ffisme** [comment]
@paramat Yes. Maybe we could use similar rotation code to chests.

**Comment by paramat** [comment]
If anyone wants this done, please submit a PR, it should be easy.

**Comment by paramat** [comment]
Soil nodes are all aligned E-W so i don't understand your issue.

**Comment by C1ffisme** [comment]
@paramat 
![screenshot_20160406_183058](https://cloud.githubusercontent.com/assets/9893266/14336904/418d6a82-fc2e-11e5-8e63-a878468a6227.png)

The one on the left looks really bad, but the one on top looks just fine.
