### ISSUE TITLE
Make flowers farmable, with seeds, instead of the slow uniform-density spread.

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#496]
Currently flowers reproduce by a very slow unrestrained spread with a fixed density of 3 flowers per 9x9 node area.
Mapgen generates flowers with varying densities and within noise-defined areas, so the current reproduction will eventually remove both these features.
If large numbers of flowers are needed, for dyeing wool for example, all that can be done is to travel to new areas to collect them. In island, skyblock or moon worlds this is not possible, we need seeds to allow intensive flower farming within a small area, this will also make flowers consistent with other crops.
When a flower is picked it should also drop 1-2 seeds on average.
I am offeriing to do the work but am asking if anyone would like to contribute seed textures? Perhaps the seed textures should have a small or subtle/dark colour to them to indicate which flower they are.

**Comment by 0-afflatus** [comment]
:+1: If I can make time, I will gladly have a go at creating some textures.

**Comment by C1ffisme** [comment]
Well, we can do this, but it isn't really realistic. Have you tried pulling seeds off of a flower? Most are really tiny. Just think of Carrot Seeds. And some plants don't use seeds (like strawberries).

Maybe we could increase the flower reproduction speed? Or add some thinking to the matter...

We could have bees and birds that pollinate flowers. But I think that's a little overkill.

**Comment by ExeterDad** [comment]
@C1ffisme your statement about strawberry plants not using seeds is false. It is true that seeds from hybreds or GMO will not produce useful seeds. It's also true most strawberry plants are created from runners of existing plants.

**Comment by C1ffisme** [comment]
When was the last time we had hybrids and GMO in Minetest?

**Comment by paramat** [comment]
What i should have suggested is that when a flower is picked it can also shake off a dust of tiny seeds. Not particularly realistic but then Minetest is simple, abstract and not strictly realistic.

**Comment by PilzAdam** [comment]
Making everything farmable via seeds is quite boring gameplay wise, it leads to the same kind of "farms" being used for everything. Different regrowing systems on the other hand add more variety and require the player to come up with different solutions how to efficiently farm them.

I see how flowers limit the production of colored wool, though. I think a better solution for that would be to make dye reproducible. Add some kind of uncolored "base dye"; combined with any color it results in two (or more) colored dyes. That way we allow the player to create a lot of colored wool without making flowers too common and boring.

**Comment by C1ffisme** [comment]
@PilzAdam Reproducable Dye? Good idea.

Although, some people may want flowers for other purposes (Gardening, Decor).

**Comment by paramat** [comment]
The problem is, the current regrowing method eventually results in flowers growing everywhere in uniform density, which would look really bad. The noise defined areas and densities are not respected.

Similarly with grass, eventually all grass lengths grow to the maximum length. During mapgen different lengths of grass are carefully placed in differing areas and densities, this looks good and adds variation.
Also, cactus and papyrus eventualy grow to the same height, again boring and lacking variation, although changing this may break cactus/papyrus farms.
So i feel all plant growing should be redesigned.

**Comment by C1ffisme** [comment]
I like your past suggestion, paramat.

Maybe we can use particles to demonstrate tiny seeds floating away?

We could also add seasons to Minetest, which would occur every say, 30 in-game days. That way winter could kill-off flowers and spring would start them going again.

Then, make flowers grow a little quickly through spring and summer. In autumn, flower growth would slow down until it stopped, and then flowers would die in the winter.

I think seasons would be an interesting addition to Minetest, especially if winter means you have to wear a coat to survive or stay inside.

Of course, if we do add seasons, we will have to add weather. (Snow is important to make winter look like, well, winter.)

And maybe seasonal colors/textures (autumn leaves, and grass could have fallen leaves on it.)

**Comment by paramat** [comment]
> Different regrowing systems on the other hand add more variety and require the player to come up with different solutions how to efficiently farm them.

That's reasonable, however with flowers the only way to harvest many is to travel, this is not possible on island, skyblock, alien planet colony or moon colony worlds.
> I think a better solution for that would be to make dye reproducible. Add some kind of uncolored "base dye"; combined with any color it results in two (or more) colored dyes. That way we allow the player to create a lot of colored wool without making flowers too common and boring.

I find that a complex and messy idea, better would be to make more dye produced from each flower.

**Comment by paramat** [comment]
Idea is unpopular so closing.

**Comment by C1ffisme** [comment]
Paramat, before you close discussion altogether, why not rename the post "Find a better way to farm flowers" and continue discussion? Just because we don't use seeds doesn't mean we can't find other ways of reproduction.
