### ISSUE TITLE
[Request] TNT API

### ISSUE THREAD

**Issue by Rui914** [minetest/minetest_game#500]
The function of TNT can use in any other mod.
・Example
```
tnt.explode
tnt.boom
tnt.register_tnt(name,description,tiles,radius)
```

**Comment by ShadowNinja** [comment]
[My nuke mod](https://github.com/ShadowNinja/nuke) has an API, and the TNT mod is based on it.

**Comment by Heybye44** [comment]
They should merge it and add server protection if it doesn't have it. :+1:

**Comment by Rui914** [comment]
Also, the explosion function of TNT also will should be to the API.

**Comment by C1ffisme** [comment]
Maybe functions like: ```tnt.explode``` and ```tnt.boom```.

Actually, I think these functions already exist, lemme check the code...

Yeah, they're all there, but they're all local. And a ```tnt.register_tnt(name,description,tiles,radius)``` would be nice.

**Comment by C1ffisme** [comment]
Maybe functions like: ```tnt.explode``` and ```tnt.boom```.

Actually, I think these functions already exist, lemme check the code...

Yeah, they're all there, but they're all local. And a ```tnt.register_tnt(name,description,tiles,radius)``` would be nice.

**Comment by LeMagnesium** [comment]
I made this modification, it's not something that complicated, and I feel like the issue list is growing without issues being closed/solved, so if it helps :  #502

**Comment by LeMagnesium** [comment]
`x_range` and `y_range`  would be enough (having x and z being different would lead to very strange shape). I will do it later, when #502 is closed or merged.

**Comment by ShadowNinja** [comment]
> A tnt.register_tnt(name,description,tiles,radius) would be nice. [...] mese TNT [...]

We might as well just rename my `nuke` mod and merge it (without missiles).
I rewrote TNT to basically just be a minimal version of that mod with some slower things like drops (because it doesn't support big explosions).

**Comment by C1ffisme** [comment]
I never knew you had missiles in your nuke mod!!! I wish I could get this kind of news...

Anyway, if you have x,y and z ranges, then you could make elipses (egg shapes).

**Comment by LeMagnesium** [comment]
> then you could make elipses (egg shapes)
For eggs you only need x (because x = z) and y.

**Comment by C1ffisme** [comment]
Yes, but say you wanted to make one that was shaped like a real egg, not like a flattened ball?

**Comment by LeMagnesium** [comment]
![tnt blow](https://lut.im/v7pheSzq/AQmJhtD1)
TNT with z and x being equal. Seen from above, this shape is regular, even if y is higher than x and z. It draws like an egg shape along the y axis.

![regular egg](https://lut.im/yIbfbt3H/6XADLFEZ)

![irregular egg](https://lut.im/bLBxtrkG/fCuKZ3D7)
TNT with z and x being different. Seen from above, it looks like little beans oriented to the same direction, like an egg, but on the z or x axis. It looks ugly.

**Comment by C1ffisme** [comment]
When did we say that explosions had to be pretty? :confused:

**Comment by LeMagnesium** [comment]
You don't want a bunch of holes rotated along the same axis, do you?

**Comment by C1ffisme** [comment]
I can see uses for it...

Think of the enemy bases we could blow up without destroying our own!

**Comment by red-001** [comment]
#667

**Comment by red-001** [comment]
TNT API was added in cfef21f
