### ISSUE TITLE
Meselamps should be default.light_max

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#503]
There are many justified complaints about how dark Minetest is (inherently and unavoidably of course), i feel that meselamps, being a mysterious magickal material, should emit at least as much light as a torch. In all my mods i always use maximum brightness for lights as this is only just satisfying enough.

**Comment by C1ffisme** [comment]
Yeah, I agree. Torches are too dark, And since meselamps are super-expensive, they should spread full light, if not more.

**Comment by LeMagnesium** [comment]
If you find these meselamps too dark for the amount and rarity of items we use to craft it, then here is a simple solution : http://pastebin.ubuntu.com/11031263/ .
And I agree, that being expensive to craft and magical, they should be at `default.LIGHT_MAX - 1` like torches and not only 12.

**Comment by C1ffisme** [comment]
Why not make them brighter? They should be ```LIGHT_MAX```.

**Comment by LeMagnesium** [comment]
`default.LIGHT_MAX` refers to the direct sunlight, meaning that no node is able to do equal lightning. Also, it is very hard to tell the difference between `default.LIGHT_MAX - 1` and `default.LIGHT_MAX` .

**Comment by C1ffisme** [comment]
Yes, but would you mine for hours to get a mese block, and make a mese lamp, just for the same amount of light as a torch?

How much would you pay for the same amount of light:
* A coal lump and a stick, found in about 3 seconds OR
* A mese block and glass, which could take **HOURS** to find.

**Comment by LeMagnesium** [comment]
> Yes, but would you mine for hours to get a mese block, and make a mese lamp, just for the same amount of light as a torch?

Then dicrease the light_source for torches.

**Comment by C1ffisme** [comment]
That's not very logical. We did that with wooden and stone tools. It was about the WORST change ever.

**Comment by LeMagnesium** [comment]
Indeed, but again, I don't remember anyone advising to use `default.LIGHT_MAX` (because it is supposed to only be sunlight).

**Comment by PilzAdam** [comment]
@C1ffisme meselamps are a way to get a light source when you mine very deep (e.g. -10000) and wood becomes rare. You can't afford to make new torches, since you need to spare your sticks for new picks. In this case you rather spend mese than wood to make a light source.

@LeMagnesium Sunlight is 15, default.light_max is 14, which is the maximum light for nodes. Lava has a light level of 14, torches have 13.

**Comment by LeMagnesium** [comment]
@PilzAdam thanks for this reminder I forgot default.light_max was dicreased a while ago to 14..
Then ok, default.light_max sounds correct, but default.light_max - 1 can still be used.

**Comment by DrConsole** [comment]
Thanks for the Linking of my Request, I also support this one.
If alamp is this hard to craft, it should have some specials in relation to normal torches as for example more light. (even if I didn't heared about them until now, but I didn't played this much yet)

**Comment by paramat** [comment]
I see i didn't realise light_max was 14. I can understand torches being 1 less than maximum, i feel meselamps should then be light_max so we have at least 1 lighting node with maximum effect, i would expect a meselamp to be as bright as lava.

**Comment by C1ffisme** [comment]
@PilzAdam Meselamps also require glass, and you don't tend to bring a lot of that around with you.

And it needs a use on the surface too.

**Comment by PilzAdam** [comment]
@C1ffisme isn't there sand underground?

**Comment by thatgraemeguy** [comment]
Sand underground is pretty rare in my experience. I think I've seen it twice in several months of play.

**Comment by DrConsole** [comment]
Could be if you use World gen V7

I also recognized it and tried out the V gen and this is more minecraft
like (more ditribution of climate zones)

**Comment by CreeperLord700** [comment]
i aggree

**Comment by paramat** [comment]
In alll mapgen sand now occurs only from -32 to 0.

**Comment by C1ffisme** [comment]
Why did you close this? It's still a problem!!!

**Comment by ExcaliburZero** [comment]
@C1ffisme Meselamps were set use use `default.LIGHT_MAX` with fa1b4d0d44535e93a085e10023a82076d180b64c through #507 . I'm assuming that was why the issue was closed.

**Comment by C1ffisme** [comment]
Ok. Didn't see that one.
