### ISSUE TITLE
Beds, doors and fire

### ISSUE THREAD

**Issue by Ekdohibs** [minetest/minetest_game#509]
To reproduce: place a bed, and put some fire near the bed *top*.
Try it a few times; then the bed top will be burnt, but the bottom won't. There is a similar problem with doors.
Note that if you try it with the bed bottom, on_destruct will be called deleting the top too. However, it is not possible to add a similar on_destruct to the bed top: indeed, both on_destructs will be called recursively, resulting in a crash should anything try to destroy the bed.

**Comment by PilzAdam** [comment]
Is the node removed before or after on_destruct is called?

**Comment by Novatux** [comment]
It looks like the node is removed after on_destruct is called (else, it wouldn't crash).

**Comment by PilzAdam** [comment]
Maybe this can be solved by adding a flag in node metadata?

**Comment by Novatux** [comment]
I had an idea like that, but found it very hacky :|... But it looks like it is the easiest solution

**Comment by Novatux** [comment]
What about making a few helpers functions for multinode nodes (such as doors and beds) and using them for doors and beds? If so, where should these functions be (builtin or default)?

**Comment by Megaf** [comment]
On homedecor doors are a single node now, can't we make beds and doors single node? @kilbith could help with that.

**Comment by LeMagnesium** [comment]
The metadata flag remains the easiest solution if we keep doors and beds as double nodes..
Yet, when fire destroys a node, it triggers the `on_destruct` function, implemented for beds, but not the `on_dignode` callback, implementer for doors... So either we make doors as beds, meaning that we could only punch it and dig it from its bottom, or we find a way to make fire activate `on_dig_node`..
#517 solves the issue for beds, using metadata flags. I haven't yet firgured out how to keep the actual way of working for doors and handle fire-made destruction...

**Comment by PilzAdam** [comment]
@Megaf a single node that covers 2 node positions is a bad idea, see https://github.com/minetest/minetest_game/issues/451#issuecomment-88100363

**Comment by Megaf** [comment]
A dummy node could be placed.

**Comment by sofar** [comment]
@LeMagnesium in your last comment you forgot to add option number 3 - add on_destruct handlers to doors. This seems a decent solution, and would probably help TNT as well, as well as other node destroying mods that may not yet exist.

**Comment by Ekdohibs** [comment]
#517 fixes this, but only for beds.

**Comment by sofar** [comment]
I don't think the current door top is flammable, so there shouldn't be any concern for doors.

**Comment by C1ffisme** [comment]
I think doors were fixed since they were turned to meshnodes.

**Comment by paramat** [comment]
Ok closing.

**Comment by paramat** [comment]
Is it a problem that half a bed burns? Seems ok to me.

**Comment by paramat** [comment]
Doesn't seem a serious bug, if only half a bed burns is that a problem?

**Comment by paramat** [comment]
I don't think is a serious bug, so removing from milestone.

**Comment by paramat** [comment]
#911 approved.
