### ISSUE TITLE
[Feature Request] Add some options to beds mod.

### ISSUE THREAD

**Issue by Megaf** [minetest/minetest_game#512]
Hi,
On I'd like to see some options to change how beds behave:

* Add option to enable/disable time change when nobody is online (When everybody leaves, beds seems to be reseting the time to morning, despite the actual time, it might be a bug).
* Add option to allow/disallow players to skip the night.

Thanks.

**Comment by Novatux** [comment]
The time resetting to morning when everybody leaves is caused because everybody in the server is in bed; this is however a bug imho.

**Comment by Novatux** [comment]
https://github.com/minetest/minetest_game/commit/3669ca0a8355a56bd6a519ccd35f7b526fa11c76

**Comment by Megaf** [comment]
https://github.com/minetest/minetest_game/commit/3669ca0a8355a56bd6a519ccd35f7b526fa11c76 fixed the first issue, thanks.

**Comment by LeMagnesium** [comment]
About the second point of the issue, it was not complicated : #514 .

**Comment by paramat** [comment]
#514 now merged.
