### ISSUE TITLE
Should mgv6 snowbiomes be enabled by default?

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#519]
Somehow i was recently under the impression that mgv6 snowbiomes must be disabled by default to avoid breaking existng worlds, of course this is actually not the case because they are controlled by mapgen flags which are stored per world in map_meta.txt.

One effect though is that any mod that relies on partcular locations for mgv6 biomes will be incompatible with the new biome system, they would need an option added to be compatible. This doesn't seem a huge problem.

Personally i would quite like snowbiomes to be enabled by default, to enable pine trees and to balance and complete the old biome system by mirroring the hot dry (desert) and hot wet (jungle) biomes with cold dry (tundra) and cold wet (taiga) biomes.

How do you feel about this?
Any other issues this would cause i haven't thought of?

Also, with the new biome system biome size has decreased, they were fairly small to begin with, it may be a good idea to increase the spreads of the biome and humidity noises. As these are stored in map_meta.txt this would not break existing worlds.
Currently biome spread is 250 and humidity spread is 500, to equalise these would be a good move by increasing biome spread to 500.

**Comment by C1ffisme** [comment]
Yes.

**Comment by Calinou** [comment]
:+1:, else some items are not accessible.

**Comment by paramat** [comment]
With snowbiomes enabled, normal and jungle biomes have roughly halved in size and deserts are down to roughly 2/3rds, so doubling biome noise spread seems ideal.

**Comment by tenplus1** [comment]
+1 enabled by default

**Comment by paramat** [comment]
Checked with hmmmm this will not break old worlds, this will probably happen soon.

**Comment by paramat** [comment]
Now by default.
