### ISSUE TITLE
Default: New obsidian brick texture

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#521]
![screenshot_20150527_050110](https://cloud.githubusercontent.com/assets/3686677/7828652/34fb857c-042e-11e5-8774-72b447da99ce.png)

Thought i would perfect the texture in an issue before creatng a PR.
I used Gimp pencil in value mode to shade the bevels, added corner bevels for a faceted black-glass look. No mortar as i feel it's not suitable for exotic obsidian constructions. Converted to indexed before exporting to reduce file size.
Comparison with current texture, top is my submission (which somehow seems to lack contrast in this screenshot while looking okay in the dungeon screenshot above):

![screenshot_20150527_050244](https://cloud.githubusercontent.com/assets/3686677/7828693/db5792ee-042e-11e5-9341-36238afc847c.png)

**Comment by C1ffisme** [comment]
Cool!

**Comment by Novatux** [comment]
Looks good!

**Comment by paramat** [comment]
I'll wait for another possible approval from the team before creating the PR.

**Comment by paramat** [comment]
Approval from sfan5 http://irc.minetest.ru/minetest-dev/2015-06-01#i_4274128
I have added the texture to my PR for river water textures https://github.com/minetest/minetest_game/pull/523

**Comment by paramat** [comment]
40e2b945e33fff87c50cd304d2c253e1e85d13c7

**Comment by C1ffisme** [comment]
It would be fun if we could get obsidian brick dungeons, with lava pools and mobs.
