### ISSUE TITLE
Wrong sound footstep on default:snow

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest_game#524]
Eg. walking over the snow nodeboxes covering the stone nodes produces... a stone footstep sound.
Same goes for snow over the leaves, etc.

This bit of code is correct but somehow ineffective in-game : https://github.com/minetest/minetest_game/blob/master/mods/default/nodes.lua#L347

**Comment by PilzAdam** [comment]
This an issue with the engine. The nodebox for the snow is probably too thin.

**Comment by C1ffisme** [comment]
What happens when you walk on slabs?

**Comment by 4aiman** [comment]
For me snow works ok.
The one from ethereal and splizard's snow mods.
Slabs and stairs are just fine too.
