### ISSUE TITLE
Cactus doesn't grow unless facing north

### ISSUE THREAD

**Issue by asl97** [minetest/minetest_game#529]
param2 (node place down):
```
north: 0
east: 1
south: 2
west: 3
```
related:
https://github.com/minetest/minetest_game/commit/fe3c5a709047fbdd51e0c8086d5ea0465d7ecb3b
https://github.com/minetest/minetest_game/pull/310

**Comment by paramat** [comment]
Yes i tried to fix this when pushing the commit but was not allowed to, i will fix soon.

**Comment by paramat** [comment]
016fa0da40d152d32d50a52b80b71b0e4e2f9d27

**Comment by asl97** [comment]
not fix
https://github.com/minetest/minetest_game/blob/a3f439bb4aee69277ff19ad224c9f61060d1b82b/mods/default/functions.lua#L136

**Comment by paramat** [comment]
I didn't see that line, thanks, will fix soon.

**Comment by asl97** [comment]
@paramat if you remove it, people could just place it sideways on top of a correctly place cactus and it would grow.

**Comment by paramat** [comment]
Yes, that's not a problem and was the previous behaviour, it also makes the code simpler. So growth is now determined by the rotation of the base cactus node in contact with sand. The rotation code was only added on my request to stop the ABM running on the large branched cacti i'm adding to mgv5/mgv7, which have base nodes placed upside-down, rotation=20.
