### ISSUE TITLE
Allow connected glass for xpanes glass

### ISSUE THREAD

**Issue by An-dz** [minetest/minetest_game#536]
The titles says all, have only the glass blocks connected is not what I was expecting to see.

Connected glass for obsidian glass would also be good.

**Comment by RHRhino** [comment]
I think the connected glass drawtype only works on full blocks.
BTW connected obsidian glass has already been requested:
https://github.com/minetest/minetest_game/issues/383
https://github.com/minetest/minetest_game/pull/442

**Comment by An-dz** [comment]
Did not notice that pull request was still open, thought it was rejected. Will try to convince its merge there.

**Comment by paramat** [comment]
Possibly needs engine changes?

**Comment by paramat** [comment]
Closing since an engine issue.
