### ISSUE TITLE
Placing locked chest on tall grass open the inventory

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest_game#537]
When you place a `locked_chess` on a node that is `buildable_to = true` like `default:grass_*`, the locked chest inventory is opened automatically.

**Comment by nanepiwo** [comment]
This does not happen for me, might you just have a faulty mouse that double-right-clicks?

**Comment by est31** [comment]
I can reproduce. I wonder however whether this is a game bug.

**Comment by BlockMen** [comment]
@est31 you guessed right, not a game bug.
