### ISSUE TITLE
[Feature Request/Discussion] Weather? Maybe?

### ISSUE THREAD

**Issue by C1ffisme** [minetest/minetest_game#538]
Yes, we did have weather before, and failed to add it. It's really hard, since it's not easy to calculate if you have a roof above you. Expecially with chunks that are seperated on the y axis.

There are ways, though. This is to discuss the possible ideas.

My idea is to drop an entity on each loaded block before a rainstorm, find where it hits, and rain if the rain is within a certain radius of a player, and the rains y level is not higher than the player's head level. If a block is placed, stop all rain on that block, drop another entity and find where it hits.

If you have ideas, please tell me!

Or I suppose we can do this real easy if we did it in the engine, but I feel that it would be very mod supportive if we did it in Lua, since you might want acid rain, falling volcano particles, etc.

**Comment by paramat** [comment]
Should be discussed as an engine and API issue, lua alone is far too slow for weather.
