### ISSUE TITLE
Unused texture

### ISSUE THREAD

**Issue by Rui914** [minetest/minetest_game#544]
The Minetest Game contains the old (not used) texture in default.

**Comment by PilzAdam** [comment]
Which texture is not used?

**Comment by Rui914** [comment]
default_tnt_*.png,
default_torch_on_ceiling.png,
default_torch.png,
↓Alternate?
player.png,
player_back.png

**Comment by LINUXFREEAK** [comment]
Yeah, can somebody delete them?

**Comment by ExcaliburZero** [comment]
I attempted to remove them with this commit: https://github.com/ExcaliburZero/minetest_game/commit/81ee9dbead40a5823c4f9f9ac3d4516a3b0d423b . However, removing the tnt textures in the default mod seems to cause some issues for some reason. When I do so, tnt nodes are no longer properly textured, even though they are using tnt textures in the tnt mod.

![screenshot_20150721_092131](https://cloud.githubusercontent.com/assets/4276196/8801794/17763fc8-2f8b-11e5-8ee3-839d41a17bd6.png)

**Comment by C1ffisme** [comment]
Try removing the textures in tnt and see if that changes anything.

**Comment by ExcaliburZero** [comment]
I tried removing the tnt mod textures while keeping the default mod textures for tnt here in https://github.com/ExcaliburZero/minetest_game/commit/723fa69d397cd9f7de5a47e4b267ab8a5a486587 . And it causes Minetest to throw a few errors into chat, but the textures for tnt do work properly. I'm not sure why this happens.

![screenshot_20150721_164913](https://cloud.githubusercontent.com/assets/4276196/8812282/3f696a62-2fc9-11e5-8aa9-fa38b59fd732.png)

**Comment by C1ffisme** [comment]
Strange... Very strange...

It appears that the TNT mod is **actually** using the textures in default...

**Comment by HybridDog** [comment]
this would break some mod
https://github.com/HybridDog/TNT/

**Comment by C1ffisme** [comment]
Why not fix that mod to make it not break?

**Comment by HybridDog** [comment]
> Why not fix that mod to make it not break?

https://github.com/CraigyDavi/minetest_game/commit/fdc876f719b2661fcf8635b2ffbab921772d8cc3 is not merged yet and l think almost noone uses my version of the tnt mod, so l only need to fix it if that becomes merged (or git am)

**Comment by paramat** [comment]
Merged PR #600
