### ISSUE TITLE
Deep caves in mgv7 always filled with sand on ground

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest_game#546]
A few examples that look not realistic __at all__. This sand also hide the ores.

![screenshot_20150624_184159](https://cloud.githubusercontent.com/assets/7883281/8335967/4c8fc1ba-1aa1-11e5-9fed-a6d6a81e5ffb.png)
![screenshot_20150624_184217](https://cloud.githubusercontent.com/assets/7883281/8335971/52eda022-1aa1-11e5-888c-4dca9436da9d.png)

**Comment by paramat** [comment]
I'll look into this. I have noticed this, i think it happens at mapchunk borders where a cave above stone tricks the biome generation into thinking there is an upper surface at the top of a mapchunk.
I need to add a deep biome that doesn't have any 'top' or 'filler' nodes, this needs to be active below the deepest oceans of mgv5, so from roughly -192 downwards, which is also the highest lava level.

**Comment by paramat** [comment]
I found the reason why caves were not removing sand https://github.com/minetest/minetest/blob/master/src/mapgen_v7.cpp#L870
This was added to stop caves removing sand from the seabed and causng huge underground waterfalls, however this cave sand issue is more important to fix so i'll remove lines 870 to 872.

**Comment by paramat** [comment]
![screenshot_20150626_020751](https://cloud.githubusercontent.com/assets/3686677/8368882/72e595ee-1ba8-11e5-9123-097a894e7278.png)

With this PR commited there will still be a few patches of sand in large caves, as shown above. Although caves are cut after biome nodes are placed, overgenerated large caves will create voids in neighbouring mapchunks which will be detected as upper surfaces, causing sand to be placed.

**Comment by kilbith** [comment]
Thanks for care of this bug. However the sand in caves does not come from the seabed, or has not fallen either. This is truly generated in the undergrounds.

mgv7 also contains some portions of sand suspended in air, often along the rivers cliffs or caves entries.

**Comment by paramat** [comment]
> the sand in caves does not come from the seabed, or has not fallen either. This is truly generated in the undergrounds.

Correct.
"Where a cave meets a mapchunk's lower border an upper surface is formed, biomegen then detects this and places sand at the top of the mapchunk below, this sand is then not being removed by cavegen."

**Comment by kilbith** [comment]
Tested https://github.com/minetest/minetest/commit/36163d96533313f8fd336c04911383569582acc1

This doesn't still solves the issue...

![screenshot_20150627_092055](https://cloud.githubusercontent.com/assets/7883281/8390959/053683b2-1cae-11e5-9889-5af506d569d7.png)
![screenshot_20150627_091954](https://cloud.githubusercontent.com/assets/7883281/8390960/0c498564-1cae-11e5-80d3-d5927075fb3f.png)

**Comment by paramat** [comment]
Yes see the 4th comment, this will be fixed below -192 when i add the full biome system. The current biome system is simple and temporary so there's no point fixing it yet. Sand in overgenerated large caves will be always be unavoidable down to -192.
