### ISSUE TITLE
Turkish Translation - Question

### ISSUE THREAD

**Issue by yigido** [minetest/minetest_game#547]
How can I translate the game into Turkish?
Can a developer help me?

**Comment by Calinou** [comment]
Please submit translation issues to [minetest/minetest](https://github.com/minetest/minetest), since minetest_game cannot be translated yet.

**Comment by yigido** [comment]
When it is ready, I will be translate it. 
Thank you.

**Comment by kilbith** [comment]
Close your issue then, which is not an issue...
