### ISSUE TITLE
Locked furnaces/doors/signs

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest_game#55]
Just a quick suggestion. ;)
Locked furnace recipe should be like locked chest, but with a steel ingot in the center.
Locked door recipe should be like a door but with a steel ingot; locked sign recipe would probably be like sign recipe, but replacing the stick with a steel ingot.

**Comment by BlockMen** [comment]
Furnaces support protection mods, so do signs. Also there is a locked door and a locked chest aswell. Closing.
