### ISSUE TITLE
[Feature Request] use visual_scale in farming.register_plant

### ISSUE THREAD

**Issue by LINUXFREEAK** [minetest/minetest_game#552]
I want to do a corn (farming) mod and I want that the block is 2 blocks high or maybe 1.8 blocks high.
I would add in mod/farming/api.lua e.g. line 211 "visual_scale = def.visual_scale,"

**Comment by PilzAdam** [comment]
Can you use override_item after registering the plant with the farming API?

**Comment by LINUXFREEAK** [comment]
Yes, I can.
But then I have to do this with a lot of items.

**Comment by Rui914** [comment]
#572 
Added visual_scale for farming.register_plant.
And, I've omitted the check code of def table.

**Comment by LINUXFREEAK** [comment]
Thanks!
