### ISSUE TITLE
The need for a new grass texture

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#560]
Celeron, hmmmm and myself find the current texture too dark and grim. When i try out the minimal game or older versions of Minetest it always strikes me how pleasant and uplifting a brigter texture is.
As an experiment i adjusted our current texture to match the brightness and hue of our previous texture (the current texture is a little too yellow, i made it greener). This is not a submission yet and not perfected, but an example of what could be:

![screenshot_20150708_235546](https://cloud.githubusercontent.com/assets/3686677/8586331/49857204-25e5-11e5-94ed-210f638ea326.png)

**Comment by kilbith** [comment]
Your texture looks good, however the current grass saturation is faithful to the RL grass (your is less, honestly).

Also you'd need to adjust the tall grass colors as well so that they would not be camouflaged / hidden onto the lands. You can take the original tall grass_\* textures in PixelBOX for suit your ground texture.

**Comment by paramat** [comment]
Yes long grasses might need some adjustment.
Our current grass is certainly more realistic, but Minetest has always had bright grass from the beginning and i feel we should keep that character.
I have tried to get used to our dark grass, usually i get used to new textures after a while, but the grass continues to bother me.

**Comment by RealBadAngel** [comment]
instead of changing the color of one grass, maybe better code grass tinting? this way we will have more variety in game and also folks could have current grass in some biomes, brighter in another...

**Comment by C1ffisme** [comment]
I actually like darker grass. It looks healthier and more saturated (Not by color, but by water.). Maybe we can use more saturated colors of grass to make tropics, swamps and jungles.

**Comment by est31** [comment]
I like the darker grass too.

**Comment by nanepiwo** [comment]
I think darker grass is a good idea, but disagree that the color should
vary in different regions.

**Comment by kilbith** [comment]
Well, people seem to be in favor of the darker grass in fact...

**Comment by est31** [comment]
related to #434

**Comment by paramat** [comment]
It's for the MTGame team to decide, i remember there was a deliberate move away from light grass, which i think was a mistake.

**Comment by Calinou** [comment]
I would like the grass to be *a tad* larger, not as bright as you made it on the first screenshot.

**Comment by kilbith** [comment]
@paramat It's up to the team (mostly devs, not artists) to decide but all preference feedbacks are considered usually. I'd feel embarassed to impose a texture that a certain amount of users don't like.

**Comment by paramat** [comment]
Yes i can understand that.
As a compromise i might submit a second possible texture, that just has the hue correction (less yellow) and less brightness increase. Also matching long grasses textures so they still stand out as was intended.
What does the MTGame team think on this issue.

**Comment by paramat** [comment]
![screenshot_20150810_171505](https://cloud.githubusercontent.com/assets/3686677/9176569/044809dc-3f84-11e5-873f-c88016bf267d.png)

I found philipbenr's original texture in #323 from which our current texture is derived. I increased contrast and brightness, and rotated the hue by +10, for the closest match to Minetest's previous grass texture of 0.4.10. I find the noise pattern of our current texture better than the 0.4.10 texture (less grid effect), but prefer the brightness, contrast and hue of the 0.4.10 texture, the suggestion above combines the best of both.

**Comment by kilbith** [comment]
:+1: I like it.

**Comment by est31** [comment]
Like it too.

**Comment by Ekdohibs** [comment]
I like it too :+1:

**Comment by paramat** [comment]
Wow i didn't expect that =) I will of course need to edit the long grasses to stand out against it as before, will work on it.

**Comment by C1ffisme** [comment]
I like it!

It's not to light and boring, but dosen't look too different from a desert! Awesome! :+1:

**Comment by JBBgameich** [comment]
I like your lighter texture.
When I played old versions I liked the light in the old versions. So I hope it will be light again

On 10. August 2015 18:25:45 MESZ, Paramat <notifications@github.com> wrote:
>![screenshot_20150810_171505](https://cloud.githubusercontent.com/assets/3686677/9176569/044809dc-3f84-11e5-873f-c88016bf267d.png)
>
>I found philipbenr's original texture in #323 from which our current
>texture is derived. I increased contrast and brightness, and rotated
>the hue by +10, for the closest match to Minetest's previous grass
>texture of 0.4.10. I find the noise pattern of our current texture
>better than the 0.4.10 texture (less grid effect), but prefer the
>brightness, contrast and hue of the 0.4.10 texture, the suggestion
>above combines the best of both.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/minetest/minetest_game/issues/560#issuecomment-129517082

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by paramat** [comment]
Will reduce saturation a little for a closer match to the 0.4.10 texture, and open a PR soon.
