### ISSUE TITLE
Add and tweak of aliases

### ISSUE THREAD

**Issue by Rui914** [minetest/minetest_game#566]
minetest_game the some alias is missing.
 alias will facilitate operations such as give command.
```
/giveme default:meselamp
↓
/giveme meselamp
```

**Comment by kilbith** [comment]
See https://github.com/minetest/minetest/issues/2907#issuecomment-121004596

**Comment by paramat** [comment]
kilbith that's a little harsh.
Rui914's description is clear enough.

**Comment by kilbith** [comment]
@paramat He has edited the description, my comment was posted when there was nothing at all (thus nothing to understand). Also everyone can use google translation and simple examples, no excuse.

**Comment by paramat** [comment]
I see sorry, yes i remember this being a blank issue.

**Comment by paramat** [comment]
"-- Aliases to support loading worlds using nodes following the old naming convention
-- These can also be helpful when using chat commands, for example /giveme"
The use with /giveme is only secondary, they're mainly for supporting old worlds, so aliases are not updated anymore.

**Comment by Rui914** [comment]
@paramat 
The use with /giveme isn't only.
For example, use to replace the map of the node.
Also, can use to recipe registration.

**Comment by paramat** [comment]
The aliases are very out of date, i don't think we update it anymore. MTGame team, do we bother updating this? i find the technical name for nodes more memorable for using with giveme etc.

**Comment by Rui914** [comment]
I understand.
