### ISSUE TITLE
[Feature Request] Add Sugar and change the papyrus to sugar cane

### ISSUE THREAD

**Issue by Rui914** [minetest/minetest_game#580]
This would be useful to some mod.
Also, it can use when added food (e.g. cake) in future minetest_game.

But, need change the papyrus to sugar cane.

#447

**Comment by PilzAdam** [comment]
This doesn't make sense to me. Why can you create paper out of a sugar cane?

**Comment by tenplus1** [comment]
Farming Redo already has sugar implemented although no reason for it to be default in game as no foods require sugar to be present, only for mod use...

**Comment by paramat** [comment]
-1. Sugar isn't fundamental enough a food for default.

**Comment by C1ffisme** [comment]
@PilzAdam You can make paper out of trees... And I suppose maybe if you grinded and cemented sugar cane together you could make paper...

**Comment by ExeterDad** [comment]
You can certainly make paper from sugar cane. In fact it's in use in tropical and sub-tropical areas. https://en.wikipedia.org/wiki/Bagasse

**Comment by C1ffisme** [comment]
Well what do you know? You can make sugar cane into paper.

I feel that sugar should be added, just so that there isn't half a billion sugars when you have mods enabled. Doubtless many mods have there own sugar just to remove dependencies.

**Comment by 0-afflatus** [comment]
Yes but papyrus != sugar cane
I'm against sugar - flour + egg + something already sweet like fruit logically makes cake.
