### ISSUE TITLE
New stairs and slabs discussion

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#581]
I'm opening this as a discussion instead of a PR to avoid conflict with https://github.com/minetest/minetest_game/pull/571, if i get approval i will make and merge the PR later.

Acacia wood needs adding of course.
As another addition i would like steelblock too, to be steel stairs, ideal for modern structures, spacecraft, space stations etc. Steel stairs and slabs are useful fine detail nodes for any structures made from steel.

**Comment by kilbith** [comment]
If we start adding a steel slab, there will be good reasons for gold slab, etc. etc. (overfilled inventory).

Why not a simplified moreblocks that regroup all those cut nodes instead ?
Example : http://i.imgur.com/4G5gIZs.png

**Comment by paramat** [comment]
More options is not a problem, however yes to avoid overkill i was restrained and didn't request glass, copper, bronze, gold, diamond =) Steel is likely to be used more than bronze and copper.

**Comment by kilbith** [comment]
Problem is that we never know what each user expects exactly. It might have good reasons as well for different materials, this is a slippery slope IMO.

**Comment by paramat** [comment]
Don't worry i got my spiked boots on =)

**Comment by C1ffisme** [comment]
What about making hay stairs and slabs?

It sounds weird and stupid, but you can use the slabs for smaller rooftops and the stairs for rooftops and you can make furniture without making it look like you sit on a stone couch.

About steel, copper, bronze, diamond, stairs, we could make another material that isn't just a normal metal, or use the same node and find a way to alter it's texture on placing and in the inventory as well as it's description (Similar to minecraft stairs,wood, etc. which are the same node).

**Comment by paramat** [comment]
Straw stairs would be good for sloped thatched roofing. What do others think?

**Comment by VanessaE** [comment]
I see no problem at all with making stairs and slabs out of the various "block" objects.  If this causes an item count bloating problem in the creative inventory, then I suggest the creative inventory needs a better way to manage large amounts of nodes.

Kilbith's ideas of adding Unified Inventory (maybe just the upstream copy but defaulted to "lite" mode) and some kind of "lite" version of the Sokomine's tablesaw (from Moreblocks) have merit.

**Comment by kilbith** [comment]
Basically I consider 2 solutions for a better sorting system in the creative inventory : 
- Unified Inventory lite - but it's still half-baked and needs some polishing (no custom background, no HD images, itembuttons size from 0.8 to 1.0, less uneeded code from the full mode).
- [Inventory Enhanced](https://github.com/indriApollo/minetest_inventory_enhanced) - based on the current inventory, with a search field. IMO this the wisest solution who inherits of the actual means w/o radical changes.

Also the moreblocks code (written by ShadowNinja and optimized) is better than the Sokomine's one, stylistically and functionally.

**Comment by paramat** [comment]
sfan5 seems to approve of steelblock but asks for input from other mtgame devs
http://irc.minetest.ru/minetest-dev/2015-07-21#i_4334153

**Comment by paramat** [comment]
Acacia wood has been added, so now this issue is for discussing what other materials could be added.

**Comment by LazyJ** [comment]
I'm in favor of adding stairs and slabs to more of the default blocks. Players come up with creative ways to use stairs and slabs for much more than just a way to walk/run up and down different elevations.

As for inventory bloat, what about instead of showing every stair and slab that is available, using a single, token icon of the shape? Maybe including a "+" symbol in the inventory image to indicate that this shape can be crafted from other blocks. Like how a "G" is currently used to indicate the item is part of a similar group of items. Then it would be up to the player to either read a list of stair and slab compatible materials or figure it out themselves by experimenting.

**Comment by VanessaE** [comment]
For reference, LazyJ's "G" comment refers to Unified Inventory ("G" over a wood block means "anything in the wood group").

**Comment by Sokomine** [comment]
Steel and straw/hay stairs are a very good idea. Probably also wool:white.
As to creative inventory, I never got warm with that one. LazyJ's suggestion of something like the group system of UI sounds good.
There is more to that - right now, the crafting system does not work well on touch-based clients, and the game as such lacks a craft guide. Inventory enhanced does not seem to provide one either, so it is of limited gain. This part of the discussion ought to happen in its own issue I think.

**Comment by paramat** [comment]
MTGame devs, how about steelblock and straw for 0.4.13, since we have a release soon?

**Comment by JBBgameich** [comment]
Straw and steel stairs are good. Straw stairs can used for roofes.

On 10. August 2015 15:50:32 MESZ, Paramat <notifications@github.com> wrote:
>MTGame devs, how about steelblock and straw for 0.4.13, since we have a
>release soon?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/minetest/minetest_game/issues/581#issuecomment-129460554

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by C1ffisme** [comment]
I would say wool stairs and slabs for furniture, but then we would have extra stairs and slabs to deal with. Another item could be used for making/being furniture, but that is beyond the scope of this issue.

**Comment by paramat** [comment]
Discussion http://irc.minetest.ru/minetest-dev/2015-08-13#i_4364304
