### ISSUE TITLE
[Feature Request] Better Cactus

### ISSUE THREAD

**Issue by LINUXFREEAK** [minetest/minetest_game#584]
Why not add a better Cactus like the one from default plus mod from BlockMen (Thank you BlockMen!)?
 
This is my edited version for the default (nodes.lua, line 748)

```lua
minetest.register_node("default:cactus", {
	description = "Cactus",
	tiles = {"default_cactus_top.png", "default_cactus_top.png", "default_cactus_side.png"},
	is_ground_content = true,
	groups = {snappy=1,choppy=3,flammable=2},
	sounds = default.node_sound_wood_defaults(),
	drawtype = "nodebox",
	paramtype = "light",
	paramtype2 = "facedir",
	damage_per_second = 1,
	node_box = {
		type = "fixed",
		fixed = {{-7/16, -0.5, -7/16, 7/16, 0.5, 7/16}, {-8/16, -0.5, -7/16, -7/16, 0.5, -7/16},
			 {7/16, -0.5, -7/16, 7/16, 0.5, -8/16},{-7/16, -0.5, 7/16, -7/16, 0.5, 8/16},{7/16, -0.5, 7/16, 8/16, 0.5, 7/16}}
	},
	selection_box = {
		type = "fixed",
		fixed = {-7/16, -0.5, -7/16, 7/16, 0.5, 7/16},
				
	},
	on_place = minetest.rotate_node
})
```

And here the new Textures (from dplus too (by BlockMen, WTFPL)):
![default_cactus_side.png](http://i.imgur.com/xrbSB0u.png)![default_cactus_top.png](http://i.imgur.com/rAW5LxM.png)
default_cactus_side.png, default_cactus_top.png

And maybe add a damage sound for it (like in dplus).

**Comment by PilzAdam** [comment]
I don't like making the cactus smaller than regular nodes.

**Comment by LINUXFREEAK** [comment]
okay but the damage?

**Comment by PilzAdam** [comment]
See #299. There is not good way to make cacti deal damage.

**Comment by paramat** [comment]
-1. Nodeboxes can't have smooth shading and would prevent the large branched cacti that will be added to mgv5/mgv7 biomes.

**Comment by tenplus1** [comment]
If you want the cactus to hurt use my PlayerPlus mod: https://github.com/tenplus1/playerplus

**Comment by LINUXFREEAK** [comment]
Okay.
