### ISSUE TITLE
Regression: get_all_craft_recipes() missing output numbers

### ISSUE THREAD

**Issue by jhcole** [minetest/minetest_game#591]
In the lua_api, the table returned by get_all_craft_recipes() is missing output quantities on the returned itemstack. This breaks unified_inventory and other mods that use this function. For example, a call like

    minetest.get_all_craft_recipes('default:wood')

returns

    {
        {
            items = {
                "default:tree"
            },
            type = "normal",
            output = "default:wood",
            width = 1
        }
    }

However, in stable-0.4 it returns

    {
        {
            items = {
                    "default:tree"
            },
            type = "normal",
            output = "default:wood 4",
            width = 1
        }
    }

**Comment by est31** [comment]
Most likely caused by 03e0dd33a847a83d975282c6caf6b926306e7b57, will write a fix.

**Comment by est31** [comment]
This is the wrong issue tracker, please open one on https://github.com/minetest/minetest/issues.

**Comment by jhcole** [comment]
Thanks for the fix est31, its working correctly now. :)

Sorry for posting the issue on the wrong tracker. I guess I was too tired.

**Comment by est31** [comment]
No big deal, thanks again for nailing down the issue.
