### ISSUE TITLE
Difficulty to jump over a node covered with a snow layer

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest_game#599]
The snow nodebox has been thicken up since https://github.com/minetest/minetest_game/commit/cbea61e8ddda29cfd539db8cc51419564dd1a9e4 ¹ And now it's really a pain to jump over a node (e.g. dirt, snowblock, leaves) covered with those thick layers.

Currently mgv6 is exempted of this snow layering on the ground, but mgv5 and mgv7 will have that very soon and some mods use extensively them as well.

¹ *which was merged without a 2nd approval, like pretty much of the latest paramat's commits.*

**Comment by Ekdohibs** [comment]
@kilbith: it *had* too approvals, mine and paramat's.

**Comment by Ekdohibs** [comment]
@kilbith: it *had* two approvals, mine and paramat's.

**Comment by Ekdohibs** [comment]
Also, I just checked jumping on those nodes, and I wasn't able to see any problems with it.

**Comment by kilbith** [comment]
Ah yes, I wasn't aware of your recent nick change. But most of the previous commits in the chronology doesn't have a 2nd approval and this habit tends to be tortious.

**Comment by paramat** [comment]
Will check this, do you mean a problem jumping up a vertical distance of 1.25 nodes instead of 1.125?

**Comment by kilbith** [comment]
>  do you mean a problem jumping up a vertical distance of 1.25 nodes instead of 1.125?

Yes, exactly. I have to retry jumping several times for succeed.

**Comment by kilbith** [comment]
I'll close it. It'd not cause a big issue in the absolute since the ground is leveled up as well (the height is kept to 1.0).

**Comment by 0-afflatus** [comment]
@kilbith - a tort is a wrongful act resulting in injury to another's person, property, or reputation. Pushing through a set of changes which are of great benefit to a computer game can hardly be described as 'tortious'. That's a big heavy accusation which is completely out of place here.
