### ISSUE TITLE
Door duplication bug

### ISSUE THREAD

**Issue by wischi-chr** [minetest/minetest_game#609]
1. Place a door.
2. rip the lower and the upper half appart (for example with pistons)
3. open/close the door-parts
4. there are now two brand-new doors

https://www.youtube.com/watch?v=f4hc8jGQgoU

So solve this, the upper half should vanish (instead of repairing itself).

btw this must not be solved by changing the mesecon/piston code, because the door mod should be able to handle partially obstructed doors (which it does when they are not used before digging)

**Comment by PilzAdam** [comment]
Shouldn't this check already do this: https://github.com/minetest/minetest_game/blob/master/mods/doors/init.lua#L132 ?

Btw, the mesecon mod should properly dig the nodes instead of just removing them, so the proper callback functions get called.

**Comment by wischi-chr** [comment]
Found the problem: http://www.lua.org/pil/3.5.html
"not" is executed before the identity operator which than is false every time.
