### ISSUE TITLE
Junglewood texture too light, boring

### ISSUE THREAD

**Issue by VanessaE** [minetest/minetest_game#611]
Please, switch back to the older, darker jungle wood texture.  The newer, lighter one just looks boring.  It has almost no contrast against the other wood textures, and at least one mod (building_blocks) expects it to be dark (to make "hardwood").  

Existing worlds with junglewood-based structures are also negatively affected by such a drastic color change.

It also effectively broke all texture packs that had jungle wood in them, because they surely also used a dark color. HDX for example has a dark, slightly reddish jungle wood.  Dreambuilder kept the darker color, also.

The old image:  

![](https://raw.githubusercontent.com/minetest/minetest_game/c2ce3d032e4483e0e3f6d078e4de9fa0a68ed459/mods/default/textures/default_junglewood.png)

**Comment by RHRhino** [comment]
Yeah I'm also for a darker (jungle-)wood texture. Currently we only have light wood textures. IMO it doesn't matter if the jungle texture is darker or another wood, but we need at least one that is darker.
:+1:

**Comment by C1ffisme** [comment]
I think I also like it too. See, jungle wood looks rather rotten and old, and dark jungle wood helps with that characteristic, it's a good material if you want to build a witch hut or long uninhabited house.

**Comment by PilzAdam** [comment]
:+1: I like my old texture, never understood why it was made so light.

**Comment by kilbith** [comment]
My proposal : ![default_junglewood](https://cloud.githubusercontent.com/assets/7883281/9140571/84f479e8-3d32-11e5-993d-bd55974d8418.png)

![woods](https://cloud.githubusercontent.com/assets/7883281/9140661/1d4a768e-3d33-11e5-964e-4832f10cee57.png)

**Comment by VanessaE** [comment]
+1 for your proposed jungle wood, kilbith.

**Comment by tenplus1** [comment]
+1

**Comment by rubenwardy** [comment]
+1

**Comment by paramat** [comment]
![default_junglewoodold](https://cloud.githubusercontent.com/assets/3686677/9145273/1663fa6c-3d4b-11e5-9be7-2ed366278381.png)

![1d4a768e-3d33-11e5-964e-4832f10cee57](https://cloud.githubusercontent.com/assets/3686677/9145295/2c0572d8-3d4b-11e5-8d73-16e9606577f2.png)

Above is the old texture enlarged, kilbith i prefer the hue of your texture to the old hue, please could it be a little darker to match in darkness?

**Comment by kilbith** [comment]
Better ?

![2015-08-07-224345_1280x800_scrot](https://cloud.githubusercontent.com/assets/7883281/9145577/d35fee5a-3d55-11e5-8b44-55aa7a2f6f7d.png) ![default_junglewood](https://cloud.githubusercontent.com/assets/7883281/9145550/8d8dc014-3d55-11e5-9d26-2c76abafcb35.png)

**Comment by RHRhino** [comment]
:+1:

**Comment by VanessaE** [comment]
:+1:

**Comment by CraigyDavi** [comment]
:+1: for @kilbith's textures

**Comment by Dragonop** [comment]
+1 for @kilbith's textures, those look nicer and will have more uses when you try to match different wooden planks on a building.

**Comment by paramat** [comment]
Looks good.

+1 i support returning to a darker texture.

**Comment by PilzAdam** [comment]
The junglewood tree textures needs to be tweaked. Currently the tree texture is rather light.

**Comment by kilbith** [comment]
I took the Gambit's patterns as base and changed the colors. Feedbacks ?

![2015-08-08-114422_1280x800_scrot](https://cloud.githubusercontent.com/assets/7883281/9149951/1506b52e-3dc3-11e5-9b8d-90ec1d3e566e.png) ![2015-08-08-114425_1280x800_scrot](https://cloud.githubusercontent.com/assets/7883281/9149952/1899c41a-3dc3-11e5-8fae-5cbd977ff62f.png) ![default_jungletree](https://cloud.githubusercontent.com/assets/7883281/9149953/22d02050-3dc3-11e5-995e-86b72f868931.png) ![default_jungletree_top](https://cloud.githubusercontent.com/assets/7883281/9149956/298720d8-3dc3-11e5-9507-74baae690435.png)

**Comment by PilzAdam** [comment]
@kilbith That looks too much like the normal trees. IMO this greenish stuff on it should be preserved.

**Comment by VanessaE** [comment]
When asked about it, @celeron55 said the outside bark of the tree is based on some generic intertwined-looking tropical trees he saw in a photo, if I remember correctly.  @Zeno- and I checked into it further based on what c55 said, and came up with "strangler fig" as the correct model, which case the current bark is just fine.

Only the top/core of the trunk should be changed, if at all.  @kilbith I think you're on the right track in that regard, but definitely keep the bark the way it already is.

**Comment by kilbith** [comment]
OK, what about this : ![default_jungletree_top](https://cloud.githubusercontent.com/assets/7883281/9150449/437ba1ec-3dd9-11e5-86c7-6cf7d787f211.png)

Before / after
![2015-08-08-141258_1280x800_scrot](https://cloud.githubusercontent.com/assets/7883281/9150416/de9b78b6-3dd7-11e5-955c-246190782d66.png) ![2015-08-08-142344_1280x800_scrot](https://cloud.githubusercontent.com/assets/7883281/9150445/31a638e2-3dd9-11e5-9290-d98c81174c71.png)

**Comment by VanessaE** [comment]
Make it a bit darker, add a bit more red to the already brownish parts?

**Comment by LazyJ** [comment]
+1 for returning a dark colored wood option to the default game. The contrast is needed.

Below, I've changed the trunk's core to a darker color, lightened the ring of pixels around the core and left the outer ring/bark as-is.

16x16 versions:
Current Default / Proposed Change
![Current Default Jungletree Top - 16x16](http://i.imgur.com/mat2fiP.png)   ![Change - Darker Core - 16x16](http://i.imgur.com/9sCgCsO.png)


126x126 versions *(to see easier in GitHub post)*:
Current Default / Proposed Change
![Current Default Jungletree Top - 126x126](http://i.imgur.com/ii3hRov.png)   ![Change - Darker Core - 16x16](http://i.imgur.com/Bilkaub.png)

**Comment by VanessaE** [comment]
@LazyJ, I'd say somewhere halfway between those two.

**Comment by kilbith** [comment]
This chocolate-y wood core wrapped in that pinkish ring is absolutely awful. That's probably the worst wood texture I ever seen.

**Comment by JBBgameich** [comment]
Yes this texture for the trunk is good, but we could look at the texture from the 0.4.9 again too. It's darker too.

On 8. August 2015 20:29:05 MESZ, LazyJ <notifications@github.com> wrote:
>+1 for returning a dark colored wood option to the default game. The
>contrast is needed.
>
>Below, I've changed the trunk's core to a darker color, lightened the
>ring of pixels around the core and left the outer ring/bark as-is.
>
>16x16 versions:
>Current Default / Proposed Change
>![Current Default Jungletree Top -
>16x16](http://i.imgur.com/mat2fiP.png)   ![Change - Darker Core -
>16x16](http://i.imgur.com/9sCgCsO.png)
>
>
>126x126 versions *(to see easier in GitHub post)*:
>Current Default / Proposed Change
>![Current Default Jungletree Top -
>126x126](http://i.imgur.com/ii3hRov.png)   ![Change - Darker Core -
>16x16](http://i.imgur.com/Bilkaub.png)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/minetest/minetest_game/issues/611#issuecomment-129032432

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by paramat** [comment]
I feel we should not change the bark at all, just change the 'tree top' texture and change the core only. The core does need to be the same hue and slightly lighter than the plank texture.
LazyJ your core is too dark, if anything the core should be slightly lighter than the planks, as treated planks tend to be darker than the orginal wood.

![1899c41a-3dc3-11e5-8fae-5cbd977ff62f](https://cloud.githubusercontent.com/assets/3686677/9153202/3eba2888-3e40-11e5-9c44-b7cde4040c5e.png)

@kilbith the core of this one plus an exact copy of the bark edge pixels is fine. The ring of pixels inside the edge pixels could be the ones from your second submission:

![31a638e2-3dd9-11e5-9290-d98c81174c71](https://cloud.githubusercontent.com/assets/3686677/9153213/0d1a33e4-3e41-11e5-94a2-d4fa2f79742c.png)

as a transition from light bark to dark core. But no pressure to make a texture if you're not inspired to make it, i'm happy to do it myself =)

**Comment by LazyJ** [comment]
Giving it another go with a lighter core color. I do like growth rings in the texture more than the cross-like pattern in from the 0.4.9 *(and earlier)* days. The orange tinted core seems repetitive with the other orange in the new, default, acacia tree trunks.

16x16 versions:
Current Default / Proposed Change
![Current Default Jungletree Top - 16x16](http://i.imgur.com/mat2fiP.png)   ![Change - Darker Core - 16x16](http://i.imgur.com/HtL8Fre.png)


126x126 versions *(to see easier in GitHub post)*:
Current Default / Proposed Change
![Current Default Jungletree Top - 126x126](http://i.imgur.com/ii3hRov.png)   ![Change - Darker Core - 126x126](http://i.imgur.com/fabwiRF.png)

And a screenshot to see how it looks in as a part of the complete jungletree:
![Jungletree Forest](http://i.imgur.com/dR9CO4l.png)

**Comment by paramat** [comment]
Looks good to me LazyJ.

**Comment by kilbith** [comment]
LazyJ's texture is awkwardly so wrong... None of the wood logs on earth are so dark and coffee-ish. Instead, a wood is getting darker after cut and drained of its water. Plus this core is completely discordant with the cambium-layer and the bark hues.

_Photo taken in the Brazilian jungle..._
![11078835-truck-carrying-wood-logs-sawed-in-the-jungle-deforestation](https://cloud.githubusercontent.com/assets/7883281/9154177/e48a48a4-3e83-11e5-8335-6b3fd7acb750.jpg)

@paramat Go ahead and tweak yourself the current jungle log texture, this is the wisest option.

**Comment by paramat** [comment]
Yeah the core could be a little lighter, it's almost darker than your new plank texture, if anything it should be lighter.
If our jungle tree node is indeed a strangler fig wrapped around another tree, that gives us the freedom to have a light green fig around a much darker host tree.

**Comment by paramat** [comment]
![strangled](https://cloud.githubusercontent.com/assets/3686677/9154862/f0967c46-3e9a-11e5-9976-84a8758d5c61.png)

![index](https://cloud.githubusercontent.com/assets/3686677/9154865/f4aa5e1a-3e9a-11e5-8f6a-964c058489f0.jpeg)

At top is the jungle tree texture enlarged with interpolation, it looks like a light-coloured strangler plant wrapped around a darker host tree. The inner ring of the tree top texture can therefore be the bark of the host tree.

**Comment by kilbith** [comment]
... is the reason why I re-propose again a variant of the Gambit's texture : 

![2015-08-08-114425_1280x800_scrot](https://cloud.githubusercontent.com/assets/7883281/9149952/1899c41a-3dc3-11e5-8fae-5cbd977ff62f.png) ![default_jungletree_top](https://cloud.githubusercontent.com/assets/7883281/9149956/298720d8-3dc3-11e5-9507-74baae690435.png)

**Comment by LazyJ** [comment]
In this round - the original bark *(no lightened ring, 2px around the core)* with a slightly lighter core than my previous one.

16x16 versions:
Current Default / Proposed Change
![Current Default Jungletree Top - 16x16](http://i.imgur.com/mat2fiP.png)   ![Change - Darker Core - 16x16](http://i.imgur.com/lTq6dbH.png)


126x126 versions *(to see easier in GitHub post)*:
Current Default / Proposed Change
![Current Default Jungletree Top - 126x126](http://i.imgur.com/ii3hRov.png)   ![Change - Darker Core - 126x126](http://i.imgur.com/wpvcOqd.png)

And a screenshot to see how it looks as a part of the complete jungletree:
![Jungletree Forest](http://i.imgur.com/djjxQV8.png)

**Comment by kilbith** [comment]
:-1: The more you're shoveling down in this track, the more you sink in the quaintness.

**Comment by VanessaE** [comment]
How about this?
![image](https://cloud.githubusercontent.com/assets/1733537/9157339/16a95458-3ec8-11e5-93e2-3332dc91d6f6.png)
![image](https://cloud.githubusercontent.com/assets/1733537/9157343/51d7990e-3ec8-11e5-9255-be84e055361b.png)



That's the central part of @LazyJ's image overlayed onto the upstream one, 58 percent opacity, "grain merge" mode.

**Comment by VanessaE** [comment]
![image](https://cloud.githubusercontent.com/assets/1733537/9157358/add24ede-3ec8-11e5-92e1-251d9a458f24.png)   ![image](https://cloud.githubusercontent.com/assets/1733537/9157543/d054a7d4-3ecf-11e5-9d85-9bfde7657b9d.png)

![image](https://cloud.githubusercontent.com/assets/1733537/9157360/b41273f0-3ec8-11e5-9305-b77856b5f64a.png)   ![image](https://cloud.githubusercontent.com/assets/1733537/9157544/e22acfba-3ecf-11e5-8b5f-57b79171af1a.png)

Another try.  existing overlaid onto @LazyJ's, grain merge at 58% opacity, this time with the color saturation turned down on his "brown" layer.

**Comment by Sokomine** [comment]
+1 to VanessaEs last suggestion
Most important part of this issue: Bring back the old dark wood (planks) texture! We need that contrast.
If possible, please also keep the new junglewood texture as an alternative. It could come from a diffrent type of tree - a new one. Wood is a good way to supply players with materials to construct things with. Diffrent colors enrich the game considerably.
I'd love to get junglewood in the original old hue plus the new hue klibith suggested plus the old junglewood plus a dark reddish-brown hue. That gives players far more options to compose their structures.
As for the tree top: In general, that's really less often used by players, so changing it ought to have less impact than with other textures. As the jungletrees have additional roots, a tree top that works as the top of a root node is also important.
As a request for the future: Improve textures, add new ones (new hues are also welcome) - but do not change the hue and general impression of existing textures as that breaks buildings. In the case of junglewood, it's mostly repair work to turn it back to the original.

**Comment by paramat** [comment]
![d35fee5a-3d55-11e5-8b44-55aa7a2f6f7d](https://cloud.githubusercontent.com/assets/3686677/9160133/cdfca89e-3f2c-11e5-83d6-0247a5a8940e.png)

![e22acfba-3ecf-11e5-8b5f-57b79171af1a](https://cloud.githubusercontent.com/assets/3686677/9160135/d2589a42-3f2c-11e5-818b-4d9a8bb28a70.png)

I like VanessaE's second submission, and kilbith's darker plank texture, i will try to get approval from another mtgame dev for this pair.

**Comment by paramat** [comment]
I like the core of VanessaE's latest texture, but would like to edit the inner ring layers to suggest a strangler fig around a dark-barked host tree. Outer pixels are the fig, inside that the bark matching the dark pixels here:

![f0967c46-3e9a-11e5-9976-84a8758d5c61](https://cloud.githubusercontent.com/assets/3686677/9164241/48548abe-3f44-11e5-8145-83b1aedda4b9.png)

**Comment by kilbith** [comment]
I don't know why are you obsessed with this dark brown core... It looks so unnatural. Also who said it's a fig ? Tons of tropical trees species have lianas. All that reveals your low-deep knowledge of nature...

**Comment by paramat** [comment]
No i'm not obsessed, it could perhaps be a little lighter to account for darkening from exposure and any surface treatment of the planks, however the core should be somewhat similar to the planks.
Maybe i should attempt this texture myself..
Yes sure it could be another large-stemmed liana, i don't mean to insist on a strangler fig.
Correct i don't have much knowledge of nature, what you write is rather abrasive.

**Comment by kilbith** [comment]
(Note : I talked about "you" in plural form)

Also I'm repeating myself but...

> however the core should be somewhat similar to the planks

A wood is getting darker after cut and drained of its water, only.

**Comment by celeron55** [comment]
In case people are wondering what the original textures represented in 0.3.x, I can answer because I designed them. They are based on something like the photo paramat linked a day ago, but with less solid wood and more and bigger strangler plants. It's meant to be as jungle as it can get.

**Comment by paramat** [comment]
Sorry kilbith, i took it too personally.

**Comment by paramat** [comment]
![default_jungletree_top128](https://cloud.githubusercontent.com/assets/3686677/9181883/53df3b80-3f9f-11e5-9886-2b596562cdb3.png) The original textyre

![default_jungletree_top128_int](https://cloud.githubusercontent.com/assets/3686677/9181890/591aac92-3f9f-11e5-9770-d813f5871a61.png) Enlarged with interpolation

celeron55 reading your comment i see it now, all this time i thought the black areas was dark wood running through a square trunk, the black is empty space around a small central trunk.
On IRC http://irc.minetest.ru/minetest-dev/2015-08-10#i_4359359 celeron55 > "well i prefer whatever is the most faithful to the original because it's one of the textures i used some time actually designing".
Perhaps we should consider returning to this original texture, as it is designed to match the side texture. we could maybe tint the central trunk to a medium brown to be a little closer to the plank texture (but not as dark).

**Comment by VanessaE** [comment]
![image](https://cloud.githubusercontent.com/assets/1733537/9182232/984b6802-3f77-11e5-8bdf-93c807ad46c4.png)
![image](https://cloud.githubusercontent.com/assets/1733537/9182238/9f71b906-3f77-11e5-884d-9f2a994934ab.png)

A combination of my previous effort and the original 0.3.x texture @paramat  just posted.

**Comment by paramat** [comment]
Wow that was quick.

**Comment by VanessaE** [comment]
:smile:

**Comment by kilbith** [comment]
Oh my...

**Comment by VanessaE** [comment]
Realized right after I posted that image that it needed more work - needed a flip-X, some antialiasing, and more color adjustment to the stranglers.  Result:
![image](https://cloud.githubusercontent.com/assets/1733537/9183273/2068d112-3f7c-11e5-88f8-8b8187a76ed2.png)
![image](https://cloud.githubusercontent.com/assets/1733537/9183280/27659e78-3f7c-11e5-931e-344eb3b247cb.png)

**Comment by kilbith** [comment]
![27659e78-3f7c-11e5-931e-344eb3b247cb](https://cloud.githubusercontent.com/assets/7883281/9184992/0ef5cc18-3fb9-11e5-849c-09679182dd4b.png)

**Comment by VanessaE** [comment]
If you don't like it, you're free to use your own texture pack.

**Comment by paramat** [comment]
This thread is becoming epic. I found myself liking PilzAdam's original darker junglewood texture and attempted a close match in 4-panel form, it turned out slightly darker and richer:

![1663fa6c-3d4b-11e5-9be7-2ed366278381](https://cloud.githubusercontent.com/assets/3686677/9186802/2cb0c9b2-3fc1-11e5-935b-8887c9ab916f.png) PilzAdam's original

![default_junglewood_bn127_cp12_ind128](https://cloud.githubusercontent.com/assets/3686677/9186807/3dcdce3e-3fc1-11e5-8d50-5acf6f46b166.png) My submission

I will probably attempt the tree top texture also.

**Comment by kilbith** [comment]
For comparison with mine
![3dcdce3e-3fc1-11e5-8d50-5acf6f46b166](https://cloud.githubusercontent.com/assets/7883281/9192518/134c91cc-400c-11e5-8465-00af11ece24b.png) ![d35fee5a-3d55-11e5-8b44-55aa7a2f6f7d](https://cloud.githubusercontent.com/assets/7883281/9192521/16fb8a76-400c-11e5-9aa6-b7a045d5c9f2.png)
What about a poll on the forum ?

**Comment by paramat** [comment]
Nah it's best decided by devs and those deeply involved in dev.
I will work on a tree top texture later.

**Comment by VanessaE** [comment]
b7a1426b42de743d07d845086f9f86f4ac845786 (by paramat)
