### ISSUE TITLE
Use the lighter moretrees pine needles texture

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#637]
![bd21da62-769b-11e4-98d8-0d9deec26ed9](https://cloud.githubusercontent.com/assets/3686677/9294413/907349d4-4444-11e5-86c7-923e7ecf6964.png)

^ Moretrees texture by VanessaE derived from Cisoun's texture

![24e31b4e-769b-11e4-94a6-433cba75f362](https://cloud.githubusercontent.com/assets/3686677/9294439/7620b020-4445-11e5-8a77-c117dadcb87b.png)

^ The current texture, Cisoun's original

Before pines are released as stable i would like to use a more realistic texture.
As VanessaE has commented pine needles are not that dark.

**Comment by sfan5** [comment]
:-1: the greener ones don't look that good in pine forests IMO

**Comment by C1ffisme** [comment]
What about blue spruce trees? Those exist.

And the originals provide a nice contrast with the snow.

**Comment by nerzhul** [comment]
:-1: too, pine are dark

**Comment by ExeterDad** [comment]
Pine are dark, but much lighter then most all conifers. I grew up in Washington State (the evergreen state) in the mountains. Not so many pines in my area, mostly Douglas Fir and Nobels. I would always marvel the lighter contrast of a Pine when I came across one.
I feel the lighter one is more accurate representation of a pine.

**Comment by VanessaE** [comment]
I'm okay with either one, however, pine needles are rather light in real life.  Compare for example, the texture used in HDX:

![image](https://cloud.githubusercontent.com/assets/1733537/9295069/a35b5976-442e-11e5-87a3-5f51133cdcb8.png)

**Comment by kilbith** [comment]
:-1:

**Comment by everamzah** [comment]
Greetings from the Pine Tree State.  They're every shade of green, here.

**Comment by C1ffisme** [comment]
Realism doesn't have to matter. I think the new leaves look too flashy and bright for leaves in a forest. Besides that, they are shaded by snow.

**Comment by Ekdohibs** [comment]
I like the darker ones better too.

**Comment by paramat** [comment]
Okay closing.

**Comment by 0-afflatus** [comment]
Sure, pine needles are lighter, but your pine trees look more like firs to me.

**Comment by ShadowNinja** [comment]
I think a lighter texture would be good, the one presented here is just *too* light.
