### ISSUE TITLE
Boats attach bug

### ISSUE THREAD

**Issue by Rui914** [minetest/minetest_game#643]
http://youtu.be/RNuPyn_Qtfo

**Comment by wilkgr76** [comment]
Easiest way to do a boat race :)
Could you add more off a description than just a link to youtube?

**Comment by Rui914** [comment]
Operate the 2 boats by when right-click on another boat in riding boat.
(I'm not good at English...)

**Comment by wilkgr76** [comment]
Thanks! I was able to replicate this in 0.4.13.
