### ISSUE TITLE
Creative inventory bug

### ISSUE THREAD

**Issue by RHRhino** [minetest/minetest_game#646]
I guess this is not the way how the creative inventory should work:
1) put item A in your inventory
2) take item B from creative inventory
3) place item B on top of item A instead of an empty slot
=> item A replaced item B in the creative inventory and you have another stack of item A 

![screenshot_20150822_135440](https://cloud.githubusercontent.com/assets/6941454/9423847/3275b9f2-48d6-11e5-9834-6323a47e0d82.png)
![screenshot_20150822_135447](https://cloud.githubusercontent.com/assets/6941454/9423848/357d1212-48d6-11e5-9ffd-d7c11ab3b965.png)
![screenshot_20150822_135452](https://cloud.githubusercontent.com/assets/6941454/9423849/3ac275b4-48d6-11e5-8ebf-f5814a490d93.png)
![screenshot_20150822_135500](https://cloud.githubusercontent.com/assets/6941454/9423850/4410ac80-48d6-11e5-8582-40cfb9270ccf.png)

**Comment by Rui914** [comment]
https://github.com/minetest/minetest/pull/3081
Perhaps it's fixed.

**Comment by RHRhino** [comment]
Oh it's an engine bug I updated to latest minetest and it works fine for me now. Thx @Rui914
