### ISSUE TITLE
Schematic tree trunks destroy existing nodes

### ISSUE THREAD

**Issue by mgl512** [minetest/minetest_game#652]
Plant some trees on a v7 world to use the "new" growing functions that use schematics. Whatever the tree, its trunk nodes will destroy any existing node. The leaves seem to work though: they always preserved existing nodes in my tests.

**Comment by paramat** [comment]
Yes this is intentional, schematics have per-node force-place that prevents the trunk being chopped by nearby leaves of other trees, and prevents the leaves removing nearby trunks of other trees. Also somewhat realistic, a trunk will often grow through and destroy most structures.

**Comment by mgl512** [comment]
I see, thank you. It's realistic between trees and it will make forests look better. But when a tree destroys player nodes, you think it's a bug.

**Comment by Ombridride** [comment]
This is an __very__ dangerous feature !

We noticed this __bug__ in MFF and tried to avoid it... 
Yes, this is a __bug__ (or a very bad feature idea). Players can now destroy protected homes if theey seed sapling near houses, with the default subgame Minetest_game, that's a very bad point !

And... My god... They can destroy unbreakable blocks...

Do you have planned a parameter to "desactivate" this __grief helper__ feature ?

**Comment by LeMagnesium** [comment]
I would also like to add that according to the documentation of `minetest.place_schematic` and the code used to place those new schematic based trees, it should not be placed forcefully. Take a look at [this](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L2232) :

> * `minetest.place_schematic(pos, schematic, rotation, replacements, force_placement)`
    * [...]
    * `force_placement` is a boolean indicating whether nodes other than `air` and
      `ignore` are replaced by the schematic

And then consider [this](https://github.com/minetest/minetest_game/blob/master/mods/default/trees.lua#L374):

> 	minetest.place_schematic({x = pos.x - 2, y = pos.y - 1, z = pos.z - 2}, path, 0, nil, **false**)

Unless the documentation is unclear about it, **false** would mean there would be no forced replacement of nodes other than air and ignore. Yet, that's what happens, and it can destroy every kind of node, including `default:chest_locked` for example. (note: I'm not the player who placed them)

![Placed locked chests I don't own](https://lut.im/2DMAtBzM/39eQIN45)

![Placing a jungle sapling](https://lut.im/4YRR8HFR/VswD9l0c)

![The chests are destroyed](https://lut.im/LjdHGxHb/yR5jJgsG)

**Comment by paramat** [comment]
Okay we will need to change how schematics work, it won't be easy and mght take some time.

**Comment by paramat** [comment]
I will move mgv5/mgv7 sapling growing into lua code instead of 'place schematic', just like mgv6 sapling-grown trees, this way we can have precise control over what is replaced.

**Comment by paramat** [comment]
> Unless the documentation is unclear about it, false would mean there would be no forced replacement of nodes other than air and ignore. Yet, that's what happens, and it can destroy every kind of node,

That flag is a global force-place flag. Within the schematic lua table itself (see https://github.com/paramat/saveschems) there are node entries for per-node force-place, which are currently set for trunks to replace any node.
Instead of moving trees into lua programs perhaps better to add a 'can replace' field to 'place schematic' that allows defining the nodes (other than air and ignore) that can be replaced. It would be set to group:water and group:leaves.

**Comment by paramat** [comment]
See #659

**Comment by paramat** [comment]
Merged 73113f344340ca75b5a77961d0d2a205566b1fe4
