### ISSUE TITLE
Not enough trees in mgv5/mgv7

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest_game#653]
I missed something or the trees have suddenly disappeared ? I don't see any of them now.

@paramat

**Comment by RHRhino** [comment]
Oh good to know I'm not the only one missing them. I didn't created new maps in the last few weeks (only today), so I can't compare when it changed, but as far as I saw there are only areas with a high density of trees and areas without a single tree in a 1000x1000 node area or even more, except the acacia tree which only appears in low density. :confused:

**Comment by paramat** [comment]
Weird, will test, nothing has changed. Biomes are very big in mgv5/v7 though, it's possible to travel 1000+ nodes without forests.

**Comment by kilbith** [comment]
Nevermind, I did not traveled enough. The trees are still here.

**Comment by RHRhino** [comment]
@paramat: I checked several mgv5/v7 seeds by flying around today and found really lage areas without a single tree. Some of these areas where up to 1000x1000nodes - this shouldn't happen, players need trees, especially if they spawn in these areas. Would it be possible to populate this empty biomes with lonely trees in a very low density. At the moment it seems that there are only high denity forests and empty areas without trees.

**Comment by paramat** [comment]
This is not a bug, but let's keep it open for discussion.

From #515
"Mapgen. Right now, mapgen, is a bit boring (only 4 biomes...), so more biomes and biome-specific resources would make the game more interesting; it would also make the player travel a bit more."

We have mgv6 as a gentle introduction for newbies, mgv7 is intended to be large scale with a sense of adventure, it is not for babies that cry if there are no trees in sight of spawn. Travelling and searching for resources enhances the game, with mgv6 it is not surprising many players stay clustered around spawn. Minetest should not be constrained by expectations formed by Minecraft (spawn and immediately punch wood) or it's baby-scale biomes.

Another reason for the scale is that heat and humidity spreads have been tuned to avoid tiny biomes, the biome size is tuned to the large scale of the mapgen. Inevitably with noise there will sometimes be large areas with no trees.

The biome system is based on our planet's, with areas of  grasslands, deserts and tundra, forests cover just under half of the area in the Minetest system. If trees were everywhere there would be no grassland biomes.

**Comment by PilzAdam** [comment]
@paramat The problem is that you can do basically nothing without wood. If there were other interesting things to do while walking the first 10 minutes then it wouldn't be such a problem.

**Comment by paramat** [comment]
Exploring itself is interesting in mgv7, the landscape is stunning. It makes the search for wood challenging, exciting and a little scary, adding much needed adventure to the game.

**Comment by FreeLikeGNU** [comment]
start player with some saplings
player plants trees if needed
???
profit!

**Comment by LNJplus** [comment]
I don't think that the player should have start items.

If you haven't fast move or fly privileges it is really hard to reach another biome, so I think the biomes should be SMALLER! (I had to do this on my server, because it's for me not playable so)

**Comment by paramat** [comment]
I'm beginning to agree they sometimes get a little too large. I'm considering reducing the spreads back to 750 as tey were before and reducing persistence to 0.4, to reduce the amount of small-scale variation, however ths means less interesting shaped biomes.

**Comment by paramat** [comment]
See https://github.com/minetest/minetest/pull/3152
