### ISSUE TITLE
Flowers don't wave 0/

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#661]
Looks really weird when plant waving is enabled and the flowers are rock-solid.
Not mushrooms obviously.

**Comment by RealBadAngel** [comment]
for the flower waving i think two textures would be needed, i mean here tulip and rose, one with just leaves 2nnd with the flower. otherwise they will look like splitting because of waving

**Comment by paramat** [comment]
Ah of course, the 2 textures of plantlike move independantly, this must be why.

**Comment by kilbith** [comment]
@RealBadAngel Something like that ? (by Gambit)

![screenshot_20150901_111749](https://cloud.githubusercontent.com/assets/7883281/9600438/5e85423e-509b-11e5-8a28-cf535066e66c.png)

Then when dug, we would get the single-flower in hand.

**Comment by paramat** [comment]
Those look better than single flowers to me.

**Comment by paramat** [comment]
We may not need new textures, as i'm workng on the waving motion of plants and have removed the y displacement, so the splitting of a single central flower now only affects the stem and is very subtle. I suggest waiting to see if my changes to waving are merged.

**Comment by RealBadAngel** [comment]
if youre tweakin waving just for flowers you will break grasses, please post your code somwhere and i will make it an option just for flowers

**Comment by kilbith** [comment]
@paramat Can you please stop to edit your comments after minutes/hours from an opinion X to Y ? Post a new comment so that we are notified of your changes of mind or additional infos. Otherwise we are not aware...

**Comment by paramat** [comment]
> if youre tweakin waving just for flowers you will break grasses

My work on waving isn't just to fix flowers, and it doesn't break grasses, both work fine with minimal splitting.

**Comment by RealBadAngel** [comment]
i mean grasses and flowers are not separate drawtypes, you cant fix one without modyfing another at the same time...

**Comment by paramat** [comment]
Ah i see.

**Comment by paramat** [comment]
666 now merged.

**Comment by kilbith** [comment]
You're unmasked, satanist !
