### ISSUE TITLE
[Feature Request] More Fences (for every kind of wood)

### ISSUE THREAD

**Issue by LNJplus** [minetest/minetest_game#663]
I already started a forum topic [here](https://forum.minetest.net/viewtopic.php?f=3&t=13162).
At the moment nobody has disagreed to that.
So now is the question what the devs say.

Here is the recipe (of course insert the right wood type. I DON'T want more sticks):
![](http://wiki.minetest.net/images/thumb/e/e6/Wooden_Planks.png/64px-Wooden_Planks.png)![](http://wiki.minetest.net/images/thumb/a/aa/Stick.png/64px-Stick.png)![](http://wiki.minetest.net/images/thumb/e/e6/Wooden_Planks.png/64px-Wooden_Planks.png)
![](http://wiki.minetest.net/images/thumb/e/e6/Wooden_Planks.png/64px-Wooden_Planks.png)![](http://wiki.minetest.net/images/thumb/a/aa/Stick.png/64px-Stick.png)![](http://wiki.minetest.net/images/thumb/e/e6/Wooden_Planks.png/64px-Wooden_Planks.png)

So I think this fences we need: Wooden Fence, Jungle Wood Fence, Pine Wood Fence, Acacia Wood Fence!

EDIT:
Oh and I think that you should get six fences.

**Comment by paramat** [comment]
+1. There was a PR by sfan5 #297 although i'm not sure about moving to another mod or the stone fences. How about just the 4 woods for now in default mod?

**Comment by LeMagnesium** [comment]
![Wooden Fences](https://lut.im/f5UbDT2t/twIt9O9v)

I've been working on that feature. Fences are automatically declared in a file called `fences.lua` in default mod (file called after nodes.lua of course) using a function called `register_fence`. The craft recipes are also registered according to what was asked in this issue. For any comments and complains, and I know there will be a lot of them, see the pull request #665.

**Comment by sofar** [comment]
#743 implements this.

**Comment by paramat** [comment]
#743 merged.
