### ISSUE TITLE
Writing numbers bug

### ISSUE THREAD

**Issue by Roman3349** [minetest/minetest_game#671]
When I want write the digit in the dialog for connect to the server or create server, so I can not write digit 1, 2, 4, 5, 6, 7 and 8 on the numeric keypad and digit 4 and 7 above the QWERTY keys.

OS: Linux Mint 17.2 x86_64
Minetest: 0.4.13
Language: czech

Sorry for my English.

**Comment by rubenwardy** [comment]
Wrong project, you want https://github.com/minetest/minetest
