### ISSUE TITLE
How to implement permanent fire

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#676]
Following discussion here #191 i would like this feature.
I think it's best as a separate node so it doesn't get scanned by the fire ABMs. We already have permanent torches made from coal, so perhaps permanent fire could be allowed on a coal block for a large and impressive form of lighting? (and for cozy campfires).
If so, how to light a coal block? how about 'using' a torch on it?

**Comment by thatgraemeguy** [comment]
https://github.com/LazyJ/fake_fire may be worth a look.

**Comment by kilbith** [comment]
@thatgraemeguy This mod is badly coded and inefficient. Take a look into the [Home Decor fork](https://github.com/VanessaE/homedecor_modpack/tree/master/fake_fire) which works with no ABMs shit.

**Comment by PilzAdam** [comment]
Permanent fire is different than fake fire. Permanent fire still spreads like regular fire, but never extinguishes.

I am against adding fake fire, thats a mod thing.
The ability to make fire permanent for (other) mods would be good though. I'd suggest making it permanent is param2 has a special value (possibly something that wouldn't collide with facedir, so mods can add different fire nodes while reusing the _game ABM). Fire that is "caused" by permanent fire would be regular, i.e. not permanent.

**Comment by RHRhino** [comment]
How do you put the permanent fire of? Is it a node which can only be placed be the player for decorative use or will it also appear naturally because of mapgen/lave/etc.? The idea of the coal blocks sounds cool, but I would prefer if the fire could also be placed on other nodes than coal blocks, otherwise it has a very limited decorative usage, because you always need a coal block below it. How about if the permanent fire could be crafted out of the coal block by using the torch on it and replaces the coal block? With this behaviour you would lose the coal block to create the permanent fire, but you still have the posibility to place any other block below it.

**Comment by PilzAdam** [comment]
@RHRhino crafting and placing pure fire isn't a good idea. IMO third party mods should set param2 of fire nodes to make it permanent; it shouldn't be in the default game. I'm thinking of mods like nether, that could modify fire to always be permanent in the nether.

**Comment by paramat** [comment]
Flames don't need param2 so we could use that, problem is such a flame would be treated like 'basic flame, and therefore have a sound placed at a quantised location up to 6 nodes away. So we need a separate node, i could add this for use by mods?

**Comment by Ferk** [comment]
Using param2 would still trigger the ABM and be slower.
A separate node that doesn't cause the fire to spread and is used for campfires, chimneys and such would be nice.
We already have torches in default after all.

**Comment by PilzAdam** [comment]
@Ferk what you are describing is "fake fire", not "permanent fire". See my first post on this issue.

**Comment by paramat** [comment]
I'm thinking a separate flame node that is scanned by the water/snow/ice extinguish ABM but not scanned by the 'naturally burning out' ABM. The advantage of having this node in MTGame is that mods can use it without having to add another heavy extinguish ABM of their own. 
PilzAdam do you approve of making this new flame node usable within MTGame as a 'big torch' on a coal block? ignited by some method. Or should it be usable by mods and creative mode only?

**Comment by PilzAdam** [comment]
@paramat for now just add the node. A method to make it usable with only _game can be added later.

**Comment by tenplus1** [comment]
We get around this by adding a fireplace node to the game which you can punch with a torch to produce a safe flame:

```
minetest.register_node("xanadu:fireplace", {
	description = "Fireplace",
	tiles = {"default_cobble.png", "default_stone.png", "default_stone.png"},
	groups = {cracky = 3, stone = 1},

	-- add fire on top when punched with torch
	on_punch = function(pos, node, puncher, pointed_thing)
		if puncher:get_wielded_item():get_name() == "default:torch" then
			local npos = { x = pos.x, y = pos.y + 1, z = pos.z}
			if (minetest.get_node(npos).name == "air") then
				minetest.set_node(npos, {name = "xanadu:safe_fire"})
--				minetest.sound_play("fire_small", {pos=npos})
			end
		end
	end,

	-- remove fire with fireplace
	after_destruct = function(pos, oldnode)
		local npos = { x = pos.x, y = pos.y + 1, z = pos.z}
		if (minetest.get_node(npos).name == "xanadu:safe_fire") then
			minetest.set_node(npos, {name = "air"})
		end
	end,
})

minetest.register_node("xanadu:safe_fire", {
	description = "Safe Fire",
	drawtype = "plantlike",
	tiles = {{
		name="fire_basic_flame_animated.png",
		animation={type="vertical_frames", aspect_w=16, aspect_h=16, length=1},
	}},
	inventory_image = "fire_basic_flame.png",
	light_source = 14,
	groups = {dig_immediate=3, hot=2, not_in_creative_inventory=1},
	drop = "",
	walkable = false,
	buildable_to = true,
	damage_per_second = 2,
})

minetest.register_craft({
	output = "xanadu:fireplace",
	recipe = {
		{"default:cobble", "default:torch", "default:cobble"},
		{"default:stone", "default:glass", "default:stone"},
		{"default:stone", "default:stone", "default:stone"},
	}
})

**Comment by paramat** [comment]
PilzAdam okay i'll work on this.

**Comment by 0-afflatus** [comment]
I use a bonfire node based on the one from stoneage by CasimirKaPazi.
I think this would be a great addition.

**Comment by paramat** [comment]
PR will be merged very soon.
