### ISSUE TITLE
"Regular" trees should be renamed

### ISSUE THREAD

**Issue by Taknamay** [minetest/minetest_game#684]
Now that acacia trees, pine trees, and jungle trees are common, I believe the "regular" trees should have a proper name. Right now it's a little jarring to have four different kinds of trees in your inventory, one of which is "tree."

I suggest apple tree.

**Comment by kilbith** [comment]
I guess you don't have a modder/admin standpoint for envisage all the troubles it brings when you rename so liberally such old fundamental nodes...

Stop change for the sake of change and make the game more enjoyable, instead.

**Comment by t4im** [comment]
Node-descriptions could be renamed without much trouble.

**Comment by Taknamay** [comment]
@kilbith, I don't consider this sake for the sake of change. As I mentioned, this would improve immersion for me.

And I was under the impression that, like t4im said, changing the description of an item won't affect mods. Right?

**Comment by paramat** [comment]
Yes changing the descriptions is fine, unfortunately changing the technical names like 'default:tree' causes too much disruption. +1 for the description 'Apple Tree' or even a specific species.
I spent a few hours trying to find a match for our jungle tree, the dark wood planks suggest wenge or rosewood (guitar fretboard wood).
Pine and acacia are specific species so if we want to be totally consistent we could have species descriptions for apple and jungle tree.

**Comment by asl97** [comment]
the trunk (tree) is use by different mod for different tree, calling it apple tree would force every single mod out there which use it to add their own trunk.

**Comment by Taknamay** [comment]
@asl97, why can't existing mods just use the default trunk?

**Comment by asl97** [comment]
cause it would be call `apple tree` when the tree is, for example, a banana tree.

**Comment by Taknamay** [comment]
Ok, now I understand the issue. I need to think about whether there is a solution to this.

**Comment by cheapie** [comment]
Speaking of mods, this would cause servers with moretrees to have at least two different kinds of "apple tree", only one of which would actually grow apples.

**Comment by paramat** [comment]
Looks like it's best to leave things unchanged.

**Comment by JBBgameich** [comment]
What about naming it mapletree?

On 28. September 2015 20:41:06 MESZ, cheapie <notifications@github.com> wrote:
>Speaking of mods, this would cause servers with moretrees to have at
>least two different kinds of "apple tree", only one of which would
>actually grow apples.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/minetest/minetest_game/issues/684#issuecomment-143838203

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by cheapie** [comment]
@JBBgameich Then we'd have the same problem that was mentioned earlier where trees from some mods would drop "maple tree" when they're not maple trees.

**Comment by JBBgameich** [comment]
Hmm you mean mods like farming_plus?  We could add a default:maple_tree and just generate this nodes in new maps, in old maps or with mods we could use the dafault:tree. So in new maps no default:tree appears.

On 29. September 2015 20:46:37 MESZ, cheapie <notifications@github.com> wrote:
>@JBBgameich Then we'd have the same problem that was mentioned earlier
>where trees from some mods would drop "maple tree" when they're not
>maple trees.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/minetest/minetest_game/issues/684#issuecomment-144153000

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Taknamay** [comment]
@JBBgameich I concur, this was the solution I was thinking of too. Keep the old nodes, but don't spawn their trees in minetest_game by default. Then spawn the new trees which are based on the current tree.

**Comment by JBBgameich** [comment]
Yes, this is good.  support for mods and old maps, but something new and better to. Im translatiNg some of the wiki to german and its hard to find a translation for default tree, standart tree or how to call this unnamed tree.

On 29. September 2015 21:59:49 MESZ, Taknamay <notifications@github.com> wrote:
>@JBBgameich I concur, this was the solution I was thinking of too. Keep
>the old nodes, but don't spawn their trees in minetest_game by default.
>Then spawn the new trees which are based on the current tree.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/minetest/minetest_game/issues/684#issuecomment-144172232

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by 0-afflatus** [comment]
The default trees annoy me. I want my apple trees to look like apple trees. 
So I kind of agree with the sentiment, but for legacy reasons I think Minetest Game is stuck with default:tree and friends.

**Comment by paramat** [comment]
I think there's nothing we can do, any change is not worth the trouble it causes.
