### ISSUE TITLE
If books are too long, other players can't see all the text.

### ISSUE THREAD

**Issue by Amaz1** [minetest/minetest_game#690]
![screenshot_20151002_115913](https://cloud.githubusercontent.com/assets/4390945/10245214/5de715ee-68fd-11e5-968a-00c0f799dccc.png)
That goes on for a bit longer, but as you can see, it gets cut off after Friday, and there is no way of scrolling down to see the rest of it.

I'm not sure if this is fixable from Lua, I had a little go at getting it to work, but I was unsuccessful.

**Comment by paramat** [comment]
There's a PR to fix this, but it needs checking by another dev.

**Comment by kilbith** [comment]
This can be closed now, right ?

**Comment by Amaz1** [comment]
I suppose it can
