### ISSUE TITLE
De-bloating of the inventory (nodebox shapes)

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest_game#697]
There was some concerns of redundance in the inventory when new shapes of materials were desired here : https://github.com/minetest/minetest_game/issues/581

While I understand the need for more shapes, we're braked by the absence of a node that regroups all these shapes and permits to slenderize the inventory.

What I propose as a solution is a work bench or circular saw specialized to cut the materials. I did some work in that direction : https://github.com/kilbith/xdecor/blob/master/worktable.lua

Unlike moreblocks, this cutting system complies with the KISS principle (made of ~170 lines) and its API is really flexible and easy to adapt (even for a beginner).

![687474703a2f2f692e696d6775722e636f6d2f4d303542716a542e706e67](https://cloud.githubusercontent.com/assets/7883281/10277825/17bc1016-6b59-11e5-858f-5e3679ee5f48.png)

Opinions ?

**Comment by PilzAdam** [comment]
I think that this does not belong into minetest_game, since it goes against the voxel principle.

**Comment by kilbith** [comment]
>  it goes against the voxel principle

In which mean(s) exactly ?

**Comment by PilzAdam** [comment]
@kilbith a 1x1x1m cube is supposed to be the smallest unit that the world consists of. I understand that it is in some special cases beneficial to break this principle (e.g. for plants or simple stairs), but this is just too much, since it almost completely invalidates it.

**Comment by kilbith** [comment]
I think there's a misunderstanding of that issue (my bad). The idea is to regroup the stairs / slabs into a dedicated node for "cutting" and hide them from the inventory. The screenie is just a demo.

**Comment by kilbith** [comment]
Not much interest, closing.

**Comment by C1ffisme** [comment]
I think someone should just make all nodes be split into microcubes (eighths) and convert all current worlds. Then we never have to worry about nodeboxes again (or at least, not as majorly as we currently do).
