### ISSUE TITLE
beds: sleepwalking

### ISSUE THREAD

**Issue by heavygale** [minetest/minetest_game#701]
When laying down in a bed while moving the movement doesn't stop.

**Comment by PilzAdam** [comment]
We probably need `set_velocity` for players to fix this.

**Comment by kilbith** [comment]
I'm fairly familiar with this bug. I already prevented it by checking the moving keys during the right-click : https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L2548-L2549

**Comment by PilzAdam** [comment]
@kilbith checking the actual velocity of the player is even better, since you can move without pressing keys. But what should we do if the player is moving while rightclicking bed? Should we just ignore the click? That would be rather unresponsive and the player might get the impression that the bed is not working.

**Comment by kilbith** [comment]
Btw you need [`get_player_velocity`](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L2532) for patching.

**Comment by kahrl** [comment]
Another option could be `set_physics_override` with `speed` set to 0.

**Comment by PilzAdam** [comment]
@kahrl thats what we currently do. The problem is that the current velocity of the player is preserved.

**Comment by kahrl** [comment]
@PilzAdam Arguably that is an engine bug then... One would assume that with `speed` set to 0, the player would stop moving.

**Comment by PilzAdam** [comment]
@kahrl I wouldn't consider it a bug. The speed parameter sets how fast the player can move by holding the movement keys. It does not limit the velocity caused by other factors (e.g. falling or being pushed by things).

**Comment by Sokomine** [comment]
I've encountered that problem with some nodes in my cottages mod as well. It is problematic as the player may drift further away and get out of reach of the node he is sitting/sleeping on, thus making getting up tricky (the nodes there do not serve to skip the night but to set the player animation, so there's no auto-getup after a time).
set_player_velocity on the engine's side would be highly welcome. It could also be used for elevators, escalators, rails and the like.
Checking the player's speed and refusing usage of the piece of furniture in case of too high speed does not always work sufficiently reliably.

**Comment by sofar** [comment]
I'd think that there would be nothing wrong with setting the player speed identical to the entity speed when it is attached. This can be done in builtin or in core?

**Comment by Rui-Minetest** [comment]
How about adding a method like as reset_player_velocity?

**Comment by Wuzzy2** [comment]
In MCL2, I fixed this in a fashion like kilbith suggested.
Check if the player velocity is smaller than a very small number. Only then the player is allowed to sleep. If the player moves, the player cannot go to bed and there will be a message in chat. Not ideal, but better than sleepwalking, and this is a perfectly reasonable workaround as long `set_player_velocity` does not exist.

**Comment by paramat** [comment]
Thanks that sounds good.

**Comment by appgurueu** [comment]
This should be closed now?
