### ISSUE TITLE
New grass texture

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#703]
I tried improving our grass texture but i'm still not happy with it, i don't really know why there's just something sickly about it, i think the original texture was beyond repair and we need a new texture.
I find grass the most difficult texture to create in a texture pack and it is perhaps the most critical to the subgame, being used in many biomes and being probably the most-seen texture. So we need to collect some alternatives and choose carefully.
This could be a chance to make the 'grass side' overlay texture hang down a little more so that the side of hills are not so dominated by dirt.
Gambit's grass should be considered, it may be too bright for most people, perhaps it could be darkened, it also has a side texture that hangs low. Our current long grass textures are by Gambit so there may be some consistency in using it.
I'll start looking around at texture packs and make some screenshots.

Perhaps we could consider a new dirt texture too? i'm not too keen on the current one.

**Comment by nerzhul** [comment]
:+1:

**Comment by PilzAdam** [comment]
Why do we change the grass texture every 2 months? This needs to stop.

**Comment by kilbith** [comment]
> Why do we change the grass texture every 2 months? This needs to stop.

Agreed. Stop messing up like that, this is disturbing.

**Comment by paramat** [comment]
Yes, i'm sorry i thought i could edit the previous texture and make it good, even when it was merged i was still unsure about it.
Grass hasn't changed much more often than other nodes, even if it had that's no excuse to keep a bad texture. So yes sorry for the mess, we need to select more carefully and find a really good one. Perhaps we can start a long process of considering alternatives.

**Comment by cheapie** [comment]
I like the current top texture, but the side does need some work. I personally like the way that Realtest does it, where all faces (except the bottom, possibly) use the top texture. That way, hills actually look like grass, and it's not like you'd see the covered faces anyway.

**Comment by paramat** [comment]
I agree the side grass should hang lower. I personally prefer the sides covered with grass but many players like the classic form of some dirt showing, so perhaps we can have it halfway or a little more?

**Comment by cheapie** [comment]
Halfway or 2/3ish might be good. I'd have to see it to really form an
opinion, though.

**Comment by C1ffisme** [comment]
Grass is pretty hard.

But... Forget about how flat it is, one of the problems of grass is that it never seems to be the right shade of green. I always look at a minetest forest and it just doesn't look... pleasing?... enough.

Now, about the shape. We all know real grass isn't flat. And normalmaps do help with that, but most people can't (or just don't for whatever reason) use them.

@cheapie the all faces idea should be implemented, but the problem is that it might look slightly weird if you are mining. Although that also means it could be used as things such as moss.

**Comment by paramat** [comment]
![screenshot_20151025_001158](https://cloud.githubusercontent.com/assets/3686677/10713263/b5688156-7aad-11e5-8124-7087b88018f3.png)

Gambit's textures darkened by 32 in gimp.

**Comment by C1ffisme** [comment]
That looks really nice. The dirt texture might need to be changed a bit, but that looks just wonderful.

**Comment by cheapie** [comment]
I like it too.

**Comment by paramat** [comment]
![screenshot_20151025_014440](https://cloud.githubusercontent.com/assets/3686677/10713652/2d2db5e2-7aba-11e5-98cb-2d1b599e664e.png)

These are from the Voxelgarden subgame by Casimir.
Edited: brightness -24, hue +6, saturation +16 in Gimp, to be as close as possible to our previous 0.4.10 texture.

**Comment by cheapie** [comment]
Too much dirt showing on those, and there are also those diagonal lines you mentioned.

I do like the lack of yellow on them, though.

**Comment by paramat** [comment]
Yes i prefer less dirt showing too. Maybe i'll lower the grass on the side.

**Comment by nerzhul** [comment]
@paramat the first is better than last image i think, too many grass lost dirt with grass interest it think

**Comment by paramat** [comment]
![screenshot_20151025_214322](https://cloud.githubusercontent.com/assets/3686677/10718098/311c4670-7b62-11e5-8c0a-2ca685a0ee29.png)

Same as the voxelgarden texture above but with a side texture that covers 3/4 of the dirt.
The pattern of the grass 'fringe' is copied from our previous 0.4.10 texture. Translucent shading is added for a slight shadow effect under the fringe.
I tried 'make seamless' in Gimp but that did not fix the dark diagonal lines, i don't find then much of a problem in use.

![screenshot_20151025_214731](https://cloud.githubusercontent.com/assets/3686677/10718109/7962cd3c-7b62-11e5-933a-df7dea0b9a49.png)

**Comment by cheapie** [comment]
Those diagonal lines are still a problem, I think. It looks odd seeing freshly-mowed-looking grass in the middle of a forest like that.

**Comment by paramat** [comment]
Maybe i'll try editing the texture subtly to reduce the line effect.

**Comment by C1ffisme** [comment]
I actually think the bottom of the grass with the dirt not being the actual dirt texture looks really good. Like soft mushy dirt on top of compressed darker dirt.

**Comment by paramat** [comment]
![screenshot_20151118_092959](https://cloud.githubusercontent.com/assets/3686677/11237356/4f2808d4-8dd7-11e5-949b-e5da68764d39.png)

Another random suggestion. Grass from PilzAdam's Nodetopia, with increased colour saturation and a low-hanging side texture. It's single-pixel noise as our current texture but i fiind it easier on the eye.

**Comment by Jordach** [comment]
Paramat, instead of make seamless - try Tilable Blur with 1px pixel radius
and then add a noise layer with 30% overlay - it should look *much* much
better.

**Comment by paramat** [comment]
![screenshot_20151224_182059](https://cloud.githubusercontent.com/assets/3686677/11997124/5e6330ac-aa6b-11e5-8b9e-3dfa04c6a539.png)

Modified Nodetopia texture again, a little less saturation, i have tried to match the brightness and saturation to our previous 0.4.10 texture. Also the side texture extends 3/4 of the way down the side, not quite as far as in the screenshot above.

To make the sides of hills look grassy i feel the new grass texture should extend more than halfway down the side of a node, 3/4 seems the obvious and simplest choice, consistent with how we divide nodes into a quarter-slab for snow nodeboxes.

**Comment by paramat** [comment]
I closed PR #756 so here are sofar's submissions for consideration:
First:

![default_grass]
(http://i.imgur.com/2EPBkRq.png)

![large sample]
(http://i.imgur.com/cxTF2Vq.png)

Second:

![x16]
(http://i.imgur.com/IATn9pB.png)

![x256]
(http://i.imgur.com/O6NRCG9.png)

![preview]
(http://i.imgur.com/d2rer1p.png)

**Comment by paramat** [comment]
![screenshot_20151025_214322](https://cloud.githubusercontent.com/assets/3686677/10718098/311c4670-7b62-11e5-8c0a-2ca685a0ee29.png)

@sofar i really like the voxelgarden texture but it has a noticeable dark diagonal line

**Comment by sofar** [comment]
![x]
(http://i.imgur.com/Ew6ZWqS.png)

Very hard texture to remove the lineations from, this is an initial pass. A lot better, but still very difficult without affecting the overall style of this texture.

**Comment by paramat** [comment]
Thanks, although it does seem to remove much of the character as you state, i prefer the original, really sorry =/

**Comment by sofar** [comment]
Yeah, I'm not that pleased with it either.

**Comment by HybridDog** [comment]
![screenshot_20160113_171051](https://cloud.githubusercontent.com/assets/3192173/12299819/ef6b53e2-ba18-11e5-979e-615339daf701.png)
l'm also not happy with mine.

**Comment by sofar** [comment]
@HybridDog lol! that almost looks like you have enabled texture filtering :)

**Comment by paramat** [comment]
I don't dislike it but it's too smooth to be consistent with other textures.

**Comment by HybridDog** [comment]
It's just the default grass texture smoothed with a normalmap.

**Comment by paramat** [comment]
This is sofar's smooth texture from https://github.com/minetest/minetest_game/issues/703#issuecomment-170385124 plus a side texture:

![screenshot_20160212_071233](https://cloud.githubusercontent.com/assets/3686677/13000918/3c6060c4-d158-11e5-831c-9d7b7ff1a50a.png)

**Comment by kilbith** [comment]
Still incompatible with the tall grasses, meant to work with PixelBOX grass. Not a smoother texture with a completely different palette. No wonder why users are complaining of inconsistency on the forums...

**Comment by sofar** [comment]
Yeah, maybe once we're done with gravel I'll start this one from scratch again.

**Comment by paramat** [comment]
I'm unsure about it too. My favourite still is the voxelgarden texture but i need to work on it to remove obvious lines.

**Comment by paramat** [comment]
I'm considering this a blocker because our current grass is so bad (my fault).

**Comment by kilbith** [comment]
Is that really a high priority or _your_ high priority ? The project can largely live without a new texture...

@PilzAdam Please remove this label.

**Comment by nerzhul** [comment]
texture could not be a high priority

**Comment by 0-afflatus** [comment]
Blockers are things that make the game unplayable. The current texture may not be perfect, but it is playable. I think it would be psychologically healthier to shelve this discussion until someone comes up with a texture that is worthy of a PR. Otherwise we end up in some kind of circular pixel-pushing game.

**Comment by paramat** [comment]
Sorry, removed. I'm only personally seeing it s a blocker.

**Comment by sofar** [comment]
I'll see if I can make some time for this now that we're done with the gravel texture.

**Comment by paramat** [comment]
New PR #1025

**Comment by paramat** [comment]
#1025 is merged.
