### ISSUE TITLE
Is a minimum light level acceptable for sapling growth?

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#704]
For example to match wheat and cotton having a minimum light level of 13 in the 'can grow' function?
Seems wrong to have saplings growing in darkness, they seem to be the only plant that doesn't depend on light level. This would make meselamps, and therefore mese, more useful underground.
Because meselamp is light 14 and torch 13, this means only meselamp would be bright enough placed next to a sapling, this seems right as i wouldn't consider a torch bright enough, this makes mese essential and adds a use for it, instead of lazily using a torch.

**Comment by thatgraemeguy** [comment]
:+1:

**Comment by kilbith** [comment]
Good idea.

**Comment by NathanSalapat** [comment]
+1

**Comment by PilzAdam** [comment]
I generally like the idea, but I'm unsure about your plans that only mese blocks can provide enough light.

**Comment by paramat** [comment]
> Because meselamp is light 14 and torch 13, this means only meselamp would be bright enough placed next to a sapling

I'm not sure if or how light from 2 light sources adds, 2 torches next to the sapling may be enough to reach the threshold of 13, and i'm okay with that. I don't intend that the sapling searches for a meselamp to enable growth.
I do feel the threshold should be 13 though to match wheat and cotton. I'll make a PR.

**Comment by paramat** [comment]
See PR #705

**Comment by paramat** [comment]
Merged.
