### ISSUE TITLE
No Menu Background when Menu_Clouds is False

### ISSUE THREAD

**Issue by LazyJ** [minetest/minetest_game#706]
Minetest Game commit:  c15bd9d

When using "menu_clouds = false" in minetest.conf, the menu background no longer shows as tiled dirt from the **default** texture pack but instead it becomes a solid black background. When using a non-default texture pack, the dirt tile appears after exiting a world.

Process:  Pick a texture pack under the Texture Pack tab, start a world then exit to the main menu.

I've updated this Issue post with some screenshots using new and old texture packs.

This is the default texture pack, selected as "None" under the Texture Pack tab:
![Default/None texture pack](http://i.imgur.com/dOrSpRT.png)

"HDX-512", 2015_10_12 release:
![HDX-512 texture pack](http://i.imgur.com/IVe1jFc.png)

"John Smith"
![John Smith texture pack](http://i.imgur.com/xnh7elT.png)

"MineToon"
![MineToon texture pack](http://i.imgur.com/hIDoeTm.png)

"Misa"
![Misa texture pack](http://i.imgur.com/TsfaJFu.png)

"Summerfields"
![Summerfields](http://i.imgur.com/ZZGLjRH.png)

<path>/minetest_game/mods/default/textures copied to <path>/minetest/textures/ and renamed
![Default textures relocated and renamed](http://i.imgur.com/zc3YvhM.png)

**Comment by red-001** [comment]
This is a minetest bug and not a minetest game bug.

**Comment by paramat** [comment]
Yes.
