### ISSUE TITLE
Use facedir in xpanes

### ISSUE THREAD

**Issue by Ferk** [minetest/minetest_game#707]
I see that the xpanes mod seems to register a new node for every single position and rotation of the pane, instead of using facedir for those positions that could have been done with a rotation of the node.

The problem with this is that it makes fences a node that is not straightforward to rotate. So if they are in a mts schematic, for example, the fences will be completely broken as soon as it's placed with a 90 degrees angle. 

Any chance for this to change?

I realize that this is probably something that might break compatibility if the old fence nodes were replaced, so they would have to be kept to not break previous maps. However, it would be enough to just allow the xpanes to be facedir-aware, so rotation would work for each of the nodes that represent each xpane configuration.

I guess this could be as easy as adding paramtype2 = "facedir" to the register function, but I'm not sure, would it break something? I'll submit a PR if you agree.

**Comment by Sokomine** [comment]
My [url=https://github.com/Sokomine/xconnected/blob/master/init.lua]xconnected[/url] mod requires far less nodes and can be used for a variety of shapes. Due to its usage of far less nodes (6 instead of 15), it's not directly compatible with xpanes, though an abm to convert the nodes ought to work.

**Comment by sofar** [comment]
This is a candidate for LBM replacement.

**Comment by sofar** [comment]
https://github.com/minetest/minetest_game/pull/946

**Comment by Ferk** [comment]
Closing as #946 was merged
