### ISSUE TITLE
The TNT mod does not use obj:punch(), but obj:set_hp()

### ISSUE THREAD

**Issue by C1ffisme** [minetest/minetest_game#708]
This makes it impossible for mobs to run things that are on_punch, such as death sounds, drops, etc. And it's also a bad hack for what can be done with a command specifically designed for this function.

**Comment by red-001** [comment]
@C1ffisme mods expect there to be a puncher, if TNT gets set off by something like mesecons then there is no puncher.

**Comment by C1ffisme** [comment]
@red-001 That's true... Although maybe you could make the puncher ```nil``` or a fake player. I understand cases where this could cause confusion with say, mob item dropping code.
