### ISSUE TITLE
Add a hurt sound

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#715]
Issue for PR #333 which is now closed.
Should be gender-universal.
Not unpleasant to listen to, not too gory, realistic or graphic, slightly amusing might be good, think cartoon sound effects, somewhat abstract like the game itself.

**Comment by paramat** [comment]
Closing for now, this is documented in the TODO list.

**Comment by C1ffisme** [comment]
Document your requirements on the list, though.

```
Should be gender-universal.
Not unpleasant to listen to, not too gory, realistic or graphic, slightly amusing might be good, think cartoon sound effects, somewhat abstract like the game itself.
```

We wouldn't want people to forget these requirements, otherwise we've got a bunch of male, unpleasant, gory, etc. sounds.

Just suggesting.
