### ISSUE TITLE
Adding loot chests to dungeons

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#721]
Something to consider?
Ancient libraries might be good too.
Blockmen is working on a mod https://forum.minetest.net/viewtopic.php?f=9&t=13487

**Comment by RHRhino** [comment]
Would be cool to explore :+1:

**Comment by tenplus1** [comment]
+1 Dungeons need that little something extra

**Comment by kilbith** [comment]
I'd prefer cobwebs in dungeons. Chests/bookshelves are too "civilized" in such abandoned ruins.

**Comment by FreeLikeGNU** [comment]
cluttergen perhaps?

**Comment by FreeLikeGNU** [comment]
@kilbith maybe these dungeons are not abandoned?

**Comment by C1ffisme** [comment]
I would use the bookshelves to hold items called "Ancient Scrolls". These items would be used in crafting recipes to build ancient weapons or tools or machines that would be useful for certain problems that may have been locked to the player. For instance, you could make a room in a dungeon make out of an indestructible material, and you need a golden key (made using the scroll) to open the door and find the secret items in the chest inside. That could seriously increase the adventure level of minetest, as well as adding a use for gold (in the key).

**Comment by C1ffisme** [comment]
Why did this get closed? It's still a valid request, and there was no stated reason in any comment.
