### ISSUE TITLE
Chest-grid and furnace-grid work slower than craft-grid in player inventory

### ISSUE THREAD

**Issue by amadin** [minetest/minetest_game#733]
If you will fast put items in chest or furnace, they often will put with delay but if you will fast put items in craft-grid in player inventory it will work with no delay always. It is trouble for all non-default mods wich add workbench in Minetest, because workbench mods working slow like chest or furnace. So if craft-grid in player inventory work fast, why others grid (from minetest_game and non-default mods) work slow?
Tested on 0.4.12-dev, 0.4.13 stable and 0.4.13-dev on new and clear locale servers, Debian Jessy.

**Comment by JBBgameich** [comment]
I have this problem too. But I dont know how to solve it..

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by PilzAdam** [comment]
This is because movement inside the player inventory is predicted on the client.

**Comment by BlockMen** [comment]
> because workbench mods working slow like chest or furnace

Then use workbench mods that work in a sane way, like my crafting mod. There is no lag/delay...

**Comment by rubenwardy** [comment]
I disagree, this lag is a bug - it should still have client prediction.

**Comment by kilbith** [comment]
> I disagree, this lag is a bug - it should still have client prediction.

https://github.com/minetest/minetest/pull/1988

**Comment by kilbith** [comment]
A maintainer for closing this, please.

**Comment by rubenwardy** [comment]
Issues for PRs shouldn't be closed until the PR is - you end up forgetting things if the PR is declined / stagnated. But maybe this should be on minetest/minetest anyway.

**Comment by kilbith** [comment]
> Issues for PRs shouldn't be closed until the PR is

Which PR ? This can be solved only the engine. Thus such issue should be opened in the engine repo. Period.

**Comment by rubenwardy** [comment]
The PR you linked to?

**Comment by rubenwardy** [comment]
The PR you linked to?
However I agree, this is an engine issue.

**Comment by kilbith** [comment]
No this PR does not handle all situations, I discussed this with sapier. This issue is likely already opened in the engine though.
