### ISSUE TITLE
[Suggestion] Change doors to meshnodes

### ISSUE THREAD

**Issue by C1ffisme** [minetest/minetest_game#738]
Since we've changed stairs to mesh nodes, changing doors would also be a better idea too, in my mind. Not only would we save the rendering of the 4 vertices around the middle of the door, but they would open and close cleaner, and not have to use ABMs, etc. It would also solve every door duplication bug known. And we would only need one node per door, not two.

The only disadvantage I can see is changing old doors into new doors. But, that is fixable by first adding the new doors, then adding an ABM in the version after that, and after that version remove the old doors. This may give problems to those who might upgrade from 0.3.x or 0.4.13 and below going directly to 0.5.0, but we are, after all, removing some mod support. And doors is a mod.

**Comment by Jordach** [comment]
:+1: With this, you could even rotate the door to hang upside down with the
6D facedir. Would look amazing for space station type builds, or for bat
people... ;)

**Comment by 0-afflatus** [comment]
:+1:

**Comment by C1ffisme** [comment]
I'm glad at least one of my suggestions gets a bit of positive comments. Thank you.

**Comment by tenplus1** [comment]
It would also be handy if all doors opened by default (by anyone) and you could use a key tool to LOCK the door for owner only or check for protection and open only for those inside a protected area.  This would save having to re-create doors for each instance.

**Comment by 0-afflatus** [comment]
@tenplus1 :+1:
"This message will self-destruct in ten seconds ..."

**Comment by sofar** [comment]
@tenplus I wrote a modification that adds keys that work for lockable doors and chests, so that may either conflict or suit your needs. 

https://forum.minetest.net/viewtopic.php?f=9&t=13732
https://github.com/sofar/minetest_game/tree/keys

**Comment by sofar** [comment]
I'm tempted to say that this would drastically improve the door code. Currently door code is convoluted and difficult due to the double-node handling code.

**Comment by tenplus1** [comment]
I was thinking of a formspec idea where you could use a key tool on a normal door and lock it to owner, lock to protected or even lock it to shared use...

**Comment by sofar** [comment]
@tenplus1 doors need a good API first, and then it would be trivial to write something like that in a mod.

**Comment by tenplus1** [comment]
agreed, lets hope the meshnodes are the first port of call :)

**Comment by sofar** [comment]
https://github.com/sofar/newdoor

Here's an initial stab at a new door based on mesh nodes.

I'm posting it as a separate mod because right now there's no compatibility or conversion code in place yet, but the doors work and door protection and operation all handles properly. The models are fully functional, can't be sneaked through as far as I've tried and they can't be obstructed by placing a block in the top half either.

It also has a door API that will make it trivial to mave mesecons integrate with it. Mesecons will only have to call doors.open(pos) or doors.close(pos) if it detects a group = door node.

What's missing is trapdoors.

A lot of that is relatively trivial code, it just needs some work which I can easily do in a few days time.

**Comment by sofar** [comment]
https://youtu.be/GCGA0LFvi0g

**Comment by sofar** [comment]
#789 implements both an API and mesh nodes.

**Comment by est31** [comment]
I don't like the model. If you look at stuff from a very low angle, you see two doors not one:
![door-mesh-game-739](https://cloud.githubusercontent.com/assets/8872119/12375117/d5308e3c-bcb3-11e5-952d-aae299ac8fa1.png)

The old door model didn't have it.

**Comment by sofar** [comment]
@est31 we can enable backface culling to eliminate that (it can be done per-door, even, so people could choose to either enable it or not)

**Comment by est31** [comment]
I don't see an use case for not enabling it.

**Comment by sofar** [comment]
@est31 I have no problems doing that. Want to comment in the PR thread?

**Comment by paramat** [comment]
789 is merged.
