### ISSUE TITLE
combine images instead of combined images

### ISSUE THREAD

**Issue by iqualfragile** [minetest/minetest_game#739]
iirc there is a ^ operator to let minetest combine images, which enables mods to change the base image and everything still looks kinda good.
b57ecb94df2bfc1c6383a3d35465e22b683821e for example does not use it, and there might be more places.

**Comment by 0-afflatus** [comment]
I don't think it makes much odds in the case of the "Written Book". It's only really worth doing if it simplifies code or reduces the number of textures needed.

**Comment by PilzAdam** [comment]
What are the benefits of this? How is the performance and memory consumption of this compared to normal textures?

**Comment by rubenwardy** [comment]
It uses more resources (as in, texture memory). Before:

* normal book
* book with strap

After:

* normal book
* strap
* normal book + book with strap.

**Comment by kilbith** [comment]
:-1: More ressources used and from a practical standpoint, combining properly high-resolution textures can be a painful task.

**Comment by 0-afflatus** [comment]
So the opposite is true? Better to make minimal use of overlays and texture transformations.

**Comment by iqualfragile** [comment]
the point of combined textures is not to reduce memory usage (which honestly does not really matter all that much, we are way way way better then minecraft and like 10 additional tiny texures won't do any bad). The point is to make modding and texturepacking easier.

**Comment by paramat** [comment]
> The point is to make modding and texturepacking easier.

Yes that's reasonable, but is there much need for a book-buckle overlay texture? Doesn't seem essential. Where else are overlays needed?

**Comment by kilbith** [comment]
> The point is to make modding and texturepacking easier.

Which is an invalid point and seems more carried by some "fad"...

I challenge you to properly extract a part of a HD texture for using it in a combination. Besides, it would require an important effort for the artists to re-make their packs, which would be broken by overlays (breaking the userspace is evil and a good reason to stop contributing).

This is an absolute no-go.

**Comment by kaeza** [comment]
The point is the ability to have wildly different textures for written and blank books. If it were an overlay, texture packs would be severely limited in their options, and must shoehorn the "written" texture to fit the base texture visually. If you have different textures, you can put completely different textures for the book "states".

**Comment by paramat** [comment]
:-1: for book overlays. Any other textures? otherwise this should be closed.

**Comment by C1ffisme** [comment]
The ability to combine images was meant so that one texture could be overlayed by many things, e.g., the dirt texture having nothing/grass/whatever on it, without drawing a dirt node for each one. However, in the case of books, I see no reason why you would want a separate ribbon on a book. It's actually easier for texture pack makers to make one texture, then to count pixels individually.
