### ISSUE TITLE
Four Deprecated Thres-s-hold Warnings When Starting Minetest Game

### ISSUE THREAD

**Issue by LazyJ** [minetest/minetest_game#746]
**Minetest Engine (2015_12_15):**  [9ee3c3](https://github.com/minetest/minetest/commit/9eee3c3f465c071bb9908749cf48be3c131a1bdf)
**Minetest Game (2015_12_12):**  b57ecb9

```
2015-12-17 15:08:14: WARNING[Main]: Field "noise_threshhold": Deprecated: new name
is "noise_threshold".
```

Grepping for "noise_threshhold" returned this:
```
mapgen.lua:60:		noise_threshhold = 0.0,
mapgen.lua:81:		noise_threshhold = 0.0,
mapgen.lua:102:		noise_threshhold = 0.0,
mapgen.lua:123:		noise_threshhold = 0.0,
```

**Comment by paramat** [comment]
This is an engine issue due to https://github.com/minetest/minetest/pull/3428 perhaps we need to remove these warnings as 'threshhold' needs to be supported for backwards compatibility.

**Comment by paramat** [comment]
Okay will fix very soon.

**Comment by paramat** [comment]
c3a1545ca1dda4b94bfecc281097ab0cdc3e565b
