### ISSUE TITLE
undiggable grave

### ISSUE THREAD

**Issue by tchncs** [minetest/minetest_game#749]
Hi, we just got an undiggable grave:

https://www.youtube.com/watch?v=3oLreUfyu6M

At the end we blowed it up with tnt...that worked.
But not every server have tnt - also not every serverowner knows how to enable it.
So, just for safety i let you know about this.
There was no note in the (regular) servers log.

**Comment by PilzAdam** [comment]
These are fresh bones, as you can see in the tooltip in the top left when pointing at the node. They are protected to be looted or destroyed for about 10 minutes (changeable in server conf). After that time they turn into "old bones" when everyone is allowed to loot and destroy them.

**Comment by tchncs** [comment]
Ouh, why we didnt saw this! Sorry!
But for note, this was bones from an player which died there over 24h ago... .
I didn't changed anything in the conf, and dont saw this long interval before.

**Comment by everamzah** [comment]
Bones use a node timer, like TNT, but every once in a while it seems to fail.

**Comment by sofar** [comment]
Side note - there's a PR that will add a "access" permission to override protection, perhaps bones need to be added to that consideration. #602

**Comment by kilbith** [comment]
A maintainer for closing this, please.

**Comment by PilzAdam** [comment]
Closing this issue. There may be an underlying problem with the reliability of node timers, but that should be an issue for the engine.
