### ISSUE TITLE
Creative inventory search function disables exiting of inventory

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#760]
@kilbith since b1e2ece63842ff5228798feb9259398c75524f8b the search field is automatically expecting letters to be typed, this means that whatever key is used for entering/exiting inventory then fails when trying to exit the inventory. The only way to exit is to click the 'X' button first.

**Comment by kaeza** [comment]
This is probably an issue in the engine. The title of this issue is also misleading, unless you mean you can not exit the form by pressing esc.

The engine should probably allow some way of specifying the default focused item.

**Comment by kilbith** [comment]
Yes, engine's particularity. It does happens as well in Unified Inventory. I have no idea why. If you click on the formspec anywhere, it does not expect letters automatically anymore.

Also you can still exit the inventory by pressing [Esc] or [Enter] at initial opening.

**Comment by paramat** [comment]
Okay, i have the habit of using the inventory key to exit but will use ESC now. Will close this and see if others complain before opening an engine issue..

**Comment by everamzah** [comment]
This has been an issue with unified_inventory forever, and has _always_ been very annoying.  Now it's frustrating to see this behavior in stock form, via the new creative search function.

I agree that it is an engine peculiarity, in that if there's a text field anywhere it'll assume that's where you want to type into.  It's just not usually the case.

**Comment by kilbith** [comment]
I just noticed that if you click anywhere on the formspec or do an operation (like moving stuff), it doesn't expect letters anymore and you can exit the inventory the normal way.

99% of time you're doing something in the inventory (preventing this micro-issue), so the "_very annoying_" is really exaggerated, especially considering the alternative keys...

**Comment by everamzah** [comment]
Yep, I noticed this as well.  Nonetheless, I can guarantee you that if I'm using unified_inventory, that the search bar will have "we" in it.  Every time.  Like paramat, I expect the "open inventory" key to also "close inventory", as it does on the default stock player inventory (survival form), chests, furnaces, and etc.
