### ISSUE TITLE
Default texture pack including normalmaps needs hosting / maintaining

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#769]
See https://github.com/minetest/minetest_game/issues/764 https://github.com/minetest/minetest_game/pull/765
@RealBadAngel i expect you would be the ideal person to do this?

**Comment by RealBadAngel** [comment]
sure, what do you want me to do?

**Comment by paramat** [comment]
Perhaps you can host and maintain the dev version yourself in your own github repo?, then maybe we can also make regular copies into a new official MTGame repo.

**Comment by kilbith** [comment]
Is it still necessary to keep this issue opened ? RBA got the message.

**Comment by paramat** [comment]
I'll close it once it's hosted somewhere, for now i'll host it myself.

**Comment by paramat** [comment]
Agreed.
