### ISSUE TITLE
Unlimited steel trapdoors

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest_game#770]
Craft a steel trapdoor and then place until your fingers hurt, they never end :) This is in the latest build.

**Comment by kilbith** [comment]
Confirmed. Fixed by replacing : https://github.com/minetest/minetest_game/blob/master/mods/doors/init.lua#L470-L473

... by : 

``` Lua
return minetest.setting_getbool("creative_mode")
```

@sofar @paramat

**Comment by sofar** [comment]
Submitted @kilbith 's suggestion as fix, thank, for reporting @tenplus1 !
