### ISSUE TITLE
Issues with tree logs as schematics

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest_game#773]
Two issues since 57939c6 : 

1. Tree logs schematics are often appearing as so (doesn't look like fallen logs) : http://imgur.com/a/5HXlM

2. Mushrooms grow exclusively onto tree logs, which is **wrong** ! This shall be something very occasional (paramat expected *one* type of mushroom spawned with a *low chance* onto tree logs).

@sofar @paramat

**Comment by sofar** [comment]
What mapgen is this?

**Comment by sofar** [comment]
Obviously I'm looking into this closely.

v7: this is where all my testing has been done, can't confirm either bug here
v6: spotted a minor error but it doesn't affect mushrooms, I can still find mushrooms, but no logs in this mapgen
v5: everything looks normal here, mushrooms can be found both on and off logs, and the logs all look properly oriented.

**Comment by sofar** [comment]
Do you have any other mods that influence mapgen enabled as well?

**Comment by kilbith** [comment]
> What mapgen is this?

Mapgen V7 (with Minetest 0.4.13-stable currently).

> Do you have any other mods that influence mapgen enabled as well?

No, only default game.

**Comment by sofar** [comment]
Can you post seed and location of those screenshots?

**Comment by kilbith** [comment]
Seed : `linux`

Coordinates of the screenshots :  ~1 km radius around `440, 6, 3964`.

**Comment by sofar** [comment]
I still can't verify. Logs look fine in my generated terrain and I can find mushrooms on the ground, albeit rare.

What version of minetest are you using?

**Comment by kilbith** [comment]
Already said...

> (with Minetest 0.4.13-stable currently).

**Comment by sofar** [comment]
*confirmed*

the issue indeed happens with 0.4.13 stable (archlinux, x86_64)

**Comment by sofar** [comment]
To be precise: I can find mushrooms *plenty* that are not on logs, so that part I think is just bad luck that you didn't find an area with many mushrooms.

The logs are indeed badly rotated.

**Comment by kilbith** [comment]
> I can find mushrooms plenty that are not on logs, so that part I think is just bad luck that you didn't find an area with many mushrooms.

I recently found mushrooms on ground actually, but in approx. proportion like : 80% of time on logs, 20% on ground. It should be the reverse proportion.

**Comment by sofar** [comment]
Strongly disagree, mushrooms are known to grow on dead wood, not randomly on ground.

**Comment by sofar** [comment]
lets' focus on the rotated log problem in this issue. You can always file a new issue for your issues with mushroom spread at mapgen.

**Comment by kilbith** [comment]
> mushrooms are known to grow on dead wood

Yes, but rarely.

Hell, you did not even adressed our expectations¹ and lied on the proportion². The result is frankly, ugly :-1:

¹ paramat : _"One type of mushroom on top would be nice with a low chance, whichever is more realistic for growing on logs"_.

² sofar : _"mushrooms are placed on a log with low probability"_.

**Comment by sofar** [comment]
please open a new ticket already

**Comment by sofar** [comment]
As for the actual confirmed bug: 0.4.13-stable doesn't appear to rotate logs at all. All of the logs have param2=12.

**Comment by sofar** [comment]
Git bisected 0.4.13 to HEAD in minetest/minetest, and shows up as:
```
a56aedb4eae7d21864ab8dc56a82f644c4639f7a is the first bad commit
commit a56aedb4eae7d21864ab8dc56a82f644c4639f7a
Author: paramat <mat.gregory@virginmedia.com>
Date:   Mon Sep 21 01:21:28 2015 +0100

    Mapnode: Add rotateAlongYAxisFull supporting 24 facedirs

:040000 040000 8f5d24fb12b9b857b5b5effca2ed85a95367e1f6 243581067d3a5367469e8afa2c480b5374f8fb34 M	src
```

It looks like 0.4.13 just doesn't have the proper code needed to rotate schematics.

**Comment by sofar** [comment]
I may have a solution for this later, possibly.

**Comment by paramat** [comment]
> It looks like 0.4.13 just doesn't have the proper code needed to rotate schematics.

Correct. MTGame-dev is expected to be used on 0.4.13-dev, so this is not an issue.

127 might be a little high for mushroom chance, perhaps 63 is better. However, many logs are in full sunlight so many mushrooms will eventually be killed off.

**Comment by paramat** [comment]
127 seems ok in rainforest as it's so humid, but i'd prefer 63 for pine logs as with appletree logs.

**Comment by sofar** [comment]
Fine with me for pine log mushroom chance. I'll submit an update later.

**Comment by kilbith** [comment]
OK, that seems fixed. Thanks @sofar and @paramat for your reactivity.
