### ISSUE TITLE
Wool cannot be dyed white

### ISSUE THREAD

**Issue by Taknamay** [minetest/minetest_game#776]
Wool cannot be dyed white right now. Is this on purpose?

**Comment by tenplus1** [comment]
Personally I think that line 12 in the wool mod's init.lua should read:

{"white",      "White",      "basecolor_white"},

**Comment by sofar** [comment]
@tenplus1 care to submit this to minetest_game? The bug exists in minetest_game, and you have a fix, so, why not submit it upstream?

**Comment by tenplus1** [comment]
Done: https://github.com/minetest/minetest_game/pull/778

**Comment by paramat** [comment]
Fix was merged.
