### ISSUE TITLE
Steel trapdoor and iron bars recipes are conflicting

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest_game#779]
Both have the same recipe.

Cc: @sofar

**Comment by sofar** [comment]
Thanks, I had no idea, this is awkward

**Comment by sofar** [comment]
alternative, doesn't have any conflicts:
```
steel_ingot, steel_ingot
steel_ingot, steel_ingot
```

**Comment by kilbith** [comment]
Yes, go for this recipe for the steel trapdoor.

**Comment by sofar** [comment]
Given the reduction in materials, I'm contemplating making the recipe yield only 1 trapdoor, instead of 2. Thoughts? @paramat?

**Comment by kilbith** [comment]
Fine to me.

**Comment by paramat** [comment]
Yes 1 trapdoor, considering how 3 ingots are needed for a pick.
