### ISSUE TITLE
Pink dye should be mixable

### ISSUE THREAD

**Issue by Taknamay** [minetest/minetest_game#781]
Once again, not sure if this is intentional or an oversight. The only dye that cannot be mixed is pink dye. I have an idea for what the table of mixtures would look like:

Pink dyes are the only kind that is not mixable. Here is an idea of the table of mixtures:

    combine with: result
    ------------------------
          black : black
           blue : magenta
          brown : orange
           cyan : grey
      darkgreen : yellow
       darkgrey : pink
          green : yellow
           grey : pink
        magenta : magenta
         orange : orange
           pink : pink
            red : red
         violet : magenta
          white : pink
         yellow : orange

**Comment by paramat** [comment]
Seems a good idea, maybe with a few changes, will suggest some later.

**Comment by paramat** [comment]
Looking at a colour wheel and always shifting 1 colour towards red, i suggest:
```
      black : black
       blue : magenta
      brown : red *
       cyan : magenta *
  darkgreen : yellow
   darkgrey : pink *
      green : yellow
       grey : pink
    magenta : red *
     orange : red *
       pink : pink
        red : red
     violet : magenta
      white : pink
     yellow : orange
```

**Comment by Taknamay** [comment]
I think mine is more consistent. For example, with your system you can mix magenta with white to make pink, then mix pink with magenta to make red. However, there are a bunch of similar weird things with dyes right now, so it's not like pink would stand out.

So, while I prefer my table, your table is also OK I would say.

**Comment by paramat** [comment]
Hm perhaps it's best to be consistent with how red mixes and treat pink exactly like red.

**Comment by paramat** [comment]
I might make a PR for this.

**Comment by paramat** [comment]
898 merged.
