### ISSUE TITLE
Create test for conflicting crafting recipies

### ISSUE THREAD

**Issue by ExcaliburZero** [minetest/minetest_game#782]
With minetest_game's development, one of the issues that can occasionally occure when new items are introduced is that their crafting recipies may conflict with pre-existing crafting recipies.

While this is something that can be tested manualy, it would probably be a good idea to setup an automated test for this, as it is something that can be easily overlooked.

It would be helpful if we could setup a test script which would gather all of the crafting recipies in minetest_game and check for any confilicts. This script could be run by a service like Travis CI whenever someone post a pull request, so that if they have a crafting recipie conflict they will be automatically notified of it.

**Comment by rubenwardy** [comment]
I made a PR for this, but it was rejected. Here is a lua builtin script I wrote:

https://gist.github.com/rubenwardy/5504537

**Comment by red-001** [comment]
Maybe minetest should print a warning if it detects a craft recipe conflict?

**Comment by Wuzzy2** [comment]
This is certainly not an issue exclusive to Minetest Game. This affects almost all mods and subgames.

It is an engine issue, see here: https://github.com/minetest/minetest/issues/4382

**Comment by sfan5** [comment]
closed in favor of engine issue (see above)
