### ISSUE TITLE
Infinite nodes obtainable from 2 slabs

### ISSUE THREAD

**Issue by everamzah** [minetest/minetest_game#786]
Using only two slabs, one can create indefinitely tall towers, gaining free materials.  Place one slab and stand on its corner, hold sneak and jump, and hold down RMB.

Edit: Dragonop found this.

**Comment by everamzah** [comment]
https://youtu.be/2DqGTBYZHpE

Here is a video demonstrating this bug using freshly cloned minetest and minetest_game.  You don't have to do this in a tower, you can place your infinite slabs anywhere you like.

**Comment by Dragonop** [comment]
You only need to do the tower until the stack runs out, in this case, 2 slabs, then you are free to roam and place infinite slabs, you can use a tool to mine it, release the mouse button, etc.
I think it's not needed to hold sneak jump as long as you use the stack you have (this is why it is done with only 2 slabs, it's faster) and keep holding the mouse button until you start to place slabs even if you don't have any.
Apparently the effect stops after some minutes if you don't use it or if you place another block. You can only place the slabs with your hand.

**Comment by kahrl** [comment]
Preliminary diagnosis: The slabs' on_place callback is sometimes returning nil intending to clear the held stack of slabs, however the engine interprets a nil return value as "do not modify the held itemstack".

https://github.com/minetest/minetest/blob/da686160c33069b77a7b4c31fd97da5fa5b59baa/src/script/cpp_api/s_item.cpp#L75

**Comment by everamzah** [comment]
Seems to work just fine.  One extra slab is okay compared.  Thanks for the quick fix!
