### ISSUE TITLE
mese crystal fragments to mese crystal craft

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest_game#788]
I'm surprised that in 0.4.13 we still don't have a crafting recipe to make 9x mese crystal fragments into 1x mese crystal...  Could you please pop this into the crafting.lua file:

```
-- 9x mese crystal fragments = 1x mese crystal
minetest.register_craft({
	output = "default:mese_crystal",
	recipe = {
		{"default:mese_crystal_fragment", "default:mese_crystal_fragment", "default:mese_crystal_fragment"},
		{"default:mese_crystal_fragment", "default:mese_crystal_fragment", "default:mese_crystal_fragment"},
		{"default:mese_crystal_fragment", "default:mese_crystal_fragment", "default:mese_crystal_fragment"},
	}
})

**Comment by kilbith** [comment]
Actually, we should drop all those fragments (obsidian, mese and glass). These have almost no value gameplay wise, except in some external mods for specific uses.

**Comment by tenplus1** [comment]
I disagree, mese is a special ore found in game so blocks/crystal/fragments are handy, same with obsidian shards for obsidian glass, and yes certain mods do rely on them and make good use of each :)

**Comment by paramat** [comment]
Being unable to craft crystal fragments back was intentionally done, i guess because it's crystalline. I think it's okay as it is :-1:

**Comment by red-001** [comment]
I agree with @paramat it makes the player think before they craft something.

**Comment by C1ffisme** [comment]
I say we should either:

A) Delete mese fragments and let mods add them or
B) Add this crafting recipe.

Realistic or not, mese shards are completely useless at the moment in vanilla, and should be removed from the game, unless they are given a purpose. (in the TODO at the dev wiki, there is a suggestion to make them a method of teleportation...)

If we do choice B, then it is possible to use mese as some kind of currency, maybe for a vanilla server.

**Comment by tenplus1** [comment]
+1 C1

**Comment by everamzah** [comment]
Gold is currency already, C1ffisme, so I suggest leaving them out as they are.  Interesting that the CaveRealms mod comes with a craft recipe for 9 shards from a single Glow Mese node.  Putting them back in preserves backwards compatibility for this mod.

However, this is very trivial to add, as demonstrated by tenplus1's snippet.  So why not make a mese_plus mod then?

**Comment by C1ffisme** [comment]
@everamzah Actually, gold really has no value, while mese can be turned into tools if you are desperate. Gold might have a use if you could trade it with NPCs, but we don't have those.

But on-topic, it seems like putting a single recipe in minetest's code is not that much work. As for making a mese_plus mod, this seems like a very small addition worth putting in an entire mod.

This recipe either goes in, or we drop mese fragments.

As a side note, mese fragments could be used in mese lamps or glow glass rather than being useless.

**Comment by everamzah** [comment]
I seem to recall gold as currency being implied in the game design.

You can break glass into fragments, but you don't make a drinking glass from the fragments.

**Comment by C1ffisme** [comment]
@everamzah No, but you can smelt them to get your glass back. (Can you, actually? I haven't tested this.)

**Comment by everamzah** [comment]
So if you smash something into shards or fragments, you can't combine it back without some additional step?

**Comment by C1ffisme** [comment]
@everamzah I dunno. You can make the mese block from it's crystals, and the mese block looks like a block, not a stack of crystals.

**Comment by everamzah** [comment]
Tough nut to crack!  Once you do, though, you can't really put it back together again.

**Comment by C1ffisme** [comment]
@everamzah Maybe mese is a non-Newtonian... solid???

(e.g. Mining quickly hardens the mese, putting it together slowly makes it act like moldable clay.)

**Comment by everamzah** [comment]
I feel the following is a reasonable solution:

Given that obsidian shards are used for cooking, and result in obsidian glass
Allow Mese Crystal Fragments to be cooked into Mese Crystals.

**Comment by tenplus1** [comment]
everamzah: that would mean 1x mese crystal would give 9x shards and cooking 1x shard would result in 1 new mese crystal...  not a good result...  I'm all for 9x mese fragments = 1x mese crystal to keep things simple.

**Comment by everamzah** [comment]
Yes, I didn't consider this until after I clicked the "Comment" button.  I think there's something to it, though, just because that's what you do with Obsidian shards.  However, if the fuel group is high enough, cooking will take so long as to not be so "cheap", yes?

**Comment by paramat** [comment]
:-1:

**Comment by C1ffisme** [comment]
What about having a machine in Minetest Game called the "assembly furnace" which would cement things together such as fragments? This means they can be used as currency, and we could have some other way of obtaining the fragments (mob drops, more common ores, etc.)

The assembly furnace would have to have other applications too, maybe we could use it for metal blocks rather than crafting them? Or some kind of rare, strong tool tier.

Anyway, just an idea.

**Comment by MT-Modder** [comment]
Maybe we could cook fragments into mese glass (maybe mesecons will make it conductive?). Then use mese glass in a 2x2 recipe to make meselamps.

Otherwise I think having a useless item is pointless.

**Comment by C1ffisme** [comment]
@MT-Modder [Mese glass... Hmm... Glows? Where have I heard of that before?](https://forum.minetest.net/viewtopic.php?f=11&t=509)
But it's a good idea, nonetheless.

**Comment by MT-Modder** [comment]
Yeah I can't lie, the image was in my head, but...
1) mese isn't used in the crafting of glow glass
2) it would would be an entirely different "yellow"
3) the light given off would be very dim.

**Comment by C1ffisme** [comment]
@MT-Modder You do have some good points, although 3) and 1) make the node seem useless if the more blocks mod is used. I dunno. I suppose it has some use. We are lacking a (vanilla) light source for dimly lit areas such as creepy caves.

**Comment by MT-Modder** [comment]
True. It just seems like the next logical step; it would be consistent with obsidian shards. I personally stopped using moreblocks + homedecor when xdecor was released. Too much "more" lol.

**Comment by paramat** [comment]
Mese crystals can be reformed into mese blocks, so likewise for shards into crystals seems consistent :+1:

**Comment by benrob0329** [comment]
I like to think of Mese as a metallic crystalline.

**Comment by paramat** [comment]
#1108 is merged.
