### ISSUE TITLE
 fire cannot be extinguishd by water

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest_game#804]
Fire should be extinguishd by water it makes sense right

**Comment by paramat** [comment]
Again weird, it works for me, sometimes it takes a few seconds.

**Comment by red-001** [comment]
Are you using lastest git?

**Comment by red-001** [comment]
Recently fire is a lot slower.

**Comment by tobyplowy** [comment]
How do i play the latest git im new

**Comment by red-001** [comment]
latest git means it is the version of minetest game you can download from github. https://github.com/minetest/minetest_game/archive/master.zip. You also need a recent version of the engine. You can  get this from the builds section of the forums.

**Comment by tobyplowy** [comment]
Culd it be extinguishd instantly ones water hits it?

**Comment by red-001** [comment]
yes but the load on the server would be a lot higher.

**Comment by paramat** [comment]
It should extinguish within 3s. Make sure you're using latest MTGame not 0.4.13 stable.
