### ISSUE TITLE
Slabs back to blocks

### ISSUE THREAD

**Issue by CodePhase** [minetest/minetest_game#808]
Hello,

I noticed on Minetest 0.4.12 and the latest Minetest and MInetest_game git pulls that I am unable to change slabs back to their original block forms by crafting one on top of the other as mentioned on the wiki (http://wiki.minetest.net/Slab):
>Two slabs of the same material can be built into full blocks by building them over each
>other. Can be used as thin wall/fence when rotated using screwdriver.

Attached is a screenshot. I have no mods enabled and am running the default minetest_game.
![noslabtoblock](https://cloud.githubusercontent.com/assets/14020204/12552092/7f52a528-c33d-11e5-9dad-653dc3cfa6b0.png)

Please let me know if you need any other information. Thanks!

**Comment by everamzah** [comment]
You can already do this in-game by placing one slab onto the top of another.

**Comment by CodePhase** [comment]
@everamzah It's not working for me.  Please refer to the screenshot.  What version of Minetest and Minetest_game are you using?  Perhaps I can try the same version.  It's possible I'm doing something wrong.

**Comment by everamzah** [comment]
You're trying to craft one wood node from two wood slabs, but that's not possible.  Instead, place one slab down on the ground, and then place another slab on top of it.

It's not a craft recipe, it's an in-world mechanic.

**Comment by CodePhase** [comment]
Success!  Thank you!  I've verified this works.
