### ISSUE TITLE
New gravel texture needed

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#811]
![screenshot_20160128_015942](https://cloud.githubusercontent.com/assets/3686677/12691664/fb9118da-c6e5-11e5-91f8-c24ba045f1a0.png)

^ Gravel beaches in tundra

Post suggestions or submissions here, lets look through subgames and texture packs too.

**Comment by Napiophelios** [comment]
Here is a modified version of the current default texture.
The lighter colors are toned down a bit so its a little softer on the eyes

![default_gravel](https://cloud.githubusercontent.com/assets/8119411/12668796/3f4e4cf0-c628-11e5-82a4-3522db8a7fc7.png)

**Comment by kilbith** [comment]
Gambit's ones : 

![default_gravel_light](https://cloud.githubusercontent.com/assets/7883281/12675938/3bd58b22-c68e-11e5-9c64-25af1d4f35a3.png) ![capture](https://cloud.githubusercontent.com/assets/7883281/12676001/f22af92a-c68e-11e5-827c-cc729e77d518.PNG)

![default_gravel](https://cloud.githubusercontent.com/assets/7883281/12676020/1bb46bbe-c68f-11e5-8870-96bfc0c2fd04.png) ![capture2](https://cloud.githubusercontent.com/assets/7883281/12676037/3c134cd6-c68f-11e5-808f-3f35b74e845b.PNG)

**Comment by sofar** [comment]
The suggestions look fairly decent, especially the lighter one posted by @kilbith. I'd like to take a look later though using them in-game.

**Comment by paramat** [comment]
Gambit's are good, i like the shadowed pebbles within a finer material, i prefer the lighter one.

**Comment by paramat** [comment]
![screenshot_20160130_025529](https://cloud.githubusercontent.com/assets/3686677/12693247/243940d4-c6fd-11e5-9935-7afcee97e35d.png)

Gambit's lighter texture, i like it.

**Comment by sofar** [comment]
it has some very repetitive parts to it, mind if I take a pass on seeing if I can eliminate those?

**Comment by 0-afflatus** [comment]
May I suggest that the problem is not so much the darkness but the greyness, especially if we are going to use this texture for beaches. Natural gravel varies in hue a bit.

**Comment by paramat** [comment]
Sofar go ahead.
As for colours, this needs to be multi-purpose fine stone, grey stone breaks down into grey cobble which breaks down into grey gravel. The purity of the colour works well and is consistent with previous gravels, being colour-neutral makes it work better alongside coloured nodes.

**Comment by sofar** [comment]
I mostly flipped sections of pixel blocks around to get rid of lineair patterns, and did a second pass refining the shading as there was an obvious dark belt on two sides of the texture causing a sort of ladder visual. The end result is quite pleasing, and has a little bit more contrast:

![]
(http://i.imgur.com/XPTqAz5.png)

![]
(http://i.imgur.com/rhgiuOU.png)

**Comment by kilbith** [comment]
The littles "L" you see are the pebble shadows. Shadows are always in same direction, not in your texture.

Also it's always delicate to touch a professional work to the risk of deteriorating it.

**Comment by sofar** [comment]
@kilbith please remove the second line of your comment, it's completely not needed and distracts from the discussion

**Comment by sofar** [comment]
Pass 2

Flipped all the shadows around to be consistent. Especially from afar this has the look I think that was originally intended where you perceive large pebbles in a lighter matrix. This didn't affect any of the lineair patterns.

![]
(http://i.imgur.com/GCV9ykS.png)
![]
(http://i.imgur.com/7rIULrE.png)

**Comment by kilbith** [comment]
Yeah, this one looks good.

**Comment by paramat** [comment]
v Gambit
![f22af92a-c68e-11e5-827c-cc729e77d518](https://cloud.githubusercontent.com/assets/3686677/12704854/faeb050e-c85b-11e5-9724-76e4cd663aac.PNG)
![sofar2gravel](https://cloud.githubusercontent.com/assets/3686677/12704848/e7448886-c85b-11e5-953d-e80979078b4b.png)
^ sofar

**Comment by 0-afflatus** [comment]
I agree, this looks good.

**Comment by Napiophelios** [comment]
:+1:   Sofar's latest texture looks very nice ingame

**Comment by sofar** [comment]
I'll try and fix that last shadow and then put this in a PR with credits to Gambit.

**Comment by sofar** [comment]
I flipped the L around and did a few more contrast dodge/burn pixel changes, all very subtle. We can continue the discussion here or in the #817. Thanks.

**Comment by 0-afflatus** [comment]
You should credit yourself as well, either
Sofar based on Gambit or
Gambit edited by Sofar or
whatever wording you find appropriate.
It's important to let people know who made the changes.

**Comment by sofar** [comment]
@0-afflatus both the commit message and the ```README.txt``` change include a note about me adjusting the texture.

**Comment by 0-afflatus** [comment]
Yes I saw that. I think that makes it clear enough that this is your modification of the original. It's purely so maintenance requests go to the right place and future discussions can be kept clear.

**Comment by 0-afflatus** [comment]
Otherwise known as owning up to the mess you made ;-)

**Comment by HybridDog** [comment]
#179

**Comment by paramat** [comment]
#817 merged.
