### ISSUE TITLE
Written books with long lines are not wrapping

### ISSUE THREAD

**Issue by everamzah** [minetest/minetest_game#813]

**Comment by tenplus1** [comment]
I went back to using my original formspec so that text wrapped properly again:

```
local function book_on_use(itemstack, user, pointed_thing)
	local player_name = user:get_player_name()
	local data = minetest.deserialize(itemstack:get_metadata())
	local title, text, owner = "", "", player_name
	if data then
		title, text, owner = data.title, data.text, data.owner
	end
	local formspec
	if owner == player_name then
		formspec = "size[8,8]"..default.gui_bg..
			"field[0.5,1;7.5,0;title;Title:;"..
				minetest.formspec_escape(title).."]"..
			"textarea[0.5,1.5;7.5,7;text;Contents:;"..
				minetest.formspec_escape(text).."]"..
			"button_exit[2.5,7.5;3,1;save;Save]"
	else
		formspec = "size[8,8]"..default.gui_bg..
			"label[0.5,0.5;by "..owner.."]"..
			"label[0.5,0;"..minetest.formspec_escape(title).."]"..
			"textarea[0.5,1.5;7.5,7;text;;"..
				minetest.formspec_escape(text).."]"
	end
	minetest.show_formspec(user:get_player_name(), "default:book", formspec)
end

**Comment by 0-afflatus** [comment]
I have a recollection that this point was raised in the original PR and never resolved. I'm not sure why, I think this is rather important.

**Comment by sofar** [comment]
This was changed last year by @Rui914 in 3fb6ee5bdf7a8940d7e25c96f41436a49fea32fc

**Comment by sofar** [comment]
Scrollbars are not possible with textarea's. That was the reason to switch to a table. If we want both, it'll have to be fixed in core I think.

**Comment by everamzah** [comment]
This shouldn't have gone in, then, as it breaks every single written book ever.

**Comment by tenplus1** [comment]
If only scrollbars were possible in textarea's if the text is too long, but the above formspec at least lets you use cursor keys to scroll downwards.

**Comment by kilbith** [comment]
Best solution is to drop the scrollbar, get back to textarea and add support for multiple pages.

**Comment by everamzah** [comment]
IMHO, the best option is to automatically convert the old format to the new one `on_use`

**Comment by sofar** [comment]
Indeed, multiple page support would be nice.

**Comment by everamzah** [comment]
I agree completely, but feel that fixing the broken books ought to be priority number one.

**Comment by everamzah** [comment]
This isn't a feature request, or at least that's not why I created the issue.  Long lines wrapped in 0.4.13 books by default, and now any book written then is broken now.  As in, you can't read books in 0.4.14 that were written in 0.4.13.

**Comment by paramat** [comment]
Ok.

**Comment by paramat** [comment]
890 merged, should be fixed.
