### ISSUE TITLE
ABM improvements

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#827]
I would like to edit the 'interval' and 'chance' of MTGame ABMs. This will need tuning and discussion before i open a PR.

1. Reduce all intervals to 16s or less.
With the default active block range of 32 nodes and a player speed of 4 nodes per second, a player walking without stopping can cross the triggering distance of an ABM in 16s. Any higher interval means that ABM actions can be missed.

2. Adjust chance parameter to compensate for the change in interval, to result in the same rate of ABM actons.
The advantage of shorter intervals and higher chance parameters is that stuff is done in a larger number of smaller batches, this reduces the length of individual lua lags and makes the lua server smoother.

3. Adjust intervals to be more evenly spread out across 1s and 16s.
This makes ABM intervals more out-of-phase instead of all firing at once causing lua lag spikes. We could even choose prime number intervals for the heaviest ABMs to keep them out of phase with each other even more.

4. Other optimisations where possible, see comments.

Below, changed values are in brackets.

```
default/
functions.lua/

Lavacooling x 2.
	interval = 1,
	chance = 2, (1)
* Interval unchangeable. Chance back to 1 for classic behaviour.
* Combine into 1 ABM for less search load.

Cactus growth.
	interval = 50, (12)
	chance = 20, (83)

Papyrus growth.
	interval = 50, (14)
	chance = 20, (71)

Leafdecay.
	interval = 2,
	chance = 5,
* Lua-heavy. Interval is expected to be small and spreads the load.

Grass growth on dirt.
	interval = 2, (6)
	chance = 200, (67)
* Lua heavy due to 3 x 4096 dirt around.
* Add 'neighbors = air' to hugely reduce number of actions.

Grass death in darkness.
	interval = 2, (8)
	chance = 20, (50)
* Action rate can be reduced, currently unnecessarily fast.
* Equalise action rate to grass growth rate.

Moss growth on cobble near water.
	interval = 17, (16)
	chance = 200,
* Lua-light so can share an interval with stairs replace ABM.

trees.lua/

Grow saplings.
	interval = 10,
	chance = 50,


doors/
init.lua/

Door replace ABMs,
	interval = 7,
	chance = 1,
* Might be replaced with LBM later. Fairly lua-light due to few doors present.
* So can share an interval with fire mod.


farming/
api.lua/

Crop growing.
	interval = 90, (9)
	chance = 2, (20)

nodes.lua/

Saturation and drying of soil.
	interval = 15,
	chance = 4,


fire/
init.lua/

Extinguish with water/snow/ice.
	interval = 3,
	chance = 2, (1)
* Lua-light. Chance = 1 for more effective extinguishing.

Remove flames when fire mod, and the 2 ABMs below, are disabled.
	interval = 7,
	chance = 2, (1)
* Lua-light. Chance = 1 for more effective removal.

Ignition.
	interval = 7,
	chance = 16,

Remove burnt nodes and flames.
	interval = 5,
	chance = 16,


flowers/
init.lua/

Flower spread.
	interval = 50, (13)
	chance = 25, (96)
* Lua heavy so prime interval 13.

Mushroom spread.
	interval = 11,
	chance = 50,


stairs/
init.lua/

Replace old nodes. Disabled by default.
	interval = 8, (16)
	chance = 1,
* Lua-light. Increase interval to maximum for less search load.
* Might be replaced by LBM later.


tnt/
init.lua/

Ignite TNT and gunpowder.
	interval = 1, (4)
	chance = 1,
* Increase interval for less search load.
* TNT and gunpowder can take a while to ignite.
```

**Comment by tenplus1** [comment]
If it's going to reduce lag and all Abm's work efficiently then it's a huge +1

**Comment by Fixer-007** [comment]
Agree on all points, especially on out of phase one. :+1:

**Comment by sofar** [comment]
@paramat we'd see even better spread of ABMs if we depart from using whole integer interval numbers, and instead do one of the following:

- Allow fractional interval (e.g. [prime]/10s : 13.7s, 8.3s)
- Always add a random jitter to the ABM timer (e.g. +/- 0.5s jitter)

**Comment by C1ffisme** [comment]
I think you missed cactus/papyrus growth in the campaign to change things to 16s or less.

Unless that was intentional.

Anyways, :+1:

**Comment by paramat** [comment]
Sorry, the list is as they are currently.

**Comment by C1ffisme** [comment]
Oh! Okay. Me being stupid.

**Comment by paramat** [comment]
I was being unclear. I'll update the list as this develops.

**Comment by C1ffisme** [comment]
Nah, I didn't read this line:

> To start here's my list of MTGame ABMs as they **currently are**

**Comment by paramat** [comment]
I only just added the last 4 words to be clear.

**Comment by paramat** [comment]
Added comments to list:

Furnace processing and TNT fuse burn are both unchangeable,

Perhaps lavacooling chance should be reverted to 1 for classic lavacooling behaviour? Curently lavacooling acts slower allowing lava to spread more. The interval is unchangeable.

Grass death in darkness acts unnecessarily fast, the action rate can be slower. There's usually lots of grass around (64^2 = 4096 within ABM range).

**Comment by sofar** [comment]
@paramat I suspect it may be a lot better to change TNT fuse burning to a node timer, and declare ABM's to be "inexact" in the API document. This may help in similar cases where timing should be precise vs. inaccurate.

**Comment by paramat** [comment]
> change TNT fuse burning to a node timer

Sounds possibly good.

Updated list with comments and suggested changes.
We should consider adding 'neighbors = "air"' to the grass growth on dirt ABM because it is currently heavy due to 3 x 4096 dirt within ABM range.

**Comment by sofar** [comment]
@paramat strike that, TNT is using a node timer to ignite adjacent gunpowder already. The ABM is to ignite gunpowder and TNT if it's adjacent to fire, or lava, which isn't replaceable with a node timer.

**Comment by sofar** [comment]
Furnace should potentially use a node timer instead of an ABM. I'm investigating...

**Comment by Fixer-007** [comment]
Important question, how to measure lua load/performance?

**Comment by paramat** [comment]
Indeed. This PR won't improve performance much, it will only spread out the ABM load and make the lua lags smaller and more frequent. Also it will make sure no nodes are missed by an ABM if the player is often walking past without stopping, so crops and flowers will tend to grow a little faster.

**Comment by paramat** [comment]
> The ABM is to ignite gunpowder and TNT if it's adjacent to fire, or lava

Good that means we can increase the interval, an ABM search every second is excessive for this use, i propose increasing it to4s which is the last gap in the list of intervals. TNT or gunpowder would take a few seconds to heat up and ignite when near fire or lava.

**Comment by paramat** [comment]
We can combine the 2 lavacooling ABMs into 1 by using a list of nodenames, then deciding the action on the node.name, just as with sapling ABMs.

**Comment by paramat** [comment]
Updated list. Fire extinguishing by water i feel should be chance = 1 to be more effective.
The stairs replace ABM, which is low priority and disabled by default, can be interval 16s.

**Comment by paramat** [comment]
Updated with all interval slots filled, some ABMs have the same interval.
Removal of flames when fire mod is disabled is changed to chance 1 to be faster.
Grass death in darkness has been slowed down to the same action rate as grass growth on dirt.

I'll now start the PR.

**Comment by sfan5** [comment]
:+1:

**Comment by xeranas** [comment]
I think it would be better to introduce flag in register_abm (e.g. spread_load) and let engine manage abm calls. It would require change on engine but would solve spreading abm load globaly. Some precision would be lost in cases when spread_load would be true. However many mods does not require it anyway.

**Comment by paramat** [comment]
PR is merged.
