### ISSUE TITLE
Game icon looks bad at different resolutions

### ISSUE THREAD

**Issue by ExcaliburZero** [minetest/minetest_game#837]
Currently the icon for Minetest Game that is used in the game selection section of the main menu is 96x96px. The icon looks good at its normal size, however, when it is viewed on the main menu it is generally distorted.

Here is the actual icon and a screenshot of it on the main menu for compairison (look at the screenshot at full size to see the distortion):

![icon](https://cloud.githubusercontent.com/assets/4276196/13023466/273483ba-d1b7-11e5-9209-7117a0f3789d.png)

![minetest_game_icon_screenshot](https://cloud.githubusercontent.com/assets/4276196/13023473/2dd59fec-d1b7-11e5-8fc5-97418a5cc140.png)

This can be fixed by having a larger version of the icon used in place of the current 96x96px sized one.

**Comment by Napiophelios** [comment]
you can also crop it to 86x86 to slightly improve its presentation

**Comment by paramat** [comment]
The ione in the main menu might be .svg.

**Comment by ExcaliburZero** [comment]
The image that is used in the main menu is a `.png` format. It is located here:

[`minetest_game/menu/icon.png`](https://github.com/minetest/minetest_game/blob/master/menu/icon.png)

**Comment by RHRhino** [comment]
@paramat we don't have a .svg support.
https://github.com/minetest/minetest/issues/2423
https://github.com/minetest/minetest/issues/2419

@ExcaliburZero If you put 'gui_scaling_filter = true' in the minetest conf it solves the problem
![1](https://cloud.githubusercontent.com/assets/6941454/13246540/85563c6c-da14-11e5-84d6-0d7d61fddc25.PNG)

**Comment by tobyplowy** [comment]
@paramat will this get fixed?

**Comment by paramat** [comment]
This is an engine issue, please move discussion to https://github.com/minetest/minetest/issues/2419
