### ISSUE TITLE
Too easy to get wheat seeds

### ISSUE THREAD

**Issue by sofar** [minetest/minetest_game#838]
It's way too easy to get wheat seeds, since grass can be dug by hand over and over
again - one can easily convert 100% of grass to seeds this way.

to reproduce:

- Dig one grass node
- plant it
- dig it again
- rinse...repeat

Proposed solutions that I can think of, best one on top:

1. Require scissors to cut grass. If grass is dug without scissors, destroy the grass without dropping the grass node. Drop seeds occasionally (1 in 20). Do not drop seeds when cutting grass with scissors.
2. Drop seeds from grass_5 only when dug. If seed drops, do not drop grass node.
3. ... ?

Similarly, leaves, flowers should not be diggable by hand, but instead require a tool?

Perhaps we can do something original like a sickle instead of scissors, as that's a far more common and appropriate tool to cut grass and wildflowers.

**Comment by C1ffisme** [comment]
The way I see it, grass is wheat that hasn't been cultivated properly. Thus it turns green and produces no crop. Then if you dig through it enough, you can find seeds.

Shears or scissors is a good idea though. It makes it a bit less ridiculous. I'm not sure if we can set node drops based on the digging tool, though.

**Comment by Napiophelios** [comment]
Shears is a pretty common tool used by several mods like plantlife and mobs,
I think it would be a good addition to the default collection of tools.

@C1ffisme  plantlife by VanessaE already sets node drops based on weilded item used to dig:
https://github.com/VanessaE/plantlife_modpack/blob/master/vines/functions.lua#L122

**Comment by xeranas** [comment]
> Similarly, leaves, flowers should not be diggable by hand, but instead require a tool?

Leaves for me is most time junk in inventory I would support idea to get leaves only when I intended (when using proper tool). However current flowers obtaining method seems fine for me. As flowers does not have seed obtaining problem I would opt-out them for now.

> Perhaps we can do something original like a sickle instead of scissors

Sickle? Why not scythe? No seriously minetest_game already have few sharp items which can do job. Why not re-use swords, at least up from iron version they should be sharp?

**Comment by sofar** [comment]
@xeranas a scythe would look too much like a hoe.

**Comment by xeranas** [comment]
@sofar it was joke :)

We should not add new tools unless we absolute need it. Right now it would be cosmetic addon rather than necessary.

From my point of view it was mistake to add scissors and now we cannot remove it because there already mods who depends on it. Same fate could be with sickle. After year or so another dev would think oh wait sickle does not make much sense and introduce toolC. And soon players will need infinity inventory to hold all of them. With every new tool comes new recipes which needs to remember.

> Perhaps we can do something original 

Whe already have nyan cat block. New skinned item or new block is not "original" stuff. For such tiny-bitsy optimisations we should reuse as much stuff as posible and move on more important stuff.

**Comment by sofar** [comment]
> it was mistake to add scissors and now we cannot remove it

there are no scissors in minetest_game.

Your last argument is nonsense: minetest_game isn't done, it's going to change whether you like it or not. If you don't want it to change, then check out a git copy and stop updating it.

**Comment by MT-Modder** [comment]
:+1: for solution 2 with increased drop rarity.

It's the quickest and most reasonable option IMO. Adding another tool for a single node drop is kinda silly. Since swords already handle snappy nodes there's really no need for it. Nevertheless, if shears or scissors had other specialty uses then it's a good idea. Otherwise it's just like the tin controversy...
1 use == pointless.

**Comment by sofar** [comment]
@MT-Modder I'm thoroughly in the Alton Brown camp that hates unitaskers :)

**Comment by MT-Modder** [comment]
I'm sorry but I don't know what you mean by that.

**Comment by sofar** [comment]
@MT-Modder a unitasker is a tool that has only a single application. The TV-chef and cooking scientist Alton Brown has a cooking show where he expresses his dismay at unitasker kitchen tools. It's just a pop reference.

**Comment by MT-Modder** [comment]
Ah gotcha now thanks. I don't watch that many cooking shows. :smiley:

**Comment by paramat** [comment]
I would support solution 2.
I seem to remember that PilzAdam is okay this cheat remaining.

**Comment by PilzAdam** [comment]
> If seed drops, do not drop grass node.

This is the current behavior, isn't it?

As @paramat said, I like it that you are guaranteed to get seeds even if you found only 1 grass node.  It helps if the player can't find a lot of grass and still wants to start farming (I found myself in that situation a few times; I walked a few minutes and only found about 5 grass).

If you really want to change that, then just make grass randomly drop nothing.

Btw, we already have tools for the `snappy` group: swords

**Comment by paramat** [comment]
I feel it's good to make it a little more challenging, like findng a jungle to find cotton seeds.
Luckily long grasses are much more common in mgv5/v7/flat/fractal/valleys. Even in mgv6 multiple long grasses are easy to find with a little traveling.

> This is the current behavior, isn't it?

Nope, i support dropping only 1 item, seeds or grass. Not sure about only grass 5 though, the distribution of grasses changes on a large scale meaning grass 5 is not always available.

**Comment by paramat** [comment]
So my suggestion is: for both grass and junglegrass, add 'max number of items = 1' as with sapliings, s that we can't generate infinite seeds from 1 piece of grass.

**Comment by sofar** [comment]
hmm the game seems to drop either seed or grass, but not both. This is done in ```farming/nodes.lua``` line 140

**Comment by paramat** [comment]
Oops just saw that.

**Comment by sofar** [comment]
So looking through this code and all the bits carefully (thanks to everyone who commented), I would like to only make one choice:

if wielding a ```snappy``` tool, drop ```default:grass_1```
otherwise, occasionally drop ```farming:seed_wheat```

This prevents the repeated planting of the same grass. I do like to make the game more difficult, and this is one of the things that's needed to make singleplayer vanilla more challenging (the other is a decent hunger mechanism that forces the player to farm for food).

**Comment by sofar** [comment]
Similarly, I'd make this same change for ```junglegrass``` and for all leaves as well - chopping leaves with a ```snappy``` tool should not yield saplings, either.

**Comment by paramat** [comment]
On this i thnk no change, repeated planting and digging is tedious anyway, and we can only get 1 seed from 1 grass, so it's not overly easy.

**Comment by 0-afflatus** [comment]
Big no to more tools. This isn't really an issue for me, it takes quite a lot of work getting started with farming as it is and I don't see how this would improve the game.

**Comment by Fixer-007** [comment]
I think solution 2 is good enough, will be nice to use it on jungle grass and leaves somehow.
