### ISSUE TITLE
Recipe type enforcing in new doors API

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest_game#842]
Cc: @sofar 

The new `doors` API imposes to use a recipe with a single material, whilst some doors require a set of different materials for crafting ([example](https://github.com/kilbith/xdecor/blob/master/recipes.lua#L218)).

I'm currently forced to set `material = ""` to register my own custom recipe outside of the function, but it leaves a hole in some crafting guides.

I call that a bad API design. Can we have the possibility to register a recipe the same way as `xpanes` [does](https://github.com/minetest/minetest_game/blob/master/mods/xpanes/init.lua#L178) ?

**Comment by sofar** [comment]
Yes, that's entirely reasonable to me. Want me to make the PR?

**Comment by kilbith** [comment]
Yes, go ahead.

**Comment by kilbith** [comment]
https://github.com/minetest/minetest_game/commit/363b95c0037997eae92fac75a15d1d28be2f6e04
