### ISSUE TITLE
Immortal group nodes are indestructible in Creative Mode

### ISSUE THREAD

**Issue by xeranas** [minetest/minetest_game#843]
It perfectly makes sense to make indestructible 'immortal' blocks on survival / regular playing time. However, on Creative Mode when I shaping map as map creator I want to able destroy all blocks.

**Comment by PilzAdam** [comment]
What nodes are talking about?

**Comment by xeranas** [comment]
@PilzAdam about those who are registered with group `immortal`. E.g:

```
minetest.register_node("some_mode:node", {
  ..
  groups = {immortal},
  ..
})
```

Founded on some legasy mod. Then misplaced some of these mods and I can't move it (destroy and re-build). Seems reproducable even without defined group (`groups = {}`).

**Comment by rubenwardy** [comment]
Creative doesn't necessarily mean map editor. I can imagine creative servers which might want immortal blocks for special areas.

**Comment by rubenwardy** [comment]
Just get that mod with the admin pickaxe

**Comment by xeranas** [comment]
@rubenwardy your case is more edge case than rule - for such cases mods should be used not for regular creativity mode. I first time heard about 'admin pickaxe' I wonder how many newcomers are in same spot as me? Is this mod at least maitained officialy (by minetest team). However it's temporally workaraound not a bug fix.

**Comment by 0-afflatus** [comment]
@xeranas surely this is an issue with the mod you have installed, not minetest_game. I have never encountered unbreakable blocks in the vanilla game.

**Comment by rubenwardy** [comment]
The development of minetest doesn't work like that, minetest_game is the only mod maintained by the core devs. If you have immortal nodes then you are using a non minetest_game mod anyway.

Immortal to me means undiggable by players. Here is how I've used immortal:

* flags - don't want people to try digging them as they're also represented in a lua table
* barriers for arenas
* travelnets, iirc

What nodes are you talking about?

It's much simpler to make immortal immortal in all cases. The admin pickaxe or similar tool is the best solution for this.

This is also not a bug either. It's a missing feature or a misbehaviour.

**Comment by xeranas** [comment]
> The admin pickaxe or similar tool is the best solution for this.

@rubenwardy how about additional privilege? "able_to_break_immortal" or something? At least it would not require special tool and it should be manageable in servers too.

**Comment by rubenwardy** [comment]
That would be a good solution.

**Comment by PilzAdam** [comment]
@xeranas ok, so you are not talking about a specific node here. As @rubenwardy said there might be legitimate reasons for mods to protect their nodes from being dug by the creative hand, so we can't make it just break everything.

Btw, the `immortal` group is only "valid" for entities. It has no predefined effect on nodes. What is rather making the nodes "immortal" is the lack of common digging groups.

There still is the case that nodes should be unbreakable in "normal" playing mode, but breakable in creative. To make this possible I would suggest to add a new group, e.g. `creative`, which is diggable by the creative hand but not by any other tool.

**Comment by rubenwardy** [comment]
Didn't know that

    * `immortal`: Disables the group damage system for an entity

https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L1100

**Comment by xeranas** [comment]
> I would suggest to add a new group, e.g. creative, which is diggable by the creative hand but not by any other tool.

At least developers would have group for this purpose. I which we could use some kind of default/fallback group for creative hand. Nevertheless this would improve situation in creative mode departament so I'm supporting it.

**Comment by paramat** [comment]
Open a new issue to request that.
