### ISSUE TITLE
New door api abm restricted to door mod

### ISSUE THREAD

**Issue by oleastre** [minetest/minetest_game#854]
I have a door mod that I can update quite simply to use the new API, but the current generated ABM expects the old node name to start with "doors:". 
My mod doors where registered with "os_doors" as prefix. I tried registering aliases, but it does not seem to work.
My only solution would be to customize the abm for my own mod, but what about exposing the abm registration in the api ? something like `doors.register_convert_abm(oldname, newname)`

**Comment by DonBatman** [comment]
The new doors mod limits the doors that can be registered. All doors that register to the doors mod will have to be called doors:name instead of the mod name. 
The crafting also makes it seriously limited since you can only use 1 material or group. For example the default wood door uses group:wood which means no one can use any wood as the craft for their doors. 

The choice will be to either change the doors mod to work with other door mods or the other door mods will have to duplicate the doors mod code.

**Comment by C1ffisme** [comment]
@DonBatman Actually, I saw a fix coming for the crafting thing in a pull request somewhere.

**Comment by DonBatman** [comment]
I found the crafting PR. It was closed 4 hours ago. 
Thanks

**Comment by oleastre** [comment]
I'd like to solve that issue with a PR, but I have three potential solutions.
First: I allow doors def to include a "modname" attribute that will replace all hard-coded "door:" with the mod name (in the significant places of course). 
Second: I add the conversion abm in the doors API; this will at least allow mods to trigger the conversion
Third: I add an optional "oldname" attribute in the door def and use that one in the abm instead of "doors:"..name

Any advice before I start coding ?

**Comment by DonBatman** [comment]
What if the : in the item string is converted to a _? mydoors:door1 would become doors:mydoors_door1.

**Comment by sofar** [comment]
I'm looking to provide a compatibility function in minetest_game that would do the hard work for you if you use the old API.

**Comment by oleastre** [comment]
My problem here is not really to be able to use the old API, but to have a simple way to convert old API based mods and worlds to the new one without having unknown blocks everywhere.

**Comment by sofar** [comment]
#858 

contains a change that would allow you to use the old registration call and get a working door (and your existing doors converted)

the ONLY thing you'd have to do is convert the bitmap and add it as a ```tiles``` property to the old api call. And the server warns about that as well.

**Comment by sofar** [comment]
@paramat, this can be closed now.

**Comment by oleastre** [comment]
Yes, after the #858 merge, the initial problem is solved. 
So, let's close this.
