### ISSUE TITLE
Join to AUR (ArchLinux User-community Repository)?

### ISSUE THREAD

**Issue by fujita-nozomi** [minetest/minetest_game#856]
if minetest_game is update everyday
why don't try join AUR(ArchLinux User-community Repository)?

**Comment by kilbith** [comment]
Already there (packaged in) : https://aur.archlinux.org/packages/minetest-git/

Also all you have to do is `git pull` in the `minetest_game` directory for updating.

**Comment by nerzhul** [comment]
As mentionned by @kilbith already the case
