### ISSUE TITLE
Placing nodes next to new doors

### ISSUE THREAD

**Issue by Ekdohibs** [minetest/minetest_game#863]
When you try to place a node next to a new door (using the door to build on), and you select the top half of the door, the node is still placed at the level of the bottom half. Moreover, you can't place a node above the door now.

**Comment by paramat** [comment]
@sofar

**Comment by sofar** [comment]
Yes, this is expected - the door mesh is the bottom part of the door.

I'd have to add a lot of code to handle exactly where and how the player is looking to try and calculate where to place the node, and I'd have to add this to ```minetest.register_on_placenode()``` since I can't hook it up to any of the door methods.

**Comment by paramat** [comment]
Sounds not worth 'fixing' it then, we shouldn't be building onto the door anyway. Ok to close?

**Comment by Ekdohibs** [comment]
Fine with me; I know this behaviour is expected but it still feels strange. However, it is minor, so feel free to close if you think it is not a problem, else, I guess it would be a "low priority, needs engine change" bug.

**Comment by sofar** [comment]
It's possible we can solve this by considering the use case "User right-click places a node on a mesh node that's larger than a 1x1x1 node box" - then you'd look to adding more logic to the core.on_place handler, which would be a decent solution and solves it for all oversized nodes.

**Comment by paramat** [comment]
Let's KISS.
