### ISSUE TITLE
No information as to how to craft items

### ISSUE THREAD

**Issue by everamzah** [minetest/minetest_game#869]
Currently Minetest Game lacks any information for the player as to how to craft items.  It would be useful to have this information available, especially once players start adding mods.

I would like to nominate jp's [Crafting Guide](https://forum.minetest.net/viewtopic.php?f=11&t=14088) mod to be included in Minetest Game.  It is a single craftitem that displays a crafting guide on `on_use`.  It would help round the default subgame out, and as a single mod is easily removed if need be.

**Comment by tenplus1** [comment]
+1 would be a great addition.

**Comment by MT-Modder** [comment]
:+1: Design is consistent with creative menu too (same designer). Then people would only have to remember one craft recipe...the guide.

**Comment by C1ffisme** [comment]
:+1:

Of course, if it includes functions to add other methods of crafting (grinding, alloy furnace, etc.) that would be even better.

**Comment by MoNTE48** [comment]
[(license : GPLv3)]

**Comment by sofar** [comment]
Not necessarily in favor, and licensing is inconsistent. I'm not a fan. This can stay a module for my taste.

**Comment by 0-afflatus** [comment]
I'm sure @kilbith's choice of licence will be for a strong reason.

**Comment by sofar** [comment]
His license choice is perfectly reasonable, and, since he's likely the sole author, if he wanted to merge this upstream, I'm pretty sure he would reasonably consider relicensing.

**Comment by kilbith** [comment]
Exactly. I don't wanna see some dickheads bundling my mod into a proprietary game. GPL preserves and perpetuates the freedom, unlike LGPL. It's up to Minetest Game to change.

**Comment by everamzah** [comment]
Sorry, I actually forgot MTG is licensed as LGPL.

http://www.gnu.org/licenses/why-not-lgpl.en.html

**Comment by paramat** [comment]
I would prefer this to remain an optional mod.

**Comment by JurajVajda** [comment]
I think the best one is unified inventory https://forum.minetest.net/viewtopic.php?id=3933 but also has to be recreated due to the license :/
