### ISSUE TITLE
Dye mod registers craft for magenta flowers, etc

### ISSUE THREAD

**Issue by everamzah** [minetest/minetest_game#878]
Dye mod registers 15 flower crafts.  This results in an unknown item for the craft recipe of any dye not derived directly from a flower.

![screenshot_20160228_132312](https://cloud.githubusercontent.com/assets/1761623/13381057/8b0db496-de1f-11e5-9398-6c7d72c8ce9b.png)

**Comment by Napiophelios** [comment]
I think this is an issue with the craft guide you are using.

I am using Zeg9's graft guide with no problems.
I don't get any unknown items in the craft guide;
just a lot of variant mixtures of dye with dye.

Also dyes can be made from things besides flowers.
Coal is manually added as a source for black dye,
maybe its better to come up with other in-game sources
for those lacking a direct source.

**Comment by everamzah** [comment]
Nonetheless, the craft is registered by MTG and is expecting - in the case of the screenshot above - a magenta flower.

**Comment by Napiophelios** [comment]
Okay, I see Zeg9 worked around it.
Your solution is legit. :+1:

**Comment by kilbith** [comment]
> I think this is an issue with the craft guide you are using.

No, it's not. There are trully groups of dye and flower with color correspondences that doesn't exist. The other crafting guides hide the unknown items, not mine for a reason : revealing the errors made in registrations.

**Comment by Napiophelios** [comment]
Yes sir everamzah has already enlightened me. :)

**Comment by PilzAdam** [comment]
It's not wrong to register recipes for groups that don't contain nodes (yet). See my comment in #879.

**Comment by 0-afflatus** [comment]
@PilzAdam agreed. This is not a bug so fix not required.

**Comment by paramat** [comment]
Agree with PilzAdam.
