### ISSUE TITLE
Suggestion: Make tree block differences more meaningful

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#882]
Hi. Currently, we have now 5 kinds of trees but they seem to be all the same, just with a different texture and biome, but there is no gameplay difference.

I suggest to change that to tweak some values to add more variation to Minetest Game. For the player this would mean more variation and the kind of tree you chop will actually matter.

My suggestions:
* Unique fuel burning time for each tree
* If possible, change mining times, so some trees are easier/harder to dig
* Maybe make some tree types minable only from a certain axe level where “easier” trees can be mined with hand and “harder” ones need axes at level X or better. I suggest to have at least one tree which can be dug by hand (to get started) and at least one tree which needs steel axe or better.

Suggested new burning times:
Pine Tree:	32
Aspen:		29
Tree:		27
Acacia Tree:	25
Jungle Tree:	22

Pine wood:	7
Aspen wood:	6
Wood:		5
Acacia wood:	5
Jungle wood:	4

Pine fence:	16
aspen fence:	15
wooden fence:	15
acacia fence:	15
jungle fence:	14

(maybe other wood-related items need to change as well? I don't know)

Suggested mining times/mining level (roughly):
Pine Tree: High
Aspen: High
Tree: Medium
Acacia Tree: Medium
Jungle Tree: Low

So. What do you think about the idea?

**Comment by MT-Modder** [comment]
:+1: I personally think the unique burn and dig times are a good idea, but we should be cautious of over complication. I don't think the player should have to make tools to dig trees, especially if they spawn in a huge taiga biome, they might have to spend a while trying to find breakable trees.

**Comment by C1ffisme** [comment]
:+1: This is a decent idea. I would also make the different types of wood furniture look different, such as fences and planks. Rather than just being a different color, looking a bit more oriented towards different cultures/time periods would be a bit fun.

**Comment by paramat** [comment]
Certainly the rainforest hardwood could have a requirement for a stone or steel axe.
Although the idea is ok i'm not keen on the extra code for minor burn time differences.

**Comment by 0-afflatus** [comment]
I think different burn times and dig times are a good idea in general. Some woods rot on contact with dirt or water, although that may be taking realism too far, but certainly introducing a mechanism that means certain woods are better for some tasks than others could add an interesting game-play element.

I'm not so sure about the mining level - most trees can be felled and split with stone-age technology, albeit not necessarily using an axe as such. Also, from a game-play POV you need wood to be able to mine, so needing a steel axe for jungle trees, would make jungles a no-go area for players at a 'primitive' tech level. That doesn't make sense to me and I think would confuse and irritate players.

**Comment by rubenwardy** [comment]
Taking longer to dig is OK, but I don't like the idea of being impossible to dig without steel etc tools.

**Comment by Wuzzy2** [comment]
OK, then. I retract the part of my suggestion to make some trees diggable for axes only.
Higher-level trees might be possible if there would be some way to guarantee the player will spawn in a certain biome. But for now it seems the player can spawn pretty much everywhere, so I see we have the problem the player might spawn in a biome where it is not possible to get wood with hand only.

**Comment by paramat** [comment]
Agreed, sometimes in mgv7 a player will spawn in a rainforest that is huge and the only wood for a long distance. Longer dig times for hardwood is okay though.

**Comment by tenplus1** [comment]
+1 for different burn times.

**Comment by sofar** [comment]
Since jungles are so densely populated, I would suggest requiring at least a wooden axe to cut, but certainly not steel. The rest of the trees should be punchable by hand.

From a casual perspective (i.e. real-life), aspen would be the lightest tree, and so it would have the shortest burn time, followed by apple, then acacia / pine and finally jungle, with the longest burn time.

**Comment by 0-afflatus** [comment]
Pine burns faster (and hotter) than apple wood.

> Since jungles are so densely populated, I would suggest requiring at least a wooden axe to cut,

Same problem, where does the player get the wood from?

**Comment by sofar** [comment]
I'd have no problem with a player having to get their initial wood outside of a jungle. Jungles are relatively rare and due to the biome system there's usually other trees around them.

**Comment by C1ffisme** [comment]
Or we could require the player to dig underneath the tree, and add some kind of tree-capitator thing. But that would ask the question: Why don't trees fall down when I cut them, and do when I dig under them?

**Comment by rubenwardy** [comment]
> Since jungles are so densely populated

could just make it painfully slow to dig. We don't want people getting trapped

**Comment by sofar** [comment]
> could just make it painfully slow to dig.

sure, I'd be ok with that.

**Comment by Ekdohibs** [comment]
:+1: for different burn times too, I was also wondering: what about adding some kind of "heat factor" to fuels, that would change the speed of cooking items? (i.e. pine wood would last less long than apple wood, but would cook items faster for example)

**Comment by paramat** [comment]
Nope that's over-complex.

Wood and stone axes have the same level, so the only option is to make steel axes essentail for hardwood.

**Comment by sofar** [comment]
The alternative would be to allow punching the junglewood, but not drop items.

**Comment by Ekdohibs** [comment]
@paramat I agree heat factor adds some complexity, but don't you think it would be more interesting gameplay-wise to have more differences between different fuels?
@sofar I don't like the punch-and-don't-get-items a lot, just making it slow would be better imho.

**Comment by paramat** [comment]
Well i'm neutral about differing burn times, not opposed, that's enough to add some difference.

**Comment by sofar** [comment]
Slow is fine too, I'm fairly indifferent on the proposed changes here. Heat factor would be overly complex, I think.

**Comment by paramat** [comment]
Note all tree trunks must be breakable by hand because new players often end up spawned inside them.

**Comment by DonBatman** [comment]
If leaves randomly dropped sticks and sticks craft into wood then all trees could require an axe.

**Comment by C1ffisme** [comment]
@DonBatman Or maybe wood tools should just be removed, and replaced with flint tools? (Or flint would be a replacement for stone when crafting stone tools.)

Then, to make your first set of tools, you would need to dig some leaves and gravel to get sticks and flint. Craft a stone axe to chop down a tree for more wood, craft a stone pick to get more stone, and your all set.

**Comment by paramat** [comment]
#1270 #1276 merged.
