### ISSUE TITLE
Suggestion: Steel fence, steel sign, steel ladder

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#883]
I suggest to add the following blocks:
* Steel fence
* Steel sign
* Steel ladder (DONE!)

(As opposed to wooden fence, wooden sign and wooden ladders, made from steel ingots instead of wood)

Because wooden fence, wooden signes and wooden ladders might all burn. The steel versions can be a way to safely build stuff near lava (at a price).
IMO a steel ladder would be very useful, I don't know how many times my ladders just burned because of lava. xD

**Comment by MT-Modder** [comment]
:+1: No more burning!

**Comment by kilbith** [comment]
I'm against. Too "industrial", best for Technic game.

**Comment by PilzAdam** [comment]
I'm generally against adding the same stuff made out of different materials. But for this special case there is a valid reason to add these: the existing signs / fences / ladders are all flammable, as @MT-Modder pointed out. So :+1: from me.

**Comment by kilbith** [comment]
Some steps forward the cluttering... You were the last warrant against that, PilzAdam.

**Comment by PilzAdam** [comment]
@kilbith maybe view it from the other side: what is the reasoning behind making all ladders, fences and signs burnable? Is there an inherent physical law in the Minetest world that prohibits writings on non-burnable materials?

**Comment by kilbith** [comment]
IMO the nodes should be exposed to this risk for the challenge and must be "low-tech" since it's handcrafting. Also by extension the beds and shelves should have a steel version ? Why defining an arbitrary limit up to the ladders and fences ?

**Comment by C1ffisme** [comment]
Fence : Eh, I'm nuetral. The birch fences might work since they are pretty darn white.

Sign : Maybe, but if it is industrial, I think a screen would fit better, although not really in vanilla minetest.

Ladder : I dunno. I would use stairs if you absolutely need to.

**Comment by MT-Modder** [comment]
Good points from all angles.

@kilbith True but some nodes are used more than others, and the player should have the ability to overcome the risk of burn if they have the materials to do so. Odds are your not going to craft 99 beds, but you will craft 99 ladders and way more often than you would beds.

@C1ffisme About using stairs - you can but it's a lot more digging for the player.

IMO steel fences are useful but not as needed as steel signs and ladders, those things are constantly being placed underground or near lava. I personally have never used fences below the surface, though that doesn't mean I never will.

**Comment by C1ffisme** [comment]
@MT-Modder I think that although steel ladders would fit in an industrial enviroment, they would be expensive to the point of uselessness in survival. You can make stone stairs for a much, much cheaper price.

We kind-of have steel fences. Those are iron bars. They work about the same way, and are actually a lot cheaper than fences.

@PilzAdam 

> Additionally, we should consider making wooden chests burnable, and adding steel chest (as a sort of higher-tier chest, that can resist fire (and maybe explosions?)).

This would be good for PVP servers, but not servers where all you want to do is build. Maybe it would replace the locked chest?

I would make the resistant chest out of obsidian, since steel blocks can be broken with an explosion.

**Comment by Wuzzy2** [comment]
Steel ladders are intended to be used rarely, where you really need them like in lava caves. Everywhere else the wooden ladders should totally suffice. :)

> and are actually a lot cheaper than fences.

We have not yet discussed crafting recipes. I'd argue we could adjust the “cost” easily by just tweaking the output number. But again, the stuff should not be cheap, this is intentional.

**Comment by C1ffisme** [comment]
@Wuzzy2 
> The player would probably figure out it is not a good idea to waste precious steel ladders for 100 nodes when there is no lava at all.

Yes... But I don't know if I have ever needed to use any kind of ladders while mining.

But you still haven't given your opinion on the steel sign...

**Comment by paramat** [comment]
:+1: For steel fences and ladders, needed anyway for a more modern look. I'll work on this.

**Comment by 0-afflatus** [comment]
Metal fences are great - I'm fairly sure they are pre-gunpowder tech if you think in terms of pig-iron rather than steel. Even just as a decorative item they can be used in situations where wooden fences just don't make sense - fire dogs, and chimney cranes for example.

Don't know about signs, but metal ladders have a clear use case as we've already discussed.

**Comment by kilbith** [comment]
I made a steel ladder texture, derived from Gambit's ladder texture : 

![capture d ecran de 2016-03-01 15-09-21](https://cloud.githubusercontent.com/assets/7883281/13429299/e1df9cca-dfbf-11e5-975b-6634b5f7d943.png) ![default_ladder_steel](https://cloud.githubusercontent.com/assets/7883281/13429304/e6d536ae-dfbf-11e5-9ee5-72c90e2f725f.png)

**Comment by NathanSalapat** [comment]
I agree, steel ladder is needed, sign and fence I'm neutral on. A wall of cobble will stop somebody from falling into lava as well as a fence would. I guess it's a visual thing.

**Comment by paramat** [comment]
Nice texture.

**Comment by 0-afflatus** [comment]
Excellent ladder texture.
Metal fences (if desired) may as well be constructed in a similar manner to wooden fences using the steel block texture.

**Comment by C1ffisme** [comment]
@kilbith That ladder texture is pretty good, I think I could find some use for it in an industrial setting (Nuclear Power Generator, Research Facility, Playgrounds even).

**Comment by paramat** [comment]
I would like these for release.

**Comment by Ekdohibs** [comment]
:+1: for steel ladder too, I'm neutral on the others.

**Comment by kilbith** [comment]
Gambit made a sign with a steel plaque : 

![capture d ecran de 2016-03-03 11-02-11](https://cloud.githubusercontent.com/assets/7883281/13490938/a6fc5a5a-e12f-11e5-8b01-ce0b6ffaa3e9.png) ![default_sign_plaque](https://cloud.githubusercontent.com/assets/7883281/13490946/ab1c7eda-e12f-11e5-8251-164eb6eda0e1.png)

**Comment by PilzAdam** [comment]
If #796 is added then we don't need steel fences anymore, since we have non-burnable fence-like nodes then.

**Comment by PilzAdam** [comment]
@C1ffisme 
>  >Additionally, we should consider making wooden chests burnable, and adding steel chest (as a sort of higher-tier chest, that can resist fire (and maybe explosions?)).
>
>This would be good for PVP servers, but not servers where all you want to do is build. Maybe it would replace the locked chest?

There are protection mods on servers that focus on building anyway. Also PVP is not the only use-case for this; e.g. building near lava should be challenge (you have to watch out that your stuff is not burning).

Replacing the locked chest might be a good idea, since we have the same mechanic for steel doors.

**Comment by C1ffisme** [comment]
@PilzAdam Yeah, It makes sense.

Although, what would the recipe look like, so that it doesn't look like a steel block? Maybe 8 steel with an obsidian lock?

![screenshot_20160303_114038](https://cloud.githubusercontent.com/assets/9893266/13503421/effd2856-e134-11e5-8d6a-b95e3bec9c34.png)

**Comment by 0-afflatus** [comment]
Just 8 steel?

**Comment by C1ffisme** [comment]
@0-afflatus It's a locked chest, so pretty important early in-game. Of course, this recipe isn't really that cheap, maybe replace the obsidian lock with a chest, and just make it a steel chest.

**Comment by 0-afflatus** [comment]
I was suggesting just the 8 steel, so it matches the wooden chest recipe. There isn't really any need for an extra 'lock' node.

**Comment by Wuzzy2** [comment]
How did this issue turn into a discussion about chests? xD
Can we please focus on fences, signs and ladders for now?
If you really feel the need for a new chest and stuff, I think it might be better to file a new issue. I really don't get the point anyways.

Back to topic:
I am okay with the particular steel ladder in #892.
I would drop my suggestion for steel fences if the stone walls are added, like previously mentioned in this discussion. I could swear someone posted it here but now it's gone?
I stick to steel signs, you'd need those if you want signs near lava. With wooden signs this would simply not be possible. I am okay with the posted texture.

Suggested recipe for signs:

```
Steel Ingot, Steel Ingot, Steel Ingot
Steel Ingot, Steel Ingot, Steel Ingot
Empty, Stick, Empty
```
Yields 3 steel signs. So, statistically, you need 2 steel ingots and 1/6 sticks for 1 sign. Sounds fair enough for me, and I consider signs to be “luxury” anyways. ;-)

**Comment by C1ffisme** [comment]
@0-afflatus Ah... okay. Sorry, I wasn't getting your sentance correctly. I thought you meant that 8 steel was too cheap for a locked chest.

**Comment by 0-afflatus** [comment]
> How did this issue turn into a discussion about chests? xD

Sorry @Wuzzy2 I do need to reign in the old ADD sometimes.

**Comment by paramat** [comment]
Steel signs are approved #895 and steel fences not needed so closing.
