### ISSUE TITLE
Non-wood doors have wood sounds

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#886]
There is a minor problem with doors and trapdoors: They all have the “wood” sound assigned to them, even the steel, glass and obsidian glass ones.

**Comment by C1ffisme** [comment]
I think there is already an issue / pull request on this.

**Comment by paramat** [comment]
Sofar submitted a sound for the steel door but it was too harsh and tinny. My suggestion is to use a car-door sound for a nice solid 'thunk'. Then some kind of non-woody sound for glass door.

**Comment by C1ffisme** [comment]
@paramat I think the glass door should have a quiet clicking sound, since you have to carefully close it (since, well, it's made of glass).

**Comment by sofar** [comment]
@paramat I'm open to digging into good sounds. Can I have a 'wee' squeek when the metal door opens? :)

**Comment by sofar** [comment]
#758 was reopened with different steel door sounds.

**Comment by paramat** [comment]
758 merged. An individula sound for glass doors would be good, or use a quieter steel door sound for now.

**Comment by paramat** [comment]
I think we should use a much quieter version of the steel door sound for the glass door, it's better than a wooden sound.

**Comment by paramat** [comment]
#1152 is merged.
