### ISSUE TITLE
Add metal sounds for metal nodes

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#887]
We have a couple of nodes made of metal, yet they all use the “stone” sound.

I think it is time to add some sort of “metal” sound set (footstep, mining, etc.) for all nodes made out of metal.

I.e.:
- Steel door
- Steel trapdoor
- Steel block
- Copper block
- Gold block
- Bronze block
- Iron bar
- etc.

**Comment by C1ffisme** [comment]
If you have some sound examples, they would be quite helpful...

**Comment by paramat** [comment]
1m cube blocks of metal have a very solid sound, not much different to stone.
For steel door and trapdoor see your other issue, a new sound would be good.

**Comment by C1ffisme** [comment]
@paramat Yes, but doors, trapdoors and iron bars are not 1m^3 cubes.

**Comment by paramat** [comment]
C1ffisme see my 2nd sentence.

**Comment by C1ffisme** [comment]
Well... This is a good sign I need to read through posts more.

But yes, metal sounds would be good.

**Comment by paramat** [comment]
Sounds for xpanes iron bar and the new steel ladder would be good.

**Comment by sofar** [comment]
I've reopened #758 with different, and better sounds. Please give it an ear!

**Comment by Fixer-007** [comment]
Steel ladder also need some sound.

**Comment by paramat** [comment]
758 merged.

**Comment by sofar** [comment]
please close?

**Comment by paramat** [comment]
See #1334

**Comment by Wuzzy2** [comment]
Metal things have sounds now, this can be closed.
