### ISSUE TITLE
Mushrooms appear in jungle

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#888]
I don't know if this is intentional but I mention it here anyways because it looks like a bug.
It is possible for mushrooms to appear in jungles. They like to spawn on that horizontal jungle tree trunks on the ground.

**Comment by C1ffisme** [comment]
I would think it's intentional, have you heard anywhere that they shouldn't be doing this?

**Comment by Wuzzy2** [comment]
Well, I thought mushrooms are limited to decidous and coniferous forests.
Whatever, it is not important.

**Comment by Fixer-007** [comment]
I've noticed that too, but maybe they actually grow in jungles?

**Comment by C1ffisme** [comment]
@Wuzzy2 I haven't read that anywhere... I'm guessing you just hypothesised it?

**Comment by MT-Modder** [comment]
Mapgen v6: (Not biome specific)
https://github.com/minetest/minetest_game/blob/master/mods/flowers/mapgen.lua#L24

Mapgen v5 or v7: (Biome specific)
https://github.com/minetest/minetest_game/blob/master/mods/flowers/mapgen.lua#L105

**Comment by C1ffisme** [comment]
@MT-Modder Well, that would make sense.

**Comment by MT-Modder** [comment]
Okay I found where it is:
https://github.com/minetest/minetest_game/blob/master/mods/default/mapgen.lua#L1074

As you can see they do in fact spawn in rainforest and rainforest swamp biomes. Not a bug.

**Comment by paramat** [comment]
I would expect warm, humid and dark jungle to be ideal for mushroom growth.
