### ISSUE TITLE
beds: Allow opting-out of night-skip check

### ISSUE THREAD

**Issue by 0-afflatus** [minetest/minetest_game#889]
As server admin I want to allow players to use beds to skip the night without having to use them myself. I also want to extend this possibility to other players who don't care one way or the other.

Rather than check_in_beds checking all connected players, it would be great to only check players who have beds, that would be simplest from a game-play POV. having tried hacking on this I know it may not be quite that simple.

**Comment by C1ffisme** [comment]
> it would be great to only check players who have beds

That would mean that if only one person had a bed, then he would basically have power over the server's day/night schedule, until someone else crafts a bed.

What about being able to add exceptions to check_in_beds with a command? (```/ignorebeds```, ```/stayup``` or even ```/allow_to_get_insomnia``)

**Comment by 0-afflatus** [comment]
> That would mean that if only one person had a bed, then he would basically have power over the server's day/night schedule, until someone else crafts a bed.

That would be my preferred behaviour. In my experience new players don't mind it being day.

**Comment by C1ffisme** [comment]
> In my experience new players don't mind it being day.

@0-afflatus Yes, that is true, but for any server (with a pretty decent computer) that uses nocturnal mobs, this player can remove the other's ability to get items this way. (And just think of a server like this where the only wool comes from spiders, the player is pretty powerful.)

I suppose this player could be banned, but what for? He isn't hacking or cheating, he is just using the game's advantages for his own purposes.

**Comment by 0-afflatus** [comment]
> this player can remove the other's ability to get items this way.

Not really, players can opt-in by making a bed. If a server owner doesn't want players to be able to skip night, that is already configurable. At the moment any one player can block night-skip simply by not going to bed and in my case that is usually me because I rarely want to stop what I'm doing to travel halfway across the map to find my bed. This makes the night-skip function practically useless.

I could really do with some practical suggestions of how to code this, we can test out hypothetical edge cases once there is a PR.

The opt-out could be limited to players with a particular admin priv, but I'd prefer it to be globally available.

**Comment by paramat** [comment]
@tenplus1 thoughts on this? Want to update your beds PR?

**Comment by paramat** [comment]
Anyone want to code this? I'm not interested in doing so and most MTG devs are absent.

**Comment by paramat** [comment]
Issue is a year old. If someone wants this they have to code it, no MTG dev is interested in doing so.
Will close in 1 month.

**Comment by paramat** [comment]
@sofar any thoughts?

**Comment by paramat** [comment]
Nope.
