### ISSUE TITLE
Typo in crafting Lua 

### ISSUE THREAD

**Issue by Napiophelios** [minetest/minetest_game#902]
https://github.com/minetest/minetest_game/blob/master/mods/default/crafting.lua#L769
needs to be changed to "default:ladder_wood",

https://github.com/minetest/minetest_game/blob/master/mods/default/crafting.lua#L793
needs to be changed to "default:sign_wall_wood"

Also fuel/burn times for other wood type fences are missing.

**Comment by paramat** [comment]
Fixed.
