### ISSUE TITLE
Doors that were removed by being burned (fire mod) are leaving hidden nodes.

### ISSUE THREAD

**Issue by everamzah** [minetest/minetest_game#909]
@sofar 

I'm having a hard time placing a node where there was a wood door that burned down.  This is current master, with the new on_burn(), and no changes to minetest_game.

I think the hidden top is remaining behind, but I have no way to remove it.

**Comment by sofar** [comment]
Reproduced this bug. Implemented a fix and verified that with the fix, a fire doesn't leave door tops on the map.
