### ISSUE TITLE
Falling nodes on top of new doors are falling

### ISSUE THREAD

**Issue by Ekdohibs** [minetest/minetest_game#923]
To reproduce, place a falling node above a new door (sand, or even more visible, snow). The node is falling, and so is not diggable either. Moreover, this creates an entity which is used for static purposes only.

**Comment by paramat** [comment]
@sofar

**Comment by sofar** [comment]
Try the patch in #926

**Comment by sofar** [comment]
I'll have to dig deeper. I can't make the top part walkable since then you can't walk *through* a door.

**Comment by sofar** [comment]
I think I can make it ```buildable_to```. Reading the code this may just fix it.

**Comment by sofar** [comment]
Please test #928. Make sure to re-place all your doors.

**Comment by paramat** [comment]
928 merged

**Comment by everamzah** [comment]
Placing a door under a pine tree with snow, and digging the pine needles above the door results in a stuck entity.

![screenshot_20160322_084952](https://cloud.githubusercontent.com/assets/1761623/13952135/12a559f2-f00b-11e5-895d-7c49db135d9a.png)

**Comment by sofar** [comment]
I'll check this, but it sounds oddly similar to the sand block stuff. Did you update and place new doors?

**Comment by kilbith** [comment]
Can't reproduce that.

**Comment by sofar** [comment]
@everamzah can you verify you were running latest minetest_game and try to reproduce again?
