### ISSUE TITLE
Add sandstone wall

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#934]
For now there is grey, red and green coloured walls, yellow (sandstone) wall will greatly help when building in savannah and desert.

@paramat feel free to close it down if people are negative about it.

**Comment by kilbith** [comment]
No, extensible walls are made out from cobbles. Not a carved, non-rustic, single-piece material.

Other reasons : you already can get desert cobbles in desert and it looks good enough in savannah too. Also this is a slippery slope to support other materials. 3 walls are fine already, so :-1:

**Comment by C1ffisme** [comment]
Wooden fences are usually yellow or white enough to cover these colors.

**Comment by paramat** [comment]
This is more an issue for adding sandstone cobble.

**Comment by kilbith** [comment]
FWIW, PixelBOX's sandstone is already cobble-looking : 

![screenshot_20160317_000241](https://cloud.githubusercontent.com/assets/7883281/13831391/badf5730-ebd3-11e5-9163-7f539ae46b88.png)

**Comment by sofar** [comment]
I'm against adding sandstone cobble. Sandstone is a very soft stone that can literally be cut and shaped with your hands, and is generally "cut" with long saw blades. As such, you don't get cobble at all, but nicely shaped pieces.

Don't give me any nonsense that minetest isn't about realism. It's sandstone, not gnucydur or gobbledetite. ;^)

**Comment by paramat** [comment]
Agreed i'm not keen on sandstone cobble.
Sandstone walls maybe ..

**Comment by paramat** [comment]
:-1:

**Comment by Fixer-007** [comment]
Sandstone walls, not cobble sandstone

**Comment by paramat** [comment]
Closing as PR has 3 -1s.
