### ISSUE TITLE
Bad collision box of opened fence gate

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#936]
If you place a single fence gate in open space, you will collide with the gate but not with the right fence post. You can just walk through it, as if it is not there.

**Comment by NathanSalapat** [comment]
I think this was done so when placing two fences next to each other you'd get a double wide opening, easier to get mobs to move through it.

**Comment by Wuzzy2** [comment]
This may be true, but sadly, this breaks single fence gates standing alone on the field.

**Comment by paramat** [comment]
Yes it's intentional.

**Comment by NathanSalapat** [comment]
Is the one pillar on the side needed? could that just be removed and then there wouldn't be any issues, unless that pillar was there for a reason, which it probably was.

**Comment by paramat** [comment]
I guess it's there for fence to connect to.
