### ISSUE TITLE
Add scissors

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#939]
I suggest to add scissors. This should be a tool to mine `group:snappy` efficiently (such a tool is currently missing and hand is too slow).

**Comment by MT-Modder** [comment]
:-1: If it had another, maybe special, use then okay but swords are designed for ```group:snappy```. Somewhat related: https://github.com/minetest/minetest_game/pull/348

**Comment by Wuzzy2** [comment]
Yes, but it makes durability go down fast.

**Comment by C1ffisme** [comment]
@Wuzzy2 Well, it's meant to work like other tools. Since we don't have mobs, we might as well make swords be used for cutting grass/shrubs.

**Comment by Wuzzy2** [comment]
I see. Other opinions?

**Comment by Napiophelios** [comment]
I disagree. Swords are weapons. And they wear out quickly.

Default mod should have tools and items that can be used by 3rd party mods 
so that each mod maker doesnt have to keep reinventing things 
every time such an item is needed.

Depending on what mods you are using, you can end up with all kinds of wooden bowls and shears..just because they are common tools/items necessary for continuity

**Comment by PilzAdam** [comment]
> such a tool is currently missing

We have swords for digging snappy nodes.

> Since we don't have mobs, we might as well make swords be used for cutting grass/shrubs.

They already have are used for cutting snappy nodes.

> Whats really ridiculous is that the game has swords...and their only use is to pick flowers :)

They are used for PVP, too.

**Comment by C1ffisme** [comment]
> > Since we don't have mobs, we might as well make swords be used for cutting grass/shrubs.

> They already have are used for cutting snappy nodes.

Okay fine, I'll get my sentence completely right, they will **stay** being used for cutting grass/shrubs.

For the record, it's hard to see what I'm typing with Github's bright white background.

**Comment by MT-Modder** [comment]
The idea to add scissors was also discussed here: https://github.com/minetest/minetest_game/issues/838

And like I said here and in that issue one use is just simply not enough. Unless that one use is worth while like TNT for example.

Maybe if some simple mobs (1 animal, 1 monster) were added swords could be combat only then scissors could be added for snappy nodes, but that's not going to happen for a while, if at all. Not to mention the big change unsuspecting players would face.

**Comment by C1ffisme** [comment]
@MT-Modder Adding 2 entire mobs just to add scissors is a little silly... That would be like buying a gallon of yellow mustard for one (family of 3 people only) hot dog/burger night.

Not sure what grocery store sells that much mustard, but you get my analogy.

**Comment by MT-Modder** [comment]
@C1ffisme Right, the idea would be to add the scissors only if the mobs were added, not to add them just for the scissors. It's just an example for switching the use of swords to combat only, thereby opening the use of scissors on plants and the like.

Like I said that's not going to happen for a while, if at all.

**Comment by C1ffisme** [comment]
@MT-Modder Hopefully at all, if in a while. (Maybe 0.5 or 0.5.1 will give us a C++ mob API?)

But back on topic, adding scissors might have to wait until swords get any other use at all. Maybe if sheep were added, then scissors might have an alternate use, though.

**Comment by MT-Modder** [comment]
Or maybe vines?

**Comment by Napiophelios** [comment]
so whats the in game purpose for the vessels mod? 
we can place empty glasses..what else?

**Comment by MT-Modder** [comment]
And mese crystal fragments...

I personally think these things should be showcased and not just available for mods to add-on to. While the general theme of minetest_game is to be an API for mods to expand upon, it shouldn't add functionality and not use it. It's a little redundant. Like adding craft recipes for things that don't exist yet.

**Comment by C1ffisme** [comment]
@Napiophelios Bottles can be used for decoration, although a use in making potions or something might be nice.

@MT-Modder I very much agree, the stuff in Minetest Game should have a main game use, as well as a use for modders. Maybe mese crystals could make healing potions?

**Comment by paramat** [comment]
:-1: I'd prefer to use axes on snappy.

**Comment by paramat** [comment]
Assuming PilzAdam disapproves, 3rd disapproval from nore http://irc.minetest.ru/minetest-dev/2016-07-10#i_4647264
