### ISSUE TITLE
Wooden sign can only be digged by axes

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#942]
Picaxes, swords, shovels and hands are not able to dig wooden signs.

**Edit: In stable 0.4.13 it was breakable by hands, wooden tools/swords (and stronger), except of hoes**

**Comment by kilbith** [comment]
Normal, it's `choppy` and has always been.

**Comment by Fixer-007** [comment]
>Normal, it's choppy and has always been.

No it is not, it was diggable by practically anything before in 0.4.13 stable, checked.

**Comment by paramat** [comment]
Should be breakable by hand i think.

**Comment by Fixer-007** [comment]
>Should be breakable by hand i think.

In stable 0.4.13 it was breakable by anything (hands, wooden tools/swords and up, except of hoes).

**Comment by C1ffisme** [comment]
I dunno if we should change this. It would stop some griefing near spawn if a server has no protection mods whatsoever. An anarchy server could have some signs for rules (not quite an anarchy server, i guess), and then a drop point into water where the player can then get an axe.

**Comment by PilzAdam** [comment]
Seems like the addition of steel signs removed the `dig_immediate = 2` group rating from wooden signs. I label this as a bug since it's (at least for me) an unnoticed and unwanted change.

**Comment by kilbith** [comment]
> I label this as a bug since it's (at least for me) an unnoticed and unwanted change.

You ordered me to remove the `snappy` group, since it's essentially similar to `dig_immediate` (except for the wearing) I assumed I could remove it as well.

**Comment by paramat** [comment]
960 merged.
