### ISSUE TITLE
Players bed are not owned after sleep on it

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#943]
I've noticed that after placing my bed (from creative inventory) and sleeping over it won't register at as owned by me, for some reason, so anyone can sleep on it.

**Comment by sofar** [comment]
I don't think this was ever the case, though.

**Comment by sofar** [comment]
This should be marked "not a bug". I'm also pushing #955 which addresses the spawning in others' protected areas, which I think is sufficient.

**Comment by paramat** [comment]
955 merged
