### ISSUE TITLE
Leafdecay doesn't work together with degrotate

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest_game#947]
If mods add leaves with plantlike drawtype and random rotation using degrotate as param2, leafdecay doesn't work for them because if param2 isn't 0 it thinks a player placed it.

If leafdecay tests if param2 is 1 instead of testing if it's not 0, the problem would be solved (fairly).
To not break something, group leafdecay_type=2 means that only param2=1 are not decayed whereas group leafdecay_type=1 makes it decay the current way.

l tested the speeds:
https://gist.github.com/HybridDog/e8b6e64303671edbe734

setting meta is ~  4.7 times as fast as setting node with param2
but getting node param2 is ~ 1.5 times as fast as getting meta

meta takes a lot more memory and disk space l guess
and tests if it should decay happen far more often than configuring the node if it shouldn't decay

**Comment by MT-Modder** [comment]
Maybe we should move it to a boolean in metadata...but that might be slower. Simply set it to true after it's placed. That way it won't interfere with rotation.

**Comment by HybridDog** [comment]
metadata is sent to clients, param2 also, but leafdecay works only server side

**Comment by MT-Modder** [comment]
Right but IDK the read/write speed of metadata vs param2...if there is a difference.

**Comment by HybridDog** [comment]
l tested the speeds:
https://gist.github.com/HybridDog/e8b6e64303671edbe734

setting meta is ~  4.7 times as fast as setting node with param2
but getting node param2 is ~ 1.5 times as fast as getting meta

**Comment by MT-Modder** [comment]
Thanks! I would have never guessed.

We should probably convert the leaf decay abm into a nodetimer as well. Maybe I'll submit a PR rewriting leaf decay, unless you'd like to do it?

From param2 --> metadata and abm --> nodetimer.

@paramat and @sofar 
What do you guys think?
This would fix the rotation problem and probably optimize leaf decay.

**Comment by HybridDog** [comment]
Using node timer is a nice idea l think
```
P(time) = (chance-1)^(time/interval-1)/chance^(time/inverval)

P ∈ [0;1]
time(P) = (log(P*chance)/log(1-1/chance)+1)*interval
 ```
the time in seconds needed to be set for compatibility is  ```(math.log(math.random()*5)/math.log(4/5)+1)*2 ```

**Comment by HybridDog** [comment]
idk why l wrote group facedir

**Comment by sofar** [comment]
I'll have to look at leafdecay as a whole design before making a decision. I haven't looked into it at all yet.

**Comment by HybridDog** [comment]
catch_up is not disabled in the abm btw

**Comment by paramat** [comment]
Degrotate was never intended to work with leafdecay.

**Comment by sofar** [comment]
As a general comment on ABM's vs. NodeTimers, I'd like to point out that NodeTimers are great for things that -over time- stop. Whereas ABM's are generally more efficient when things will continuously be happening.

I'm not entirely sure that replacing the leafdecay code with inserted node timers in leaves is a good idea. It means a lot of timers will be have to get inserted (when? how?) and these are all going to tick over and over again unless node removal criteria are met. While I am no fan of the current code, it serves it purpose well.

**Comment by MT-Modder** [comment]
Okay I wasn't sure. Thanks for looking into it though and for the useful info.
