### ISSUE TITLE
Fire is slow and dies  out easily

### ISSUE THREAD

**Issue by FaraoneLele** [minetest/minetest_game#949]
if I give fire to a tree the wood does not burn, if they are in a biome without snow, if they are in a snowy biome

**Comment by C1ffisme** [comment]
If you give "focus"???

Please explain what this 'focus' is.

**Comment by FaraoneLele** [comment]
the fire, sorry : )

**Comment by C1ffisme** [comment]
A screenshot might be handy.

**Comment by FaraoneLele** [comment]
![screenshot_20160318_175803](https://cloud.githubusercontent.com/assets/17162630/13885492/fb72bfa2-ed32-11e5-8593-674062c849c9.png)

**Comment by C1ffisme** [comment]
Are you using perma-fire, or normal fire? I tried permanent fire, and it didn't burn trees...

**Comment by FaraoneLele** [comment]
I was using the permanent fire, but now I tried it with flint and steal, and does not burn the same

**Comment by FaraoneLele** [comment]
![screenshot_20160318_181009](https://cloud.githubusercontent.com/assets/17162630/13885833/aa283c74-ed34-11e5-85b9-9d195f68d6ee.png)

**Comment by FaraoneLele** [comment]
fire expands, but does not burn the block.

**Comment by C1ffisme** [comment]
Hmmm... I know fire has recently burned slower. Try burning the leaves.

**Comment by FaraoneLele** [comment]
the leaves will burn slowly, but burn

**Comment by C1ffisme** [comment]
Does the tree burn with it?

Also, try placing fire several times.

**Comment by FaraoneLele** [comment]
ok i try

**Comment by FaraoneLele** [comment]
![screenshot_20160318_181622](https://cloud.githubusercontent.com/assets/17162630/13886070/8a889d5e-ed35-11e5-879c-2ff0e5a1f70d.png)

**Comment by FaraoneLele** [comment]
ok!! he burn! but very very slowy

**Comment by C1ffisme** [comment]
Yeah, I guess it mimics real life, where logs actually take time to burn, and need kindling.

If you need more support, try the minetest forums. It's best not to ask for support here, since everyone gets an email every time we post.

**Comment by paramat** [comment]
Fire is a little slow, i might speed it up for release.

**Comment by paramat** [comment]
#956 
In testing it really isn't slow, it just inevitably starts slow because spread is inherently exponentiial, after 2-3 mins fire spread really accelerates. If it started fast then it would become too fast later on.

Anyway, because it starts so slowly, and due to popular demand, i have increased spread speed slightly in the PR.

**Comment by paramat** [comment]
956 merged
