### ISSUE TITLE
commands do not work on mac

### ISSUE THREAD

**Issue by FaraoneLele** [minetest/minetest_game#952]
the commands on Mac do not work by pressing T, after writing it, nothing happens

**Comment by FaraoneLele** [comment]
![screenshot_20160318_184957](https://cloud.githubusercontent.com/assets/17162630/13887085/38dc2408-ed3a-11e5-98ea-7b4699ac3ca7.png)

**Comment by PilzAdam** [comment]
This is an engine issue, please reopen here: https://github.com/minetest/minetest/issues

Before reopening, though, check if there are any spaces in front of the slash. Also try waiting a bit, the server may have multiple seconds of lag (even in singleplayer).
