### ISSUE TITLE
Flint and steel should check for neighbouring flammable nodes

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#961]
@kilbith 
Currently it can add a flame anywhere and the flame can last minutes before the fire ABM extinguishes it due to lack of surrounding flammable nodes.
Instead perhaps there should be a check for a flammable node neighbour (any srrounding node, not just below) before adding the flame.
Flint and steel provides the spark, but flammable material is needed for a flame.

**Comment by kilbith** [comment]
Yes, that might be a good idea. I'll do that.

**Comment by kilbith** [comment]
Hmm... actually the fire can't be feed for an above flammable material. Perhaps we should only consider a check from the below for simplicity and realism.

**Comment by paramat** [comment]
962 merged.
