### ISSUE TITLE
Glass Doors and Glass Doors have the same names (Duh!)

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#963]
There are two items called “Glass Door”: Glass Door and Glass Door.
Glass Door is made out of Glass, and then there is Glass Door, which is made out of Obsidian Glass.

Pretty confusing, right?
Please rename Glass Door (the obisian one) to Obsidian Glass Door.

**Comment by paramat** [comment]
:+1: Well spotted.

**Comment by paramat** [comment]
968 merged.
