### ISSUE TITLE
Bed respawn not working on server.

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest_game#979]
Running the latest daily, bed respawn works fine on singleplayer or using server tab to run your own server from client-side, but connecting to actual server then bed respawn doesn't work.  You die you respawn at spawn instead, even with the minetest.conf settings enabled.

**Comment by paramat** [comment]
@sofar any ideas?

**Comment by sofar** [comment]
Is this perhaps attempting to use a bed that inside a protected area owned by a different player?

**Comment by sofar** [comment]
Can't reproduce. Started server as ```minetestserver```. then connected a client to it. Died to verify that spawn point was in spot A, then went to spot B and placed a bed, slept in bed, and died, and spawned in spot B.

What mods are on this server? Perhaps that's a clue.

**Comment by tenplus1** [comment]
Bed was placed in an unprotected area and the only mod dealing with respawn is the default beds mod as dropondie only drops inventory on death, it doesnt deal with player locations.

**Comment by tenplus1** [comment]
Update: Tested latest build and issue still same, works on standalone server but not on actual server.

**Comment by wilkgr76** [comment]
Confirmed on MegaF's server - this occurs even if I am the only person sleeping.
