### ISSUE TITLE
[Feature Request] More informative descriptions

### ISSUE THREAD

**Issue by C1ffisme** [minetest/minetest_game#981]
I found this little hack recently...
![screenshot_20160328_110840](https://cloud.githubusercontent.com/assets/9893266/14083003/efc4a8ca-f4d8-11e5-9b74-1b0bfac941b4.png)
And I thought I might open up some discussion on making things such as...
![screenshot_20160328_113227](https://cloud.githubusercontent.com/assets/9893266/14083027/13698cf0-f4d9-11e5-84dc-66b73b94f06e.png)

#### Why would we do this?

Because it can tell you a bit more information than just a name. New players might not know that a steel sword does the same damage as a bronze sword, or that a mese sword only does 7 damage, not 8. (Which would make the diamond sword do 10.)

Thoughts?

**Comment by Calinou** [comment]
The problem of long descriptions is that their tooltips can become very obstrusive. A possible fix is to show only the first line for 1 second, then show the full description after 1 second.

**Comment by C1ffisme** [comment]
@Calinou We could do something like that... But it would require an engine change.

For the record, if you think that's obstructive...
![2016-03-28_11 56 40](https://cloud.githubusercontent.com/assets/9893266/14083600/3708477a-f4dc-11e5-970f-b409cf33c084.png)
(Note: A lot of these enchantments are ones that you don't normally get on a sword, but even with 2 or 3 of these cut off, the list is quite long.)

**Comment by sofar** [comment]
This is already a partial PR (WIP) and concept in progress in minetest_game:

https://github.com/minetest/minetest/pull/3449

**Comment by C1ffisme** [comment]
@sofar Oh... I forgot about that not being merged yet.

Can't wait for that to come, though.

(Anyway, mostly I'm just talking about using this little newline hack that I was told about.)

**Comment by sofar** [comment]
If you look closely, and follow my wishlist/worklist, then you'll see that there's a lot of work needed to make it happen:

https://forum.minetest.net/viewtopic.php?f=7&t=14229&p=212421#p212421

**Comment by paramat** [comment]
:-1: Tooltips are not the place for extra information, because everyone other than new players don't need the extra information and it will be irritating.

**Comment by C1ffisme** [comment]
@paramat This is true right now, because there isn't a lot to be written. If we add an advanced forging/enhancing/enchanting system that changes damage, attack speed, critical strike chance?/ etc., then it would be helpful to see the data.

I'm not sure why you think tooltips are the wrong place for information, since it is the same place information is kept in Terraria, Minecraft, etc. (Being a player of both of those games) It's popular game design.

**Comment by sofar** [comment]
If properly implemented, #3449 will allow mods to put *anything* in the tooltip. And it's up to mods and mod writers to use it smartly or not, minetest shouldn't necessarily obstruct them.

But, Moot discussion until code exists. It's all a pipe dream without code.

**Comment by paramat** [comment]
This might be good in special cases, but your issue here suggests adding information for many things, which is why i disapproved. Unless there is a great need for information to be quickly accessed in inventory it's better the information is elsewhere. For example in Minecraft special items with special abilities i can see the need. Almost all items and nodes do not need more information in a tooltip.

**Comment by C1ffisme** [comment]
@paramat 
> adding information for many things

Not really... I only plan on adding things for the tools. Adding `A decorative block` to almost every block in Minetest Game is a bit pointless (albeit slightly funny for a while).

**Comment by kilbith** [comment]
As the author of an  [enchanting mod](https://github.com/minetest-mods/enchanting), there's a need for my users to have more informations in tooltips and colored text as well. It's more a feature-request for the engine anyways.

I agree the default tools should not have that much infos in tooltips.

**Comment by paramat** [comment]
:-1: 
Tooltips are not the place for non-essential extra information, because everyone other than new players do not need the extra information and it will be irritating.
Your issue here suggests adding information for many things in MTGame, which is why i disapprove. Unless there is a great need for information to be quickly accessed in inventory it's better the information is elsewhere.
So fine for mods and subgames but not for MTGame.

**Comment by paramat** [comment]
However, i'm not sure what you are requesting here. Do you want extra information about MTG nodes displayed? Your example seems to suggest use in an alternative subgame or mod.

**Comment by MarkuBu** [comment]
Why it has to be a tooltip? Why not a box above or below the inventory form? This is also a common game design from much older games then Minecraft

**Comment by C1ffisme** [comment]
@MarkuBu That's a smart idea, but we don't have that feature in the inventory formspec right now.

@paramat Mostly my idea is for information on tools. It might be helpful for newer players to know how much damage a sword does, how fast a pickaxe digs, etc. 

I **don't** want a full text description for every node, I don't want this in Obsidian's description:

```
...
description = 
        "Obsidian\n
        \n
        Obsidian is a very hard\n
        rock which can only be broken\n
        by a steel pickaxe or higher. Good\n
        for fortresses and strong bases.\n",
...
```

**Comment by paramat** [comment]
As i wrote, that information may be briefy useful to a new player, but will irritate most platers most of the time, new players can refer to docs for such information, the tooltip is for information that absolutely needs to be seen quickly in the inventory.

**Comment by C1ffisme** [comment]
@paramat Truth is, I'm sure most people will look at a brick block in the inventory, and suppose that it is a brick block. But you don't see us stuffing that in some documentation file because it could be 'annoying' to people who already know what it is.

Even then, I don't think we have any documentation for Minetest Game, in-game or otherwise (Other than API features, of course.).

**Comment by paramat** [comment]
Erm, the node name is essential information, that's why it's displayed in the tooltip.

**Comment by DonBatman** [comment]
imho more informative descriptions are not needed. If mods do need to add more they can.
If people think it would be good for beginners the I suggest making a helper mod that overrides the item description. Then new players could activate the mod and get more information. When they are comfortable with the items they can disable the mod and play with just names for tooltips.

**Comment by C1ffisme** [comment]
@paramat Is it? For a newbie, but for any veteran of Minetest Game, you can very easily see what a node is. 

@DonBatman What do you do when you forget what damage a weapon does and you need to find out real quick? Do you have to turn on a setting for only a few seconds just to do so?

**Comment by DonBatman** [comment]
@C1ffisme to be honest I don't think I have ever needed to know the damage of a weapon. I can understand how you might want it in pvp servers though. Even then if you make a mod that overrides the weapons description you can have that info.

**Comment by paramat** [comment]
It's common for mods to have differing nodes with identical or very similar textures. The node name is the 'unique identifier' not the textures used, so the nodename is essential information to know for sure what a node is. In MTGame itself no more information is needed.

This arguing is a waste of time, this is not going to happen, so closing.

**Comment by C1ffisme** [comment]
@paramat Eh, it can wait until MTG actually has something worth explaining to people.
