### ISSUE TITLE
boat model contains 1700+ tris

### ISSUE THREAD

**Issue by sofar** [minetest/minetest_game#985]
The current boat model contains 1700+ triangles, which is unneeded and unnecessarily heavy on the rendering engine for no reason.

I've already cleaned up the mesh to ~80 tris, and started re-UV unwrapping the mesh (as you can imagine 1700 tris uvmapped is no particular fun weekend project), but I just need to finish it.

I'm opening this as an issue to try and fix this before 0.4.14. Given the high amount of tris this should be worth including in 0.4.14.

**Comment by PilzAdam** [comment]
If you are already on it: can you make the wood texture less stretched out?

**Comment by sofar** [comment]
yes, I'm rewrapping it so that it looks nice. I'll even try to make pixels show up in the correct size as compared to pixels on wooden nodes.

**Comment by sofar** [comment]
#990

**Comment by DonBatman** [comment]
Nice work sofar :+1:

**Comment by paramat** [comment]
So far, so good.

**Comment by paramat** [comment]
#990 merged.
