### ISSUE TITLE
XPanes are no propagating sunlight

### ISSUE THREAD

**Issue by everamzah** [minetest/minetest_game#987]
@sofar @paramat 

Though they are defined to do so, individual xpane panes (pane_n) nodes are no propagating sunlight.

![screenshot_20160329_204601](https://cloud.githubusercontent.com/assets/1761623/14128516/70a420ee-f5ef-11e5-989c-59569eeeaad0.png)

**Comment by sofar** [comment]
This is without the xpanes PR, so it has nothing to do with XPanes.

**Comment by sofar** [comment]
Also, it may be drawn slightly darker, but I still get a param1 = 15 value everywhere.

**Comment by Fixer-007** [comment]
Can confirm this with "Smooth Lighting" off

**Comment by DonBatman** [comment]
Isn't this the nodebox lighting issue? this happens with all nodeboxes.

**Comment by PilzAdam** [comment]
@DonBatman no, it isn't. The issue you are talking about is not darkening the nodes below the nodebox.

**Comment by paramat** [comment]
Possibly an engine issue.

**Comment by everamzah** [comment]
This can be fixed easily by adding sunlight_propagates = true to this section: https://github.com/minetest/minetest_game/blob/master/mods/xpanes/init.lua#L125 -- though I doubt this is a proper solution.

**Comment by sofar** [comment]
The new Xpanes PR has ```sunlight_propagates = true```. We could just merge that :D

**Comment by paramat** [comment]
They are already, see line 80.

**Comment by paramat** [comment]
Seems to be an engine issue so please open an issue there.

**Comment by paramat** [comment]
> This can be fixed easily by adding sunlight_propagates = true

They have that property already.

**Comment by everamzah** [comment]
I think there's 15 nodes defined for each pane registered with xpanes mod.  Only one of them is propagating sunlight, for whatever reason the others aren't.  I guess they're supposed to inherit the value of the original def, but they don't.  Regardless, adding `sunlight_propagates = true,` to line 125 does indeed resolve the issue.

Why it doesn't work like you'd think it should by reading the code, I have no clue.  This was some time ago, and I was equally puzzled.

**Comment by paramat** [comment]
I see.
