### ISSUE TITLE
Opening a door with a bed removes adjacent node

### ISSUE THREAD

**Issue by everamzah** [minetest/minetest_game#991]
Using stock minetest and minetest_game.  @sofar @paramat 

![screenshot_20160330_214242](https://cloud.githubusercontent.com/assets/1761623/14163138/63aa399c-f6c0-11e5-9568-d34a0e672750.png)

https://www.youtube.com/watch?v=Cr8VfGkSQ6Y

**Comment by sofar** [comment]
Fixed by #994
