### ISSUE TITLE
There's no way to add specular maps to texture packs 

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest_game#992]
There's no way to add specular maps to texture packs this probably isn't a bug but it should still be added   I really wanted this (NOTE) i also love the bumpmapping that is the reason why I want this

**Comment by paramat** [comment]
More of an engine issue, it needs to be supported in the engine before we support them in MTGame.

**Comment by tobyplowy** [comment]
paramat if it is supported by the developers will it be addit?
