### ISSUE TITLE
New obsidian texture

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest_game#993]
I think the obsidian texture looks a bit boring. Maby It could look a bit more colorful?

**Comment by Gael-de-Sailly** [comment]
![Real obsidian](http://rockhoundblog.com/wp-content/uploads/2006/11/obsidian.jpg)
The (real) obsidian is a strange vitreous stone, that has nothing to do with cobble stone. It just looks like black glass. But a more realistic texture would be a unified color, that would be even more boring. I like the current one.

**Comment by kilbith** [comment]
PixelBOX vs. MTG : 

![capture d ecran de 2016-03-31 16-43-33](https://cloud.githubusercontent.com/assets/7883281/14179680/442b4ac0-f760-11e5-8b4f-99ff6222dd58.png) ![default_obsidian](https://cloud.githubusercontent.com/assets/7883281/14179704/649255ce-f760-11e5-9858-55ebabf3b27b.png)
  ![capture d ecran de 2016-03-31 16-44-32](https://cloud.githubusercontent.com/assets/7883281/14179683/4889bcfa-f760-11e5-8f41-cc731af8bd6e.png)

**Comment by tobyplowy** [comment]
Yeah that looks somewhat better. But Maybe decrease The brightness of the brightest color Just A Little Bit and maybe also add some bigger stones

**Comment by Napiophelios** [comment]
I personally like the current texture.
I think any change to it would be a mistake.

**Comment by Gael-de-Sailly** [comment]
I'm neutral. That's interesting, but that don't really represents the obsidian.

**Comment by tobyplowy** [comment]
Maybe it could be an edit of the original obsidian but with more color variation?

**Comment by Gael-de-Sailly** [comment]
Yes, that could be better.

**Comment by tobyplowy** [comment]
Gael-de-Sailly maybe you could try making a texture?

**Comment by paramat** [comment]
:-1: I like the current one, the pixelbox one is too cobbly. It needs to be super dark and smooth.

**Comment by tobyplowy** [comment]
Hey maby you got trye makeing One smooth but with some color

**Comment by Fixer-007** [comment]
I like current one

**Comment by DonBatman** [comment]
I like the current one too

**Comment by C1ffisme** [comment]
Eh... I like the current one. It's not the best, but it doesn't make sense that cobblestone is blast-proof.

**Comment by paramat** [comment]
Dark with just a slight hint of colour is needed, so the current one is good.

**Comment by paramat** [comment]
Closing as most are happy with the current one.
