### ISSUE TITLE
Water and lava should go through non solid blocks like fences and iron bars

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest_game#996]
Basically Everything that real Water should be able to pass truh :P

**Comment by tenplus1** [comment]
If lava is near a wooden fence then the fence will eventually catch fire and burn up, same with iron bars if the melty group is set then the on_burn call can remove it.

**Comment by tobyplowy** [comment]
#tenplus1 Yes I know but it Still be possible bdw you still have water water doesn't burn stuff

**Comment by C1ffisme** [comment]
Have you tried that in Minecraft?

Yeah, it doesn't work.
![2016-04-01_11 43 37](https://cloud.githubusercontent.com/assets/9893266/14213707/0f8a00fa-f7ff-11e5-8b78-890532221882.png)

If we added every feature from Real Life... This game wouldn't be a very good game.

Gameplay > Realism.

**Comment by paramat** [comment]
Fences and iron bars are nodes, so act as solid to liquids.
You canmake a node destroyed by liquid with 'floodable = true'.

**Comment by C1ffisme** [comment]
And from now on... Please ask questions like these in the [forum](https://forum.minetest.net/).

(Github is for bugs, development, and some feature requests! [And, not even that last one, really.])
