### ISSUE TITLE
dirt should turn to dry grass in savannahs

### ISSUE THREAD

**Issue by sofar** [minetest/minetest_game#998]
This is a trivial tweak I think. The ABM that turns dirt into grass needs to take the surroundings into account.

(as a side node, if temp/humidity noise would be known at this point, it could use that)

**Comment by paramat** [comment]
I realised this problem a while ago but decided against a fix because at the time that ABM was very intensive already. Now we are using 'neighbors = air' it can be more complex.

**Comment by 0-afflatus** [comment]
Please lose the apostrophe in the title. The plural of savannah is savannahs.

**Comment by paramat** [comment]
999 is merged.
